/****** Object:  StoredProcedure [dbo].[ANA_LIS_TROVA_CONTRATTI_NON_ABBINATI]    Script Date: 11/17/2025 15:18:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_LIS_TROVA_CONTRATTI_NON_ABBINATI]

@DATAINIZIORICERCA	CHAR(8),
@DATAFINERICERCA	CHAR(8),
@CATEGORIA		CHAR(2),
@SERVIZIO		CHAR(2),
@ATTIVITA		CHAR(2),
@NOMEDOC		VARCHAR(20)

AS

DECLARE	


@SQL			VARCHAR(5000),
@MSG			VARCHAR(255)

--*********************** ADESIONE ******************************
IF @NOMEDOC = 'ADE'  
BEGIN
	SELECT @SQL = 'SELECT "ADE" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRADE_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRADE_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRADE_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRADE_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRADE_LIS_NOME AS NOME_CONTRAENTE , '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' "" AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRADE_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRADE_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRADE_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRADE_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRADE_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRADE_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" '
	SELECT @SQL = @SQL + '  AND LSRADE_LIS_FLAG_ANAG = "0" ORDER BY 2'
END

--*********************** AUTORIZZAZIONE SQUADRA ******************************
IF @NOMEDOC = 'AUT'  
BEGIN
	SELECT @SQL = 'SELECT "AUT" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRAUT_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRAUT_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRAUT_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRAUT_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRAUT_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' "" AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRAUT_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRAUT_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRAUT_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRAUT_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRAUT_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRAUT_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" '
	SELECT @SQL = @SQL + '  AND LSRAUT_LIS_FLAG_ANAG = "0" ORDER BY 2'
END


--*********************** CONTRATTO QUADRO ******************************
IF @NOMEDOC = 'CON'  
BEGIN
	SELECT @SQL = 'SELECT "CON" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRCON_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRCON_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRCON_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRCON_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRCON_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' "" AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRCON_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRCON_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRCON_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + '  AND LSRCON_LIS_FLAG_ANAG = "0" ORDER BY 2'
END

--*********************** FIDEJUSSIONE ******************************
IF @NOMEDOC = 'FID'  
BEGIN
	SELECT @SQL = 'SELECT "FID" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRFID_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRFID_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRFID_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRFID_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRFID_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' LSRFID_LIS_ANNO_RIF AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRFID_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRFID_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND ((LSRFID_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" ) '
	SELECT @SQL = @SQL + ' OR (LSRFID_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_ATTIVITA = "  " ) )'

	SELECT @SQL = @SQL + '  AND LSRFID_LIS_FLAG_ANAG = "0" ORDER BY 2'
END
--print @sql
--*********************** RAD ******************************
IF @NOMEDOC = 'RAD'  
BEGIN
	SELECT @SQL = 'SELECT "RAD" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRAD_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRAD_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRAD_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRAD_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_LIS_FONTE AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' "" AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRAD_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRRAD_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRRAD_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRRAD_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRRAD_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRRAD_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" '
	SELECT @SQL = @SQL + '  AND LSRRAD_LIS_FLAG_ANAG = "0" ORDER BY 2'
END


--*********************** RINUNCIA ******************************
IF @NOMEDOC = 'RIN'  
BEGIN
	SELECT @SQL = 'SELECT "RIN" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRIN_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRIN_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRIN_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRIN_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRIN_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' "" AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRIN_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRRIN_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRRIN_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRRIN_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRRIN_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRRIN_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" '
	SELECT @SQL = @SQL + '  AND LSRRIN_LIS_FLAG_ANAG = "0" ORDER BY 2'
END

--*********************** TUTTI I DOCUMENTI ******************************
IF @NOMEDOC = ''  
BEGIN
	SELECT @SQL = 'SELECT "ADE" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRADE_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRADE_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRADE_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRADE_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRADE_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' "" AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRADE_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRADE_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRADE_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRADE_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRADE_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRADE_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" '
	SELECT @SQL = @SQL + '  AND LSRADE_LIS_FLAG_ANAG = "0" '
	SELECT @SQL = @SQL + '  UNION '
	SELECT @SQL = @SQL + ' SELECT "AUT" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRAUT_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRAUT_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRAUT_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRAUT_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRAUT_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' "" AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRAUT_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRAUT_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRAUT_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRAUT_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRAUT_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRAUT_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" '
	SELECT @SQL = @SQL + '  AND LSRAUT_LIS_FLAG_ANAG = "0" '
	SELECT @SQL = @SQL + '  UNION '
	SELECT @SQL = @SQL + ' SELECT "CON" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRCON_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRCON_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRCON_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRCON_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRCON_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' "" AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRCON_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRCON_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRCON_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + '  AND LSRCON_LIS_FLAG_ANAG = "0" '
	SELECT @SQL = @SQL + '  UNION '
	SELECT @SQL = @SQL + ' SELECT "FID" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRFID_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRFID_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRFID_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRFID_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRFID_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' "" AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' LSRFID_LIS_ANNO_RIF AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRFID_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRFID_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND (  (LSRFID_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" ) '
	SELECT @SQL = @SQL + ' 	OR ( LSRFID_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRFID_LIS_KEY_ATTIVITA = "  " ) )'
	SELECT @SQL = @SQL + '  AND LSRFID_LIS_FLAG_ANAG = "0" '
	SELECT @SQL = @SQL + '  UNION '
	SELECT @SQL = @SQL + ' SELECT "RAD" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRAD_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRAD_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRAD_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRAD_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_LIS_FONTE AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' ""  AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRAD_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRRAD_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRRAD_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRRAD_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRRAD_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRRAD_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" '
	SELECT @SQL = @SQL + '  AND LSRRAD_LIS_FLAG_ANAG = "0" '
	SELECT @SQL = @SQL + '  UNION '
	SELECT @SQL = @SQL + ' SELECT "RIN" AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRIN_LIS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRIN_LIS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRIN_LIS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRIN_LIS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRIN_LIS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' ""  AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' ""  AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRIN_LIS '
	SELECT @SQL = @SQL + ' WHERE LSRRIN_LIS_KEY_DATA_INS >= "' + @DATAINIZIORICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRRIN_LIS_KEY_DATA_INS <= "' + @DATAFINERICERCA + '" '
	SELECT @SQL = @SQL + ' AND LSRRIN_LIS_KEY_CATEGORIA = "' + @CATEGORIA + '" '
	SELECT @SQL = @SQL + ' AND LSRRIN_LIS_KEY_SERVIZIO = "' + @SERVIZIO + '" '
	SELECT @SQL = @SQL + ' AND LSRRIN_LIS_KEY_ATTIVITA = "' + @ATTIVITA + '" '
	SELECT @SQL = @SQL + '  AND LSRRIN_LIS_FLAG_ANAG = "0" '
	SELECT @SQL = @SQL + ' ORDER BY 1,2 '

END


EXECUTE (@SQL)
GO
