/****** Object:  StoredProcedure [dbo].[ANA_CONI_TROVA_CONTRATTI_NON_ABBINATI]    Script Date: 11/17/2025 15:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[ANA_CONI_TROVA_CONTRATTI_NON_ABBINATI]

@DATAINIZIORICERCA	CHAR(8),
@DATAFINERICERCA	CHAR(8),
@NOMEDOC		VARCHAR(20)

AS

DECLARE	
 

@SQL			VARCHAR(8000),
@MSG			VARCHAR(255)

--*********************** QUESTIONARIO ******************************
IF @NOMEDOC = 'QST'  
BEGIN
	SELECT @SQL = 'SELECT ''QST'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRQST_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRQST_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRQST_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRQST_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRQST_CONI_NOME AS NOME_CONTRAENTE , '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRQST_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRQST_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRQST_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRQST_CONI_FLAG_ANAG = ''0'' ORDER BY 2'
END

--*********************** NULLA OSTA ******************************
IF @NOMEDOC = 'NUO'  
BEGIN
	SELECT @SQL = 'SELECT ''NUO'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRNUO_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRNUO_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRNUO_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRNUO_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRNUO_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRNUO_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRNUO_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRNUO_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRNUO_CONI_FLAG_ANAG = ''0'' ORDER BY 2'
END


--*********************** CONTRATTO ******************************
IF @NOMEDOC = 'CON'  
BEGIN
	SELECT @SQL = 'SELECT ''CON'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRCON_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRCON_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRCON_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRCON_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRCON_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRCON_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRCON_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRCON_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRCON_CONI_FLAG_ANAG = ''0'' ORDER BY 2'
END

--*********************** CONTRATTO GIOCHI PUBBLCII******************************
IF @NOMEDOC = 'CGP'  
BEGIN
	SELECT @SQL = 'SELECT ''CGP'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' lsrcon_gp_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'lsrcon_gp_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'lsrcon_gp_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' lsrcon_gp_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' lsrcon_gp_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM lsrcon_gp '
	SELECT @SQL = @SQL + ' WHERE lsrcon_gp_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND lsrcon_gp_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND lsrcon_gp_FLAG_ANAG = ''0'' ORDER BY 2'
END


--*********************** TULPS ******************************


IF @NOMEDOC = 'TLP'  
BEGIN
	SELECT @SQL = 'SELECT ''TLP'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRTLP_ST_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRTLP_ST_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRTLP_ST_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRTLP_ST_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRTLP_ST_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRTLP_ST '
	SELECT @SQL = @SQL + ' WHERE LSRTLP_ST_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRTLP_ST_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRTLP_ST_FLAG_ANAG = ''0'' ORDER BY 2'
END



--*********************** FIDEJUSSIONE ******************************
IF @NOMEDOC = 'FID'  
BEGIN
	SELECT @SQL = 'SELECT ''FID'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRFID_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRFID_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRFID_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRFID_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRFID_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' LSRFID_CONI_ANNO_RIF AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRFID_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRFID_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRFID_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRFID_CONI_FLAG_ANAG = ''0'' ORDER BY 2'
END

--*********************** RAD ******************************
IF @NOMEDOC = 'RAD'  
BEGIN
	SELECT @SQL = 'SELECT ''RAD'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRAD_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRAD_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRAD_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRAD_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_CONI_FONTE AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRAD_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRRAD_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRAD_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRRAD_CONI_FLAG_ANAG = ''0'' ORDER BY 2'
END

--*********************** RAD ST ******************************
IF @NOMEDOC = 'RST'  
BEGIN
	SELECT @SQL = 'SELECT ''RST'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRAD_ST_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRAD_ST_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRAD_ST_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRAD_ST_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_ST_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_ST_FONTE AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRAD_ST '
	SELECT @SQL = @SQL + ' WHERE LSRRAD_ST_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRAD_ST_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRRAD_ST_FLAG_ANAG = ''0'' ORDER BY 2'
END


--*********************** RINUNCIA ******************************
IF @NOMEDOC = 'RIN'  
BEGIN
	SELECT @SQL = 'SELECT ''RIN'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRIN_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRIN_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRIN_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRRIN_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRIN_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRIN_CONI_CODICE_SERVIZIO = ''11'''
	SELECT @SQL = @SQL + '  AND LSRRIN_CONI_FLAG_ANAG = ''0'' ORDER BY 2'
END


--************* CONTRATTO SCOMMESSE IPPICHE ********
IF @NOMEDOC = 'COS'  
BEGIN
	SELECT @SQL = 'SELECT ''COS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRCON_GS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRCON_GS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRCON_GS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRCON_GS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRCON_GS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRCON_GS '
	SELECT @SQL = @SQL + ' WHERE LSRCON_GS_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRCON_GS_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRCON_GS_CODICE_SERVIZIO = ''08'' '
	SELECT @SQL = @SQL + '  AND LSRCON_GS_FLAG_ANAG = ''0'' ORDER BY 2'
END


--************* NULLA OSTA SCOMMESSE  IPPICHE ********
IF @NOMEDOC = 'NUS'  
BEGIN
	SELECT @SQL = 'SELECT ''NUS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRNUO_GS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRNUO_GS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRNUO_GS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRNUO_GS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRNUO_GS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRNUO_GS '
	SELECT @SQL = @SQL + ' WHERE LSRNUO_GS_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRNUO_GS_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRNUO_GS_CODICE_SERVIZIO = ''08'' '
	SELECT @SQL = @SQL + '  AND LSRNUO_GS_FLAG_ANAG = ''0'' ORDER BY 2'
END

--************* RAD SCOMMESSE  IPPICHE ********
IF @NOMEDOC = 'RAS'  
BEGIN
	SELECT @SQL = 'SELECT ''RAS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRAD_GS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRAD_GS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRAD_GS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRAD_GS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_GS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRAD_GS '
	SELECT @SQL = @SQL + ' WHERE LSRRAD_GS_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRAD_GS_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRAD_GS_CODICE_SERVIZIO = ''08'' '
	SELECT @SQL = @SQL + '  AND LSRRAD_GS_FLAG_ANAG = ''0'' ORDER BY 2'
END


--************* RINUNCIA SCOMMESSE  IPPICHE ********
IF @NOMEDOC = 'RIS'  
BEGIN
	SELECT @SQL = 'SELECT ''RIS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRIN_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRIN_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRIN_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRRIN_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRIN_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRIN_CONI_CODICE_SERVIZIO = ''08'''
	SELECT @SQL = @SQL + '  AND LSRRIN_CONI_FLAG_ANAG = ''0'' ORDER BY 2'
END


--************* RINUNCIA SCOMMESSE  IPPICHE ********

IF @NOMEDOC = 'TLS'  
BEGIN
	SELECT @SQL = 'SELECT ''TLS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRTLP_GS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRTLP_GS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRTLP_GS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRTLP_GS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRTLP_GS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRTLP_GS '
	SELECT @SQL = @SQL + ' WHERE LSRTLP_GS_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRTLP_GS_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRTLP_GS_CODICE_SERVIZIO = ''08'' '
	SELECT @SQL = @SQL + '  AND LSRTLP_GS_FLAG_ANAG = ''0'' ORDER BY 2'
END

--*********************** TUTTI I DOCUMENTI ******************************
IF @NOMEDOC = ''  
BEGIN
	SELECT @SQL = 'SELECT ''QST'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRQST_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRQST_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRQST_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRQST_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRQST_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRQST_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRQST_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRQST_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRQST_CONI_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''NUO'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRNUO_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRNUO_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRNUO_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRNUO_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRNUO_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRNUO_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRNUO_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRNUO_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRNUO_CONI_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''CON'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRCON_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRCON_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRCON_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRCON_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRCON_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRCON_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRCON_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRCON_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRCON_CONI_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''CGP'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' lsrcon_gp_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'lsrcon_gp_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'lsrcon_gp_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' lsrcon_gp_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' lsrcon_gp_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM lsrcon_gp '
	SELECT @SQL = @SQL + ' WHERE lsrcon_gp_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND lsrcon_gp_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND lsrcon_gp_FLAG_ANAG = ''0'' '
	
	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''TLP'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRTLP_ST_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRTLP_ST_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRTLP_ST_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRTLP_ST_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRTLP_ST_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRTLP_ST '
	SELECT @SQL = @SQL + ' WHERE LSRTLP_ST_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRTLP_ST_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRTLP_ST_FLAG_ANAG = ''0'''

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''FID'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRFID_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRFID_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRFID_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRFID_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRFID_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' LSRFID_CONI_ANNO_RIF AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRFID_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRFID_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRFID_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRFID_CONI_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''RAD'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRAD_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRAD_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRAD_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRAD_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_CONI_FONTE AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' ''''  AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRAD_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRRAD_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRAD_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRRAD_CONI_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''RST'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRAD_ST_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRAD_ST_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRAD_ST_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRAD_ST_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_ST_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_ST_FONTE AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRAD_ST '
	SELECT @SQL = @SQL + ' WHERE LSRRAD_ST_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRAD_ST_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRRAD_ST_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''RIN'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRIN_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRIN_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' ''''  AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' ''''  AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRIN_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRRIN_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRIN_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRRIN_CONI_FLAG_ANAG = ''0'' '
	SELECT @SQL = @SQL + '  AND LSRRIN_CONI_CODICE_SERVIZIO = ''11'''

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''COS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRCON_GS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRCON_GS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRCON_GS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRCON_GS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRCON_GS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRCON_GS '
	SELECT @SQL = @SQL + ' WHERE LSRCON_GS_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRCON_GS_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRCON_GS_CODICE_SERVIZIO = ''08'' '
	SELECT @SQL = @SQL + '  AND LSRCON_GS_FLAG_ANAG = ''0'''

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''NUS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRNUO_GS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRNUO_GS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRNUO_GS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRNUO_GS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRNUO_GS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRNUO_GS '
	SELECT @SQL = @SQL + ' WHERE LSRNUO_GS_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRNUO_GS_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRNUO_GS_CODICE_SERVIZIO = ''08'' '
	SELECT @SQL = @SQL + '  AND LSRNUO_GS_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL +'  SELECT ''RAS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRAD_GS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRAD_GS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRAD_GS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRAD_GS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRAD_GS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRAD_GS '
	SELECT @SQL = @SQL + ' WHERE LSRRAD_GS_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRAD_GS_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRAD_GS_CODICE_SERVIZIO = ''08'' '
	SELECT @SQL = @SQL + '  AND LSRRAD_GS_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL + ' SELECT ''RIN'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRRIN_CONI_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRRIN_CONI_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRRIN_CONI_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' ''''  AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' ''''  AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRRIN_CONI '
	SELECT @SQL = @SQL + ' WHERE LSRRIN_CONI_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRRIN_CONI_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + '  AND LSRRIN_CONI_FLAG_ANAG = ''0'' '
	SELECT @SQL = @SQL + '  AND LSRRIN_CONI_CODICE_SERVIZIO = ''11'''

	SELECT @SQL = @SQL + '  UNION '

	SELECT @SQL = @SQL +' SELECT ''TLS'' AS TIPO_DOCUMENTO, '
	SELECT @SQL = @SQL + ' LSRTLP_GS_KEY_ID_RICEV AS RICEV,'
	SELECT @SQL = @SQL +  'LSRTLP_GS_KEY_DATA_INS AS DATA_INS, '
	SELECT @SQL = @SQL +  'LSRTLP_GS_KEY_ORA_INS AS ORA_INS, '
	SELECT @SQL = @SQL + ' LSRTLP_GS_COGNOME AS COGNOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' LSRTLP_GS_NOME AS NOME_CONTRAENTE, '
	SELECT @SQL = @SQL + ' '''' AS PROVENIENZA, '
	SELECT @SQL = @SQL + ' '''' AS ANNO_RIF '
	SELECT @SQL = @SQL + ' FROM LSRTLP_GS '
	SELECT @SQL = @SQL + ' WHERE LSRTLP_GS_KEY_DATA_INS >= ''' + @DATAINIZIORICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRTLP_GS_KEY_DATA_INS <= ''' + @DATAFINERICERCA + ''' '
	SELECT @SQL = @SQL + ' AND LSRTLP_GS_CODICE_SERVIZIO = ''08'' '
	SELECT @SQL = @SQL + '  AND LSRTLP_GS_FLAG_ANAG = ''0'' '

	SELECT @SQL = @SQL + ' ORDER BY 1,2 '


END

--print @SQL
EXECUTE (@SQL)
GO
