/****** Object:  StoredProcedure [dbo].[ANADLL_ESEGUI_QUERY]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANADLL_ESEGUI_QUERY]  
			@QUERYSQL 			VARCHAR(2500)

AS

EXECUTE (@QUERYSQL)
GO
