/****** Object:  StoredProcedure [dbo].[ANA_TROVA_PROVVEDIMENTI]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_TROVA_PROVVEDIMENTI]
 
@CODLTM	 	CHAR(6),
@DATADECOR		CHAR(8),
@TIPOPROVV		VARCHAR(5),
@PERIODOPROVV	CHAR(1)

AS

DECLARE	

@TIPOCOND		VARCHAR(30),
@SQL			VARCHAR(500),
@MSG			VARCHAR(255)


IF @TIPOPROVV IS NULL
BEGIN
	SELECT @MSG = 'INDICARE IL TIPO PROVVEDIMENTO DA RICERCARE'
	RAISERROR (@MSG, 16, 1)
	RETURN
END
ELSE IF @TIPOPROVV = 'STATO'
BEGIN
	SELECT @TIPOCOND = ' IN ("A", "S", "M", "R")'
END
ELSE IF @TIPOPROVV = 'ANAG'
BEGIN
	SELECT @TIPOCOND = ' IN ("I", "E", "T")'
END
ELSE
BEGIN
	SELECT @TIPOCOND = ' IN ("' + @TIPOPROVV + '")'
END

IF @DATADECOR IS NULL
BEGIN
	SELECT @SQL = 'SELECT * FROM LSRPRO WHERE '
	SELECT @SQL = @SQL + 'LSRPRO_KEY_TIPO_REC '
	SELECT @SQL = @SQL + @TIPOCOND
	SELECT @SQL = @SQL + ' AND LSRPRO_KEY_ID_RICEV = "'
	SELECT @SQL = @SQL + @CODLTM
	SELECT @SQL = @SQL + '" AND LSRPRO_FLAG_VALIDITA = "Y"'
	SELECT @SQL = @SQL + ' AND LSRPRO_DECOR_DAL = '
	SELECT @SQL = @SQL + '('
	SELECT @SQL = @SQL +  'SELECT MAX(LSRPRO_DECOR_DAL) FROM LSRPRO WHERE '
	SELECT @SQL = @SQL + 'LSRPRO_KEY_TIPO_REC '
	SELECT @SQL = @SQL + @TIPOCOND
	SELECT @SQL = @SQL + ' AND LSRPRO_KEY_ID_RICEV = "'
	SELECT @SQL = @SQL + @CODLTM
	SELECT @SQL = @SQL + '" AND LSRPRO_FLAG_VALIDITA = "Y"'
	SELECT @SQL = @SQL + ')'

END
ELSE
BEGIN
	IF @PERIODOPROVV = 'A'	--ULTIMO PROVVEDIMENTO IN CORSO ALLA DATA @DECORDAL
	BEGIN
		SELECT @SQL = 'SELECT * FROM LSRPRO WHERE '
		SELECT @SQL = @SQL + 'LSRPRO_KEY_TIPO_REC '
		SELECT @SQL = @SQL + @TIPOCOND
		SELECT @SQL = @SQL + ' AND LSRPRO_KEY_ID_RICEV = "'
		SELECT @SQL = @SQL + @CODLTM
		SELECT @SQL = @SQL + '" AND LSRPRO_FLAG_VALIDITA = "Y"'
		SELECT @SQL = @SQL + ' AND LSRPRO_DECOR_DAL = '
		SELECT @SQL = @SQL + '('
		SELECT @SQL = @SQL +  'SELECT MAX(LSRPRO_DECOR_DAL) FROM LSRPRO WHERE '
		SELECT @SQL = @SQL + 'LSRPRO_KEY_TIPO_REC '
		SELECT @SQL = @SQL + @TIPOCOND
		SELECT @SQL = @SQL + ' AND LSRPRO_KEY_ID_RICEV = "'
		SELECT @SQL = @SQL + @CODLTM
		SELECT @SQL = @SQL + '" AND LSRPRO_FLAG_VALIDITA = "Y"'
		SELECT @SQL = @SQL + ' AND LSRPRO_DECOR_DAL <= "'
		SELECT @SQL = @SQL + @DATADECOR
		SELECT @SQL = @SQL + '")'
	END
	IF @PERIODOPROVV = 'F' 	--PROVVEDIMENTO FUTURO ALLA DATA @DECORDAL
	BEGIN
		SELECT @SQL = 'SELECT * FROM LSRPRO WHERE '
		SELECT @SQL = @SQL + 'LSRPRO_KEY_TIPO_REC '
		SELECT @SQL = @SQL + @TIPOCOND
		SELECT @SQL = @SQL + ' AND LSRPRO_KEY_ID_RICEV = "'
		SELECT @SQL = @SQL + @CODLTM
		SELECT @SQL = @SQL + '" AND LSRPRO_FLAG_VALIDITA = "Y"'
		SELECT @SQL = @SQL + ' AND LSRPRO_DECOR_DAL = '
		SELECT @SQL = @SQL + '('
		SELECT @SQL = @SQL +  'SELECT MAX(LSRPRO_DECOR_DAL) FROM LSRPRO WHERE '
		SELECT @SQL = @SQL + 'LSRPRO_KEY_TIPO_REC '
		SELECT @SQL = @SQL + @TIPOCOND
		SELECT @SQL = @SQL + ' AND LSRPRO_KEY_ID_RICEV = "'
		SELECT @SQL = @SQL + @CODLTM
		SELECT @SQL = @SQL + '" AND LSRPRO_FLAG_VALIDITA = "Y"'
		SELECT @SQL = @SQL + ' AND LSRPRO_DECOR_DAL > "'
		SELECT @SQL = @SQL + @DATADECOR
		SELECT @SQL = @SQL + '")'
	END
END

EXECUTE (@SQL)
GO
