/****** Object:  StoredProcedure [dbo].[Report_ricevitorie_e_documenti_inviati_LOTTO]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
/****** Object:  Stored Procedure dbo.Report_ricevitorie_e_documenti_inviati_LOTTO    Script Date: 16/10/2003 10.27.11 ******/
CREATE	PROCEDURE [dbo].[Report_ricevitorie_e_documenti_inviati_LOTTO] 
--	@DATA		 	CHAR(8),
	@SERVIZIO		CHAR(2),
	@CODRICEV		CHAR(6),
	@SIGLAPROV		CHAR(2),
	@COMUNE			CHAR(20),
	@REGIONE		CHAR(2),
	@RUOTA			CHAR(2),
	@STATOSERVIZIO		CHAR(2),
	@FLAG_BRIEF		CHAR(1),
	@XML 			CHAR(1),
	@ESITO 			INT OUT

AS
DECLARE  @TIPOSTATO CHAR(1)
		,@DATA 	CHAR(8) 

SELECT @ESITO = 0

--IF (@DATA IS NULL) OR (RTRIM(LTRIM(@DATA)) = '')
--BEGIN
--    SELECT @ESITO = 9
--    RAISERROR ('MANCA LA DATA',16,1)
--    RETURN @ESITO
--END

IF (@SERVIZIO IS NULL) OR (RTRIM(LTRIM(@SERVIZIO)) = '')
BEGIN
    SELECT @ESITO = 9
    RAISERROR ('MANCA IL NOME DEL SERVIZIO',16,1)
    RETURN @ESITO
END

IF (@SIGLAPROV IS NULL) OR (RTRIM(LTRIM(@SIGLAPROV)) = '')
BEGIN
    SELECT @SIGLAPROV = NULL
END
-- SE LA SIGLA DELLA PROVINCIA NON E' NULLA, 
-- METTO A NULL LA SIGLA DELLA REGIONE
ELSE
BEGIN
	SELECT @REGIONE = NULL
END

IF (@REGIONE IS NULL) OR (RTRIM(LTRIM(@REGIONE)) = '')
BEGIN
    SELECT @REGIONE = NULL
END

/**/
/**/
/**/
SELECT @ESITO = 1000
RAISERROR ('LOTTO DA DEFINIRE',16,1)
RETURN @ESITO
/**/
/**/
/**/

SET QUOTED_IDENTIFIER OFF
GO
