/****** Object:  StoredProcedure [dbo].[TITOLARE_PRECEDENTE_K]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[TITOLARE_PRECEDENTE_K] 

@RICEV		CHAR(6),
@DATARIF		CHAR(8),
@COGNOME		CHAR(25) OUTPUT,
@NOME		CHAR(25) OUTPUT,
@DATADAL		CHAR(8) OUTPUT

AS

SELECT @COGNOME = RTRIM(LTRIM(LSRTIT_COGNOME)) , 
               @NOME =  RTRIM(LTRIM(LSRTIT_NOME)),  
	  @DATADAL = LSRTIT_DATA_VALIDITA 
FROM LSRTIT
WHERE LSRTIT_KEY_ID_RICEV = @RICEV 
AND  LSRTIT_FLAG_VALIDITA = 'Y'
AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) =
(	
	SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV = @RICEV
	AND  LSRTIT_FLAG_VALIDITA = 'Y'
	AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) <
		(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)
		FROM LSRTIT
		WHERE LSRTIT_KEY_ID_RICEV = @RICEV 
		AND LSRTIT_TIPO = 'T'  
		AND  (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) <= 
			(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) FROM LSRTIT
			WHERE LSRTIT_KEY_ID_RICEV = @RICEV
			 AND LSRTIT_DATA_VALIDITA <= @DATARIF 
			AND  LSRTIT_FLAG_VALIDITA = 'Y')
		AND  LSRTIT_FLAG_VALIDITA = 'Y'
		AND  LSRTIT_TIPO_PROVV='I')
)
GO
