/****** Object:  StoredProcedure [dbo].[ANA_MOVIMENTA_RICARICHE_DA_LOTTO]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_MOVIMENTA_RICARICHE_DA_LOTTO]
 
@CODLTM		CHAR(6), 
@DATAINS		CHAR(8), 
@ORAINS		CHAR(8), 
@CATEGORIA		CHAR(2), 
@SERVIZIO		CHAR(2), 
@ATTIVITA		CHAR(2), 
@DATADECOR		CHAR(8), 
@TIPOPROVV		CHAR(1), 
@DATAPROVV		CHAR(8), 
@NUMPROVV		VARCHAR(14), 
@FIRMA		VARCHAR(17), 
@NOTE		VARCHAR(255)

AS 

DECLARE

@ASSOCIAZIONE	CHAR(1),
@STATO		CHAR(1),
@TIPOMOV		CHAR(1),
@NEWSTATO		CHAR(1),
@DATAINSLET		CHAR(8),
@ORAINSLET		CHAR(8),
@MSGERR		VARCHAR(255)



IF @TIPOPROVV IN ('A')
BEGIN
	SELECT @NEWSTATO = '1'
	SELECT @TIPOMOV = 'R'
END
ELSE IF @TIPOPROVV IN ('S', 'R', 'M')
BEGIN
	SELECT @NEWSTATO = '2'
	SELECT @TIPOMOV = 'D'
END


IF @DATAINS IS NULL OR LTRIM(RTRIM(@DATAINS )) = ''
BEGIN
	SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)

	SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
			SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
			SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
			SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)
END

SELECT @DATAINSLET = @DATAINS
SELECT @ORAINSLET = @ORAINS

IF @DATADECOR <= @DATAINS
BEGIN
	SELECT @DATADECOR = CONVERT(CHAR,GETDATE() + 1, 112)
END


IF @DATADECOR > CONVERT(CHAR, GETDATE() + 1, 112)
BEGIN
	SELECT @DATAINSLET = CONVERT(CHAR, CONVERT(DATETIME,@DATADECOR) - 1, 112)
	SELECT @ORAINSLET = '00000000'
END


SELECT @STATO = NULL
SELECT @ASSOCIAZIONE = NULL

SELECT  @STATO  = LSRSER_TEL_STATO, @ASSOCIAZIONE = LSRSER_TEL_ASSOCIAZIONE
FROM LSRSER_TEL
WHERE LSRSER_TEL_KEY_ID_RICEV = @CODLTM
AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA
AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
AND LSRSER_TEL_FLAG_VALIDITA = 'Y'
AND LSRSER_TEL_DATA_DECOR =
	(SELECT MAX(LSRSER_TEL_DATA_DECOR) 
	FROM LSRSER_TEL
	WHERE LSRSER_TEL_DATA_DECOR <= @DATAINS
	AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_TEL_FLAG_VALIDITA = 'Y'
	AND LSRSER_TEL_KEY_ID_RICEV = @CODLTM)

BEGIN TRANSACTION

IF @STATO IS NOT NULL AND LTRIM(RTRIM(@STATO)) <> ''
BEGIN
	IF @STATO <>  '0' AND @TIPOMOV = 'D'
	BEGIN
		SELECT @NOTE = 'DISATTIVAZIONE PER PROVVEDIMENTO LOTTO N° ' + LTRIM(RTRIM(@NUMPROVV)) + ' DEL ' + @DATAPROVV


		UPDATE LSRSER_TEL SET
		LSRSER_TEL_FLAG_VALIDITA = 'N'
		WHERE LSRSER_TEL_KEY_ID_RICEV = @CODLTM
		AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA
		AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
		AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
		AND LSRSER_TEL_DATA_DECOR >= @DATADECOR	


		INSERT INTO LSRSER_TEL VALUES
		(@CODLTM, @DATAINS, @ORAINS, @CATEGORIA, @SERVIZIO, @ATTIVITA, @NEWSTATO, @DATADECOR,
		@TIPOPROVV, @DATAPROVV, @NUMPROVV, @ASSOCIAZIONE, @FIRMA, @NOTE, '00000000', 'Y')
		
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRSER_TEL - RICEVITORIA ' + @CODLTM
			ROLLBACK TRANSACTION
			RAISERROR (@MSGERR, 16, 1)
			RETURN
		END


		--SE DISATTIVO E IL SERVIZIO E' ATTIVO DEVO INVIARE LA LETTERA 
		IF @STATO = '1'
		BEGIN
			INSERT INTO LSRLET_LIS VALUES
			(@CODLTM, @DATAINSLET, @ORAINSLET, @CATEGORIA, @SERVIZIO, @ATTIVITA, @TIPOMOV, @DATADECOR, 'LSRPRO',
			@DATAINS+@ORAINS, '00000000', '', @FIRMA, 'V')
	
			IF @@ERROR <> 0 
			BEGIN
				SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRLET_LIS - RICEVITORIA ' + @CODLTM
				ROLLBACK TRANSACTION
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END

			DELETE FROM LSRLET_LIS WHERE
			LSRLET_LIS_KEY_ID_RICEV = @CODLTM AND
			LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA AND
			LSRLET_LIS_KEY_SERVIZIO = @SERVIZIO AND
			LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA AND
			LSRLET_LIS_DECOR_DAL > @DATADECOR

			IF @@ERROR <> 0 
			BEGIN
				SELECT @MSGERR = 'ERRORE IN CANCELLAZIONE RECORD SU LSRLET_LIS - RICEVITORIA ' + @CODLTM
				ROLLBACK TRANSACTION
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END
		END
		ELSE
		BEGIN
			--SE DISATTIVO E IL SERVIZIO E' GIA' DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHE' IL CAMBIAMENTO DI STATO E' DOVUTO A CAMBIAMENTO DEL LOTTO
			INSERT INTO LSRLET_LIS VALUES
			(@CODLTM, @DATAINSLET, @ORAINSLET,@CATEGORIA, @SERVIZIO, @ATTIVITA, @TIPOMOV, @DATADECOR, 'LSRPRO',
			@DATAINS+@ORAINS, '19000101', '', @FIRMA, 'V')
		
			IF @@ERROR <> 0 
			BEGIN
				SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRLET_LIS - RICEVITORIA ' + @CODLTM
				ROLLBACK TRANSACTION
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END
		END
	END
END

COMMIT TRANSACTION
GO
