/****** Object:  StoredProcedure [dbo].[Seleziona_Servizi_Disattivabili_LIS]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
/****** Object:  Stored Procedure dbo.Seleziona_Servizi_Disattivabili_LIS    Script Date: 16/07/2003 11:23:29 ******/

CREATE	PROCEDURE [dbo].[Seleziona_Servizi_Disattivabili_LIS] 
	@DATA		 	CHAR(8),
	@RICEV			CHAR(6),
	@XML 			CHAR(1) = '0',
	@ESITO			INT OUT
AS

IF (@DATA IS NULL) OR (RTRIM(LTRIM(@DATA)) = '')
BEGIN
    SELECT @ESITO = 999
    RAISERROR ('VALORIZZARE IL CAMPO DATA',16,1)
    RETURN @ESITO
END

IF (@RICEV IS NULL) OR (RTRIM(LTRIM(@RICEV)) = '')
BEGIN
    SELECT @ESITO = 999
    RAISERROR ('VALORIZZARE LA RICEVITORIA',16,1)
    RETURN @ESITO
END


IF @XML = '0'
BEGIN
 SELECT  servizio = A.LSRSER_TEL_KEY_CATEGORIA + A.LSRSER_TEL_KEY_SERVIZIO + A.LSRSER_TEL_KEY_ATTIVITA,  decodifica = rtrim(ltrim(lsrser_lis_dec_nome))
 FROM LSRSER_TEL A, lsrser_lis_dec
 WHERE A.LSRSER_TEL_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_TEL_KEY_CATEGORIA + A.LSRSER_TEL_KEY_SERVIZIO + A.LSRSER_TEL_KEY_ATTIVITA
 AND A.LSRSER_TEL_STATO = '1'
 AND A.LSRSER_TEL_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_TEL_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_TEL_DATA_DECOR) 
 	FROM LSRSER_TEL B
 	WHERE B.LSRSER_TEL_KEY_ID_RICEV = A.LSRSER_TEL_KEY_ID_RICEV
 	AND B.LSRSER_TEL_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_TEL_DATA_DECOR <= @Data 
 	AND B.LSRSER_TEL_KEY_CATEGORIA + B.LSRSER_TEL_KEY_SERVIZIO + B.LSRSER_TEL_KEY_ATTIVITA =
 	    A.LSRSER_TEL_KEY_CATEGORIA + A.LSRSER_TEL_KEY_SERVIZIO + A.LSRSER_TEL_KEY_ATTIVITA)
 GROUP BY A.LSRSER_TEL_KEY_CATEGORIA + A.LSRSER_TEL_KEY_SERVIZIO + A.LSRSER_TEL_KEY_ATTIVITA, rtrim(ltrim(lsrser_lis_dec_nome))

 UNION

 SELECT  A.LSRSER_CITT_KEY_CATEGORIA + A.LSRSER_CITT_KEY_SERVIZIO + A.LSRSER_CITT_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_CITT A,   lsrser_lis_dec
 WHERE A.LSRSER_CITT_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_CITT_KEY_CATEGORIA + A.LSRSER_CITT_KEY_SERVIZIO + A.LSRSER_CITT_KEY_ATTIVITA
 AND A.LSRSER_CITT_STATO = '1'
 AND A.LSRSER_CITT_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_CITT_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_CITT_DATA_DECOR) 
 	FROM LSRSER_CITT B
 	WHERE B.LSRSER_CITT_KEY_ID_RICEV = A.LSRSER_CITT_KEY_ID_RICEV
 	AND B.LSRSER_CITT_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_CITT_DATA_DECOR <= @Data 
 	AND B.LSRSER_CITT_KEY_CATEGORIA + B.LSRSER_CITT_KEY_SERVIZIO + B.LSRSER_CITT_KEY_ATTIVITA =
 	    A.LSRSER_CITT_KEY_CATEGORIA + A.LSRSER_CITT_KEY_SERVIZIO + A.LSRSER_CITT_KEY_ATTIVITA)
 GROUP BY A.LSRSER_CITT_KEY_CATEGORIA + A.LSRSER_CITT_KEY_SERVIZIO + A.LSRSER_CITT_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome))

 UNION

 SELECT  A.LSRSER_ATTI_KEY_CATEGORIA + A.LSRSER_ATTI_KEY_SERVIZIO + A.LSRSER_ATTI_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_ATTI A,  lsrser_lis_dec
 WHERE A.LSRSER_ATTI_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_ATTI_KEY_CATEGORIA + A.LSRSER_ATTI_KEY_SERVIZIO + A.LSRSER_ATTI_KEY_ATTIVITA
 AND A.LSRSER_ATTI_STATO = '1'
 AND A.LSRSER_ATTI_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_ATTI_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_ATTI_DATA_DECOR) 
 	FROM LSRSER_ATTI B
 	WHERE B.LSRSER_ATTI_KEY_ID_RICEV = A.LSRSER_ATTI_KEY_ID_RICEV
 	AND B.LSRSER_ATTI_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_ATTI_DATA_DECOR <= @Data 
 	AND B.LSRSER_ATTI_KEY_CATEGORIA + B.LSRSER_ATTI_KEY_SERVIZIO + B.LSRSER_ATTI_KEY_ATTIVITA =
 	    A.LSRSER_ATTI_KEY_CATEGORIA + A.LSRSER_ATTI_KEY_SERVIZIO + A.LSRSER_ATTI_KEY_ATTIVITA)
 GROUP BY A.LSRSER_ATTI_KEY_CATEGORIA + A.LSRSER_ATTI_KEY_SERVIZIO + A.LSRSER_ATTI_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome))

 UNION

 SELECT  A.LSRSER_BIG_KEY_CATEGORIA + A.LSRSER_BIG_KEY_SERVIZIO + A.LSRSER_BIG_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_BIG A,  lsrser_lis_dec
 WHERE A.LSRSER_BIG_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_BIG_KEY_CATEGORIA + A.LSRSER_BIG_KEY_SERVIZIO + A.LSRSER_BIG_KEY_ATTIVITA
 AND A.LSRSER_BIG_STATO = '1'
 AND A.LSRSER_BIG_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_BIG_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_BIG_DATA_DECOR) 
 	FROM LSRSER_BIG B
 	WHERE B.LSRSER_BIG_KEY_ID_RICEV = A.LSRSER_BIG_KEY_ID_RICEV
 	AND B.LSRSER_BIG_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_BIG_DATA_DECOR <= @Data 
 	AND B.LSRSER_BIG_KEY_CATEGORIA + B.LSRSER_BIG_KEY_SERVIZIO + B.LSRSER_BIG_KEY_ATTIVITA =
 	    A.LSRSER_BIG_KEY_CATEGORIA + A.LSRSER_BIG_KEY_SERVIZIO + A.LSRSER_BIG_KEY_ATTIVITA)
 GROUP BY A.LSRSER_BIG_KEY_CATEGORIA + A.LSRSER_BIG_KEY_SERVIZIO + A.LSRSER_BIG_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome))

 UNION

 SELECT  A.LSRSER_PAG_KEY_CATEGORIA + A.LSRSER_PAG_KEY_SERVIZIO + A.LSRSER_PAG_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_PAG A,  lsrser_lis_dec
 WHERE A.LSRSER_PAG_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_PAG_KEY_CATEGORIA + A.LSRSER_PAG_KEY_SERVIZIO + A.LSRSER_PAG_KEY_ATTIVITA
 AND A.LSRSER_PAG_STATO = '1'
 AND A.LSRSER_PAG_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_PAG_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_PAG_DATA_DECOR) 
 	FROM LSRSER_PAG B
 	WHERE B.LSRSER_PAG_KEY_ID_RICEV = A.LSRSER_PAG_KEY_ID_RICEV
 	AND B.LSRSER_PAG_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_PAG_DATA_DECOR <= @Data 
 	AND B.LSRSER_PAG_KEY_CATEGORIA + B.LSRSER_PAG_KEY_SERVIZIO + B.LSRSER_PAG_KEY_ATTIVITA =
 	    A.LSRSER_PAG_KEY_CATEGORIA + A.LSRSER_PAG_KEY_SERVIZIO + A.LSRSER_PAG_KEY_ATTIVITA)
 GROUP BY A.LSRSER_PAG_KEY_CATEGORIA + A.LSRSER_PAG_KEY_SERVIZIO + A.LSRSER_PAG_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome))
 ORDER BY  1


END
ELSE
BEGIN



 SELECT  servizio = A.LSRSER_TEL_KEY_CATEGORIA + A.LSRSER_TEL_KEY_SERVIZIO + A.LSRSER_TEL_KEY_ATTIVITA,  decodifica = rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_TEL A, lsrser_lis_dec
 WHERE A.LSRSER_TEL_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_TEL_KEY_CATEGORIA + A.LSRSER_TEL_KEY_SERVIZIO + A.LSRSER_TEL_KEY_ATTIVITA
 AND A.LSRSER_TEL_STATO = '1'
 AND A.LSRSER_TEL_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_TEL_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_TEL_DATA_DECOR) 
 	FROM LSRSER_TEL B
 	WHERE B.LSRSER_TEL_KEY_ID_RICEV = A.LSRSER_TEL_KEY_ID_RICEV
 	AND B.LSRSER_TEL_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_TEL_DATA_DECOR <= @Data 
 	AND B.LSRSER_TEL_KEY_CATEGORIA + B.LSRSER_TEL_KEY_SERVIZIO + B.LSRSER_TEL_KEY_ATTIVITA =
 	    A.LSRSER_TEL_KEY_CATEGORIA + A.LSRSER_TEL_KEY_SERVIZIO + A.LSRSER_TEL_KEY_ATTIVITA)
 GROUP BY A.LSRSER_TEL_KEY_CATEGORIA + A.LSRSER_TEL_KEY_SERVIZIO + A.LSRSER_TEL_KEY_ATTIVITA, rtrim(ltrim(lsrser_lis_dec_nome))

 UNION

 SELECT  A.LSRSER_CITT_KEY_CATEGORIA + A.LSRSER_CITT_KEY_SERVIZIO + A.LSRSER_CITT_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_CITT A,   lsrser_lis_dec
 WHERE A.LSRSER_CITT_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_CITT_KEY_CATEGORIA + A.LSRSER_CITT_KEY_SERVIZIO + A.LSRSER_CITT_KEY_ATTIVITA
 AND A.LSRSER_CITT_STATO = '1'
 AND A.LSRSER_CITT_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_CITT_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_CITT_DATA_DECOR) 
 	FROM LSRSER_CITT B
 	WHERE B.LSRSER_CITT_KEY_ID_RICEV = A.LSRSER_CITT_KEY_ID_RICEV
 	AND B.LSRSER_CITT_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_CITT_DATA_DECOR <= @Data 
 	AND B.LSRSER_CITT_KEY_CATEGORIA + B.LSRSER_CITT_KEY_SERVIZIO + B.LSRSER_CITT_KEY_ATTIVITA =
 	    A.LSRSER_CITT_KEY_CATEGORIA + A.LSRSER_CITT_KEY_SERVIZIO + A.LSRSER_CITT_KEY_ATTIVITA)
 GROUP BY A.LSRSER_CITT_KEY_CATEGORIA + A.LSRSER_CITT_KEY_SERVIZIO + A.LSRSER_CITT_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome))

 UNION

 SELECT  A.LSRSER_ATTI_KEY_CATEGORIA + A.LSRSER_ATTI_KEY_SERVIZIO + A.LSRSER_ATTI_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_ATTI A,  lsrser_lis_dec
 WHERE A.LSRSER_ATTI_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_ATTI_KEY_CATEGORIA + A.LSRSER_ATTI_KEY_SERVIZIO + A.LSRSER_ATTI_KEY_ATTIVITA
 AND A.LSRSER_ATTI_STATO = '1'
 AND A.LSRSER_ATTI_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_ATTI_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_ATTI_DATA_DECOR) 
 	FROM LSRSER_ATTI B
 	WHERE B.LSRSER_ATTI_KEY_ID_RICEV = A.LSRSER_ATTI_KEY_ID_RICEV
 	AND B.LSRSER_ATTI_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_ATTI_DATA_DECOR <= @Data 
 	AND B.LSRSER_ATTI_KEY_CATEGORIA + B.LSRSER_ATTI_KEY_SERVIZIO + B.LSRSER_ATTI_KEY_ATTIVITA =
 	    A.LSRSER_ATTI_KEY_CATEGORIA + A.LSRSER_ATTI_KEY_SERVIZIO + A.LSRSER_ATTI_KEY_ATTIVITA)
 GROUP BY A.LSRSER_ATTI_KEY_CATEGORIA + A.LSRSER_ATTI_KEY_SERVIZIO + A.LSRSER_ATTI_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome))

 UNION

 SELECT  A.LSRSER_BIG_KEY_CATEGORIA + A.LSRSER_BIG_KEY_SERVIZIO + A.LSRSER_BIG_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_BIG A,  lsrser_lis_dec
 WHERE A.LSRSER_BIG_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_BIG_KEY_CATEGORIA + A.LSRSER_BIG_KEY_SERVIZIO + A.LSRSER_BIG_KEY_ATTIVITA
 AND A.LSRSER_BIG_STATO = '1'
 AND A.LSRSER_BIG_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_BIG_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_BIG_DATA_DECOR) 
 	FROM LSRSER_BIG B
 	WHERE B.LSRSER_BIG_KEY_ID_RICEV = A.LSRSER_BIG_KEY_ID_RICEV
 	AND B.LSRSER_BIG_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_BIG_DATA_DECOR <= @Data 
 	AND B.LSRSER_BIG_KEY_CATEGORIA + B.LSRSER_BIG_KEY_SERVIZIO + B.LSRSER_BIG_KEY_ATTIVITA =
 	    A.LSRSER_BIG_KEY_CATEGORIA + A.LSRSER_BIG_KEY_SERVIZIO + A.LSRSER_BIG_KEY_ATTIVITA)
 GROUP BY A.LSRSER_BIG_KEY_CATEGORIA + A.LSRSER_BIG_KEY_SERVIZIO + A.LSRSER_BIG_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome))

 UNION

 SELECT  A.LSRSER_PAG_KEY_CATEGORIA + A.LSRSER_PAG_KEY_SERVIZIO + A.LSRSER_PAG_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome)) 
 FROM LSRSER_PAG A,  lsrser_lis_dec
 WHERE A.LSRSER_PAG_FLAG_VALIDITA = 'Y'
 AND lsrser_lis_dec_CATEGORIA + lsrser_lis_dec_SERVIZIO + lsrser_lis_dec_ATTIVITA =
 	  A.LSRSER_PAG_KEY_CATEGORIA + A.LSRSER_PAG_KEY_SERVIZIO + A.LSRSER_PAG_KEY_ATTIVITA
 AND A.LSRSER_PAG_STATO = '1'
 AND A.LSRSER_PAG_KEY_ID_RICEV = @Ricev 
 AND A.LSRSER_PAG_DATA_DECOR =
 	(SELECT MAX(B.LSRSER_PAG_DATA_DECOR) 
 	FROM LSRSER_PAG B
 	WHERE B.LSRSER_PAG_KEY_ID_RICEV = A.LSRSER_PAG_KEY_ID_RICEV
 	AND B.LSRSER_PAG_FLAG_VALIDITA = 'Y'
 	AND B.LSRSER_PAG_DATA_DECOR <= @Data 
 	AND B.LSRSER_PAG_KEY_CATEGORIA + B.LSRSER_PAG_KEY_SERVIZIO + B.LSRSER_PAG_KEY_ATTIVITA =
 	    A.LSRSER_PAG_KEY_CATEGORIA + A.LSRSER_PAG_KEY_SERVIZIO + A.LSRSER_PAG_KEY_ATTIVITA)
 GROUP BY A.LSRSER_PAG_KEY_CATEGORIA + A.LSRSER_PAG_KEY_SERVIZIO + A.LSRSER_PAG_KEY_ATTIVITA,  rtrim(ltrim(lsrser_lis_dec_nome))
 ORDER BY  1
 FOR XML RAW

END

SET QUOTED_IDENTIFIER OFF
GO
