/****** Object:  StoredProcedure [dbo].[ACQUISIZIONE_RINUNCIA_LIS]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ACQUISIZIONE_RINUNCIA_LIS]


	@RICEV 			CHAR(6),
	@CATEGORIA			CHAR(2),
	@SERVIZIO			CHAR(2),
	@ATTIVITA			CHAR(2),
	@NOMEFILE			VARCHAR(255),
	@DATAINVIODOC		CHAR(8),
	@DATADOC			CHAR(8),
	@NUMPROTDOC		CHAR(25),
	@STATODOC			CHAR(1),
	@ASSOCIAZIONE		CHAR(1),
	@DATARINUNCIA		CHAR(8),
	@DATARINUNCIARINUNCIA	CHAR(8),
	@COGNOME			CHAR(24),
	@NOME			CHAR(20),
	@NOTE			CHAR(50),
	@FLAGANAG			CHAR(1),
	@FKDATAINSTIT		CHAR(8),
	@FKORAINSTIT		CHAR(8),
	@FIRMA			CHAR(17),

	
	@MSGERR 			VARCHAR(100) OUTPUT
 AS


DECLARE 	

@APPORICEV		CHAR(6),
@DATAOGGI   		CHAR(8),
@ORAOGGI  		CHAR(8),
@COGNOMETIT	CHAR(24),
@NOMETIT		CHAR(20),
@FLAGANAGTIT	CHAR(1),
@DATAINSTIT		CHAR(8),
@ORAINSTIT		CHAR(8),
@TIPOPREC 		CHAR(1),
@TIPOPROVV		CHAR(1),
@TITTROVATO	CHAR(1),
@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)


--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL NOME FILE è VALORIZZATO, CONTROLLO SE IL NOME/COGNOME DEL TITOLARE PRESENTE SUL FILE è QUELLO DI UN TITOLARE VALIDO
-- 2) CONTROLLO CHE LA RICEVITORIA NON ABBIA GIà UNA RINUNCIA CON LA STESSA DATA E NUM PROTOCOLLO
-- 3) SE IL FLAGANAG è A 0 VERIFICO CHE NON SIA GIà PRESENTE UNA RINUNCIA PER LA RICEVITORIA CON FLAG A 0
-- 4) SE IL FLAGANAG è A 1 VERIFICO CHE NON SIA GIà PRESENTE UNA RINUNCIA PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 5) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT


--*************************************************************************
--           CONTROLLO 1
--*************************************************************************
IF @NOMEFILE <> '' 
BEGIN

	DECLARE CUR_R1 SCROLL CURSOR FOR
	SELECT LSRTIT_COGNOME, LSRTIT_NOME, LSRTIT_KEY_DATA_INS, LSRTIT_KEY_ORA_INS, LSRTIT_TIPO_PROVV
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV=@RICEV AND
	  	LSRTIT_DATA_VALIDITA < @DATAOGGI AND
		  LSRTIT_FLAG_VALIDITA = 'Y' 
	ORDER BY LSRTIT_DATA_VALIDITA DESC  
	SELECT @TIPOPREC = ''
	SELECT @FLAGOK = 'N'
	SELECT @TITTROVATO = 'N'
	SELECT @FLAGANAGTIT ='0'
	SELECT @FLAGANAG ='0'
	SELECT @FKDATAINSTIT = '00000000'	
	SELECT @FKORAINSTIT = '00000000'	

	OPEN CUR_R1
	FETCH NEXT FROM CUR_R1
	INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @TIPOPROVV
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @TITTROVATO = 'N'
		BEGIN
			  --******************************************************************
			  --INIZIO CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			 --******************************************************************
			IF @TIPOPREC = ''
			BEGIN
				SELECT @TIPOPREC = @TIPOPROVV
				SELECT @FLAGOK ='Y'
			SELECT @FLAGANAGTIT ='1'
			END
			ELSE
			BEGIN
				IF @TIPOPREC = 'E' AND @FLAGOK ='Y'
				BEGIN
					SELECT @TIPOPREC = @TIPOPROVV
					SELECT @FLAGOK = 'N'
				END
				ELSE
				BEGIN
					IF ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND (@TIPOPROVV ='I' OR @TIPOPROVV ='C')) OR ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND @TIPOPROVV ='E')
					BEGIN
						SELECT @TIPOPREC = @TIPOPROVV
						SELECT @FLAGOK = 'Y'
						SELECT @FLAGANAGTIT ='2'
					END
					ELSE
	    				BEGIN
	     					SELECT @TIPOPREC = @TIPOPROVV
	     					SELECT @FLAGOK = 'N'
	    				END
	   			END
	  		END
			--******************************************************************
			--FINE CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			--******************************************************************
			-- SE HO TROVATO UN TITOLARE VALIDO INIZIALIZZO TUTTE LE VARIABILI RELATIVE A QUESTO TITOLARE
			IF @FLAGOK = 'Y'
			BEGIN
				IF (@COGNOME = @COGNOMETIT AND @NOME = @NOMETIT)
				BEGIN
					SELECT @FLAGANAG = @FLAGANAGTIT
					SELECT @FKDATAINSTIT	= @DATAINSTIT
					SELECT @FKORAINSTIT = @ORAINSTIT
					SELECT @COGNOME = @COGNOMETIT
					SELECT @NOME = @NOMETIT
					SELECT @TITTROVATO = 'Y'
				END
			END
		END --END IF @TITTROVATO = 'N'
		FETCH NEXT FROM CUR_R1
		INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @TIPOPROVV
	END

	CLOSE CUR_R1
	DEALLOCATE CUR_R1

END


--*************************************************************************
--           CONTROLLO 2
--*************************************************************************


SELECT @APPORICEV = LSRRIN_LIS_KEY_ID_RICEV 
FROM LSRRIN_LIS
WHERE LSRRIN_LIS_KEY_ID_RICEV = @RICEV
	AND LSRRIN_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRRIN_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRRIN_LIS_KEY_ATTIVITA = @ATTIVITA
	AND LSRRIN_LIS_DATA_CONTRATTO = @DATADOC
	AND LSRRIN_LIS_NUM_PROT_DOC = @NUMPROTDOC
	AND LSRRIN_LIS_ASSOCIAZIONE = @ASSOCIAZIONE

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RICEVITORIA ESISTE UNA RINUNCIA CON STESSA DATA E PROT.- RINUNCIA NON ACQUISITA'
	RETURN
END

--*************************************************************************
--           CONTROLLO 3
--*************************************************************************
IF (@FLAGANAG = '0')
BEGIN
	SELECT @FKDATAINSTIT = ''	
	SELECT @FKORAINSTIT = ''	

	SELECT @APPORICEV = LSRRIN_LIS_KEY_ID_RICEV 
	FROM LSRRIN_LIS
	WHERE LSRRIN_LIS_KEY_ID_RICEV = @RICEV
		AND LSRRIN_LIS_KEY_CATEGORIA = @CATEGORIA
		AND LSRRIN_LIS_KEY_SERVIZIO = @SERVIZIO
		AND LSRRIN_LIS_KEY_ATTIVITA = @ATTIVITA
		AND LSRRIN_LIS_FLAG_ANAG = '0'

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +'PER LA RICEVITORIA ESISTE UNA RINUNCIA NON ABBINATA - RINUNCIA NON ACQUISITA'
		RETURN
	END
END


--*************************************************************************
--           CONTROLLO 4
--*************************************************************************
IF (@FLAGANAG <> '0')
BEGIN
	SELECT @APPORICEV = LSRRIN_LIS_KEY_ID_RICEV 
	FROM LSRRIN_LIS
	WHERE LSRRIN_LIS_KEY_ID_RICEV = @RICEV
		AND LSRRIN_LIS_KEY_CATEGORIA = @CATEGORIA
		AND LSRRIN_LIS_KEY_SERVIZIO = @SERVIZIO
		AND LSRRIN_LIS_KEY_ATTIVITA = @ATTIVITA	
		AND LSRRIN_LIS_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRRIN_LIS_FK_ORA_INS_TIT = @FKORAINSTIT

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RICEVITORIA ESISTE UNA RINUNCIA PER IL TITOLARE INDICATO - RINUNCIA NON ACQUISITA'
		RETURN
	END
END


--*************************************************************************
--           CONTROLLO 5
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_COGNOME , @NOME = LSRTIT_NOME
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_KEY_ORA_INS = @FKORAINSTIT

END 


--*************************************************************************
--           IL RECORD VIENE INSERITO SU LSRRIN_LIS
--*************************************************************************
INSERT INTO LSRRIN_LIS VALUES (
	@RICEV, 		
	@DATAOGGI,
	@ORAOGGI,
	@CATEGORIA,		
	@SERVIZIO,		
	@ATTIVITA,		
	@NOMEFILE,			
	@DATADOC,		
	@DATAINVIODOC,	
	@NUMPROTDOC,	
	@DATARINUNCIA,
	@DATARINUNCIARINUNCIA,
	@ASSOCIAZIONE,	
	@STATODOC,	
	@COGNOME,	
	@NOME	,	
	@NOTE,	
	@FLAGANAG,	
	@FKDATAINSTIT,	
	@FKORAINSTIT,	
	@FIRMA	)

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO RINUNCIA - RINUNCIA NON ACQUISITA'
	RETURN
END
ELSE
BEGIN
	IF @FLAGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' RINUNCIA ACQUISITA MA NON ABBINATA'
	END
	ELSE	
	BEGIN	
		SELECT @MSGERR = '9999 - ' + @RICEV +'RINUNCIA ACQUISITA CORRETTAMENTE'
	END
	RETURN
END
GO
