/****** Object:  StoredProcedure [dbo].[ASSOCIAZIONE_CU]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ASSOCIAZIONE_CU] 

AS

DECLARE @RICEV AS CHAR(6); 
DECLARE @ASSOC AS CHAR(1);
DECLARE @LOST AS CHAR(8);
DECLARE @CODSER AS CHAR(1);
DECLARE @DATAOGGI AS CHAR(8);
DECLARE @COGNOME AS CHAR(24);
DECLARE @NOME AS CHAR(20)


SELECT @DATAOGGI = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

--CANCELLO TUTTI I RECORD DALLA TABELLA CU_ASSOCIAZIONE
DELETE FROM CU_ASSOCIAZIONE

INSERT INTO  CU_ASSOCIAZIONE 
SELECT LSR01A_KEY_ID_RICEV, LSR01A_COGNOME, 
         LSR01A_NOME, LSR01A_TAB_GIOCHI_10, '', '', '' 
FROM CONDIVISO.DBO.LSR01A
WHERE LSR01A_TAB_GIOCHI_10 <>'0'


DECLARE CUR_R1 SCROLL CURSOR FOR
SELECT COD_LOTTOMATICA, COGNOME_TIT, NOME_TIT
FROM CU_ASSOCIAZIONE

OPEN CUR_R1
FETCH NEXT FROM CUR_R1
INTO @RICEV, @COGNOME, @NOME

WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT  @ASSOC = '' 

	IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
	BEGIN
		SELECT @ASSOC = LSRCON_LIS_ASSOCIAZIONE, 
			@COGNOME = LSRCON_LIS_COGNOME,
			@NOME = LSRCON_LIS_NOME
		FROM LSRCON_LIS
		WHERE LSRCON_LIS_KEY_ID_RICEV = @RICEV
		AND LSRCON_LIS_FLAG_ANAG = '1'
						
		IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
		BEGIN
			
			SELECT @ASSOC = LSRADE_LIS_ASSOCIAZIONE, 
				@COGNOME = LSRADE_LIS_COGNOME,
				@NOME = LSRADE_LIS_NOME
			FROM LSRADE_LIS
			WHERE LSRADE_LIS_KEY_ID_RICEV = @RICEV
			AND LSRADE_LIS_FLAG_ANAG = '1'
 			AND LSRADE_LIS_KEY_CATEGORIA + LSRADE_LIS_KEY_SERVIZIO + LSRADE_LIS_KEY_ATTIVITA  = '050101' 
		END
	END

	UPDATE CU_ASSOCIAZIONE 
	SET ASSOCIAZIONE = @ASSOC,
		COGNOME_DOC = @COGNOME,
		NOME_DOC = @NOME
	WHERE COD_LOTTOMATICA = @RICEV

	FETCH NEXT FROM CUR_R1		
	INTO @RICEV, @COGNOME, @NOME
END

CLOSE CUR_R1
DEALLOCATE CUR_R1
GO
