/****** Object:  StoredProcedure [dbo].[ASSOCIAZIONE_BOLLO]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ASSOCIAZIONE_BOLLO] 

AS

DECLARE @RICEV AS char(6); 
DECLARE @ASSOC AS char(1);
DECLARE @LOST AS char(8);
DECLARE @CODSER AS char(1);
DECLARE @DATAOGGI AS char(8);
DECLARE @COGNOME AS CHAR(24);
DECLARE @NOME AS CHAR(20)


SELECT @DATAOGGI = substring(convert(char(25),getdate(),121),1,4)+
		substring(convert(char(25),getdate(),121),6,2)+
		substring(convert(char(25),getdate(),121),9,2)

--CANCELLO TUTTI I RECORD DALLA TABELLA bollo_associazione
DELETE FROM bollo_associazione

INSERT INTO  bollo_associazione 
SELECT lsr01a_key_id_ricev, lsr01a_cognome, 
         lsr01a_nome, lsr01a_tab_giochi_bollo, '', '', '' 
FROM condiviso.dbo.lsr01a
WHERE lsr01a_tab_giochi_bollo <>'0'


DECLARE CUR_R1 SCROLL CURSOR FOR
SELECT cod_lottomatica, cognome_tit, nome_tit
FROM bollo_associazione

OPEN CUR_R1
FETCH NEXT FROM CUR_R1
INTO @RICEV, @COGNOME, @NOME

WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT  @ASSOC = '' 

	IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
	BEGIN
		SELECT @ASSOC = LSRCON_BOLLO_ASSOCIAZIONE, 
			@COGNOME = LSRCON_BOLLO_COGNOME,
			@NOME = LSRCON_BOLLO_NOME
		FROM LSRCON_BOLLO
		WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRCON_BOLLO_FLAG_ANAG = '1'
		AND LSRCON_BOLLO_TIPO_DOC IN ('C', 'A')
		ORDER BY LSRCON_BOLLO_TIPO_DOC 
						
		IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
		BEGIN
			SELECT @ASSOC = LSRSER_BOLLO_ASSOCIAZIONE
			FROM LSRSER_BOLLO
			WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
			AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
			AND LSRSER_BOLLO_DATA_DECOR =
				(SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
				FROM LSRSER_BOLLO
				WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
					AND  LSRSER_BOLLO_DATA_DECOR <= @DATAOGGI
					AND  LSRSER_BOLLO_FLAG_VALIDITA = 'Y')

		
			IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
			BEGIN
				SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE,
					@COGNOME = LSRRAD_COGNOME,
					@NOME = LSRRAD_NOME
				FROM LSRRAD A
				WHERE LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_FONTE = 'A'
				AND LSRRAD_TIPO_SERVIZIO = '05'					
				AND LSRRAD_FLAG_ANAG = '1'
				AND LSRRAD_DATA_INVIO_DOC = (
					SELECT MAX(LSRRAD_DATA_INVIO_DOC)
					FROM LSRRAD B
					WHERE A.LSRRAD_KEY_ID_RICEV =  B.LSRRAD_KEY_ID_RICEV
					AND LSRRAD_FONTE = 'A'
					AND LSRRAD_TIPO_SERVIZIO = '05'					
					AND LSRRAD_FLAG_ANAG = '1'
					)
 
			END
		END
	END

	UPDATE bollo_associazione 
	SET associazione = @ASSOC,
		cognome_doc = @COGNOME,
		nome_doc = @NOME
	WHERE cod_lottomatica = @RICEV

	FETCH NEXT FROM CUR_R1		
	INTO @RICEV, @COGNOME, @NOME
END

CLOSE CUR_R1
DEALLOCATE CUR_R1
GO
