/****** Object:  StoredProcedure [dbo].[ASSOC_BOLLO]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ASSOC_BOLLO] 

AS

DECLARE 

@RICEV		CHAR(6), 
@ASSOC		CHAR(1),
@LOST		CHAR(8),
@CODSER		CHAR(1),
@DATAOGGI	CHAR(8),
@COGNOME	CHAR(24),
@NOME		CHAR(20)


SELECT @DATAOGGI = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

--CANCELLO TUTTI I RECORD DALLA TABELLA CONTRATTI_CNI
--DELETE FROM ASSOCIAZIONE_SERVIZI

--INSERT INTO  ASSOCIAZIONE_SERVIZI 
--SELECT DISTINCT(LSRTIT_KEY_ID_RICEV), '', '', '' 
--FROM LSRTIT



DECLARE CUR_R1 SCROLL CURSOR FOR
SELECT COD_LOTT
FROM ASSOCIAZIONE_SERVIZI
--WHERE  COD_LOTT >= 'RM3964'

OPEN CUR_R1
FETCH NEXT FROM CUR_R1
INTO @RICEV

WHILE @@FETCH_STATUS = 0 
BEGIN
	PRINT @RICEV
	-- BOLLO
	SELECT  @ASSOC = '' 

		SELECT @ASSOC = LSRCON_BOLLO_ASSOCIAZIONE, 
			@COGNOME = LSRCON_BOLLO_COGNOME,
			@NOME = LSRCON_BOLLO_NOME
		FROM LSRCON_BOLLO
		WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRCON_BOLLO_FLAG_ANAG = '1'
		AND LSRCON_BOLLO_TIPO_DOC IN ('C', 'A')
		ORDER BY LSRCON_BOLLO_TIPO_DOC

						
		IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
		BEGIN
			SELECT @ASSOC = LSRSER_BOLLO_ASSOCIAZIONE
			FROM LSRSER_BOLLO
			WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
			AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
			AND LSRSER_BOLLO_DATA_DECOR =
				(SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
				FROM LSRSER_BOLLO
				WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
					AND  LSRSER_BOLLO_DATA_DECOR <= @DATAOGGI
					AND  LSRSER_BOLLO_FLAG_VALIDITA = 'Y')

		
			IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
			BEGIN
				SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE,
					@COGNOME = LSRRAD_COGNOME,
					@NOME = LSRRAD_NOME
				FROM LSRRAD A
				WHERE LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_FONTE = 'A'
				AND LSRRAD_TIPO_SERVIZIO = '05'					
				AND LSRRAD_FLAG_ANAG = '1'
				AND LSRRAD_DATA_INVIO_DOC = (
					SELECT MAX(LSRRAD_DATA_INVIO_DOC)
					FROM LSRRAD B
					WHERE A.LSRRAD_KEY_ID_RICEV =  B.LSRRAD_KEY_ID_RICEV
					AND LSRRAD_FONTE = 'A'
					AND LSRRAD_TIPO_SERVIZIO = '05'					
					AND LSRRAD_FLAG_ANAG = '1'
					)
 
			END
		END

	UPDATE ASSOCIAZIONE_SERVIZI 
	SET BOLLO = @ASSOC
	WHERE COD_LOTT = @RICEV

--END


	FETCH NEXT FROM CUR_R1		
	INTO @RICEV
END

CLOSE CUR_R1
DEALLOCATE CUR_R1
GO
