/****** Object:  StoredProcedure [dbo].[ATTIVAZIONE_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ATTIVAZIONE_GS]  

	@RICEV 		CHAR(6),
	@CODSER			CHAR(2),
	@DATAATTIV		CHAR(8),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(50),
	@MSGERR 		VARCHAR(100) OUTPUT
AS

DECLARE 	

@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATAORAINS	CHAR(16),
@DATAMAX		CHAR(8),
@CHKRICEV		CHAR(6),
@STATOLOTTO	CHAR(1),
@STATOTRISA		CHAR(1),
@STATOTRISF		CHAR(1),
@TIPOPROVV		CHAR(1),
@PROVVFUT		CHAR(8),
@ASSOCIAZIONE	CHAR(1),
@DESCSTATO		CHAR(80)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

/*
' ESEGUO I CONTROLLI NEL CASO DI ATTIVAZIONE AL SERVIZIO TRIS:
' 1) - ESISTE LA RICEVITORIA IN LSRSER_TRIS
' 2) - LO STATO DEL SERVIZIO LOTTO SIA ATTIVO OPPURE ABBIA ALMENO LA CONCESSIONE ALLA DATA DI ATTIVAZIONE
' 3) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 4) - IL SERVIZIO NON SIA GIà ATTIVO	
' 5) - LO STATO DEL SERVIZIO TRIS SIA UGUALE A 0 E IL TIPO PROVVEDIMENTO DIVERSO DA 'I' (CAMBIO INTESTATARIO) -- NON APPLICATO (07-12-2000)
*/


/*
CONTROLLO 1
*/
/*
SELECT @CHKRICEV = LSRSER_TRIS_KEY_ID_RICEV FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE SU LSRSER_TRIS'
	RETURN
END
*/
/*
CONTROLLO 2 - ANNULLATO IN DATA 27/12/2005

SELECT @STATOLOTTO = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR <= @DATAATTIV)

IF @STATOLOTTO = 'S' OR @STATOLOTTO = 'M' OR @STATOLOTTO = 'R'
BEGIN
	SELECT @MSGERR = '7777 - ' + @RICEV +' SERVIZIO LOTTO SOSPESO/REVOCATO'
	RETURN
END
*/

/*
CONTROLLO 3
*/

SELECT @PROVVFUT = LSRSER_TRIS_DATA_DECOR,@STATOTRISF = LSRSER_TRIS_STATO
FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
AND LSRSER_TRIS_DATA_DECOR = @DATAATTIV


IF @PROVVFUT IS NOT NULL

BEGIN
	IF @STATOTRISF = '1'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI ATTIVAZIONE/ RIATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOTRISF = '2'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI DISATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOTRISF = '3'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI SOSPENSIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END

	SELECT @MSGERR = '6666 - ' + @RICEV + '  ' + @DESCSTATO
	RETURN
END

/*
CONTROLLO 4
*/
SELECT @STATOTRISA = LSRSER_TRIS_STATO 
FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
AND LSRSER_TRIS_DATA_DECOR =
	(SELECT MAX(LSRSER_TRIS_DATA_DECOR) 
	FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
	AND LSRSER_TRIS_DATA_DECOR <= @DATAATTIV)

IF @STATOTRISA = '1'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO TRIS GIA ATTIVATO'
	RETURN
END

IF @STATOTRISA = '2'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO TRIS DISATTIVO'
	RETURN
END

IF @STATOTRISA = '3'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO TRIS SOSPESO'
	RETURN
END


/*
CONTROLLO 5 (ANNULLATO IN DATA 07-12-2000)
*/
/*
SELECT @TIPOPROVV = LSRSER_TRIS_TIPO_PROVV FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
AND LSRSER_TRIS_DATA_DECOR <=
(SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
AND LSRSER_TRIS_DATA_DECOR <= @DATAATTIV)

IF @STATOTRIS = '0' 
BEGIN 
	IF @TIPOPROVV <> 'I'
	BEGIN
		BEGIN TRANSACTION

		INSERT INTO LSRSER_TRIS VALUES (@RICEV,@DATAINS,@ORAINS,'1',@DATAATTIV,NULL,NULL,NULL,NULL,@FIRMA,NULL,'00000000','Y')

		IF @@ERROR <> 0 
			BEGIN
				SELECT @MSGERR = '9999 - ' + @RICEV +' ' + ' ERRORE NELL'INSERT SU LSRSER_TRIS'
				ROLLBACK TRANSACTION
				RETURN
			END
		ELSE
			BEGIN
				SELECT @MSGERR = '0000 - OPERAZIONE TERMINATA CORRETTAMENTE'
				COMMIT TRANSACTION
				RETURN
			END
	END
	ELSE
	BEGIN
		SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO TRIS NON ATTIVABILE - CAMBIO INTESTATARIO IN CORSO'
		RETURN
	END
END
*/


--INIZIO MODIFICA IN DATA 02-05-2001

BEGIN TRANSACTION

SELECT @DATAORAINS = MAX(LSRLET_GS_KEY_DATA_INS+LSRLET_GS_KEY_ORA_INS)
				FROM LSRLET_GS	
				WHERE LSRLET_GS_KEY_ID_RICEV = @RICEV
				AND lsrlet_gs_key_codice_servizio = @CODSER
				AND LSRLET_GS_TIPO_MOVIMENTAZIONE = 'A'
				AND LSRLET_GS_KEY_DATA_INS = @DATAINS
				AND LSRLET_GS_DECOR_DAL = '00000000'

IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET_GS SET LSRLET_GS_DECOR_DAL = @DATAATTIV,
		LSRLET_GS_NOTE = @NOTE
	WHERE LSRLET_GS_KEY_ID_RICEV = @RICEV
	AND LSRLET_GS_KEY_DATA_INS+LSRLET_GS_KEY_ORA_INS = @DATAORAINS
	AND lsrlet_gs_key_codice_servizio = @CODSER
	AND LSRLET_GS_TIPO_MOVIMENTAZIONE = 'A'

END
ELSE
BEGIN
	INSERT INTO LSRLET_GS VALUES(@RICEV,@DATAINS,@ORAINS,@CODSER,'A',@DATAATTIV,'','','00000000',@NOTE,@FIRMA,'V')
END

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET_GS'
	ROLLBACK TRANSACTION
	RETURN
END

--FINE MODIFICA IN DATA 02-05-2001



IF @STATOTRISF = 0
BEGIN
	UPDATE LSRSER_TRIS SET LSRSER_TRIS_FLAG_VALIDITA = 'N'
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
	AND LSRSER_TRIS_DATA_DECOR >= @DATAATTIV
END

INSERT INTO LSRSER_TRIS VALUES (@RICEV,@DATAINS,@ORAINS,'1',@DATAATTIV,NULL,NULL,NULL,NULL,@FIRMA,NULL,'00000000','Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV + ' ERRORE IN INSERT SU LSRSER_TRIS'
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	SELECT @MSGERR = '0000 - ' + @RICEV + ' OPERAZIONE TERMINATA CORRETTAMENTE'
	COMMIT TRANSACTION
	RETURN
END
GO
