/****** Object:  StoredProcedure [dbo].[ATTIVAZIONE_GP]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ATTIVAZIONE_GP]  

	@RICEV 		CHAR(6),
	@CODSER			CHAR(2),
	@DATAATTIV		CHAR(8),
	@TIPOPV		CHAR(1),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(50),
	@MSGERR 		VARCHAR(100) OUTPUT
AS

DECLARE 	

@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATAORAINS	CHAR(16),
@DATAMAX		CHAR(8),
@CHKRICEV		CHAR(6),
@STATOLOTTO	CHAR(1),
@STATOGPA		CHAR(1),
@STATOGPF		CHAR(1),
@TIPOPROVV		CHAR(1),
@PROVVFUT		CHAR(8),
@ASSOCIAZIONE	CHAR(1),
@DESCSTATO		CHAR(80)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

/*
' ESEGUO I CONTROLLI NEL CASO DI ATTIVAZIONE AL SERVIZIO GP:
' 1) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 2) - IL SERVIZIO NON SIA GIà ATTIVO	
' 3) - LO STATO DEL SERVIZIO GP SIA UGUALE A 0 E IL TIPO PROVVEDIMENTO DIVERSO DA 'I' (CAMBIO INTESTATARIO) -- NON APPLICATO (07-12-2000)
*/
/*CONTROLLO 1
*/

SELECT @PROVVFUT = LSRSER_GP_DATA_DECOR,@STATOGPF = LSRSER_GP_STATO
FROM LSRSER_GP
WHERE LSRSER_GP_KEY_ID_RICEV = @RICEV
AND LSRSER_GP_FLAG_VALIDITA = 'Y'
AND LSRSER_GP_DATA_DECOR = @DATAATTIV


IF @PROVVFUT IS NOT NULL

BEGIN
	IF @STATOGPF = '1'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI ATTIVAZIONE/ RIATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOGPF = '2'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI DISATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOGPF = '3'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI SOSPENSIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END

	SELECT @MSGERR = '6666 - ' + @RICEV + '  ' + @DESCSTATO
	RETURN
END

/*
CONTROLLO 4
*/
SELECT @STATOGPA = LSRSER_GP_STATO 
FROM LSRSER_GP
WHERE LSRSER_GP_KEY_ID_RICEV = @RICEV
AND LSRSER_GP_FLAG_VALIDITA = 'Y'
AND LSRSER_GP_DATA_DECOR =
	(SELECT MAX(LSRSER_GP_DATA_DECOR) 
	FROM LSRSER_GP
	WHERE LSRSER_GP_KEY_ID_RICEV = @RICEV
	AND LSRSER_GP_FLAG_VALIDITA = 'Y'
	AND LSRSER_GP_DATA_DECOR <= @DATAATTIV)

IF @STATOGPA = '1'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO GP GIA ATTIVATO'
	RETURN
END

IF @STATOGPA = '2'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO GP DISATTIVO'
	RETURN
END

IF @STATOGPA = '3'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO GP SOSPESO'
	RETURN
END


--INIZIO MODIFICA IN DATA 02-05-2001

BEGIN TRANSACTION

SELECT @DATAORAINS = MAX(LSRLET_GS_KEY_DATA_INS+LSRLET_GS_KEY_ORA_INS)
				FROM LSRLET_GS	
				WHERE LSRLET_GS_KEY_ID_RICEV = @RICEV
				AND lsrlet_gs_key_codice_servizio = @CODSER
				AND LSRLET_GS_TIPO_MOVIMENTAZIONE = 'A'
				AND LSRLET_GS_KEY_DATA_INS = @DATAINS
				AND LSRLET_GS_DECOR_DAL = '00000000'

IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET_GS SET LSRLET_GS_DECOR_DAL = @DATAATTIV,
		LSRLET_GS_NOTE = @NOTE
	WHERE LSRLET_GS_KEY_ID_RICEV = @RICEV
	AND LSRLET_GS_KEY_DATA_INS+LSRLET_GS_KEY_ORA_INS = @DATAORAINS
	AND lsrlet_gs_key_codice_servizio = @CODSER
	AND LSRLET_GS_TIPO_MOVIMENTAZIONE = 'A'

END
ELSE
BEGIN
	INSERT INTO LSRLET_GS VALUES(@RICEV,@DATAINS,@ORAINS,@CODSER,'A',@DATAATTIV,'','','00000000',@NOTE,@FIRMA,'V')
END

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET_GS'
	ROLLBACK TRANSACTION
	RETURN
END

--FINE MODIFICA IN DATA 02-05-2001



IF @STATOGPF = 0
BEGIN
	UPDATE LSRSER_GP SET LSRSER_GP_FLAG_VALIDITA = 'N'
	WHERE LSRSER_GP_KEY_ID_RICEV = @RICEV
	AND LSRSER_GP_FLAG_VALIDITA = 'Y'
	AND LSRSER_GP_DATA_DECOR >= @DATAATTIV
END

INSERT INTO LSRSER_GP VALUES (@RICEV,@DATAINS,@ORAINS,'1','A',@DATAATTIV,NULL,NULL,NULL,@TIPOPV,@FIRMA,NULL,'00000000','Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV + ' ERRORE IN INSERT SU LSRSER_GP'
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	SELECT @MSGERR = '0000 - ' + @RICEV + ' OPERAZIONE TERMINATA CORRETTAMENTE'
	COMMIT TRANSACTION
	RETURN
END
GO
