/****** Object:  StoredProcedure [dbo].[RIATTIVAZIONE_ST]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[RIATTIVAZIONE_ST]  
	@RICEV 		CHAR(6),
	@DATAATTIV		CHAR(8),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(50),
	@MSGERR 		VARCHAR(100) OUTPUT
AS


DECLARE 	@DATAINS		CHAR(8),
		@ORAINS		CHAR(8),
		@DATAORAINS	CHAR(16),
		@DATAMAX		CHAR(8),
		@CHKRICEV		CHAR(6),
		@STATOLOTTO	CHAR(1),
		@STATOA		CHAR(1),
		@STATOCONI		CHAR(1),
		@STATOFUTURO	CHAR(1),
		@TIPOPROVV		CHAR(1),
		@PROVVFUT		CHAR(8),
		@ASSOCIAZIONE	CHAR(1),
		@DESCSTATO		CHAR(80)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)
/*
' ESEGUO I CONTROLLI NEL CASO DI RIATTIVAZIONE A ST
' 1) - ESISTE LA RICEVITORIA IN LSRSER_ST
' 2) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 3) - IL SERVIZIO SIA IN UNO STATO COMPATIBILE CON LA RIATTIVAZIONE
*/

/*
CONTROLLO 1
*/
SELECT @CHKRICEV = LSRSER_ST_KEY_ID_RICEV
FROM LSRSER_ST
WHERE  LSRSER_ST_KEY_ID_RICEV = @RICEV
	AND LSRSER_ST_FLAG_VALIDITA = 'Y'

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE SUGLI ARCHIVI'
	RETURN
END

/*
CONTROLLO - STATO CONI ATTIVO
*/
SELECT @STATOCONI = ''
SELECT @STATOCONI = LSRSER_CONI_STATO 
FROM LSRSER_CONI
WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEV
	AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
	AND LSRSER_CONI_DATA_DECOR =
	(
		SELECT MAX(LSRSER_CONI_DATA_DECOR) 
		FROM LSRSER_CONI
		WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEV
		AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
		AND LSRSER_CONI_DATA_DECOR <= @DATAATTIV
	)

IF @STATOCONI <> '1' 

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' CONI DISATTVO'
	RETURN
END

/*
CONTROLLO 2
*/

SELECT @PROVVFUT = LSRSER_ST_DATA_DECOR, @STATOFUTURO = LSRSER_ST_STATO
FROM LSRSER_ST
WHERE LSRSER_ST_KEY_ID_RICEV = @RICEV
	AND LSRSER_ST_FLAG_VALIDITA = 'Y'
	AND LSRSER_ST_DATA_DECOR = @DATAATTIV


IF @PROVVFUT IS NOT NULL

BEGIN
	IF @STATOFUTURO = '1'
	BEGIN
		SELECT @DESCSTATO = 'PROVV. DI ATTIVAZIONE/ RIATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOFUTURO = '2'
	BEGIN
		SELECT @DESCSTATO = 'PROVV. DI DISATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	SELECT @MSGERR = '6666 - ' + @RICEV + '  ' + @DESCSTATO
	RETURN
END

/*
CONTROLLO 3
*/
SELECT @STATOA = LSRSER_ST_STATO 
FROM LSRSER_ST
WHERE LSRSER_ST_KEY_ID_RICEV = @RICEV
	AND LSRSER_ST_FLAG_VALIDITA = 'Y'
	AND LSRSER_ST_DATA_DECOR =
		(SELECT MAX(LSRSER_ST_DATA_DECOR) 
		FROM LSRSER_ST
		WHERE LSRSER_ST_KEY_ID_RICEV = @RICEV
			AND LSRSER_ST_FLAG_VALIDITA = 'Y'
			AND LSRSER_ST_DATA_DECOR <= @DATAATTIV)

IF @STATOA = '1'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO GIA ATTIVATO'
	RETURN
END


BEGIN TRANSACTION

SELECT @DATAORAINS = MAX(LSRLET_ST_KEY_DATA_INS+LSRLET_ST_KEY_ORA_INS)
				FROM LSRLET_ST
				WHERE LSRLET_ST_KEY_ID_RICEV = @RICEV
				AND LSRLET_ST_TIPO_MOVIMENTAZIONE = 'R'
				AND LSRLET_ST_KEY_DATA_INS = @DATAINS
				AND LSRLET_ST_DECOR_DAL = '00000000'

IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET_ST 
	SET LSRLET_ST_DECOR_DAL = @DATAATTIV,
		LSRLET_ST_NOTE = @NOTE
	WHERE LSRLET_ST_KEY_ID_RICEV = @RICEV
	AND LSRLET_ST_KEY_DATA_INS+LSRLET_ST_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_ST_TIPO_MOVIMENTAZIONE = 'R'

END
ELSE
BEGIN
	INSERT INTO LSRLET_ST
	 VALUES(@RICEV,@DATAINS,@ORAINS,'R',@DATAATTIV,'','','00000000',@NOTE,@FIRMA,'V')
END

	
IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET'
	ROLLBACK TRANSACTION
	RETURN
END


INSERT INTO LSRSER_ST VALUES (@RICEV,@DATAINS,@ORAINS,'1','R',@DATAATTIV,NULL,NULL,NULL,@FIRMA,NULL,'00000000','Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO VARIAZIONE STATO'
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN

	SELECT @MSGERR = '0000 - ' + @RICEV +' OPERAZIONE TERMINATA CORRETTAMENTE'


	COMMIT TRANSACTION
	RETURN
END
GO
