/****** Object:  StoredProcedure [dbo].[VARIAZIONE_CONTRATTO_QUADRO_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[VARIAZIONE_CONTRATTO_QUADRO_LIS]
	@RICEV 		CHAR(6),
	@NOMEFILE		VARCHAR(255),
	@DATAINVIODOC	CHAR(8),
	@DATADOC		CHAR(8),
	@NUMPROTDOC	CHAR(25),
	@STATODOC		CHAR(1),
	@ASSOCIAZIONE	CHAR(1),
	@PARTITAIVA		CHAR(11),
	@COGNOME		CHAR(24),
	@NOME		CHAR(20),
	@NOTE		CHAR(50),
	@FLAGANAG		CHAR(1),
	@FKDATAINSTIT	CHAR(8),
	@FKORAINSTIT	CHAR(8),

	@KEYDATAINSDOC	CHAR(8),
	@KEYORAINSDOC	CHAR(8),
	@ABBINATO 		CHAR(1),
	
	@FIRMA		CHAR(17),
	@MSGERR 		VARCHAR(100) OUTPUT
 AS


DECLARE 	@APPORICEV		CHAR(6),
		@DATAOGGI   		CHAR(8),
		@ORAOGGI  		CHAR(8),
		@COGNOMETIT	CHAR(24),
		@NOMETIT		CHAR(20),
		@FLAGANAGTIT	CHAR(1),
		@DATAINSTIT		CHAR(8),
		@ORAINSTIT		CHAR(8),
		@TIPOPREC 		CHAR(1),
		@TIPOPROVV		CHAR(1),
		@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)



--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL ABBINATO = '0' E FLAGANAG è <>0 VERIFICO CHE NON SIA GIà PRESENTE UNA ADESIONE PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 2) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT



--*************************************************************************
--           CONTROLLO 1
--*************************************************************************
IF (@ABBINATO = '0' AND @FLAGANAG<>'0')
BEGIN
	SELECT @APPORICEV = LSRCON_LIS_KEY_ID_RICEV 
	FROM LSRCON_LIS
	WHERE LSRCON_LIS_KEY_ID_RICEV = @RICEV
		AND LSRCON_LIS_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRCON_LIS_FK_ORA_INS_TIT = @FKORAINSTIT

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RICEVITORIA ESISTE UN CONTRATTO PER IL TITOLARE INDICATO - CONTRATTO NON AGGIORNATO'
		RETURN
	END
END


--*************************************************************************
--           CONTROLLO 2
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_COGNOME , @NOME = LSRTIT_NOME
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_KEY_ORA_INS = @FKORAINSTIT

END 


--*************************************************************************
--           IL RECORD VIENE INSERITO SU LSRCON_LIS
--*************************************************************************

UPDATE LSRCON_LIS 
SET 	LSRCON_LIS_DATA_CONTRATTO =@DATADOC,		
	LSRCON_LIS_DATA_INVIO_DOC = @DATAINVIODOC,	
	LSRCON_LIS_NUM_PROT_DOC = @NUMPROTDOC,	
	LSRCON_LIS_ASSOCIAZIONE = @ASSOCIAZIONE,	
	LSRCON_LIS_STATO_DOC = @STATODOC,	
	LSRCON_LIS_PARTITA_IVA = @PARTITAIVA,
	LSRCON_LIS_COGNOME = @COGNOME,	
	LSRCON_LIS_NOME = @NOME,	
	LSRCON_LIS_NOTE = @NOTE,	
	LSRCON_LIS_FLAG_ANAG = @FLAGANAG,	
	LSRCON_LIS_FK_DATA_INS_TIT = @FKDATAINSTIT,	
	LSRCON_LIS_FK_ORA_INS_TIT = @FKORAINSTIT,	
	LSRCON_LIS_FIRMA =@FIRMA	
WHERE LSRCON_LIS_KEY_ID_RICEV  = @RICEV
	AND LSRCON_LIS_KEY_DATA_INS = @KEYDATAINSDOC
	AND LSRCON_LIS_KEY_ORA_INS = @KEYORAINSDOC


IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO CONTRATTO - CONTRATTO NON  AGGIORNATO'
	RETURN
END
ELSE
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' CONTRATTO AGGIORNATO CORRETTAMENTE'
	RETURN
END
GO
