/****** Object:  StoredProcedure [dbo].[VARIAZIONE_FIDEJUSSIONE_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[VARIAZIONE_FIDEJUSSIONE_LIS]


	@RICEV 		CHAR(6),
	@CATEGORIA		CHAR(2),
	@SERVIZIO		CHAR(2),
	@ATTIVITA		CHAR(2),
	@NOMEFILE		VARCHAR(255),
	@DATAINVIODOC	CHAR(8),
	@DATADOC		CHAR(8),
	@NUMPROTDOC	CHAR(25),
	@STATODOC		CHAR(1),
	@ASSOCIAZIONE	CHAR(2),
	@IMPORTO		CHAR(20),
	@ANNORIF		CHAR(4),
	@COGNOME		CHAR(24),
	@NOME		CHAR(20),
	@NOTE		CHAR(50),
	@FLAGANAG		CHAR(1),
	@FKDATAINSTIT	CHAR(8),
	@FKORAINSTIT	CHAR(8),

	@KEYDATAINSDOC	CHAR(8),
	@KEYORAINSDOC	CHAR(8),
	@ABBINATO 		CHAR(1),
	
	@FIRMA		CHAR(17),
	@MSGERR 		VARCHAR(100) OUTPUT
 AS


DECLARE 	@APPORICEV		CHAR(6),
		@DATAOGGI   		CHAR(8),
		@ORAOGGI  		CHAR(8),
		@COGNOMETIT		CHAR(24),
		@NOMETIT		CHAR(20),
		@FLAGANAGTIT		CHAR(1),
		@DATAINSTIT		CHAR(8),
		@ORAINSTIT		CHAR(8),
		@TIPOPREC 		CHAR(1),
		@TIPOPROVV		CHAR(1),
		@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)

IF (@ANNORIF = '' OR @ANNORIF IS NULL)
BEGIN
	SELECT @ANNORIF = SUBSTRING(CONVERT (VARCHAR(10), GETDATE(),112),1,4)
END  

--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL FLAGANAG è <>0 E ABBINATO = 0 VERIFICO CHE NON SIA GIà PRESENTE UNA FIDEJUSSIONE PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 2) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT



--*************************************************************************
--           CONTROLLO 1
--*************************************************************************
IF (@ABBINATO = '0' AND @FLAGANAG<>'0')
BEGIN
	SELECT @APPORICEV = LSRFID_LIS_KEY_ID_RICEV 
	FROM LSRFID_LIS
	WHERE LSRFID_LIS_KEY_ID_RICEV = @RICEV
		AND LSRFID_LIS_KEY_CATEGORIA = @CATEGORIA
		AND LSRFID_LIS_KEY_SERVIZIO = @SERVIZIO
		AND LSRFID_LIS_KEY_ATTIVITA = @ATTIVITA	
		AND LSRFID_LIS_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRFID_LIS_FK_ORA_INS_TIT = @FKORAINSTIT
		AND LSRFID_LIS_ANNO_RIF = @ANNORIF

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RIC. ESISTE UNA FID. PER IL TIT. E ANNO RIF. INDICATI - FID. NON AGGIORNATA'
		RETURN
	END
END


--*************************************************************************
--           CONTROLLO 2
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_COGNOME , @NOME = LSRTIT_NOME
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_KEY_ORA_INS = @FKORAINSTIT

END 


--*************************************************************************
--           IL RECORD VIENE INSERITO SU LSRFID_LIS
--*************************************************************************

UPDATE LSRFID_LIS 
SET  LSRFID_LIS_DATA_CONTRATTO = @DATADOC,		
	LSRFID_LIS_DATA_INVIO_DOC = @DATAINVIODOC,	
	LSRFID_LIS_NUM_PROT_DOC = @NUMPROTDOC,	
	LSRFID_LIS_ID_SOC = @ASSOCIAZIONE,	
	LSRFID_LIS_STATO_DOC = @STATODOC,	
	LSRFID_LIS_COGNOME = @COGNOME,	
	LSRFID_LIS_NOME = @NOME	,	
	LSRFID_LIS_IMPORTO = @IMPORTO,
	LSRFID_LIS_ANNO_RIF = @ANNORIF,
	LSRFID_LIS_NOTE = @NOTE,	
	LSRFID_LIS_FLAG_ANAG = @FLAGANAG,	
	LSRFID_LIS_FK_DATA_INS_TIT = @FKDATAINSTIT,	
	LSRFID_LIS_FK_ORA_INS_TIT = @FKORAINSTIT,	
	LSRFID_LIS_FIRMA = @FIRMA	
 WHERE LSRFID_LIS_KEY_ID_RICEV = @RICEV
	AND LSRFID_LIS_KEY_DATA_INS = @KEYDATAINSDOC
	AND LSRFID_LIS_KEY_ORA_INS = @KEYORAINSDOC
	AND LSRFID_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRFID_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRFID_LIS_KEY_ATTIVITA = @ATTIVITA


IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO FIDEJUSSIONE - FIDEJUSSIONE NON AGGIORNATA'
	RETURN
END
ELSE

BEGIN
	SELECT @MSGERR = @RICEV +' FIDEJUSSIONE AGGIORNATA CORRETTAMENTE'
	RETURN
END
GO
