/****** Object:  StoredProcedure [dbo].[VARIAZIONE_RAD_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[VARIAZIONE_RAD_LIS]  

	@RICEV 			CHAR(6),
	@CATEGORIA			CHAR(2),
	@SERVIZIO			CHAR(2),
	@ATTIVITA			CHAR(2),
	@TIPOMOVIMENTAZIONE	CHAR(1),
	@FONTE			CHAR(1),  
	@FIRMADOC 			CHAR(17),
	@NOMEFILE			VARCHAR(255),
	@DATAINVIODOC		CHAR(8),
	@DATADOC			CHAR(8),
	@NUMPROTDOC		CHAR(25),
	@STATODOC			CHAR(1),
	@CAUSALE			CHAR(1),
	@ASSOCIAZIONE		CHAR(1),
	@COGNOME			CHAR(24),
	@NOME			CHAR(20),
	@NOTE			CHAR(50),
	@FLAGANAG			CHAR(1),
	@FKDATAINSTIT		CHAR(8),
	@FKORAINSTIT		CHAR(8),

	@KEYDATAINSDOC		CHAR(8),
	@KEYORAINSDOC		CHAR(8),
	@ABBINATO 			CHAR(1),	
	
	@FIRMA			CHAR(17),
	@MSGERR 			VARCHAR(100) OUTPUT
 AS

DECLARE 	@APPORICEV		CHAR(6),
		@DATAOGGI   		CHAR(8),
		@ORAOGGI  		CHAR(8),
		@COGNOMETIT		CHAR(24),
		@NOMETIT		CHAR(20),
		@FLAGANAGTIT		CHAR(1),
		@DATAINSTIT		CHAR(8),
		@ORAINSTIT		CHAR(8),
		@TIPOPREC 		CHAR(1),
		@TIPOPROVV		CHAR(1),
		@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)



--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL FLAGANAG è <> 0 E ABBINATO = '0'  VERIFICO CHE NON SIA GIà PRESENTE UN RAD PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 2) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT



--*************************************************************************
--           CONTROLLO 1
--*************************************************************************
/* ELIMINATO IL CONTROLLO IL 21/11/2002 SU SEGNALAZIONE LIS: UN TITOLARE PUO' AVERE PIù DI UN DOC RAD ASSOCIATO (DE SIMONI)

IF (@ABBINATO = '0' AND @FLAGANAG<>'0')
BEGIN
	SELECT @APPORICEV = LSRRAD_LIS_KEY_ID_RICEV 
	FROM LSRRAD_LIS
	WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEV
		AND LSRRAD_LIS_KEY_CATEGORIA = @CATEGORIA
		AND LSRRAD_LIS_KEY_SERVIZIO = @SERVIZIO
		AND LSRRAD_LIS_KEY_ATTIVITA = @ATTIVITA	
		AND LSRRAD_LIS_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRRAD_LIS_FK_ORA_INS_TIT = @FKORAINSTIT

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RICEVITORIA ESISTE UN RAD PER IL TITOLARE INDICATO - RAD NON AGGIORNATO'
		RETURN
	END
END
*/

--*************************************************************************
--           CONTROLLO 2
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_COGNOME , @NOME = LSRTIT_NOME
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_KEY_ORA_INS = @FKORAINSTIT

END 


--*************************************************************************
--           IL RECORD VIENE INSERITO SU LSRRAD_LIS
--*************************************************************************

UPDATE LSRRAD_LIS 
SET LSRRAD_LIS_TIPO_MOVIMENTAZIONE = @TIPOMOVIMENTAZIONE,
	LSRRAD_LIS_FONTE = @FONTE,  
	LSRRAD_LIS_FIRMA_DOC =@FIRMADOC,	
	LSRRAD_LIS_DATA_DOC = @DATADOC,		
	LSRRAD_LIS_DATA_INVIO_DOC = @DATAINVIODOC,	
	LSRRAD_LIS_NUM_PROT_DOC = @NUMPROTDOC,	
	LSRRAD_LIS_ASSOCIAZIONE = @ASSOCIAZIONE,	
	LSRRAD_LIS_CAUSALE_LIS = @CAUSALE,
	LSRRAD_LIS_STATO_DOC = @STATODOC,	
	LSRRAD_LIS_COGNOME = @COGNOME,	
	LSRRAD_LIS_NOME = @NOME	,	
	LSRRAD_LIS_NOTE = @NOTE,	
 	LSRRAD_LIS_FLAG_ANAG = @FLAGANAG,	
	LSRRAD_LIS_FK_DATA_INS_TIT = @FKDATAINSTIT,	
	LSRRAD_LIS_FK_ORA_INS_TIT = @FKORAINSTIT,	
	LSRRAD_LIS_FIRMA = @FIRMA	
WHERE  LSRRAD_LIS_KEY_ID_RICEV = @RICEV
	AND LSRRAD_LIS_KEY_DATA_INS = @KEYDATAINSDOC
	AND LSRRAD_LIS_KEY_ORA_INS = @KEYORAINSDOC
	AND LSRRAD_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRRAD_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRRAD_LIS_KEY_ATTIVITA = @ATTIVITA



IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE AGGIORNAMENTO RAD - RAD NON AGGIORNATO'
	RETURN
END

ELSE
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' RAD AGGIORNATO CORRETTAMENTE'
	RETURN
END
GO
