/****** Object:  StoredProcedure [dbo].[SCRIVI_LSRLET_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[SCRIVI_LSRLET_LIS]  
			@RICEV			CHAR(6),
			@CATEGORIA			CHAR(2),
			@SERVIZIO			CHAR(2),
			@ATTIVITA			CHAR(2),
			@CON	 			CHAR(15), 
			@CAS	 			CHAR(15), 
			@AUT	 			CHAR(15), 
			@FID	 			CHAR(15), 
			@RAD	 			CHAR(15), 
			@DATAINS			CHAR(8),
			@ORAINS			CHAR(8),
			@TIPOMOV			CHAR(1),
			@FIRMA	 		CHAR(17)


AS

DECLARE		@IDDOC			CHAR(16),
			@RICERIN			CHAR(6),
			@NOMESERVIZIO		VARCHAR(6)

SELECT @NOMESERVIZIO = @CATEGORIA + @SERVIZIO + @ATTIVITA

IF @CON <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRCON_LIS_KEY_DATA_INS +  LSRCON_LIS_KEY_ORA_INS 
	FROM LSRCON_LIS 
	WHERE LSRCON_LIS_KEY_ID_RICEV = @RICEV
		AND LSRCON_LIS_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_LIS VALUES
			(@RICEV,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA, @TIPOMOV,'00000000','LSRCON_LIS',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @CAS <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRADE_LIS_KEY_DATA_INS +  LSRADE_LIS_KEY_ORA_INS 
	FROM LSRADE_LIS 
	WHERE LSRADE_LIS_KEY_ID_RICEV = @RICEV
		AND LSRADE_LIS_KEY_CATEGORIA = @CATEGORIA
		AND LSRADE_LIS_KEY_SERVIZIO = @SERVIZIO
		AND LSRADE_LIS_KEY_ATTIVITA = @ATTIVITA
		AND LSRADE_LIS_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_LIS VALUES
			(@RICEV,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA, @TIPOMOV,'00000000','LSRADE_LIS',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @AUT <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRAUT_LIS_KEY_DATA_INS +  LSRAUT_LIS_KEY_ORA_INS 
	FROM LSRAUT_LIS 
	WHERE LSRAUT_LIS_KEY_ID_RICEV = @RICEV
		AND LSRAUT_LIS_KEY_CATEGORIA = @CATEGORIA
		AND LSRAUT_LIS_KEY_SERVIZIO = @SERVIZIO
		AND LSRAUT_LIS_KEY_ATTIVITA = @ATTIVITA
		AND LSRAUT_LIS_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_LIS VALUES
			(@RICEV,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA, @TIPOMOV,'00000000','LSRAUT_LIS',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @FID <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRFID_LIS_KEY_DATA_INS +  LSRFID_LIS_KEY_ORA_INS 
	FROM LSRFID_LIS 
	WHERE LSRFID_LIS_KEY_ID_RICEV = @RICEV
		AND ( (LSRFID_LIS_KEY_CATEGORIA = @CATEGORIA
			AND LSRFID_LIS_KEY_SERVIZIO = @SERVIZIO
			AND LSRFID_LIS_KEY_ATTIVITA = @ATTIVITA)
			OR LSRFID_LIS_KEY_CATEGORIA + LSRFID_LIS_KEY_SERVIZIO + LSRFID_LIS_KEY_ATTIVITA = @CATEGORIA + @SERVIZIO + '  '
		)
		AND LSRFID_LIS_FLAG_ANAG = '1'
		AND LSRFID_LIS_ANNO_RIF = CONVERT(CHAR(4),GETDATE(),112)


	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_LIS VALUES
			(@RICEV,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA, @TIPOMOV,'00000000','LSRFID_LIS',@IDDOC,'00000000','',@FIRMA,'')
	END

END

IF @RAD <> '0'
BEGIN

	SELECT @IDDOC = NULL

	-- MODIFICA DEL 06/08/2002:
	-- AGGIUNTO CONTROLLO SULLA DATA DI INVIO DEL DOCUMENTO RAD
	IF @CATEGORIA = '01'
	BEGIN
		SELECT @IDDOC =  LSRRAD_LIS_KEY_DATA_INS +  LSRRAD_LIS_KEY_ORA_INS 
		FROM LSRRAD_LIS 
		WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEV
			AND LSRRAD_LIS_KEY_CATEGORIA = @CATEGORIA
			AND LSRRAD_LIS_KEY_SERVIZIO = @SERVIZIO
			AND LSRRAD_LIS_KEY_ATTIVITA = @ATTIVITA
			AND LSRRAD_LIS_TIPO_MOVIMENTAZIONE = @TIPOMOV
			AND LSRRAD_LIS_FLAG_ANAG = '1'
			AND LSRRAD_LIS_DATA_INVIO_DOC >= 
				(SELECT MAX(LSRSER_TEL_DATA_DECOR) FROM LSRSER_TEL  
				WHERE LSRSER_TEL_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
				AND LSRSER_TEL_FLAG_VALIDITA = 'Y' 
				AND LSRSER_TEL_KEY_CATEGORIA + LSRSER_TEL_KEY_SERVIZIO + LSRSER_TEL_KEY_ATTIVITA = @CATEGORIA + @SERVIZIO + @ATTIVITA
				AND LSRSER_TEL_KEY_ID_RICEV = LSRRAD_LIS_KEY_ID_RICEV ) 

	END

	IF @CATEGORIA = '02'
	BEGIN
		SELECT @IDDOC =  LSRRAD_LIS_KEY_DATA_INS +  LSRRAD_LIS_KEY_ORA_INS 
		FROM LSRRAD_LIS 
		WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEV
			AND LSRRAD_LIS_KEY_CATEGORIA = @CATEGORIA
			AND LSRRAD_LIS_KEY_SERVIZIO = @SERVIZIO
			AND LSRRAD_LIS_KEY_ATTIVITA = @ATTIVITA
			AND LSRRAD_LIS_TIPO_MOVIMENTAZIONE = @TIPOMOV
			AND LSRRAD_LIS_FLAG_ANAG = '1'
			AND LSRRAD_LIS_DATA_INVIO_DOC >= 
				(SELECT MAX(LSRSER_CITT_DATA_DECOR) FROM LSRSER_CITT  
				WHERE LSRSER_CITT_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
				AND LSRSER_CITT_FLAG_VALIDITA = 'Y' 
				AND LSRSER_CITT_KEY_CATEGORIA + LSRSER_CITT_KEY_SERVIZIO + LSRSER_CITT_KEY_ATTIVITA = @CATEGORIA + @SERVIZIO + @ATTIVITA
				AND LSRSER_CITT_KEY_ID_RICEV = LSRRAD_LIS_KEY_ID_RICEV ) 

	END

	IF @CATEGORIA = '03'
	BEGIN
		SELECT @IDDOC =  LSRRAD_LIS_KEY_DATA_INS +  LSRRAD_LIS_KEY_ORA_INS 
		FROM LSRRAD_LIS 
		WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEV
			AND LSRRAD_LIS_KEY_CATEGORIA = @CATEGORIA
			AND LSRRAD_LIS_KEY_SERVIZIO = @SERVIZIO
			AND LSRRAD_LIS_KEY_ATTIVITA = @ATTIVITA
			AND LSRRAD_LIS_TIPO_MOVIMENTAZIONE = @TIPOMOV
			AND LSRRAD_LIS_FLAG_ANAG = '1'
			AND LSRRAD_LIS_DATA_INVIO_DOC >= 
				(SELECT MAX(LSRSER_PAG_DATA_DECOR) FROM LSRSER_PAG  
				WHERE LSRSER_PAG_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
				AND LSRSER_PAG_FLAG_VALIDITA = 'Y' 
				AND LSRSER_PAG_KEY_CATEGORIA + LSRSER_PAG_KEY_SERVIZIO + LSRSER_PAG_KEY_ATTIVITA = @CATEGORIA + @SERVIZIO + @ATTIVITA
				AND LSRSER_PAG_KEY_ID_RICEV = LSRRAD_LIS_KEY_ID_RICEV ) 
	END

	IF @CATEGORIA = '04'
	BEGIN
		SELECT @IDDOC =  LSRRAD_LIS_KEY_DATA_INS +  LSRRAD_LIS_KEY_ORA_INS 
		FROM LSRRAD_LIS 
		WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEV
			AND LSRRAD_LIS_KEY_CATEGORIA = @CATEGORIA
			AND LSRRAD_LIS_KEY_SERVIZIO = @SERVIZIO
			AND LSRRAD_LIS_KEY_ATTIVITA = @ATTIVITA
			AND LSRRAD_LIS_TIPO_MOVIMENTAZIONE = @TIPOMOV
			AND LSRRAD_LIS_FLAG_ANAG = '1'
			AND LSRRAD_LIS_DATA_INVIO_DOC >= 
				(SELECT MAX(LSRSER_BIG_DATA_DECOR) FROM LSRSER_BIG  
				WHERE LSRSER_BIG_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
				AND LSRSER_BIG_FLAG_VALIDITA = 'Y' 
				AND LSRSER_BIG_KEY_CATEGORIA + LSRSER_BIG_KEY_SERVIZIO + LSRSER_BIG_KEY_ATTIVITA =@CATEGORIA + @SERVIZIO + @ATTIVITA
				AND LSRSER_BIG_KEY_ID_RICEV = LSRRAD_LIS_KEY_ID_RICEV ) 
	END

	IF @CATEGORIA = '05'
	BEGIN
		SELECT @IDDOC =  LSRRAD_LIS_KEY_DATA_INS +  LSRRAD_LIS_KEY_ORA_INS 
		FROM LSRRAD_LIS 
		WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEV
			AND LSRRAD_LIS_KEY_CATEGORIA = @CATEGORIA
			AND LSRRAD_LIS_KEY_SERVIZIO = @SERVIZIO
			AND LSRRAD_LIS_KEY_ATTIVITA = @ATTIVITA
			AND LSRRAD_LIS_TIPO_MOVIMENTAZIONE = @TIPOMOV
			AND LSRRAD_LIS_FLAG_ANAG = '1'
			AND LSRRAD_LIS_DATA_INVIO_DOC >= 
				(SELECT MAX(LSRSER_ATTI_DATA_DECOR) FROM LSRSER_ATTI  
				WHERE LSRSER_ATTI_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
				AND LSRSER_ATTI_FLAG_VALIDITA = 'Y' 
				AND LSRSER_ATTI_KEY_CATEGORIA +LSRSER_ATTI_KEY_SERVIZIO + LSRSER_ATTI_KEY_ATTIVITA = @CATEGORIA + @SERVIZIO + @ATTIVITA
				AND LSRSER_ATTI_KEY_ID_RICEV = LSRRAD_LIS_KEY_ID_RICEV ) 
	END


	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_LIS VALUES
			(@RICEV,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA, @TIPOMOV,'00000000','LSRRAD_LIS',@IDDOC,'00000000','',@FIRMA,'')
	END
END


--IF @TIPOMOV = 'D'
IF @TIPOMOV = 'D'
BEGIN
	--Se esiste la rinuncia, la sua data deve essere minore o uguale alla data di domani
	SELECT @IDDOC = NULL
	SELECT @IDDOC = LSRRIN_LIS_KEY_DATA_INS + LSRRIN_LIS_KEY_ORA_INS
	 FROM LSRRIN_LIS
	WHERE LSRRIN_LIS_KEY_ID_RICEV = @RICEV
		AND LSRRIN_LIS_KEY_CATEGORIA = @CATEGORIA
		AND LSRRIN_LIS_KEY_SERVIZIO = @SERVIZIO
		AND LSRRIN_LIS_KEY_ATTIVITA = @ATTIVITA
		AND LSRRIN_LIS_FLAG_ANAG = '1'
		AND LSRRIN_LIS_DATA_RINUNCIA <= CONVERT(CHAR,GETDATE() + 1 ,112)
		AND (lsrrin_LIS_data_rinuncia_rinuncia is NULL OR lsrrin_LIS_data_rinuncia_rinuncia ='00000000' or lsrrin_LIS_data_rinuncia_rinuncia = '')
	
	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_LIS VALUES
		(@RICEV, @DATAINS, @ORAINS, @CATEGORIA, @SERVIZIO, @ATTIVITA,@TIPOMOV,'00000000','LSRRIN_LIS',@IDDOC,'00000000','',@FIRMA,'')
	END
END
GO
