/****** Object:  StoredProcedure [dbo].[SCRIVI_LSRLET_APPOGGIO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[SCRIVI_LSRLET_APPOGGIO]

@CODSER 		CHAR(2),	
@DATAINS 		CHAR(8),
@FLAGSETT		CHAR(1),
@RC  			CHAR(50) OUTPUT

AS

DECLARE

@RICEV		CHAR(6),
@RICEAPPO		CHAR(14),
@RICESER		CHAR(6),
--@CODSER		CHAR(2),
@TIPOMOV		CHAR(1),
@DECORDAL		CHAR(8),
@TABDOC		CHAR(8),
@IDDOC		CHAR(16),
@DATAORALET	CHAR(16),

@CODAMM		CHAR(8),
@COGNOME		CHAR(24),
@NOME		CHAR(20),
@PROTDOC		CHAR(20),
@DATADOC		CHAR(8),

@PROTDOC_R		CHAR(20),
@DATADOC_R		CHAR(8),
@PROTDOC_A		CHAR(20),
@DATADOC_A		CHAR(8),

@CODFONTE		CHAR(2),
@ASSOC		CHAR(2),
@CAUSALE		CHAR(100),
@LOTTOM		CHAR(1),
@FONTE		CHAR(2),
@ENTE		CHAR(2),
@NOTE		CHAR(100),
@FLAG_SEGN		CHAR(1),

@PROVVPRO		CHAR(1),
@DATAPROVV		CHAR(8),

--MODIFICA DEL 06/09/01: VARIABILE DA UTILIZZARE PER PRENDERE IL TITOLARE CORRENTE
@DATAVALTIT		CHAR(8),

@DATAAL		CHAR(8),
@ORAINS		CHAR(8),
--@RC			CHAR(50),
@NUMREC		INT,
@LOST			CHAR(8),



@COUNT		INT




DELETE FROM LSRLET_APPOGGIO

SELECT @DATAAL = CONVERT(CHAR,CONVERT(DATETIME,@DATAINS) + 6,112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @NUMREC = 0

IF @FLAGSETT = '0' -- SELEZIONATA STAMPA GIORNALIERA
BEGIN

	DECLARE CUR_LET CURSOR FOR
	
	SELECT LSRLET_KEY_ID_RICEV,LSRLET_COD_SERVIZIO,LSRLET_TIPO_MOVIMENTAZIONE,LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS
	FROM LSRLET 
	WHERE LSRLET_DECOR_DAL <> '00000000'
	AND LSRLET_KEY_DATA_INS = @DATAINS
	AND LSRLET_DATA_LETTERA = '00000000'
	AND LSRLET_COD_SERVIZIO = @CODSER
	GROUP BY LSRLET_KEY_ID_RICEV,LSRLET_COD_SERVIZIO,LSRLET_TIPO_MOVIMENTAZIONE,LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS
	ORDER BY 1,2

END
ELSE
BEGIN

	DECLARE CUR_LET CURSOR FOR

	SELECT LSRLET_KEY_ID_RICEV,LSRLET_COD_SERVIZIO,LSRLET_TIPO_MOVIMENTAZIONE,LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS
	FROM LSRLET 
	WHERE LSRLET_DECOR_DAL <> '00000000'
	AND LSRLET_KEY_DATA_INS BETWEEN @DATAINS AND @DATAAL
	AND LSRLET_DATA_LETTERA <> '00000000'
	AND LSRLET_DATA_LETTERA <> '19000101'
	AND LSRLET_COD_SERVIZIO = @CODSER
	GROUP BY LSRLET_KEY_ID_RICEV,LSRLET_COD_SERVIZIO,LSRLET_TIPO_MOVIMENTAZIONE,LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS
	ORDER BY 1,2

END

DECLARE CUR_LET_REG CURSOR FOR 
SELECT [lsrlet_key_id_ricev], [lsrlet_cod_amm], [lsrlet_cognome], [lsrlet_nome], [lsrlet_cod_servizio], [lsrlet_tipo_movimentazione], [lsrlet_data_decor], [lsrlet_num_prot_documento], [lsrlet_data_prot_documento], [lsrlet_destinatario], 'MF', [lsrlet_causale], [lsrlet_data_ins] 
FROM [Anaconda].[dbo].[lsrlet_appoggio]
WHERE substring(lsrlet_cod_amm,1,2) in   ('AO','TS','UD','GO','PN','CA','SS','NU','OR','CI','OT','VS', 'OG' )
AND LSRLET_KEY_ID_RICEV NOT IN (SELECT LSRLET_KEY_ID_RICEV FROM LSRLET WHERE LSRLET_COD_DESTINATARIO='MF')


BEGIN TRANSACTION

OPEN CUR_LET
FETCH NEXT FROM CUR_LET INTO @RICEV, @CODSER, @TIPOMOV, @DATAORALET
WHILE @@FETCH_STATUS = 0 

BEGIN
	SELECT @ASSOC = NULL
	SELECT @TABDOC = NULL
	SELECT @IDDOC = NULL
	SELECT @NOTE = NULL
	SELECT @CAUSALE = NULL
	SELECT @PROTDOC = NULL
	SELECT @DATADOC = NULL

	SELECT @PROTDOC_A = NULL
	SELECT @DATADOC_A = NULL
	SELECT @PROTDOC_R = NULL
	SELECT @DATADOC_R = NULL

	SELECT @FONTE = NULL
	SELECT @LOTTOM = NULL
	SELECT @ENTE = NULL
	SELECT @PROVVPRO = NULL
	-- FLAG PER LE SEGNALAZIONI (SE è AD 1 SCRIVE UNA SEGNALAZIONE)
	SELECT @FLAG_SEGN = '0'

	SELECT @CODAMM = LSRRIC_COD_AMM 
		FROM LSRRIC
		WHERE LSRRIC_KEY_ID_RICEV = @RICEV

	SELECT @DATAVALTIT = SUBSTRING(@DATAORALET, 1, 8)
	SELECT @DATAVALTIT = CONVERT(CHAR(8), CONVERT(DATETIME, @DATAVALTIT) + 1,112)
	SELECT @COGNOME = LSRTIT_COGNOME, @NOME = LSRTIT_NOME
		FROM LSRTIT
		WHERE LSRTIT_KEY_ID_RICEV = @RICEV
		AND LSRTIT_DATA_VALIDITA =
			(SELECT MAX(LSRTIT_DATA_VALIDITA) 
			FROM LSRTIT
			WHERE LSRTIT_KEY_ID_RICEV = @RICEV
--			AND LSRTIT_DATA_VALIDITA <= @DATAINS
			-- MODIFICA DEL 06/09/01: DEVE ESSERE PRESO IL TITOLARE ALLA DATA DI INSERIMENTO DELLA LETTERA + 1 
			AND LSRTIT_DATA_VALIDITA <= @DATAVALTIT
--			AND LSRTIT_DATA_VALIDITA <= SUBSTRING(@DATAORALET, 1, 8)
			AND LSRTIT_FLAG_VALIDITA = 'Y')
--			AND LSRTIT_FT_VOS <> '00000000')
		AND LSRTIT_FLAG_VALIDITA = 'Y'
--		AND LSRTIT_FT_VOS <> '00000000'

-- ATTIVAZIONE F101

	IF @CODSER = '02' AND @TIPOMOV = 'A'
	BEGIN

		SELECT @DECORDAL= LSRLET_DECOR_DAL,
			@TABDOC = LSRLET_NOME_TAB_DOCUMENTO,
			@IDDOC = LSRLET_FK_TAB_DOCUMENTO,
			@NOTE = LSRLET_NOTE		FROM LSRLET 
		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
		BEGIN

			SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_FONTE = 'A'
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			GROUP BY LSRRAD_COD_ASSOCIAZIONE
	
			IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
			BEGIN
				SELECT @ASSOC = LSRCON_F101_ASSOCIAZIONE
				FROM LSRCON_F101
				WHERE LSRCON_F101_KEY_ID_RICEV = @RICEV
				AND LSRCON_F101_FLAG_ANAG = '1'

				IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
				BEGIN
					SELECT @ASSOC = LSRSER_F101_ASSOCIAZIONE
					FROM LSRSER_F101
					WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
					AND LSRSER_F101_FLAG_VALIDITA = 'Y'
					AND LSRSER_F101_DATA_DECOR =
						(SELECT MAX(LSRSER_F101_DATA_DECOR)
						FROM LSRSER_F101
						WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
						AND  LSRSER_F101_DATA_DECOR <= @DATAINS
						AND  LSRSER_F101_FLAG_VALIDITA = 'Y')
				END
			END
		END

		INSERT INTO LSRLET_APPOGGIO VALUES (
		@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, '', '', 'A', @ASSOC, '',SUBSTRING(@DATAORALET,1,8))

	END


-- DISATTIVAZIONE F101

	IF @CODSER = '02' AND @TIPOMOV = 'D'

	BEGIN

		SELECT @DECORDAL= LSRLET_DECOR_DAL,
			@TABDOC = LSRLET_NOME_TAB_DOCUMENTO,
			@IDDOC = LSRLET_FK_TAB_DOCUMENTO,
			@NOTE = LSRLET_NOTE
		FROM LSRLET 

		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		IF @TABDOC = 'LSRRAD'
		BEGIN
			SELECT @COGNOME = LSRRAD_COGNOME,
				@NOME = LSRRAD_NOME,
				@PROTDOC = LSRRAD_NUM_PROT_DOC,
				@DATADOC = LSRRAD_DATA_INVIO_DOC,
				@FONTE = LSRRAD_FONTE,
				@ASSOC = LSRRAD_COD_ASSOCIAZIONE,
				@LOTTOM = LSRRAD_CAUSALE_LOTTOMATICA,
				@ENTE = LSRRAD_COD_ENTE
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS = @IDDOC

			IF @FONTE = 'Q'
			BEGIN
				SELECT @CAUSALE = 'QUESTURA'
			END

			IF @FONTE = 'R'
			BEGIN
				SELECT @CAUSALE = 'REGIONE'
			END

			IF @FONTE = 'A'
			BEGIN
				SELECT @CAUSALE = 'ASSOCIAZIONE'
			END

			IF @FONTE = 'L'
			BEGIN
				IF @LOTTOM = '3'
				BEGIN
					SELECT @CAUSALE = 'INADEMPIENZE CONTRATTUALI'
				END

				IF @LOTTOM = '7'
				BEGIN
					SELECT @CAUSALE = 'CONTRATTUALISTICA INCOMPLETA'
				END
			END
		END

		IF @TABDOC = 'LSRPRO'
		BEGIN
			SELECT @DATAPROVV =''
			SELECT @PROVVPRO = LSRPRO_KEY_TIPO_REC,
				@DATAPROVV = LSRPRO_DECOR_DAL
			FROM LSRPRO
			WHERE LSRPRO_KEY_ID_RICEV = @RICEV
			AND LSRPRO_DATA_INS + LSRPRO_ORA_INS = @IDDOC

			IF @PROVVPRO = 'I'
			BEGIN
				SELECT @CAUSALE = 'CAMBIO TITOLARE'
				SELECT @DECORDAL = @DATAPROVV
				-- PRENDO L'ASSOCIAZIONE TRA LA CONTRATTUALISTICA CON FLAG ANAG A 2
				IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
				BEGIN

					SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
					FROM LSRRAD

					WHERE LSRRAD_KEY_ID_RICEV = @RICEV
					AND LSRRAD_FONTE = 'A'
					AND LSRRAD_TIPO_SERVIZIO = @CODSER
					AND LSRRAD_FLAG_ANAG = '2'
					GROUP BY LSRRAD_COD_ASSOCIAZIONE
	
					IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
					BEGIN
						SELECT @ASSOC = LSRCON_F101_ASSOCIAZIONE,  @LOST = MAX(LSRCON_F101_DATA_CONTRATTO)
						FROM LSRCON_F101
						WHERE LSRCON_F101_KEY_ID_RICEV = @RICEV
						AND LSRCON_F101_FLAG_ANAG = '2'
						GROUP BY LSRCON_F101_ASSOCIAZIONE

						IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
						BEGIN
							SELECT @ASSOC = LSRSER_F101_ASSOCIAZIONE
							FROM LSRSER_F101
							WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
							AND LSRSER_F101_FLAG_VALIDITA = 'Y'
							AND LSRSER_F101_DATA_DECOR =
								(SELECT MAX(LSRSER_F101_DATA_DECOR)
								FROM LSRSER_F101
								WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
								AND  LSRSER_F101_DATA_DECOR <= @DATAINS
								AND  LSRSER_F101_FLAG_VALIDITA = 'Y')
						END
					END
				END


			END
			IF @PROVVPRO = 'S' 
			BEGIN
				SELECT @CAUSALE = 'SOSPENSIONE LOTTO'
				SELECT @DECORDAL = @DATAPROVV
			END
			IF @PROVVPRO = 'R'
			BEGIN
				SELECT @CAUSALE = 'REVOCA LOTTO'
				SELECT @DECORDAL = @DATAPROVV
			END
			IF @PROVVPRO = 'M'
			BEGIN
				SELECT @CAUSALE = 'SMANTELLAMENTO TERMINALI'
				SELECT @DECORDAL = @DATAPROVV
			END

		END

		IF @TABDOC = 'LSRRIN'
		BEGIN
			SELECT @CAUSALE = 'RINUNCIA'
		END
 
		IF RTRIM(LTRIM(@TABDOC)) = ''
		BEGIN
			SELECT @PROTDOC = ''
			SELECT @DATADOC = ''
			SELECT @CAUSALE = @NOTE
		END
		
		IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
		BEGIN

			SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_FONTE = 'A'
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			GROUP BY LSRRAD_COD_ASSOCIAZIONE
	
			IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
			BEGIN
				SELECT @ASSOC = LSRCON_F101_ASSOCIAZIONE
				FROM LSRCON_F101
				WHERE LSRCON_F101_KEY_ID_RICEV = @RICEV
				AND LSRCON_F101_FLAG_ANAG = '1'

				IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
				BEGIN
					SELECT @ASSOC = LSRSER_F101_ASSOCIAZIONE
					FROM LSRSER_F101
					WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
					AND LSRSER_F101_FLAG_VALIDITA = 'Y'
					AND LSRSER_F101_DATA_DECOR =
						(SELECT MAX(LSRSER_F101_DATA_DECOR)
						FROM LSRSER_F101
						WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
						AND  LSRSER_F101_DATA_DECOR <= @DATAINS
						AND  LSRSER_F101_FLAG_VALIDITA = 'Y')
				END
			END
		END

		INSERT INTO LSRLET_APPOGGIO VALUES (
		@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC, @DATADOC, 'A', @ASSOC, @CAUSALE,SUBSTRING(@DATAORALET,1,8))

	END

-- RIATTIVAZIONE F101

	IF @CODSER = '02' AND @TIPOMOV = 'R'
	BEGIN

		SELECT @DECORDAL= LSRLET_DECOR_DAL,
			@TABDOC = LSRLET_NOME_TAB_DOCUMENTO,
			@IDDOC = LSRLET_FK_TAB_DOCUMENTO,
			@NOTE = LSRLET_NOTE
		FROM LSRLET 
		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		IF @TABDOC = 'LSRRAD'
		BEGIN
			SELECT @COGNOME = LSRRAD_COGNOME,
				@NOME = LSRRAD_NOME,
				@PROTDOC = LSRRAD_NUM_PROT_DOC,
				@DATADOC = LSRRAD_DATA_INVIO_DOC,
				@FONTE = LSRRAD_FONTE,
				@ASSOC = LSRRAD_COD_ASSOCIAZIONE,
				@LOTTOM = LSRRAD_CAUSALE_LOTTOMATICA,
				@ENTE = LSRRAD_COD_ENTE
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS = @IDDOC

			IF @FONTE = 'Q'
			BEGIN
				SELECT @CAUSALE = 'QUESTURA'
			END

			IF @FONTE = 'R'
			BEGIN
				SELECT @CAUSALE = 'REGIONE'
			END

			IF @FONTE = 'A'
			BEGIN
				SELECT @CAUSALE = 'ASSOCIAZIONE'
			END

			IF @FONTE = 'L'
			BEGIN				IF @LOTTOM = '3'
				BEGIN
					SELECT @CAUSALE = 'RISOLUZIONE INADEMPIENZE'
				END
				IF @LOTTOM = '5'
				BEGIN
					SELECT @CAUSALE = 'CAMBIO TITOLARE'
				END
				IF @LOTTOM = '8'
				BEGIN
					SELECT @CAUSALE = 'RIATTIVAZIONE LOTTO'
				END
			END
		END

 
		IF RTRIM(LTRIM(@TABDOC)) <>'LSRRAD'
		BEGIN
			SELECT @CAUSALE = @NOTE
		END

		IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
		BEGIN
			SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_FONTE = 'A'			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			GROUP BY LSRRAD_COD_ASSOCIAZIONE
	
			IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
			BEGIN
				SELECT @ASSOC = LSRCON_F101_ASSOCIAZIONE
				FROM LSRCON_F101
				WHERE LSRCON_F101_KEY_ID_RICEV = @RICEV
				AND LSRCON_F101_FLAG_ANAG = '1'

				IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
				BEGIN
					SELECT @ASSOC = LSRSER_F101_ASSOCIAZIONE
					FROM LSRSER_F101
					WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
					AND LSRSER_F101_FLAG_VALIDITA = 'Y'
					AND LSRSER_F101_DATA_DECOR =
						(SELECT MAX(LSRSER_F101_DATA_DECOR)
						FROM LSRSER_F101
						WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
						AND  LSRSER_F101_DATA_DECOR <= @DATAINS
						AND  LSRSER_F101_FLAG_VALIDITA = 'Y')
				END
			END
		END

		INSERT INTO LSRLET_APPOGGIO VALUES (
		@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC, @DATADOC, 'A', @ASSOC, @CAUSALE,SUBSTRING(@DATAORALET,1,8))

	END

-- ATTIVAZIONE BOLLO

	IF @CODSER = '05' AND @TIPOMOV = 'A'
	BEGIN
		DECLARE CUR_RAD CURSOR FOR
		SELECT LSRLET_DECOR_DAL, LSRLET_NOME_TAB_DOCUMENTO, LSRLET_FK_TAB_DOCUMENTO, LSRLET_NOTE
		FROM LSRLET 
		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		OPEN CUR_RAD
		FETCH NEXT FROM CUR_RAD INTO @DECORDAL, @TABDOC, @IDDOC, @NOTE
		WHILE @@FETCH_STATUS = 0 

		BEGIN
			IF @TABDOC = 'LSRRAD'
			BEGIN
				SELECT @COGNOME = LSRRAD_COGNOME,
					@NOME = LSRRAD_NOME,
					@PROTDOC = LSRRAD_NUM_PROT_DOC,
					@DATADOC = LSRRAD_DATA_INVIO_DOC,
					@FONTE = LSRRAD_FONTE,
					@ASSOC = LSRRAD_COD_ASSOCIAZIONE,
					@LOTTOM = LSRRAD_CAUSALE_LOTTOMATICA,
					@ENTE = LSRRAD_COD_ENTE
				FROM LSRRAD
				WHERE LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS = @IDDOC

				IF @FONTE = 'R'
				BEGIN
					SELECT @CAUSALE = @NOTE 
					INSERT INTO LSRLET_APPOGGIO VALUES (
					@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC, @DATADOC, 'R', @ENTE, @CAUSALE,SUBSTRING(@DATAORALET,1,8))

				END

				IF @FONTE = 'A'
				BEGIN
					SELECT @CAUSALE = @NOTE  
					INSERT INTO LSRLET_APPOGGIO VALUES (
					@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC, @DATADOC, 'A', @ASSOC, @CAUSALE,SUBSTRING(@DATAORALET,1,8))
				END

			END

			IF RTRIM(LTRIM(@TABDOC)) = ''
			BEGIN
				SELECT @PROTDOC = ''
				SELECT @DATADOC = ''
				SELECT @CAUSALE = @NOTE
		
				INSERT INTO LSRLET_APPOGGIO VALUES (
				@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC, @DATADOC, 'A', '', @CAUSALE,SUBSTRING(@DATAORALET,1,8))
				INSERT INTO LSRLET_APPOGGIO VALUES (
				@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC, @DATADOC, 'R', '', @CAUSALE,SUBSTRING(@DATAORALET,1,8))
			END
			
			FETCH NEXT FROM CUR_RAD INTO @DECORDAL, @TABDOC, @IDDOC, @NOTE
		END
		
		CLOSE CUR_RAD
		DEALLOCATE CUR_RAD
	END --DE CHEE

-- DISATTIVAZIONE/RIATTIVAZIONE BOLLO

	IF @CODSER = '05' AND (@TIPOMOV = 'R' OR @TIPOMOV = 'D')
	BEGIN
		SELECT @DECORDAL= LSRLET_DECOR_DAL,
		@TABDOC = LSRLET_NOME_TAB_DOCUMENTO,
		@IDDOC = LSRLET_FK_TAB_DOCUMENTO,
		@NOTE = LSRLET_NOTE
		FROM LSRLET 
		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		SELECT @ENTE = ''
		SELECT @ASSOC =''
/*
		SELECT @ENTE = LSRRAD_COD_ENTE
		FROM LSRRAD
		WHERE LSRRAD_KEY_ID_RICEV = @RICEV
		AND LSRRAD_FONTE = 'R'
		AND LSRRAD_TIPO_SERVIZIO =@CODSER
		AND LSRRAD_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRRAD_FLAG_ANAG = '1'

		SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE
		FROM LSRRAD
		WHERE LSRRAD_KEY_ID_RICEV = @RICEV
		AND LSRRAD_FONTE = 'A'
		AND LSRRAD_TIPO_SERVIZIO = @CODSER
		AND LSRRAD_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRRAD_FLAG_ANAG = '1'

*/
		SELECT @ENTE = LSRRAD_COD_ENTE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
		FROM LSRRAD
		WHERE LSRRAD_KEY_ID_RICEV = @RICEV
		AND LSRRAD_FONTE = 'R'
		AND LSRRAD_TIPO_SERVIZIO = @CODSER
		AND LSRRAD_FLAG_ANAG = '1'
		GROUP BY LSRRAD_COD_ENTE

		SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
		FROM LSRRAD
		WHERE LSRRAD_KEY_ID_RICEV = @RICEV
		AND LSRRAD_FONTE = 'A'
		AND LSRRAD_TIPO_SERVIZIO = @CODSER
		AND LSRRAD_FLAG_ANAG = '1'
		GROUP BY LSRRAD_COD_ASSOCIAZIONE
			
		IF @TABDOC = 'LSRRAD'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR
			SELECT LSRLET_DECOR_DAL,
				LSRLET_NOME_TAB_DOCUMENTO,
				LSRLET_FK_TAB_DOCUMENTO,
				LSRLET_NOTE
			FROM LSRLET 
			WHERE LSRLET_DECOR_DAL <> '00000000'
			AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
			AND LSRLET_COD_SERVIZIO = @CODSER
			AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
			AND LSRLET_KEY_ID_RICEV = @RICEV
			ORDER BY 1

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @DECORDAL, @TABDOC, @IDDOC, @NOTE
			WHILE @@FETCH_STATUS = 0 

			BEGIN

				SELECT @COGNOME = LSRRAD_COGNOME,
					@NOME = LSRRAD_NOME,
					@PROTDOC = LSRRAD_NUM_PROT_DOC,
					@DATADOC = LSRRAD_DATA_INVIO_DOC,
					@FONTE = LSRRAD_FONTE,
					@ASSOC = LSRRAD_COD_ASSOCIAZIONE,
					@LOTTOM = LSRRAD_CAUSALE_LOTTOMATICA,
					@ENTE = LSRRAD_COD_ENTE
				FROM LSRRAD
				WHERE LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS = @IDDOC

				SELECT @CAUSALE = ''

				IF SUBSTRING(@NOTE,1,12) = 'SEGNALAZIONE'
				BEGIN
					SELECT @FLAG_SEGN = '1'
				END
	
				IF @FONTE = 'R'
				BEGIN
					SELECT @DATADOC_R = @DATADOC
					SELECT @PROTDOC_R = @PROTDOC
					
					SELECT @CAUSALE = LSRENT_DESCRIZIONE
						FROM LSRENT
						WHERE LSRENT_KEY_COD_ENTE = @ENTE

					SELECT @CAUSALE = @NOTE +  @CAUSALE + ' ' + @DATADOC + ' ' + @PROTDOC

					IF @FLAG_SEGN = '1'
					BEGIN
						INSERT INTO LSRLET_APPOGGIO VALUES (
						@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC, @DATADOC, 'R', @ENTE, @CAUSALE,SUBSTRING(@DATAORALET,1,8))
					END
	
				END

				IF @FONTE = 'A'
				BEGIN
					SELECT @DATADOC_A = @DATADOC
					SELECT @PROTDOC_A = @PROTDOC
					
					SELECT @CAUSALE = @NOTE +  'ASSOCIAZIONE'

					IF @FLAG_SEGN = '1'
					BEGIN
						INSERT INTO LSRLET_APPOGGIO VALUES (
						@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC, @DATADOC, 'A', @ASSOC, @CAUSALE,SUBSTRING(@DATAORALET,1,8))
					END

				END

				IF @FONTE = 'L'
				BEGIN
					IF @TIPOMOV = 'R'
					BEGIN
		 				IF @LOTTOM = '3'
						BEGIN
							SELECT @CAUSALE = 'RISOLUZIONE INADEMPIENZE'
						END
						IF @LOTTOM = '5'
						BEGIN
							SELECT @CAUSALE = 'CAMBIO TITOLARE'
						END
						IF @LOTTOM = '8'
						BEGIN
							SELECT @CAUSALE = 'RIATTIVAZIONE LOTTO'
						END
					END
					IF @TIPOMOV = 'D'
					BEGIN
		 				IF @LOTTOM = '3'
						BEGIN
							SELECT @CAUSALE = 'INADEMPIENZE CONTRATTUALI'
						END
						IF @LOTTOM = '7'
						BEGIN
							SELECT @CAUSALE = 'CONTRATTUALISTICA INCOMPLETA'
						END
					END
				END
				--IF SUBSTRING(@CODAMM,1,2) = 'AO' OR SUBSTRING(@CODAMM,1,2)='CA'  OR SUBSTRING(@CODAMM,1,2)='SS' OR SUBSTRING(@CODAMM,1,2)='NU' OR SUBSTRING(@CODAMM,1,2)='OR' OR SUBSTRING(@CODAMM,1,2)='TS' OR SUBSTRING(@CODAMM,1,2)='UD'  OR SUBSTRING(@CODAMM,1,2)='GO'  OR SUBSTRING(@CODAMM,1,2)='PN'  AND (@ENTE<>'MF' AND @ASSOC<>'MF')
				--BEGIN	
				--	select @count =COUNT(*)
				--	from lsrlet_appoggio
				---	where lsrlet_key_id_ricev=@ricev
				--	and lsrlet_cod_destinatario<>'MF'
				--	if @count=0 
				--	begin
		    		--		INSERT INTO LSRLET_APPOGGIO VALUES (
				--		@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC_R, @DATADOC_R, 'R', 'MF', @CAUSALE,SUBSTRING(@DATAORALET,1,8))
--select @count=0
		--			end
    					
			--	END

				FETCH NEXT FROM CUR_RAD INTO @DECORDAL, @TABDOC, @IDDOC, @NOTE
			END

			CLOSE CUR_RAD
			DEALLOCATE CUR_RAD
		END
		

------------------------

		IF RTRIM(LTRIM(@TABDOC)) = ''
		BEGIN
			SELECT @PROTDOC_A = ''
			SELECT @DATADOC_A = ''

			SELECT @PROTDOC_R = ''
			SELECT @DATADOC_R = ''

			SELECT @CAUSALE = @NOTE
		END

		IF @TABDOC = 'LSRPRO'
		BEGIN
			SELECT @DATAPROVV =''
			SELECT @PROVVPRO = LSRPRO_KEY_TIPO_REC,
				@DATAPROVV = LSRPRO_DECOR_DAL
			FROM LSRPRO
			WHERE LSRPRO_KEY_ID_RICEV = @RICEV
			AND LSRPRO_DATA_INS + LSRPRO_ORA_INS = @IDDOC

			IF @PROVVPRO = 'I'
			BEGIN
				SELECT @DECORDAL = @DATAPROVV
				SELECT @CAUSALE = 'CAMBIO TITOLARE'
				--PRENDO L'ASSOCIAZIONE TRA LA CONTRATTUALISTICA CON FLAG ANAG A 2
				IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
				BEGIN

					SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
					FROM LSRRAD
					WHERE LSRRAD_KEY_ID_RICEV = @RICEV
					AND LSRRAD_FONTE = 'A'
					AND LSRRAD_TIPO_SERVIZIO = @CODSER	
					AND LSRRAD_FLAG_ANAG = '2'
					GROUP BY LSRRAD_COD_ASSOCIAZIONE
						
					IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
					BEGIN
						SELECT @ASSOC = LSRCON_BOLLO_ASSOCIAZIONE, @LOST = MAX(LSRCON_BOLLO_DATA_CONTRATTO)
						FROM LSRCON_BOLLO
						WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEV
						AND LSRCON_BOLLO_FLAG_ANAG = '2'
						GROUP BY LSRCON_BOLLO_ASSOCIAZIONE
		
						IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
						BEGIN
							SELECT @ASSOC = LSRSER_BOLLO_ASSOCIAZIONE
							FROM LSRSER_BOLLO
							WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
							AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
							AND LSRSER_BOLLO_DATA_DECOR =
								(SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
								FROM LSRSER_BOLLO
								WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
								AND  LSRSER_BOLLO_DATA_DECOR <= @DATAINS
								AND  LSRSER_BOLLO_FLAG_VALIDITA = 'Y')
						END
					END
				END
			END

			IF @PROVVPRO = 'S' 
			BEGIN
				SELECT @CAUSALE = 'SOSPENSIONE LOTTO'
				SELECT @DECORDAL = @DATAPROVV
			END
			IF @PROVVPRO = 'R'
			BEGIN
				SELECT @CAUSALE = 'REVOCA LOTTO'
				SELECT @DECORDAL = @DATAPROVV
			END
			IF @PROVVPRO = 'M'
			BEGIN
				SELECT @CAUSALE = 'SMANTELLAMENTO TERMINALI'
				SELECT @DECORDAL = @DATAPROVV
			END
		END

		IF @TABDOC = 'LSRRIN'
		BEGIN
			SELECT @CAUSALE = 'RINUNCIA'
		END

		IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
		BEGIN

			SELECT @ASSOC = LSRRAD_COD_ASSOCIAZIONE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_FONTE = 'A'
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			GROUP BY LSRRAD_COD_ASSOCIAZIONE
	
			IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
			BEGIN
				SELECT @ASSOC = LSRCON_BOLLO_ASSOCIAZIONE
				FROM LSRCON_BOLLO
				WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEV
				AND LSRCON_BOLLO_FLAG_ANAG = '1'
				AND LSRCON_BOLLO_TIPO_DOC IN ('C','A')
				ORDER BY LSRCON_BOLLO_TIPO_DOC

				IF @ASSOC = '' OR @ASSOC IS NULL OR @ASSOC = ' '
				BEGIN
					SELECT @ASSOC = LSRSER_BOLLO_ASSOCIAZIONE
					FROM LSRSER_BOLLO
					WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV					AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'

					AND LSRSER_BOLLO_DATA_DECOR =
						(SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
						FROM LSRSER_BOLLO
						WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
						AND  LSRSER_BOLLO_DATA_DECOR <= @DATAINS
						AND  LSRSER_BOLLO_FLAG_VALIDITA = 'Y')
				END
			END
		END
		IF @ENTE = '' OR @ENTE IS NULL OR @ENTE = ' '
		BEGIN
			SELECT @ENTE = LSRRAD_COD_ENTE, @LOST = MAX(LSRRAD_DATA_INVIO_DOC)
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_FONTE = 'R'
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			GROUP BY LSRRAD_COD_ENTE
		END

		IF @FLAG_SEGN = '0'
		BEGIN
			INSERT INTO LSRLET_APPOGGIO VALUES (
			@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC_A, @DATADOC_A, 'A', @ASSOC, @CAUSALE,SUBSTRING(@DATAORALET,1,8))

			INSERT INTO LSRLET_APPOGGIO VALUES (
			@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, @PROTDOC_R, @DATADOC_R, 'R', @ENTE, @CAUSALE,SUBSTRING(@DATAORALET,1,8))
			
		
		END

                                        
	END

-- ATTIVAZIONE TRIS

	IF @CODSER = '08' AND @TIPOMOV = 'A'
	BEGIN

		SELECT @DECORDAL= LSRLET_DECOR_DAL,
			@TABDOC = LSRLET_NOME_TAB_DOCUMENTO,
			@IDDOC = LSRLET_FK_TAB_DOCUMENTO,
			@NOTE = LSRLET_NOTE
		FROM LSRLET 
		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		INSERT INTO LSRLET_APPOGGIO VALUES (
		@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, '', '', 'T', '', '',SUBSTRING(@DATAORALET,1,8))

	END

-- DISATTIVAZIONE TRIS

	IF @CODSER = '08' AND (@TIPOMOV = 'D' OR @TIPOMOV = 'S')
	BEGIN

		SELECT @DECORDAL= LSRLET_DECOR_DAL,
			@TABDOC = LSRLET_NOME_TAB_DOCUMENTO,
			@IDDOC = LSRLET_FK_TAB_DOCUMENTO,
			@NOTE = LSRLET_NOTE

		FROM LSRLET 
		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		IF @TABDOC = 'LSRRAD'
		BEGIN
			SELECT @COGNOME = LSRRAD_COGNOME,
				@NOME = LSRRAD_NOME,
				@PROTDOC = LSRRAD_NUM_PROT_DOC,
				@DATADOC = LSRRAD_DATA_INVIO_DOC,
				@FONTE = LSRRAD_FONTE,
				@ASSOC = LSRRAD_COD_ASSOCIAZIONE,
				@LOTTOM = LSRRAD_CAUSALE_LOTTOMATICA,
				@ENTE = LSRRAD_COD_ENTE
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS = @IDDOC

			IF SUBSTRING(@NOTE,1,12) <> 'SEGNALAZIONE'
			BEGIN
	
				IF @FONTE = 'Q'
				BEGIN
					SELECT @CAUSALE = 'QUESTURA'
				END

				IF @FONTE = 'L'
				BEGIN
					IF @LOTTOM = '3'
					BEGIN
						SELECT @CAUSALE = 'INADEMPIENZE CONTRATTUALI'
					END
					IF @LOTTOM = '7'
					BEGIN
						SELECT @CAUSALE = 'CONTRATTUALISTICA INCOMPLETA'
					END
				END
			END
			ELSE
			BEGIN
-- MODIFICA DEL 25/03/2002: SE LE NOTE PRESE DA LET CORRISPONDONO A "SEGNALAZIONI" LA CAUSALE NON VIENE MODIFICATA IN SCRITTURA SULLA LET APPOGGIO, CONSENTENDO LA SEGNALAZIONE AL POSTO DELLA MOVIMENTAZIONE

				SELECT @CAUSALE = @NOTE
			END
			
		END

		IF @TABDOC = 'LSRPRO'
		BEGIN
			SELECT @DATAPROVV =''
			SELECT @PROVVPRO = LSRPRO_KEY_TIPO_REC,
				@DATAPROVV = LSRPRO_DECOR_DAL
			FROM LSRPRO
			WHERE LSRPRO_KEY_ID_RICEV = @RICEV
			AND LSRPRO_DATA_INS + LSRPRO_ORA_INS = @IDDOC

			IF @PROVVPRO = 'I'
			BEGIN
				SELECT @CAUSALE = 'CAMBIO TITOLARE'
				SELECT @DECORDAL = @DATAPROVV
			END
			IF @PROVVPRO = 'S' 
			BEGIN
				SELECT @CAUSALE = 'SOSPENSIONE LOTTO'
				SELECT @DECORDAL = @DATAPROVV
			END
			IF @PROVVPRO = 'R'
			BEGIN
				SELECT @CAUSALE = 'REVOCA LOTTO'
				SELECT @DECORDAL = @DATAPROVV
			END
			IF @PROVVPRO = 'M'
			BEGIN
				SELECT @CAUSALE = 'SMANTELLAMENTO TERMINALI'
				SELECT @DECORDAL = @DATAPROVV
			END
		END


		IF @TABDOC = 'LSRRIN'
		BEGIN
			SELECT @CAUSALE = 'RINUNCIA'
		END
 
		IF RTRIM(LTRIM(@TABDOC)) = ''
		BEGIN
			SELECT @PROTDOC = ''
			SELECT @DATADOC = ''
			SELECT @CAUSALE = @NOTE
		END


		INSERT INTO LSRLET_APPOGGIO VALUES (
		@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, '', '', 'T', '', @CAUSALE,SUBSTRING(@DATAORALET,1,8))


	END

-- RIATTIVAZIONE TRIS

	IF @CODSER = '08' AND @TIPOMOV = 'R'
	BEGIN

		SELECT @DECORDAL= LSRLET_DECOR_DAL,
			@TABDOC = LSRLET_NOME_TAB_DOCUMENTO,
			@IDDOC = LSRLET_FK_TAB_DOCUMENTO,
			@NOTE = LSRLET_NOTE
		FROM LSRLET 
		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		IF @TABDOC = 'LSRRAD'
		BEGIN
			SELECT @COGNOME = LSRRAD_COGNOME,
				@NOME = LSRRAD_NOME,
				@PROTDOC = LSRRAD_NUM_PROT_DOC,
				@DATADOC = LSRRAD_DATA_INVIO_DOC,
				@FONTE = LSRRAD_FONTE,
				@ASSOC = LSRRAD_COD_ASSOCIAZIONE,
				@LOTTOM = LSRRAD_CAUSALE_LOTTOMATICA,
				@ENTE = LSRRAD_COD_ENTE
			FROM LSRRAD
			WHERE LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS = @IDDOC

			IF @FONTE = 'Q'
			BEGIN
				SELECT @CAUSALE = 'QUESTURA'
			END

			IF @FONTE = 'R'
			BEGIN
				SELECT @CAUSALE = 'REGIONE'
			END

			IF @FONTE = 'A'
			BEGIN
				SELECT @CAUSALE = 'ASSOCIAZIONE'
			END

			IF @FONTE = 'L'
			BEGIN
				IF @LOTTOM = '3'
				BEGIN
                                                                	IF @NOTE <>  'RISOLUZIONE INADEMPIENZE' AND @NOTE <> 'RIATTIVAZIONE OFFERTA PACCHETTO'
					BEGIN
						SELECT @CAUSALE = @NOTE
					END
					ELSE
					BEGIN
						SELECT @CAUSALE = 'RISOLUZIONE INADEMPIENZE'
					END
				END
				IF @LOTTOM = '5'

				BEGIN
					SELECT @CAUSALE = 'CAMBIO TITOLARE'
				END
				IF @LOTTOM = '8'
				BEGIN
					SELECT @CAUSALE = 'RIATTIVAZIONE LOTTO'
				END
			END
		END

 
		IF RTRIM(LTRIM(@TABDOC)) <> 'LSRRAD'
		BEGIN
			SELECT @CAUSALE = @NOTE
		END

		INSERT INTO LSRLET_APPOGGIO VALUES (
		@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL, '', '', 'T', '', @CAUSALE,SUBSTRING(@DATAORALET,1,8))


	END

-- MOVIMENTAZIONI LOTTO

	IF @CODSER = '01'
	BEGIN

		SELECT @DECORDAL= LSRLET_DECOR_DAL,
			@TABDOC = LSRLET_NOME_TAB_DOCUMENTO,
			@IDDOC = LSRLET_FK_TAB_DOCUMENTO,
			@NOTE = LSRLET_NOTE
		FROM LSRLET 
		WHERE LSRLET_DECOR_DAL <> '00000000'
		AND LSRLET_KEY_DATA_INS  + LSRLET_KEY_ORA_INS= @DATAORALET
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_ID_RICEV = @RICEV
		ORDER BY 1

		SELECT @PROVVPRO = LSRPRO_KEY_TIPO_REC,
			@PROTDOC = LSRPRO_KEY_PROG_PROVV,
			@DATADOC = LSRPRO_KEY_DATA_PROVV
		FROM LSRPRO
		WHERE LSRPRO_KEY_ID_RICEV = @RICEV
		AND LSRPRO_DATA_INS + LSRPRO_ORA_INS = @IDDOC

		IF @PROVVPRO = 'I'
		BEGIN
			SELECT @CAUSALE = 'CAMBIO TITOLARE'
		END
		IF @PROVVPRO = 'A'
		BEGIN
			SELECT @CAUSALE = 'RIATTIVAZIONE LOTTO'
		END
		IF @PROVVPRO = 'S' 
		BEGIN
			SELECT @CAUSALE = 'SOSPENSIONE LOTTO'
		END
		IF @PROVVPRO = 'R'
		BEGIN
			SELECT @CAUSALE = 'REVOCA LOTTO'
		END
		IF @PROVVPRO = 'M'
		BEGIN
			SELECT @CAUSALE = 'SMANTELLAMENTO TERMINALI'
		END


		INSERT INTO LSRLET_APPOGGIO VALUES (
		@RICEV, @CODAMM, @COGNOME, @NOME, @CODSER, @TIPOMOV, @DECORDAL,@PROTDOC, @DATADOC, 'L', '', @CAUSALE,SUBSTRING(@DATAORALET,1,8))


	END

	IF @FLAGSETT = '0' -- SELEZIONATA STAMPA GIORNALIERA
	BEGIN
		UPDATE LSRLET SET LSRLET_DATA_LETTERA = CONVERT(CHAR,GETDATE(),112)
		WHERE LSRLET_KEY_ID_RICEV = @RICEV
		AND LSRLET_COD_SERVIZIO = @CODSER
		AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORALET
	END

	FETCH NEXT FROM CUR_LET INTO @RICEV, @CODSER, @TIPOMOV, @DATAORALET

END

-- X VALORIZZARE GLI ENTI SCONOSCIUTI
UPDATE LSRLET_APPOGGIO
SET LSRLET_COD_DESTINATARIO = 
	(SELECT LSRDEC_PROV_COD_ENTE FROM LSRDEC_PROV
	WHERE LSRDEC_PROV_SIGLA = SUBSTRING(LSRLET_COD_AMM,1,2))
WHERE LSRLET_DESTINATARIO = 'R'
AND( LSRLET_COD_DESTINATARIO IS NULL
OR LSRLET_COD_DESTINATARIO IN ('', ' ', '  ') )

UPDATE LSRLET_APPOGGIO 
SET LSRLET_COD_DESTINATARIO = 'P1'
WHERE LSRLET_DESTINATARIO = 'R'
AND LSRLET_COD_DESTINATARIO = 'PA'
AND LSRLET_CAUSALE NOT LIKE 'CAMBIO%'


IF @CODSER='05'
BEGIN


	insert into lsrlet_appoggio  select 
	lsrlet_key_id_ricev, [lsrlet_cod_amm], [lsrlet_cognome], [lsrlet_nome], [lsrlet_cod_servizio], [lsrlet_tipo_movimentazione], [lsrlet_data_decor], [lsrlet_num_prot_documento], [lsrlet_data_prot_documento], [lsrlet_destinatario], 'MF', [lsrlet_causale], [lsrlet_data_ins] 
	FROM [Anaconda].[dbo].[lsrlet_appoggio]
	WHERE substring(lsrlet_cod_amm,1,2) in ('AO','TS','UD','GO','PN','CA','SS','NU','OR','CI','OT','VS', 'OG'  )
	AND LSRLET_KEY_ID_RICEV NOT IN (SELECT LSRLET_KEY_ID_RICEV FROM LSRLET WHERE LSRLET_COD_DESTINATARIO='MF')
	and lsrlet_cod_destinatario not in  ('1','',' ')

	insert into lsrlet_appoggio  
	select distinct lsrlet_key_id_ricev, [lsrlet_cod_amm], [lsrlet_cognome], [lsrlet_nome], [lsrlet_cod_servizio], [lsrlet_tipo_movimentazione], [lsrlet_data_decor], [lsrlet_num_prot_documento], [lsrlet_data_prot_documento], 'R' lsrlet_destinatario,
	 case substring(lsrlet_cod_amm,1,2) 
	when'SS'then'CA'
	when'OR'then'CA'
	when'CA'then'CA'
	when'NU'then'CA'
	when'CI'then'CA'
	when'OT'then'CA'
	when'VS'then 'CA' 
	when'OG'then'CA'
	when'UD'then'TS'
	when'TS'then'TS'
	when'GO'then'TS'
	when'PN'then'PN'
	when'AO'then'AO'
	else substring(lsrlet_cod_amm,1,2)
	end lsrlet_cod_destinatario, [lsrlet_causale], [lsrlet_data_ins] 
	FROM [Anaconda].[dbo].[lsrlet_appoggio] a
	where LSRLET_KEY_ID_RICEV IN (SELECT distinct  LSRLET_KEY_ID_RICEV FROM LSRLET_appoggio WHERE LSRLET_COD_DESTINATARIO in ('1','',' ','MF')
	and  LSRLET_KEY_ID_RICEV not in (SELECT LSRLET_KEY_ID_RICEV FROM LSRLET_appoggio WHERE LSRLET_COD_DESTINATARIO in  ('CA','TS','AO'))
	and lsrlet_cod_destinatario not in  ('CA','TS','AO')
	and substring(lsrlet_cod_amm,1,2) in ('AO','TS','UD','GO','PN','CA','SS','NU','OR','CI','OT','VS', 'OG'  ))
	and (lsrlet_num_prot_documento in (select max(lsrlet_num_prot_documento) from lsrlet_appoggio b where b.lsrlet_key_id_ricev=a.lsrlet_key_id_ricev) or lsrlet_num_prot_documento is null)

END
--UPDATE LSRLET_APPOGGIO 
--SET LSRLET_COD_DESTINATARIO='CA'
--where lsrlet_destinatario='R'
--and LSRLET_COD_DESTINATARIO='MF'
--and substring(lsrlet_cod_amm,1,2) in ('CA','OR','NU','SS')

--UPDATE LSRLET_APPOGGIO 
--SET LSRLET_COD_DESTINATARIO='TS'
--where lsrlet_destinatario='R'
--and LSRLET_COD_DESTINATARIO='MF'
--and substring(lsrlet_cod_amm,1,2) in ('GO','PN','TS','UD')

--UPDATE LSRLET_APPOGGIO 
---SET LSRLET_COD_DESTINATARIO='AO'
--where lsrlet_destinatario='R'
--anD LSRLET_COD_DESTINATARIO='MF'
--and substring(lsrlet_cod_amm,1,2) = 'AO'

SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)

COMMIT TRANSACTION

CLOSE CUR_LET
DEALLOCATE CUR_LET
GO
