/****** Object:  StoredProcedure [dbo].[SCRIVI_LSRLET]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[SCRIVI_LSRLET] 
 
	@RICEV			CHAR(6),
	@CODSER 			CHAR(2), 
	@CON	 			CHAR(15), 
	@CAS	 			CHAR(15), 
	@FID	 			CHAR(15), 
	@APS	 			CHAR(15), 
	@RAD	 			CHAR(15), 
	@DATAINS			CHAR(8),
	@ORAINS			CHAR(8),
	@TIPOMOV			CHAR(1),
	@FIRMA	 		CHAR(17)


AS

DECLARE		

@IDDOC			CHAR(16),
@RICERIN			CHAR(6)


IF @CON <> '0'
BEGIN
	IF @CODSER = '02'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRCON_F101_KEY_DATA_INS +  LSRCON_F101_KEY_ORA_INS 
		FROM LSRCON_F101 WHERE LSRCON_F101_KEY_ID_RICEV = @RICEV
		AND LSRCON_F101_TIPO_DOC = 'C'
		AND LSRCON_F101_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRCON_F101',@IDDOC,'00000000','',@FIRMA,'')
		END
	END

	IF @CODSER = '05'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRCON_BOLLO_KEY_DATA_INS +  LSRCON_BOLLO_KEY_ORA_INS 
		FROM LSRCON_BOLLO WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRCON_BOLLO_TIPO_DOC = 'C'
		AND LSRCON_BOLLO_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRCON_BOLLO',@IDDOC,'00000000','',@FIRMA,'')
		END

	END

	IF @CODSER = '08'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRCON_TRIS_KEY_DATA_INS +  LSRCON_TRIS_KEY_ORA_INS 
		FROM LSRCON_TRIS WHERE LSRCON_TRIS_KEY_ID_RICEV = @RICEV
		AND LSRCON_TRIS_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRCON_TRIS',@IDDOC,'00000000','',@FIRMA,'')
		END

	END
END

IF @CAS <> '0'
BEGIN
	IF @CODSER = '02'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRCON_F101_KEY_DATA_INS +  LSRCON_F101_KEY_ORA_INS 
		FROM LSRCON_F101 WHERE LSRCON_F101_KEY_ID_RICEV = @RICEV
		AND LSRCON_F101_TIPO_DOC = 'A'
		AND LSRCON_F101_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRCON_F101',@IDDOC,'00000000','',@FIRMA,'')
		END

	END
	IF @CODSER = '05'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRCON_BOLLO_KEY_DATA_INS +  LSRCON_BOLLO_KEY_ORA_INS 
		FROM LSRCON_BOLLO WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRCON_BOLLO_TIPO_DOC = 'A'
		AND LSRCON_BOLLO_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRCON_BOLLO',@IDDOC,'00000000','',@FIRMA,'')
		END

	END

END

IF @FID <> '0'
BEGIN
	IF @CODSER = '02'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRFID_F101_KEY_DATA_INS +  LSRFID_F101_KEY_ORA_INS 
		FROM LSRFID_F101 WHERE LSRFID_F101_KEY_ID_RICEV = @RICEV
		AND LSRFID_F101_ANNO_RIF = CONVERT(CHAR(4),GETDATE(),112)
		AND LSRFID_F101_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRFID_F101',@IDDOC,'00000000','',@FIRMA,'')
		END

	END

	IF @CODSER = '05'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRFID_BOLLO_KEY_DATA_INS +  LSRFID_BOLLO_KEY_ORA_INS 
		FROM LSRFID_BOLLO WHERE LSRFID_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRFID_BOLLO_ANNO_RIF = CONVERT(CHAR(4),GETDATE(),112)
		AND LSRFID_BOLLO_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRFID_BOLLO',@IDDOC,'00000000','',@FIRMA,'')
		END

	END

	IF @CODSER = '08'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRFID_TRIS_KEY_DATA_INS +  LSRFID_TRIS_KEY_ORA_INS 
		FROM LSRFID_TRIS WHERE LSRFID_TRIS_KEY_ID_RICEV = @RICEV
		AND LSRFID_TRIS_ANNO_RIF = CONVERT(CHAR(4),GETDATE(),112)
		AND LSRFID_TRIS_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRFID_TRIS',@IDDOC,'00000000','',@FIRMA,'')
		END

	END
END

IF @APS <> '0'
BEGIN
	IF @CODSER = '02'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRAPS_F101_KEY_DATA_INS +  LSRAPS_F101_KEY_ORA_INS 
		FROM LSRAPS_F101 WHERE LSRAPS_F101_KEY_ID_RICEV = @RICEV
		AND LSRAPS_F101_ANNO_RIF = CONVERT(CHAR(4),GETDATE(),112)
		AND LSRAPS_F101_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRAPS_F101',@IDDOC,'00000000','',@FIRMA,'')
		END

	END

	IF @CODSER = '08'
	BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRAPS_TRIS_KEY_DATA_INS +  LSRAPS_TRIS_KEY_ORA_INS 
		FROM LSRAPS_TRIS WHERE LSRAPS_TRIS_KEY_ID_RICEV = @RICEV
		AND LSRAPS_TRIS_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRAPS_TRIS',@IDDOC,'00000000','',@FIRMA,'')
		END

	END
END

IF @RAD <> '0'
BEGIN
	IF @TIPOMOV = 'D'
	BEGIN
		-- MODIFICA DEL 30/07/2001:
		-- AGGIUNTA LA CONDIZIONE CHE LA DATA DI INVIO DEL DOCUMENTO RAD
		-- SIA >= DELLA DATA DECORRENZA DELLO STATO ATTUALE DEL SERVIZIO
		IF @CODSER = '02'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			OR
			(LSRRAD_FONTE = 'Q' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' )
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '7'))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'D' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_F101_DATA_DECOR)
				FROM LSRSER_F101
				WHERE LSRSER_F101_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_F101_FLAG_VALIDITA = 'Y' 
				AND LSRSER_F101_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD
			DEALLOCATE CUR_RAD
		END -- END IF CODSER=02

		IF @CODSER = '05'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			OR
			(LSRRAD_FONTE = 'Q' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' )
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '7'))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'D' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
				FROM LSRSER_BOLLO
				WHERE LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y' 
				AND LSRSER_BOLLO_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD
			DEALLOCATE CUR_RAD

		END -- END IF CODSER=05

		IF @CODSER = '08'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			OR
			(LSRRAD_FONTE = 'Q' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' )
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '7'))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'D' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_TRIS_DATA_DECOR)
				FROM LSRSER_TRIS 
				WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
				AND LSRSER_TRIS_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD
			DEALLOCATE CUR_RAD

		END -- END IF CODSER=08
	END
	IF @TIPOMOV = 'S'
	BEGIN
		DECLARE CUR_RAD CURSOR FOR 
		SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
		LSRRAD_KEY_ID_RICEV = @RICEV
		AND
		((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S')
		OR
		(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
		OR
		(LSRRAD_FONTE = 'Q' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S')
		OR
		(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S' )
		OR
		(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S' AND LSRRAD_CAUSALE_LOTTOMATICA = '7'))
		AND LSRRAD_TIPO_SERVIZIO = @CODSER
		AND LSRRAD_FLAG_ANAG = '1'
		AND LSRRAD_DATA_INVIO_DOC > 
			(SELECT  VAR = CASE 
				WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 			FROM LSRRAD 
			WHERE LSRRAD_FLAG_ANAG = '1' 
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'S' )
		AND LSRRAD_DATA_INVIO_DOC >=
			(SELECT MAX(LSRSER_TRIS_DATA_DECOR)
			FROM LSRSER_TRIS 
			WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
			AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
			AND LSRSER_TRIS_KEY_ID_RICEV = @RICEV)

		--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
		AND lsrrad_data_decor <= (convert(char(8) ,getdate() + 1,112))

		OPEN CUR_RAD
		FETCH NEXT FROM CUR_RAD INTO @IDDOC
		WHILE @@FETCH_STATUS = 0
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
		
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
		END

		CLOSE CUR_RAD
		DEALLOCATE CUR_RAD

	END

	IF @TIPOMOV = 'R'
	BEGIN

		-- MODIFICA DEL 30/07/2001:
		-- AGGIUNTA LA CONDIZIONE CHE LA DATA DI INVIO DEL DOCUMENTO RAD
		-- SIA >= DELLA DATA DECORRENZA DELLO STATO ATTUALE DEL SERVIZIO

		IF @CODSER = '02' 
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			(
			(LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R')
			OR
			--MODIFICA DEL 15/06/2001 : TOLTA LA CAUSALE LOTTOMATICA
			--(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' )
			--MODIFICA DEL 06/02/2002 : TOLTA LA FONTE ASSOCIAZIONE
			--OR
			--(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' )
			)
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'R' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_F101_DATA_DECOR)
				FROM LSRSER_F101
				WHERE LSRSER_F101_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_F101_FLAG_VALIDITA = 'Y' 
				AND LSRSER_F101_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD

			DEALLOCATE CUR_RAD
		END -- END IF CODSER=02

		IF @CODSER = '05' 
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R')
			OR
			--MODIFICA DEL 15/06/2001 : TOLTA LA CAUSALE LOTTOMATICA
			--(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' )
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' ))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'R' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
				FROM LSRSER_BOLLO
				WHERE LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y' 
				AND LSRSER_BOLLO_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD

			DEALLOCATE CUR_RAD
		END -- END IF CODSER=05

		IF @CODSER = '08' 
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R')
			OR
			--MODIFICA DEL 15/06/2001 : TOLTA LA CAUSALE LOTTOMATICA
			--(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' )
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' ))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'R' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_TRIS_DATA_DECOR)
				FROM LSRSER_TRIS
				WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
				AND LSRSER_TRIS_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD

			DEALLOCATE CUR_RAD
		END -- END IF CODSER=02

	END

	IF @TIPOMOV = 'A'
	BEGIN
		-- MODIFICA DEL 30/07/2001:
		-- AGGIUNTA LA CONDIZIONE CHE LA DATA DI INVIO DEL DOCUMENTO RAD
		-- SIA >= DELLA DATA DECORRENZA DELLO STATO ATTUALE DEL SERVIZIO
		-- WARNING: CONTROLLO RIMOSSO IL 01/08/2001
		IF @CODSER = '05'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'A')
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'A' ))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'A' )
	
			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD

			DEALLOCATE CUR_RAD

		END
	END

END

--IF @TIPOMOV = 'D'
--MODIFICA DEL 05/01/2001: ANCHE PER LE SOSPENSIONI TRIS SONO TENUTE IN CONSIDERAZIONE LE RINUNCE
IF @TIPOMOV = 'D' OR @TIPOMOV = 'S'
BEGIN
	--SE ESISTE LA RINUNCIA, LA SUA DATA DEVE ESSERE MINORE O UGUALE ALLA DATA DI DOMANI
	SELECT @IDDOC = NULL
	SELECT @IDDOC = LSRRIN_KEY_DATA_INS + LSRRIN_KEY_ORA_INS
	 FROM LSRRIN
	WHERE LSRRIN_KEY_ID_RICEV = @RICEV
		AND LSRRIN_CODICE_SERVIZIO = @CODSER
		AND LSRRIN_FLAG_ANAG = '1'
		AND LSRRIN_DATA_RINUNCIA <= CONVERT(CHAR,GETDATE() + 1 ,112)
		AND (LSRRIN_DATA_RINUNCIA_RINUNCIA IS NULL OR LSRRIN_DATA_RINUNCIA_RINUNCIA ='00000000' OR LSRRIN_DATA_RINUNCIA_RINUNCIA = '')
	
	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET VALUES
		(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRIN',@IDDOC,'00000000','',@FIRMA,'')
	END
END
GO
