/****** Object:  StoredProcedure [dbo].[Report_contrattualistica_non_abbinata]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[Report_contrattualistica_non_abbinata]
	@SERVIZIO CHAR(2), 
	@DATA CHAR(8), 
	@XML CHAR(1) = '0', 
	@ESITO INT OUT
AS
DECLARE @CODRETURN INT

SELECT @ESITO = 0

IF (@SERVIZIO IS NULL) OR (RTRIM(LTRIM(@SERVIZIO)) = '')
BEGIN
    SELECT @ESITO = 8
    RAISERROR ('MANCA IL NOME DEL SERVIZIO',16,1)
    RETURN @ESITO
END

IF (@DATA IS NULL) OR (RTRIM(LTRIM(@DATA)) = '')
BEGIN
	SELECT @ESITO = 87
	RAISERROR ('MANCA LA DATA DI RICERCA',16,1)
	RETURN @ESITO
END

IF (@XML = '1')
--IL RISULTATO DEVE ESSERE PRODOTTO IN FORMATO XML
BEGIN 
	--***********************
	--    	F101
	--***********************
	IF (@SERVIZIO = '02')
	BEGIN
		-- APS
		SELECT  'APS' AS Documento,
			LSRAPS_F101_KEY_ID_RICEV AS Cod_Lottomatica,
			'' AS Associazione,
			ISNULL(LSRAPS_F101_DATA_INVIO_DOC,'') AS Data_Invio_Doc ,
			rtrim(ltrim(LSRAPS_F101_COGNOME)) AS Cognome,
			rtrim(ltrim(LSRAPS_F101_NOME)) AS Nome,
			lsr01a_cognome as CognomeTit,
			lsr01a_nome as NomeTit
		FROM    LSRAPS_F101, condiviso.dbo.lsr01a
		WHERE   LSRAPS_F101_FLAG_ANAG = '0'
			AND LSRAPS_F101_KEY_DATA_INS <= @DATA
			and lsr01a_KEY_ID_RICEV = LSRAPS_F101_KEY_ID_RICEV
	 
		UNION ALL
		-- CONTRATTO
		SELECT  'CONTRATTO',
			LSRCON_F101_KEY_ID_RICEV,
			ISNULL (LSRCON_F101_ASSOCIAZIONE, ''),
			ISNULL (LSRCON_F101_DATA_INVIO_DOC, ''),			 
			rtrim(ltrim(LSRCON_F101_COGNOME)),
			rtrim(ltrim(LSRCON_F101_NOME)),
			lsr01a_cognome as CognomeTit,
			lsr01a_nome as NomeTit
		FROM    LSRCON_F101, condiviso.dbo.lsr01a
		WHERE   LSRCON_F101_FLAG_ANAG = '0'
			AND LSRCON_F101_KEY_DATA_INS <= @DATA
			and lsr01a_KEY_ID_RICEV = 	LSRCON_F101_KEY_ID_RICEV
		UNION ALL
		-- FIDEJUSSIONE	
		SELECT  'FIDEJUSSIONE',
			LSRFID_F101_KEY_ID_RICEV,
			ISNULL (LSRFID_F101_ID_SOC, ''),
			ISNULL (LSRFID_F101_DATA_INVIO_DOC, ''),			
			rtrim(ltrim(LSRFID_F101_COGNOME)),
			rtrim(ltrim(LSRFID_F101_NOME)),
			lsr01a_cognome as CognomeTit,
			lsr01a_nome as NomeTit
		FROM    LSRFID_F101, condiviso.dbo.lsr01a
		WHERE   LSRFID_F101_FLAG_ANAG = '0'
			AND LSRFID_F101_KEY_DATA_INS <= @DATA
			and lsr01a_KEY_ID_RICEV = LSRfid_F101_KEY_ID_RICEV
		UNION ALL
	
		-- RAD
		SELECT  'RAD',
			LSRRAD_KEY_ID_RICEV,
			ISNULL (LSRRAD_FONTE, ''),
			ISNULL (LSRRAD_DATA_INVIO_DOC, ''),
			rtrim(ltrim(LSRRAD_COGNOME)),
			rtrim(ltrim(LSRRAD_NOME)),
			lsr01a_cognome as CognomeTit,
			lsr01a_nome as NomeTit
		FROM    LSRRAD, condiviso.dbo.lsr01a
		WHERE   LSRRAD_FLAG_ANAG = '0'
			AND LSRRAD_TIPO_SERVIZIO = '02'
			AND LSRRAD_KEY_DATA_INS <= @DATA
			and lsr01a_KEY_ID_RICEV = LSRrad_KEY_ID_RICEV
		UNION ALL
		-- RIN
		SELECT  'RINUNCIA',
			LSRRIN_KEY_ID_RICEV,
			'',
			ISNULL(LSRRIN_DATA_INVIO_DOC, ''),
			rtrim(ltrim(LSRRIN_COGNOME)),
			rtrim(ltrim(LSRRIN_NOME)),
			lsr01a_cognome as CognomeTit,
			lsr01a_nome as NomeTit
		FROM    LSRRIN, condiviso.dbo.lsr01a
		WHERE   LSRRIN_FLAG_ANAG = '0'
			AND LSRRIN_CODICE_SERVIZIO = '02'
			AND LSRRIN_KEY_DATA_INS <= @DATA
			and lsr01a_KEY_ID_RICEV = LSRrin_KEY_ID_RICEV
		FOR XML RAW
	
		IF @@ROWCOUNT < 2
		BEGIN
			SELECT @ESITO = 2
			RAISERROR ('NESSUN DOCUMENTO NON ABBINATO PER LA DATA RICHIESTA',16,1)
			RETURN @ESITO
		END
	END --IF @SERVIZIO = '02'		

	--***********************
	--    	BOLLO
	--***********************
	IF (@SERVIZIO = '05')
	BEGIN
		-- CONTRATTO
		SELECT  'CONTRATTO' AS Documento,
			LSRCON_BOLLO_KEY_ID_RICEV AS Cod_Lottomatica,
			ISNULL (LSRCON_BOLLO_ASSOCIAZIONE, '') AS Associazione,
			ISNULL (LSRCON_BOLLO_DATA_INVIO_DOC, '') AS Data_invio_Doc,		
			rtrim(ltrim(LSRCON_BOLLO_COGNOME)) AS Cognome,
			rtrim(ltrim(LSRCON_BOLLO_NOME)) AS Nome
		FROM    LSRCON_BOLLO
		WHERE   LSRCON_BOLLO_FLAG_ANAG = '0'
			AND LSRCON_BOLLO_KEY_DATA_INS <= @DATA
			AND LSRCON_BOLLO_TIPO_DOC = 'C'
	
		UNION ALL
		-- ADESIONE
		SELECT  'ADESIONE',
			LSRCON_BOLLO_KEY_ID_RICEV,
			ISNULL (LSRCON_BOLLO_ASSOCIAZIONE, ''),
			ISNULL (LSRCON_BOLLO_DATA_INVIO_DOC, ''),	
			rtrim(ltrim(LSRCON_BOLLO_COGNOME)),
			rtrim(ltrim(LSRCON_BOLLO_NOME))
		FROM    LSRCON_BOLLO
		WHERE   LSRCON_BOLLO_FLAG_ANAG = '0'
			AND LSRCON_BOLLO_KEY_DATA_INS <= @DATA
			AND LSRCON_BOLLO_TIPO_DOC = 'A'

		UNION ALL
	
		-- RAD
		SELECT  'RAD',
			LSRRAD_KEY_ID_RICEV,
			ISNULL (LSRRAD_FONTE, ''),
			ISNULL (LSRRAD_DATA_INVIO_DOC, ''),		
			rtrim(ltrim(LSRRAD_COGNOME)),
			rtrim(ltrim(LSRRAD_NOME))
		FROM    LSRRAD
		WHERE   LSRRAD_FLAG_ANAG = '0'
			AND LSRRAD_TIPO_SERVIZIO = '05'
			AND LSRRAD_KEY_DATA_INS <= @DATA

		UNION ALL
		-- RIN
		SELECT  'RINUNCIA',
			LSRRIN_KEY_ID_RICEV,
			'', 			ISNULL (LSRRIN_DATA_INVIO_DOC, ''),
			rtrim(ltrim(LSRRIN_COGNOME)),
			rtrim(ltrim(LSRRIN_NOME))
		FROM    LSRRIN
		WHERE   LSRRIN_FLAG_ANAG = '0'
			AND LSRRIN_CODICE_SERVIZIO = '05'
			AND LSRRIN_KEY_DATA_INS <= @DATA

		FOR XML RAW
	
		IF @@ROWCOUNT < 2
		BEGIN
			SELECT @ESITO = 2
			RAISERROR ('NESSUN DOCUMENTO NON ABBINATO PER LA DATA RICHIESTA',16,1)
			RETURN @ESITO
		END
	END --IF @SERVIZIO = '05'		

	--***********************
	--    	TRIS
	--***********************
	IF (@SERVIZIO = '08')
	BEGIN
		-- APS
		SELECT  'APS' AS Documento,
			LSRAPS_TRIS_KEY_ID_RICEV AS Cod_Lottomatica,
			'' AS Associazione,
			ISNULL (LSRAPS_TRIS_KEY_DATA_INS, '') AS Data_Invio_Doc,
			rtrim(ltrim(LSRAPS_TRIS_COGNOME)) AS Cognome,
			rtrim(ltrim(LSRAPS_TRIS_NOME)) AS Nome
		FROM    LSRAPS_TRIS
		WHERE   LSRAPS_TRIS_FLAG_ANAG = '0'
			AND LSRAPS_TRIS_KEY_DATA_INS <= @DATA
	 
		UNION ALL
		-- CONTRATTO
		SELECT  'CONTRATTO',
			LSRCON_TRIS_KEY_ID_RICEV,
			'',
			ISNULL (LSRCON_TRIS_DATA_CONTRATTO, ''),
			rtrim(ltrim(LSRCON_TRIS_COGNOME)),
			rtrim(ltrim(LSRCON_TRIS_NOME))
		FROM    LSRCON_TRIS
		WHERE   LSRCON_TRIS_FLAG_ANAG = '0'
			AND LSRCON_TRIS_KEY_DATA_INS <= @DATA
	
		UNION ALL
		-- FIDEJUSSIONE	
		SELECT  'FIDEJUSSIONE',
			LSRFID_TRIS_KEY_ID_RICEV,
			ISNULL (LSRFID_TRIS_ID_SOC, ''),
			ISNULL (LSRFID_TRIS_KEY_DATA_INS, ''),
			rtrim(ltrim(LSRFID_TRIS_COGNOME)),
			rtrim(ltrim(LSRFID_TRIS_NOME))
		FROM    LSRFID_TRIS
		WHERE   LSRFID_TRIS_FLAG_ANAG = '0'
			AND LSRFID_TRIS_KEY_DATA_INS <= @DATA

		UNION ALL
	
		-- RAD
		SELECT  'RAD',
			LSRRAD_KEY_ID_RICEV,
			ISNULL (LSRRAD_FONTE, ''),
			ISNULL (LSRRAD_DATA_INVIO_DOC, ''),
			rtrim(ltrim(LSRRAD_COGNOME)),
			rtrim(ltrim(LSRRAD_NOME))
		FROM    LSRRAD
		WHERE   LSRRAD_FLAG_ANAG = '0'
			AND LSRRAD_TIPO_SERVIZIO = '08'
			AND LSRRAD_KEY_DATA_INS <= @DATA

		UNION ALL
		-- RIN
		SELECT  'RINUNCIA',
			LSRRIN_KEY_ID_RICEV,
			'',
			ISNULL (LSRRIN_DATA_INVIO_DOC, ''),
			rtrim(ltrim(LSRRIN_COGNOME)),
			rtrim(ltrim(LSRRIN_NOME))
		FROM    LSRRIN
		WHERE   LSRRIN_FLAG_ANAG = '0'
			AND LSRRIN_CODICE_SERVIZIO = '08'
			AND LSRRIN_KEY_DATA_INS <= @DATA
		FOR XML RAW
	
		IF @@ROWCOUNT < 2
		BEGIN
			SELECT @ESITO = 2
			RAISERROR ('NESSUN DOCUMENTO NON ABBINATO PER LA DATA RICHIESTA',16,1)
			RETURN @ESITO
		END
	END --IF @SERVIZIO = '08'		
	
END
--FLAG XML = '0'
ELSE
BEGIN
	--***********************
	--    	F101
	--***********************
	IF (@SERVIZIO = '02')
	BEGIN
		-- APS
		SELECT  'APS' AS NOMEDOC,
			LSRAPS_F101_KEY_ID_RICEV AS CODLTM,
			'' AS ASSOCIAZIONE,
			ISNULL(LSRAPS_F101_DATA_INVIO_DOC,'') AS DATAINVIODOC ,
			LSRAPS_F101_COGNOME AS COGNOME,
			LSRAPS_F101_NOME AS NOME
		FROM    LSRAPS_F101
		WHERE   LSRAPS_F101_FLAG_ANAG = '0'
			AND LSRAPS_F101_KEY_DATA_INS <= @DATA
	 
		UNION ALL
		-- CONTRATTO
		SELECT  'CONTRATTO' AS NOMEDOC,
			LSRCON_F101_KEY_ID_RICEV AS CODLTM,
			ISNULL (LSRCON_F101_ASSOCIAZIONE, '') AS ASSOCIAZIONE,
			ISNULL (LSRCON_F101_DATA_INVIO_DOC, '') AS DATAINVIODOC,			 
			LSRCON_F101_COGNOME AS COGNOME,
			LSRCON_F101_NOME AS NOME
		FROM    LSRCON_F101
		WHERE   LSRCON_F101_FLAG_ANAG = '0'
			AND LSRCON_F101_KEY_DATA_INS <= @DATA
	
		UNION ALL
		-- FIDEJUSSIONE	
		SELECT  'FIDEJUSSIONE' AS NOMEDOC,
			LSRFID_F101_KEY_ID_RICEV AS CODLTM,
			ISNULL (LSRFID_F101_ID_SOC, '') AS ASSOCIAZIONE,
			ISNULL (LSRFID_F101_DATA_INVIO_DOC, '') AS DATAINVIODOC,			
			LSRFID_F101_COGNOME AS COGNOME,
			LSRFID_F101_NOME AS NOME
		FROM    LSRFID_F101
		WHERE   LSRFID_F101_FLAG_ANAG = '0'
			AND LSRFID_F101_KEY_DATA_INS <= @DATA

		UNION ALL
	
		-- RAD
		SELECT  'RAD' AS NOMEDOC,
			LSRRAD_KEY_ID_RICEV AS CODLTM,
			ISNULL (LSRRAD_FONTE, '') AS ASSOCIAZIONE,
			ISNULL (LSRRAD_DATA_INVIO_DOC, '') AS DATAINVIODOC,
			LSRRAD_COGNOME AS COGNOME,
			LSRRAD_NOME AS NOME
		FROM    LSRRAD
		WHERE   LSRRAD_FLAG_ANAG = '0'
			AND LSRRAD_TIPO_SERVIZIO = '02'
			AND LSRRAD_KEY_DATA_INS <= @DATA

		UNION ALL
		-- RIN
		SELECT  'RINUNCIA' AS NOMEDOC,
			LSRRIN_KEY_ID_RICEV AS CODLTM,
			'' AS ASSOCIAZIONE,
			ISNULL(LSRRIN_DATA_INVIO_DOC, '') AS DATAINVIODOC ,
			LSRRIN_COGNOME AS COGNOME,
			LSRRIN_NOME AS NOME
		FROM    LSRRIN
		WHERE   LSRRIN_FLAG_ANAG = '0'
			AND LSRRIN_CODICE_SERVIZIO = '02'
			AND LSRRIN_KEY_DATA_INS <= @DATA
		IF @@ROWCOUNT < 2
		BEGIN
			SELECT @ESITO = 2
			RAISERROR ('NESSUN DOCUMENTO NON ABBINATO PER LA DATA RICHIESTA',16,1)
			RETURN @ESITO
		END
	END --IF @SERVIZIO = '02'		

	--***********************
	--    	BOLLO
	--***********************
	IF (@SERVIZIO = '05')
	BEGIN
		-- CONTRATTO
		SELECT  'CONTRATTO' AS NOMEDOC,
			LSRCON_BOLLO_KEY_ID_RICEV AS CODLTM,
			ISNULL (LSRCON_BOLLO_ASSOCIAZIONE, '') AS ASSOCIAZIONE,
			ISNULL (LSRCON_BOLLO_DATA_INVIO_DOC, '') AS DATAINVIODOC,		
			LSRCON_BOLLO_COGNOME AS COGNOME,
			LSRCON_BOLLO_NOME AS NOME
		FROM    LSRCON_BOLLO
		WHERE   LSRCON_BOLLO_FLAG_ANAG = '0'
			AND LSRCON_BOLLO_KEY_DATA_INS <= @DATA
			AND LSRCON_BOLLO_TIPO_DOC = 'C'
	
		UNION ALL
		-- ADESIONE
		SELECT  'ADESIONE' AS NOMEDOC,
			LSRCON_BOLLO_KEY_ID_RICEV AS CODLTM,
			ISNULL (LSRCON_BOLLO_ASSOCIAZIONE, '') AS ASSOCIAZIONE,
			ISNULL (LSRCON_BOLLO_DATA_INVIO_DOC, '') AS DATAINVIODOC,	
			LSRCON_BOLLO_COGNOME AS COGNOME,
			LSRCON_BOLLO_NOME AS NOME
		FROM    LSRCON_BOLLO
		WHERE   LSRCON_BOLLO_FLAG_ANAG = '0'
			AND LSRCON_BOLLO_KEY_DATA_INS <= @DATA
			AND LSRCON_BOLLO_TIPO_DOC = 'A'

		UNION ALL
	
		-- RAD
		SELECT  'RAD' AS NOMEDOC,
			LSRRAD_KEY_ID_RICEV AS CODLTM,
			ISNULL (LSRRAD_FONTE, '') AS ASSOCIAZIONE,
			ISNULL (LSRRAD_DATA_INVIO_DOC, '') AS DATAINVIODOC,		
			LSRRAD_COGNOME AS COGNOME,
			LSRRAD_NOME AS NOME
		FROM    LSRRAD
		WHERE   LSRRAD_FLAG_ANAG = '0'
			AND LSRRAD_TIPO_SERVIZIO = '05'
			AND LSRRAD_KEY_DATA_INS <= @DATA

		UNION ALL
		-- RIN
		SELECT  'RINUNCIA' AS NOMEDOC,
			LSRRIN_KEY_ID_RICEV AS CODLTM,
			'' AS ASSOCIAZIONE,
			ISNULL (LSRRIN_DATA_INVIO_DOC, '') AS DATAINVIODOC,			
			LSRRIN_COGNOME AS COGNOME,
			LSRRIN_NOME AS NOME
		FROM    LSRRIN
		WHERE   LSRRIN_FLAG_ANAG = '0'
			AND LSRRIN_CODICE_SERVIZIO = '05'
			AND LSRRIN_KEY_DATA_INS <= @DATA

		IF @@ROWCOUNT < 2
		BEGIN
			SELECT @ESITO = 2
			RAISERROR ('NESSUN DOCUMENTO NON ABBINATO PER LA DATA RICHIESTA',16,1)
			RETURN @ESITO
		END
	END --IF @SERVIZIO = '05'		

	--***********************
	--    	TRIS
	--***********************
	IF (@SERVIZIO = '08')
	BEGIN
		-- APS
		SELECT  'APS' AS NOMEDOC,
			LSRAPS_TRIS_KEY_ID_RICEV AS CODLTM,
			'' AS ASSOCIAZIONE,
			ISNULL (LSRAPS_TRIS_KEY_DATA_INS, '') AS DATAINVIODOC,			
			LSRAPS_TRIS_COGNOME AS COGNOME,
			LSRAPS_TRIS_NOME AS NOME
		FROM    LSRAPS_TRIS
		WHERE   LSRAPS_TRIS_FLAG_ANAG = '0'
			AND LSRAPS_TRIS_KEY_DATA_INS <= @DATA
	 
		UNION ALL
		-- CONTRATTO
		SELECT  'CONTRATTO' AS NOMEDOC,
			LSRCON_TRIS_KEY_ID_RICEV AS CODLTM,
			'' AS ASSOCIAZIONE,
			ISNULL (LSRCON_TRIS_DATA_CONTRATTO, '') AS DATAINVIODOC,			
			LSRCON_TRIS_COGNOME AS COGNOME,
			LSRCON_TRIS_NOME AS NOME
		FROM    LSRCON_TRIS
		WHERE   LSRCON_TRIS_FLAG_ANAG = '0'
			AND LSRCON_TRIS_KEY_DATA_INS <= @DATA
	
		UNION ALL
		-- FIDEJUSSIONE	
		SELECT  'FIDEJUSSIONE' AS NOMEDOC,
			LSRFID_TRIS_KEY_ID_RICEV AS CODLTM,
			ISNULL (LSRFID_TRIS_ID_SOC, '') AS ASSOCIAZIONE,
			ISNULL (LSRFID_TRIS_KEY_DATA_INS, '') AS DATAINVIODOC,		
			LSRFID_TRIS_COGNOME AS COGNOME,
			LSRFID_TRIS_NOME AS NOME
		FROM    LSRFID_TRIS
		WHERE   LSRFID_TRIS_FLAG_ANAG = '0'
			AND LSRFID_TRIS_KEY_DATA_INS <= @DATA

		UNION ALL
	
		-- RAD
		SELECT  'RAD' AS NOMEDOC,
			LSRRAD_KEY_ID_RICEV AS CODLTM,
			ISNULL (LSRRAD_FONTE, '') AS ASSOCIAZIONE,
			ISNULL (LSRRAD_DATA_INVIO_DOC, '') AS DATAINVIODOC,	  
			LSRRAD_COGNOME AS COGNOME,
			LSRRAD_NOME AS NOME
		FROM    LSRRAD
		WHERE   LSRRAD_FLAG_ANAG = '0'
			AND LSRRAD_TIPO_SERVIZIO = '08'
			AND LSRRAD_KEY_DATA_INS <= @DATA

		UNION ALL
		-- RIN
		SELECT  'RINUNCIA' AS NOMEDOC,
			LSRRIN_KEY_ID_RICEV AS CODLTM,
			'' AS ASSOCIAZIONE,
			ISNULL (LSRRIN_DATA_INVIO_DOC, '') AS DATAINVIODOC,
			LSRRIN_COGNOME AS COGNOME,
			LSRRIN_NOME AS NOME
		FROM    LSRRIN
		WHERE   LSRRIN_FLAG_ANAG = '0'
			AND LSRRIN_CODICE_SERVIZIO = '08'
			AND LSRRIN_KEY_DATA_INS <= @DATA
	
		IF @@ROWCOUNT < 2
		BEGIN
			SELECT @ESITO = 2
			RAISERROR ('NESSUN DOCUMENTO NON ABBINATO PER LA DATA RICHIESTA',16,1)
			RETURN @ESITO
		END
	END --IF @SERVIZIO = '08'		
END

RETURN @ESITO
GO
