/****** Object:  StoredProcedure [dbo].[GEV_DATI_RICEVITORIA]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_DATI_RICEVITORIA] 

@RICEV		CHAR(6),
@DATARIF		CHAR(8),
@TIPORICERCA	CHAR(1),
@DENOMINAZIONE	VARCHAR(100) OUTPUT,
@INDIRIZZO		VARCHAR(100) OUTPUT,
@COMUNE		VARCHAR(100) OUTPUT,
@CAP			CHAR(5) OUTPUT,
@TELEFONO		CHAR(12) OUTPUT

AS

IF @TIPORICERCA = 'P' --DATI RELATIVI AL TITOLARE PRECEDENTE
BEGIN
	SELECT @DENOMINAZIONE = LSRRIC_DECOD_RICEV,
		@INDIRIZZO = LSRRIC_INDIRIZZO,
		@COMUNE = LSRRIC_COMUNE_RICEV,
		@CAP = LSRRIC_CAP,
		@TELEFONO = CASE 
					WHEN LTRIM(RTRIM(LSRRIC_TEL_RICEVITORIA)) = '' THEN '0'
					WHEN LSRRIC_TEL_RICEVITORIA IS NULL THEN '0'
					ELSE LSRRIC_TEL_RICEVITORIA 
				END
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @RICEV 
	AND  LSRRIC_FLAG_VALIDITA = 'Y'
	AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) =
	(	
		SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)
		FROM LSRRIC
		WHERE LSRRIC_KEY_ID_RICEV = @RICEV
		AND  LSRRIC_FLAG_VALIDITA = 'Y'
		AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) <
			(SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)
			FROM LSRRIC
			WHERE LSRRIC_KEY_ID_RICEV = @RICEV 
			AND  (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) <= 
				(SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)
				FROM LSRRIC
				WHERE LSRRIC_KEY_ID_RICEV = @RICEV
				 AND LSRRIC_DATA_VALIDITA <= @DATARIF 
				AND  LSRRIC_FLAG_VALIDITA = 'Y')
			AND  LSRRIC_FLAG_VALIDITA = 'Y')
)
END
ELSE
BEGIN
	SELECT @DENOMINAZIONE = LSRRIC_DECOD_RICEV,
		@INDIRIZZO = LSRRIC_INDIRIZZO,
		@COMUNE = LSRRIC_COMUNE_RICEV,
		@CAP = LSRRIC_CAP,
		@TELEFONO = CASE 
					WHEN LTRIM(RTRIM(LSRRIC_TEL_RICEVITORIA)) = '' THEN '0'
					WHEN LSRRIC_TEL_RICEVITORIA IS NULL THEN '0'
					ELSE LSRRIC_TEL_RICEVITORIA 
				END
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @RICEV 
	AND  LSRRIC_FLAG_VALIDITA = 'Y'
	AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) =
	(	
		SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)
		FROM LSRRIC
		WHERE LSRRIC_KEY_ID_RICEV = @RICEV
		AND  LSRRIC_FLAG_VALIDITA = 'Y'
		AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) <= CONVERT(CHAR, GETDATE(), 112)
	)
END
GO
