/****** Object:  StoredProcedure [dbo].[GEV_CODIFICA_SGI_LTM]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE        PROCEDURE [dbo].[GEV_CODIFICA_SGI_LTM] 

@COD_INP	VARCHAR(7),
@COD_OUT	VARCHAR(6)	OUTPUT

AS 

DECLARE 

@MSGERR		VARCHAR(50),
@PROGR		CHAR(4),
@CTRL		INT,
@LTM		CHAR(2),
@SGI_APPO	CHAR(3),
@SGI		CHAR(3),
@SGI_OVER	CHAR(3)

IF RTRIM(LTRIM(@COD_INP)) = '' OR @COD_INP IS NULL
BEGIN
	SELECT @MSGERR = 'INDICARE UN CODICE RICEVITORIA'
	RAISERROR(@MSGERR,16,1)
	RETURN 9999
END

SELECT @SGI = SUBSTRING(@COD_INP,1,3)

SELECT  @LTM = Rete_LTM,
	@SGI = Rete_SGI,
	@SGI_OVER = ISNULL(Rete_SGI_oversize,'')
FROM GEV_Decod_LTM_SGI
WHERE Rete_SGI = @SGI OR Rete_SGI_oversize = @SGI

IF RTRIM(LTRIM(@SGI)) = '' OR @SGI IS NULL
BEGIN
	SELECT @MSGERR = 'RETE NON PREVISTA'
	RAISERROR(@MSGERR,16,1)
	RETURN 9999
END
ELSE
BEGIN
	IF SUBSTRING(@COD_INP,1,3) = @SGI_OVER
	BEGIN
	----------------------------------------------------------
	-- PROMEMORIA: Questo test è inutile, non esistono codici 
	-- superiori a 9999, ma va previsto per il futuro.
	----------------------------------------------------------
		SELECT @PROGR = SUBSTRING(@COD_INP,4,4) -- + 10000 ????
	END
	ELSE
	BEGIN
		SELECT @PROGR = SUBSTRING(@COD_INP,4,4)
		SELECT @COD_OUT = @LTM + @PROGR

		SELECT @CTRL = COUNT(*)
		FROM LSRRIC
		WHERE LSRRIC_KEY_ID_RICEV = @COD_OUT

		IF @CTRL = 0
		BEGIN
			SELECT @COD_OUT = ''
			SELECT @MSGERR = 'CODICE RICEVITORIA INESISTENTE'
			RAISERROR(@MSGERR,16,1)
			RETURN 9999
		END
		RETURN 0
	END
END
GO
