/****** Object:  StoredProcedure [dbo].[GEV_CODIFICA_LTM_SGI_EXT]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE         PROCEDURE [dbo].[GEV_CODIFICA_LTM_SGI_EXT] 

@COD_INP	VARCHAR(6),
@COD_OUT	VARCHAR(10)	OUTPUT

AS 

DECLARE 

@MSGERR		VARCHAR(50),
@PROGR		CHAR(4),
@CTRL		INT,
@LTM		CHAR(2),
@SGI		CHAR(2),
@SGI_OVER	CHAR(2)

IF RTRIM(LTRIM(@COD_INP)) = '' OR @COD_INP IS NULL
BEGIN
	SELECT @MSGERR = 'INDICARE UN CODICE RICEVITORIA'
	RAISERROR(@MSGERR,16,1)
	RETURN 9999
END

SELECT @LTM = SUBSTRING(@COD_INP,1,2)

SELECT  @LTM = Rete_LTM,
	@SGI = Rete_SGI,
	@SGI_OVER = ISNULL(Rete_SGI_oversize,'')
FROM GEV_Decod_LTM_SGI
WHERE Rete_LTM = @LTM

IF RTRIM(LTRIM(@LTM)) = '' OR @LTM IS NULL
BEGIN
	SELECT @MSGERR = 'RETE NON PREVISTA'
	RAISERROR(@MSGERR,16,1)
	RETURN 9999
END
/* DA ELIMINARE DOPO FASE DI TEST
ELSE
BEGIN
	SELECT @CTRL = COUNT(*)
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @COD_INP

	IF @CTRL = 0
	BEGIN
		SELECT @COD_OUT = ''
		SELECT @MSGERR = 'CODICE RICEVITORIA INESISTENTE'
		RAISERROR(@MSGERR,16,1)
		RETURN 9999
	END
END
*/

SELECT @PROGR = SUBSTRING(@COD_INP,3,4)

IF RTRIM(LTRIM(@SGI_OVER)) <> ''
BEGIN
	IF CONVERT(INT,@PROGR) > 9999
	BEGIN
		SELECT @COD_OUT = SUBSTRING(@SGI_OVER,1,1) + @COD_INP
		RETURN 0
	END
END

SELECT @COD_OUT = SUBSTRING(@SGI,1,1) + @COD_INP
RETURN 0
GO
