/****** Object:  StoredProcedure [dbo].[ANA_REP_PVNOLOTTISTI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[ANA_REP_PVNOLOTTISTI]
AS 
BEGIN

SELECT 
A.lsr01a_key_id_ricev,
A.lsr01a_cognome,
A.lsr01a_nome,
A.lsr01a_decod_ricev,
A.lsr01a_indirizzo,
A.lsr01a_cap,
A.lsr01a_comune_ricev,
A.lsr01a_prov_ricev,
T_RIDGEV.RIDGEV,
T_RIDLOTTO.RIDLOTTO,
T_RIDCONI.RIDCONI
FROM CONDIVISO.DBO.LSR01A A
LEFT OUTER JOIN (SELECT lcr01a_data_inizio_val AS RIDGEV, LCR01A_KEY_ID_RICEV
                 FROM Riscossioni.DBO.LCR01A
		 WHERE LCR01A_DATA_INIZIO_VAL <= CONVERT(CHAR, GETDATE(), 112)
                 AND LCR01A_TIPO_GIOCO='09'
                 AND LCR01A_KEY_DATA_FINE_VAL = '99999999' ) AS T_RIDGEV 
                 ON A.LSR01A_KEY_ID_RICEV =   T_RIDGEV.LCR01A_KEY_ID_RICEV
LEFT OUTER JOIN (SELECT lcr01a_data_inizio_val as RIDLOTTO, LCR01A_KEY_ID_RICEV
                 FROM Riscossioni.DBO.LCR01A
		 WHERE LCR01A_DATA_INIZIO_VAL <= CONVERT(CHAR, GETDATE(), 112)
                 AND LCR01A_TIPO_GIOCO='01'
                 AND LCR01A_KEY_DATA_FINE_VAL = '99999999' ) AS T_RIDLOTTO
                 ON A.LSR01A_KEY_ID_RICEV = T_RIDLOTTO.LCR01A_KEY_ID_RICEV
LEFT OUTER JOIN (SELECT lcr01a_data_inizio_val as RIDCONI, LCR01A_KEY_ID_RICEV
                 FROM Riscossioni.DBO.LCR01A
		 WHERE LCR01A_DATA_INIZIO_VAL <= CONVERT(CHAR, GETDATE(), 112)
                 AND LCR01A_TIPO_GIOCO='11'
                 AND LCR01A_KEY_DATA_FINE_VAL = '99999999' ) AS T_RIDCONI
                 ON A.LSR01A_KEY_ID_RICEV =  T_RIDCONI.LCR01A_KEY_ID_RICEV
WHERE LSR01A_TAB_GIOCHI_LOTTO IN ('0', '2')
AND LSR01A_TAB_GIOCHI_09 IN ('0', '2')
AND LSR01A_TAB_GIOCHI_11 IN ('1')
AND LSR01A_TAB_GIOCHI_12  IN ('1')
ORDER BY 1
END
GO
