/****** Object:  StoredProcedure [dbo].[ANAGRICEV]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANAGRICEV] @RICEVITORIA CHAR(6), @DATARICERCA CHAR(8) 

AS

IF @DATARICERCA = ""
BEGIN
	SELECT @DATARICERCA = CONVERT(CHAR(8),GETDATE(),112) 
END

SELECT * FROM LSRRIC JOIN LSRTIT 
ON LSRRIC_KEY_ID_RICEV = LSRTIT_KEY_ID_RICEV 
WHERE LSRTIT_TIPO = 'T'  
AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
(
	SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) FROM LSRRIC 
	WHERE LSRRIC_KEY_ID_RICEV = @RICEVITORIA
	AND  LSRRIC_DATA_VALIDITA <= @DATARICERCA
	AND  LSRRIC_FLAG_VALIDITA = 'Y')
	AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
	(
		SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) FROM LSRTIT 
		WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
		AND  LSRTIT_DATA_VALIDITA <= @DATARICERCA
		AND  LSRTIT_FLAG_VALIDITA = 'Y'
	)
AND  LSRRIC_KEY_ID_RICEV = @RICEVITORIA
AND  LSRRIC_FLAG_VALIDITA = 'Y'
AND  LSRTIT_FLAG_VALIDITA = 'Y'
GO
