/****** Object:  StoredProcedure [dbo].[GEV_DISATTIVAZIONE_DA_LOTTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GEV_DISATTIVAZIONE_DA_LOTTO] 

@RICEVITORIA 	CHAR(6),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATADECOR		CHAR(8),
@DATAPROVV		CHAR(8),
@TIPOPROVV		CHAR(1),
@NUMPROVV		CHAR(8),
@FIRMA		CHAR(17),
@OGGI			CHAR(8)


AS 

DECLARE	

--@CODSGI		CHAR(6),
--@CODAMM		CHAR(6),
@ASSOCIAZIONE	CHAR(1),
@STATO		CHAR(1),
--@OPZLOTTO		CHAR(1),
@DATA		CHAR(8),
@ORA			CHAR(8),
@DATAINSLET		CHAR(8),
@NOTE		CHAR(150),
@NUMERR 		VARCHAR(4),
@MSGERR 		VARCHAR(50)

SELECT @NOTE = 'SERVIZIO DISABILITATO DAL PROVVEDIMENTO LOTTO N° ' + @NUMPROVV + ' DEL ' + LTRIM(RTRIM(SUBSTRING(@DATAPROVV,7,2) + '-' + SUBSTRING(@DATAPROVV,5,2)+ '-' + SUBSTRING(@DATAPROVV,1,4)))
SELECT @DATA = CONVERT(CHAR,GETDATE(),112)
SELECT @ORA = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)

SELECT @DATAINSLET = @DATA

IF @DATADECOR <= @DATA
BEGIN
	SELECT @DATADECOR = CONVERT(CHAR,GETDATE() + 1,112)
END

IF @DATADECOR > CONVERT(CHAR,GETDATE() + 1,112)
BEGIN
	SELECT @DATAINSLET = CONVERT(CHAR,CONVERT(DATETIME,@DATADECOR) - 1,112)
END

/*
SELECT @CODAMM = NULL
SELECT @CODSGI =  NULL

EXEC GEV_ESISTE_RICEVITORIA @RICEVITORIA OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

IF @@ERROR <> 0
BEGIN
	RETURN
END

*/

--- TRATTAMENTO SERVIZIO GEV

SELECT @STATO = NULL
--SELECT @OPZLOTTO = NULL

SELECT @STATO=LSRSER_GEV_STATO--, @OPZLOTTO = LSRSER_GEV_OPZ_LOTTO
FROM LSRSER_GEV
WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
AND LSRSER_GEV_DATA_DECOR =
(
	SELECT MAX(LSRSER_GEV_DATA_DECOR) 
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_DATA_DECOR <= @DATADECOR
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
)
 


IF @TIPOPROVV = 'I'	--LA DISATTIVAZIONE DIPENDE DA CAMBIO TITOLARITA' DEL LOTTO
BEGIN
	UPDATE LSRSER_GEV SET
	LSRSER_GEV_FLAG_VALIDITA = 'N'
	WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_GEV_DATA_DECOR > @OGGI
--	AND LSRSER_GEV_DATA_DECOR <> @DATADECOR

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_GEV'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

	IF @STATO IS NOT NULL
	BEGIN
		IF @STATO <>  '0'
		BEGIN
			INSERT INTO LSRSER_GEV VALUES
				(@RICEVITORIA, 
				@DATAINS, 
				@ORAINS,   
				'2', 
				'D',
				@DATADECOR, 
				@TIPOPROVV, 
				@DATAPROVV, 
				@NUMPROVV, 
				'',
				@FIRMA, 
				@NOTE, 
				'00000000', 
				'Y')

			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_GEV'
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END
		END
	END
END
ELSE
BEGIN
	IF @TIPOPROVV <> 'I'	--LA DISATTIVAZIONE NON DIPENDE DA CAMBIO TITOLARITA' DEL LOTTO
	BEGIN
--		IF @OPZLOTTO = 'Y'
--		BEGIN
			UPDATE LSRSER_GEV SET
			LSRSER_GEV_FLAG_VALIDITA = 'N'
			WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_GEV_DATA_DECOR > @OGGI
--			AND LSRSER_GEV_DATA_DECOR <> @DATADECOR

			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_GEV'
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END

			IF @STATO IS NOT NULL
			BEGIN
				IF @STATO <>  '0'
				BEGIN
					INSERT INTO LSRSER_GEV VALUES
						(@RICEVITORIA, 
						@DATAINS, 
						@ORAINS,   
						'2', 
						'D',
						@DATADECOR, 
						@TIPOPROVV, 
						@DATAPROVV, 
						@NUMPROVV, 
						'',
						@FIRMA, 
						@NOTE, 
						'00000000', 
						'Y')


					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_GEV'
						RAISERROR (@MSGERR, 16, 1)
						RETURN
					END
				END
			END
--		END
	END
END

--SE DISATTIVO E IL SERVIZIO E' ATTIVO DEVO INVIARE LA LETTERA 

IF @STATO = '1'
BEGIN
	INSERT INTO LSRLET VALUES
	(@RICEVITORIA,@DATAINSLET,@ORA,'09','D',@DATADECOR,'LSRPRO',
	@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END
ELSE
BEGIN
	--SE IL SERVIZIO E' GIA' DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHE'
	-- IL CAMBIAMENTO DI STATO E' DOVUTO A CAMBIAMENTO DEL LOTTO
	INSERT INTO LSRLET VALUES
	(@RICEVITORIA,@DATAINSLET,@ORA,'09','D',@DATADECOR,'LSRPRO',
	@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END
GO
