/****** Object:  StoredProcedure [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_LSRPRO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_LSRPRO] 

@CODLTM 		VARCHAR(7),
@TIPOPROVV		CHAR(1),
@DATAPROVV		CHAR(8),
@NUMPROVV		VARCHAR(14),
@NEWFLAG		CHAR(1),
@FIRMA		VARCHAR(17),
@NOTE		VARCHAR(255)

AS

DECLARE

@CHKLTM		VARCHAR(7),
@MSGERR		VARCHAR(255),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8)


SELECT @CHKLTM = NULL
SELECT @DATAINS = NULL
SELECT @ORAINS = NULL

SELECT @CHKLTM = LSRPRO_KEY_ID_RICEV, @DATAINS = LSRPRO_DATA_INS, @ORAINS = LSRPRO_ORA_INS
FROM LSRPRO
WHERE
LSRPRO_KEY_ID_RICEV = @CODLTM AND
LSRPRO_FLAG_VALIDITA = 'Y' AND
LSRPRO_KEY_TIPO_REC = @TIPOPROVV AND
LSRPRO_KEY_PROG_PROVV = @NUMPROVV AND
LSRPRO_KEY_DATA_PROVV = @DATAPROVV

IF @CHKLTM IS NULL
BEGIN
	SELECT @MSGERR = 'NESSUN PROVVEDIMENTO ESISTENTE PER I PARAMETRI INDICATI'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

BEGIN TRANSACTION


-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
DELETE FROM LSRLET
WHERE LSRLET_KEY_ID_RICEV = @CODLTM
AND LSRLET_NOME_TAB_DOCUMENTO = 'LSRPRO'
AND LSRLET_FK_TAB_DOCUMENTO = @DATAINS + @ORAINS

SELECT @MSGERR = @@ERROR
	
IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

-- CANCELLO I RECORD DELLA TABELLA LSRLET_LIS LEGATI AL PROVVEDIMENTO
DELETE FROM LSRLET_LIS
WHERE LSRLET_LIS_KEY_ID_RICEV = @CODLTM
AND LSRLET_LIS_NOME_TAB_DOCUMENTO = 'LSRPRO'
AND LSRLET_LIS_FK_TAB_DOCUMENTO = @DATAINS + @ORAINS

SELECT @MSGERR = @@ERROR
	
IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


UPDATE LSRPRO SET 
LSRPRO_FLAG_VALIDITA = @NEWFLAG,
LSRPRO_FIRMA = @FIRMA
WHERE 
LSRPRO_KEY_ID_RICEV = @CODLTM AND
LSRPRO_FLAG_VALIDITA = 'Y' AND
LSRPRO_KEY_TIPO_REC = @TIPOPROVV AND
LSRPRO_KEY_PROG_PROVV = @NUMPROVV AND
LSRPRO_KEY_DATA_PROVV = @DATAPROVV

SELECT @MSGERR = @@ERROR
	
IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


COMMIT TRANSACTION
GO
