/****** Object:  StoredProcedure [dbo].[GEV_DECOD_RICEV]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_DECOD_RICEV] 

@COD_INP	VARCHAR(7),
@COD_OUT	VARCHAR(7)	OUTPUT

AS 


DECLARE 

@MSGERR		VARCHAR(50),
@RUOTALTM		CHAR(2),
@RUOTASGI		CHAR(1),
@PROGRUOTA	VARCHAR(5),
@LTM			VARCHAR(7),
@SGI			VARCHAR(7),
@RETE		CHAR(1)

IF RTRIM(LTRIM(@COD_INP)) = '' OR @COD_INP IS NULL
BEGIN
	SELECT @MSGERR = 'INDICARE UN CODICE RICEVITORIA'
	RAISERROR(@MSGERR,16,1)
	RETURN
END

IF ISNUMERIC(@PROGRUOTA) = 1
BEGIN
	SELECT @MSGERR = 'CODICE RICEVITORIA ERRATO'
	RAISERROR(@MSGERR,16,1)
	RETURN
END


IF ISNUMERIC(@COD_INP) = 0	--STO TRATTANDO UN CODICE LOTTOMATICA
BEGIN
	SELECT @PROGRUOTA = UPPER(SUBSTRING(@COD_INP, 3, 4))

	SELECT @RUOTALTM = UPPER(SUBSTRING(@COD_INP,1,2))

	IF NOT @RUOTALTM  IN ('BA', 'CA', 'FI', 'GE', 'MI', 'NA', 'PA', 'RM', 'TO', 'VE')
	BEGIN
		SELECT @MSGERR = 'CODICE RICEVITORIA ERRATO'
		RAISERROR(@MSGERR,16,1)
		RETURN
	END
	ELSE
	BEGIN
		SELECT DISTINCT @LTM = LSRRIC_KEY_ID_RICEV
		FROM LSRRIC
		WHERE LSRRIC_KEY_ID_RICEV = @COD_INP

		IF @LTM IS NULL
		BEGIN
			SELECT @MSGERR = 'CODICE RICEVITORIA INESISTENTE'
			RAISERROR(@MSGERR,16,1)
			RETURN
		END
		ELSE
		BEGIN
			IF @RUOTALTM = 'BA'
			BEGIN
				SELECT @RUOTASGI = '0'
			END
			ELSE IF @RUOTALTM = 'CA'
			BEGIN
				SELECT @RUOTASGI = '1'
			END
			ELSE IF @RUOTALTM = 'FI'
			BEGIN
				SELECT @RUOTASGI = '2'
			END
			ELSE IF @RUOTALTM = 'GE'
			BEGIN
				SELECT @RUOTASGI = '3'
			END
			ELSE IF @RUOTALTM = 'MI'
			BEGIN
				SELECT @RUOTASGI = '4'
			END
			ELSE IF @RUOTALTM = 'NA'
			BEGIN
				SELECT @RUOTASGI = '5'
			END
			ELSE IF @RUOTALTM = 'PA'
			BEGIN
				SELECT @RUOTASGI = '6'
			END
			ELSE IF @RUOTALTM = 'RM'
			BEGIN
				SELECT @RUOTASGI = '7'
			END
			ELSE IF @RUOTALTM = 'TO'
			BEGIN
				SELECT @RUOTASGI = '8'
			END
			ELSE IF @RUOTALTM = 'VE'
			BEGIN
				SELECT @RUOTASGI = '9'
			END
			
			IF CONVERT(INT,@PROGRUOTA) <= 9999
			BEGIN
				SELECT @COD_OUT = '3' + @RUOTASGI + @PROGRUOTA
				RETURN
			END
			ELSE
			BEGIN
				SELECT @COD_OUT = '4' + @RUOTASGI + SUBSTRING(@PROGRUOTA, 2, 4)
				RETURN				
			END
		END
	END
END
ELSE  --STO TRATTANDO UN CODICE SGI
BEGIN
	SELECT @PROGRUOTA = UPPER(SUBSTRING(@COD_INP, 3, 5))

	SELECT @RETE = SUBSTRING(@COD_INP, 1, 1)

PRINT @COD_INP
PRINT @PROGRUOTA

	IF NOT @RETE  IN ('3', '4') --IDENTIFICATIVI PER LOTTOMATICA
	BEGIN
		SELECT @MSGERR = 'RICEVITORIA NON APPARTENENTE ALLA RETE LOTTOMATICA'
		RAISERROR(@MSGERR,16,1)
		RETURN
	END	

	SELECT @RUOTASGI = SUBSTRING(@COD_INP, 2, 1)

	IF @RUOTASGI = '0'
	BEGIN
		SELECT @RUOTALTM = 'BA'
	END
	ELSE IF @RUOTASGI = '1'
	BEGIN
		SELECT @RUOTALTM = 'CA'
	END
	ELSE IF @RUOTASGI = '2'
	BEGIN
		SELECT @RUOTALTM = 'FI'
	END
	ELSE IF @RUOTASGI = '3'
	BEGIN
		SELECT @RUOTALTM = 'GE'
	END
	ELSE IF @RUOTASGI = '4'
	BEGIN
		SELECT @RUOTALTM = 'MI'
	END
	ELSE IF @RUOTASGI = '5'
	BEGIN
		SELECT @RUOTALTM = 'NA'
	END
	ELSE IF @RUOTASGI = '6'
	BEGIN
		SELECT @RUOTALTM = 'PA'
	END
	ELSE IF @RUOTASGI = '7'
	BEGIN
		SELECT @RUOTALTM = 'RM'
	END
	ELSE IF @RUOTASGI = '8'
	BEGIN
		SELECT @RUOTALTM = 'TO'
	END
	ELSE IF @RUOTASGI = '9'
	BEGIN
		SELECT @RUOTALTM = 'VE'
	END

	IF @RETE = '3'
	BEGIN
		SELECT @PROGRUOTA =  CONVERT(CHAR, CONVERT(INT, @PROGRUOTA))
		
		SELECT @PROGRUOTA = REPLICATE('0', 4 - LEN(@PROGRUOTA)) + @PROGRUOTA

		SELECT @LTM = @RUOTALTM + @PROGRUOTA
PRINT @LTM
	END
	ELSE IF @RETE = '4'
	BEGIN
		SELECT @PROGRUOTA =  CONVERT(CHAR, 10000 + CONVERT(INT, @PROGRUOTA))

		SELECT @LTM = @RUOTALTM + @PROGRUOTA
	END

	SELECT DISTINCT @COD_OUT = LSRRIC_KEY_ID_RICEV
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @LTM

	IF @COD_OUT IS NULL
	BEGIN
		SELECT @MSGERR = 'CODICE RICEVITORIA INESISTENTE'
		RAISERROR(@MSGERR,16,1)
		RETURN
	END

END
GO
