/****** Object:  StoredProcedure [dbo].[GEV_RICEVITORIA_PRECEDENTE]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_RICEVITORIA_PRECEDENTE] 

@RICEV		CHAR(6),
@DATARIF		CHAR(8),
@DENOM		VARCHAR(50) OUTPUT,
@DATADAL		CHAR(8) OUTPUT

AS


SELECT @DENOM = RTRIM(LTRIM(LSRRIC_DECOD_RICEV)), @DATADAL = LSRRIC_DATA_VALIDITA 
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @RICEV
AND  LSRRIC_FLAG_VALIDITA = 'Y'
AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) =
(	
	SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @RICEV
	AND  LSRRIC_FLAG_VALIDITA = 'Y'
	AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) <
	(
		SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)
		FROM LSRRIC
		WHERE LSRRIC_KEY_ID_RICEV = @RICEV
		AND  LSRRIC_FLAG_VALIDITA = 'Y'
		AND  (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) <= 
		(
			SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
			FROM LSRRIC
			WHERE LSRRIC_KEY_ID_RICEV = @RICEV
			AND  LSRRIC_FLAG_VALIDITA = 'Y'
			AND LSRRIC_DATA_VALIDITA <= @DATARIF
		)
	)
)
GO
