/****** Object:  StoredProcedure [dbo].[GEV_ESISTE_RINUNCIA]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_ESISTE_RINUNCIA] 

@CODLTM		VARCHAR(7),
@CODSER		VARCHAR(6),
@DATARIF		CHAR(8),
@DATARIN1		CHAR(8) OUTPUT,
@DATARIN2		CHAR(8) OUTPUT

AS

DECLARE

@MSGERR		VARCHAR(50)

IF LTRIM(RTRIM(@CODSER)) = '09'
BEGIN
	SELECT @DATARIN1 = '00000000'

	SELECT @DATARIN1 = LSRRIN_GEV_DATA_RIN
	FROM LSRRIN_GEV
	WHERE LSRRIN_GEV_COD_LOTTO = @CODLTM
	AND LSRRIN_GEV_FLAG_ANAG = '1'
	AND LSRRIN_GEV_DATA_RIN =
	(
		SELECT MAX(LSRRIN_GEV_DATA_RIN)
		FROM LSRRIN_GEV
		WHERE LSRRIN_GEV_COD_LOTTO = @CODLTM
		AND LSRRIN_GEV_FLAG_ANAG = '1'
		AND LSRRIN_GEV_DATA_RIN <= @DATARIF
	)

	SELECT @DATARIN2 = '00000000'

	SELECT @DATARIN2 = LSRRIN_GEV_DATA_RIN_RIN
	FROM LSRRIN_GEV
	WHERE LSRRIN_GEV_COD_LOTTO = @CODLTM
	AND LSRRIN_GEV_FLAG_ANAG = '1'
	AND LSRRIN_GEV_DATA_RIN =
	(
		SELECT MAX(LSRRIN_GEV_DATA_RIN_RIN)
		FROM LSRRIN_GEV
		WHERE LSRRIN_GEV_COD_LOTTO = @CODLTM
		AND LSRRIN_GEV_FLAG_ANAG = '1'
		AND LSRRIN_GEV_DATA_RIN_RIN <= @DATARIF
	)

END
ELSE IF LTRIM(RTRIM(@CODSER)) IN ('01', '02', '05', '08')
BEGIN
	SELECT @DATARIN1 = '00000000'

	SELECT @DATARIN1 = LSRRIN_DATA_RINUNCIA
	FROM LSRRIN
	WHERE LSRRIN_KEY_ID_RICEV = @CODLTM
	AND LSRRIN_CODICE_SERVIZIO = @CODSER
	AND LSRRIN_FLAG_ANAG = '1'
	AND LSRRIN_DATA_RINUNCIA =
	(
		SELECT MAX(LSRRIN_DATA_RINUNCIA)
		FROM LSRRIN
		WHERE LSRRIN_KEY_ID_RICEV = @CODLTM
		AND LSRRIN_FLAG_ANAG = '1'
		AND LSRRIN_DATA_RINUNCIA <= @DATARIF
	)

	SELECT @DATARIN2 = '00000000'

	SELECT @DATARIN2 = LSRRIN_DATA_RINUNCIA_RINUNCIA
	FROM LSRRIN
	WHERE LSRRIN_KEY_ID_RICEV = @CODLTM
	AND LSRRIN_CODICE_SERVIZIO = @CODSER
	AND LSRRIN_FLAG_ANAG = '1'
	AND LSRRIN_DATA_RINUNCIA_RINUNCIA =
	(
		SELECT MAX(LSRRIN_DATA_RINUNCIA_RINUNCIA)
		FROM LSRRIN
		WHERE LSRRIN_KEY_ID_RICEV = @CODLTM
		AND LSRRIN_FLAG_ANAG = '1'
		AND LSRRIN_DATA_RINUNCIA_RINUNCIA <= @DATARIF
	)
END
ELSE
BEGIN
	SELECT @DATARIN1 = '00000000'

	SELECT @DATARIN1 = LSRRIN_LIS_DATA_RINUNCIA
	FROM LSRRIN_LIS
	WHERE LSRRIN_LIS_KEY_ID_RICEV = @CODLTM
	AND LSRRIN_LIS_KEY_CATEGORIA + LSRRIN_LIS_KEY_SERVIZIO + LSRRIN_LIS_KEY_ATTIVITA = @CODSER
	AND LSRRIN_LIS_FLAG_ANAG = '1'
	AND LSRRIN_LIS_DATA_RINUNCIA =
	(
		SELECT MAX(LSRRIN_LIS_DATA_RINUNCIA)
		FROM LSRRIN_LIS
		WHERE LSRRIN_LIS_KEY_ID_RICEV = @CODLTM
		AND LSRRIN_LIS_FLAG_ANAG = '1'
		AND LSRRIN_LIS_DATA_RINUNCIA <= @DATARIF
	)

	SELECT @DATARIN2 = '00000000'

	SELECT @DATARIN1 = LSRRIN_LIS_DATA_RINUNCIA_RINUNCIA
	FROM LSRRIN_LIS
	WHERE LSRRIN_LIS_KEY_ID_RICEV = @CODLTM
	AND LSRRIN_LIS_KEY_CATEGORIA + LSRRIN_LIS_KEY_SERVIZIO + LSRRIN_LIS_KEY_ATTIVITA = @CODSER
	AND LSRRIN_LIS_FLAG_ANAG = '1'
	AND LSRRIN_LIS_DATA_RINUNCIA_RINUNCIA =
	(
		SELECT MAX(LSRRIN_LIS_DATA_RINUNCIA_RINUNCIA)
		FROM LSRRIN_LIS
		WHERE LSRRIN_LIS_KEY_ID_RICEV = @CODLTM
		AND LSRRIN_LIS_FLAG_ANAG = '1'
		AND LSRRIN_LIS_DATA_RINUNCIA_RINUNCIA <= @DATARIF
	)

END
GO
