/****** Object:  StoredProcedure [dbo].[GEV_ESISTE_RID]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE    PROCEDURE [dbo].[GEV_ESISTE_RID] 

		@CODLTM		CHAR(6),
		@DATA		CHAR(8),
		@TIPOGIOCO		CHAR(2),
		@ABI			CHAR(5) OUTPUT,
		@CAB			CHAR(5) OUTPUT,
		@DESCRIZIONE	VARCHAR(50) OUTPUT
AS


DECLARE		

		@CHKRICEV	CHAR(6),
		@MSGERR	VARCHAR(100)


IF RTRIM(LTRIM(@CODLTM)) = '' OR @CODLTM IS NULL
BEGIN
	SELECT @MSGERR = 'VALORIZZARE LA RICEVITORIA ' 
	RAISERROR (@MSGERR, 16, 1)
	RETURN 9999
END

IF RTRIM(LTRIM(@DATA)) = '' OR @DATA IS NULL
BEGIN
	SELECT @MSGERR = 'VALORIZZARE LA DATA ' 
	RAISERROR (@MSGERR, 16, 1)
	RETURN 9999
END

IF RTRIM(LTRIM(@TIPOGIOCO)) = '' OR @TIPOGIOCO IS NULL
BEGIN
	SELECT @MSGERR = 'VALORIZZARE IL TIPO DI GIOCO ' 
	RAISERROR (@MSGERR, 16, 1)
	RETURN 9999
END
/*
SELECT @CHKRICEV = NULL
SELECT @CHKRICEV = LCR01A_KEY_ID_RICEV, 
	 @ABI = LCR01A_ABI, 
	 @CAB = LCR01A_CAB, 
	 @DESCRIZIONE = LCR01A_DESCRIZIONE
FROM CONDIVISO.DBO.LCR01A
WHERE LCR01A_KEY_ID_RICEV = @CODLTM 
AND @DATA BETWEEN LCR01A_DATA_INIZIO_VAL AND LCR01A_KEY_DATA_FINE_VAL
AND LCR01A_TIPO_GIOCO = @TIPOGIOCO

*/
SELECT @CHKRICEV = NULL
IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
BEGIN
	--RID CONI (che possono essere anche LOTTO)
	SELECT @CHKRICEV = cod_lottomatica, 
		@ABI = LCR01A_ABI, 
		@CAB = LCR01A_CAB, 
		@DESCRIZIONE = LCR01A_DESCRIZIONE
	FROM 
	(
		SELECT *
		FROM Riscossioni.dbo.DELEGHEBANCA_PV
		WHERE data_fine_val='99999999'
	)DB_PV, 
	(
		SELECT *
		FROM [SQL-DBSAN1\A].CONDIVISO.DBO.LCR01A
		WHERE lcr01a_key_data_fine_val='99999999'
	)LCR
	WHERE cod_banca=lcr01a_key_id_ricev 
	--and cod_prodotto=lcr01a_tipo_gioco
		AND @DATA BETWEEN LCR01A_DATA_INIZIO_VAL AND LCR01A_KEY_DATA_FINE_VAL
		AND cod_lottomatica = @CODLTM

END
ELSE
BEGIN	
	SELECT  @CHKRICEV =LCR01A_KEY_ID_RICEV, --25960
		@ABI =LCR01A_ABI, 
		@CAB =LCR01A_CAB, 
		@DESCRIZIONE = LCR01A_DESCRIZIONE
	FROM [SQL-DBSAN1\A].CONDIVISO.DBO.LCR01A
	WHERE lcr01a_key_data_fine_val='99999999'
		and lcr01a_tipo_gioco='01' 
		and lcr01a_key_id_ricev not in 
		(
			SELECT cod_banca
			FROM Riscossioni.dbo.DELEGHEBANCA_PV
			WHERE data_fine_val='99999999'
		) 
		and lcr01a_key_id_ricev not in
		(
			SELECT cod_lottomatica
			FROM Riscossioni.dbo.DELEGHEBANCA_PV
			WHERE data_fine_val='99999999'
		) 
		AND @DATA BETWEEN LCR01A_DATA_INIZIO_VAL AND LCR01A_KEY_DATA_FINE_VAL
		AND LCR01A_KEY_ID_RICEV = @CODLTM


END


IF @CHKRICEV IS NULL
BEGIN
	SELECT @MSGERR = 'RID INESISTENTE PER LA RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	RETURN 9999
END
GO
