/****** Object:  StoredProcedure [dbo].[LIT_AGGIORNA_TTB_V]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE     PROCEDURE [dbo].[LIT_AGGIORNA_TTB_V]  AS

DECLARE   	

@IERI 			CHAR(8),
@OGGI 		CHAR(8),
@DATAINS 		CHAR(8),
@RICEVITORIA 	CHAR(6),
@CODAMM 		CHAR(6),
@DATADECOR 	CHAR(8),
@DECORDAL 		CHAR(8),
@DATAATTIV 		CHAR(8),
@DATACESSAZ 	CHAR(8),
@DECODRICEV 	CHAR(50),
@COMUNERICEV 	CHAR(24),
@PROVRICEV 		CHAR(2),
@CAPRICEV 		CHAR(5),
@INDIRIZZORICEV 	CHAR(40),
@COGNOME 		CHAR(24),
@NOME 		CHAR(20),
@STATOGEV 		CHAR(1),

@TELRICEV 		CHAR(12),
@TELTIT 		CHAR(12),
@SIGLAIC 		CHAR(2),
@SIGLAREG 		CHAR(2),
@CHIUSURARICEV 		CHAR(1),
@SPECIALERICEV 		CHAR(1),
@CODMAGAZ 		CHAR(5),
@IDTAB 			CHAR(4),
@ASSORICEV 		CHAR(1),
@DATARIATTIV 		CHAR(8),
@FLAGESE 		CHAR(1),
@TESTO 			VARCHAR(300),
@NUMTERM 		CHAR(2),
@TERMINST 		CHAR(1),
@MODULO 		CHAR(1),
@FLAGCOMM 		CHAR(1),
@FLGANN			CHAR(1),
@MSGERR 		VARCHAR(100),
@NOMEJOB		VARCHAR(25)


SELECT @NOMEJOB = 'LSFG012001B2'

SELECT @STATOGEV = '0'

SELECT @OGGI = CONVERT(CHAR(8), GETDATE(), 112)

SELECT @IERI = CONVERT(CHAR(8), GETDATE() - 1, 112)


--***************************************************************************
--*  CURSORE RELATIVO ALLE RICEVITORIE
--***************************************************************************
DECLARE CUR_RIC CURSOR FOR 
SELECT	LSRRIC_KEY_ID_RICEV,
		LSRRIC_COD_AMM,
		LSRRIC_DECOD_RICEV,
		LSRRIC_COMUNE_RICEV,
		LSRRIC_PROV_RICEV,
		LSRRIC_CAP,
		LSRRIC_INDIRIZZO,
		LSRRIC_TEL_RICEVITORIA,
		LSRRIC_SIGLA_IC,
		LSRRIC_SIGLA_REG,
		LSRRIC_CHIUSURA,
		LSRRIC_TAB_SPECIALI,
		LSRRIC_CODICE_MAGAZZINO,
		LSRRIC_FLAG_ESERCIZIO,
		LSRRIC_NUM_TERMINALI,
		LSRRIC_ID_TAB
FROM LSRRIC A
WHERE LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA = 
	(SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) FROM LSRRIC B
	 WHERE ((LSRRIC_DATA_VALIDITA <= @OGGI AND LSRRIC_KEY_DATA_INS =  @IERI)
	OR LSRRIC_DATA_VALIDITA =  @OGGI)
AND B.LSRRIC_KEY_ID_RICEV = A.LSRRIC_KEY_ID_RICEV
AND LSRRIC_FLAG_VALIDITA = 'Y') 
AND LSRRIC_FLAG_VALIDITA = 'Y'
and LSRRIC_KEY_ID_RICEV  like 'LI%'

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA, 
		@CODAMM,
		@DECODRICEV,
		@COMUNERICEV,
		@PROVRICEV,
		@CAPRICEV,
		@INDIRIZZORICEV,
		@TELRICEV,
		@SIGLAIC,
		@SIGLAREG,
		@CHIUSURARICEV,
		@SPECIALERICEV,
		@CODMAGAZ,
		@FLAGESE,
		@NUMTERM,
		@IDTAB
WHILE @@FETCH_STATUS = 0 
BEGIN

	update ttb_v
	set decod_ricev = @DECODRICEV,
		comune_ricev = @COMUNERICEV,
		prov_ricev = @PROVRICEV,
		cap = @CAPRICEV,
		indirizzo = @INDIRIZZORICEV,
		tel_ricevitoria = @TELRICEV,
		data_mod = @OGGI
	where key_id_ricev = @RICEVITORIA
	
	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA, 
			@CODAMM,
			@DECODRICEV,
			@COMUNERICEV,
			@PROVRICEV,
			@CAPRICEV,
			@INDIRIZZORICEV,
			@TELRICEV,
			@SIGLAIC,
			@SIGLAREG,
			@CHIUSURARICEV,
			@SPECIALERICEV,
			@CODMAGAZ,
			@FLAGESE,
			@NUMTERM,
			@IDTAB
END  

CLOSE CUR_RIC
DEALLOCATE CUR_RIC


--***************************************************************************
--*                  CURSORE RELATIVO AI TITOLARI
--***************************************************************************
DECLARE CUR_TIT CURSOR FOR 
SELECT 	LSRTIT_KEY_ID_RICEV,
	LSRTIT_COGNOME,
	LSRTIT_NOME,
	LSRTIT_TELEFONO
FROM LSRTIT A
WHERE (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
	(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV
	AND ((LSRTIT_DATA_VALIDITA <= @OGGI
	AND LSRTIT_KEY_DATA_INS =  @IERI)
	OR LSRTIT_DATA_VALIDITA =  @OGGI)
	AND LSRTIT_TIPO = 'T'
	AND LSRTIT_FLAG_VALIDITA = 'Y')
AND LSRTIT_FLAG_VALIDITA = 'Y'
AND LSRTIT_TIPO = 'T'
and LSRTIT_KEY_ID_RICEV  like 'LI%'

OPEN CUR_TIT
FETCH NEXT FROM CUR_TIT INTO @RICEVITORIA,
		@COGNOME,
		@NOME,
		@TELTIT
WHILE @@FETCH_STATUS = 0 
BEGIN

	update ttb_v
	set cognome = @COGNOME,
		nome = @NOME,
		TEL_CASA = @TELTIT,
		data_mod = @OGGI
	where key_id_ricev =@RICEVITORIA

	FETCH NEXT FROM CUR_TIT INTO @RICEVITORIA,
		@COGNOME,
		@NOME,
		@TELTIT
END  

CLOSE CUR_TIT
DEALLOCATE CUR_TIT


--***************************************************************************
--*                  CURSORE RELATIVO AL G&V
--***************************************************************************
DECLARE CUR_GEV CURSOR FOR 
SELECT 	LSRSER_GEV_KEY_ID_RICEV,
	LSRSER_GEV_STATO
	FROM LSRSER_GEV A
	WHERE(LSRSER_GEV_DATA_DECOR) = 
		(SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV
		WHERE LSRSER_GEV_KEY_ID_RICEV =A.LSRSER_GEV_KEY_ID_RICEV
		AND ((LSRSER_GEV_DATA_DECOR <=  convert(char(8),getdate(),112)
		AND LSRSER_GEV_KEY_DATA_INS =   convert(char(8),getdate() -1 ,112))
		OR LSRSER_GEV_DATA_DECOR =   convert(char(8),getdate(),112))
		AND LSRSER_GEV_FLAG_VALIDITA = 'Y')
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'  
	and substring (lsrser_gev_key_id_ricev, 1, 2) = 'LI'

OPEN CUR_GEV
FETCH NEXT FROM CUR_GEV INTO @RICEVITORIA,
		@STATOGEV
WHILE @@FETCH_STATUS = 0 
BEGIN
	update ttb_v
	set GEV = @STATOGEV
	where key_id_ricev =@RICEVITORIA

	FETCH NEXT FROM CUR_GEV INTO @RICEVITORIA, 
			@STATOGEV
END  

CLOSE CUR_GEV
DEALLOCATE CUR_GEV


EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. LIT_AGGIORNA_TTB_V TERMINATA CORRETTAMENTE', 0
GO
