/****** Object:  StoredProcedure [dbo].[ADESIONE_BOLLO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ADESIONE_BOLLO]  
	@RICEV 		CHAR(6),
	@DATAADES		CHAR(8),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(50),
	@CANONE		CHAR(1),
	@MSGERR 		VARCHAR(100) OUTPUT
AS

DECLARE 	@DATAINS		CHAR(8),
		@ORAINS		CHAR(8),
		@DATAORAINS	CHAR(16),
		@STATOBOLLO	CHAR(1),
		@TIPOPROVV		CHAR(1),
		@CHKRICEV		CHAR(6)


SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

/*
' ESEGUO I CONTROLLI NEL CASO DI ATTIVAZIONE AL SERVIZIO BOLLO:
' 1) - ESISTE LA RICEVITORIA IN LSRRIC
' 2)  NON ESISTE LA RICEVITORIA IN LSRSER_BOLLO 
*/


/*
CONTROLLO 1
*/

SELECT @CHKRICEV = NULL

SELECT @CHKRICEV = LSRRIC_KEY_ID_RICEV FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE'
	RETURN
END

/*
CONTROLLO 2
*/

SELECT @CHKRICEV = NULL

SELECT @CHKRICEV = LSRSER_BOLLO_KEY_ID_RICEV FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NOT NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA GIA PRESENTE SU LSRSER_BOLLO'
	RETURN
END
ELSE
BEGIN
	--INIZIO MODIFICA IN DATA 02-05-2001

	BEGIN TRANSACTION

	SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
					FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @RICEV
					AND LSRLET_COD_SERVIZIO = '05'
					AND LSRLET_TIPO_MOVIMENTAZIONE = 'I'
					AND LSRLET_KEY_DATA_INS = @DATAINS
					AND LSRLET_DECOR_DAL = '00000000'

	IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
	BEGIN	
		UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATAADES
		WHERE LSRLET_KEY_ID_RICEV = @RICEV
		AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
		AND LSRLET_COD_SERVIZIO = '05'
		AND LSRLET_TIPO_MOVIMENTAZIONE = 'I'

	END
	ELSE
	BEGIN
		INSERT INTO LSRLET VALUES(@RICEV,@DATAINS,@ORAINS,'05','I',@DATAADES,'','','00000000',@NOTE,@FIRMA,'V')
	END

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET'
		ROLLBACK TRANSACTION
		RETURN
	END

	--FINE MODIFICA IN DATA 02-05-2001


	INSERT INTO LSRSER_BOLLO VALUES (@RICEV,@DATAINS,@ORAINS,'0',@DATAADES,@CANONE,NULL,NULL,NULL,NULL,@FIRMA,NULL,'00000000','Y')

	IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT SU LSRSER_BOLLO'
			ROLLBACK TRANSACTION
			RETURN
		END

	ELSE
		BEGIN
			SELECT @MSGERR = '0000 - ' + @RICEV +' ELABORAZIONE TERMINATA CORRETTAMENTE'
			COMMIT TRANSACTION
			RETURN
		END
END
GO
