/****** Object:  StoredProcedure [dbo].[GEV_TITOLARE_PRECEDENTE]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_TITOLARE_PRECEDENTE] 

@RICEV		CHAR(6),
@DATARIF		CHAR(8),
@TITOLARE		CHAR(50) OUTPUT,
@DATADAL		CHAR(8) OUTPUT

AS

/*
SELECT @TITOLARE = RTRIM(LTRIM(LSRTIT_COGNOME)) + ' ' + RTRIM(LTRIM(LSRTIT_NOME)), 
	@DATADAL = LSRTIT_DATA_VALIDITA 
FROM LSRTIT 
WHERE LSRTIT_TIPO_PROVV IN ('E','I') 
AND LSRTIT_KEY_ID_RICEV = @RICEV
AND LSRTIT_FLAG_VALIDITA = 'Y'
AND LSRTIT_DATA_VALIDITA = 
	(SELECT MAX(LSRTIT_DATA_VALIDITA)
	FROM LSRTIT
	WHERE lsrTIT_TIPO_PROVV IN ('E','I') 
	AND LSRTIT_KEY_ID_RICEV = @RICEV
	AND LSRTIT_FLAG_VALIDITA = 'Y'
	AND LSRTIT_DATA_VALIDITA < @DATARIF)

*/

SELECT @TITOLARE = RTRIM(LTRIM(LSRTIT_COGNOME)) + ' ' + RTRIM(LTRIM(LSRTIT_NOME)),  
	@DATADAL = LSRTIT_DATA_VALIDITA 
FROM LSRTIT
WHERE LSRTIT_KEY_ID_RICEV = @RICEV 
AND  LSRTIT_FLAG_VALIDITA = 'Y'
AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) =
(	
	SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV = @RICEV
	AND  LSRTIT_FLAG_VALIDITA = 'Y'
	AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) <
		(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)
		FROM LSRTIT
		WHERE LSRTIT_KEY_ID_RICEV = @RICEV 
		--order by lsrtit_data_validita
		AND LSRTIT_TIPO = 'T'  
		AND  (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) <= 
			(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) FROM LSRTIT
			WHERE LSRTIT_KEY_ID_RICEV = @RICEV
			 AND LSRTIT_DATA_VALIDITA <= @DATARIF 
			AND  LSRTIT_FLAG_VALIDITA = 'Y')
		AND  LSRTIT_FLAG_VALIDITA = 'Y'
		AND  LSRTIT_TIPO_PROVV IN ('I', 'E'))
)
GO
