/****** Object:  StoredProcedure [dbo].[ANNULLA_PROVVEDIMENTO_SERVIZI_PACCHETTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANNULLA_PROVVEDIMENTO_SERVIZI_PACCHETTO]  
	@RICEVITORIA		CHAR(6),
	@TIPOPROVV		CHAR(1),
	@DATAPROVV		CHAR(8),
	@PROGPROVV		CHAR(14),
	@MSGERR		CHAR(100) OUTPUT  

AS

DECLARE	

@DATAINS 	CHAR(8),
@ORAINS   	CHAR(8)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR, GETDATE(), 121),1,4)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),6,2)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),9,2)

SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)

BEGIN TRANSACTION

--***********************************************
--                   F101
--***********************************************
UPDATE LSRSER_F101 SET
LSRSER_F101_FLAG_VALIDITA = 'A', 
LSRSER_F101_KEY_DATA_INS = @DATAINS,
LSRSER_F101_KEY_ORA_INS = @ORAINS,
LSRSER_F101_NOTE = 'ANNULLATO PERCHè  RICEVITORIA APPARTENENTE OFFERTA PACCHETTO',
LSRSER_F101_FIRMA = 'ANATEAM'
WHERE LSRSER_F101_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_F101_TIPO_PROVV = @TIPOPROVV
AND LSRSER_F101_DATA_PROVV = @DATAPROVV
AND LSRSER_F101_PROG_PROVV = @PROGPROVV

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
	RETURN
END

-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
DELETE FROM LSRLET
WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
AND LSRLET_KEY_DATA_INS = @DATAINS
AND LSRLET_COD_SERVIZIO IN ('02')

IF @@ERROR<>0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
	RETURN
END

--***********************************************
--              TRIS
--***********************************************
UPDATE LSRSER_TRIS SET
LSRSER_TRIS_FLAG_VALIDITA = 'A', 
LSRSER_TRIS_KEY_DATA_INS = @DATAINS,
LSRSER_TRIS_KEY_ORA_INS = @ORAINS,
LSRSER_TRIS_NOTE =  'ANNULLATO PERCHè  RICEVITORIA APPARTENENTE OFFERTA PACCHETTO',
LSRSER_TRIS_FIRMA = 'ANATEAM'
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_TRIS_TIPO_PROVV = @TIPOPROVV
AND LSRSER_TRIS_DATA_PROVV = @DATAPROVV
AND LSRSER_TRIS_PROG_PROVV = @PROGPROVV

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
	RETURN
END

-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
DELETE FROM LSRLET
WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
AND LSRLET_KEY_DATA_INS = @DATAINS
AND LSRLET_COD_SERVIZIO IN ('08')

IF @@ERROR<>0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
	RETURN
END

--***********************************************
--                      BOLLO
--***********************************************
UPDATE LSRSER_BOLLO SET
LSRSER_BOLLO_FLAG_VALIDITA = 'A', 
LSRSER_BOLLO_KEY_DATA_INS = @DATAINS,
LSRSER_BOLLO_KEY_ORA_INS = @ORAINS,
LSRSER_BOLLO_NOTE =  'ANNULLATO PERCHè  RICEVITORIA APPARTENENTE OFFERTA PACCHETTO',
LSRSER_BOLLO_FIRMA = 'ANATEAM'
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_BOLLO_TIPO_PROVV = @TIPOPROVV
AND LSRSER_BOLLO_DATA_PROVV = @DATAPROVV
AND LSRSER_BOLLO_PROG_PROVV = @PROGPROVV

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
	RETURN
END

-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
DELETE FROM LSRLET
WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
AND LSRLET_KEY_DATA_INS = @DATAINS
AND LSRLET_COD_SERVIZIO IN ('05')

IF @@ERROR<>0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
	RETURN
END

COMMIT TRANSACTION

SELECT @MSGERR = '0000 - OPERAZIONE TERMINATA CORRETTAMENTE'

RETURN
GO
