/****** Object:  StoredProcedure [dbo].[ANNULLA_PROVVEDIMENTO_SERVIZI_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANNULLA_PROVVEDIMENTO_SERVIZI_LIS]  

	@CATEGORIA		CHAR(2),
	@SERVIZIO		CHAR(2),
	@ATTIVITA		CHAR(2),
	@RICEVITORIA		CHAR(6),
	@ORAOLD		CHAR(8),
	@STATO		CHAR(1),
	@FIRMAOLD		VARCHAR(17),
	@NOTE		VARCHAR(150),
	@FIRMANEW		VARCHAR(17),
	@MSGERR		VARCHAR(100) OUTPUT  

AS

DECLARE	

@DATAINS 	CHAR(8),
@ORAINS   	CHAR(8)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR, GETDATE(), 121),1,4)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),6,2)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),9,2)

SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)

BEGIN TRANSACTION

IF @CATEGORIA = '01' 
BEGIN
	UPDATE LSRSER_TEL SET
	LSRSER_TEL_FLAG_VALIDITA = 'A', 
	LSRSER_TEL_KEY_DATA_INS = @DATAINS,
	LSRSER_TEL_KEY_ORA_INS = @ORAINS,
	LSRSER_TEL_NOTE = @NOTE,
	LSRSER_TEL_FIRMA = @FIRMANEW
	WHERE LSRSER_TEL_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_TEL_KEY_ORA_INS = @ORAOLD
	AND LSRSER_TEL_STATO = @STATO
	AND LSRSER_TEL_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET_LIS
	WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_LIS_KEY_DATA_INS = @DATAINS
	AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRLET_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END
END

ELSE IF @CATEGORIA = '02'
BEGIN
	UPDATE LSRSER_CITT SET
	LSRSER_CITT_FLAG_VALIDITA = 'A', 
	LSRSER_CITT_KEY_DATA_INS = @DATAINS,
	LSRSER_CITT_KEY_ORA_INS = @ORAINS,
	LSRSER_CITT_NOTE = @NOTE,
	LSRSER_CITT_FIRMA = @FIRMANEW
	WHERE LSRSER_CITT_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_CITT_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_CITT_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_CITT_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_CITT_KEY_ORA_INS = @ORAOLD
	AND LSRSER_CITT_STATO = @STATO
	AND LSRSER_CITT_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET_LIS
	WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_LIS_KEY_DATA_INS = @DATAINS
	AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRLET_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END

END

ELSE IF @CATEGORIA = '03'
BEGIN
	UPDATE LSRSER_PAG SET
	LSRSER_PAG_FLAG_VALIDITA = 'A', 
	LSRSER_PAG_KEY_DATA_INS = @DATAINS,
	LSRSER_PAG_KEY_ORA_INS = @ORAINS,
	LSRSER_PAG_NOTE = @NOTE,
	LSRSER_PAG_FIRMA = @FIRMANEW
	WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_PAG_KEY_ORA_INS = @ORAOLD
	AND LSRSER_PAG_STATO = @STATO
	AND LSRSER_PAG_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET_LIS
	WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_LIS_KEY_DATA_INS = @DATAINS
	AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRLET_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END
END

ELSE IF @CATEGORIA = '04'
BEGIN
	UPDATE LSRSER_BIG SET
	LSRSER_BIG_FLAG_VALIDITA = 'A', 
	LSRSER_BIG_KEY_DATA_INS = @DATAINS,
	LSRSER_BIG_KEY_ORA_INS = @ORAINS,
	LSRSER_BIG_NOTE = @NOTE,
	LSRSER_BIG_FIRMA = @FIRMANEW
	WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_BIG_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_BIG_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_BIG_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_BIG_KEY_ORA_INS = @ORAOLD
	AND LSRSER_BIG_STATO = @STATO
	AND LSRSER_BIG_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET_LIS
	WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_LIS_KEY_DATA_INS = @DATAINS
	AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRLET_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END

END

ELSE IF @CATEGORIA = '05'
BEGIN
	UPDATE LSRSER_ATTI SET
	LSRSER_ATTI_FLAG_VALIDITA = 'A', 
	LSRSER_ATTI_KEY_DATA_INS = @DATAINS,
	LSRSER_ATTI_KEY_ORA_INS = @ORAINS,
	LSRSER_ATTI_NOTE = @NOTE,
	LSRSER_ATTI_FIRMA = @FIRMANEW
	WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_ATTI_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_ATTI_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_ATTI_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_ATTI_KEY_ORA_INS = @ORAOLD
	AND LSRSER_ATTI_STATO = @STATO
	AND LSRSER_ATTI_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET_LIS
	WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_LIS_KEY_DATA_INS = @DATAINS
	AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRLET_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END


END

COMMIT TRANSACTION

SELECT @MSGERR = '0000 - OPERAZIONE TERMINATA CORRETTAMENTE'

RETURN
GO
