/****** Object:  StoredProcedure [dbo].[ANNULLA_PROVVEDIMENTO_SERVIZI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANNULLA_PROVVEDIMENTO_SERVIZI]  

	@SERVIZIO		CHAR(10),
	@RICEVITORIA		CHAR(6),
	@ORAOLD		CHAR(8),
	@STATO		CHAR(1),
	@FIRMAOLD		VARCHAR(17),
	@NOTE		VARCHAR(150),
	@FIRMANEW		VARCHAR(17),
	@MSGERR		VARCHAR(100) OUTPUT  

AS

DECLARE	@DATAINS 	CHAR(8),
                 	@ORAINS   	CHAR(8)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR, GETDATE(), 121),1,4)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),6,2)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),9,2)

SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)

BEGIN TRANSACTION

IF @SERVIZIO = 'F101' 
BEGIN
	UPDATE LSRSER_F101 SET
	LSRSER_F101_FLAG_VALIDITA = 'A', 
	LSRSER_F101_KEY_DATA_INS = @DATAINS,
	LSRSER_F101_KEY_ORA_INS = @ORAINS,
	LSRSER_F101_NOTE = @NOTE,
	LSRSER_F101_FIRMA = @FIRMANEW
	WHERE LSRSER_F101_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_F101_KEY_ORA_INS = @ORAOLD
	AND LSRSER_F101_STATO = @STATO
	AND LSRSER_F101_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET
	WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_KEY_DATA_INS = @DATAINS
	AND LSRLET_COD_SERVIZIO IN ('02')

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END
END
ELSE IF @SERVIZIO = 'TRIS'
BEGIN
	UPDATE LSRSER_TRIS SET
	LSRSER_TRIS_FLAG_VALIDITA = 'A', 
	LSRSER_TRIS_KEY_DATA_INS = @DATAINS,
	LSRSER_TRIS_KEY_ORA_INS = @ORAINS,
	LSRSER_TRIS_NOTE = @NOTE,
	LSRSER_TRIS_FIRMA = @FIRMANEW
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_TRIS_KEY_ORA_INS = @ORAOLD
	AND LSRSER_TRIS_STATO = @STATO
	AND LSRSER_TRIS_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET
	WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_KEY_DATA_INS = @DATAINS
	AND LSRLET_COD_SERVIZIO IN ('08')

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END
END

ELSE IF @SERVIZIO = 'GEV'
BEGIN
	UPDATE LSRSER_GEV SET
	LSRSER_GEV_FLAG_VALIDITA = 'A', 
	LSRSER_GEV_KEY_DATA_INS = @DATAINS,
	LSRSER_GEV_KEY_ORA_INS = @ORAINS,
	LSRSER_GEV_NOTE = @NOTE,
	LSRSER_GEV_FIRMA = @FIRMANEW
	WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_GEV_KEY_ORA_INS = @ORAOLD
	AND LSRSER_GEV_STATO = @STATO
	AND LSRSER_GEV_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET
	WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_KEY_DATA_INS = @DATAINS
	AND LSRLET_COD_SERVIZIO IN ('09')

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END
END

ELSE IF @SERVIZIO = 'BOLLO'
BEGIN
	UPDATE LSRSER_BOLLO SET
	LSRSER_BOLLO_FLAG_VALIDITA = 'A', 
	LSRSER_BOLLO_KEY_DATA_INS = @DATAINS,
	LSRSER_BOLLO_KEY_ORA_INS = @ORAINS,
	LSRSER_BOLLO_NOTE = @NOTE,
	LSRSER_BOLLO_FIRMA = @FIRMANEW
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_BOLLO_KEY_ORA_INS = @ORAOLD
	AND LSRSER_BOLLO_STATO = @STATO
	AND LSRSER_BOLLO_FIRMA = @FIRMAOLD

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
		RETURN
	END
	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET
	WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_KEY_DATA_INS = @DATAINS
	AND LSRLET_COD_SERVIZIO IN ('05')

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END

END

COMMIT TRANSACTION

SELECT @MSGERR = '0000 - OPERAZIONE TERMINATA CORRETTAMENTE'

RETURN
GO
