/****** Object:  StoredProcedure [dbo].[ANNULLA_PROVVEDIMENTO_CONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANNULLA_PROVVEDIMENTO_CONI]  

	@RICEVITORIA		CHAR(6),
	@ORAOLD		CHAR(8),
	@STATO		CHAR(1),
	@FIRMAOLD		VARCHAR(17),
	@NOTE		VARCHAR(150),
	@FIRMANEW		VARCHAR(17),
	@MSGERR		VARCHAR(100) OUTPUT  

AS

DECLARE	@DATAINS 	CHAR(8),
                 	@ORAINS   	CHAR(8)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR, GETDATE(), 121),1,4)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),6,2)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),9,2)

SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)

BEGIN TRANSACTION

UPDATE LSRSER_CONI SET
LSRSER_CONI_FLAG_VALIDITA = 'A', 
LSRSER_CONI_KEY_DATA_INS = @DATAINS,
LSRSER_CONI_KEY_ORA_INS = @ORAINS,
LSRSER_CONI_NOTE = @NOTE,
LSRSER_CONI_FIRMA = @FIRMANEW
WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_CONI_KEY_ORA_INS = @ORAOLD
AND LSRSER_CONI_STATO = @STATO
AND LSRSER_CONI_FIRMA = @FIRMAOLD

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
	RETURN
END
-- CANCELLO I RECORD DELLA TABELLA LSRLET_CONI LEGATI AL PROVVEDIMENTO
DELETE FROM LSRLET_CONI
WHERE LSRLET_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRLET_CONI_KEY_DATA_INS = @DATAINS


IF @@ERROR<>0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET_CONI'
	RETURN
END


COMMIT TRANSACTION

SELECT @MSGERR = '0000 - OPERAZIONE TERMINATA CORRETTAMENTE'

RETURN
GO
