/****** Object:  StoredProcedure [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_COMUNI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_COMUNI] 

@CODLTM 		VARCHAR(7),
@DATAORAINS	CHAR(16),
@TIPOPROVV		CHAR(1),
@DATAPROVV		CHAR(8),
@NUMPROVV		VARCHAR(14),
@DATADECOR		CHAR(8),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@NEWFLAG		CHAR(1),
@DALOTTO		CHAR(1),
@STATO		CHAR(1),
@ORAOLD		CHAR(8),
@SERVIZIO		VARCHAR(4),
@ATTIVITA		VARCHAR(4),
@FIRMA		VARCHAR(17),
@NOTE		VARCHAR(255)


AS

DECLARE

@CHKLTM		VARCHAR(7),
@MSGERR		VARCHAR(255),
@CATEGORIA 	VARCHAR(10)


SELECT @CATEGORIA = '02'

BEGIN TRANSACTION

IF @DALOTTO = 'Y' -- L'ANNULLAMENTO DELLA MOVIMENTAZIONE PROVIENE DA UNA MOVIMENTAZIONE DEL LOTTO
BEGIN

	IF @NOTE IS NULL OR LTRIM(RTRIM(@NOTE)) = ''
	BEGIN
		SELECT @NOTE = 'ANNULLAMENTO DEL PROVVEDIMENTO LOTTO N° ' + @NUMPROVV + ' DEL ' + @DATAPROVV
	END
	
	UPDATE LSRSER_CITT SET 
	LSRSER_CITT_FLAG_VALIDITA = @NEWFLAG, 
	LSRSER_CITT_NOTE = @NOTE,
	LSRSER_CITT_FIRMA = @FIRMA,
	LSRSER_CITT_KEY_DATA_INS = @DATAINS,
	LSRSER_CITT_KEY_ORA_INS = @ORAINS
	WHERE 
	LSRSER_CITT_KEY_ID_RICEV = @CODLTM AND
	LSRSER_CITT_FLAG_VALIDITA = 'Y' AND
	LSRSER_CITT_TIPO_PROVV = @TIPOPROVV AND
	LSRSER_CITT_PROG_PROVV = @NUMPROVV AND
	LSRSER_CITT_DATA_PROVV = @DATAPROVV

	-- CANCELLO I RECORD DELLA TABELLA LSRLET_LIS LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET_LIS
	WHERE LSRLET_LIS_KEY_ID_RICEV = @CODLTM
	AND LSRLET_LIS_DECOR_DAL = @DATADECOR
	AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA

	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE IN CANCELLAZIONE RECORD LSRLET_LIS - RICEVITORIA ' + @CODLTM
		RAISERROR (@MSGERR, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END
END
ELSE IF @DALOTTO = 'N' -- L'ANNULLAMENTO DELLA MOVIMENTAZIONE NON PROVIENE DA UNA MOVIMENTAZIONE DEL LOTTO
BEGIN

	SELECT @DATAINS = NULL
	SELECT @ORAINS = NULL

	SELECT @DATAINS = CONVERT(CHAR, GETDATE(), 112)

	SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
				SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
				SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
				SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)

	UPDATE LSRSER_CITT SET
	LSRSER_CITT_FLAG_VALIDITA = @NEWFLAG, 
	LSRSER_CITT_KEY_DATA_INS = @DATAINS,
	LSRSER_CITT_KEY_ORA_INS = @ORAINS,
	LSRSER_CITT_NOTE = @NOTE,
	LSRSER_CITT_FIRMA = @FIRMA
	WHERE LSRSER_CITT_KEY_ID_RICEV = @CODLTM
	AND LSRSER_CITT_KEY_ORA_INS = @DATAINS
	AND LSRSER_CITT_KEY_ORA_INS = @ORAOLD

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET_LIS
	WHERE LSRLET_LIS_KEY_ID_RICEV = @CODLTM
	AND LSRLET_LIS_KEY_DATA_INS = @DATAINS
	AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRLET_LIS_KEY_SERVIZIO = @SERVIZIO
	AND LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA

	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE IN CANCELLAZIONE RECORD LSRLET_LIS - RICEVITORIA ' + @CODLTM
		RAISERROR (@MSGERR, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END

END


COMMIT TRANSACTION
GO
