/****** Object:  StoredProcedure [dbo].[AGGIORNA_TERM_MAGAZ]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[AGGIORNA_TERM_MAGAZ] AS 

DECLARE	

@RICEV01	CHAR(6),
@RICEVRIC	CHAR(6),
@TERM	CHAR(2),
@MAGAZ	CHAR(5),
@DATA	CHAR(8),
@MSGERR  	VARCHAR(100),
@NOMEJOB	VARCHAR(45),
@NOMEFILE	VARCHAR(25)

SELECT @DATA = CONVERT(CHAR(8),GETDATE(),112)
SELECT @NOMEJOB = 'AGG_TERM_MAGAZ_LOG_' + @DATA + '.txt'

SELECT @MSGERR = 'INIZIO S.P. AGGIORNA_TERM_MAGAZ ' + CONVERT(CHAR,GETDATE(),121)

EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0

DECLARE CUR_01 CURSOR FOR 
SELECT LSR01A_KEY_ID_RICEV, LSR01A_TERM_INST, LSR01A_CODICE_MAGAZZINO
FROM DATIVOS.VOS.LSR01A
WHERE SUBSTRING(LSR01A_KEY_ID_RICEV,2,1) <> 'X'


BEGIN TRANSACTION


OPEN CUR_01
FETCH NEXT FROM CUR_01 INTO @RICEV01,@TERM,@MAGAZ
WHILE @@FETCH_STATUS = 0 
BEGIN

	SELECT @RICEVRIC = NULL

	SELECT @RICEVRIC = LSRRIC_KEY_ID_RICEV
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @RICEV01

	IF @RICEVRIC IS NULL
	BEGIN
		SELECT @MSGERR = 'RICEVITORIA ' + @RICEV01 + ' INESISTENTE SU LSRRIC'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
	END
	ELSE
	BEGIN
		UPDATE LSRRIC SET 
		LSRRIC_CODICE_MAGAZZINO = @MAGAZ,
		LSRRIC_NUM_TERMINALI = @TERM
		WHERE LSRRIC_KEY_ID_RICEV = @RICEV01

		SELECT @MSGERR = 'AGGIORNATA RICEVITORIA ' + @RICEV01
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
	END

	SELECT @RICEV01 = NULL
	SELECT @TERM = NULL
	SELECT @MAGAZ = NULL

	FETCH NEXT FROM CUR_01 INTO @RICEV01,@TERM,@MAGAZ
	
END

COMMIT TRANSACTION

CLOSE CUR_01
DEALLOCATE CUR_01

SELECT @MSGERR = 'AGGIORNAMENTO EFFETTUATO'
EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
GO
