/****** Object:  StoredProcedure [dbo].[AGGIORNA_FT_VOS_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[AGGIORNA_FT_VOS_LIS] 

 AS

DECLARE  	

@IERI			CHAR(8),
@OGGI			CHAR(8),
@STRINGA		VARCHAR(100),
@FILELOG		VARCHAR(80),
@DATA		CHAR(8),
@NOMEJOB		VARCHAR(25),

@FLAG INT

SELECT @NOMEJOB = 'AACG012002GN'

SELECT @OGGI = CONVERT(CHAR, GETDATE(), 112)

SELECT @DATA = @OGGI

SELECT @IERI = CONVERT(CHAR, GETDATE() - 1, 112)

BEGIN TRANSACTION

--AGGIORNAMENTO TABELLA LSRSER_TEL
UPDATE LSRSER_TEL 
SET LSRSER_TEL_FT_VOS = @OGGI
WHERE
LSRSER_TEL_FLAG_VALIDITA = 'Y' AND
LSRSER_TEL_FT_VOS = '00000000' AND
LSRSER_TEL_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
LSRSER_TEL_KEY_DATA_INS < CONVERT(CHAR, GETDATE(), 112)

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @STRINGA='ERRORE IN AGGIORNAMENTO  LSRSER_TEL  ' 
	EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
	RAISERROR (@STRINGA, 16, 1)
	RETURN
END


--AGGIORNAMENTO TABELLA LSRSER_CITT
UPDATE LSRSER_CITT
SET LSRSER_CITT_FT_VOS = @OGGI
WHERE
LSRSER_CITT_FLAG_VALIDITA = 'Y' AND
LSRSER_CITT_FT_VOS = '00000000' AND
LSRSER_CITT_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
LSRSER_CITT_KEY_DATA_INS < CONVERT(CHAR, GETDATE(), 112)

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @STRINGA='ERRORE IN AGGIORNAMENTO  LSRSER_CITT  '
	EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
	RAISERROR (@STRINGA, 16, 1)
	RETURN
END


--AGGIORNAMENTO TABELLA LSRSER_PAG
UPDATE LSRSER_PAG
SET LSRSER_PAG_FT_VOS = @OGGI
WHERE
LSRSER_PAG_FLAG_VALIDITA = 'Y' AND
LSRSER_PAG_FT_VOS = '00000000' AND
LSRSER_PAG_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
LSRSER_PAG_KEY_DATA_INS < CONVERT(CHAR, GETDATE(), 112)

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @STRINGA='ERRORE IN AGGIORNAMENTO  LSRSER_PAG '
	EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
	RAISERROR (@STRINGA, 16, 1)
	RETURN
END


--AGGIORNAMENTO TABELLA LSRSER_BIG
UPDATE LSRSER_BIG
SET LSRSER_BIG_FT_VOS = @OGGI
WHERE
LSRSER_BIG_FLAG_VALIDITA = 'Y' AND
LSRSER_BIG_FT_VOS = '00000000' AND
LSRSER_BIG_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
LSRSER_BIG_KEY_DATA_INS < CONVERT(CHAR, GETDATE(), 112)


IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @STRINGA='ERRORE IN AGGIORNAMENTO  LSRSER_BIG '
	EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
	RAISERROR (@STRINGA, 16, 1)
	RETURN
END


--AGGIORNAMENTO TABELLA LSRSER_ATTI
UPDATE LSRSER_ATTI
SET LSRSER_ATTI_FT_VOS = @OGGI
WHERE
LSRSER_ATTI_FLAG_VALIDITA = 'Y' AND
LSRSER_ATTI_FT_VOS = '00000000' AND
LSRSER_ATTI_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
LSRSER_ATTI_KEY_DATA_INS < CONVERT(CHAR, GETDATE(), 112)

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @STRINGA='ERRORE IN AGGIORNAMENTO  LSRSER_ATTI '
	EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
	RAISERROR (@STRINGA, 16, 1)
	RETURN
END



COMMIT TRANSACTION

SELECT @STRINGA='SP AGGIORNA_FT_VOS TERMINATA CORRETTAMENTE'
EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
GO
