/****** Object:  StoredProcedure [dbo].[DISATTIVAZIONE_F101]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISATTIVAZIONE_F101]  
	@RICEV 		CHAR(6),
	@DATADIS		CHAR(8),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(50),
	@MSGERR 		VARCHAR(100) OUTPUT
AS

DECLARE 	

@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATAORAINS	CHAR(16),
@CHKRICEV		CHAR(6),
@STATOLOTTO	CHAR(1),
@STATOF101		CHAR(1),
@PROVVFUT		CHAR(8),
@DESCSTATO		CHAR(80)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

/*
' ESEGUO I CONTROLLI NEL CASO DI DISATTIVAZIONE AL SERVIZIO F101:
' 1) - ESISTE LA RICEVITORIA IN LSRSER_F101
' 2) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 3) - IL SERVIZIO SIA IN UNO STATO COMPATIBILE CON LA DISATTIVAZIONE
*/


/*
CONTROLLO 1
*/
SELECT @CHKRICEV = LSRSER_F101_KEY_ID_RICEV FROM LSRSER_F101
WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE SU LSRSER_F101'
	RETURN
END

/*
CONTROLLO 2
*/
SELECT @PROVVFUT = LSRSER_F101_DATA_DECOR,@STATOF101=LSRSER_F101_STATO
FROM LSRSER_F101
WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
AND LSRSER_F101_FLAG_VALIDITA = 'Y'
AND LSRSER_F101_DATA_DECOR = @DATADIS

IF @PROVVFUT IS NOT NULL

BEGIN
	IF @STATOF101 = '0'
	BEGIN
		SELECT @DESCSTATO = 'IL SERVIZIO RISULTA NON ATTIVO ALLA DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOF101 = '1'
	BEGIN
		SELECT @DESCSTATO = 'PROVV. DI TIPO ATTIVAZIONE/ RIATTIVAZIONE GIA PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOF101 = '2'
	BEGIN
		SELECT @DESCSTATO = 'PROVV. DI TIPO DISATTIVAZIONE GIA PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END

	SELECT @MSGERR = '6666 - ' + @RICEV + @DESCSTATO
	RETURN
END

/*
CONTROLLO 4
*/

SELECT @STATOF101 = LSRSER_F101_STATO FROM LSRSER_F101
WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
AND LSRSER_F101_FLAG_VALIDITA = 'Y'
AND LSRSER_F101_DATA_DECOR =
(
	SELECT MAX(LSRSER_F101_DATA_DECOR) FROM LSRSER_F101
	WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
	AND LSRSER_F101_FLAG_VALIDITA = 'Y'
	AND LSRSER_F101_DATA_DECOR <= @DATADIS
)

IF @STATOF101 = '0'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO F101 ANCORA NON ATTIVATO'
	RETURN
END

IF @STATOF101 = '2' 

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO F101 GIA DISATTIVATO'
	RETURN
END

--INIZIO MODIFICA IN DATA 02-05-2001

BEGIN TRANSACTION

SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
FROM LSRLET
WHERE LSRLET_KEY_ID_RICEV = @RICEV
AND LSRLET_COD_SERVIZIO = '02'
AND LSRLET_TIPO_MOVIMENTAZIONE = 'D'
AND LSRLET_KEY_DATA_INS = @DATAINS
AND LSRLET_DECOR_DAL = '00000000'

IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATADIS
	WHERE LSRLET_KEY_ID_RICEV = @RICEV
	AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_COD_SERVIZIO = '02'
	AND LSRLET_TIPO_MOVIMENTAZIONE = 'D'

END
ELSE
BEGIN
	INSERT INTO LSRLET VALUES(@RICEV,@DATAINS,@ORAINS,'02','D',@DATADIS,'','','00000000',@NOTE,@FIRMA,'V')
END

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET'
	ROLLBACK TRANSACTION
	RETURN
END


--FINE MODIFICA IN DATA 02-05-2001

INSERT INTO LSRSER_F101 VALUES (@RICEV,@DATAINS,@ORAINS,'2',@DATADIS,NULL,NULL,NULL,NULL,@FIRMA,NULL,'00000000','Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' ERRORE IN INSERT SU LSRSER_F101'
	ROLLBACK TRANSACTION
END
ELSE
BEGIN

	SELECT @MSGERR = '0000 - ' + @RICEV +'OPERAZIONE TERMINATA CORRETTAMENTE'
	COMMIT TRANSACTION
END
GO
