/****** Object:  StoredProcedure [dbo].[DISABILITA_SER_LOTTOMATICA]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[DISABILITA_SER_LOTTOMATICA] 

@RICEVITORIA 	CHAR(6),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATADECOR		CHAR(8),
@DATAPROVV		CHAR(8),
@TIPOPROVV		CHAR(1),
@NUMPROVV		CHAR(8),
@FIRMA		CHAR(17),
@OGGI			CHAR(8),
@NUMERR 		VARCHAR(4) OUTPUT,
@MSGERR 		VARCHAR(50) OUTPUT

AS

DECLARE	

@ASSOCIAZIONE	CHAR(1),
@STATO		CHAR(1),
@CANONE		CHAR(1),
@DATA		CHAR(8),
@ORA			CHAR(8),
@DATAINSLET	CHAR(8),
@NOTE		CHAR(150)


BEGIN TRANSACTION

SELECT @NOTE = 'SERVIZIO DISABILITATO DAL PROVVEDIMENTO LOTTO N° ' + @NUMPROVV + ' DEL ' + LTRIM(RTRIM(SUBSTRING(@DATAPROVV,7,2) + '-' + SUBSTRING(@DATAPROVV,5,2)+ '-' + SUBSTRING(@DATAPROVV,1,4)))
SELECT @DATA = CONVERT(CHAR,GETDATE(),112)
SELECT @ORA = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)

SELECT @DATAINSLET = @DATA

--MODIFICA DEL 15/05/2001
IF @DATADECOR <= @DATA
BEGIN
	SELECT @DATADECOR = CONVERT(CHAR,GETDATE() + 1,112)
END
--FINE MODIFICA

--MODIFICA DEL 10/05/2002 f.giacovazzi
IF @DATADECOR > CONVERT(CHAR,GETDATE() + 1,112)
BEGIN
	SELECT @DATAINSLET = CONVERT(CHAR,CONVERT(DATETIME,@DATADECOR)-1,112)
END
--FINE MODIFICA

--- TRATTAMENTO SERVIZIO F101

SELECT @STATO = NULL

SELECT @ASSOCIAZIONE=LSRSER_F101_ASSOCIAZIONE,@STATO=LSRSER_F101_STATO
FROM LSRSER_F101
WHERE LSRSER_F101_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_F101_DATA_DECOR =
(
	SELECT MAX(LSRSER_F101_DATA_DECOR) 
	FROM LSRSER_F101
	WHERE LSRSER_F101_DATA_DECOR <= @OGGI
	AND LSRSER_F101_FLAG_VALIDITA = 'Y'
	AND LSRSER_F101_KEY_ID_RICEV = @RICEVITORIA
)
AND LSRSER_F101_FLAG_VALIDITA = 'Y'

--MODIFICA DEL 31/07/2001
IF @STATO IS NOT NULL
--FINE MODIFICA DEL 31/07/2001
BEGIN
	--MODIFICA DEL 01/06/2001
	IF @STATO <>  '0'
	--FINE MODIFICA DEL 01/06/2001
	BEGIN
		INSERT INTO LSRSER_F101 VALUES
		(@RICEVITORIA,@DATAINS,@ORAINS,'2',@DATADECOR,
		@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_F101'
			ROLLBACK TRANSACTION
			RETURN
		END
		ELSE
		BEGIN
			UPDATE LSRSER_F101 SET
			LSRSER_F101_FLAG_VALIDITA = 'N'
			WHERE LSRSER_F101_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_F101_DATA_DECOR > @OGGI
			AND LSRSER_F101_DATA_DECOR <> @DATADECOR

			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_F101'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN
				--MODIFICA DEL 22/06/2001: 
				--SE DISATTIVO E IL SERVIZIO è ATTIVO DEVO INVIARE LA LETTERA 
				IF @STATO = '1'
				BEGIN
					INSERT INTO LSRLET VALUES
					(@RICEVITORIA,@DATAINSLET,@ORA,'02','D',@DATADECOR,'LSRPRO',
					@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')

					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
						ROLLBACK TRANSACTION
						RETURN
					END
				END
				ELSE
				BEGIN
					--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
					INSERT INTO LSRLET VALUES
					(@RICEVITORIA,@DATAINSLET,@ORA,'02','D',@DATADECOR,'LSRPRO',
					@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')

					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
						ROLLBACK TRANSACTION
						RETURN
					END
				END
			END
		END
	END
END

--- TRATTAMENTO SERVIZIO TRIS - DISABILITATO IL 27/12/2005
/*
SELECT @STATO = NULL

SELECT @ASSOCIAZIONE=LSRSER_TRIS_ASSOCIAZIONE,@STATO=LSRSER_TRIS_STATO
FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_TRIS_DATA_DECOR =
(
	SELECT MAX(LSRSER_TRIS_DATA_DECOR) 
	FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_DATA_DECOR <= @OGGI
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
	AND LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
)
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'


--MODIFICA DEL 31/07/2001
IF @STATO IS NOT NULL
--FINE MODIFICA DEL 31/07/2001
BEGIN

	--MODIFICA DEL 01/06/2001
	IF @STATO <> '0'
	--FINE MODIFICA DEL 01/06/2001
	BEGIN
		--MODIFICA DEL 07/08/2002
		--SE LO STATO DEL SERVIZIO TRIS E' 2, DEVE RIMANERE A 2
		IF @STATO = '2'
		BEGIN
			INSERT INTO LSRSER_TRIS VALUES
			(@RICEVITORIA,@DATAINS,@ORAINS,'2',@DATADECOR,
			@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')
		END
		ELSE
		BEGIN
			INSERT INTO LSRSER_TRIS VALUES
			(@RICEVITORIA,@DATAINS,@ORAINS,'3',@DATADECOR,
			@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')
		END
		--FINE MODIFICA DEL 07/08/2002


		IF @@ERROR <> 0 
		BEGIN
			SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' - ERRORE IN INSERIMENTO LSRSER_TRIS'
			ROLLBACK TRANSACTION
			RETURN
		END
		ELSE
		BEGIN
			UPDATE LSRSER_TRIS SET
			LSRSER_TRIS_FLAG_VALIDITA = 'N'
			WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_TRIS_DATA_DECOR > @OGGI
			AND LSRSER_TRIS_DATA_DECOR <> @DATADECOR

			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_TRIS'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN
				--MODIFICA DEL 22/06/2001: 
				--SE DISATTIVO E IL SERVIZIO è ATTIVO DEVO INVIARE LA LETTERA
				IF @STATO = '1' 
				BEGIN
					INSERT INTO LSRLET VALUES
					(@RICEVITORIA,@DATAINSLET,@ORA,'08','S',@DATADECOR,'LSRPRO',
					@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')

					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
						ROLLBACK TRANSACTION
						RETURN
					END
				END
				ELSE
				BEGIN
				--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
					--MODIFICA DEL 07/08/2002
					--SE LO STATO DEL SERVIZIO TRIS E' 2, DEVE RIMANERE A 2, QUINDI SULLA LETTERA LO STATO E' D
					IF @STATO = '2'
					BEGIN
						INSERT INTO LSRLET VALUES
						(@RICEVITORIA,@DATAINSLET,@ORA,'08','D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')
					END
					ELSE
					BEGIN
						INSERT INTO LSRLET VALUES
						(@RICEVITORIA,@DATAINSLET,@ORA,'08','S',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')
					END
					--FINE MODIFICA DEL 07/08/2002
					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
						ROLLBACK TRANSACTION
						RETURN
					END

				END
			END
		END
	END
END

*/

--- TRATTAMENTO SERVIZIO BOLLO

SELECT @STATO = NULL

SELECT @ASSOCIAZIONE=LSRSER_BOLLO_ASSOCIAZIONE,@STATO=LSRSER_BOLLO_STATO,
@CANONE=LSRSER_BOLLO_CANONE
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_BOLLO_DATA_DECOR =
(
	SELECT MAX(LSRSER_BOLLO_DATA_DECOR) 
	FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_DATA_DECOR <= @OGGI
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
	AND LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
)
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'


--MODIFICA DEL 31/07/2001
IF @STATO IS NOT NULL
--FINE MODIFICA DEL 31/07/2001
BEGIN

	--MODIFICA DEL 01/06/2001
	IF @STATO <> '0'
	--FINE MODIFICA DEL 01/06/2001
	BEGIN
		-- MODIFICA DEL 03/08/2001: IL FLAG  CANONE VA MESSO A N
		INSERT INTO LSRSER_BOLLO VALUES
		(@RICEVITORIA,@DATAINS,@ORAINS,'2',@DATADECOR,'N',
		@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_BOLLO'
			ROLLBACK TRANSACTION
			RETURN
		END
		ELSE
		BEGIN
			UPDATE LSRSER_BOLLO SET
			LSRSER_BOLLO_FLAG_VALIDITA = 'N'
			WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_BOLLO_DATA_DECOR > @OGGI
			AND LSRSER_BOLLO_DATA_DECOR <> @DATADECOR

			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_BOLLO'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN
				--MODIFICA DEL 22/06/2001: 
				--SE DISATTIVO E IL SERVIZIO è ATTIVO, DEVO INVIARE LA LETTERA 
				IF @STATO = '1'
				BEGIN
					INSERT INTO LSRLET VALUES
					(@RICEVITORIA,@DATAINSLET,@ORA,'05','D',@DATADECOR,'LSRPRO',
					@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')

					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
						ROLLBACK TRANSACTION
						RETURN
					END
				END
				ELSE
				BEGIN
				--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
					INSERT INTO LSRLET VALUES
					(@RICEVITORIA,@DATAINSLET,@ORA,'05','D',@DATADECOR,'LSRPRO',
					@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')

					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
						ROLLBACK TRANSACTION
						RETURN
					END
				END
			END
		END
	END
END



SELECT @STATO = NULL

SELECT @STATO=LSRSER_GEV_stato
FROM LSRSER_GEV
WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_GEV_DATA_DECOR =
(
	SELECT MAX(LSRSER_GEV_DATA_DECOR) 
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_DATA_DECOR <= @OGGI
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
)
AND LSRSER_GEV_FLAG_VALIDITA = 'Y'


--MODIFICA DEL 31/07/2001
IF @STATO IS NOT NULL
--FINE MODIFICA DEL 31/07/2001
BEGIN

	--MODIFICA DEL 01/06/2001
	IF @STATO <> '0'
	--FINE MODIFICA DEL 01/06/2001
	BEGIN
		-- MODIFICA DEL 03/08/2001: IL FLAG  CANONE VA MESSO A N
		INSERT INTO LSRSER_GEV VALUES
		(@RICEVITORIA,@DATAINS,@ORAINS,'2',@DATADECOR,'D',
		@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_GEV'
			ROLLBACK TRANSACTION
			RETURN
		END
		ELSE
		BEGIN
			UPDATE LSRSER_GEV SET
			LSRSER_GEV_FLAG_VALIDITA = 'N'
			WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_GEV_DATA_DECOR > @OGGI
			AND LSRSER_GEV_DATA_DECOR <> @DATADECOR

			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_GEV'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN
				--MODIFICA DEL 22/06/2001: 
				--SE DISATTIVO E IL SERVIZIO è ATTIVO, DEVO INVIARE LA LETTERA 
				IF @STATO = '1'
				BEGIN
					INSERT INTO LSRLET VALUES
					(@RICEVITORIA,@DATAINSLET,@ORA,'09','D',@DATADECOR,'LSRPRO',
					@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')

					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
						ROLLBACK TRANSACTION
						RETURN
					END
				END
				ELSE
				BEGIN
				--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
					INSERT INTO LSRLET VALUES
					(@RICEVITORIA,@DATAINSLET,@ORA,'09','D',@DATADECOR,'LSRGEV',
					@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')

					IF @@ERROR <> 0 
					BEGIN
						SELECT @NUMERR = '9999'
						SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
						ROLLBACK TRANSACTION
						RETURN
					END
				END
			END
		END
	END
END



--MODIFICA DEL 14-06-2002 F.GIACOVAZZI

--TRATTAMENTO GEV
--EXEC GEV_DISATTIVAZIONE_DA_LOTTO
--@RICEVITORIA,
--@DATAINS,
--@ORAINS,
--@DATADECOR,
--@DATAPROVV,
--@TIPOPROVV,
--@NUMPROVV,
--@FIRMA,
--@OGGI	

--IF @@ERROR <> 0 
--BEGIN
--	SELECT @NUMERR = '9999'
--	SELECT @MSGERR = @NUMERR + ' -  ERRORE IN TRATTAMENTO GEV'
--	ROLLBACK TRANSACTION
--	RETURN
--END
--FINE MODIFICA

SELECT @NUMERR = '0000'
SELECT @MSGERR = @NUMERR
COMMIT TRANSACTION

RETURN
GO
