/****** Object:  StoredProcedure [dbo].[DISABILITA_SER_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[DISABILITA_SER_LIS] 

	@RICEVITORIA 	CHAR(6),
	@DATAINS		CHAR(8),
	@ORAINS		CHAR(8),
	@DATADECOR		CHAR(8),
	@DATAPROVV		CHAR(8),
	@TIPOPROVV		CHAR(1),
	@NUMPROVV		CHAR(14),
	@FIRMA		CHAR(17),
	@OGGI			CHAR(8),
	@NUMERR 		VARCHAR(4) OUTPUT,
	@MSGERR 		VARCHAR(50) OUTPUT
AS

DECLARE	

@ASSOCIAZIONE	CHAR(1),
@STATO		CHAR(1),
@CANONE		CHAR(1),
@DATA		CHAR(8),
@DATAINSLET		CHAR(8),
@ORA			CHAR(8),
@DATADECORLET	CHAR(8),
@CATEGORIA		CHAR(2),
@SERVIZIO		CHAR(2),
@ATTIVITA		CHAR(2),
@NOTE		CHAR(150)
	

BEGIN TRANSACTION

IF @TIPOPROVV = 'I'
BEGIN
	SELECT @NOTE = 'SERVIZIO DISABILITATO DAL CAMBIO INTESTAZIONE N° ' + @NUMPROVV + ' DEL ' + LTRIM(RTRIM(SUBSTRING(@DATAPROVV,7,2) + '-' + SUBSTRING(@DATAPROVV,5,2)+ '-' + SUBSTRING(@DATAPROVV,1,4)))
END
ELSE
BEGIN
	SELECT @NOTE = 'SERVIZIO DISABILITATO DAL PROVVEDIMENTO LOTTO N° ' + @NUMPROVV + ' DEL ' + LTRIM(RTRIM(SUBSTRING(@DATAPROVV,7,2) + '-' + SUBSTRING(@DATAPROVV,5,2)+ '-' + SUBSTRING(@DATAPROVV,1,4)))
END


SELECT @DATA = CONVERT(CHAR,GETDATE(),112)
SELECT @ORA = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)



SELECT @DATAINSLET = @DATA

--MODIFICA DEL 15/05/2001
IF @DATADECOR <= @DATA
BEGIN
	SELECT @DATADECOR = CONVERT(CHAR,GETDATE() + 1,112)
END
--FINE MODIFICA

--MODIFICA DEL 10/05/2002 
IF @DATADECOR > CONVERT(CHAR,GETDATE() + 1,112)
BEGIN
	SELECT @DATAINSLET = CONVERT(CHAR,CONVERT(DATETIME,@DATADECOR)-1,112)
END
--FINE MODIFICA


DECLARE CUR_R1 SCROLL CURSOR FOR

SELECT  LSRSER_LIS_DEC_CATEGORIA,   LSRSER_LIS_DEC_SERVIZIO,  LSRSER_LIS_DEC_ATTIVITA  
FROM LSRSER_LIS_DEC A 
WHERE LSRSER_LIS_DEC_SERVIZIO <>''
AND NOT EXISTS ( 
	SELECT * FROM LSRSER_LIS_DEC 
 	WHERE A.LSRSER_LIS_DEC_CATEGORIA = LSRSER_LIS_DEC_CATEGORIA
 		AND A.LSRSER_LIS_DEC_SERVIZIO = LSRSER_LIS_DEC_SERVIZIO
 		AND LSRSER_LIS_DEC_ATTIVITA <> ''
	)
UNION
SELECT  LSRSER_LIS_DEC_CATEGORIA,  LSRSER_LIS_DEC_SERVIZIO,  LSRSER_LIS_DEC_ATTIVITA  
FROM LSRSER_LIS_DEC 
WHERE LSRSER_LIS_DEC_CATEGORIA <> ''
	AND LSRSER_LIS_DEC_SERVIZIO <> ''
	AND LSRSER_LIS_DEC_ATTIVITA <> ''

OPEN CUR_R1
FETCH NEXT FROM CUR_R1
INTO @CATEGORIA, @SERVIZIO, @ATTIVITA


WHILE @@FETCH_STATUS = 0 
BEGIN

	--******************************************************************************
	--- TRATTAMENTO CATEGORIA 01 - SERVIZI TELEFONICI
	--******************************************************************************
	IF @CATEGORIA = '01'
	BEGIN

	             	SELECT @STATO = NULL

		SELECT  @STATO  = LSRSER_TEL_STATO, @ASSOCIAZIONE = LSRSER_TEL_ASSOCIAZIONE
		FROM LSRSER_TEL
		WHERE LSRSER_TEL_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_TEL_DATA_DECOR =
				(SELECT MAX(LSRSER_TEL_DATA_DECOR) 
				FROM LSRSER_TEL
				WHERE LSRSER_TEL_DATA_DECOR <= @OGGI
					AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA
					AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
					AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
					AND LSRSER_TEL_FLAG_VALIDITA = 'Y'
					AND LSRSER_TEL_KEY_ID_RICEV = @RICEVITORIA)
			AND LSRSER_TEL_FLAG_VALIDITA = 'Y'

		IF @STATO =  '1' OR @STATO =  '2' 
		BEGIN
			UPDATE LSRSER_TEL SET
			LSRSER_TEL_FLAG_VALIDITA = 'N'
			WHERE LSRSER_TEL_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_TEL_DATA_DECOR >= @DATADECOR	

		
			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_TEL'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN

				INSERT INTO LSRSER_TEL VALUES
				(@RICEVITORIA,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA,'2',@DATADECOR,
				@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

				IF @@ERROR <> 0 
				BEGIN
					SELECT @NUMERR = '9999'
					SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_TEL'
					ROLLBACK TRANSACTION
					RETURN
				END
				ELSE
				BEGIN
					--MODIFICA DEL 22/06/2001: 
					--SE DISATTIVO E IL SERVIZIO è ATTIVO DEVO INVIARE LA LETTERA 
					IF @STATO = '1'
					BEGIN
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA,@DATAINSLET,@ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')
						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
					ELSE
					BEGIN
						--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET, @ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')
	
						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
				END
			END

		END --IF @STATO 
	
	END --END IF @CATEGORIA = 01


	--******************************************************************************
	--- TRATTAMENTO CATEGORIA 02 - SERVIZI AL CITTADINO
	--******************************************************************************
	IF @CATEGORIA = '02'
	BEGIN

	             	SELECT @STATO = NULL

		SELECT  @STATO  = LSRSER_CITT_STATO, @ASSOCIAZIONE = LSRSER_CITT_ASSOCIAZIONE
		FROM LSRSER_CITT
		WHERE LSRSER_CITT_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_CITT_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_CITT_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_CITT_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_CITT_DATA_DECOR =
			(SELECT MAX(LSRSER_CITT_DATA_DECOR) 
			FROM LSRSER_CITT
			WHERE LSRSER_CITT_DATA_DECOR <= @OGGI
				AND LSRSER_CITT_KEY_CATEGORIA = @CATEGORIA
				AND LSRSER_CITT_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_CITT_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_CITT_FLAG_VALIDITA = 'Y'
				AND LSRSER_CITT_KEY_ID_RICEV = @RICEVITORIA)
			AND LSRSER_CITT_FLAG_VALIDITA = 'Y'

		IF @STATO =  '1' OR @STATO =  '2' 
		BEGIN
			UPDATE LSRSER_CITT SET
			LSRSER_CITT_FLAG_VALIDITA = 'N'
			WHERE LSRSER_CITT_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_CITT_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_CITT_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_CITT_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_CITT_DATA_DECOR >= @DATADECOR
	
			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_CITT'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN
				INSERT INTO LSRSER_CITT VALUES
				(@RICEVITORIA,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA,'2',@DATADECOR,
				@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')
				IF @@ERROR <> 0 
				BEGIN
					SELECT @NUMERR = '9999'
					SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_CITT'
					ROLLBACK TRANSACTION
					RETURN
				END
				ELSE
				BEGIN
					--MODIFICA DEL 22/06/2001: 
					--SE DISATTIVO E IL SERVIZIO è ATTIVO DEVO INVIARE LA LETTERA 
					IF @STATO = '1'
					BEGIN
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET,@ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')
	
						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
					ELSE
					BEGIN
						--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET, @ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')
	
						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
				END
			END
		END --IF @STATO <>  '0'
	
	END --END IF @CATEGORIA = 02

	--******************************************************************************
	--- TRATTAMENTO CATEGORIA 03 - PAGAMENTO UTENZE
	--******************************************************************************
	IF @CATEGORIA = '03'
	BEGIN

	             	SELECT @STATO = NULL

		SELECT  @STATO  = LSRSER_PAG_STATO, @ASSOCIAZIONE = LSRSER_PAG_ASSOCIAZIONE
		FROM LSRSER_PAG
		WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_PAG_DATA_DECOR =
			(SELECT MAX(LSRSER_PAG_DATA_DECOR) 
			FROM LSRSER_PAG
			WHERE LSRSER_PAG_DATA_DECOR <= @OGGI
				AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA
				AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
				AND LSRSER_PAG_KEY_ID_RICEV = @RICEVITORIA)
			AND LSRSER_PAG_FLAG_VALIDITA = 'Y'

		IF @STATO =  '1' OR @STATO =  '2' 
		BEGIN	
			UPDATE LSRSER_PAG SET
			LSRSER_PAG_FLAG_VALIDITA = 'N'
			WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_PAG_DATA_DECOR >= @DATADECOR
			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_PAG'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN
				INSERT INTO LSRSER_PAG VALUES
				(@RICEVITORIA,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA,'2',@DATADECOR,
				@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

				IF @@ERROR <> 0 
				BEGIN
					SELECT @NUMERR = '9999'
					SELECT @MSGERR = @NUMERR + ' -  ERRORE IN  INSERIMENTO LSRSER_PAG'
					ROLLBACK TRANSACTION
					RETURN
				END
				ELSE
				BEGIN
					--MODIFICA DEL 22/06/2001: 
					--SE DISATTIVO E IL SERVIZIO è ATTIVO DEVO INVIARE LA LETTERA 
					IF @STATO = '1'
					BEGIN
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET, @ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')

						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
					ELSE
					BEGIN
						--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET, @ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')
	
						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
				END
			END

		END --IF @STATO IS NOT NULL
	
	END --END IF @CATEGORIA = 03

	--******************************************************************************
	--- TRATTAMENTO CATEGORIA 04 - BIGLIETTERIA
	--******************************************************************************
	IF @CATEGORIA = '04'
	BEGIN

	             	SELECT @STATO = NULL

		SELECT  @STATO  = LSRSER_BIG_STATO, @ASSOCIAZIONE = LSRSER_BIG_ASSOCIAZIONE
		FROM LSRSER_BIG
		WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_BIG_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_BIG_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_BIG_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_BIG_DATA_DECOR =
			(SELECT MAX(LSRSER_BIG_DATA_DECOR) 
			FROM LSRSER_BIG
			WHERE LSRSER_BIG_DATA_DECOR <= @OGGI
				AND LSRSER_BIG_KEY_CATEGORIA = @CATEGORIA
				AND LSRSER_BIG_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_BIG_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
				AND LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIA)
			AND LSRSER_BIG_FLAG_VALIDITA = 'Y'

		IF @STATO =  '1' OR @STATO =  '2' 
		BEGIN
			UPDATE LSRSER_BIG SET
			LSRSER_BIG_FLAG_VALIDITA = 'N'
			WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_BIG_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_BIG_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_BIG_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_BIG_DATA_DECOR >= @DATADECOR
			
			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_BIG'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN
				INSERT INTO LSRSER_BIG VALUES
					(@RICEVITORIA,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA,'2',@DATADECOR,
					@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')
	
				IF @@ERROR <> 0 
				BEGIN
					SELECT @NUMERR = '9999'
					SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_BIG'
					ROLLBACK TRANSACTION
					RETURN
				END
				ELSE
				BEGIN
					--MODIFICA DEL 22/06/2001: 
					--SE DISATTIVO E IL SERVIZIO è ATTIVO DEVO INVIARE LA LETTERA 
					IF @STATO = '1'
					BEGIN
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET, @ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')

						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
					ELSE
					BEGIN
						--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET, @ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')
	
						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
				END
			END
		END --IF @STATO <>  '0'

	END --END IF @CATEGORIA = 04


	--******************************************************************************
	--- TRATTAMENTO CATEGORIA 05 - ATTI GIUDIZIARI
	--******************************************************************************
	IF @CATEGORIA = '05'
	BEGIN

	             	SELECT @STATO = NULL

		SELECT  @STATO  = LSRSER_ATTI_STATO, @ASSOCIAZIONE = LSRSER_ATTI_ASSOCIAZIONE
		FROM LSRSER_ATTI
		WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_ATTI_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_ATTI_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_ATTI_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_ATTI_DATA_DECOR =
			(SELECT MAX(LSRSER_ATTI_DATA_DECOR) 
			FROM LSRSER_ATTI
			WHERE LSRSER_ATTI_DATA_DECOR <= @OGGI
				AND LSRSER_ATTI_KEY_CATEGORIA = @CATEGORIA
				AND LSRSER_ATTI_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_ATTI_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'
				AND LSRSER_ATTI_KEY_ID_RICEV = @RICEVITORIA)
			AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'


		IF @STATO =  '1' OR @STATO =  '2' 
		BEGIN
			UPDATE LSRSER_ATTI SET
			LSRSER_ATTI_FLAG_VALIDITA = 'N'
			WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEVITORIA
			AND LSRSER_ATTI_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_ATTI_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_ATTI_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_ATTI_DATA_DECOR >= @DATADECOR
	
			IF @@ERROR <> 0 
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' -  ERRORE IN AGGIORNAMENTO LSRSER_ATTI'
				ROLLBACK TRANSACTION
				RETURN
			END
			ELSE
			BEGIN
				INSERT INTO LSRSER_ATTI VALUES
				(@RICEVITORIA,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA,'2',@DATADECOR,
				@TIPOPROVV,@DATAPROVV,@NUMPROVV,@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

				IF @@ERROR <> 0 
				BEGIN
					SELECT @NUMERR = '9999'
					SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRSER_ATTI'
					ROLLBACK TRANSACTION
					RETURN
				END
				ELSE
				BEGIN
					--MODIFICA DEL 22/06/2001: 
					--SE DISATTIVO E IL SERVIZIO è ATTIVO DEVO INVIARE LA LETTERA 
					IF @STATO = '1'
					BEGIN
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET,@ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')
	
						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
					ELSE
					BEGIN
						--SE DISATTIVO E IL SERVIZIO è GIà DISATTIVO, NON DEVO INVIARE LA LETTERA PERCHè IL CAMBIAMENTO DI STATO è DOVUTO A CAMBIAMENTO DEL LOTTO
						INSERT INTO LSRLET_LIS VALUES
						(@RICEVITORIA, @DATAINSLET, @ORA,@CATEGORIA, @SERVIZIO, @ATTIVITA,'D',@DATADECOR,'LSRPRO',
						@DATAINS+@ORAINS,'19000101','',@FIRMA,'V')
	
						IF @@ERROR <> 0 
						BEGIN
							SELECT @NUMERR = '9999'
							SELECT @MSGERR = @NUMERR + ' -  ERRORE IN INSERIMENTO LSRLET'
							ROLLBACK TRANSACTION
							RETURN
						END
					END
				END
			END
		END --IF @STATO <>  '0'

	
	END --END IF @CATEGORIA = 05

	
	FETCH NEXT FROM CUR_R1		
	INTO @CATEGORIA, @SERVIZIO, @ATTIVITA

END -- WHILE

CLOSE CUR_R1
DEALLOCATE CUR_R1



SELECT @NUMERR = '0000'
SELECT @MSGERR = @NUMERR
COMMIT TRANSACTION

RETURN
GO
