/****** Object:  StoredProcedure [dbo].[ANA_DISATTIVA_BOLLO_TEMP]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_DISATTIVA_BOLLO_TEMP] 

@CODLTM 		CHAR(6),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@FIRMA		VARCHAR(17),
@NOTE		VARCHAR(255),
@MSGOUT 		VARCHAR(255) OUTPUT

AS

DECLARE 	

@CHKRICEV		CHAR(6),
@STATOA		CHAR(1),
@STATOF		CHAR(1),
@CANONE		CHAR(1),
@DATADECOR		CHAR(8),
@DATAAPP		CHAR(8),
@ASSOCIAZIONE	CHAR(1),
@DESCSTATO		VARCHAR(255)

SELECT @DATADECOR = CONVERT(CHAR(8),GETDATE() + 1,112)


/*
' ESEGUO I CONTROLLI NEL CASO DI DISATTIVAZIONE AL SERVIZIO BOLLO:
' 1) - ESISTE LA RICEVITORIA IN LSRRIC
' 2) - ESISTE LA RICEVITORIA IN LSRSER_BOLLO
' 3) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 4) - IL SERVIZIO SIA IN UNO STATO COMPATIBILE CON LA DISATTIVAZIONE
*/


/*
CONTROLLO 1 - ESISTE LA RICEVITORIA IN LSRRIC
*/

SELECT @CHKRICEV = NULL

SELECT DISTINCT @CHKRICEV = LSRRIC_KEY_ID_RICEV 
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @CODLTM

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGOUT = '1111 - RICEVITORIA INESISTENTE'
	RETURN
END


/*
CONTROLLO 2
*/

SELECT @CHKRICEV = NULL

SELECT @CHKRICEV = LSRSER_BOLLO_KEY_ID_RICEV 
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGOUT = '1111 - RICEVITORIA INESISTENTE SU LSRSER_BOLLO'
	RETURN
END

/*
CONTROLLO 3
*/

SELECT @STATOF = NULL
SELECT @DESCSTATO = NULL

SELECT @DESCSTATO = 
CASE LSRSER_BOLLO_STATO
	WHEN '0' THEN 'RISULTA NON ATTIVATO'
	WHEN '1' THEN 'RISULTA ATTIVATO'
	WHEN '2' THEN 'RISULTA DISATTIVATO'
END,
@STATOF = LSRSER_BOLLO_STATO
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_DATA_DECOR = @DATADECOR

IF @STATOF IS NOT NULL

BEGIN
	IF @STATOF = '0'
	BEGIN
		SELECT @DESCSTATO = @DESCSTATO + ' ALLA DATA ' + SUBSTRING(@DATADECOR,7,2) + '-' + SUBSTRING(@DATADECOR,5,2) + '-' + SUBSTRING(@DATADECOR,1,4) 
	END
	ELSE IF @STATOF = '1'
	BEGIN
		SELECT @DESCSTATO = @DESCSTATO + ' ALLA DATA ' + SUBSTRING(@DATADECOR,7,2) + '-' + SUBSTRING(@DATADECOR,5,2) + '-' + SUBSTRING(@DATADECOR,1,4) 
	END
	ELSE IF @STATOF = '2'
	BEGIN
		SELECT @DESCSTATO = @DESCSTATO + ' ALLA DATA ' + SUBSTRING(@DATADECOR,7,2) + '-' + SUBSTRING(@DATADECOR,5,2) + '-' + SUBSTRING(@DATADECOR,1,4) 
	END

	SELECT @MSGOUT = '1111 - ' + @DESCSTATO
	RETURN
END

/*
CONTROLLO 4
*/

SELECT @STATOA = NULL
SELECT @DESCSTATO = NULL
SELECT @ASSOCIAZIONE = NULL
SELECT @CANONE = NULL
SELECT @DATAAPP = NULL

SELECT @STATOA = LSRSER_BOLLO_STATO, 
	@DATAAPP = LSRSER_BOLLO_DATA_DECOR,
	@ASSOCIAZIONE = LSRSER_BOLLO_ASSOCIAZIONE, 
	@CANONE = LSRSER_BOLLO_CANONE,
	@DESCSTATO =
	CASE LSRSER_BOLLO_STATO
		WHEN '0' THEN 'RISULTA NON ATTIVATO'
		WHEN '1' THEN 'RISULTA ATTIVATO'
		WHEN '2' THEN 'RISULTA DISATTIVATO'
		ELSE 'NON PRESENTE'
	END
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_DATA_DECOR =
(
	SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
	AND LSRSER_BOLLO_DATA_DECOR <= @DATADECOR
)

IF @STATOA <> '1'
BEGIN
	IF @STATOA IS NULL
	BEGIN
		SELECT @DESCSTATO = @DESCSTATO
	END
	ELSE IF @STATOA = '0'
	BEGIN
		SELECT @DESCSTATO = @DESCSTATO
	END
	ELSE IF @STATOA = '2' 
	BEGIN
		SELECT @DESCSTATO = @DESCSTATO +  + ' IN DATA ' + SUBSTRING(@DATAAPP,7,2) + '-' + SUBSTRING(@DATAAPP,5,2) + '-' + SUBSTRING(@DATAAPP,1,4) 
	END

	SELECT @MSGOUT = '1111 - ' + @DESCSTATO
	RETURN
END

BEGIN TRANSACTION

INSERT INTO LSRLET VALUES
(@CODLTM, @DATAINS, @ORAINS, '05', 'D', @DATADECOR, '', '', '00000000', @NOTE, @FIRMA, 'V')


IF @@ERROR <> 0 
BEGIN
	SELECT @MSGOUT = '9999 - ' + @CODLTM +' ERRORE IN INSERIMENTO RECORD SU LSRLET'
	RAISERROR(@MSGOUT, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


INSERT INTO LSRSER_BOLLO VALUES 
(@CODLTM, @DATAINS, @ORAINS, '2', @DATADECOR, @CANONE, NULL, NULL, NULL, @ASSOCIAZIONE, @FIRMA, '', '00000000', 'Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGOUT = '9999 - ' + @CODLTM +' ERRORE IN INSERIMENTO RECORD SU LSRSER_BOLLO'
	RAISERROR(@MSGOUT, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

SELECT @MSGOUT = '0000 - OPERAZIONE TERMINATA CORRETTAMENTE'

COMMIT TRANSACTION
GO
