/****** Object:  StoredProcedure [dbo].[INSERTPROVVCONC]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[INSERTPROVVCONC]  

	@RICEVITORIA 	CHAR(6),
	@TIPO			CHAR(1),
	@DATAINS		CHAR(8),
	@DATAPROVV		CHAR(8),
	@PROGPROVV		CHAR(14),
	@CAUSALE		CHAR(40),
	@FIRMA		CHAR(17),
	@EMANATO		CHAR(25),
	@DECORDAL		CHAR(8),
	@DECORAL		CHAR(8),
	@TASSA		CHAR(9),
	@ANNO		CHAR(4),
	@MASSIMALE		CHAR(11),
	@CODTAB		CHAR(10),
	@FLGANN		CHAR(1),
	@MSGERR 		VARCHAR(70) OUTPUT



AS

DECLARE 

@ORAINS		CHAR(8),
@NUMERR		CHAR(50)


SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)  + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2) 

BEGIN TRANSACTION

INSERT INTO LSRPRO VALUES 
(@RICEVITORIA,@TIPO,@DATAINS,@ORAINS,@DATAPROVV,@PROGPROVV,
 @CAUSALE,@FIRMA,@EMANATO,@DECORDAL,@DECORAL,@TASSA,@ANNO,
 @MASSIMALE,@CODTAB,@FLGANN,'Y',@DATAINS)

             
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR =  '9999 - ' + @RICEVITORIA + ' - ' + @TIPO + ' - ERRORE IN INSERIMENTO LSRPRO'
             ROLLBACK TRANSACTION
             RETURN 
END
ELSE
BEGIN
	COMMIT TRANSACTION
	SELECT @MSGERR = '0000'
END
GO
