/****** Object:  StoredProcedure [dbo].[GEV_ASSOCIA_TITOLARE_DOCUMENTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_ASSOCIA_TITOLARE_DOCUMENTO]

@RICEV 		VARCHAR(7),
@COGNOME		VARCHAR(24),
@NOME		VARCHAR(20),
@FLGANAG		CHAR(1)	OUTPUT,
@FKDATAINS		CHAR(8)	OUTPUT,
@FKORAINS		CHAR(8)	OUTPUT

AS


DECLARE 	
@APPORICEV		CHAR(6),
@DATAOGGI   		CHAR(8),
@ORAOGGI  		CHAR(8),
@COGNOMETIT	CHAR(24),
@NOMETIT		CHAR(20),
@FLAGANAGTIT	CHAR(1),
@DATAINSTIT		CHAR(8),
@ORAINSTIT		CHAR(8),
@TIPOPREC 		CHAR(1),
@TIPOPROVV		CHAR(1),
@TITTROVATO	CHAR(1),
@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)

 	DECLARE CUR_R1 SCROLL CURSOR FOR
	
	SELECT LSRTIT_COGNOME, LSRTIT_NOME, LSRTIT_KEY_DATA_INS, LSRTIT_KEY_ORA_INS, LSRTIT_TIPO_PROVV
	FROM LSRTIT	WHERE 
	LSRTIT_KEY_ID_RICEV = @RICEV AND
	LSRTIT_DATA_VALIDITA < @DATAOGGI AND
	LSRTIT_FLAG_VALIDITA = 'Y' AND
	LSRTIT_TIPO_PROVV IN ('E', 'I', 'C')
	ORDER BY LSRTIT_DATA_VALIDITA DESC 

	SELECT @TIPOPREC = ''
	SELECT @FLAGOK = 'N'
	SELECT @TITTROVATO = 'N'
	SELECT @FLGANAG ='0'
	SELECT @FKDATAINS ='00000000'
	SELECT @FKORAINS ='00000000'

	OPEN CUR_R1
	FETCH NEXT FROM CUR_R1
	INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @TIPOPROVV
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @TITTROVATO = 'N'
		BEGIN
			  --******************************************************************
			  --INIZIO CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			 --******************************************************************
			IF @TIPOPREC = ''
			BEGIN
				SELECT @TIPOPREC = @TIPOPROVV
				SELECT @FLAGOK ='Y'
				SELECT @FLAGANAGTIT ='1'
			END
			ELSE
			BEGIN
				IF @TIPOPREC = 'E' AND @FLAGOK ='Y'
				BEGIN
					SELECT @TIPOPREC = @TIPOPROVV
					SELECT @FLAGOK = 'N'
				END
				ELSE
				BEGIN
					IF ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND (@TIPOPROVV ='I' OR @TIPOPROVV ='C')) 
						OR ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND @TIPOPROVV ='E')
					BEGIN
						SELECT @TIPOPREC = @TIPOPROVV
						SELECT @FLAGOK = 'Y'
						SELECT @FLAGANAGTIT ='2'
					END
					ELSE
	    				BEGIN
	     					SELECT @TIPOPREC = @TIPOPROVV
	     					SELECT @FLAGOK = 'N'
	    				END
	   			END
	  		END
			--******************************************************************
			--FINE CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			--******************************************************************
			-- SE HO TROVATO UN TITOLARE VALIDO INIZIALIZZO TUTTE LE VARIABILI RELATIVE A QUESTO TITOLARE
			IF @FLAGOK = 'Y'
			BEGIN
				IF (@COGNOME = @COGNOMETIT AND @NOME = @NOMETIT)
				BEGIN
					SELECT @FLGANAG = @FLAGANAGTIT
					SELECT @FKDATAINS= @DATAINSTIT
					SELECT @FKORAINS = @ORAINSTIT
					SELECT @COGNOME = @COGNOMETIT
					SELECT @NOME = @NOMETIT
					SELECT @TITTROVATO = 'Y'
				END
			END
		END --END IF @TITTROVATO = 'N'
		FETCH NEXT FROM CUR_R1
		INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @TIPOPROVV
	END

	CLOSE CUR_R1
	DEALLOCATE CUR_R1
GO
