/****** Object:  StoredProcedure [dbo].[INSERT_LSRPRO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[INSERT_LSRPRO]
 
	@RICEVITORIA 	CHAR(6),
	@DATAINS		CHAR(8),
	@ORAINS		CHAR(8),
	@TIPOPROVV		CHAR(1),
	@DATAPROVV		CHAR(8),
	@NUMPROVV		CHAR(14),
	@CAUSALE		CHAR(40),
	@FIRMA		CHAR(17),
	@EMANATO		CHAR(25),
	@DATADECOR		CHAR(8),
	@OGGI			CHAR(8),
	@IDTAB		CHAR(10),
	@OPZIONE		CHAR(1),
	@OLDPROVV		CHAR(1),
	@OLDDATAPROVV	CHAR(8),
	@OLDPROGPROVV	CHAR(14),
	@NUMERR 		VARCHAR(4) OUTPUT,
	@MSGERR 		VARCHAR(50) OUTPUT

AS

DECLARE	

@TASSA		CHAR(9),
@ANNO		CHAR(4),
@MASSIMALE		CHAR(9),
@CODTAB		CHAR(10)


DECLARE CUR_PRO CURSOR FOR

SELECT LSRPRO_TASSA,LSRPRO_ANNO,LSRPRO_MASSIMALE,LSRPRO_COD_TAB
FROM LSRPRO
WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_FLAG_VALIDITA = 'Y'
AND LSRPRO_DECOR_DAL = 
	(SELECT MAX (LSRPRO_DECOR_DAL) 
	FROM LSRPRO
	WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRPRO_FLAG_VALIDITA = 'Y'
	AND LSRPRO_DECOR_DAL <= @OGGI)

OPEN CUR_PRO
FETCH NEXT FROM CUR_PRO INTO @TASSA,@ANNO,@MASSIMALE,@CODTAB
CLOSE CUR_PRO
DEALLOCATE CUR_PRO

BEGIN TRANSACTION 

IF @OPZIONE <> 'F'
BEGIN
--	BEGIN TRANSACTION

	INSERT INTO LSRPRO VALUES
	(@RICEVITORIA,@TIPOPROVV,@DATAINS,@ORAINS,
	@DATAPROVV,@NUMPROVV,@CAUSALE,@FIRMA,
	@EMANATO,@DATADECOR,'00000000',@TASSA,@ANNO,@MASSIMALE,@CODTAB,
	'','Y','00000000')

	IF @@ERROR <> 0 
	BEGIN
		 
                           SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRPRO'
                           ROLLBACK TRANSACTION
                           RETURN 0
                          
             END
/*	ELSE
	BEGIN
		SELECT @NUMERR = '0000'
		SELECT @MSGERR = @NUMERR
		COMMIT TRANSACTION
	END
*/
END
ELSE
BEGIN
--	BEGIN TRANSACTION

	UPDATE LSRPRO SET LSRPRO_FLAG_VALIDITA = 'N'
	WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRPRO_KEY_TIPO_REC = @OLDPROVV
	AND LSRPRO_KEY_DATA_PROVV = @OLDDATAPROVV
	AND LSRPRO_KEY_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRPRO'
		ROLLBACK TRANSACTION
                           ROLLBACK TRANSACTION
		RETURN
	END
	ELSE
	BEGIN
		INSERT INTO LSRPRO VALUES
		(@RICEVITORIA,@TIPOPROVV,@DATAINS,@ORAINS,
		@DATAPROVV,@NUMPROVV,@CAUSALE,
		@FIRMA,@EMANATO,@DATADECOR,
		'00000000',@TASSA,@ANNO,@MASSIMALE,@CODTAB,
		'','Y','00000000')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRPRO'
			ROLLBACK TRANSACTION
			RETURN
		END
/*		ELSE
		BEGIN
			SELECT @NUMERR = '0000'
			SELECT @MSGERR = @NUMERR
			COMMIT TRANSACTION
		END
*/
	END
END

SELECT @NUMERR = '0000'
SELECT @MSGERR = @NUMERR
COMMIT TRANSACTION

RETURN
GO
