/****** Object:  StoredProcedure [dbo].[INSERT_LSRPRO_I_CONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[INSERT_LSRPRO_I_CONI]
 
	@RICEVITORIA 	CHAR(6),
	@CODCONI	CHAR(6),
	@TIPORIV	CHAR(1),
	@TIPOPROVV	CHAR(1),
	@DATAPROVV	CHAR(8),
	@NUMPROVV	CHAR(14),
	@CAUSALE	CHAR(40),
	@FIRMA		CHAR(17),
	@EMANATO	CHAR(25),
	@DATADECOR	CHAR(8),


	@COGNOME	CHAR(24),
	@NOME		CHAR(20),
	@DENOMINAZIONE		CHAR(50),
	@DATANASC	CHAR(8),
	@LUOGONASC	CHAR(24),
	@PROVNASC	CHAR(2),
	@CODFISC	CHAR(16),
	@SESSO		CHAR(1),
	@INDIRIZZO	CHAR(40),
	@CAP		CHAR(5),
	@COMUNE		CHAR(24),
	@PROVINCIA	CHAR(2),
	@PARTITAIVA	CHAR(11),
	@TELCASA	CHAR(12),
	@TELCELL	CHAR(12),

	@NUMERR 	VARCHAR(4) OUTPUT,

	@MSGERR 	VARCHAR(200) OUTPUT

AS

DECLARE
@OGGI			CHAR(8),
@DOMANI			CHAR(8),
@DATADIS		CHAR(8),
@DATAINS		CHAR(8),
@ORAINS			CHAR(8),
@DATAINSLET		CHAR(8),
@ORAINSLET		CHAR(8),
@DATAAPPO		CHAR(8),
@APPORICEV		CHAR(6),
@FK_DATA_INS_TIT	CHAR(8),
@FK_ORA_INS_TIT		CHAR(8),
@FKPRO			CHAR(16),
@DATALET		CHAR(8),
@DATA_INS_LET		CHAR(8),
@STATOOGGI		CHAR(1)

SELECT @OGGI = CONVERT(CHAR(8),GETDATE(),112)
SELECT @DOMANI = CONVERT(CHAR(8),GETDATE() + 1,112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)  + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2) 
SELECT @DATAAPPO = NULL

/*
-- STEP DA ESEGUIRE
1) VERIFICA CHE NON ESISTONO ALTRI PROVVEDIMENTI CON STESSA DATA E NUMERO PROVVEDIMENTO
2) VERIFICA CHE PER IL TITOLARE ATTUALE ESISTE UN PROVEVDIMENTO DI TIPO F CON DATA DECORRENZA INFERIORE
3) VERIFICA CHE NON ESISTONO ALTRI PROVVEDIMENTI CON STESSA DATA VALIDITA'
4) VERIFICA CHE SE LA DECORRENZA è NEL FUTURO NON VI SIANO ALTRI PROVVEDIMENTI CON DATA DECORRENZA NEL FUTURO
5) INSERIMENTO RECORD SU LSRTIT_CONI
6) INSERIMENTO RECORD SU LSRPRO_CONI
*/



--*************************************************************************
--           STEP 1
--*************************************************************************
SELECT @APPORICEV = NULL
SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
FROM LSRPRO_CONI 
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_CONI_FLAG_VALIDITA = 'Y'
AND LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
AND lsrpro_coni_data_provv = @NUMPROVV
AND lsrpro_coni_prog_provv = @DATAPROVV

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO CON STESSA DATA  E NUMERO'
	RETURN 
END


--*************************************************************************
--           STEP 2
--*************************************************************************
SELECT @DATAAPPO = NULL
SELECT @DATAAPPO = LSRPRO_CONI_DECOR_DAL
FROM LSRTIT_CONI, LSRPRO_CONI
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRTIT_CONI_KEY_ID_RICEV = LSRPRO_CONI_KEY_ID_RICEV
	AND LSRPRO_CONI_FK_DATA_INS_TIT = LSRTIT_CONI_KEY_DATA_INS
	AND LSRPRO_CONI_FK_ORA_INS_TIT = LSRTIT_CONI_KEY_ORA_INS 
AND (lsrtit_coni_data_validita + lsrtit_coni_ora_validita) =
	(select max(lsrtit_coni_data_validita + lsrtit_coni_ora_validita)
	from lsrtit_coni
	where lsrtit_coni_key_id_ricev = @RICEVITORIA
	and  lsrtit_coni_data_validita <= @OGGI
	and  lsrtit_coni_flag_validita = 'Y')
AND LSRTIT_CONI_FLAG_VALIDITA = 'Y'
AND LSRPRO_CONI_TIPO_PROVV = 'F'
and lsrpro_coni_flag_validita = 'Y'

IF (@DATAAPPO <>'' OR @DATAAPPO IS NOT NULL)
BEGIN
	IF @DATAAPPO >= @DATADECOR
	BEGIN
                SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - LA DATA DECORRENZA DEVE ESSERE SUPERIORE A ' + @DATAAPPO
                RETURN 
	END
END


IF (@DATAAPPO ='' OR @DATAAPPO IS NULL)
BEGIN
                SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - MANCA IL PROVVEDIMENTO DI CESSAZIONE DEL TITOLARE PRECEDENTE '
                RETURN 

END



--*************************************************************************
--           STEP 3
--*************************************************************************
SELECT @APPORICEV = NULL
SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
FROM LSRPRO_CONI
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_CONI_FLAG_VALIDITA = 'Y'
AND LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
AND LSRPRO_CONI_DECOR_DAL = @DATADECOR

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO CON STESSA DATA DECORRENZA'
	RETURN 
END




--*************************************************************************
--           STEP 4
--*************************************************************************

IF (@DATADECOR > @OGGI)
BEGIN
	SELECT @APPORICEV = NULL
	SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
	FROM LSRPRO_CONI
	WHERE lsrpro_CONI_key_id_ricev = @RICEVITORIA
	 	and LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
	 	and lsrpro_CONI_flag_validita='Y' 
		and lsrpro_CONI_decor_dal >@OGGI
	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO CON DATA DECORRENZA NEL FUTURO'
		RETURN 
	END
END

BEGIN TRANSACTION

--*************************************************************************
--           STEP 5
--*************************************************************************


INSERT INTO lsrtit_coni VALUES(
	@RICEVITORIA,
	@OGGI,
	@ORAINS,
	@TIPORIV,
	@CODCONI,
	@COGNOME,
	@NOME, 
	@DENOMINAZIONE, 
	@DATANASC,
	@LUOGONASC,
	@PROVNASC,
	@CODFISC,
	@SESSO,
	@INDIRIZZO,
	@CAP,
	@COMUNE,
	@PROVINCIA,
	@PARTITAIVA,
	@TELCASA,
	@TELCELL,
	@FIRMA,
	@DATAPROVV, 
	@NUMPROVV, 
	@TIPOPROVV, 
	@DATADECOR , 
	'00000000', 
	'Y', 
	'1', 
	'00000000')

IF @@ERROR <> 0 
BEGIN
	 
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE ACQUISIZIONE TITOLARE'
	ROLLBACK TRANSACTION
	RETURN 0
                  
END


--*************************************************************************
--           STEP 6
--*************************************************************************
INSERT INTO LSRPRO_CONI VALUES (
	@RICEVITORIA,
	@OGGI,
	@ORAINS,
	@TIPOPROVV,
	@DATAPROVV,
	@NUMPROVV,
	@DATADECOR,
	'',
	@CAUSALE,
	@FIRMA,
	@EMANATO,
	@OGGI,
	@ORAINS,
	'Y',
	'00000000'
	)

IF @@ERROR <> 0 
BEGIN
	 
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE ACQUISIZIONE PROVVEDIMENTO'
	ROLLBACK TRANSACTION
	RETURN 0
                  
END


SELECT @NUMERR = '0000'
SELECT @MSGERR = @NUMERR
SELECT @MSGERR = @NUMERR + ' - ' + 'ELABORAZIONE TERMINATA CORRETTAMENTE'
COMMIT TRANSACTION

RETURN
GO
