/****** Object:  StoredProcedure [dbo].[IC_AGGIORNA_FT_VOS_CHIUSURE]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[IC_AGGIORNA_FT_VOS_CHIUSURE]

@RC 		INT	OUTPUT

AS


DECLARE	

@OGGI			CHAR(8),
@IERI			CHAR(8),
@ORA			CHAR(8),
@MSG			VARCHAR(200),
@FILELOG		VARCHAR(25),

@SCRIVIFILE		VARCHAR(15),
@SCRIVILOG		VARCHAR(15),
@COPIAFILE		VARCHAR(15),
@ESISTEFILE		VARCHAR(15),
@CANCELLAFILE	VARCHAR(15),
@NOMEJOB		VARCHAR(15),
@PATHID		INT


SELECT @OGGI = CONVERT (CHAR(8), GETDATE(),112)

SELECT @IERI = CONVERT (CHAR(8), GETDATE() - 1,112)

SELECT @ORA = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @SCRIVILOG = 'MSDB..UT_AA004'
SELECT @COPIAFILE = 'MSDB..UT_AA007'
SELECT @CANCELLAFILE = 'MSDB..UT_AA009'
SELECT @SCRIVIFILE = 'MSDB..UT_AA010'
SELECT @ESISTEFILE = 'MSDB..UT_AA011'

SELECT @NOMEJOB = 'AAEG012004UC'
SELECT @PATHID = 83


BEGIN TRANSACTION

	UPDATE LSRCHI_FT_VOS
	SET LSRCHI_FT_VOS = CONVERT(CHAR,CONVERT(DATETIME,LSRCHI_DATA_INS,112)+ 1,112)
	WHERE LSRCHI_DATA_INS < CONVERT(CHAR,GETDATE(),112)
	AND LSRCHI_FT_VOS = '00000000'
	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSG = 'ERRORE IN AGGIORNAMENTO TABELLA LSRCHI_FT_VOS ' + @ORA
		EXEC  @SCRIVILOG 9999, @NOMEJOB, @MSG, 0
		RAISERROR(@MSG, 16, 1)
		SELECT @RC = @@ERROR
		RETURN
	END
	ELSE
	BEGIN
		SELECT @MSG = 'AGGIORNAMENTO TABELLA LSRCHI_FT_VOS EFFETTUATO CORRETTAMENTE ' + @ORA
		EXEC  @SCRIVILOG 9999, @NOMEJOB, @MSG, 0
		COMMIT TRANSACTION
	END

SELECT @RC = 0
GO
