/****** Object:  StoredProcedure [dbo].[GEV_TITOLARE_PROVVEDIMENTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_TITOLARE_PROVVEDIMENTO]
	@RICEV 		CHAR(6),
	@DATARIC	     	CHAR(8),
	@COGNOME		VARCHAR(24) OUTPUT,
	@NOME		VARCHAR(20) OUTPUT,
	@TIPOPROVV		CHAR(1) OUTPUT

AS

SELECT @COGNOME = NULL
SELECT @NOME = NULL

SELECT @COGNOME = LSRTIT_COGNOME, @NOME = LSRTIT_NOME, @TIPOPROVV = LSRTIT_TIPO_PROVV
FROM LSRTIT
WHERE 
LSRTIT_KEY_ID_RICEV = @RICEV AND
LSRTIT_FLAG_VALIDITA = 'Y' AND
LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA = 
(
	SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV = @RICEV
	AND LSRTIT_DATA_VALIDITA <= @DATARIC
	AND LSRTIT_FLAG_VALIDITA = 'Y'
)
GO
