/****** Object:  StoredProcedure [dbo].[IC_FT_VOS_CHIUSURE]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[IC_FT_VOS_CHIUSURE]

		@RC 		INT	OUTPUT

AS


DECLARE	

@LTMS		CHAR(6),
@LTMDS		CHAR(6),
@DATAI		CHAR(8),
@DATAF		CHAR(8),
@DATAINS		CHAR(8),
@FIRMA		CHAR(17),
@CAUSALE		CHAR(2),
@ENTE		CHAR(2),
@PROV		CHAR(2),
@PROG		CHAR(1),
@ORAINS		CHAR(8),
@TIPOAGG		CHAR(1),
@MILLENNIO		CHAR(1),
@OLDLTMS		CHAR(6),
@OLDLTMDS		CHAR(6),
@OLDDATAI		CHAR(8),
@FTVOS		CHAR(8),
@OGGI			CHAR(8),
@IERI			CHAR(8),
@ORA			CHAR(8),
@MSG			VARCHAR(200),
@FILEFT		VARCHAR(25),
@FILEPLT		VARCHAR(25),
@FILELOG		VARCHAR(25),
@FILECOPIA		VARCHAR(25),
@NREC		INT,

@SCRIVIFILE		VARCHAR(15),
@SCRIVILOG		VARCHAR(15),
@COPIAFILE		VARCHAR(15),
@ESISTEFILE		VARCHAR(15),
@CANCELLAFILE	VARCHAR(15),
@NOMEJOB		VARCHAR(15),
@PATHID		INT,
@RESULT		INT



SELECT @OGGI = CONVERT (CHAR(8), GETDATE(),112)

SELECT @IERI = CONVERT (CHAR(8), GETDATE() - 1,112)

SELECT @ORA = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @SCRIVILOG = 'MSDB..UT_AA004'
SELECT @COPIAFILE = 'MSDB..UT_AA007'
SELECT @CANCELLAFILE = 'MSDB..UT_AA009'
SELECT @SCRIVIFILE = 'MSDB..UT_AA010'
SELECT @ESISTEFILE = 'MSDB..UT_AA011'

SELECT @NOMEJOB = 'AAEG012004UC'
SELECT @PATHID = 83
SELECT @FILEFT = 'IC_CHIUSURE.txt'
SELECT @FILELOG = 'IC_CHIUSURE_LOG.txt'
SELECT @FILEPLT = 'IC_CHIUSURE.plt'
SELECT @FILECOPIA = 'IC_CHIUSURE_' + @OGGI + '.txt'


SELECT @MSG = 'INIZIO TRASFERIMENTO DATI CHIUSURE ' + @OGGI + ' - ' + @ORA


EXEC  @SCRIVILOG 9999, @NOMEJOB, @MSG, 0

EXEC  @SCRIVILOG 9999, @NOMEJOB, '', 0


EXEC @RESULT = @ESISTEFILE @PATHID, @FILEPLT, 9999, @NOMEJOB
IF @RESULT = 0
BEGIN
	SELECT @MSG = 'TROVATO FILE PILOTA - ESECUZIONE S.P. IC_FT_VOS_CHIUSURE INTERROTTA'
	EXEC  @SCRIVILOG 9999, @NOMEJOB, @MSG, 0
	RAISERROR (@MSG, 16, 1)
	SELECT @RC = @@ERROR
--	EXEC  @SCRIVIFILE 9999, @PATHID, @FILELOG, @MSG, @NOMEJOB
	RETURN
END

SELECT @NREC =  COUNT(*)
		FROM LSRCHI_FT_VOS
		WHERE LSRCHI_DATA_INS = @IERI
--		WHERE LSRCHI_DATA_INS = @OGGI
		AND LSRCHI_FT_VOS = '00000000'

SELECT @MSG = 'TROVATI ' + CONVERT(VARCHAR(3),@NREC) + ' RECORD SU LSRCHI_FT_VOS'

EXEC  @SCRIVILOG 9999, @NOMEJOB, @MSG, 0
EXEC  @SCRIVILOG 9999, @NOMEJOB, '', 0

--SCRIVO RECORD DI TESTA
EXEC  @SCRIVIFILE 9999, @PATHID, @FILEFT, 'KKKK', @NOMEJOB

SELECT @MSG = NULL

IF @NREC > 0
BEGIN

	DECLARE CUR_CHI SCROLL CURSOR FOR
	SELECT *
	FROM LSRCHI_FT_VOS
	WHERE LSRCHI_DATA_INS = @IERI
--	WHERE LSRCHI_DATA_INS = @OGGI
	AND LSRCHI_FT_VOS = '00000000'
	ORDER BY LSRCHI_KEY_ID_RICEV, LSRCHI_DATA_INS, LSRCHI_ORA_INS 

	OPEN CUR_CHI
	FETCH NEXT FROM CUR_CHI INTO 
	@LTMS, @LTMDS, @DATAI, @DATAF, @DATAINS, @FIRMA, @CAUSALE,
	@ENTE, @PROV, @PROG, @ORAINS, @TIPOAGG, @MILLENNIO, 
	@OLDLTMS, @OLDLTMDS, @OLDDATAI, @FTVOS

	WHILE @@FETCH_STATUS = 0 
	BEGIN
		SELECT @MSG = @LTMS + @LTMDS + @DATAI + @DATAF + @DATAINS + @FIRMA + 
				@CAUSALE + @ENTE + @PROV + @PROG + @ORAINS + @TIPOAGG + 
				@MILLENNIO + @OLDLTMS + @OLDLTMDS + @OLDDATAI

		EXEC  @SCRIVILOG 9999, @NOMEJOB, @MSG, 0
		EXEC  @SCRIVIFILE 9999, @PATHID, @FILEFT, @MSG, @NOMEJOB
		SELECT @MSG = NULL

		FETCH NEXT FROM CUR_CHI INTO 
		@LTMS, @LTMDS, @DATAI, @DATAF, @DATAINS, @FIRMA, @CAUSALE,
		@ENTE, @PROV, @PROG, @ORAINS, @TIPOAGG, @MILLENNIO, 
		@OLDLTMS, @OLDLTMDS, @OLDDATAI, @FTVOS
	END

	CLOSE CUR_CHI
	DEALLOCATE CUR_CHI
END
ELSE
BEGIN
	EXEC  @SCRIVIFILE 9999, @PATHID, @FILEFT, '', @NOMEJOB
END

EXEC  @COPIAFILE @PATHID, @FILEFT, @PATHID, @FILECOPIA, 9999, @NOMEJOB

EXEC  @SCRIVIFILE 9999, @PATHID, @FILEPLT, '', @NOMEJOB


SELECT @MSG = 'S.P. IC_FT_VOS_CHIUSURE TERMINATA CORRETTAMENTE ' + @OGGI + ' - ' + @ORA

EXEC  @SCRIVILOG 9999, @NOMEJOB, '', 0
EXEC  @SCRIVILOG 9999, @NOMEJOB, @MSG, 0

SELECT @RC = 0
GO
