/****** Object:  StoredProcedure [dbo].[CARICA_PREGRESSO_CONTRATTI_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CARICA_PREGRESSO_CONTRATTI_LIS]

AS
DECLARE
	@PARTITAIVA		CHAR(11),
	@DENOMINAZIONE	CHAR(50),
	@DECODRICEV	CHAR(50),
	@ELENCO		CHAR(20),
	@FIDEJUSSIONE	CHAR(20),
	@CONTRQUADRO	CHAR(2),
	@ASSOCIAZIONE	CHAR(1),

	@COGNOME		CHAR(24),
	@NOME		CHAR(20),
	@RICEV		CHAR(6),
	@APPORICEV		CHAR(6),
	@DATAOGGI   		CHAR(8),
	@ORAOGGI  		CHAR(8),

	@FKDATAINSTIT	CHAR(8),
	@FKORAINSTIT	CHAR(8),

	@TIPOPREC 		CHAR(1),
	@TIPOPROVV		CHAR(1),
	@TITTROVATO 	CHAR(1),
	@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)



DECLARE CUR_PIVA SCROLL CURSOR FOR
SELECT Cod_ltm, Decod, Elenco, PIva, Fid, Contr
FROM FIT_FILE_ALLINEAMENTO
WHERE PIva IS NOT NULL OR Contr IS NOT NULL
--WHERE (Partita_IVA IS NOT NULL AND  Partita_IVA <>'')

OPEN CUR_PIVA
FETCH NEXT FROM CUR_PIVA
INTO @RICEV, @DENOMINAZIONE, @ELENCO, @PARTITAIVA, @FIDEJUSSIONE, @CONTRQUADRO
WHILE @@FETCH_STATUS = 0 
BEGIN
	IF @CONTRQUADRO IS NULL
	BEGIN
		SELECT @CONTRQUADRO = ''
	END

	-- NEL CASO IN CUI ELENCO E'<> 10000, ALLORA L'ASSOCIAZIONE E' FIT
	IF @ELENCO <> '10000'
	BEGIN
		SELECT @ASSOCIAZIONE = '1'
	END
	ELSE
	BEGIN
		SELECT @ASSOCIAZIONE = ''
	END 

	PRINT 'ELABORAZIONE RICEVITORIA ' + @RICEV
	-- VERIFICO CHE LA DENOMINAZIONE SIA VALIDA
 	SELECT @DECODRICEV = ''

	SELECT @DECODRICEV = LSRRIC_DECOD_RICEV,
		@COGNOME = LSRTIT_COGNOME, 
		@NOME = LSRTIT_NOME, 
		@FKDATAINSTIT = LSRTIT_KEY_DATA_INS, 
		@FKORAINSTIT = LSRTIT_KEY_ORA_INS
	FROM LSRRIC JOIN LSRTIT
	ON LSRRIC_KEY_ID_RICEV = LSRTIT_KEY_ID_RICEV
	WHERE LSRRIC_KEY_ID_RICEV = @RICEV
		AND LSRRIC_DECOD_RICEV = @DENOMINAZIONE 
		AND LSRRIC_DATA_VALIDITA = 
			(SELECT MAX(LSRRIC_DATA_VALIDITA)
			FROM LSRRIC
			WHERE LSRRIC_KEY_ID_RICEV =@RICEV AND
				LSRRIC_DATA_VALIDITA <= @DATAOGGI AND
				 LSRRIC_FLAG_VALIDITA = 'Y' 
			)
		AND LSRTIT_DATA_VALIDITA = 
			(SELECT MAX(LSRTIT_DATA_VALIDITA)
			FROM LSRTIT
			WHERE LSRTIT_KEY_ID_RICEV =@RICEV AND
				LSRTIT_DATA_VALIDITA <= @DATAOGGI AND
				 LSRTIT_FLAG_VALIDITA = 'Y' 
			)
		AND  LSRRIC_FLAG_VALIDITA = 'Y' 
		AND  LSRTIT_FLAG_VALIDITA = 'Y' 


	-- SE HO TROVATO CHE LA DENOMINAZIONE è VALIDA
	-- ALLORA INSERISCO IL RECORD SU LSRCON_LIS
	IF @DECODRICEV <> ''
	BEGIN
		--*************************************************************************
		--           IL RECORD VIENE INSERITO SU LSRCON_LIS
		--*************************************************************************
		INSERT INTO LSRCON_LIS VALUES (
			@RICEV, 		
			@DATAOGGI,
			@ORAOGGI,
			'',			
			'00000000',		
			'00000000',	
			@CONTRQUADRO,	
			@ASSOCIAZIONE,	
			'C',	
			@PARTITAIVA,
			@COGNOME,	
			@NOME	,	
			'',	
			'1',	
			@FKDATAINSTIT,	
			@FKORAINSTIT,	
			'LIS_USER'	)

		IF @@ERROR <> 0 
		BEGIN
			PRINT  @RICEV +' ERRORE INSERIMENTO CONTRATTO - CONTRATTO NON ACQUISITO'
		END
		ELSE
		BEGIN
			PRINT  @RICEV +' CONTRATTO ACQUISITO CORRETTAMENTE'
		END
	END

	FETCH NEXT FROM CUR_PIVA
	INTO   @RICEV, @DENOMINAZIONE, @ELENCO, @PARTITAIVA, @FIDEJUSSIONE, @CONTRQUADRO
END
CLOSE CUR_PIVA
DEALLOCATE CUR_PIVA
GO
