/****** Object:  StoredProcedure [dbo].[CAMBIOTIT]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CAMBIOTIT] AS

DECLARE

@RICEVPRO		VARCHAR(6),
@PROVRICEV		VARCHAR(2),
@DATADECOR		VARCHAR(8),
@DATAPROVV		VARCHAR(8),
@CAUSALE		VARCHAR(50),
@PROVV		VARCHAR(20),
@FIRMA		VARCHAR(25),
@NOME		VARCHAR(35),
@COGNOME		VARCHAR(35),
@MSG			VARCHAR(200)

DELETE FROM TITPALERMO

DECLARE CURTIT CURSOR FOR
SELECT LSRPRO_KEY_ID_RICEV, LSRPRO_DECOR_DAL, 
LSRPRO_KEY_PROG_PROVV, LSRPRO_KEY_DATA_PROVV,
LSRPRO_CAUSALE, LSRPRO_FIRMA FROM LSRPRO
WHERE LSRPRO_KEY_ID_RICEV LIKE ('PA%') AND
LSRPRO_KEY_TIPO_REC IN ('I') 
AND SUBSTRING (LSRPRO_DECOR_DAL,1,4) IN ('2000','2001')
AND LSRPRO_FLAG_VALIDITA = 'Y'

OPEN CURTIT
FETCH NEXT FROM CURTIT INTO @RICEVPRO, @DATADECOR, @PROVV, @DATAPROVV, @CAUSALE, @FIRMA

WHILE @@FETCH_STATUS = 0
BEGIN

	SELECT @PROVRICEV = NULL
	SELECT @PROVRICEV = LSRRIC_PROV_RICEV
	FROM LSRRIC WHERE LSRRIC_KEY_ID_RICEV = @RICEVPRO

	IF @PROVRICEV = 'PA'
	BEGIN

		SELECT @NOME = LSRTIT_NOME,
			@COGNOME = LSRTIT_COGNOME
		FROM LSRTIT
		WHERE LSRTIT_KEY_ID_RICEV = @RICEVPRO
		AND LSRTIT_DATA_VALIDITA = @DATADECOR
		AND LSRTIT_FLAG_VALIDITA = 'Y'

		INSERT INTO TITPALERMO VALUES 
		(@RICEVPRO, @COGNOME, @NOME, @DATADECOR, @PROVV, @DATAPROVV, @CAUSALE, @FIRMA)

	END

	SELECT @NOME = NULL
	SELECT @COGNOME = NULL
	SELECT @CAUSALE = NULL
	SELECT @PROVV = NULL
	SELECT @DATAPROVV = NULL
	SELECT @RICEVPRO = NULL

	FETCH NEXT FROM CURTIT INTO @RICEVPRO, @DATADECOR, @PROVV, @DATAPROVV, @CAUSALE, @FIRMA
END

CLOSE CURTIT
DEALLOCATE CURTIT
GO
