/****** Object:  StoredProcedure [dbo].[CALCOLA_ADDEBITO_CANONE_BOLLO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[CALCOLA_ADDEBITO_CANONE_BOLLO] 
	@RICEVITORIA 	CHAR(6),
	@FLAGCANONE	CHAR(1) OUTPUT,
	@NUMERR 		VARCHAR(4) OUTPUT,
	@MSGERR 		VARCHAR(50) OUTPUT
AS

DECLARE 
	@STATOBOLLO		CHAR(1),
	@TIPOPROVV 		CHAR(1), 
	@DATAPROVV		CHAR(8),
	@PROGPROVV		CHAR(14),
	@DECORPROVV		CHAR(8),
	@DATAOGGI		CHAR(8),
	@ANNOCORRENTE 		CHAR(4), 
	@DATAULTIMOCANONE	CHAR(8),
	@ANNOULTIMOCANONE	CHAR(4)

-- IN BASE ALLA CAUSALE DI DISATTIVAZIONE:
-- 1) CT: 	SE DATA DECORRENZA CT > DATA PAGAMENTO ULTIMO CANONE --> CANONE NO
--		SE DATA DECORRENZA CT < DATA PAGAMENTO ULTIMO CANONE --> CANONE SI
-- 2) ALTRO:	DATA PAGAMENTO ULTIMO CANONE > ANNO IN CORSO--> CANONE NO
--		DATA PAGAMENTO ULTIMO CANONE < ANNO IN CORSO--> CANONE SI

SELECT @FLAGCANONE = 'Y'
SELECT @ANNOCORRENTE = SUBSTRING(CONVERT (VARCHAR(10), GETDATE(),112),1,4)
SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)

--PRENDO LO STATO ATTUALE DEL BOLLO
SELECT @STATOBOLLO = LSRSER_BOLLO_STATO, 
	@TIPOPROVV = LSRSER_BOLLO_TIPO_PROVV,
	@DATAPROVV = LSRSER_BOLLO_DATA_PROVV,
	@PROGPROVV = LSRSER_BOLLO_PROG_PROVV
FROM LSRSER_BOLLO 
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_BOLLO_DATA_DECOR = 
		(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) 
		FROM LSRSER_BOLLO 
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
			AND  LSRSER_BOLLO_DATA_DECOR <= @DATAOGGI
			AND  LSRSER_BOLLO_FLAG_VALIDITA = 'Y')
	AND  LSRSER_BOLLO_FLAG_VALIDITA = 'Y'

--SE LO STATO È 2 (DISATTIVO) VADO AVANTI

IF @STATOBOLLO = '2'
BEGIN

	-- PRENDO LA DATA DI PAGAMENTO DELL'ULTIMO CANONE
	SELECT @DATAULTIMOCANONE = ''
	SELECT @DATAULTIMOCANONE = MAX(LNH01A_DATA_CONT_FINE)
 	FROM CONDIVISO.DBO.LNH01A
	WHERE  LNH01A_KEY_ID_RICEV = @RICEVITORIA 
		AND CONVERT(FLOAT,LNH01A_CANONE_ANNUALE)<>0 
		AND LNH01A_FLAG_EC_DIRITTI='1'
	-- SE NON CI SONO DATI SUI CANONI ADDEBITATI
	-- SOLLEVO L'ERRORE
	IF (@DATAULTIMOCANONE IS NULL) OR (LTRIM(RTRIM(@DATAULTIMOCANONE)) = '')
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - DATI CANONE NON PRESENTI'
		RETURN	
	END
	-- ... ALTRIMENTI VADO AVANTI
	ELSE
	BEGIN
		-- LO STATO È DOVUTO A UN PROVVEDIMENTO DI TIPO I	
		IF @TIPOPROVV = 'I'
		BEGIN
			-- PRENDO LA DATA DECORRENZA DEL CAMBIO TITOLARE
			SELECT @DECORPROVV = LSRPRO_DECOR_DAL
			FROM LSRPRO
			WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
				AND LSRPRO_KEY_TIPO_REC = @TIPOPROVV
				AND LSRPRO_KEY_DATA_PROVV = @DATAPROVV
				AND LSRPRO_KEY_PROG_PROVV = @PROGPROVV
			-- SE DATA DECORRENZA CT > DATA PAGAMENTO ULTIMO CANONE 
			IF @DECORPROVV >= @DATAULTIMOCANONE
			BEGIN 
				--> CANONE NO
				SELECT @FLAGCANONE = 'N'
			END
			-- ... ALTRIMENTI
			ELSE
			BEGIN
				--> CANONE SI
				SELECT @FLAGCANONE = 'Y'
			END
	
		END
		-- LO STATO NON È DOVUTO A UN PROVVEDIMENTO DI TIPO I
		ELSE
		BEGIN
			SELECT @ANNOULTIMOCANONE = SUBSTRING(@DATAULTIMOCANONE,1,4)
			--DATA PAGAMENTO ULTIMO CANONE > ANNO IN CORSO
			IF @ANNOULTIMOCANONE >= @ANNOCORRENTE
			BEGIN
				--> CANONE NO
				SELECT @FLAGCANONE = 'N'
			END
			ELSE
			BEGIN
				--> CANONE SI
				SELECT @FLAGCANONE = 'Y'
			END
		
		END
	END
END
-- ... ALTRIMENTI (NON DISATTIVO) SEGNALO ERRORE
ELSE
BEGIN 
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - RICEVITORIA NON DISATTIVA'
	RETURN

END

SELECT @NUMERR = '0000'
SELECT @MSGERR = @NUMERR
GO
