/****** Object:  StoredProcedure [dbo].[CC_DATI_LETTERA_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CC_DATI_LETTERA_GS]

@CODLTM		VARCHAR(7),
@GS			VARCHAR(6),
@DATASTATO		CHAR(8),
@TABELLA		VARCHAR(20) OUTPUT,
@FKTAB		VARCHAR(16) OUTPUT,
@TIPOMOV		CHAR(1) OUTPUT,
@NOTE		VARCHAR(100) OUTPUT

 AS

SELECT @TABELLA = NULL
SELECT @FKTAB = NULL
SELECT @TIPOMOV = NULL


IF LEN(@GS) = 2
BEGIN
	SELECT @TABELLA = LSRLET_NOME_TAB_DOCUMENTO, @FKTAB = LSRLET_FK_TAB_DOCUMENTO, 
	@TIPOMOV = LSRLET_TIPO_MOVIMENTAZIONE, @NOTE = LSRLET_NOTE
	FROM LSRLET 
	WHERE 
	LSRLET_KEY_ID_RICEV = @CODLTM AND
	LSRLET_DATA_LETTERA <> '00000000' AND
	LSRLET_COD_SERVIZIO = @GS AND
	LSRLET_DECOR_DAL = @DATASTATO
END
ELSE
BEGIN
	SELECT @TABELLA = LSRLET_LIS_NOME_TAB_DOCUMENTO, @FKTAB = LSRLET_LIS_FK_TAB_DOCUMENTO, 
	@TIPOMOV = LSRLET_LIS_TIPO_MOVIMENTAZIONE, @NOTE = LSRLET_LIS_NOTE
	FROM LSRLET_LIS
	WHERE 
	LSRLET_LIS_KEY_ID_RICEV = @CODLTM AND
	LSRLET_LIS_DECOR_DAL <> '00000000' AND
	LSRLET_LIS_KEY_CATEGORIA + LSRLET_LIS_KEY_SERVIZIO + LSRLET_LIS_KEY_ATTIVITA = @GS AND
	LSRLET_LIS_DECOR_DAL = @DATASTATO

END
GO
