/****** Object:  StoredProcedure [dbo].[CC_STATI_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE    PROCEDURE [dbo].[CC_STATI_GS] 

@CODLTM		VARCHAR(7),
@GS			VARCHAR(6),
@DATASTATO1	CHAR(8) 	OUTPUT,
@STATO1		VARCHAR(15) 	OUTPUT,
@DATASTATO2	CHAR(8) 	OUTPUT,
@STATO2		VARCHAR(15) 	OUTPUT,
@DATAPROVV		CHAR(8) 	OUTPUT,
@TIPOPROVV		CHAR(1) 	OUTPUT,
@NUMPROVV		VARCHAR(15) 	OUTPUT,
@CANONE		CHAR(1) 	OUTPUT

AS

DECLARE

@TABELLA 		VARCHAR(20)

SELECT @DATASTATO1 = NULL
SELECT @STATO1 = NULL

SELECT @DATASTATO2 = NULL
SELECT @STATO2 = NULL

SELECT @DATAPROVV = NULL
SELECT @TIPOPROVV = NULL
SELECT @NUMPROVV = NULL

IF @GS = '05'
BEGIN
	SELECT @DATASTATO1 = LSRSER_BOLLO_DATA_DECOR, @STATO1 = LSRSER_BOLLO_STATO,
	@TIPOPROVV = LSRSER_BOLLO_TIPO_PROVV, @DATAPROVV = LSRSER_BOLLO_DATA_PROVV, 
	@NUMPROVV = LSRSER_BOLLO_PROG_PROVV, @CANONE = LSRSER_BOLLO_CANONE
	FROM LSRSER_BOLLO
	WHERE
	LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM AND
	LSRSER_BOLLO_FLAG_VALIDITA = 'Y' AND
	LSRSER_BOLLO_FT_VOS <> '00000000' AND
	LSRSER_BOLLO_DATA_DECOR =
	(
		SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
		FROM LSRSER_BOLLO
		WHERE
		LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM AND
		LSRSER_BOLLO_FLAG_VALIDITA = 'Y' AND
		LSRSER_BOLLO_FT_VOS <> '00000000' AND
		LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
	)
	
	SELECT @DATASTATO2 = LSRSER_BOLLO_DATA_DECOR, @STATO2 = LSRSER_BOLLO_STATO
	FROM LSRSER_BOLLO
	WHERE
	LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM AND
	LSRSER_BOLLO_FLAG_VALIDITA = 'Y' AND
	LSRSER_BOLLO_FT_VOS <> '00000000' AND
	LSRSER_BOLLO_DATA_DECOR =
	(
		SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
		FROM LSRSER_BOLLO
		WHERE
		LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM AND
		LSRSER_BOLLO_FLAG_VALIDITA = 'Y' AND
		LSRSER_BOLLO_FT_VOS <> '00000000' AND
		LSRSER_BOLLO_DATA_DECOR < @DATASTATO1
	)
	
	IF @STATO2 = '0'
	BEGIN
		SELECT @DATASTATO2 = NULL
	END
END

IF @GS = '08'
BEGIN
	SELECT @DATASTATO1 = LSRSER_TRIS_DATA_DECOR, @STATO1 = LSRSER_TRIS_STATO,
	@TIPOPROVV = LSRSER_TRIS_TIPO_PROVV, @DATAPROVV = LSRSER_TRIS_DATA_PROVV, 
	@NUMPROVV = LSRSER_TRIS_PROG_PROVV
	FROM LSRSER_TRIS
	WHERE
	LSRSER_TRIS_KEY_ID_RICEV = @CODLTM AND
	LSRSER_TRIS_FLAG_VALIDITA = 'Y' AND
	LSRSER_TRIS_FT_VOS <> '00000000' AND
	LSRSER_TRIS_DATA_DECOR =
	(
		SELECT MAX(LSRSER_TRIS_DATA_DECOR)
		FROM LSRSER_TRIS
		WHERE
		LSRSER_TRIS_KEY_ID_RICEV = @CODLTM AND
		LSRSER_TRIS_FLAG_VALIDITA = 'Y' AND
		LSRSER_TRIS_FT_VOS <> '00000000' AND
		LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
	)
	
	SELECT @DATASTATO2 = LSRSER_TRIS_DATA_DECOR, @STATO2 = LSRSER_TRIS_STATO
	FROM LSRSER_TRIS
	WHERE
	LSRSER_TRIS_KEY_ID_RICEV = @CODLTM AND
	LSRSER_TRIS_FLAG_VALIDITA = 'Y' AND
	LSRSER_TRIS_FT_VOS <> '00000000' AND
	LSRSER_TRIS_DATA_DECOR =
	(
		SELECT MAX(LSRSER_TRIS_DATA_DECOR)
		FROM LSRSER_TRIS
		WHERE
		LSRSER_TRIS_KEY_ID_RICEV = @CODLTM AND
		LSRSER_TRIS_FLAG_VALIDITA = 'Y' AND
		LSRSER_TRIS_FT_VOS <> '00000000' AND
		LSRSER_TRIS_DATA_DECOR < @DATASTATO1
	)
END

IF @GS = '09'
BEGIN
	SELECT @DATASTATO1 = LSRSER_GEV_DATA_DECOR, @STATO1 = LSRSER_GEV_STATO,
	@TIPOPROVV = LSRSER_GEV_TIPO_PROVV, @DATAPROVV = LSRSER_GEV_DATA_PROVV, 
	@NUMPROVV = LSRSER_GEV_PROG_PROVV
	FROM LSRSER_GEV
	WHERE
	LSRSER_GEV_KEY_ID_RICEV = @CODLTM AND
	LSRSER_GEV_FLAG_VALIDITA = 'Y' AND
	LSRSER_GEV_FT_VOS <> '00000000' AND
	LSRSER_GEV_DATA_DECOR =
	(
		SELECT MAX(LSRSER_GEV_DATA_DECOR)
		FROM LSRSER_GEV
		WHERE
		LSRSER_GEV_KEY_ID_RICEV = @CODLTM AND
		LSRSER_GEV_FLAG_VALIDITA = 'Y' AND
		LSRSER_GEV_FT_VOS <> '00000000' AND
		LSRSER_GEV_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
	)
	 
	SELECT @DATASTATO2 = LSRSER_GEV_DATA_DECOR, @STATO2 = LSRSER_GEV_STATO
	FROM LSRSER_GEV
	WHERE
	LSRSER_GEV_KEY_ID_RICEV = @CODLTM AND
	LSRSER_GEV_FLAG_VALIDITA = 'Y' AND
	LSRSER_GEV_FT_VOS <> '00000000' AND
	LSRSER_GEV_DATA_DECOR =
	(
		SELECT MAX(LSRSER_GEV_DATA_DECOR)
		FROM LSRSER_GEV
		WHERE
		LSRSER_GEV_KEY_ID_RICEV = @CODLTM AND
		LSRSER_GEV_FLAG_VALIDITA = 'Y' AND
		LSRSER_GEV_FT_VOS <> '00000000' AND

		LSRSER_GEV_DATA_DECOR < @DATASTATO1
	)
END

IF @GS = '02'
BEGIN

	SELECT @DATASTATO1 = LSRSER_GP_DATA_DECOR, @STATO1 = LSRSER_GP_STATO,
	@TIPOPROVV = LSRSER_GP_TIPO_PROVV, @DATAPROVV = LSRSER_GP_DATA_PROVV, 
	@NUMPROVV = LSRSER_GP_PROG_PROVV
	FROM LSRSER_GP
	WHERE
	LSRSER_GP_KEY_ID_RICEV = @CODLTM AND
	LSRSER_GP_FLAG_VALIDITA = 'Y' AND
	LSRSER_GP_FT_VOS <> '00000000' AND
	LSRSER_GP_DATA_DECOR =
	(
		SELECT MAX(LSRSER_GP_DATA_DECOR)
		FROM LSRSER_GP
		WHERE
		LSRSER_GP_KEY_ID_RICEV = @CODLTM AND
		LSRSER_GP_FLAG_VALIDITA = 'Y' AND
		LSRSER_GP_FT_VOS <> '00000000' AND
		LSRSER_GP_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
	)
	

	SELECT @DATASTATO2 = LSRSER_GP_DATA_DECOR, @STATO2 = LSRSER_GP_STATO
	FROM LSRSER_GP
	WHERE
	LSRSER_GP_KEY_ID_RICEV = @CODLTM AND
	LSRSER_GP_FLAG_VALIDITA = 'Y' AND
	LSRSER_GP_FT_VOS <> '00000000' AND
	LSRSER_GP_DATA_DECOR =
	(
		SELECT MAX(LSRSER_GP_DATA_DECOR)
		FROM LSRSER_GP
		WHERE
		LSRSER_GP_KEY_ID_RICEV = @CODLTM AND
		LSRSER_GP_FLAG_VALIDITA = 'Y' AND
		LSRSER_GP_FT_VOS <> '00000000' AND
		LSRSER_GP_DATA_DECOR < @DATASTATO1
	)
END

IF @GS = '11'
BEGIN
	SELECT @DATASTATO1 = LSRSER_CONI_DATA_DECOR, @STATO1 = LSRSER_CONI_STATO,
	@TIPOPROVV = LSRSER_CONI_TIPO_PROVV, @DATAPROVV = LSRSER_CONI_DATA_PROVV, 
	@NUMPROVV = LSRSER_CONI_PROG_PROVV
	FROM LSRSER_CONI
	WHERE
	LSRSER_CONI_KEY_ID_RICEV = @CODLTM AND
	LSRSER_CONI_FLAG_VALIDITA = 'Y' AND
	LSRSER_CONI_FT_VOS <> '00000000' AND
	LSRSER_CONI_DATA_DECOR =
	(
		SELECT MAX(LSRSER_CONI_DATA_DECOR)
		FROM LSRSER_CONI
		WHERE
		LSRSER_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRSER_CONI_FLAG_VALIDITA = 'Y' AND
		LSRSER_CONI_FT_VOS <> '00000000' AND
		LSRSER_CONI_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
	)
	
	SELECT @DATASTATO2 = LSRSER_CONI_DATA_DECOR, @STATO2 = LSRSER_CONI_STATO
	FROM LSRSER_CONI
	WHERE
	LSRSER_CONI_KEY_ID_RICEV = @CODLTM AND
	LSRSER_CONI_FLAG_VALIDITA = 'Y' AND
	LSRSER_CONI_FT_VOS <> '00000000' AND
	LSRSER_CONI_DATA_DECOR =
	(
		SELECT MAX(LSRSER_CONI_DATA_DECOR)
		FROM LSRSER_CONI
		WHERE
		LSRSER_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRSER_CONI_FLAG_VALIDITA = 'Y' AND
		LSRSER_CONI_FT_VOS <> '00000000' AND
		LSRSER_CONI_DATA_DECOR < @DATASTATO1
	)
END

IF @STATO2 IS NULL OR @STATO2 = '0'
BEGIN
	SELECT @DATASTATO2 = NULL
END

--MODIFICA DEL 01/09/2005: GESTIONE SCOMMESSE SPORTIVE
/*
select *
from lsrser_st
*/

IF @GS = '12'
BEGIN
	SELECT @DATASTATO1 = LSRSER_ST_DATA_DECOR, @STATO1 = LSRSER_ST_STATO,
	@TIPOPROVV = LSRSER_ST_TIPO_PROVV, @DATAPROVV = LSRSER_ST_DATA_PROVV, 
	@NUMPROVV = LSRSER_ST_PROG_PROVV
	FROM LSRSER_ST
	WHERE
	LSRSER_ST_KEY_ID_RICEV = @CODLTM AND
	LSRSER_ST_FLAG_VALIDITA = 'Y' AND
	LSRSER_ST_FT_VOS <> '00000000' AND
	LSRSER_ST_DATA_DECOR =
	(
		SELECT MAX(LSRSER_ST_DATA_DECOR)
		FROM LSRSER_ST
		WHERE
		LSRSER_ST_KEY_ID_RICEV = @CODLTM AND
		LSRSER_ST_FLAG_VALIDITA = 'Y' AND
		LSRSER_ST_FT_VOS <> '00000000' AND
		LSRSER_ST_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
	)
	
	SELECT @DATASTATO2 = LSRSER_ST_DATA_DECOR, @STATO2 = LSRSER_ST_STATO
	FROM LSRSER_ST
	WHERE
	LSRSER_ST_KEY_ID_RICEV = @CODLTM AND
	LSRSER_ST_FLAG_VALIDITA = 'Y' AND
	LSRSER_ST_FT_VOS <> '00000000' AND
	LSRSER_ST_DATA_DECOR =
	(
		SELECT MAX(LSRSER_ST_DATA_DECOR)
		FROM LSRSER_ST
		WHERE
		LSRSER_ST_KEY_ID_RICEV = @CODLTM AND
		LSRSER_ST_FLAG_VALIDITA = 'Y' AND
		LSRSER_ST_FT_VOS <> '00000000' AND
		LSRSER_ST_DATA_DECOR < @DATASTATO1
	)
END

IF @STATO2 IS NULL OR @STATO2 = '0'
BEGIN
	SELECT @DATASTATO2 = NULL
END

IF LEN(@GS) > 2
BEGIN
	SELECT @TABELLA = NULL

	SELECT @TABELLA = LSRSER_LIS_DEC_NOME_TAB 
	FROM LSRSER_LIS_DEC
	WHERE LSRSER_LIS_DEC_CATEGORIA + LSRSER_LIS_DEC_SERVIZIO + LSRSER_LIS_DEC_ATTIVITA = @GS


	IF @TABELLA = 'LSRSER_ATTI'
	BEGIN
		SELECT @DATASTATO1 = LSRSER_ATTI_DATA_DECOR, @STATO1 = LSRSER_ATTI_STATO,
		@TIPOPROVV = LSRSER_ATTI_TIPO_PROVV, @DATAPROVV = LSRSER_ATTI_DATA_PROVV, 
		@NUMPROVV = LSRSER_ATTI_PROG_PROVV
		FROM LSRSER_ATTI
		WHERE
		LSRSER_ATTI_KEY_ID_RICEV = @CODLTM AND
		LSRSER_ATTI_FLAG_VALIDITA = 'Y' AND
		LSRSER_ATTI_FT_VOS <> '00000000' AND
		LSRSER_ATTI_KEY_CATEGORIA + LSRSER_ATTI_KEY_SERVIZIO + LSRSER_ATTI_KEY_ATTIVITA = @GS AND
		LSRSER_ATTI_DATA_DECOR =
		(
			SELECT MAX(LSRSER_ATTI_DATA_DECOR)
			FROM LSRSER_ATTI
			WHERE
			LSRSER_ATTI_KEY_ID_RICEV = @CODLTM AND
			LSRSER_ATTI_FLAG_VALIDITA = 'Y' AND
			LSRSER_ATTI_FT_VOS <> '00000000' AND
			LSRSER_ATTI_KEY_CATEGORIA + LSRSER_ATTI_KEY_SERVIZIO + LSRSER_ATTI_KEY_ATTIVITA = @GS AND
			LSRSER_ATTI_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
		)

		SELECT @DATASTATO2 = LSRSER_ATTI_DATA_DECOR, @STATO2 = LSRSER_ATTI_STATO
		FROM LSRSER_ATTI
		WHERE
		LSRSER_ATTI_KEY_ID_RICEV = @CODLTM AND
		LSRSER_ATTI_FLAG_VALIDITA = 'Y' AND
		LSRSER_ATTI_FT_VOS <> '00000000' AND
		LSRSER_ATTI_KEY_CATEGORIA + LSRSER_ATTI_KEY_SERVIZIO + LSRSER_ATTI_KEY_ATTIVITA = @GS AND
		LSRSER_ATTI_DATA_DECOR =
		(
			SELECT MAX(LSRSER_ATTI_DATA_DECOR)
			FROM LSRSER_ATTI
			WHERE
			LSRSER_ATTI_KEY_ID_RICEV = @CODLTM AND
			LSRSER_ATTI_FLAG_VALIDITA = 'Y' AND
			LSRSER_ATTI_FT_VOS <> '00000000' AND
			LSRSER_ATTI_KEY_CATEGORIA + LSRSER_ATTI_KEY_SERVIZIO + LSRSER_ATTI_KEY_ATTIVITA = @GS AND
			LSRSER_ATTI_DATA_DECOR <@DATASTATO1
		)

	END
	
	IF @TABELLA = 'LSRSER_BIG'
	BEGIN
		SELECT @DATASTATO1 = LSRSER_BIG_DATA_DECOR, @STATO1 = LSRSER_BIG_STATO,
		@TIPOPROVV = LSRSER_BIG_TIPO_PROVV, @DATAPROVV = LSRSER_BIG_DATA_PROVV, 
		@NUMPROVV = LSRSER_BIG_PROG_PROVV
		FROM LSRSER_BIG
		WHERE
		LSRSER_BIG_KEY_ID_RICEV = @CODLTM AND
		LSRSER_BIG_FLAG_VALIDITA = 'Y' AND
		LSRSER_BIG_FT_VOS <> '00000000' AND
		LSRSER_BIG_KEY_CATEGORIA + LSRSER_BIG_KEY_SERVIZIO + LSRSER_BIG_KEY_ATTIVITA = @GS AND
		LSRSER_BIG_DATA_DECOR =
		(
			SELECT MAX(LSRSER_BIG_DATA_DECOR)
			FROM LSRSER_BIG
			WHERE
			LSRSER_BIG_KEY_ID_RICEV = @CODLTM AND
			LSRSER_BIG_FLAG_VALIDITA = 'Y' AND
			LSRSER_BIG_FT_VOS <> '00000000' AND
			LSRSER_BIG_KEY_CATEGORIA + LSRSER_BIG_KEY_SERVIZIO + LSRSER_BIG_KEY_ATTIVITA = @GS AND
			LSRSER_BIG_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
		)

		SELECT @DATASTATO2 = LSRSER_BIG_DATA_DECOR, @STATO2 = LSRSER_BIG_STATO
		FROM LSRSER_BIG
		WHERE
		LSRSER_BIG_KEY_ID_RICEV = @CODLTM AND
		LSRSER_BIG_FLAG_VALIDITA = 'Y' AND
		LSRSER_BIG_FT_VOS <> '00000000' AND
		LSRSER_BIG_KEY_CATEGORIA + LSRSER_BIG_KEY_SERVIZIO + LSRSER_BIG_KEY_ATTIVITA = @GS AND
		LSRSER_BIG_DATA_DECOR =
		(
			SELECT MAX(LSRSER_BIG_DATA_DECOR)
			FROM LSRSER_BIG
			WHERE
			LSRSER_BIG_KEY_ID_RICEV = @CODLTM AND
			LSRSER_BIG_FLAG_VALIDITA = 'Y' AND
			LSRSER_BIG_FT_VOS <> '00000000' AND
			LSRSER_BIG_KEY_CATEGORIA + LSRSER_BIG_KEY_SERVIZIO + LSRSER_BIG_KEY_ATTIVITA = @GS AND
			LSRSER_BIG_DATA_DECOR <@DATASTATO1
		)
	END
	IF @TABELLA = 'LSRSER_CITT'
	BEGIN
		SELECT @DATASTATO1 = LSRSER_CITT_DATA_DECOR, @STATO1 = LSRSER_CITT_STATO,
		@TIPOPROVV = LSRSER_CITT_TIPO_PROVV, @DATAPROVV = LSRSER_CITT_DATA_PROVV, 
		@NUMPROVV = LSRSER_CITT_PROG_PROVV
		FROM LSRSER_CITT
		WHERE
		LSRSER_CITT_KEY_ID_RICEV = @CODLTM AND
		LSRSER_CITT_FLAG_VALIDITA = 'Y' AND
		LSRSER_CITT_FT_VOS <> '00000000' AND
		LSRSER_CITT_KEY_CATEGORIA + LSRSER_CITT_KEY_SERVIZIO + LSRSER_CITT_KEY_ATTIVITA = @GS AND
		LSRSER_CITT_DATA_DECOR =
		(
			SELECT MAX(LSRSER_CITT_DATA_DECOR)
			FROM LSRSER_CITT
			WHERE
			LSRSER_CITT_KEY_ID_RICEV = @CODLTM AND
			LSRSER_CITT_FLAG_VALIDITA = 'Y' AND
			LSRSER_CITT_FT_VOS <> '00000000' AND
			LSRSER_CITT_KEY_CATEGORIA + LSRSER_CITT_KEY_SERVIZIO + LSRSER_CITT_KEY_ATTIVITA = @GS AND
			LSRSER_CITT_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
		)

		SELECT @DATASTATO2 = LSRSER_CITT_DATA_DECOR, @STATO2 = LSRSER_CITT_STATO
		FROM LSRSER_CITT
		WHERE
		LSRSER_CITT_KEY_ID_RICEV = @CODLTM AND
		LSRSER_CITT_FLAG_VALIDITA = 'Y' AND
		LSRSER_CITT_FT_VOS <> '00000000' AND
		LSRSER_CITT_KEY_CATEGORIA + LSRSER_CITT_KEY_SERVIZIO + LSRSER_CITT_KEY_ATTIVITA = @GS AND
		LSRSER_CITT_DATA_DECOR =
		(
			SELECT MAX(LSRSER_CITT_DATA_DECOR)
			FROM LSRSER_CITT
			WHERE
			LSRSER_CITT_KEY_ID_RICEV = @CODLTM AND
			LSRSER_CITT_FLAG_VALIDITA = 'Y' AND
			LSRSER_CITT_FT_VOS <> '00000000' AND
			LSRSER_CITT_KEY_CATEGORIA + LSRSER_CITT_KEY_SERVIZIO + LSRSER_CITT_KEY_ATTIVITA = @GS AND
			LSRSER_CITT_DATA_DECOR <@DATASTATO1
		)

	END
	IF @TABELLA = 'LSRSER_PAG'
	BEGIN
		SELECT @DATASTATO1 = LSRSER_PAG_DATA_DECOR, @STATO1 = LSRSER_PAG_STATO,
		@TIPOPROVV = LSRSER_PAG_TIPO_PROVV, @DATAPROVV = LSRSER_PAG_DATA_PROVV, 
		@NUMPROVV = LSRSER_PAG_PROG_PROVV
		FROM LSRSER_PAG
		WHERE
		LSRSER_PAG_KEY_ID_RICEV = @CODLTM AND
		LSRSER_PAG_FLAG_VALIDITA = 'Y' AND
		LSRSER_PAG_FT_VOS <> '00000000' AND
		LSRSER_PAG_KEY_CATEGORIA + LSRSER_PAG_KEY_SERVIZIO + LSRSER_PAG_KEY_ATTIVITA = @GS AND
		LSRSER_PAG_DATA_DECOR =
		(
			SELECT MAX(LSRSER_PAG_DATA_DECOR)
			FROM LSRSER_PAG
			WHERE
			LSRSER_PAG_KEY_ID_RICEV = @CODLTM AND
			LSRSER_PAG_FLAG_VALIDITA = 'Y' AND
			LSRSER_PAG_FT_VOS <> '00000000' AND
			LSRSER_PAG_KEY_CATEGORIA + LSRSER_PAG_KEY_SERVIZIO + LSRSER_PAG_KEY_ATTIVITA = @GS AND
			LSRSER_PAG_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
		)

		SELECT @DATASTATO2 = LSRSER_PAG_DATA_DECOR, @STATO2 = LSRSER_PAG_STATO
		FROM LSRSER_PAG
		WHERE
		LSRSER_PAG_KEY_ID_RICEV = @CODLTM AND
		LSRSER_PAG_FLAG_VALIDITA = 'Y' AND
		LSRSER_PAG_FT_VOS <> '00000000' AND
		LSRSER_PAG_KEY_CATEGORIA + LSRSER_PAG_KEY_SERVIZIO + LSRSER_PAG_KEY_ATTIVITA = @GS AND
		LSRSER_PAG_DATA_DECOR =
		(
			SELECT MAX(LSRSER_PAG_DATA_DECOR)
			FROM LSRSER_PAG
			WHERE
			LSRSER_PAG_KEY_ID_RICEV = @CODLTM AND
			LSRSER_PAG_FLAG_VALIDITA = 'Y' AND
			LSRSER_PAG_FT_VOS <> '00000000' AND
			LSRSER_PAG_KEY_CATEGORIA + LSRSER_PAG_KEY_SERVIZIO + LSRSER_PAG_KEY_ATTIVITA = @GS AND
			LSRSER_PAG_DATA_DECOR <@DATASTATO1
		)

	END
	IF @TABELLA = 'LSRSER_TEL'
	BEGIN
		SELECT @DATASTATO1 = LSRSER_TEL_DATA_DECOR, @STATO1 = LSRSER_TEL_STATO,
		@TIPOPROVV = LSRSER_TEL_TIPO_PROVV, @DATAPROVV = LSRSER_TEL_DATA_PROVV, 
		@NUMPROVV = LSRSER_TEL_PROG_PROVV
		FROM LSRSER_TEL
		WHERE
		LSRSER_TEL_KEY_ID_RICEV = @CODLTM AND
		LSRSER_TEL_FLAG_VALIDITA = 'Y' AND
		LSRSER_TEL_FT_VOS <> '00000000' AND
		LSRSER_TEL_KEY_CATEGORIA + LSRSER_TEL_KEY_SERVIZIO + LSRSER_TEL_KEY_ATTIVITA = @GS AND
		LSRSER_TEL_DATA_DECOR =
		(
			SELECT MAX(LSRSER_TEL_DATA_DECOR)
			FROM LSRSER_TEL
			WHERE
			LSRSER_TEL_KEY_ID_RICEV = @CODLTM AND
			LSRSER_TEL_FLAG_VALIDITA = 'Y' AND
			LSRSER_TEL_FT_VOS <> '00000000' AND
			LSRSER_TEL_KEY_CATEGORIA + LSRSER_TEL_KEY_SERVIZIO + LSRSER_TEL_KEY_ATTIVITA = @GS AND
			LSRSER_TEL_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)
		)

		SELECT @DATASTATO2 = LSRSER_TEL_DATA_DECOR, @STATO2 = LSRSER_TEL_STATO
		FROM LSRSER_TEL
		WHERE
		LSRSER_TEL_KEY_ID_RICEV = @CODLTM AND
		LSRSER_TEL_FLAG_VALIDITA = 'Y' AND
		LSRSER_TEL_FT_VOS <> '00000000' AND
		LSRSER_TEL_KEY_CATEGORIA + LSRSER_TEL_KEY_SERVIZIO + LSRSER_TEL_KEY_ATTIVITA = @GS AND
		LSRSER_TEL_DATA_DECOR =
		(
			SELECT MAX(LSRSER_TEL_DATA_DECOR)
			FROM LSRSER_TEL
			WHERE
			LSRSER_TEL_KEY_ID_RICEV = @CODLTM AND
			LSRSER_TEL_FLAG_VALIDITA = 'Y' AND
			LSRSER_TEL_FT_VOS <> '00000000' AND
			LSRSER_TEL_KEY_CATEGORIA + LSRSER_TEL_KEY_SERVIZIO + LSRSER_TEL_KEY_ATTIVITA = @GS AND
			LSRSER_TEL_DATA_DECOR <@DATASTATO1
		)

	END

END
GO
