/****** Object:  StoredProcedure [dbo].[CREA_LSEAPP]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CREA_LSEAPP]  AS

DECLARE   

@IERI 			CHAR(8),
@OGGI 		CHAR(8),
@RICEVITORIA 	CHAR(6),
@DATAORAINS 	CHAR(16),
@RICEVITORIATIT 	CHAR(6),
@COGNOMETIT 	CHAR(24),
@NOMETIT 		CHAR(24),
@DATAVALTIT 	CHAR(8),
@DATANASCTIT 	CHAR(8),
@LUOGONASCTIT 	CHAR(30),
@PROVNASCTIT 	CHAR(2),    
@TIPO 			CHAR(1), 
@SESSOTIT 		CHAR(1),
@DATAINSTIT 		CHAR(8),
@FLAGESE 		CHAR(1),
@CODFISCTIT 		CHAR(16),
@TESTO 		VARCHAR(300),
@NOMEJOB		VARCHAR(25)

SELECT @OGGI = CONVERT(CHAR(8), GETDATE(), 112)
SELECT @IERI = SUBSTRING(CONVERT(CHAR, GETDATE() -1, 121),1,4)+ 
		SUBSTRING(CONVERT(CHAR, GETDATE() -1, 121),6,2)+ 
		SUBSTRING(CONVERT(CHAR, GETDATE() -1, 121),9,2)

SELECT @NOMEJOB = 'AAEG012001UC'

DELETE FROM LSEAPP
--***************************************************************************
--* DICHIARAZIONE DEL CURSORE RELATIVO AI TITOLARI
--***************************************************************************
DECLARE CURSORE_TIT CURSOR
FOR SELECT LSRTIT_KEY_ID_RICEV,MAX(LSRTIT_KEY_DATA_INS+LSRTIT_KEY_ORA_INS)
FROM LSRTIT
WHERE ((LSRTIT_DATA_VALIDITA <= @OGGI
AND LSRTIT_KEY_DATA_INS =  @IERI)
OR LSRTIT_DATA_VALIDITA =  @OGGI)
AND LSRTIT_FLAG_VALIDITA = 'Y'
AND LSRTIT_FT_VOS = '00000000'
GROUP BY LSRTIT_KEY_ID_RICEV
ORDER BY 1
--***************************************************************************
--* APERTURA DEL CURSORE RELATIVO ALLE RICEVITORIE + TITOLARI
--***************************************************************************
OPEN CURSORE_TIT
FETCH NEXT FROM CURSORE_TIT INTO @RICEVITORIA,@DATAORAINS
WHILE @@FETCH_STATUS = 0 
BEGIN
	DECLARE CURSORE_RICTIT CURSOR
	FOR SELECT LSRRIC_KEY_ID_RICEV, LSRTIT_KEY_DATA_INS,
	LSRTIT_COGNOME,LSRTIT_NOME, LSRTIT_DATA_VALIDITA, LSRTIT_DATA_NASCITA,
	LSRTIT_COMUNE_NASCITA, LSRTIT_PROVINCIA_NASCITA, LSRTIT_TIPO, LSRTIT_SESSO,
	LSRTIT_CODICE_FISCALE, LSRRIC_FLAG_ESERCIZIO 
	FROM LSRRIC JOIN LSRTIT ON LSRRIC_KEY_ID_RICEV = LSRTIT_KEY_ID_RICEV 
	WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA 
	AND LSRTIT_KEY_DATA_INS+LSRTIT_KEY_ORA_INS = @DATAORAINS
	AND LSRRIC_KEY_DATA_INS+LSRRIC_KEY_ORA_INS = 
		(SELECT MAX(LSRRIC_KEY_DATA_INS+LSRRIC_KEY_ORA_INS) 
		FROM LSRRIC
		WHERE LSRRIC_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRIC_DATA_VALIDITA <= @OGGI 
		AND LSRRIC_FLAG_VALIDITA = 'Y'
		AND LSRRIC_FT_VOS = '00000000') 
	AND LSRTIT_DATA_VALIDITA <= @OGGI 
	AND LSRTIT_FLAG_VALIDITA = 'Y' 
	AND LSRRIC_FT_VOS = '00000000'

	OPEN CURSORE_RICTIT
	FETCH NEXT FROM CURSORE_RICTIT INTO @RICEVITORIATIT,@DATAINSTIT,
             @COGNOMETIT, @NOMETIT, @DATAVALTIT, @DATANASCTIT,
             @LUOGONASCTIT,@PROVNASCTIT,@TIPO, @SESSOTIT,
             @CODFISCTIT, @FLAGESE
	WHILE @@FETCH_STATUS = 0 
	BEGIN
  		INSERT INTO LSEAPP VALUES (@RICEVITORIATIT,@TIPO,
		@LUOGONASCTIT,@PROVNASCTIT, @DATANASCTIT,@SESSOTIT,@CODFISCTIT,
               	NULL,NULL,NULL, @DATAVALTIT, @DATAINSTIT,@FLAGESE,NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @TESTO = 'ERRORE IN INSERT SU LSEAPP'
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @TESTO, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSEAPP TERMINATA IN MODO ANOMALO', 0
			RAISERROR (@TESTO, 16, 1)
			RETURN
		END

		FETCH NEXT FROM CURSORE_RICTIT INTO @RICEVITORIATIT,@DATAINSTIT,
		@COGNOMETIT, @NOMETIT, @DATAVALTIT, @DATANASCTIT,
		@LUOGONASCTIT,@PROVNASCTIT,@TIPO, @SESSOTIT,
		@CODFISCTIT, @FLAGESE
	END

	CLOSE CURSORE_RICTIT
	DEALLOCATE CURSORE_RICTIT

	FETCH NEXT FROM CURSORE_TIT INTO @RICEVITORIA,@DATAORAINS
END

CLOSE CURSORE_TIT
DEALLOCATE CURSORE_TIT

EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSEAPP TERMINATA CORRETTAMENTE', 0
GO
