/****** Object:  StoredProcedure [dbo].[Crea_AttivLis]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[Crea_AttivLis] 
AS

DECLARE	@Stato			char(1),
                  	@Oggi			char(8),
                  	@Ieri			char(8),
	             @DataDecorr		char(8), 
		@StatoSer		char(1),
		@Categoria		char(2),
		@Servizio		char(2),
		@Attivita		char(2),
		@CodRicev		char(6),
		@NumRecAtt		char(8),	
		@NumRecDis		char(8),	
		@NumRecTot		char(8),	
		@FILEDATE		VARCHAR(35),
		@FILEAPPO		VARCHAR(35),
		@FILEPLTLIS		VARCHAR(35),
		@NOMEJOB		VARCHAR(15),
		@PATHID		INT,
		@MSGERR		VARCHAR(100),
		@STRINGA		VARCHAR(200)


SELECT @Oggi = CONVERT(CHAR,GETDATE(),112)
SELECT @Ieri = CONVERT(CHAR,GETDATE() - 1,112)
--SELECT @Oggi = '20020831'
--SELECT @Ieri = '20020830'

SELECT @PATHID = 83
SELECT @NOMEJOB = 'AACG012001GN'
SELECT @FILEDATE = 'ATTIVLIS.' + @Ieri
SELECT @FILEAPPO = 'ATTIVLIS_' + @Ieri
SELECT @FILEPLTLIS = 'ATTIVLIS.PLT'

--CANCELLAZIONE FILE AttivLis.Data
EXEC MSDB..UT_AA009  @PATHID, @FILEDATE, 9999, @NOMEJOB
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE CANCELLAZIONE FILE'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

--CANCELLAZIONE FILE AttivLis_Data
EXEC MSDB..UT_AA009  @PATHID, @FILEAPPO, 9999, @NOMEJOB
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE CANCELLAZIONE FILE'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END


--SCRITTURA FILE AttivLis.Data
SELECT @STRINGA = '0' + @Ieri
EXEC MSDB..UT_AA010 9999, @PATHID, @FILEDATE, @STRINGA, @NOMEJOB
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE SCRITTURA FILE'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

SELECT @NumRecAtt = '00000000'
SELECT @NumRecDis = '00000000'
SELECT @NumRecTot	= '00000002'

DECLARE CUR_R1 SCROLL CURSOR FOR

SELECT  LSRSER_TEL_KEY_ID_RICEV, LSRSER_TEL_KEY_CATEGORIA, 
	LSRSER_TEL_KEY_SERVIZIO, LSRSER_TEL_KEY_ATTIVITA, LSRSER_TEL_STATO
FROM LSRSER_TEL  A
WHERE LSRSER_TEL_DATA_DECOR = 
	(SELECT MAX(LSRSER_TEL_DATA_DECOR) 
	FROM LSRSER_TEL B
	WHERE ((LSRSER_TEL_DATA_DECOR <= @OGGI AND LSRSER_TEL_KEY_DATA_INS =  @IERI)
		OR LSRSER_TEL_DATA_DECOR =  @OGGI)
		AND B.LSRSER_TEL_KEY_ID_RICEV = A.LSRSER_TEL_KEY_ID_RICEV
		AND LSRSER_TEL_FLAG_VALIDITA = 'Y'
		AND LSRSER_TEL_FT_VOS = '00000000'
		)
	AND LSRSER_TEL_FT_VOS = '00000000'
 	AND LSRSER_TEL_FLAG_VALIDITA = 'Y'

UNION	

SELECT  LSRSER_CITT_KEY_ID_RICEV, LSRSER_CITT_KEY_CATEGORIA, 
	LSRSER_CITT_KEY_SERVIZIO, LSRSER_CITT_KEY_ATTIVITA, LSRSER_CITT_STATO
FROM LSRSER_CITT  A
WHERE LSRSER_CITT_DATA_DECOR = 
	(SELECT MAX(LSRSER_CITT_DATA_DECOR) 
	FROM LSRSER_CITT B
	WHERE ((LSRSER_CITT_DATA_DECOR <= @OGGI AND LSRSER_CITT_KEY_DATA_INS =  @IERI)
		OR LSRSER_CITT_DATA_DECOR =  @OGGI)
		AND B.LSRSER_CITT_KEY_ID_RICEV = A.LSRSER_CITT_KEY_ID_RICEV
		AND LSRSER_CITT_FLAG_VALIDITA = 'Y'
		AND LSRSER_CITT_FT_VOS = '00000000'
	)
	AND LSRSER_CITT_FT_VOS = '00000000'
 	AND LSRSER_CITT_FLAG_VALIDITA = 'Y'

UNION	

SELECT  LSRSER_PAG_KEY_ID_RICEV, LSRSER_PAG_KEY_CATEGORIA, 
	LSRSER_PAG_KEY_SERVIZIO, LSRSER_PAG_KEY_ATTIVITA, LSRSER_PAG_STATO
FROM LSRSER_PAG  A
WHERE LSRSER_PAG_DATA_DECOR = 
	(SELECT MAX(LSRSER_PAG_DATA_DECOR) 
	FROM LSRSER_PAG B
	WHERE ((LSRSER_PAG_DATA_DECOR <= @OGGI AND LSRSER_PAG_KEY_DATA_INS =  @IERI)
		OR LSRSER_PAG_DATA_DECOR =  @OGGI)
		AND B.LSRSER_PAG_KEY_ID_RICEV = A.LSRSER_PAG_KEY_ID_RICEV
		AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
		AND LSRSER_PAG_FT_VOS = '00000000'
	)
	AND LSRSER_PAG_FT_VOS = '00000000'
 	AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
	AND LSRSER_PAG_KEY_CATEGORIA + LSRSER_PAG_KEY_SERVIZIO + LSRSER_PAG_KEY_ATTIVITA <> '030101'

UNION	

SELECT  LSRSER_BIG_KEY_ID_RICEV, LSRSER_BIG_KEY_CATEGORIA, 
	LSRSER_BIG_KEY_SERVIZIO, LSRSER_BIG_KEY_ATTIVITA, LSRSER_BIG_STATO
FROM LSRSER_BIG  A
WHERE LSRSER_BIG_DATA_DECOR = 
	(SELECT MAX(LSRSER_BIG_DATA_DECOR) 
	FROM LSRSER_BIG B
	WHERE ((LSRSER_BIG_DATA_DECOR <= @OGGI AND LSRSER_BIG_KEY_DATA_INS =  @IERI)
		OR LSRSER_BIG_DATA_DECOR =  @OGGI)
		AND B.LSRSER_BIG_KEY_ID_RICEV = A.LSRSER_BIG_KEY_ID_RICEV
		AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
		AND LSRSER_BIG_FT_VOS = '00000000'
	)
	AND LSRSER_BIG_FT_VOS = '00000000'
 	AND LSRSER_BIG_FLAG_VALIDITA = 'Y'

UNION	

SELECT  LSRSER_ATTI_KEY_ID_RICEV, LSRSER_ATTI_KEY_CATEGORIA, 
	LSRSER_ATTI_KEY_SERVIZIO, LSRSER_ATTI_KEY_ATTIVITA, LSRSER_ATTI_STATO
FROM LSRSER_ATTI  A
WHERE LSRSER_ATTI_DATA_DECOR = 
	(SELECT MAX(LSRSER_ATTI_DATA_DECOR) 
	FROM LSRSER_ATTI B
	WHERE ((LSRSER_ATTI_DATA_DECOR <= @OGGI AND LSRSER_ATTI_KEY_DATA_INS =  @IERI)
		OR LSRSER_ATTI_DATA_DECOR =  @OGGI)
		AND B.LSRSER_ATTI_KEY_ID_RICEV = A.LSRSER_ATTI_KEY_ID_RICEV
		AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'

		AND LSRSER_ATTI_FT_VOS = '00000000'
	)
	AND LSRSER_ATTI_FT_VOS = '00000000'
 	AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'


OPEN CUR_R1
FETCH NEXT FROM CUR_R1
INTO @CodRicev, @Categoria, @Servizio, @Attivita, @StatoSer


WHILE @@FETCH_STATUS = 0 
BEGIN

	--SCRITTURA FILE AttivLis_Data
	--LA DATA CHE COMPARE NEL RECORD RELATIVO ALLA MOVIMENTAZIONE DEVE ESSERE LA DATA
	--DEL GIORNO PRECEDENTE, QUELLO IN CUI LA MOVIMENTAZIONE E' STATA ACQUISITA
	SELECT @STRINGA = '1' + @CodRicev + @Ieri +   @Categoria + @Servizio + @Attivita + @StatoSer + @Ieri
	EXEC MSDB..UT_AA010 9999, @PATHID, @FILEDATE, @STRINGA, @NOMEJOB
	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE SCRITTURA FILE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	IF @StatoSer = '1' 
	BEGIN
		SELECT @NumRecAtt = @NumRecAtt + 1
	END
	ELSE
	BEGIN
		SELECT @NumRecDis = @NumRecDis + 1
	END

	SELECT @NumRecTot = @NumRecTot + 1


	FETCH NEXT FROM CUR_R1
	INTO @CodRicev, @Categoria, @Servizio, @Attivita, @StatoSer


END
CLOSE CUR_R1
DEALLOCATE CUR_R1


SELECT @NumRecAtt = Replicate ('0', (8 - len(@NumRecAtt))) + @NumRecAtt
SELECT @NumRecDis = Replicate ('0', (8 - len(@NumRecDis))) + @NumRecDis
SELECT @NumRecTot = Replicate ('0', (8 - len(@NumRecTot))) + @NumRecTot

PRINT @NumRecTot
--SE CI SONO MOVIMENTAZIONI DA INVIARE, ALLORA CONTINUO LA SCRITTURA DEL FILE
IF @NumRecTot <> '00000002'
BEGIN
	--SCRITTURA FILE AttivLis_Data
	SELECT @STRINGA = '9' + @Ieri + @NumRecAtt + @NumRecDis + @NumRecTot 
	EXEC MSDB..UT_AA010 9999, @PATHID, @FILEDATE, @STRINGA, @NOMEJOB
	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE SCRITTURA FILE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END


END
--ALTRIMENTI 
ELSE
BEGIN
	--CANCELLAZIONE FILE AttivLis.Data
	EXEC MSDB..UT_AA009  @PATHID, @FILEDATE, 9999, @NOMEJOB
	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE CANCELLAZIONE FILE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

	--E NE CREO UNO VUOTO
	EXEC MSDB..UT_AA010 9999, @PATHID, @FILEDATE, '', @NOMEJOB
	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE SCRITTURA FILE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END

--CREATA COPIA DEL FILE PRODOTO CON IL NOME @FILEAPPO
EXEC MSDB..UT_AA007  @PATHID, @FILEDATE, @PATHID, @FILEAPPO, 9999, @NOMEJOB
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE CREAZIONE COPIA FILE'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

-- CREAZIONE FILE PILOTA
EXEC MSDB..UT_AA010 9999, @PATHID, @FILEPLTLIS, '', @NOMEJOB
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE CREAZIONE FILE PILOTA'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

--EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_ATTIV_LIS TERMINATA CORRETTAMENTE', 0
GO
