/****** Object:  StoredProcedure [dbo].[CC_DATI_MOVIMENTAZIONI_OLD_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CC_DATI_MOVIMENTAZIONI_OLD_GS]

@CODLTM		VARCHAR(7),
@GS			VARCHAR(6),
@DATASTATO		CHAR(8)


AS

IF @GS = '02'
BEGIN
	SELECT  DATA_RAD, 
	CASE TIPO
		WHEN 'A' THEN 'ATTIVAZIONE'
		WHEN 'D' THEN 'DISATTIVAZIONE'
		WHEN 'R' THEN 'RIATTIVAZIONE'
		WHEN 'S' THEN 'SOSPENSIONE'
	END AS TIPOMOV,
	FONTE,
	NULL
	FROM RAD_F101
	WHERE
	COD_LOTT = @CODLTM AND
	DATA_RAD = @DATASTATO
	ORDER BY DATA_RAD DESC
END
ELSE IF @GS = '05'
BEGIN
	SELECT  DATA_RAD, 
	CASE TIPO
		WHEN 'A' THEN 'ATTIVAZIONE'
		WHEN 'D' THEN 'DISATTIVAZIONE'
		WHEN 'R' THEN 'RIATTIVAZIONE'
		WHEN 'S' THEN 'SOSPENSIONE'
	END AS TIPOMOV,
	FONTE,
	PROVV_COD_ENTE
	FROM RAD_BOLLO
	WHERE
	COD_LOTT = @CODLTM AND
	DATA_RAD = @DATASTATO
	ORDER BY DATA_RAD DESC
END
ELSE IF @GS = '08'
BEGIN
	SELECT  DATA_RAD, 
	CASE TIPO
		WHEN 'A' THEN 'ATTIVAZIONE'
		WHEN 'D' THEN 'DISATTIVAZIONE'
		WHEN 'R' THEN 'RIATTIVAZIONE'
		WHEN 'S' THEN 'SOSPENSIONE'
	END AS TIPOMOV,
	FONTE,
	NULL
	FROM RAD_TRIS
	WHERE
	COD_LOTT = @CODLTM AND
	DATA_RAD = @DATASTATO
	ORDER BY DATA_RAD DESC

END
GO
