/****** Object:  StoredProcedure [dbo].[CC_DATI_MOVIMENTAZIONI_NEW_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[CC_DATI_MOVIMENTAZIONI_NEW_GS]

@CODLTM		VARCHAR(7),
@GS			VARCHAR(6),
@DATASTATO		CHAR(8)

 AS

IF LEN(@GS) = 2
BEGIN
	--MODIFICA DEL 30/07/2003: GESTIONE CONI (CDS)
	IF (@GS='11')
	BEGIN
		SELECT LSRLET_CONI_NOME_TAB_DOCUMENTO, LSRLET_CONI_FK_TAB_DOCUMENTO, 
		CASE LSRLET_CONI_TIPO_MOVIMENTAZIONE
			WHEN 'A' THEN 'ATTIVAZIONE'
			WHEN 'D' THEN 'DISATTIVAZIONE'
			WHEN 'R' THEN 'RIATTIVAZIONE'
		END AS TIPOMOV, LSRLET_CONI_NOTE
		FROM LSRLET_CONI 
		WHERE 
		LSRLET_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRLET_CONI_DATA_LETTERA <>  '19000101' AND
		LSRLET_CONI_DECOR_DAL = 
		(
			SELECT MAX(LSRLET_CONI_DECOR_DAL)
			FROM LSRLET_CONI 
			WHERE 
			LSRLET_CONI_KEY_ID_RICEV = @CODLTM AND
			LSRLET_CONI_DATA_LETTERA <> '19000101' AND
			LSRLET_CONI_DECOR_DAL <= @DATASTATO
		)

	END
	--MODIFICA DEL 01/09/2005: GESTIONE SCOMMESSE SPORTIVE
	IF (@GS='12')
	BEGIN
		SELECT LSRLET_ST_NOME_TAB_DOCUMENTO, LSRLET_ST_FK_TAB_DOCUMENTO, 
		CASE LSRLET_ST_TIPO_MOVIMENTAZIONE
			WHEN 'A' THEN 'ATTIVAZIONE'
			WHEN 'D' THEN 'DISATTIVAZIONE'
			WHEN 'R' THEN 'RIATTIVAZIONE'
		END AS TIPOMOV, LSRLET_ST_NOTE
		FROM LSRLET_ST 
		WHERE 
		LSRLET_ST_KEY_ID_RICEV = @CODLTM AND
		LSRLET_ST_DATA_LETTERA <>  '19000101' AND
		LSRLET_ST_DECOR_DAL = 
		(
			SELECT MAX(LSRLET_ST_DECOR_DAL)
			FROM LSRLET_ST 
			WHERE 
			LSRLET_ST_KEY_ID_RICEV = @CODLTM AND
			LSRLET_ST_DATA_LETTERA <> '19000101' AND
			LSRLET_ST_DECOR_DAL <= @DATASTATO
		)

	END

	IF (@GS='08')
	BEGIN
		SELECT LSRLET_GS_NOME_TAB_DOCUMENTO, LSRLET_GS_FK_TAB_DOCUMENTO, 
		CASE LSRLET_GS_TIPO_MOVIMENTAZIONE
			WHEN 'A' THEN 'ATTIVAZIONE'
			WHEN 'D' THEN 'DISATTIVAZIONE'
			WHEN 'R' THEN 'RIATTIVAZIONE'
			WHEN 'S' THEN 'SOSPENSIONE'
		END AS TIPOMOV, LSRLET_GS_NOTE
		FROM LSRLET_GS 
		WHERE 
		LSRLET_GS_KEY_ID_RICEV = @CODLTM AND
		LSRLET_GS_DATA_LETTERA <>  '19000101' AND
		LSRLET_GS_DECOR_DAL = 
		(
			SELECT MAX(LSRLET_GS_DECOR_DAL)
			FROM LSRLET_GS 
			WHERE 
			LSRLET_GS_KEY_ID_RICEV = @CODLTM AND
			LSRLET_GS_KEY_CODICE_SERVIZIO = '08' AND
			LSRLET_GS_DATA_LETTERA <> '19000101' AND
			LSRLET_GS_DECOR_DAL <= @DATASTATO
		)

	END
	IF (@GS='02')
	BEGIN
		SELECT LSRLET_GS_NOME_TAB_DOCUMENTO, LSRLET_GS_FK_TAB_DOCUMENTO, 
		CASE LSRLET_GS_TIPO_MOVIMENTAZIONE
			WHEN 'A' THEN 'ATTIVAZIONE'
			WHEN 'D' THEN 'DISATTIVAZIONE'
			WHEN 'R' THEN 'RIATTIVAZIONE'
			WHEN 'S' THEN 'SOSPENSIONE'
		END AS TIPOMOV, LSRLET_GS_NOTE
		FROM LSRLET_GS 
		WHERE 
		LSRLET_GS_KEY_ID_RICEV = @CODLTM AND
		LSRLET_GS_DATA_LETTERA <>  '19000101' AND
		LSRLET_GS_DECOR_DAL = 
		(
			SELECT MAX(LSRLET_GS_DECOR_DAL)
			FROM LSRLET_GS 
			WHERE 
			LSRLET_GS_KEY_ID_RICEV = @CODLTM AND
			LSRLET_GS_KEY_CODICE_SERVIZIO = '02' AND
			LSRLET_GS_DATA_LETTERA <> '19000101' AND
			LSRLET_GS_DECOR_DAL <= @DATASTATO
		)

	END

	ELSE
	BEGIN
		SELECT LSRLET_NOME_TAB_DOCUMENTO, LSRLET_FK_TAB_DOCUMENTO, 
		CASE LSRLET_TIPO_MOVIMENTAZIONE
			WHEN 'A' THEN 'ATTIVAZIONE'
			WHEN 'D' THEN 'DISATTIVAZIONE'
			WHEN 'R' THEN 'RIATTIVAZIONE'
		END AS TIPOMOV, LSRLET_NOTE
		FROM LSRLET 
		WHERE 
		LSRLET_KEY_ID_RICEV = @CODLTM AND
		LSRLET_DATA_LETTERA NOT IN ('00000000', '19000101') AND
		LSRLET_COD_SERVIZIO = @GS AND
		LSRLET_DECOR_DAL = 
		(
			SELECT MAX(LSRLET_DECOR_DAL)
			FROM LSRLET 
			WHERE 
			LSRLET_KEY_ID_RICEV = @CODLTM AND
			LSRLET_DATA_LETTERA NOT IN ('00000000', '19000101') AND
			LSRLET_COD_SERVIZIO = @GS AND
			LSRLET_DECOR_DAL <= @DATASTATO
		)
	END
END
ELSE
BEGIN
	SELECT LSRLET_LIS_NOME_TAB_DOCUMENTO, LSRLET_LIS_FK_TAB_DOCUMENTO, 
	LSRLET_LIS_TIPO_MOVIMENTAZIONE, LSRLET_LIS_NOTE
	FROM LSRLET_LIS
	WHERE 
	LSRLET_LIS_KEY_ID_RICEV = @CODLTM AND
	LSRLET_LIS_DECOR_DAL <> '00000000' AND
	LSRLET_LIS_KEY_CATEGORIA + LSRLET_LIS_KEY_SERVIZIO + LSRLET_LIS_KEY_ATTIVITA = @GS AND
	LSRLET_LIS_DECOR_DAL =
	(
		SELECT MAX(LSRLET_LIS_DECOR_DAL)
		FROM LSRLET_LIS
		WHERE 
		LSRLET_LIS_KEY_ID_RICEV = @CODLTM AND
		LSRLET_LIS_DECOR_DAL <> '00000000' AND
		LSRLET_LIS_DATA_LETTERA <> '19000101' AND
		LSRLET_LIS_KEY_CATEGORIA + LSRLET_LIS_KEY_SERVIZIO + LSRLET_LIS_KEY_ATTIVITA = @GS AND
		LSRLET_LIS_DECOR_DAL <=  @DATASTATO
	)

END
GO
