/****** Object:  StoredProcedure [dbo].[CREA_LSR5APP]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CREA_LSR5APP]

AS

DECLARE 

@OGGI			CHAR(8),
@IERI			CHAR(8),
@MSGERR		VARCHAR(100),
@RICEV		CHAR(6),
@TIPOREC		CHAR(1),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATAPROVV 	CHAR(8),
@PROGPROVV		CHAR(14),
@CAUSALE		CHAR(40),
@FIRMA		CHAR(17),
@EMANATO		CHAR(25),
@DECORDAL		CHAR(8),
@DECORAL		CHAR(8),
@TASSA		CHAR(9),
@ANNO		CHAR(4),
@MASSIMALE		CHAR(11),
@CODTAB		CHAR(10),
@FLAGANNULL	CHAR(1),
@FLAGVAL		CHAR(1),
@FTVOS		CHAR(8),
@NOMEJOB		VARCHAR(25)

SELECT @NOMEJOB = 'AAEG012001UC'

SELECT @OGGI =  CONVERT(CHAR(8),GETDATE(),112)
SELECT @IERI =  CONVERT(CHAR(8),GETDATE()-1,112)

DELETE FROM LSR5APP

DECLARE CUR_PRO CURSOR FOR 
SELECT * FROM LSRPRO
WHERE (LSRPRO_DECOR_DAL = (@OGGI)  OR (LSRPRO_DECOR_DAL <= @OGGI AND LSRPRO_DATA_INS = @IERI))
	 AND LSRPRO_KEY_TIPO_REC IN ('I','E','T')
	AND LSRPRO_FT_VOS = '00000000'
	AND LSRPRO_FLAG_VALIDITA = 'Y'
	and LSRPRO_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)


ORDER BY LSRPRO_DATA_INS,LSRPRO_ORA_INS
OPEN CUR_PRO
FETCH NEXT FROM CUR_PRO INTO 
@RICEV,@TIPOREC,@DATAINS,@ORAINS,@DATAPROVV,
@PROGPROVV,@CAUSALE,@FIRMA,@EMANATO,@DECORDAL,
@DECORAL,@TASSA,@ANNO,@MASSIMALE,@CODTAB,
@FLAGANNULL,@FLAGVAL,@FTVOS

WHILE @@FETCH_STATUS = 0
BEGIN
	INSERT INTO LSR5APP VALUES
	(@RICEV,@TIPOREC,@DATAPROVV,@PROGPROVV,@CAUSALE,@FIRMA,
	 @EMANATO,@DECORDAL,NULL,@FLAGANNULL,NULL,NULL,NULL)
	
	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = @RICEV + ' - ERRORE IN INSERT SU LSR5APP'
		RAISERROR (@MSGERR, 16, 1)

		EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
		EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSR5APP TERMINATA IN MODO ANOMALO', 0

		CLOSE CUR_PRO
		DEALLOCATE CUR_PRO

		RETURN
	END

	FETCH NEXT FROM CUR_PRO INTO 
	@RICEV,@TIPOREC,@DATAINS,@ORAINS,@DATAPROVV,
	@PROGPROVV,@CAUSALE,@FIRMA,@EMANATO,@DECORDAL,
	@DECORAL,@TASSA,@ANNO,@MASSIMALE,@CODTAB,
	@FLAGANNULL,@FLAGVAL,@FTVOS
END

CLOSE CUR_PRO
DEALLOCATE CUR_PRO

EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSR5APP TERMINATA CORRETTAMENTE', 0
GO
