/****** Object:  StoredProcedure [dbo].[GESTIONE_LSRVAR_IND]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GESTIONE_LSRVAR_IND]
  
	@RICEV 		CHAR(6),
	@INDIRIZZO		CHAR(40),
	@CAP			CHAR(5),
	@COMUNE		CHAR(24),
	@PROVINCIA		CHAR(2),
	@MSGERR 		VARCHAR(100) OUTPUT
AS

DECLARE 	

@DATAINS		CHAR(8),
@APPO_RICEV		CHAR(6),
@ORAINS		CHAR(8),
@STATO_CU		CHAR(1),
@STATO_BOLLO	CHAR(1)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

/*
' ESEGUO I SEGUENTI CONTROLLI 
' 1 - ESISTENZA SERVIZIO BOLLO
' 2 - ESISTENZA SERVIZIO CONTRIBUTO UNIFICATO
*/


/*
CONTROLLO 1
*/
SELECT @STATO_BOLLO = ''
SELECT @STATO_BOLLO = LSRSER_BOLLO_STATO 
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
	AND LSRSER_BOLLO_DATA_DECOR <=
	(
		SELECT MAX(LSRSER_BOLLO_DATA_DECOR) 
		FROM LSRSER_BOLLO
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
		AND LSRSER_BOLLO_DATA_DECOR <= @DATAINS
	)

--SE LO STATO DEL SERVIZIO è 1 O 2 INSERISCO IL RECORD NELLA TABELLA LSRVAR_IND
IF @STATO_BOLLO = '1' OR @STATO_BOLLO = '2'
BEGIN
	-- CONTROLLO CHE NON SIA GIà PRESENTE UN RECORD PER LA RICEVITORIA IN QUESTIONE
	SELECT @APPO_RICEV = ''
	SELECT @APPO_RICEV = LSRVAR_IND_KEY_ID_RICEV
	FROM LSRVAR_IND
	WHERE LSRVAR_IND_KEY_ID_RICEV = @RICEV
		AND LSRVAR_IND_DATA = @DATAINS
		AND LSRVAR_IND_COD_SERV = '05'

 	-- SE IL RECORD C'è FACCIO L'INSERT
	IF @APPO_RICEV = ''
	BEGIN
		INSERT INTO LSRVAR_IND
		VALUES (
			@RICEV,
			@DATAINS,
			'05',
			@INDIRIZZO,
			@CAP,
			@COMUNE,
			@PROVINCIA,
			'00000000'			
			)
	END
	-- ALTRIMENTI AGGIORNO IL RECORD PRESENTE
	ELSE
	BEGIN
		UPDATE LSRVAR_IND
		SET LSRVAR_IND_INDIRIZZO = @INDIRIZZO,
			LSRVAR_IND_CAP = @CAP,
			LSRVAR_IND_COMUNE = @COMUNE,
			LSRVAR_IND_PROVINCIA = @PROVINCIA
		WHERE  LSRVAR_IND_KEY_ID_RICEV = @RICEV
		AND LSRVAR_IND_DATA = @DATAINS
		AND LSRVAR_IND_COD_SERV = '05'
	END
END


/*
CONTROLLO 2
*/
SELECT @STATO_CU = ''
SELECT @STATO_CU = LSRSER_ATTI_STATO 
FROM LSRSER_ATTI
WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEV
	AND LSRSER_ATTI_KEY_CATEGORIA = '05'
	AND LSRSER_ATTI_KEY_SERVIZIO = '01'
	AND LSRSER_ATTI_KEY_ATTIVITA = '01'
	AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'
	AND LSRSER_ATTI_DATA_DECOR <=
	(
		SELECT MAX(LSRSER_ATTI_DATA_DECOR) 
		FROM LSRSER_ATTI
		WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEV
		AND LSRSER_ATTI_KEY_CATEGORIA = '05'
		AND LSRSER_ATTI_KEY_SERVIZIO = '01'
		AND LSRSER_ATTI_KEY_ATTIVITA = '01'
		AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'
		AND LSRSER_ATTI_DATA_DECOR <= @DATAINS
	)

--SE LO STATO DEL SERVIZIO è 1 O 2 INSERISCO IL RECORD NELLA TABELLA LSRVAR_IND
IF @STATO_CU = '1' OR @STATO_CU = '2'
BEGIN
	-- CONTROLLO CHE NON SIA GIà PRESENTE UN RECORD PER LA RICEVITORIA IN QUESTIONE
	SELECT @APPO_RICEV = ''
	SELECT @APPO_RICEV = LSRVAR_IND_KEY_ID_RICEV
	FROM LSRVAR_IND
	WHERE LSRVAR_IND_KEY_ID_RICEV = @RICEV
		AND LSRVAR_IND_DATA = @DATAINS
		AND LSRVAR_IND_COD_SERV = '35'

 	-- SE IL RECORD C'è FACCIO L'INSERT
	IF @APPO_RICEV = ''
	BEGIN
		INSERT INTO LSRVAR_IND
		VALUES (
			@RICEV,
			@DATAINS,
			'35',
			@INDIRIZZO,
			@CAP,
			@COMUNE,
			@PROVINCIA,			
			'00000000'			
			)
	END
	-- ALTRIMENTI AGGIORNO IL RECORD PRESENTE
	ELSE
	BEGIN
		UPDATE LSRVAR_IND
		SET LSRVAR_IND_INDIRIZZO = @INDIRIZZO,
			LSRVAR_IND_CAP = @CAP,
			LSRVAR_IND_COMUNE = @COMUNE,
			LSRVAR_IND_PROVINCIA = @PROVINCIA
		WHERE  LSRVAR_IND_KEY_ID_RICEV = @RICEV
		AND LSRVAR_IND_DATA = @DATAINS
		AND LSRVAR_IND_COD_SERV = '35'
	END
END


IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO VARIAZIONE INDIRIZZO'
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN

	SELECT @MSGERR = '0000 - ' + @RICEV +' OPERAZIONE TERMINATA CORRETTAMENTE'


	COMMIT TRANSACTION
	RETURN
END
GO
