/****** Object:  StoredProcedure [dbo].[ANA_MOVIMENTA_LSRPRO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_MOVIMENTA_LSRPRO]
 
	@CODLTM	 	CHAR(6),
	@DATAINS		CHAR(8),
	@ORAINS		CHAR(8),
	@TIPOPROVV		CHAR(1),
	@DATAPROVV		CHAR(8),
	@NUMPROVV		CHAR(14),
	@CAUSALE		CHAR(40),
	@FIRMA		CHAR(17),
	@EMANATO		CHAR(25),
	@DATADECOR		CHAR(8),
	@NEWOLD		CHAR(3),
	@FDATAINS		CHAR(8) OUTPUT,
	@FORAINS		CHAR(8) OUTPUT,
	@FTIPOPROVV		CHAR(1) OUTPUT,
	@FDATAPROVV	CHAR(8) OUTPUT,
	@FNUMPROVV		CHAR(14) OUTPUT,
	@FDATADECOR	CHAR(8) OUTPUT

AS

DECLARE	

@TASSA		CHAR(9),
@ANNO		CHAR(4),
@MASSIMALE		CHAR(9),
@CODTAB		CHAR(10),
@CHKLTM		VARCHAR(7),
@CHKSTATO		VARCHAR(15),
@MSG			VARCHAR(255)


---------------------------------------------------------------------
--Controllo se esiste un provvedimento con:
-- la stessa data inserimento
-- la stessa ricevitoria
---------------------------------------------------------------------

SELECT @CHKLTM = NULL
SELECT @CHKSTATO = NULL

SELECT @CHKLTM = LSRPRO_KEY_ID_RICEV,
	@CHKSTATO = 
	CASE LSRPRO_KEY_TIPO_REC
		WHEN 'A' THEN 'RIATTIVAZIONE'
		WHEN 'S' THEN 'SOSPENSIONE'
		WHEN 'R' THEN 'REVOCA'
		WHEN 'M' THEN 'SMANTELLAMENTO'
	END
	FROM LSRPRO WHERE
	LSRPRO_KEY_ID_RICEV = @CODLTM AND
	LSRPRO_DATA_INS = @DATAINS AND
	LSRPRO_KEY_TIPO_REC NOT IN ('E', 'I', 'T') AND
	LSRPRO_FLAG_VALIDITA = 'Y'

IF @CHKLTM IS NOT NULL
BEGIN
	SELECT @MSG = "ESISTE GIA' UN PROVVEDIMENTO DI " + @CHKSTATO + " INSERITO OGGI"
	RAISERROR (@MSG, 16, 1)
	RETURN
END


---------------------------------------------------------------------------------------------------------------------------------------------
--CONTROLLO SE ESISTE UN PROVVEDIMENTO NEL FUTURO RISPETTO AD OGGI
---------------------------------------------------------------------------------------------------------------------------------------------

IF @NEWOLD IS NULL OR LTRIM(RTRIM(@NEWOLD)) = ''
BEGIN
	SELECT @CHKLTM = NULL
	SELECT @CHKSTATO = NULL

	SELECT @FTIPOPROVV = NULL
	SELECT @FNUMPROVV = NULL
	SELECT @FDATAPROVV = NULL
	SELECT @FDATADECOR = NULL

	
	SELECT @CHKLTM = LSRPRO_KEY_ID_RICEV, 
		@FDATAINS = LSRPRO_DATA_INS,
		@FORAINS = LSRPRO_ORA_INS,
		@FTIPOPROVV = LSRPRO_KEY_TIPO_REC,
		@FNUMPROVV = LSRPRO_KEY_PROG_PROVV,
		@FDATAPROVV = LSRPRO_KEY_DATA_PROVV,
		@FDATAPROVV = LSRPRO_DECOR_DAL,
		@CHKSTATO = 
		CASE LSRPRO_KEY_TIPO_REC
			WHEN 'A' THEN 'RIATTIVAZIONE'
			WHEN 'S' THEN 'SOSPENSIONE'
			WHEN 'R' THEN 'REVOCA'
			WHEN 'M' THEN 'SMANTELLAMENTO'
		END
		FROM LSRPRO WHERE
		LSRPRO_KEY_ID_RICEV = @CODLTM AND
		LSRPRO_DECOR_DAL > @DATAINS AND
		LSRPRO_KEY_TIPO_REC NOT IN ('E', 'I', 'T') AND
		LSRPRO_FLAG_VALIDITA = 'Y'

	IF @CHKLTM IS NOT NULL
	BEGIN
		SELECT @MSG = '9999 - ESISTE UN PROVVEDIMENTO DI ' + @CHKSTATO + ' CON DECORRENZA FUTURA'
		RAISERROR (@MSG, 16, 1)
		RETURN
	END
END

SELECT @TASSA = LSRPRO_TASSA, @ANNO = LSRPRO_ANNO, @MASSIMALE = LSRPRO_MASSIMALE, @CODTAB = LSRPRO_COD_TAB
FROM LSRPRO
WHERE LSRPRO_KEY_ID_RICEV = @CODLTM
AND LSRPRO_FLAG_VALIDITA = 'Y'
AND LSRPRO_DECOR_DAL = 
	(SELECT MAX (LSRPRO_DECOR_DAL) 
	FROM LSRPRO
	WHERE LSRPRO_KEY_ID_RICEV = @CODLTM
	AND LSRPRO_FLAG_VALIDITA = 'Y'
	AND LSRPRO_DECOR_DAL <= @DATAINS)

IF @NEWOLD = 'OLD' 
BEGIN
	BEGIN TRANSACTION
	-- ACQUISISCO IL NUOVO PROVVEDIMENTO E MANTENGO VALIDO IL PROVVEDIMENTO FUTURO

	INSERT INTO LSRPRO VALUES
	(@CODLTM, @TIPOPROVV, @DATAINS, @ORAINS,
	@DATAPROVV, @NUMPROVV, @CAUSALE, @FIRMA,
	@EMANATO, @DATADECOR, '00000000', @TASSA, @ANNO, @MASSIMALE, @CODTAB,
	'', 'N', '00000000')

	IF @@ERROR <> 0 
	BEGIN
		 
                           SELECT @MSG = 'ERRORE IN ACQUISIZIONE PROVVEDIMENTO'
		ROLLBACK TRANSACTION
		RAISERROR (@MSG, 16, 1)
                           RETURN
                          
             END
END
ELSE IF @NEWOLD = 'NEW'
BEGIN
	BEGIN TRANSACTION
	-- ACQUISISCO IL NUOVO PROVVEDIMENTO E ANNULLO LOGICAMENTE IL PROVVEDIMENTO FUTURO

	INSERT INTO LSRPRO VALUES
	(@CODLTM,@TIPOPROVV,@DATAINS,@ORAINS,
	@DATAPROVV,@NUMPROVV,@CAUSALE,
	@FIRMA,@EMANATO,@DATADECOR,
	'00000000',@TASSA,@ANNO,@MASSIMALE,@CODTAB,
	'','Y','00000000')

	IF @@ERROR <> 0 

	BEGIN
		SELECT @MSG = 'ERRORE IN ACQUISIZIONE PROVVEDIMENTO'
		ROLLBACK TRANSACTION
		RAISERROR (@MSG, 16, 1)
                           RETURN
             END

	UPDATE LSRPRO SET LSRPRO_FLAG_VALIDITA = 'N'	
	WHERE 
	LSRPRO_KEY_ID_RICEV = @CODLTM AND
	LSRPRO_FLAG_VALIDITA = 'Y' AND
	LSRPRO_KEY_TIPO_REC NOT IN ('E', 'I', 'T') AND
	LSRPRO_KEY_DATA_PROVV = @FDATAPROVV AND
	LSRPRO_KEY_PROG_PROVV = @FNUMPROVV
END
ELSE IF @NEWOLD IS NULL OR LTRIM(RTRIM(@NEWOLD)) = ''
BEGIN
	BEGIN TRANSACTION
	-- ACQUISISCO IL NUOVO PROVVEDIMENTO

	INSERT INTO LSRPRO VALUES
	(@CODLTM,@TIPOPROVV,@DATAINS,@ORAINS,
	@DATAPROVV,@NUMPROVV,@CAUSALE,
	@FIRMA,@EMANATO,@DATADECOR,
	'00000000',@TASSA,@ANNO,@MASSIMALE,@CODTAB,
	'','Y','00000000')

	IF @@ERROR <> 0 
	BEGIN
                           SELECT @MSG = 'ERRORE IN ACQUISIZIONE PROVVEDIMENTO'
		ROLLBACK TRANSACTION
		RAISERROR (@MSG, 16, 1)
                           RETURN
             END
END

COMMIT TRANSACTION

RETURN
GO
