/****** Object:  StoredProcedure [dbo].[ANA_MOVIMENTA_BOLLO_DA_LOTTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_MOVIMENTA_BOLLO_DA_LOTTO] 

@RICEVITORIA 	CHAR(6),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATADECOR		CHAR(8),
@DATAPROVV		CHAR(8),
@TIPOPROVV		CHAR(1),
@NUMPROVV		CHAR(8),
@FIRMA		CHAR(17),
@NOTE		VARCHAR(255)

AS

DECLARE	

@ASSOCIAZIONE	CHAR(1),
@STATO		CHAR(1),
@TIPOMOV		CHAR(1),
@NEWSTATO		CHAR(1),
@CANONE		CHAR(1),
@DATAINSLET		CHAR(8),
@ORAINSLET		CHAR(8),
@CODSER		VARCHAR(7),
@MSG			VARCHAR(255),
@MSGERR		VARCHAR(255)


--///////////////////////////////////////////////////////////////////////////////////////
-------------------------------------------------------------------------------------------------------------------------------------------------
--	@TIPOMOV PUO' ASSUMERE I SEGUENTI VALORI:

--	I ---> ADESIONE
--	A ---> ATTIVAZIONE
--	D ---> DISATTIVAZIONE
--	R ---> RIATTIVAZIONE
-------------------------------------------------------------------------------------------------------------------------------------------------
--///////////////////////////////////////////////////////////////////////////////////////

SELECT @MSG = ' - RICEVITORIA: ' + @RICEVITORIA

SELECT @CODSER = '05'

IF @TIPOPROVV IN ('A')
BEGIN
	SELECT @NEWSTATO = '1'
	SELECT @TIPOMOV = 'R'
END
ELSE IF @TIPOPROVV IN ('S', 'R', 'M')
BEGIN
	SELECT @NEWSTATO = '2'
	SELECT @TIPOMOV = 'D'
END


IF @DATAINS IS NULL OR LTRIM(RTRIM(@DATAINS )) = ''
BEGIN
	SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)

	SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
			SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
			SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
			SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)
END

SELECT @DATAINSLET = @DATAINS
SELECT @ORAINSLET = @ORAINS

IF @DATADECOR <= @DATAINS
BEGIN
	SELECT @DATADECOR = CONVERT(CHAR,GETDATE() + 1,112)
END


IF @DATADECOR > CONVERT(CHAR,GETDATE() + 1,112)
BEGIN
	SELECT @DATAINSLET = CONVERT(CHAR,CONVERT(DATETIME,@DATADECOR)-1,112)
	SELECT @ORAINSLET = '00000000'
END


--- TRATTAMENTO SERVIZIO BOLLO

SELECT @CANONE = NULL
SELECT @STATO = NULL
SELECT @ASSOCIAZIONE = NULL

SELECT @ASSOCIAZIONE= LSRSER_BOLLO_ASSOCIAZIONE, @STATO = LSRSER_BOLLO_STATO,
@CANONE = LSRSER_BOLLO_CANONE
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_DATA_DECOR =
(
	SELECT MAX(LSRSER_BOLLO_DATA_DECOR) 
	FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
	AND LSRSER_BOLLO_DATA_DECOR <= @DATAINS
)

--AD OGGI 22-08-2002 UN PROVVEDIMENTO LOTTO PUO' SOLO DISATTIVARE LA BOLLO

IF @STATO IS NOT NULL AND LTRIM(RTRIM(@STATO)) <> ''
BEGIN
	IF @STATO <>  '0' AND @TIPOMOV = 'D'
	BEGIN
		SELECT @NOTE = 'DISATTIVAZIONE PER PROVVEDIMENTO LOTTO N° ' + LTRIM(RTRIM(@NUMPROVV)) + ' DEL ' + @DATAPROVV

		INSERT INTO LSRSER_BOLLO VALUES
		(@RICEVITORIA, @DATAINS, @ORAINS, @NEWSTATO, @DATADECOR, @CANONE,
		@TIPOPROVV, @DATAPROVV, @NUMPROVV, @ASSOCIAZIONE, @FIRMA, @NOTE, '00000000', 'Y')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRSER_BOLLO'
			SELECT @MSGERR = @MSG + ' - ' + @MSGERR
			RAISERROR (@MSGERR, 16, 1)
			RETURN
		END

		UPDATE LSRSER_BOLLO SET
		LSRSER_BOLLO_FLAG_VALIDITA = 'N'
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
		AND LSRSER_BOLLO_DATA_DECOR > @DATAINS
		AND LSRSER_BOLLO_DATA_DECOR <> @DATADECOR

		--SE STO DISATTIVANDO E IL SERVIZIO E' ATTIVO DEVO INVIARE LA LETTERA 
		IF @STATO = '1'
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEVITORIA, @DATAINSLET, @ORAINSLET, @CODSER, @TIPOMOV, @DATADECOR, 'LSRPRO',
			@DATAINS+@ORAINS, '00000000', '', @FIRMA, 'V')

			IF @@ERROR <> 0 
			BEGIN
				SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRLET'
				SELECT @MSGERR = @MSG + ' - ' + @MSGERR
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END

			DELETE FROM LSRLET WHERE
			LSRLET_KEY_ID_RICEV = @RICEVITORIA AND
			LSRLET_COD_SERVIZIO = @CODSER AND
			LSRLET_DECOR_DAL > @DATADECOR

			IF @@ERROR <> 0 
			BEGIN
				SELECT @MSGERR = 'ERRORE IN CANCELLAZIONE RECORD SU LSRLET'
				SELECT @MSGERR = @MSG + ' - ' + @MSGERR
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END
		END
		ELSE
		BEGIN
			--SE STO DISATTIVANDO E IL SERVIZIO E' GIA' DISATTIVO, 
			--NON DEVO INVIARE LA LETTERA PERCHE' LA MOVIMENTAZIONE
			--E' DOVUTA A PROVVEDIMENTO LOTTO
			INSERT INTO LSRLET VALUES
			(@RICEVITORIA, @DATAINSLET, @ORAINSLET, @CODSER, @TIPOMOV, @DATADECOR, 'LSRPRO',
			@DATAINS+@ORAINS, '19000101', '', @FIRMA, 'V')

			IF @@ERROR <> 0 
			BEGIN
				SELECT @MSGERR = @@ERROR
				SELECT @MSGERR = @MSG + ' - ' + @MSGERR
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END
		END
	END
END
GO
