/****** Object:  StoredProcedure [dbo].[ANA_MOVIMENTA_BOLLO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_MOVIMENTA_BOLLO]  

@CODLTM 		CHAR(6),
@TIPOMOV		CHAR(1),
@DATADECOR		CHAR(8),
@CANONE		CHAR(1),
@CHKLOTTO		CHAR(1),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@FIRMA		VARCHAR(17),
@NOTE		VARCHAR(255),
@MSGOUT		VARCHAR(255) OUTPUT


AS

DECLARE 	

@DATAORAINS	CHAR(16),
@CHKRICEV		CHAR(6),
@STATOLOTTO	CHAR(1),
@STATOA		CHAR(1),
@STATOF		CHAR(1),
@DESCSTATO		VARCHAR(15),
@DATADECORF	VARCHAR(25),
@DATADECORA	VARCHAR(25),
@DATAPRIMA		CHAR(8),
@ASSOCIAZIONE	CHAR(1),
@NEWSTATO		CHAR(1),
@CODSER		VARCHAR(7),
@MSG			VARCHAR(255),
@MSGERR		VARCHAR(255)


--/////////////////////////////////////////////////////////////////////////
--------------------------------------------------------------------------------------------------------------------------
-- @CHKLOTTO PUO' ASSUMERE I SEGUENTI VALORI

-- Y ---> DEVO CONTROLLARE LO STATO DEL LOTTO
-- N ---> NON DEVO CONTROLLARE LO STATO DEL LOTTO
--------------------------------------------------------------------------------------------------------------------------
-- @TIPOMOV PUO' ASSUMERE I SEGUENTI VALORI

-- A ---> ATTIVAZIONE
-- D ---> DISATTIVAZIONE
-- R ---> RIATTIVAZIONE
-- S ---> SOSPENSIONE
-- I ---> ADESIONE
--------------------------------------------------------------------------------------------------------------------------
--/////////////////////////////////////////////////////////////////////////


SELECT @MSGOUT = NULL
SELECT @MSG = 'RICEVITORIA ' + @CODLTM + ': - '

IF @CANONE IS NULL OR LTRIM(RTRIM(@CANONE)) = ''
BEGIN
	SELECT @CANONE = NULL
END

IF @CHKLOTTO <> 'Y'
BEGIN
	SELECT @NOTE = 'MOVIMENTAZIONE INDIPENDENTE DA STATO LOTTO'
END

IF @TIPOMOV IN ('A', 'R')
BEGIN
	SELECT @NEWSTATO = '1'
END
ELSE IF @TIPOMOV = 'D'
BEGIN
	SELECT @NEWSTATO = '2'
END
ELSE IF @TIPOMOV = 'I'
BEGIN
	SELECT @NEWSTATO = '0'
END
ELSE IF @TIPOMOV = 'S'
BEGIN
	SELECT @NEWSTATO = '3'
END

SELECT @CODSER = '05'

IF @DATAINS IS NULL OR LTRIM(RTRIM(@DATAINS)) = ''
BEGIN
	SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
	
	SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)
END

IF @DATADECOR IS NULL OR LTRIM(RTRIM(@DATADECOR )) = ''
BEGIN
	SELECT @DATADECOR = CONVERT(CHAR,GETDATE() + 1,112)
END

SELECT @DATAPRIMA = CONVERT(CHAR(8), CONVERT(DATETIME, @DATADECOR) - 1, 112)

/*

--CONTROLLI COMUNI

' 1) - ESISTE LA RICEVITORIA
' 2) - ESISTE LA RICEVITORIA IN LSRSER_BOLLO
' 3) - IL SERVIZIO SIA IN UNO STATO COMPATIBILE CON LA MOVIMENTAZIONE
' 4) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 5) - LO STATO DEL SERVIZIO LOTTO SE RICHIESTO

*/



/*
CONTROLLO 1
*/

SELECT @CHKRICEV = NULL

SELECT DISTINCT @CHKRICEV = LSRRIC_KEY_ID_RICEV 
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @CODLTM

IF @CHKRICEV IS NULL
BEGIN
	SELECT @MSGERR = @MSG + 'INESISTENTE'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN 
END

/*
CONTROLLO 2
*/

SELECT @CHKRICEV = NULL

SELECT DISTINCT @CHKRICEV = LSRSER_BOLLO_KEY_ID_RICEV
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM

IF @CHKRICEV IS NULL
BEGIN
	SELECT @MSGERR = @MSG + 'INESISTENTE SU LSRSER_BOLLO'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END


/*
CONTROLLO 3
*/

SELECT @STATOA = NULL
SELECT @DATADECORA = NULL

SELECT @STATOA = LSRSER_BOLLO_STATO, @ASSOCIAZIONE = LSRSER_BOLLO_ASSOCIAZIONE, 
	@DATADECORA = LSRSER_BOLLO_DATA_DECOR
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_DATA_DECOR =
	(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) 
	FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
	AND LSRSER_BOLLO_DATA_DECOR <= @DATADECOR)


SELECT @DATADECORA = UPPER( SUBSTRING(CONVERT(VARCHAR(25),CONVERT(DATETIME,CONVERT(VARCHAR(25), @DATADECORA,121))), 1, 12))

IF (@STATOA IS NULL OR LTRIM(RTRIM(@STATOA)) = '') AND (@TIPOMOV <> 'I' OR @TIPOMOV <> 'A')
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO NON PRESENTE - OPERAZIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '0' AND (@TIPOMOV = 'S' OR @TIPOMOV = 'D')
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO NON ANCORA ATTIVATO - OPERAZIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '0' AND @TIPOMOV = 'I'
BEGIN
	SELECT @MSGERR = @MSG + ' PRESENTE ADESIONE DEL ' + @DATADECORA + ' - ADESIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '0' AND @TIPOMOV = 'R'
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO NON ANCORA ATTIVATO - RIATTIVAZIONE  NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '1' AND (@TIPOMOV = 'A' OR @TIPOMOV = 'R' OR @TIPOMOV = 'I')
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO ATTIVATO IL ' + @DATADECORA + ' - OPERAZIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '2' AND @TIPOMOV = 'D'
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO DISATTIVATO IL ' + @DATADECORA + ' - DISATTIVAZIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '2' AND @TIPOMOV = 'A'
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO DISATTIVATO IL ' + @DATADECORA + ' - ATTIVAZIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '2' AND @TIPOMOV = 'S'
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO DISATTIVATO IL ' + @DATADECORA + ' - SOSPENSIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '2' AND @TIPOMOV = 'I'
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO DISATTIVATO IL ' + @DATADECORA + ' - ADESIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '3' AND @TIPOMOV = 'A'
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO SOSPESO IL ' + @DATADECORA + ' - ATTIVAZIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END
ELSE IF @STATOA = '3' AND @TIPOMOV = 'S'
BEGIN
	SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO SOSPESO IL ' + @DATADECORA + ' - SOSPENSIONE NON ESEGUITA'
	SELECT @MSGOUT = '1111 - ' + @MSGERR
	RETURN
END

/*
CONTROLLO 4
*/

SELECT @STATOF = NULL
SELECT @DATADECORF = NULL

SELECT @DATADECORF = LSRSER_BOLLO_DATA_DECOR, @STATOF = LSRSER_BOLLO_STATO,
@DESCSTATO = CASE LSRSER_BOLLO_STATO
	WHEN '0' THEN 'NON ATTIVATO'
	WHEN '1' THEN 'ATTIVATO'
	WHEN '2' THEN 'DISATTIVATO'
	WHEN '3' THEN 'SOSPESO'
	ELSE 'NON PRESENTE'
END
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @CODLTM
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_DATA_DECOR = @DATADECOR


IF @STATOF IS NOT NULL OR LTRIM(RTRIM(@STATOF)) = ''
BEGIN
	SELECT @DATADECORF = UPPER( SUBSTRING(CONVERT(VARCHAR(25),CONVERT(DATETIME,CONVERT(VARCHAR(25), @DATADECORF,121))), 1, 12))

	IF @STATOF = '0'
	BEGIN
		SELECT @MSGERR = @MSG + ' ADESIONE PRESENTE ALLA DATA ' + @DATADECORF + ' OPERAZIONE NON ESEGUITA'
		SELECT @MSGOUT = '1111 - ' + @MSGERR
		RETURN
	END
	ELSE IF @STATOF = '1'
	BEGIN
		SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO ATTIVO ALLA DATA ' + @DATADECORF + ' OPERAZIONE NON ESEGUITA'
		SELECT @MSGOUT = '1111 - ' + @MSGERR
		RETURN
	END
	ELSE IF @STATOF = '2'
	BEGIN
		SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO DISATTIVO ALLA DATA ' + @DATADECORF + ' OPERAZIONE NON ESEGUITA'
		SELECT @MSGOUT = '1111 - ' + @MSGERR
		RETURN
	END
	ELSE IF @STATOF = '3'
	BEGIN
		SELECT @MSGERR = @MSG + ' SERVIZIO BOLLO SOSPESO ALLA DATA ' + @DATADECORF + ' OPERAZIONE NON ESEGUITA'
		SELECT @MSGOUT = '1111 - ' + @MSGERR
		RETURN
	END
END

/*
CONTROLLO 5
*/

IF @CHKLOTTO = 'Y'
BEGIN
	SELECT @STATOLOTTO = NULL

	SELECT @STATOLOTTO = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
	AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
	AND LSRSER_LOTTO_DATA_DECOR =
		(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
		WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
		AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
		AND LSRSER_LOTTO_DATA_DECOR <= @DATADECOR)
	
	IF (@STATOLOTTO = 'S' OR @STATOLOTTO = 'M' OR @STATOLOTTO = 'R' OR LTRIM(RTRIM(@STATOLOTTO)) = '') AND @TIPOMOV <> 'I'
	BEGIN
		SELECT @MSGERR = @MSG + ' LOTTO SOSPESO/REVOCATO/NON ATTIVATO'
		SELECT @MSGOUT = '1111 - ' + @MSGERR
		RETURN
	END
END

SELECT @DATAORAINS = NULL

SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
				FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @CODLTM
				AND LSRLET_COD_SERVIZIO = @CODSER
				AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
				AND LSRLET_KEY_DATA_INS = @DATAINS
				AND LSRLET_DECOR_DAL = '00000000'

BEGIN TRANSACTION

IF @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATADECOR
	WHERE LSRLET_KEY_ID_RICEV = @CODLTM
	AND LSRLET_KEY_DATA_INS + LSRLET_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_COD_SERVIZIO = @CODSER
	AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSGERR = 'ERRORE IN AGGIORNAMENTO RECORD SU LSRLET'
		SELECT @MSGERR = @MSG + ' - ' + @MSGERR
		RAISERROR (@MSGERR, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END
END
ELSE
BEGIN

	IF (@STATOA IS NULL OR LTRIM(RTRIM(@STATOA)) = '') AND @TIPOMOV = 'A'
	BEGIN
		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINS, @ORAINS, @CODSER, 'I', @DATAPRIMA, '', '', '00000000', @NOTE, @FIRMA, 'V')
	
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRLET'
			SELECT @MSGERR = @MSG + ' - ' + @MSGERR
			RAISERROR (@MSGERR, 16, 1)
			ROLLBACK TRANSACTION
			RETURN
		END
	END

	INSERT INTO LSRLET VALUES
	(@CODLTM, @DATAINS, @ORAINS, @CODSER, @TIPOMOV, @DATADECOR, '', '', '00000000', @NOTE, @FIRMA, 'V')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRLET'
		SELECT @MSGERR = @MSG + ' - ' + @MSGERR
		RAISERROR (@MSGERR, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END
END

IF (@STATOA IS NULL OR LTRIM(RTRIM(@STATOA)) = '') AND @TIPOMOV = 'A'
BEGIN
	INSERT INTO LSRSER_BOLLO VALUES 
	(@CODLTM, @DATAINS, @ORAINS, '0', @DATAPRIMA, @CANONE,
	NULL, NULL, NULL, @ASSOCIAZIONE, @FIRMA, @NOTE, '00000000', 'Y')
	
	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRSER_BOLLO'
		SELECT @MSGERR = @MSG + ' - ' + @MSGERR
		RAISERROR (@MSGERR, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END
END

INSERT INTO LSRSER_BOLLO VALUES 
(@CODLTM, @DATAINS, @ORAINS, @NEWSTATO, @DATADECOR,
@CANONE, NULL, NULL, NULL, @ASSOCIAZIONE, @FIRMA, @NOTE, '00000000', 'Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = 'ERRORE IN INSERIMENTO RECORD SU LSRSER_BOLLO'
	SELECT @MSGERR = @MSG + ' - ' + @MSGERR
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


COMMIT TRANSACTION
GO
