/****** Object:  StoredProcedure [dbo].[ANA_MOVIMENTA_LIS_DA_LOTTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_MOVIMENTA_LIS_DA_LOTTO] 

@CODLTM	 	CHAR(6),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATADECOR		CHAR(8),
@DATAPROVV		CHAR(8),
@TIPOPROVV		CHAR(1),
@NUMPROVV		CHAR(8),
@FIRMA		CHAR(17),
@NOTE		VARCHAR(255)


AS


DECLARE 

@MSGERR		VARCHAR(255),
@CATEGORIA		CHAR(2),
@SERVIZIO		CHAR(2),
@ATTIVITA		CHAR(2)


BEGIN TRANSACTION

DECLARE CUR_LIS SCROLL CURSOR FOR

SELECT  LSRSER_LIS_DEC_CATEGORIA,   LSRSER_LIS_DEC_SERVIZIO,  LSRSER_LIS_DEC_ATTIVITA  
FROM LSRSER_LIS_DEC A 
WHERE LSRSER_LIS_DEC_SERVIZIO <>''
AND NOT EXISTS ( 
	SELECT * FROM LSRSER_LIS_DEC 
 	WHERE A.LSRSER_LIS_DEC_CATEGORIA = LSRSER_LIS_DEC_CATEGORIA
 		AND A.LSRSER_LIS_DEC_SERVIZIO = LSRSER_LIS_DEC_SERVIZIO
 		AND LSRSER_LIS_DEC_ATTIVITA <> ''
	)
UNION
SELECT  LSRSER_LIS_DEC_CATEGORIA,  LSRSER_LIS_DEC_SERVIZIO,  LSRSER_LIS_DEC_ATTIVITA  
FROM LSRSER_LIS_DEC 
WHERE LSRSER_LIS_DEC_CATEGORIA <> ''
	AND LSRSER_LIS_DEC_SERVIZIO <> ''
	AND LSRSER_LIS_DEC_ATTIVITA <> ''

OPEN CUR_LIS
FETCH NEXT FROM CUR_LIS
INTO @CATEGORIA, @SERVIZIO, @ATTIVITA

WHILE @@FETCH_STATUS = 0 
BEGIN
	IF @CATEGORIA = '01'
	BEGIN
		EXEC ANA_MOVIMENTA_RICARICHE_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@CATEGORIA,
			@SERVIZIO,
			@ATTIVITA,
			@DATADECOR,
			@TIPOPROVV,
			@DATAPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'EERORE IN ESECUZIONE S.P. ANA_MOVIMENTA_RICARICHE_DA_LOTTO - RICEVITORIA ' + @CODLTM
			ROLLBACK TRANSACTION
			RAISERROR (@MSGERR, 16, 1)
			RETURN
		END
	END

	IF @CATEGORIA = '02'
	BEGIN
		EXEC ANA_MOVIMENTA_COMUNI_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@CATEGORIA,
			@SERVIZIO,
			@ATTIVITA,
			@DATADECOR,
			@TIPOPROVV,
			@DATAPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'EERORE IN ESECUZIONE S.P. ANA_MOVIMENTA_COMUNI_DA_LOTTO - RICEVITORIA ' + @CODLTM
			ROLLBACK TRANSACTION
			RAISERROR (@MSGERR, 16, 1)
			RETURN
		END

	END

	IF @CATEGORIA = '03'
	BEGIN
		EXEC ANA_MOVIMENTA_CANONE_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@CATEGORIA,
			@SERVIZIO,
			@ATTIVITA,
			@DATADECOR,
			@TIPOPROVV,
			@DATAPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'EERORE IN ESECUZIONE S.P. ANA_MOVIMENTA_PAGAMENTI_DA_LOTTO - RICEVITORIA ' + @CODLTM
			ROLLBACK TRANSACTION
			RAISERROR (@MSGERR, 16, 1)
			RETURN
		END

	END

	IF @CATEGORIA = '04'
	BEGIN
		EXEC ANA_MOVIMENTA_BIGLIETTERIA_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@CATEGORIA,
			@SERVIZIO,
			@ATTIVITA,
			@DATADECOR,
			@TIPOPROVV,
			@DATAPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'EERORE IN ESECUZIONE S.P. ANA_MOVIMENTA_BIGLIETTERIA_DA_LOTTO - RICEVITORIA ' + @CODLTM
			ROLLBACK TRANSACTION
			RAISERROR (@MSGERR, 16, 1)
			RETURN
		END

	END

	IF @CATEGORIA = '05'
	BEGIN
		EXEC ANA_MOVIMENTA_CONTRIBUTO_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@CATEGORIA,
			@SERVIZIO,
			@ATTIVITA,
			@DATADECOR,
			@TIPOPROVV,
			@DATAPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'EERORE IN ESECUZIONE S.P. ANA_MOVIMENTA_CONTRIBUTO_DA_LOTTO - RICEVITORIA ' + @CODLTM
			ROLLBACK TRANSACTION
			RAISERROR (@MSGERR, 16, 1)
			RETURN
		END

	END

	FETCH NEXT FROM CUR_LIS
	INTO @CATEGORIA, @SERVIZIO, @ATTIVITA
END

CLOSE CUR_LIS
DEALLOCATE CUR_LIS

COMMIT TRANSACTION
GO
