/****** Object:  StoredProcedure [dbo].[CREA_LSR1APP]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE     PROCEDURE [dbo].[CREA_LSR1APP]  AS

DECLARE   	

@IERI 			CHAR(8),
@OGGI 		CHAR(8),
@DATAINS 		CHAR(8),
@RICEVITORIA 	CHAR(6),
@RICEVITORIAD 	CHAR(6),
@RICEVITORIAB 	CHAR(6),
@CODAMM 		CHAR(6),
@DATADECOR 	CHAR(8),
@DECORDAL 		CHAR(8),
@DATAATTIV 		CHAR(8),
@DATACESSAZ 	CHAR(8),
@DECODRICEV 	CHAR(50),
@COMUNERICEV 	CHAR(24),
@PROVRICEV 		CHAR(2),
@CAPRICEV 		CHAR(5),
@INDIRIZZORICEV 	CHAR(40),
@COGNOME 		CHAR(24),
@NOME 		CHAR(20),
@STATORICEV 	CHAR(1),
@STATOLOTTO 	CHAR(1),
@STATOBOLLO 	CHAR(1),
@STATOTRIS 		CHAR(1),
@STATOF101 		CHAR(1),
@STATOSERTEL 	CHAR(1),
@STATOBIG 		CHAR(1),
@STATOCOMUNE 	CHAR(1),
@STATORAI 		CHAR(1),
@STATOGEV 		CHAR(1),
@STATOCONI		CHAR(1),
@STATOST		CHAR(1),
@STATOST_SI		CHAR(1),

@TELRICEV 		CHAR(12),
@TELTIT 		CHAR(12),
@SIGLAIC 		CHAR(2),
@SIGLAREG 		CHAR(2),
@CHIUSURARICEV 		CHAR(1),
@SPECIALERICEV 		CHAR(1),
@CODMAGAZ 		CHAR(5),
@IDTAB 			CHAR(4),
@ASSORICEV 		CHAR(1),
@DATARIATTIV 		CHAR(8),
@FLAGESE 		CHAR(1),
@TESTO 			VARCHAR(300),
@NUMTERM 		CHAR(2),
@TERMINST 		CHAR(1),
@MODULO 		CHAR(1),
@FLAGCOMM 		CHAR(1),
@TABRIC 		CHAR(1),
@TABTIT 		CHAR(1),
@TABLOTTO 		CHAR(1),
@TABF101 		CHAR(1),
@TABRAI 		CHAR(1),
@TABINFO 		CHAR(1),
@TABBOLLO 		CHAR(1),
@TABBIG 		CHAR(1),
@TABCOMUNE 		CHAR(1),
@TABTRIS 		CHAR(1),
@TABGEV 		CHAR(1),
@TABCONI		CHAR(1),
@TABST			CHAR(1),
@FLGANN			CHAR(1),
@MSGERR 		VARCHAR(100),
@NOMEJOB		VARCHAR(25)


SELECT @NOMEJOB = 'AAEG012001UC'

SELECT @STATOLOTTO = '0'
SELECT @STATOBOLLO = '0'
SELECT @STATOTRIS = '0'
SELECT @STATOF101 = '0'
SELECT @STATOSERTEL = '0'
SELECT @STATORAI = '0'
SELECT @STATOCOMUNE = '0'
SELECT @STATOBIG = '0'
SELECT @STATOGEV = '0'
SELECT @STATOCONI = '0'
SELECT @STATOST = '0'

SELECT @OGGI = CONVERT(CHAR(8), GETDATE(), 112)

SELECT @IERI = CONVERT(CHAR(8), GETDATE() - 1, 112)


--EXEC CREA_LSRFLAG
DELETE FROM LSR1APP
--***************************************************************************
--* DICHIARAZIONE DEL CURSORE RELATIVO ALLE RICEVITORIE
--***************************************************************************
DECLARE CUR_FLAG CURSOR FOR 
SELECT * 
FROM LSRFLAG
OPEN CUR_FLAG
FETCH NEXT FROM CUR_FLAG INTO 
	@RICEVITORIAB,@TABRIC,@TABTIT,@TABLOTTO,
	@TABF101,@TABRAI,@TABINFO,@TABBOLLO,
	@TABBIG,@TABCOMUNE,@TABTRIS,@TABGEV,@TABCONI,@TABST

IF @@FETCH_STATUS <> 0
BEGIN
	SELECT @MSGERR = 'NESSUNA MOVIMENTAZIONE ANAGRAFICA'

	EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0

	CLOSE CUR_FLAG
	DEALLOCATE CUR_FLAG
	RETURN
END
ELSE
WHILE @@FETCH_STATUS = 0 
BEGIN
--=========================================================================
IF @TABRIC IS NOT NULL
BEGIN
	SELECT	@RICEVITORIA=LSRRIC_KEY_ID_RICEV,
			@CODAMM=LSRRIC_COD_AMM,
			@DECODRICEV=LSRRIC_DECOD_RICEV,
			@COMUNERICEV=LSRRIC_COMUNE_RICEV,
			@PROVRICEV=LSRRIC_PROV_RICEV,
			@CAPRICEV=LSRRIC_CAP,
			@INDIRIZZORICEV=LSRRIC_INDIRIZZO,
			@TELRICEV=LSRRIC_TEL_RICEVITORIA,
			@SIGLAIC=LSRRIC_SIGLA_IC,
			@SIGLAREG=LSRRIC_SIGLA_REG,
			@CHIUSURARICEV=LSRRIC_CHIUSURA,
			@SPECIALERICEV=LSRRIC_TAB_SPECIALI,
			@CODMAGAZ=LSRRIC_CODICE_MAGAZZINO,
			@FLAGESE=LSRRIC_FLAG_ESERCIZIO,
			@NUMTERM=LSRRIC_NUM_TERMINALI,
			@IDTAB=LSRRIC_ID_TAB
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
		(SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) 
		FROM LSRRIC 
		WHERE LSRRIC_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRRIC_DATA_VALIDITA <= @OGGI
		AND LSRRIC_KEY_DATA_INS =  @IERI)
		OR LSRRIC_DATA_VALIDITA =  @OGGI)
		AND LSRRIC_FLAG_VALIDITA = 'Y')
	AND LSRRIC_FLAG_VALIDITA = 'Y'
END
ELSE
BEGIN
	SELECT	@RICEVITORIA=LSRRIC_KEY_ID_RICEV,
			@CODAMM=LSRRIC_COD_AMM,
			@DECODRICEV=LSRRIC_DECOD_RICEV,
			@COMUNERICEV=LSRRIC_COMUNE_RICEV,
			@PROVRICEV=LSRRIC_PROV_RICEV,
			@CAPRICEV=LSRRIC_CAP,
			@INDIRIZZORICEV=LSRRIC_INDIRIZZO,
			@TELRICEV=LSRRIC_TEL_RICEVITORIA,

			@SIGLAIC=LSRRIC_SIGLA_IC,
			@SIGLAREG=LSRRIC_SIGLA_REG,
			@CHIUSURARICEV=LSRRIC_CHIUSURA,
			@SPECIALERICEV=LSRRIC_TAB_SPECIALI,
			@CODMAGAZ=LSRRIC_CODICE_MAGAZZINO,

			@FLAGESE=LSRRIC_FLAG_ESERCIZIO,
			@NUMTERM=LSRRIC_NUM_TERMINALI,
			@IDTAB=LSRRIC_ID_TAB
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
		(SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) FROM LSRRIC 
		WHERE LSRRIC_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRRIC_DATA_VALIDITA <= @OGGI
		AND LSRRIC_FLAG_VALIDITA = 'Y')
	AND LSRRIC_FLAG_VALIDITA = 'Y'
END
--=========================================================================
IF @TABTIT IS NOT NULL
BEGIN
	SELECT 	@COGNOME=LSRTIT_COGNOME,
			@NOME=LSRTIT_NOME,
			@TELTIT=LSRTIT_TELEFONO
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
		(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) FROM LSRTIT
		WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRTIT_DATA_VALIDITA <= @OGGI
		AND LSRTIT_KEY_DATA_INS =  @IERI)
		OR LSRTIT_DATA_VALIDITA =  @OGGI)
		AND LSRTIT_TIPO = 'T'
		AND LSRTIT_FLAG_VALIDITA = 'Y')
	AND LSRTIT_FLAG_VALIDITA = 'Y'
	AND LSRTIT_TIPO = 'T'
END
ELSE
BEGIN
	SELECT 	@COGNOME=LSRTIT_COGNOME,
			@NOME=LSRTIT_NOME,
			@TELTIT=LSRTIT_TELEFONO
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
		(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) FROM LSRTIT
		WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRTIT_DATA_VALIDITA <= @OGGI
		AND LSRTIT_TIPO = 'T'
		AND LSRTIT_FLAG_VALIDITA = 'Y')
	AND LSRTIT_FLAG_VALIDITA = 'Y'
	AND LSRTIT_TIPO = 'T'
END
--=========================================================================
-- MODIFICA DEL 15/09/2006
-- AGGIUNTA PULITURA VARIABILI
SELECT 	@STATORICEV = ''
SELECT	@DATADECOR = ''
SELECT	@ASSORICEV = ''

IF @TABLOTTO IS NOT NULL
BEGIN
	SELECT 	@STATORICEV = LSRSER_LOTTO_TIPO_PROVV,
			@DATADECOR = LSRSER_LOTTO_DATA_DECOR,
			@ASSORICEV = LSRSER_LOTTO_ASSOCIAZIONE
	FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_LOTTO_DATA_DECOR) = 
		(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
		WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_LOTTO_DATA_DECOR <= @OGGI
		AND LSRSER_LOTTO_KEY_DATA_INS =  @IERI)
		OR LSRSER_LOTTO_DATA_DECOR =  @OGGI)
		AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y')
	AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
END
ELSE
BEGIN
	SELECT 	@STATORICEV = LSRSER_LOTTO_TIPO_PROVV,
			@DATADECOR = LSRSER_LOTTO_DATA_DECOR,
			@ASSORICEV = LSRSER_LOTTO_ASSOCIAZIONE
	FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_LOTTO_DATA_DECOR) = 
		(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
		WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_LOTTO_DATA_DECOR <= @OGGI
		AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y')
	AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
END

IF @STATORICEV = 'A' 
BEGIN
	SELECT @DATAATTIV = @DATADECOR
	SELECT @DATACESSAZ = '00000000'
	SELECT @DATARIATTIV = '00000000'
	SELECT @STATOLOTTO = '1'
END
ELSE IF @STATORICEV = 'S' OR @STATORICEV = 'R' OR @STATORICEV = 'M' 
BEGIN
	SELECT @DATAATTIV = '00000000'
	SELECT @DATACESSAZ = @DATADECOR
	SELECT @DATARIATTIV = '00000000'
	SELECT @STATOLOTTO = '2'
END
ELSE
--MODIFICA DEL 09/08/2001 PER LE RICEVITORIE CHE HANNO SOLO LA CONCESSIONE
BEGIN

	SELECT @DATAATTIV = '00000000'
	SELECT @DATACESSAZ = '00000000'
	SELECT @DATARIATTIV = '00000000'
	SELECT @STATOLOTTO = '0'

	SELECT @FLGANN = NULL

	SELECT @FLGANN = LSRPRO_FLAG_ANNUL, @DATADECOR = LSRPRO_DECOR_DAL
	FROM LSRPRO A
	WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIAB
	AND LSRPRO_KEY_TIPO_REC = 'C'
	AND LSRPRO_FLAG_VALIDITA = 'Y'
	AND LSRPRO_DECOR_DAL =
		(SELECT MAX(LSRPRO_DECOR_DAL) 
		FROM LSRPRO B
		WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRPRO_KEY_TIPO_REC = 'C'
		AND LSRPRO_FLAG_VALIDITA = 'Y'
		AND LSRPRO_DECOR_DAL <= @OGGI)

	IF @FLGANN = '1'
	BEGIN
		SELECT @DATAATTIV = '00000000'
		SELECT @DATACESSAZ = @DATADECOR
		SELECT @DATARIATTIV = '00000000'
		SELECT @STATOLOTTO = '0'
	END

END 


--=========================================================================
-- ************* MODIFICA DEL 14/08/2001 ************* 
-- LA DATA LSR01A_DATA_VAL_PROVV DEVE ESSERE VALORIZZATA CON
-- LA DATA DECORRENZA DELL'EVENTUALE PROVVEDIMENTO DI TIPO I 
-- SE TALE PROVVEDIMENTO NON ESISTE, DEVE ESSERE VALORIZZATA CON 00000000
SELECT @DECORDAL = '00000000'
SELECT @DECORDAL = LSRPRO_DECOR_DAL 
FROM LSRPRO
WHERE (LSRPRO_DECOR_DAL = (@OGGI) 
	OR (LSRPRO_DECOR_DAL <= @OGGI AND
	LSRPRO_DATA_INS = @IERI))
	AND LSRPRO_KEY_TIPO_REC IN ('I')
AND LSRPRO_FT_VOS = '00000000'
AND LSRPRO_FLAG_VALIDITA = 'Y'
AND LSRPRO_KEY_ID_RICEV= @RICEVITORIAB

--=========================================================================================================
--CDS: MODIFICA DEL 27/06/2007
--SOSTITUITO LSRSER_F101 CON LSRSER_GP, MA LA VARIABILE SI CHIAMA SEMPRE @STATOF101 !!!!!!!!!!!!!!!!!!!!!!!
--=========================================================================================================
SELECT @STATOF101 = '0'

IF @TABF101 IS NOT NULL
BEGIN
	SELECT @STATOF101 = LSRSER_GP_STATO
	FROM LSRSER_GP
	WHERE LSRSER_GP_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_GP_DATA_DECOR) = 
		(SELECT MAX(LSRSER_GP_DATA_DECOR) FROM LSRSER_GP
		WHERE LSRSER_GP_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_GP_DATA_DECOR <= @OGGI
		AND LSRSER_GP_KEY_DATA_INS =  @IERI)
		OR LSRSER_GP_DATA_DECOR =  @OGGI)
		AND LSRSER_GP_FLAG_VALIDITA = 'Y')
	AND LSRSER_GP_FLAG_VALIDITA = 'Y'
END
ELSE
BEGIN
	SELECT @STATOF101 = LSRSER_GP_STATO
	FROM LSRSER_GP
	WHERE LSRSER_GP_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_GP_DATA_DECOR) = 
		(SELECT MAX(LSRSER_GP_DATA_DECOR) FROM LSRSER_GP
		WHERE LSRSER_GP_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_GP_DATA_DECOR <= @OGGI
		AND LSRSER_GP_FLAG_VALIDITA = 'Y')
	AND LSRSER_GP_FLAG_VALIDITA = 'Y'
END
--=========================================================================
/*
IF @TABRAI IS NOT NULL
BEGIN
	SELECT @STATORAI = LSRSER_RAI_STATO
	FROM LSRSER_RAI
	WHERE LSRSER_RAI_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_RAI_DATA_DECOR) = 
		(SELECT MAX(LSRSER_RAI_DATA_DECOR) FROM LSRSER_RAI
		WHERE LSRSER_RAI_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_RAI_DATA_DECOR <= @OGGI
		AND LSRSER_RAI_KEY_DATA_INS =  @IERI)
		OR LSRSER_RAI_DATA_DECOR =  @OGGI)
		AND LSRSER_RAI_FLAG_VALIDITA = 'Y')
	AND LSRSER_RAI_FLAG_VALIDITA = 'Y'
END
ELSE
BEGIN
	SELECT @STATORAI = LSRSER_RAI_STATO
	FROM LSRSER_RAI
	WHERE LSRSER_RAI_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_RAI_DATA_DECOR) = 
		(SELECT MAX(LSRSER_RAI_DATA_DECOR) FROM LSRSER_RAI
		WHERE LSRSER_RAI_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_RAI_DATA_DECOR <= @OGGI
		AND LSRSER_RAI_FLAG_VALIDITA = 'Y')
	AND LSRSER_RAI_FLAG_VALIDITA = 'Y'
END

--=========================================================================

IF @TABINFO IS NOT NULL
BEGIN
	SELECT @STATOSERTEL = LSRSER_INFO_STATO
	FROM LSRSER_INFO
	WHERE LSRSER_INFO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_INFO_DATA_DECOR) = 
		(SELECT MAX(LSRSER_INFO_DATA_DECOR) FROM LSRSER_INFO
		WHERE LSRSER_INFO_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_INFO_DATA_DECOR <= @OGGI
		AND LSRSER_INFO_KEY_DATA_INS =  @IERI)
		OR LSRSER_INFO_DATA_DECOR =  @OGGI)
		AND LSRSER_INFO_FLAG_VALIDITA = 'Y')
	AND LSRSER_INFO_FLAG_VALIDITA = 'Y'
END
ELSE
BEGIN
	SELECT @STATOSERTEL = LSRSER_INFO_STATO
	FROM LSRSER_INFO
	WHERE LSRSER_INFO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_INFO_DATA_DECOR) = 
		(SELECT MAX(LSRSER_INFO_DATA_DECOR) FROM LSRSER_INFO
		WHERE LSRSER_INFO_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_INFO_DATA_DECOR <= @OGGI
		AND LSRSER_INFO_FLAG_VALIDITA = 'Y')
	AND LSRSER_INFO_FLAG_VALIDITA = 'Y'
END
*/

--=========================================================================
SELECT @STATOBOLLO = '0'

IF @TABBOLLO IS NOT NULL
BEGIN
	SELECT @STATOBOLLO = LSRSER_BOLLO_STATO
	FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_BOLLO_DATA_DECOR) = 
		(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_BOLLO_DATA_DECOR <= @OGGI
		AND LSRSER_BOLLO_KEY_DATA_INS =  @IERI)
		OR LSRSER_BOLLO_DATA_DECOR =  @OGGI)
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y')
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
END
ELSE
BEGIN
	SELECT @STATOBOLLO = LSRSER_BOLLO_STATO
	FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_BOLLO_DATA_DECOR) = 
		(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_BOLLO_DATA_DECOR <= @OGGI
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y')
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
END


--=========================================================================
SELECT @STATOTRIS = '0'
IF @TABTRIS IS NOT NULL
BEGIN
	SELECT @STATOTRIS = LSRSER_TRIS_STATO
	FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_TRIS_DATA_DECOR) = 
		(SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS
		WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_TRIS_DATA_DECOR <= @OGGI
		AND LSRSER_TRIS_KEY_DATA_INS =  @IERI)
		OR LSRSER_TRIS_DATA_DECOR =  @OGGI)
		AND LSRSER_TRIS_FLAG_VALIDITA = 'Y')
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'  
END
ELSE
BEGIN
	SELECT @STATOTRIS = LSRSER_TRIS_STATO
	FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_TRIS_DATA_DECOR) = 
		(SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS
		WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_TRIS_DATA_DECOR <= @OGGI
		AND LSRSER_TRIS_FLAG_VALIDITA = 'Y')
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
END

--=========================================================================
SELECT @STATOCONI = '0'

IF @TABCONI IS NOT NULL
BEGIN
	SELECT @STATOCONI = LSRSER_CONI_STATO
	FROM LSRSER_CONI
	WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_CONI_DATA_DECOR) = 
		(SELECT MAX(LSRSER_CONI_DATA_DECOR) FROM LSRSER_CONI
		WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_CONI_DATA_DECOR <= @OGGI
		AND LSRSER_CONI_KEY_DATA_INS =  @IERI)
		OR LSRSER_CONI_DATA_DECOR =  @OGGI)
		AND LSRSER_CONI_FLAG_VALIDITA = 'Y')
	AND LSRSER_CONI_FLAG_VALIDITA = 'Y'  

/*
	SELECT  @STATOCONI = LSRSER_CONI_STATO
	FROM LSRSER_CONI
	WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_CONI_DATA_DECOR) = 
		(SELECT MAX(LSRSER_CONI_DATA_DECOR) FROM LSRSER_CONI
		WHERE LSRSER_CONI_KEY_ID_RICEV =  @RICEVITORIAB
		AND ((LSRSER_CONI_DATA_DECOR <= @OGGI
		AND LSRSER_CONI_KEY_DATA_INS =  @IERI)
		OR LSRSER_CONI_DATA_DECOR =  @OGGI)
		AND LSRSER_CONI_FLAG_VALIDITA = 'Y')
	AND(LSRSER_CONI_KEY_ORA_INS) = 
		(SELECT MAX(LSRSER_CONI_KEY_ORA_INS) FROM LSRSER_CONI
		WHERE LSRSER_CONI_KEY_ID_RICEV =  @RICEVITORIAB
		AND ((LSRSER_CONI_DATA_DECOR <= @OGGI
		AND LSRSER_CONI_KEY_DATA_INS = @IERI)
		OR LSRSER_CONI_DATA_DECOR =  @OGGI)
		AND LSRSER_CONI_FLAG_VALIDITA = 'Y')
	AND LSRSER_CONI_FLAG_VALIDITA = 'Y'  

*/

END
ELSE
BEGIN
	SELECT @STATOCONI = LSRSER_CONI_STATO
	FROM LSRSER_CONI
	WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_CONI_DATA_DECOR) = 
		(SELECT MAX(LSRSER_CONI_DATA_DECOR) FROM LSRSER_CONI
		WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_CONI_DATA_DECOR <= @OGGI
		AND LSRSER_CONI_FLAG_VALIDITA = 'Y')
	AND LSRSER_CONI_FLAG_VALIDITA = 'Y' 
END

--=========================================================================
SELECT @STATOST = '0'

IF @TABST IS NOT NULL
BEGIN
	SELECT @STATOST = LSRSER_ST_STATO
	FROM LSRSER_ST
	WHERE LSRSER_ST_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_ST_DATA_DECOR) = 
		(SELECT MAX(LSRSER_ST_DATA_DECOR) FROM LSRSER_ST
		WHERE LSRSER_ST_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_ST_DATA_DECOR <= @OGGI
		AND LSRSER_ST_KEY_DATA_INS =  @IERI)
		OR LSRSER_ST_DATA_DECOR =  @OGGI)
		AND LSRSER_ST_FLAG_VALIDITA = 'Y')
	AND LSRSER_ST_FLAG_VALIDITA = 'Y'  

END
ELSE
BEGIN
	SELECT @STATOST = LSRSER_ST_STATO
	FROM LSRSER_ST
	WHERE LSRSER_ST_KEY_ID_RICEV = @RICEVITORIAB

	AND(LSRSER_ST_DATA_DECOR) = 
		(SELECT MAX(LSRSER_ST_DATA_DECOR) FROM LSRSER_ST
		WHERE LSRSER_ST_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_ST_DATA_DECOR <= @OGGI
		AND LSRSER_ST_FLAG_VALIDITA = 'Y')
	AND LSRSER_ST_FLAG_VALIDITA = 'Y' 
END


--=========================================================================
SELECT @STATOGEV = '0'

IF @TABGEV IS NOT NULL
BEGIN
	SELECT @STATOGEV = LSRSER_GEV_STATO
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_GEV_DATA_DECOR) = 
		(SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV
		WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_GEV_DATA_DECOR <= @OGGI
		AND LSRSER_GEV_KEY_DATA_INS =  @IERI)
		OR LSRSER_GEV_DATA_DECOR =  @OGGI)
		AND LSRSER_GEV_FLAG_VALIDITA = 'Y')
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'  


END
ELSE
BEGIN
	SELECT @STATOGEV = LSRSER_GEV_STATO
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_GEV_DATA_DECOR) = 
		(SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV
		WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_GEV_DATA_DECOR <= @OGGI
		AND LSRSER_GEV_FLAG_VALIDITA = 'Y')
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y' 
END

--=========================================================================
/*
IF @TABBIG IS NOT NULL
BEGIN
	SELECT @STATOBIG = LSRSER_BIG_STATO
	FROM LSRSER_BIG
	WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIAB

	AND(LSRSER_BIG_DATA_DECOR) = 
		(SELECT MAX(LSRSER_BIG_DATA_DECOR) FROM LSRSER_BIG
		WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_BIG_DATA_DECOR <= @OGGI
		AND LSRSER_BIG_KEY_DATA_INS =  @IERI)
		OR LSRSER_BIG_DATA_DECOR =  @OGGI)
		AND LSRSER_BIG_FLAG_VALIDITA = 'Y')
	AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
END
ELSE
BEGIN
	SELECT @STATOBIG = LSRSER_BIG_STATO
	FROM LSRSER_BIG
	WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_BIG_DATA_DECOR) = 
		(SELECT MAX(LSRSER_BIG_DATA_DECOR) FROM LSRSER_BIG
		WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_BIG_DATA_DECOR <= @OGGI
		AND LSRSER_BIG_FLAG_VALIDITA = 'Y')
	AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
END

--=========================================================================

IF @TABCOMUNE IS NOT NULL
BEGIN
	SELECT @STATOCOMUNE = LSRSER_COMUNE_STATO
	FROM LSRSER_COMUNE
	WHERE LSRSER_COMUNE_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_COMUNE_DATA_DECOR) = 
		(SELECT MAX(LSRSER_COMUNE_DATA_DECOR) FROM LSRSER_COMUNE
		WHERE LSRSER_COMUNE_KEY_ID_RICEV = @RICEVITORIAB
		AND ((LSRSER_COMUNE_DATA_DECOR <= @OGGI
		AND LSRSER_COMUNE_KEY_DATA_INS =  @IERI)
		OR LSRSER_COMUNE_DATA_DECOR =  @OGGI)
		AND LSRSER_COMUNE_FLAG_VALIDITA = 'Y')
	AND LSRSER_COMUNE_FLAG_VALIDITA = 'Y'
END
ELSE
BEGIN
	SELECT @STATOCOMUNE = LSRSER_COMUNE_STATO
	FROM LSRSER_COMUNE
	WHERE LSRSER_COMUNE_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_COMUNE_DATA_DECOR) = 
		(SELECT MAX(LSRSER_COMUNE_DATA_DECOR) FROM LSRSER_COMUNE
		WHERE LSRSER_COMUNE_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_COMUNE_DATA_DECOR <= @OGGI
		AND LSRSER_COMUNE_FLAG_VALIDITA = 'Y')
	AND LSRSER_COMUNE_FLAG_VALIDITA = 'Y'
END
*/


IF @TELRICEV = '/'
BEGIN
	SELECT @TELRICEV = ''
END

IF @TELTIT = '/'
BEGIN
	SELECT @TELTIT = ''
END

--***************************************************************************************************
-- MODIFICA DEL 27/12/2005:
-- CALCOLO IL VALORE DEL FLAG 12 IN ACCORDO AI CAMPI @STATOTRIS E @STATOST

SELECT @STATOST_SI =  CASE 
         	WHEN @STATOTRIS = '0' AND @STATOST = '0' THEN '0'
		WHEN @STATOTRIS = '0' AND @STATOST = '1' THEN '4'
         	WHEN @STATOTRIS = '0' AND @STATOST = '2' THEN '6'
        	WHEN @STATOTRIS = '1' AND @STATOST = '0' THEN '3'
        	WHEN @STATOTRIS = '1' AND @STATOST = '1' THEN '1'
        	WHEN @STATOTRIS = '1' AND @STATOST = '2' THEN '7'
      		WHEN @STATOTRIS = '2' AND @STATOST = '0' THEN '0'
      		WHEN @STATOTRIS = '2' AND @STATOST = '1' THEN '4'
         	WHEN @STATOTRIS = '2' AND @STATOST = '2' THEN '6'
         	WHEN @STATOTRIS = '3' AND @STATOST = '0' THEN '5'
        	WHEN @STATOTRIS = '3' AND @STATOST = '1' THEN '8'
         	WHEN @STATOTRIS = '3' AND @STATOST = '2' THEN '2'
         ELSE '0'
END


--*************************************************************************************************************
--MODIFICA DEL 27/06/2007
-- WORK AROUND SCOMMESSE: IMPOSTO IL FLAG 11 E IL FLAG 12 COME IL FLAG 2
IF @RICEVITORIAB LIKE '6%' OR @RICEVITORIAB LIKE '7%' 
BEGIN
	SELECT @STATOCONI = @STATOF101
	SELECT @STATOST_SI = @STATOF101
END 


--***************************************************************************************************

INSERT INTO LSR1APP VALUES
(@RICEVITORIAB,@CODAMM,@NUMTERM,@MODULO,@DATAATTIV,@DATACESSAZ,@DECODRICEV,@COMUNERICEV,
@PROVRICEV,@CAPRICEV,@INDIRIZZORICEV,@COGNOME,@NOME,@STATORICEV,@TELRICEV,@TELTIT,@DECORDAL,
@STATOLOTTO,@STATOF101,@STATORAI,@STATOSERTEL,@STATOBOLLO,@STATOBIG,@STATOCOMUNE,@STATOTRIS,@STATOGEV,'0',@STATOCONI,@STATOST_SI,
NULL,@SIGLAIC,@SIGLAREG,@CHIUSURARICEV,@SPECIALERICEV,NULL,@CODMAGAZ,@IDTAB,@ASSORICEV,@FLAGCOMM,
@OGGI,@DATARIATTIV,@FLAGESE,@TERMINST)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN INSERT LSR1APP'
	RAISERROR (@MSGERR, 16, 1)
	EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
	EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSR1APP TERMINATA IN MODO ANOMALO', 0

	CLOSE CUR_FLAG
	DEALLOCATE CUR_FLAG
	RETURN
END

FETCH NEXT FROM CUR_FLAG INTO 
	@RICEVITORIAB,@TABRIC,@TABTIT,@TABLOTTO,
	@TABF101,@TABRAI,@TABINFO,@TABBOLLO,
	@TABBIG,@TABCOMUNE,@TABTRIS,@TABGEV,@TABCONI,@TABST
END

CLOSE CUR_FLAG
DEALLOCATE CUR_FLAG

EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSR1APP TERMINATA CORRETTAMENTE', 0
GO
