/****** Object:  StoredProcedure [dbo].[CREA_LSR01A]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CREA_LSR01A]  AS

DECLARE   

@IERI			CHAR(8),
@OGGI			CHAR(8),
@DATAINS		CHAR(8),
@RICEVITORIA		CHAR(6),
@RICEVITORIAD	CHAR(6),
@RICEVITORIAB	CHAR(6),
@CODAMM		CHAR(6),
@DATADECOR		CHAR(8),
@DATAATTIV		CHAR(8),
@DATACESSAZ	CHAR(8),
@DECODRICEV	CHAR(50),
@COMUNERICEV	CHAR(24),
@PROVRICEV		CHAR(2),
@CAPRICEV		CHAR(5),
@INDIRIZZORICEV 	CHAR(40),
@COGNOME		CHAR(24),
@NOME		CHAR(20),
@STATORICEV		CHAR(1),
@STATOLOTTO	CHAR(1),
@STATOBOLLO	CHAR(1),
@STATOTRIS		CHAR(1),
@STATOF101		CHAR(1),
@STATOSERTEL	CHAR(1),
@STATOBIG		CHAR(1),
@STATOCOMUNE	CHAR(1),
@STATORAI		CHAR(1),
@TELRICEV		CHAR(12),
@TELTIT		CHAR(12),
@SIGLAIC		CHAR(2),
@SIGLAREG		CHAR(2),
@CHIUSURARICEV	CHAR(1),
@SPECIALERICEV	CHAR(1),
@CODMAGAZ		CHAR(5),
@IDTAB		CHAR(4),
@ASSORICEV		CHAR(1),
@DATARIATTIV	CHAR(8),
@FLAGESE		CHAR(1),
@TESTO		VARCHAR(300),
@NUMTERM		CHAR(2),
@TERMINST		CHAR(1),
@MODULO		CHAR(1),
@FLAGCOMM		CHAR(1),
@TABRIC		CHAR(1),
@TABTIT		CHAR(1),
@TABLOTTO		CHAR(1),
@TABF101		CHAR(1),
@TABRAI		CHAR(1),
@TABINFO		CHAR(1),
@TABBOLLO		CHAR(1),
@TABBIG		CHAR(1),
@TABCOMUNE		CHAR(1),
@TABTRIS		CHAR(1),
@MSGERR		VARCHAR(100),
@NOMEJOB		VARCHAR(25)

SELECT @STATOLOTTO = '0'
SELECT @STATOBOLLO = '0'
SELECT @STATOTRIS = '0'
SELECT @STATOF101 = '0'
SELECT @STATOSERTEL = '0'
SELECT @STATORAI = '0'
SELECT @STATOCOMUNE = '0'
SELECT @STATOBIG = '0'

SELECT @OGGI = CONVERT(CHAR(8), GETDATE(), 112)

SELECT @IERI = SUBSTRING(CONVERT(CHAR, GETDATE() -1, 121),1,4)+ 
		 SUBSTRING(CONVERT(CHAR, GETDATE() -1, 121),6,2)+ 
		 SUBSTRING(CONVERT(CHAR, GETDATE() -1, 121),9,2)

SELECT @NOMEJOB = 'AAEG012001UC'

DELETE FROM LSR1APP
--***************************************************************************
--* DICHIARAZIONE DEL CURSORE RELATIVO ALLE RICEVITORIE
--***************************************************************************
DECLARE CUR_FLAG CURSOR FOR 
SELECT LSRRIC_KEY_ID_RICEV
FROM LSRRIC

OPEN CUR_FLAG
FETCH NEXT FROM CUR_FLAG INTO 
@RICEVITORIAB

IF @@FETCH_STATUS <> 0
BEGIN
	SELECT @MSGERR = 'NESSUNA MOVIMENTAZIONE ANAGRAFICA'
	RAISERROR(@MSGERR,16,1)
	EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
	EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSR01A TERMINATA CORRETTAMENTE', 0
	CLOSE CUR_FLAG
	DEALLOCATE CUR_FLAG

	RETURN
END
ELSE

WHILE @@FETCH_STATUS = 0 

BEGIN
--=========================================================================
	SELECT @RICEVITORIA=LSRRIC_KEY_ID_RICEV,
		@CODAMM=LSRRIC_COD_AMM,
		@DECODRICEV=LSRRIC_DECOD_RICEV,
		@COMUNERICEV=LSRRIC_COMUNE_RICEV,
		@PROVRICEV=LSRRIC_PROV_RICEV,
		@CAPRICEV=LSRRIC_CAP,
		@INDIRIZZORICEV=LSRRIC_INDIRIZZO,
		@TELRICEV=LSRRIC_TEL_RICEVITORIA,
		@SIGLAIC=LSRRIC_SIGLA_IC,
		@SIGLAREG=LSRRIC_SIGLA_REG,
		@CHIUSURARICEV=LSRRIC_CHIUSURA,
		@SPECIALERICEV=LSRRIC_TAB_SPECIALI,
		@CODMAGAZ=LSRRIC_CODICE_MAGAZZINO,
		@FLAGESE=LSRRIC_FLAG_ESERCIZIO,
		@NUMTERM=LSRRIC_NUM_TERMINALI,
		@IDTAB=LSRRIC_ID_TAB
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @RICEVITORIAB

--=========================================================================
	SELECT @COGNOME=LSRTIT_COGNOME,
		@NOME=LSRTIT_NOME,
		@TELTIT=LSRTIT_TELEFONO
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIAB

--=========================================================================

	SELECT @STATORICEV = NULL
	SELECT @STATORICEV = LSRSER_LOTTO_TIPO_PROVV,
		@DATADECOR = LSRSER_LOTTO_DATA_DECOR,
		@ASSORICEV = LSRSER_LOTTO_ASSOCIAZIONE
	FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_LOTTO_DATA_DECOR) = 
	(
		SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
		WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_LOTTO_DATA_DECOR <= @OGGI
		AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'

	IF @STATORICEV = 'A' 
	BEGIN
		SELECT @DATAATTIV = @DATADECOR
		SELECT @DATACESSAZ = '00000000'
		SELECT @DATARIATTIV = '00000000'
		SELECT @STATOLOTTO = '1'
	END
	ELSE IF @STATORICEV = 'S' OR @STATORICEV = 'R' OR @STATORICEV = 'M' 
	BEGIN
		SELECT @DATAATTIV = '00000000'
		SELECT @DATACESSAZ = @DATADECOR
		SELECT @DATARIATTIV = '00000000'
		SELECT @STATOLOTTO = '2'
	END
	ELSE IF LTRIM(RTRIM(@STATORICEV)) = ''
	BEGIN
		SELECT @DATAATTIV = '00000000'
		SELECT @DATACESSAZ = @DATADECOR
		SELECT @DATARIATTIV = '00000000'
		SELECT @STATOLOTTO = '0'
	END
--=========================================================================

	SELECT @STATOF101 = NULL

	SELECT @STATOF101 = LSRSER_F101_STATO
	FROM LSRSER_F101
	WHERE LSRSER_F101_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_F101_DATA_DECOR) = 
	(
		SELECT MAX(LSRSER_F101_DATA_DECOR) FROM LSRSER_F101
		WHERE LSRSER_F101_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_F101_DATA_DECOR <= @OGGI
		AND LSRSER_F101_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_F101_FLAG_VALIDITA = 'Y'
--=========================================================================

	SELECT @STATORAI = NULL

	SELECT @STATORAI = LSRSER_RAI_STATO
	FROM LSRSER_RAI
	WHERE LSRSER_RAI_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_RAI_DATA_DECOR) = 
	(
		SELECT MAX(LSRSER_RAI_DATA_DECOR) FROM LSRSER_RAI
		WHERE LSRSER_RAI_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_RAI_DATA_DECOR <= @OGGI
		AND LSRSER_RAI_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_RAI_FLAG_VALIDITA = 'Y'
--=========================================================================

	SELECT @STATOSERTEL = NULL

	SELECT @STATOSERTEL = LSRSER_INFO_STATO
	FROM LSRSER_INFO
	WHERE LSRSER_INFO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_INFO_DATA_DECOR) = 
	(
		SELECT MAX(LSRSER_INFO_DATA_DECOR) FROM LSRSER_INFO
		WHERE LSRSER_INFO_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_INFO_DATA_DECOR <= @OGGI
		AND LSRSER_INFO_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_INFO_FLAG_VALIDITA = 'Y'
--=========================================================================

	SELECT @STATOBOLLO = NULL

	SELECT @STATOBOLLO = LSRSER_BOLLO_STATO
	FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_BOLLO_DATA_DECOR) = 
	(
		SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_BOLLO_DATA_DECOR <= @OGGI
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
--=========================================================================

	SELECT @STATOTRIS = NULL

	SELECT @STATOTRIS = LSRSER_TRIS_STATO
	FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_TRIS_DATA_DECOR) = 
	(
		SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS
		WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_TRIS_DATA_DECOR <= @OGGI
		AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
--=========================================================================

	SELECT @STATOBIG = NULL

	SELECT @STATOBIG = LSRSER_BIG_STATO
	FROM LSRSER_BIG
	WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_BIG_DATA_DECOR) = 
	(
		SELECT MAX(LSRSER_BIG_DATA_DECOR) FROM LSRSER_BIG
		WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_BIG_DATA_DECOR <= @OGGI
		AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
--=========================================================================

	SELECT @STATOCOMUNE = NULL

	SELECT @STATOCOMUNE = LSRSER_COMUNE_STATO
	FROM LSRSER_COMUNE
	WHERE LSRSER_COMUNE_KEY_ID_RICEV = @RICEVITORIAB
	AND(LSRSER_COMUNE_DATA_DECOR) = 
	(
		SELECT MAX(LSRSER_COMUNE_DATA_DECOR) FROM LSRSER_COMUNE
		WHERE LSRSER_COMUNE_KEY_ID_RICEV = @RICEVITORIAB
		AND LSRSER_COMUNE_DATA_DECOR <= @OGGI
		AND LSRSER_COMUNE_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_COMUNE_FLAG_VALIDITA = 'Y'

	IF @TELRICEV = '/'
	BEGIN
		SELECT @TELRICEV = ''
	END

	IF @TELTIT = '/'
	BEGIN
		SELECT @TELTIT = ''
	END

	INSERT INTO LSR1APP VALUES
	(@RICEVITORIAB,@CODAMM,@NUMTERM,@MODULO,@DATAATTIV,@DATACESSAZ,@DECODRICEV,@COMUNERICEV,
	@PROVRICEV,@CAPRICEV,@INDIRIZZORICEV,@COGNOME,@NOME,@STATORICEV,@TELRICEV,@TELTIT,'00000000',
	@STATOLOTTO,@STATOF101,@STATORAI,@STATOSERTEL,@STATOBOLLO,@STATOBIG,@STATOCOMUNE,@STATOTRIS,'0','0','0','0',
	NULL,@SIGLAIC,@SIGLAREG,@CHIUSURARICEV,@SPECIALERICEV,NULL,@CODMAGAZ,@IDTAB,@ASSORICEV,@FLAGCOMM,
	@OGGI,@DATARIATTIV,@FLAGESE,@TERMINST)

	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE IN INSERT LSR1APP'
		RAISERROR (@MSGERR, 16, 1)
		EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
		EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSR01A TERMINATA IN MODO ANOMALO', 0

		CLOSE CUR_FLAG
		DEALLOCATE CUR_FLAG

		RETURN
	END

	FETCH NEXT FROM CUR_FLAG INTO @RICEVITORIAB

END

CLOSE CUR_FLAG
DEALLOCATE CUR_FLAG

EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSR01A TERMINATA CORRETTAMENTE', 0
GO
