/****** Object:  StoredProcedure [dbo].[CC_DATI_LOTTO_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CC_DATI_LOTTO_GS] 

@CODLTM		CHAR(6),
@STATOLOTTO	VARCHAR(25) OUTPUT,
@NUMPROVVPRO	VARCHAR(14) OUTPUT,
@DECORLOTTO	VARCHAR(8) OUTPUT,
@DATAPROVVPRO	VARCHAR(8) OUTPUT,
@DECORPRO		VARCHAR(8) OUTPUT,
@ENTEPRO		VARCHAR(25) OUTPUT,
@TIPOPROVVPRO	VARCHAR(25) OUTPUT,
@CAUSALEPRO	VARCHAR(40) OUTPUT,
@FLGANNULL		CHAR(1) OUTPUT

AS


SELECT 
@STATOLOTTO = LSRSER_LOTTO_TIPO_PROVV, @DECORLOTTO = LSRSER_LOTTO_DATA_DECOR
FROM LSRSER_LOTTO
WHERE
LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM AND
LSRSER_LOTTO_FLAG_VALIDITA = 'Y' AND
LSRSER_LOTTO_FT_VOS <> '00000000' AND
LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM AND
LSRSER_LOTTO_DATA_DECOR =
(
	SELECT MAX(LSRSER_LOTTO_DATA_DECOR)
	FROM LSRSER_LOTTO
	WHERE
	LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM AND
	LSRSER_LOTTO_FLAG_VALIDITA = 'Y' AND
	LSRSER_LOTTO_FT_VOS <> '00000000' AND
	LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR, GETDATE(),112)
)


SELECT @DATAPROVVPRO = LSRPRO_KEY_DATA_PROVV, @DECORPRO = LSRPRO_DECOR_DAL,
@ENTEPRO = LSRPRO_EMANATO, @TIPOPROVVPRO = LSRPRO_KEY_TIPO_REC, 
@CAUSALEPRO = LSRPRO_CAUSALE, @FLGANNULL = LSRPRO_FLAG_ANNUL,
@NUMPROVVPRO = LSRPRO_KEY_PROG_PROVV
FROM LSRPRO
WHERE
LSRPRO_KEY_ID_RICEV = @CODLTM AND
LSRPRO_KEY_TIPO_REC NOT IN ('E', 'T') AND
LSRPRO_FLAG_VALIDITA = 'Y' AND
LSRPRO_FT_VOS <> '00000000' AND
LSRPRO_DECOR_DAL =
(
	SELECT MAX (LSRPRO_DECOR_DAL)
	FROM LSRPRO
	WHERE
	LSRPRO_KEY_ID_RICEV = @CODLTM AND
	LSRPRO_DECOR_DAL <= CONVERT(CHAR, GETDATE(),112) AND
	LSRPRO_FLAG_VALIDITA = 'Y' AND
	LSRPRO_FT_VOS <> '00000000' AND
	LSRPRO_KEY_TIPO_REC NOT IN ('E', 'T')
)

IF LTRIM(RTRIM(@STATOLOTTO)) = 'A'
BEGIN
	SELECT @STATOLOTTO = 'ATTIVO'
END
ELSE IF LTRIM(RTRIM(@STATOLOTTO)) = 'R'
BEGIN
	SELECT @STATOLOTTO = 'REVOCATO'
END
ELSE IF LTRIM(RTRIM(@STATOLOTTO)) = 'S'
BEGIN
	SELECT @STATOLOTTO = 'SOSPESO'
END
ELSE IF LTRIM(RTRIM(@STATOLOTTO)) = 'M'
BEGIN
	SELECT @STATOLOTTO = 'SMANTELLATO'
END
ELSE IF LTRIM(RTRIM(@STATOLOTTO)) = ''
BEGIN
	IF LTRIM(RTRIM(@TIPOPROVVPRO)) = 'C'
	BEGIN
		IF LTRIM(RTRIM(@FLGANNULL)) = '1'
		BEGIN
			SELECT @STATOLOTTO = 'CONCESSIONE ANNULLATA'
			SELECT @DECORLOTTO = @DECORPRO
		END
		ELSE
		BEGIN
			SELECT @STATOLOTTO = 'CONCESSIONE'
			SELECT @DECORLOTTO = @DECORPRO
		END
	END
	ELSE
	BEGIN
		SELECT @STATOLOTTO = 'NON ATTIVATO'
		SELECT @DECORLOTTO = NULL
	END
END

IF LTRIM(RTRIM(@TIPOPROVVPRO)) = 'A'
BEGIN
	SELECT @TIPOPROVVPRO = 'RIATTIVAZIONE '
END
ELSE IF LTRIM(RTRIM(@TIPOPROVVPRO)) = 'R'
BEGIN
	SELECT @TIPOPROVVPRO = 'REVOCA'
END
ELSE IF LTRIM(RTRIM(@TIPOPROVVPRO)) = 'S'
BEGIN
	SELECT @TIPOPROVVPRO = 'SOSPENSIONE'
END
ELSE IF LTRIM(RTRIM(@TIPOPROVVPRO)) = 'M'
BEGIN
	SELECT @TIPOPROVVPRO = 'SMANTELLAMENTO'
END
ELSE IF LTRIM(RTRIM(@TIPOPROVVPRO)) = 'I'
BEGIN
	SELECT @TIPOPROVVPRO = 'CAMBIO TITOLARE'
END
ELSE IF LTRIM(RTRIM(@TIPOPROVVPRO)) = 'C'
BEGIN
	SELECT @TIPOPROVVPRO = 'CONCESSIONE'
END

IF @NUMPROVVPRO IS NULL
BEGIN
	SELECT @NUMPROVVPRO = 'N.D.'
END

IF @ENTEPRO IS NULL
BEGIN
	SELECT @ENTEPRO = 'N.D.'
END
GO
