/****** Object:  StoredProcedure [dbo].[CC_DATI_RAD_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[CC_DATI_RAD_GS] 

@CODLTM		VARCHAR(7),
@GS			VARCHAR(6),
@DATASTATO1	CHAR(8),
@DATASTATO2	CHAR(8),
@TABELLA		VARCHAR(20),
@FKTAB		CHAR(16)


AS

DECLARE 

@DATAPROVV		CHAR(8),
@TIPOPROVV		CHAR(1),
@NUMPROVV		VARCHAR(15),
@TIPOMOV		CHAR(1),
@DATARAD		CHAR(8),
@FONTE		VARCHAR(15),
@ENTE		VARCHAR(25),
@CAUSALE		VARCHAR(50)


IF @TABELLA IS NULL OR LTRIM(RTRIM(@TABELLA)) = ''
BEGIN

	IF LEN(@GS) = 2
	BEGIN
		--MODIFICA DEL 30/07/2003: GESTIONE CONI (CDS)
		IF @GS='11'
		BEGIN

			IF @DATASTATO2 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_CONI_DATA_INVIO_DOC, 
				CASE LSRRAD_CONI_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_CONI_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
				END AS TIPOMOV,
				LSRRAD_CONI_CAUSALE_LOTTOMATICA,
				LSRRAD_CONI_NUM_PROT_DOC
				FROM LSRRAD_CONI
				WHERE
				LSRRAD_CONI_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_CONI_FLAG_ANAG = '1' AND 
				LSRRAD_CONI_DATA_INVIO_DOC BETWEEN @DATASTATO2 AND @DATASTATO1
				ORDER BY LSRRAD_CONI_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_CONI_DATA_INVIO_DOC, 
				CASE LSRRAD_CONI_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_CONI_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
				END AS TIPOMOV,
				LSRRAD_CONI_CAUSALE_LOTTOMATICA,
				LSRRAD_CONI_NUM_PROT_DOC
				FROM LSRRAD_CONI
				WHERE
				LSRRAD_CONI_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_CONI_FLAG_ANAG = '1' AND 
				LSRRAD_CONI_DATA_INVIO_DOC <= @DATASTATO1
				ORDER BY LSRRAD_CONI_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NULL
			BEGIN
				SELECT  LSRRAD_CONI_DATA_INVIO_DOC, 
				CASE LSRRAD_CONI_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'M' THEN 'MONOPOLI'
					WHEN 'A' THEN 'ASSOCIAZIONE'
				END AS FONTE,
				'',
				CASE LSRRAD_CONI_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
				END AS TIPOMOV,
				LSRRAD_CONI_CAUSALE_LOTTOMATICA,
				LSRRAD_CONI_NUM_PROT_DOC
				FROM LSRRAD_CONI
				WHERE
				LSRRAD_CONI_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_CONI_FLAG_ANAG = '1'
				ORDER BY LSRRAD_CONI_DATA_INVIO_DOC DESC
		
				RETURN
			END
		END
		ELSE IF @GS='12'
		BEGIN

			IF @DATASTATO2 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_ST_DATA_INVIO_DOC, 
				CASE LSRRAD_ST_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_ST_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
				END AS TIPOMOV,
				LSRRAD_ST_CAUSALE_LOTTOMATICA,
				LSRRAD_ST_NUM_PROT_DOC
				FROM LSRRAD_ST
				WHERE
				LSRRAD_ST_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_ST_FLAG_ANAG = '1' AND 
				LSRRAD_ST_DATA_INVIO_DOC BETWEEN @DATASTATO2 AND @DATASTATO1
				ORDER BY LSRRAD_ST_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_ST_DATA_INVIO_DOC, 
				CASE LSRRAD_ST_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_ST_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
				END AS TIPOMOV,
				LSRRAD_ST_CAUSALE_LOTTOMATICA,
				LSRRAD_ST_NUM_PROT_DOC
				FROM LSRRAD_ST
				WHERE
				LSRRAD_ST_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_ST_FLAG_ANAG = '1' AND 
				LSRRAD_ST_DATA_INVIO_DOC <= @DATASTATO1
				ORDER BY LSRRAD_ST_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NULL
			BEGIN
				SELECT  LSRRAD_ST_DATA_INVIO_DOC, 
				CASE LSRRAD_ST_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'M' THEN 'MONOPOLI'
					WHEN 'A' THEN 'ASSOCIAZIONE'
				END AS FONTE,
				'',
				CASE LSRRAD_ST_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
				END AS TIPOMOV,
				LSRRAD_ST_CAUSALE_LOTTOMATICA,
				LSRRAD_ST_NUM_PROT_DOC
				FROM LSRRAD_ST
				WHERE
				LSRRAD_ST_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_ST_FLAG_ANAG = '1'
				ORDER BY LSRRAD_ST_DATA_INVIO_DOC DESC
		
				RETURN
			END
		END

		ELSE IF @GS='08'
		BEGIN

			IF @DATASTATO2 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_GS_DATA_INVIO_DOC, 
				CASE LSRRAD_GS_FONTE

					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'R' THEN 'ENTE/REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_GS_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'

				END AS TIPOMOV,
				LSRRAD_GS_CAUSALE_LOTTOMATICA,
				LSRRAD_GS_NUM_PROT_DOC
				FROM LSRRAD_GS
				WHERE
				LSRRAD_GS_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_GS_FLAG_ANAG = '1' AND 
				lsrRAD_GS_CODICE_servizio = '08' AND
				LSRRAD_GS_DATA_INVIO_DOC BETWEEN @DATASTATO2 AND @DATASTATO1
				ORDER BY LSRRAD_GS_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_GS_DATA_INVIO_DOC, 
				CASE LSRRAD_GS_FONTE

					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'R' THEN 'ENTE/REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_GS_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'

				END AS TIPOMOV,
				LSRRAD_GS_CAUSALE_LOTTOMATICA,
				LSRRAD_GS_NUM_PROT_DOC
				FROM LSRRAD_GS
				WHERE
				LSRRAD_GS_KEY_ID_RICEV = @CODLTM AND
				lsrRAD_GS_CODICE_servizio = '08' AND
				LSRRAD_GS_FLAG_ANAG = '1' AND 
				LSRRAD_GS_DATA_INVIO_DOC <= @DATASTATO1
				ORDER BY LSRRAD_GS_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NULL
			BEGIN
				SELECT  LSRRAD_GS_DATA_INVIO_DOC, 
				CASE LSRRAD_GS_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'R' THEN 'ENTE/REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_GS_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'
				END AS TIPOMOV,
				LSRRAD_GS_CAUSALE_LOTTOMATICA,
				LSRRAD_GS_NUM_PROT_DOC
				FROM LSRRAD_GS
				WHERE
				LSRRAD_GS_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_GS_FLAG_ANAG = '1' AND
				lsrRAD_GS_CODICE_servizio = '08'
				ORDER BY LSRRAD_GS_DATA_INVIO_DOC DESC
		
				RETURN
			END
		END

		-- GIOCHI PUBBLICI
		ELSE IF @GS='02'
		BEGIN

			IF @DATASTATO2 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_GS_DATA_INVIO_DOC, 
				CASE LSRRAD_GS_FONTE

					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'R' THEN 'ENTE/REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_GS_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'

				END AS TIPOMOV,
				LSRRAD_GS_CAUSALE_LOTTOMATICA,
				LSRRAD_GS_NUM_PROT_DOC
				FROM LSRRAD_GS
				WHERE
				LSRRAD_GS_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_GS_FLAG_ANAG = '1' AND 
				lsrRAD_GS_CODICE_servizio = '02' AND
				LSRRAD_GS_DATA_INVIO_DOC BETWEEN @DATASTATO2 AND @DATASTATO1
				ORDER BY LSRRAD_GS_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_GS_DATA_INVIO_DOC, 
				CASE LSRRAD_GS_FONTE

					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'R' THEN 'ENTE/REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_GS_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'

				END AS TIPOMOV,
				LSRRAD_GS_CAUSALE_LOTTOMATICA,
				LSRRAD_GS_NUM_PROT_DOC
				FROM LSRRAD_GS
				WHERE
				LSRRAD_GS_KEY_ID_RICEV = @CODLTM AND
				lsrRAD_GS_CODICE_servizio = '02' AND
				LSRRAD_GS_FLAG_ANAG = '1' AND 
				LSRRAD_GS_DATA_INVIO_DOC <= @DATASTATO1
				ORDER BY LSRRAD_GS_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NULL
			BEGIN
				SELECT  LSRRAD_GS_DATA_INVIO_DOC, 
				CASE LSRRAD_GS_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
					WHEN 'R' THEN 'ENTE/REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'M' THEN 'MONOPOLI'
				END AS FONTE,
				'',
				CASE LSRRAD_GS_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'
				END AS TIPOMOV,
				LSRRAD_GS_CAUSALE_LOTTOMATICA,
				LSRRAD_GS_NUM_PROT_DOC
				FROM LSRRAD_GS
				WHERE
				LSRRAD_GS_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_GS_FLAG_ANAG = '1' AND
				lsrRAD_GS_CODICE_servizio = '02'
				ORDER BY LSRRAD_GS_DATA_INVIO_DOC DESC
		
				RETURN
			END
		END

		ELSE --ALTRI GIOCHI-SERVIZI LTM
		BEGIN
			IF @DATASTATO2 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_DATA_INVIO_DOC, 
				CASE LSRRAD_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'R' THEN 'REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
				END AS FONTE,
				LSRRAD_COD_ENTE,
				CASE LSRRAD_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'
				END AS TIPOMOV,
				LSRRAD_CAUSALE_LOTTOMATICA,
				LSRRAD_NUM_PROT_DOC
				FROM LSRRAD
				WHERE
				LSRRAD_TIPO_SERVIZIO = @GS AND
				LSRRAD_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_FLAG_ANAG = '1' AND 
				LSRRAD_DATA_INVIO_DOC BETWEEN @DATASTATO2 AND @DATASTATO1
				ORDER BY LSRRAD_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NOT NULL
			BEGIN
				SELECT  LSRRAD_DATA_INVIO_DOC, 
				CASE LSRRAD_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'R' THEN 'REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
				END AS FONTE,
				LSRRAD_COD_ENTE,
				CASE LSRRAD_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'
				END AS TIPOMOV,
				LSRRAD_CAUSALE_LOTTOMATICA,
				LSRRAD_NUM_PROT_DOC
				FROM LSRRAD
				WHERE
				LSRRAD_TIPO_SERVIZIO = @GS AND
				LSRRAD_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_FLAG_ANAG = '1' AND 
				LSRRAD_DATA_INVIO_DOC <= @DATASTATO1
				ORDER BY LSRRAD_DATA_INVIO_DOC DESC
		
				RETURN
			END
		
			IF @DATASTATO1 IS NULL
			BEGIN
				SELECT  LSRRAD_DATA_INVIO_DOC, 
				CASE LSRRAD_FONTE
					WHEN 'L' THEN 'LOTTOMATICA'
					WHEN 'R' THEN 'REGIONE'
					WHEN 'Q' THEN 'QUESTURA'
					WHEN 'A' THEN 'ASSOCIAZIONE'
				END AS FONTE,
				LSRRAD_COD_ENTE,
				CASE LSRRAD_TIPO_MOVIMENTAZIONE
					WHEN 'A' THEN 'ATTIVAZIONE'
					WHEN 'D' THEN 'DISATTIVAZIONE'
					WHEN 'R' THEN 'RIATTIVAZIONE'
					WHEN 'S' THEN 'SOSPENSIONE'
				END AS TIPOMOV,
				LSRRAD_CAUSALE_LOTTOMATICA,
				LSRRAD_NUM_PROT_DOC
				FROM LSRRAD
				WHERE
				LSRRAD_TIPO_SERVIZIO = @GS AND
				LSRRAD_KEY_ID_RICEV = @CODLTM AND
				LSRRAD_FLAG_ANAG = '1'
				ORDER BY LSRRAD_DATA_INVIO_DOC DESC
		
				RETURN
			END
		END
	END
	ELSE  --GIOCO/SERVIZIO LIS
	BEGIN
	
		IF @DATASTATO2 IS NOT NULL
		BEGIN
			SELECT  LSRRAD_LIS_DATA_INVIO_DOC, 
			CASE LSRRAD_LIS_FONTE
				WHEN 'L' THEN 'LOTTOMATICA'
				WHEN 'R' THEN 'REGIONE'
				WHEN 'Q' THEN 'QUESTURA'
				WHEN 'A' THEN 'ASSOCIAZIONE'
			END AS FONTE,
			CASE LSRRAD_LIS_TIPO_MOVIMENTAZIONE
				WHEN 'A' THEN 'ATTIVAZIONE'
				WHEN 'D' THEN 'DISATTIVAZIONE'
				WHEN 'R' THEN 'RIATTIVAZIONE'
				WHEN 'S' THEN 'SOSPENSIONE'
			END AS TIPOMOV,
			LSRRAD_LIS_CAUSALE_LIS,
			LSRRAD_LIS_NUM_PROT_DOC
			FROM LSRRAD_LIS
			WHERE
			LSRRAD_LIS_KEY_CATEGORIA + LSRRAD_LIS_KEY_SERVIZIO + LSRRAD_LIS_KEY_ATTIVITA = @GS AND
			LSRRAD_LIS_KEY_ID_RICEV = @CODLTM AND
			LSRRAD_LIS_FLAG_ANAG = '1' AND 
			LSRRAD_LIS_DATA_INVIO_DOC BETWEEN @DATASTATO2 AND @DATASTATO1
			ORDER BY LSRRAD_LIS_DATA_INVIO_DOC DESC
	
			RETURN
		END
	
	
		IF @DATASTATO1 IS NOT NULL
		BEGIN
			SELECT  LSRRAD_LIS_DATA_INVIO_DOC, 
			CASE LSRRAD_LIS_FONTE
				WHEN 'L' THEN 'LOTTOMATICA'
				WHEN 'R' THEN 'REGIONE'
				WHEN 'Q' THEN 'QUESTURA'
				WHEN 'A' THEN 'ASSOCIAZIONE'
			END AS FONTE,
			CASE LSRRAD_LIS_TIPO_MOVIMENTAZIONE
				WHEN 'A' THEN 'ATTIVAZIONE'
				WHEN 'D' THEN 'DISATTIVAZIONE'
				WHEN 'R' THEN 'RIATTIVAZIONE'
				WHEN 'S' THEN 'SOSPENSIONE'
			END AS TIPOMOV,
			LSRRAD_LIS_CAUSALE_LIS,
			LSRRAD_LIS_NUM_PROT_DOC
			FROM LSRRAD_LIS
			WHERE
			LSRRAD_LIS_KEY_CATEGORIA + LSRRAD_LIS_KEY_SERVIZIO + LSRRAD_LIS_KEY_ATTIVITA = @GS AND
			LSRRAD_LIS_KEY_ID_RICEV = @CODLTM AND
			LSRRAD_LIS_FLAG_ANAG = '1' AND 
			LSRRAD_LIS_DATA_INVIO_DOC <= @DATASTATO1
			ORDER BY LSRRAD_LIS_DATA_INVIO_DOC DESC
	
			RETURN
		END
	
		IF @DATASTATO1 IS NULL
		BEGIN
			SELECT  LSRRAD_LIS_DATA_INVIO_DOC, 
			CASE LSRRAD_LIS_FONTE
				WHEN 'L' THEN 'LOTTOMATICA'
				WHEN 'R' THEN 'REGIONE'
				WHEN 'Q' THEN 'QUESTURA'
				WHEN 'A' THEN 'ASSOCIAZIONE'
			END AS FONTE,
			CASE LSRRAD_LIS_TIPO_MOVIMENTAZIONE
				WHEN 'A' THEN 'ATTIVAZIONE'
				WHEN 'D' THEN 'DISATTIVAZIONE'
				WHEN 'R' THEN 'RIATTIVAZIONE'
				WHEN 'S' THEN 'SOSPENSIONE'
			END AS TIPOMOV,
			LSRRAD_LIS_CAUSALE_LIS,
			LSRRAD_LIS_NUM_PROT_DOC
			FROM LSRRAD_LIS
			WHERE
			LSRRAD_LIS_KEY_CATEGORIA + LSRRAD_LIS_KEY_SERVIZIO + LSRRAD_LIS_KEY_ATTIVITA = @GS AND
			LSRRAD_LIS_KEY_ID_RICEV = @CODLTM AND
			LSRRAD_LIS_FLAG_ANAG = '1'
			ORDER BY LSRRAD_LIS_DATA_INVIO_DOC DESC
	
			RETURN
		END
	END
END
ELSE
BEGIN
	IF @TABELLA = 'LSRRAD'
	BEGIN
		SELECT  LSRRAD_DATA_INVIO_DOC, 
		CASE LSRRAD_FONTE
			WHEN 'L' THEN 'LOTTOMATICA'
			WHEN 'R' THEN 'REGIONE'
			WHEN 'Q' THEN 'QUESTURA'
			WHEN 'A' THEN 'ASSOCIAZIONE'
		END AS FONTE,
		LSRRAD_COD_ENTE,
		CASE LSRRAD_TIPO_MOVIMENTAZIONE
			WHEN 'A' THEN 'ATTIVAZIONE'
			WHEN 'D' THEN 'DISATTIVAZIONE'
			WHEN 'R' THEN 'RIATTIVAZIONE'
			WHEN 'S' THEN 'SOSPENSIONE'
		END AS TIPOMOV,
		LSRRAD_CAUSALE_LOTTOMATICA,
		LSRRAD_NUM_PROT_DOC
		FROM LSRRAD
		WHERE
		LSRRAD_TIPO_SERVIZIO = @GS AND
		LSRRAD_KEY_ID_RICEV = @CODLTM AND
		LSRRAD_FLAG_ANAG = '1' AND
		LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS = @FKTAB
		ORDER BY LSRRAD_DATA_INVIO_DOC DESC
	END
	ELSE IF @TABELLA = 'LSRRAD_LIS'
	BEGIN
		SELECT  LSRRAD_LIS_DATA_INVIO_DOC, 
		CASE LSRRAD_LIS_FONTE
			WHEN 'L' THEN 'LOTTOMATICA'
			WHEN 'R' THEN 'REGIONE'
			WHEN 'Q' THEN 'QUESTURA'
			WHEN 'A' THEN 'ASSOCIAZIONE'
		END AS FONTE,
		CASE LSRRAD_LIS_TIPO_MOVIMENTAZIONE
			WHEN 'A' THEN 'ATTIVAZIONE'
			WHEN 'D' THEN 'DISATTIVAZIONE'
			WHEN 'R' THEN 'RIATTIVAZIONE'
			WHEN 'S' THEN 'SOSPENSIONE'
		END AS TIPOMOV,
		LSRRAD_LIS_CAUSALE_LIS,
		LSRRAD_LIS_NUM_PROT_DOC
		FROM LSRRAD_LIS
		WHERE
		LSRRAD_LIS_KEY_CATEGORIA + LSRRAD_LIS_KEY_SERVIZIO + LSRRAD_LIS_KEY_ATTIVITA = @GS AND
		LSRRAD_LIS_KEY_ID_RICEV = @CODLTM AND
		LSRRAD_LIS_FLAG_ANAG = '1' AND 
		LSRRAD_LIS_KEY_DATA_INS + LSRRAD_LIS_KEY_ORA_INS = @FKTAB
		ORDER BY LSRRAD_LIS_DATA_INVIO_DOC DESC
	END
END
GO
