/****** Object:  StoredProcedure [dbo].[CC_DATI_DOC_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[CC_DATI_DOC_GS] 

@CODLTM		VARCHAR(7),
@GS			VARCHAR(6),
@DATAADE		CHAR(8)	OUTPUT,
@DATACON		CHAR(8) 	OUTPUT,
@DATAAPS		CHAR(8) 	OUTPUT,
@DATAFID		CHAR(8) 	OUTPUT,
@DATARIN		CHAR(8) 	OUTPUT,
@DATAINVIO		CHAR(8)	OUTPUT,
@DATAAUT		CHAR(8) 	OUTPUT,
@DATANUO		CHAR(8)	OUTPUT,
@DATAQST		CHAR(8)	OUTPUT
 
AS

DECLARE

@DATARINRIN		CHAR(8),
@ANNORIF		CHAR(4)


SELECT @ANNORIF = SUBSTRING(CONVERT(CHAR, GETDATE(),112),1,4)

IF LEN(@GS) = 2
BEGIN

	--MODIFICA DEL 29/07/2003: GESTIONE CONI (CDS)
	IF (@GS='11')
	BEGIN
		SELECT @DATARIN = NULL
		SELECT @DATARINRIN = NULL
		
		SELECT @DATARIN = MAX(LSRRIN_CONI_DATA_RINUNCIA)
		FROM LSRRIN_CONI
		WHERE
		LSRRIN_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRRIN_CONI_FLAG_ANAG = '1' 
	
		SELECT @DATARINRIN = MAX(LSRRIN_CONI_DATA_RINUNCIA_RINUNCIA)
		FROM LSRRIN_CONI
		WHERE
		LSRRIN_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRRIN_CONI_FLAG_ANAG = '1'

		IF @DATARIN <= @DATARINRIN
		BEGIN
			SELECT @DATARIN = NULL
		END
	
		SELECT @DATACON = MAX(LSRCON_CONI_KEY_DATA_INS)
		FROM LSRCON_CONI
		WHERE
		LSRCON_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRCON_CONI_FLAG_ANAG = '1'

		SELECT @DATAFID = MAX(LSRFID_CONI_KEY_DATA_INS)
		FROM LSRFID_CONI
		WHERE
		LSRFID_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRFID_CONI_FLAG_ANAG = '1' 
--		AND LSRFID_CONI_ANNO_RIF = @ANNORIF

		SELECT @DATANUO = MAX(lsrnuo_coni_data_accettazione)
		FROM LSRNUO_CONI
		WHERE
		LSRNUO_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRNUO_CONI_FLAG_ANAG = '1'

		SELECT @DATAQST = MAX(lsrqst_coni_key_data_ins)
		FROM LSRQST_CONI
		WHERE
		LSRQST_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRQST_CONI_FLAG_ANAG = '1'
	
	END
	--MODIFICA DEL 01/09/2005: GESTIONE SCOMMESSE SPORTIVE
	ELSE IF (@GS='12')
	BEGIN
		SELECT @DATARIN = NULL
		SELECT @DATARINRIN = NULL
		
		SELECT @DATARIN = MAX(LSRRIN_CONI_DATA_RINUNCIA)
		FROM LSRRIN_CONI
		WHERE
		LSRRIN_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRRIN_CONI_FLAG_ANAG = '1' 
	
		SELECT @DATARINRIN = MAX(LSRRIN_CONI_DATA_RINUNCIA_RINUNCIA)
		FROM LSRRIN_CONI
		WHERE
		LSRRIN_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRRIN_CONI_FLAG_ANAG = '1'

		IF @DATARIN <= @DATARINRIN
		BEGIN
			SELECT @DATARIN = NULL
		END
	
		SELECT @DATACON = MAX(LSRCON_CONI_KEY_DATA_INS)
		FROM LSRCON_CONI
		WHERE
		LSRCON_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRCON_CONI_FLAG_ANAG = '1'

	
		SELECT @DATAFID = MAX(LSRFID_CONI_KEY_DATA_INS)
		FROM LSRFID_CONI
		WHERE
		LSRFID_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRFID_CONI_FLAG_ANAG = '1' 
--		AND LSRFID_CONI_ANNO_RIF = @ANNORIF
		
		-- APPOGGIO LA DATA DEI TULPS NELLA VARIABILE @DATAAPS
		SELECT @DATAAPS = MAX(LSRTLP_ST_KEY_DATA_INS) 
		FROM LSRTLP_ST
		WHERE 
		LSRTLP_ST_KEY_ID_RICEV = @CODLTM AND
		LSRTLP_ST_FLAG_ANAG='1'
		
		SELECT @DATANUO = MAX(lsrnuo_coni_data_accettazione)
		FROM LSRNUO_CONI
		WHERE
		LSRNUO_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRNUO_CONI_FLAG_ANAG = '1'

		SELECT @DATAQST = MAX(lsrqst_coni_key_data_ins)
		FROM LSRQST_CONI
		WHERE
		LSRQST_CONI_KEY_ID_RICEV = @CODLTM AND
		LSRQST_CONI_FLAG_ANAG = '1'
	
	END
	ELSE
	BEGIN
		SELECT @DATARIN = NULL
		SELECT @DATARINRIN = NULL
		
		SELECT @DATARIN = MAX(LSRRIN_DATA_RINUNCIA)
		FROM LSRRIN
		WHERE
		LSRRIN_KEY_ID_RICEV = @CODLTM AND
		LSRRIN_FLAG_ANAG = '1' AND
		LSRRIN_CODICE_SERVIZIO = @GS
	
		SELECT @DATARINRIN = MAX(LSRRIN_DATA_RINUNCIA_RINUNCIA)
		FROM LSRRIN
		WHERE
		LSRRIN_KEY_ID_RICEV = @CODLTM AND
		LSRRIN_FLAG_ANAG = '1' AND
		LSRRIN_CODICE_SERVIZIO = @GS 
	
		IF @DATARIN <= @DATARINRIN
		BEGIN
			SELECT @DATARIN = NULL
		END
	
	
		IF @GS = '05' ---BOLLO
		BEGIN
		------------------------------------------------------------------------------
		-- DATI BOLLO
		------------------------------------------------------------------------------
		
			SELECT @DATAADE = MAX(LSRCON_BOLLO_DATA_CONTRATTO)
			FROM LSRCON_BOLLO
			WHERE
			LSRCON_BOLLO_KEY_ID_RICEV = @CODLTM AND
			LSRCON_BOLLO_FLAG_ANAG = '1' AND
			LSRCON_BOLLO_TIPO_DOC = 'A'
	
			SELECT @DATAINVIO = MAX(LSRCON_BOLLO_DATA_INVIO_DOC)
			FROM LSRCON_BOLLO
			WHERE
			LSRCON_BOLLO_KEY_ID_RICEV = @CODLTM AND
			LSRCON_BOLLO_FLAG_ANAG = '1' AND
			LSRCON_BOLLO_TIPO_DOC = 'A' 
	
		
			IF @DATAADE < @DATAINVIO
			BEGIN
				SELECT @DATAADE = LSRCON_BOLLO_DATA_CONTRATTO
				FROM LSRCON_BOLLO
				WHERE
				LSRCON_BOLLO_KEY_ID_RICEV = @CODLTM AND
				LSRCON_BOLLO_FLAG_ANAG = '1' AND
				LSRCON_BOLLO_TIPO_DOC = 'A' AND
				LSRCON_BOLLO_DATA_INVIO_DOC = @DATAINVIO
	
				IF @DATAADE < @DATAINVIO
				BEGIN
					SELECT @DATAADE = @DATAINVIO
				END
			END
			
			
			SELECT @DATAINVIO = NULL
		
			SELECT @DATACON = MAX(LSRCON_BOLLO_DATA_CONTRATTO)
			FROM LSRCON_BOLLO
			WHERE
			LSRCON_BOLLO_KEY_ID_RICEV = @CODLTM AND
			LSRCON_BOLLO_FLAG_ANAG = '1' AND
			LSRCON_BOLLO_TIPO_DOC = 'C'
	
			SELECT @DATAINVIO = MAX(LSRCON_BOLLO_DATA_INVIO_DOC)
			FROM LSRCON_BOLLO
			WHERE
			LSRCON_BOLLO_KEY_ID_RICEV = @CODLTM AND
			LSRCON_BOLLO_FLAG_ANAG = '1' AND
			LSRCON_BOLLO_TIPO_DOC = 'C' 
	
		
			IF @DATACON < @DATAINVIO
			BEGIN
				SELECT @DATACON = LSRCON_BOLLO_DATA_CONTRATTO
				FROM LSRCON_BOLLO
				WHERE
				LSRCON_BOLLO_KEY_ID_RICEV = @CODLTM AND
				LSRCON_BOLLO_FLAG_ANAG = '1' AND
				LSRCON_BOLLO_TIPO_DOC = 'C' AND
				LSRCON_BOLLO_DATA_INVIO_DOC = @DATAINVIO
	
				IF @DATACON < @DATAINVIO
				BEGIN
					SELECT @DATACON = @DATAINVIO
				END
			END
			
		END
		
		IF @GS = '08' ---TRIS
		BEGIN
			SELECT @DATACON = MAX(LSRCON_GS_DATA_CONTRATTO)
			FROM LSRCON_GS
			WHERE
			LSRCON_GS_KEY_ID_RICEV = @CODLTM AND
			LSRCON_GS_FLAG_ANAG = '1' AND
			LSRCON_GS_CODICE_SERVIZIO = '08'
	
		
			SELECT @DATAFID = MAX(lsrfid_coni_data_doc)
			FROM LSRFID_CONI
			WHERE
			LSRFID_CONI_KEY_ID_RICEV = @CODLTM AND
			LSRFID_CONI_FLAG_ANAG = '1' AND
			LSRFID_CONI_ANNO_RIF = @ANNORIF
	
		
			-- APPOGGIO LA DATA DEI TULPS NELLA VARIABILE @DATAAPS
			SELECT @DATAAPS = MAX(lsrtlp_GS_data_rilascio) 
			FROM LSRTLP_GS
			WHERE 
			LSRTLP_GS_KEY_ID_RICEV = @CODLTM AND
			LSRTLP_GS_FLAG_ANAG='1' AND
			LSRTLP_GS_CODICE_SERVIZIO = '08'

			SELECT @DATANUO = MAX(lsrnuo_GS_data_nulla_osta)
			FROM LSRNUO_GS
			WHERE
			LSRNUO_GS_KEY_ID_RICEV = @CODLTM AND
			LSRNUO_GS_FLAG_ANAG = '1'	 AND
			LSRNUO_GS_CODICE_SERVIZIO = '08'
		END

		IF @GS = '02' ---GIOCHI PUBBLICI
		BEGIN
			SELECT @DATACON = MAX(LSRCON_GP_DATA_CONTRATTO)
			FROM LSRCON_GP
			WHERE
			LSRCON_GP_KEY_ID_RICEV = @CODLTM AND
			LSRCON_GP_FLAG_ANAG = '1' 
	
		
			SELECT @DATAFID = MAX(lsrfid_GP_data_doc)
			FROM LSRFID_GP
			WHERE
			LSRFID_GP_KEY_ID_RICEV = @CODLTM AND
			LSRFID_GP_FLAG_ANAG = '1' AND
			LSRFID_GP_ANNO_RIF = @ANNORIF
	
		
			-- APPOGGIO LA DATA DEI TULPS NELLA VARIABILE @DATAAPS
			SELECT @DATAAPS = MAX(lsrtlp_GS_data_rilascio) 
			FROM LSRTLP_GS
			WHERE 
			LSRTLP_GS_KEY_ID_RICEV = @CODLTM AND
			LSRTLP_GS_FLAG_ANAG='1' AND
			LSRTLP_GS_CODICE_SERVIZIO = '02'

			SELECT @DATANUO = MAX(lsrnuo_GS_data_nulla_osta)
			FROM LSRNUO_GS
			WHERE
			LSRNUO_GS_KEY_ID_RICEV = @CODLTM AND
			LSRNUO_GS_FLAG_ANAG = '1'	 AND
			LSRNUO_GS_CODICE_SERVIZIO = '02'
		END

	
		IF @GS = '09' ---GRATTA & VINCI
		BEGIN
			SELECT @DATACON = LSRCON_GEV_DATA_DOCUMENTO
			FROM LSRCON_GEV
			WHERE
			LSRCON_GEV_COD_LOTTO = @CODLTM AND
			LSRCON_GEV_FLAG_ANAG = '1' AND
			LSRCON_GEV_DATA_DOCUMENTO =
			(
				SELECT MAX(LSRCON_GEV_DATA_DOCUMENTO)
				FROM LSRCON_GEV
				WHERE
				LSRCON_GEV_COD_LOTTO = @CODLTM AND
				LSRCON_GEV_FLAG_ANAG = '1' 
			)
		
			SELECT @DATAFID = LSRFID_GEV_DATA_DOCUMENTO
			FROM LSRFID_GEV
			WHERE
			LSRFID_GEV_COD_LOTTO = @CODLTM AND
			LSRFID_GEV_FLAG_ANAG = '1' AND
			LSRFID_GEV_ANNO_RIF = @ANNORIF AND
			LSRFID_GEV_DATA_DOCUMENTO =
			(
				SELECT MAX(LSRFID_GEV_DATA_DOCUMENTO)
				FROM LSRFID_GEV
				WHERE
				LSRFID_GEV_COD_LOTTO = @CODLTM AND
				LSRFID_GEV_FLAG_ANAG = '1'  AND
				LSRFID_GEV_ANNO_RIF = @ANNORIF
			)
		
			SELECT @DATAQST = LSRQST_GEV_KEY_DATA_INS
			FROM LSRQST_GEV
			WHERE
			LSRQST_GEV_COD_LOTTO = @CODLTM AND
			LSRQST_GEV_FLAG_ANAG = '1' AND
			LSRQST_GEV_KEY_DATA_INS =
			(
				SELECT MAX(LSRQST_GEV_KEY_DATA_INS)
				FROM LSRQST_GEV
				WHERE
				LSRQST_GEV_COD_LOTTO = @CODLTM AND
				LSRQST_GEV_FLAG_ANAG = '1' 
			)
	
			SELECT @DATARIN = NULL
			SELECT @DATARINRIN = NULL
			
			SELECT @DATARIN = MAX(LSRRIN_GEV_DATA_RIN)
			FROM LSRRIN_GEV
			WHERE
			LSRRIN_GEV_COD_LOTTO = @CODLTM AND
			LSRRIN_GEV_FLAG_ANAG = '1'
		
			SELECT @DATARINRIN = MAX(LSRRIN_GEV_DATA_RIN_RIN)
			FROM LSRRIN_GEV
			WHERE
			LSRRIN_GEV_COD_LOTTO = @CODLTM AND
			LSRRIN_GEV_FLAG_ANAG = '1'
		
			IF @DATARIN <= @DATARINRIN
			BEGIN
				SELECT @DATARIN = NULL
			END
	
		END
		

	END
	

END
ELSE --GIOCO/SERVIZIO LIS
BEGIN
	SELECT @DATAINVIO = NULL
	
-------------------------------------------------
--CONTRATTO QUADRO
-------------------------------------------------
	SELECT @DATACON = LSRCON_LIS_DATA_CONTRATTO, @DATAINVIO = LSRCON_LIS_DATA_INVIO_DOC
	FROM LSRCON_LIS
	WHERE
	LSRCON_LIS_KEY_ID_RICEV = @CODLTM AND
	LSRCON_LIS_FLAG_ANAG = '1' AND
	LSRCON_LIS_DATA_INVIO_DOC =
	(
		SELECT MAX(LSRCON_LIS_DATA_INVIO_DOC)
		FROM LSRCON_LIS
		WHERE
		LSRCON_LIS_KEY_ID_RICEV = @CODLTM AND
		LSRCON_LIS_FLAG_ANAG = '1'
	)
	
	IF @DATACON IS NULL
	BEGIN
		SELECT @DATACON = @DATAINVIO
	END

-------------------------------------------------
--ADESIONE
-------------------------------------------------

	SELECT @DATAINVIO = NULL
	
	SELECT @DATAADE = LSRADE_LIS_DATA_CONTRATTO, @DATAINVIO = LSRADE_LIS_DATA_INVIO_DOC
	FROM LSRADE_LIS
	WHERE
	LSRADE_LIS_KEY_ID_RICEV = @CODLTM AND
	LSRADE_LIS_KEY_CATEGORIA + LSRADE_LIS_KEY_SERVIZIO + LSRADE_LIS_KEY_ATTIVITA = @GS AND
	LSRADE_LIS_FLAG_ANAG = '1' AND
	LSRADE_LIS_DATA_INVIO_DOC =
	(
		SELECT MAX(LSRADE_LIS_DATA_INVIO_DOC)
		FROM LSRADE_LIS
		WHERE
		LSRADE_LIS_KEY_ID_RICEV = @CODLTM AND
		LSRADE_LIS_KEY_CATEGORIA + LSRADE_LIS_KEY_SERVIZIO + LSRADE_LIS_KEY_ATTIVITA = @GS AND
		LSRADE_LIS_FLAG_ANAG = '1'
	)
	
	IF @DATAADE IS NULL
	BEGIN
		SELECT @DATAADE = @DATAINVIO
	END

-------------------------------------------------
--FIDEJUSSIONE
-------------------------------------------------

	SELECT @DATAINVIO = NULL
	
	SELECT @DATAFID = LSRFID_LIS_DATA_CONTRATTO, @DATAINVIO = LSRFID_LIS_DATA_INVIO_DOC
	FROM LSRFID_LIS
	WHERE
	LSRFID_LIS_KEY_ID_RICEV = @CODLTM AND
	LSRFID_LIS_KEY_CATEGORIA + LSRFID_LIS_KEY_SERVIZIO + LSRFID_LIS_KEY_ATTIVITA = @GS AND
	LSRFID_LIS_FLAG_ANAG = '1' AND
	LSRFID_LIS_DATA_INVIO_DOC =
	(
		SELECT MAX(LSRFID_LIS_DATA_INVIO_DOC)
		FROM LSRFID_LIS
		WHERE
		LSRFID_LIS_KEY_ID_RICEV = @CODLTM AND
		LSRFID_LIS_KEY_CATEGORIA + LSRFID_LIS_KEY_SERVIZIO + LSRFID_LIS_KEY_ATTIVITA = @GS AND
		LSRFID_LIS_FLAG_ANAG = '1'
	)
	
	IF @DATAFID IS NULL
	BEGIN
		SELECT @DATAFID = @DATAINVIO
	END

------------------------------------------------------------------
--AUTORIZZAZIONE SQUADRA CALCIO
------------------------------------------------------------------

	SELECT @DATAINVIO = NULL
	
	SELECT @DATAAUT = LSRAUT_LIS_DATA_CONTRATTO, @DATAINVIO = LSRAUT_LIS_DATA_INVIO_DOC
	FROM LSRAUT_LIS
	WHERE
	LSRAUT_LIS_KEY_ID_RICEV = @CODLTM AND
	LSRAUT_LIS_FLAG_ANAG = '1' AND
	LSRAUT_LIS_KEY_CATEGORIA + LSRAUT_LIS_KEY_SERVIZIO + LSRAUT_LIS_KEY_ATTIVITA = @GS AND
	LSRAUT_LIS_DATA_INVIO_DOC =
	(
		SELECT MAX(LSRAUT_LIS_DATA_INVIO_DOC)
		FROM LSRAUT_LIS
		WHERE
		LSRAUT_LIS_KEY_ID_RICEV = @CODLTM AND
		LSRAUT_LIS_KEY_CATEGORIA + LSRAUT_LIS_KEY_SERVIZIO + LSRAUT_LIS_KEY_ATTIVITA = @GS AND
		LSRAUT_LIS_FLAG_ANAG = '1'
	)
	
	IF @DATAAUT IS NULL
	BEGIN

		SELECT @DATAAUT = @DATAINVIO
	END

END
GO
