/****** Object:  StoredProcedure [dbo].[CARICA_CONCESSIONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CARICA_CONCESSIONI]

AS

DECLARE	

@RICEVR3			CHAR(6),
@TIPORECR3			CHAR(1),
@DATAPROVVR3		CHAR(8),
@PROGPROVVR3		CHAR(14),
@CAUSALER3			CHAR(40),
@FIRMAR3			CHAR(17),
@EMANATOR3			CHAR(25),
@DECORDALR3		CHAR(8),
@DECORALR3 			CHAR (8),
@TASSA 			CHAR(9),
@ANNO 			CHAR(4),
@MASSIMALE 			CHAR(11),
@CODTAB 			CHAR(10),
@DISPONIBILER3		CHAR(48),
@FLAGANNULLR3 		CHAR(1),
@DATAINSR3			CHAR(8),
@FIRMAANNULLR3		CHAR(17),
@DATAANNULLR3		CHAR(8),
@FILLERR3			CHAR(7),

@RICEVE1			CHAR(6),
@TIPORECE1			CHAR(1),
@COMUNENASC		CHAR(30),
@PROVNASC			CHAR(2),
@DATANASC			CHAR(8),
@SESSO			CHAR(1),
@CODFISC			CHAR(16),
@COGNOMEE1			CHAR(25),
@NOMEE1			CHAR(20),
@DISPONIBILEE1		CHAR(18),
@DECORDALE1		CHAR(8),
@DATAINSE1			CHAR(8),
@FLAGESEE1			CHAR(1),
@FILLERE1			CHAR(6),

@RICEVR1			CHAR(6),
@CODAMM			CHAR(6),
@QTATERM			CHAR(2),
@MODULO			CHAR(1),
@DATAATTIV			CHAR(8),
@DATACESSAZ		CHAR(8),
@DECODRICEV		CHAR(50),
@COMUNERICEV		CHAR(24),
@PROVRICEV			CHAR(2),
@CAP				CHAR(5),
@INDIRIZZO			CHAR(40),
@COGNOMER1		CHAR(24),
@NOMER1			CHAR(20),
@STATOR1			CHAR(1),
@TELRICEV			CHAR(12),
@TELCASA			CHAR(12),
@DECORDALR1		CHAR(8),
@LOTTO			CHAR(1),
@F101				CHAR(1),
@RAI				CHAR(1),
@INFO				CHAR(1),
@BOLLO			CHAR(1),
@BIG				CHAR(1),
@COMUNE			CHAR(1),
@TRIS				CHAR(1),
@FLAG9			CHAR(1),
@FLAG10			CHAR(1),
@FLAG11			CHAR(1),
@FLAG12			CHAR(1),
@FILLERR1			CHAR(4),
@SIGLAIC			CHAR(2),
@SIGLAREG			CHAR(2),
@CHIUSURA			CHAR(1),
@TABSPECIALI			CHAR(1),
@FILLER2R1			CHAR(1),
@CODMAGAZZ			CHAR(5),
@TAB				CHAR(4),
@ASSOCIAZIONE		CHAR(1),
@COMMUTATA		CHAR(1),
@DATAINSR1			CHAR(8),
@DATARIATTIV		CHAR(8),
@FLAGESER1			CHAR(1),
@TERMINST			CHAR(2),

@ORAINS  			CHAR (8),
@FLAGVAL 			CHAR(1) ,
@FTVOS 			CHAR (8),

@ESITO 			BIT,
@DATA			VARCHAR(11),
@STRINGA 			VARCHAR(100),
@MSGERR 			VARCHAR(100),

@NOMEJOB			VARCHAR(25)


SELECT @DATA = CONVERT (VARCHAR(10), GETDATE(),112)


SELECT @STRINGA = 'INIZIO CARICAMENTO NUOVE CONCESSIONI' + ' ' + @DATA
SELECT @NOMEJOB = 'AAEG012003UC'

EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
EXEC  MSDB..UT_AA004 9999, @NOMEJOB, '', 0


DECLARE CUR_R3 SCROLL CURSOR FOR
SELECT *
FROM LSR03A_CONC

OPEN CUR_R3
FETCH NEXT FROM CUR_R3 
INTO @RICEVR3,@TIPORECR3,@DATAPROVVR3,@PROGPROVVR3,@CAUSALER3,@FIRMAR3,
	@EMANATOR3, @DECORDALR3, @DECORALR3,@TASSA,@ANNO,@MASSIMALE,@CODTAB,
	@DISPONIBILER3, @FLAGANNULLR3,	@DATAINSR3,@FIRMAANNULLR3,@DATAANNULLR3,@FILLERR3
WHILE @@FETCH_STATUS = 0 
BEGIN

	IF @DECORDALR3 = '00000000' OR @DECORDALR3 = NULL OR @DECORDALR3 = ''
	BEGIN
		SELECT @DECORDALR3 = @DATAPROVVR3
	END

	IF @FLAGANNULLR3 <> '1'
	BEGIN

		SELECT @RICEVR1 =  LSR01A_KEY_ID_RICEV FROM LSR01A_CONC
		WHERE LSR01A_KEY_ID_RICEV = @RICEVR3

		SELECT @RICEVE1 =  LSE01A_KEY_ID_RICEV FROM LSE01A_CONC
		WHERE LSE01A_KEY_ID_RICEV = @RICEVR3
		AND LSE01A_KEY_TIPO_REC = 'T'

		IF @RICEVR1 IS NULL OR @RICEVR1 = ''
		BEGIN

			SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' NON PRESENTE SU LSR01A_CONC ' + @DATA
			RAISERROR (@MSGERR, 16, 1)
			EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0

			RETURN
		END
		ELSE IF @RICEVE1 IS  NULL OR @RICEVE1 = ''
		BEGIN
			SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' NON PRESENTE SU LSE01A_CONC ' + @DATA
			RAISERROR (@MSGERR, 16, 1)
			EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0

			RETURN
		END
		ELSE
		BEGIN
			SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
				SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
				SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
				SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

			DECLARE CUR_R1 SCROLL CURSOR FOR
			SELECT *
			FROM LSR01A_CONC
			WHERE LSR01A_KEY_ID_RICEV = @RICEVR3


			OPEN CUR_R1
			FETCH NEXT FROM CUR_R1 
			INTO @RICEVR1,@CODAMM,@QTATERM,@MODULO,@DATAATTIV,@DATACESSAZ,
			@DECODRICEV,@COMUNERICEV,@PROVRICEV,@CAP,@INDIRIZZO,@COGNOMER1,
			@NOMER1,@STATOR1,@TELRICEV,@TELCASA,@DECORDALR1,@LOTTO,@F101,
			@RAI,@INFO,@BOLLO,@BIG,@COMUNE,@TRIS,@FLAG9,@FLAG10,@FLAG11,@FLAG12,
			@FILLERR1,@SIGLAIC,@SIGLAREG,@CHIUSURA,@TABSPECIALI,@FILLER2R1,@CODMAGAZZ,
			@TAB,@ASSOCIAZIONE,@COMMUTATA,@DATAINSR1,@DATARIATTIV,@FLAGESER1,
			@TERMINST

			IF @@FETCH_STATUS = 0 
			BEGIN
				DECLARE CUR_E1 SCROLL CURSOR FOR
				SELECT *
				FROM LSE01A_CONC
				WHERE LSE01A_KEY_ID_RICEV = @RICEVR3
		
				OPEN CUR_E1
				FETCH NEXT FROM CUR_E1 
				INTO @RICEVE1,@TIPORECE1,@COMUNENASC,@PROVNASC,@DATANASC,
				@SESSO,@CODFISC,@COGNOMEE1,@NOMEE1,@DISPONIBILEE1,
				@DECORDALE1,@DATAINSE1,@FLAGESEE1,@FILLERE1
		
				BEGIN TRANSACTION
		
				INSERT INTO LSRPRO VALUES (
					@RICEVR3,@TIPORECR3,@DATAINSR3,@ORAINS,@DATAPROVVR3,
					@PROGPROVVR3,@CAUSALER3,@FIRMAR3,	@EMANATOR3,@DECORDALR3,
					@DECORALR3,@TASSA,@ANNO,@MASSIMALE,@CODTAB,
					@FLAGANNULLR3,'Y',@DATAINSR3)

				IF @@ERROR <> 0
				BEGIN
					SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRPRO ' + @ORAINS
					RAISERROR (@MSGERR, 16, 1)
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
		
					CLOSE CUR_R1
					DEALLOCATE CUR_R1

					CLOSE CUR_R3
					DEALLOCATE CUR_R3
		
					CLOSE CUR_E1
					DEALLOCATE CUR_E1
		
					ROLLBACK TRANSACTION

					RETURN
				END
		
		
				INSERT INTO LSRRIC VALUES (
				@RICEVR3,@DATAINSR3,@ORAINS,@CODAMM,@DATAATTIV,@DATACESSAZ,
				@DECODRICEV,@COMUNERICEV,@PROVRICEV,@CAP,@INDIRIZZO,@STATOR1,
				@TELRICEV,@SIGLAIC,@SIGLAREG,@CHIUSURA,@TABSPECIALI,@CODMAGAZZ,
				@DATARIATTIV,@FLAGESER1,@TERMINST,@TAB,@FIRMAR3,NULL,@DATAPROVVR3,
				@PROGPROVVR3,@TIPORECR3,@DECORDALR3,'00000000','Y',@DATAINSR3)
				IF @@ERROR <> 0
				BEGIN
					SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRRIC ' + @ORAINS
					RAISERROR(@MSGERR,16,1)
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
					ROLLBACK TRANSACTION

					CLOSE CUR_R1
					DEALLOCATE CUR_R1

					CLOSE CUR_R3
					DEALLOCATE CUR_R3

					CLOSE CUR_E1
					DEALLOCATE CUR_E1

					RETURN
				END
		
				INSERT INTO LSRTIT VALUES (
				@RICEVR3,@DATAINSR3,@ORAINS,NULL,@COGNOMER1,@NOMER1,@DATANASC,
				@COMUNENASC,@PROVNASC,@TELCASA,@TIPORECE1,NULL,@CODFISC,
				NULL,@SESSO,@FIRMAR3,@DATAPROVVR3,@PROGPROVVR3,@TIPORECR3,
				@DECORDALR3,'00000000','Y',@DATAINSR3)
				IF @@ERROR <> 0
				BEGIN
					SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRTIT ' + @ORAINS
					RAISERROR(@MSGERR,16,1)
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
					ROLLBACK TRANSACTION

					CLOSE CUR_R1
					DEALLOCATE CUR_R1

					CLOSE CUR_R3
					DEALLOCATE CUR_R3

					CLOSE CUR_E1
					DEALLOCATE CUR_E1

					RETURN
				END
		
				INSERT INTO LSRSER_LOTTO VALUES (
				@RICEVR3,@DATAINSR3,@ORAINS,@DECORDALR3,@STATOR1,@DATAPROVVR3,
				@PROGPROVVR3,@ASSOCIAZIONE,@FIRMAR3,'',@DATAINSR3,'Y')
				IF @@ERROR <> 0
				BEGIN
					SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRSER_LOTTO ' + @ORAINS
					RAISERROR(@MSGERR,16,1)
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
					ROLLBACK TRANSACTION

					CLOSE CUR_R1
					DEALLOCATE CUR_R1

					CLOSE CUR_R3
					DEALLOCATE CUR_R3

					CLOSE CUR_E1
					DEALLOCATE CUR_E1

					RETURN
				END

				-- CDS MODIFICA DEL 13/06/2008.
				-- INIZIALIZZO LA DATA DI REPOSNSABILITA' CONTABILE
				INSERT INTO LSRDATA_RESP_CONT VALUES (
				@RICEVR3,@DATAINSR3,@ORAINS,@DECORDALR3, '99999999')
				IF @@ERROR <> 0
				BEGIN
					SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRDATA_RESP_CONT ' + @ORAINS
					RAISERROR(@MSGERR,16,1)
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
					ROLLBACK TRANSACTION

					CLOSE CUR_R1
					DEALLOCATE CUR_R1

					CLOSE CUR_R3
					DEALLOCATE CUR_R3

					CLOSE CUR_E1
					DEALLOCATE CUR_E1

					RETURN
				END
		
				INSERT INTO LSRSER_TRIS VALUES (

					@RICEVR3,@DATAINSR3,@ORAINS,@TRIS,@DECORDALR3,
					@TIPORECR3,@DATAPROVVR3,@PROGPROVVR3,'',@FIRMAR3,
					'FLAG TRIS IMPOSTATO DAL PROVVEDIMENTO DI CONCESSIONE ',
					@DATAINSR3,'Y')
				IF @@ERROR <> 0
				BEGIN
					SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRSER_TRIS ' + @ORAINS
					RAISERROR(@MSGERR,16,1)
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
					ROLLBACK TRANSACTION

					CLOSE CUR_R1
					DEALLOCATE CUR_R1

					CLOSE CUR_R3
					DEALLOCATE CUR_R3

					CLOSE CUR_E1
					DEALLOCATE CUR_E1

					RETURN

				END

				INSERT INTO LSRSER_F101 VALUES (
					@RICEVR3,@DATAINSR3,@ORAINS,@F101,@DECORDALR3,
					@TIPORECR3,@DATAPROVVR3,@PROGPROVVR3,'',@FIRMAR3,
					'FLAG F101 IMPOSTATO DAL PROVVEDIMENTO DI CONCESSIONE ',
					@DATAINSR3,'Y')
				IF @@ERROR <> 0
				BEGIN
					SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRSER_F101 ' + @ORAINS
					RAISERROR(@MSGERR,16,1)
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
					EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
					ROLLBACK TRANSACTION

					CLOSE CUR_R1
					DEALLOCATE CUR_R1

					CLOSE CUR_R3
					DEALLOCATE CUR_R3

					CLOSE CUR_E1
					DEALLOCATE CUR_E1

					RETURN
				END

		
				IF @BOLLO <> '0'
				BEGIN
					INSERT INTO LSRSER_BOLLO VALUES (
					@RICEVR3,@DATAINSR3,@ORAINS,@BOLLO,@DECORDALR3,'',
					@TIPORECR3,@DATAPROVVR3,@PROGPROVVR3,'',@FIRMAR3,
					'FLAG BOLLO IMPOSTATO DAL PROVVEDIMENTO DI CONCESSIONE ',
					@DATAINSR3,'Y')
					IF @@ERROR <> 0
					BEGIN
						SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRSER_BOLLO ' + @ORAINS
						RAISERROR(@MSGERR,16,1)
						EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
						EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
						ROLLBACK TRANSACTION

						CLOSE CUR_R1
						DEALLOCATE CUR_R1

						CLOSE CUR_R3
						DEALLOCATE CUR_R3

						CLOSE CUR_E1
						DEALLOCATE CUR_E1

						RETURN
					END
				END
		
			COMMIT TRANSACTION
		
			CLOSE CUR_R1
			DEALLOCATE CUR_R1
		
			CLOSE CUR_E1
			DEALLOCATE CUR_E1
		END
		
	END
		
	END
	ELSE
	BEGIN

	BEGIN TRANSACTION
---INIZIO MODIFICA DEL 30/07/2001
--	INSERT INTO LSRPRO VALUES (
--			@RICEVR3,@TIPORECR3,@DATAINSR3,@ORAINS,@DATAPROVVR3,
--			@PROGPROVVR3,@CAUSALER3,@FIRMAANNULLR3,@EMANATOR3,@DATAANNULLR3,
--			@DECORALR3,@TASSA,@ANNO,@MASSIMALE,@CODTAB,
--			@FLAGANNULLR3,'Y',@DATAINSR3)

	INSERT INTO LSRPRO VALUES (
			@RICEVR3,@TIPORECR3,@DATAANNULLR3,'00000000',@DATAANNULLR3,
			@PROGPROVVR3,@CAUSALER3,@FIRMAANNULLR3,@EMANATOR3,@DATAANNULLR3,
			@DECORALR3,@TASSA,@ANNO,@MASSIMALE,@CODTAB,
			@FLAGANNULLR3,'Y',@DATAINSR3)
---FINE MODIFICA DEL 30/07/2001

	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = '9999 ' +  @RICEVR3 + ' ERRORE IN INSERT SU LSRPRO ' + @ORAINS
		RAISERROR(@MSGERR,16,1)
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA IN MODO ANOMALO', 0
		ROLLBACK TRANSACTION

		CLOSE CUR_R1
		DEALLOCATE CUR_R1
		
		RETURN
	END

	COMMIT TRANSACTION
	END


	FETCH NEXT FROM CUR_R3 
	INTO @RICEVR3,@TIPORECR3,@DATAPROVVR3,@PROGPROVVR3,@CAUSALER3,@FIRMAR3,
		@EMANATOR3,@DECORDALR3,@DECORALR3,@TASSA,@ANNO,@MASSIMALE,@CODTAB,
		@DISPONIBILER3, @FLAGANNULLR3,	@DATAINSR3,@FIRMAANNULLR3,@DATAANNULLR3,@FILLERR3

END
CLOSE CUR_R3
DEALLOCATE CUR_R3

EXEC  MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_CONCESSIONI TERMINATA CORRETTAMENTE', 0
GO
