/****** Object:  StoredProcedure [dbo].[CARICA_ATTIVAZIONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CARICA_ATTIVAZIONI]

		@MSGERR 		VARCHAR(100)	OUTPUT

AS


DECLARE	@RICEV		CHAR(6),
		@DATAATTIV		CHAR(8),
		@ASSO		CHAR(1),
		@OGGI			CHAR(8),
		@IERI			CHAR(8),
		@ORAINS		CHAR(8),

		@ESITO 		BIT,
		@STRINGA 		VARCHAR(100),
		@FILEDILOG		VARCHAR(80),
@PATHID		INT,
@NOMEJOB	VARCHAR(15)


SELECT @OGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @IERI = CONVERT (VARCHAR(10), GETDATE() - 1,112)

SELECT @ORAINS =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)

SELECT @STRINGA = 'INIZIO CARICAMENTO NUOVE ATTIVAZIONI' + ' ' + @OGGI
SELECT @PATHID = 83
SELECT @NOMEJOB = 'AAEG012002UC'

EXEC MSDB..UT_AA004 9999, @NOMEJOB, '', 0
EXEC MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
EXEC MSDB..UT_AA004 9999, @NOMEJOB, '', 0

DECLARE CUR_R1 SCROLL CURSOR FOR
SELECT LSR01A_KEY_ID_RICEV,LSR01A_DATA_ATTIV,LSR01A_ASSOCIAZIONE
FROM LSR01A_ATT

BEGIN TRANSACTION

OPEN CUR_R1
FETCH NEXT FROM CUR_R1
INTO @RICEV,@DATAATTIV,@ASSO
WHILE @@FETCH_STATUS = 0 

BEGIN
	INSERT INTO LSRSER_LOTTO  VALUES (@RICEV,@OGGI,@ORAINS,@DATAATTIV,'A',NULL,NULL,@ASSO,'VOS','',@OGGI,'Y')

	IF @@ERROR <> 0
	BEGIN
		SELECT @MSGERR = '9999 ' +  @RICEV + ' ERRORE IN INSERT SU LSRSER_LOTTO ' + @ORAINS
		RAISERROR(@MSGERR,16,1)
		EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
		EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CARICA_ATTIVAZIONI TERMINATA IN MODO ANOMALO', 0
		ROLLBACK TRANSACTION
		RETURN
	END

FETCH NEXT FROM CUR_R1		
INTO @RICEV,@DATAATTIV,@ASSO

END

COMMIT TRANSACTION

CLOSE CUR_R1
DEALLOCATE CUR_R1
GO
