/****** Object:  StoredProcedure [dbo].[CREA_LSRFLAG]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROCEDURE [dbo].[CREA_LSRFLAG] 


AS

DECLARE

@IERI 			CHAR(8),
@OGGI 		CHAR(8),
@RICEVITORIA 	CHAR(6),
@RICEVITORIAB 	CHAR(6),
@STATORICEV 	CHAR(1),
@STATOLOTTO 	CHAR(1),
@STATOBOLLO 	CHAR(1),
@STATOTRIS 		CHAR(1),
@STATOF101 		CHAR(1),
@STATOSERTEL 	CHAR(1),
@STATOBIG 		CHAR(1),
@STATOCOMUNE 	CHAR(1),
@STATORAI 		CHAR(1),
@STATOGEV 		CHAR(1),
@STATOCONI	CHAR(1),
@STATOST	CHAR(1),

@STRINGA 		VARCHAR(100),
@MSGERR		VARCHAR(100),
@FLAG 		INT,
@NOMEJOB		VARCHAR(25)

SELECT @NOMEJOB = 'AAEG012001UC'

SELECT @OGGI = CONVERT(CHAR(8), GETDATE(), 112)

SELECT @IERI = CONVERT(CHAR(8), GETDATE() - 1, 112)

DELETE FROM LSRFLAG

DECLARE CUR_RIC CURSOR FOR 
SELECT LSRRIC_KEY_ID_RICEV
FROM LSRRIC A
WHERE LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA = 
	(SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) FROM LSRRIC B
	 WHERE ((LSRRIC_DATA_VALIDITA <= @OGGI AND LSRRIC_KEY_DATA_INS =  @IERI)
	OR LSRRIC_DATA_VALIDITA =  @OGGI)
AND B.LSRRIC_KEY_ID_RICEV = A.LSRRIC_KEY_ID_RICEV
AND LSRRIC_FLAG_VALIDITA = 'Y'
AND LSRRIC_FT_VOS = '00000000') 
AND LSRRIC_FLAG_VALIDITA = 'Y'
AND LSRRIC_FT_VOS = '00000000'
and LSRRIC_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL
	
	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG
	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_RIC = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END
	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  

CLOSE CUR_RIC
DEALLOCATE CUR_RIC

--TRATTAMENTO LSRTIT
DECLARE CUR_RIC CURSOR FOR 
SELECT LSRTIT_KEY_ID_RICEV
FROM LSRTIT A
WHERE LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA = 
	(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) FROM LSRTIT B
	WHERE ((LSRTIT_DATA_VALIDITA <= @OGGI AND LSRTIT_KEY_DATA_INS =  @IERI)
	OR LSRTIT_DATA_VALIDITA =  @OGGI)
AND B.LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV
AND LSRTIT_FLAG_VALIDITA = 'Y'
AND LSRTIT_FT_VOS = '00000000') 
AND LSRTIT_FLAG_VALIDITA = 'Y'
AND LSRTIT_FT_VOS = '00000000'
and LSRTIT_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL

	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG
	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_TIT = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  


CLOSE CUR_RIC
DEALLOCATE CUR_RIC

--TRATTAMENTO LSRSER_LOTTO
DECLARE CUR_RIC CURSOR FOR 
SELECT LSRSER_LOTTO_KEY_ID_RICEV
FROM LSRSER_LOTTO A
WHERE LSRSER_LOTTO_DATA_DECOR = 
	(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO B
	WHERE ((LSRSER_LOTTO_DATA_DECOR <= @OGGI AND LSRSER_LOTTO_KEY_DATA_INS =  @IERI)
	OR LSRSER_LOTTO_DATA_DECOR =  @OGGI)
AND B.LSRSER_LOTTO_KEY_ID_RICEV = A.LSRSER_LOTTO_KEY_ID_RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_FT_VOS = '00000000')
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_FT_VOS = '00000000'
and LSRSER_LOTTO_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL

	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG
	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_LOTTO = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,NULL,NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END


	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  

CLOSE CUR_RIC
DEALLOCATE CUR_RIC

--******************************************
--CDS: 2007/06/27
--E' STATO SOSTITUITO LSRSER_F101 CON LSRSER_GP
--******************************************
--TRATTAMENTO LSRSER_GP
DECLARE CUR_RIC CURSOR FOR 
SELECT LSRSER_GP_KEY_ID_RICEV
FROM LSRSER_GP A
WHERE LSRSER_GP_DATA_DECOR = 
	(SELECT MAX(LSRSER_GP_DATA_DECOR) FROM LSRSER_GP B
	 WHERE ((LSRSER_GP_DATA_DECOR <= @OGGI AND LSRSER_GP_KEY_DATA_INS =  @IERI)
	OR LSRSER_GP_DATA_DECOR =  @OGGI)
AND B.LSRSER_GP_KEY_ID_RICEV = A.LSRSER_GP_KEY_ID_RICEV
AND LSRSER_GP_FLAG_VALIDITA = 'Y'
AND LSRSER_GP_FT_VOS = '00000000')
AND LSRSER_GP_FLAG_VALIDITA = 'Y'
AND LSRSER_GP_FT_VOS = '00000000'
and LSRSER_GP_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL

	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG
	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_F101 = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,NULL,NULL,NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  

CLOSE CUR_RIC
DEALLOCATE CUR_RIC

--TRATTAMENTO LSRSER_BOLLO
DECLARE CUR_RIC CURSOR FOR 
SELECT LSRSER_BOLLO_KEY_ID_RICEV
FROM LSRSER_BOLLO A
WHERE LSRSER_BOLLO_DATA_DECOR = 
	(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO B
	WHERE ((LSRSER_BOLLO_DATA_DECOR <= @OGGI AND LSRSER_BOLLO_KEY_DATA_INS =  @IERI)
	OR LSRSER_BOLLO_DATA_DECOR =  @OGGI)
AND B.LSRSER_BOLLO_KEY_ID_RICEV = A.LSRSER_BOLLO_KEY_ID_RICEV
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_FT_VOS = '00000000')
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_FT_VOS = '00000000'
and LSRSER_BOLLO_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL

	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG

	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_BOLLO = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL,NULL,NULL,NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  

CLOSE CUR_RIC
DEALLOCATE CUR_RIC

--TRATTAMENTO LSRSER_TRIS
DECLARE CUR_RIC CURSOR FOR 
SELECT LSRSER_TRIS_KEY_ID_RICEV
FROM LSRSER_TRIS A
WHERE LSRSER_TRIS_DATA_DECOR = 
	(SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS B
	WHERE ((LSRSER_TRIS_DATA_DECOR <= @OGGI
	AND LSRSER_TRIS_KEY_DATA_INS =  @IERI)
	OR LSRSER_TRIS_DATA_DECOR =  @OGGI)
AND B.LSRSER_TRIS_KEY_ID_RICEV = A.LSRSER_TRIS_KEY_ID_RICEV
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
AND LSRSER_TRIS_FT_VOS = '00000000')
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
AND LSRSER_TRIS_FT_VOS = '00000000'
and LSRSER_TRIS_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL

	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG
	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_TRIS = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL,NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  


CLOSE CUR_RIC
DEALLOCATE CUR_RIC

--TRATTAMENTO LSRSER_CONI
DECLARE CUR_RIC CURSOR FOR 
SELECT LSRSER_CONI_KEY_ID_RICEV
FROM LSRSER_CONI A
WHERE LSRSER_CONI_DATA_DECOR = 
	(SELECT MAX(LSRSER_CONI_DATA_DECOR) FROM LSRSER_CONI B
	WHERE ((LSRSER_CONI_DATA_DECOR <= @OGGI
	AND LSRSER_CONI_KEY_DATA_INS =  @IERI)
	OR LSRSER_CONI_DATA_DECOR =  @OGGI)
AND B.LSRSER_CONI_KEY_ID_RICEV = A.LSRSER_CONI_KEY_ID_RICEV
AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
AND LSRSER_CONI_FT_VOS = '00000000')
AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
AND LSRSER_CONI_FT_VOS = '00000000'
and LSRSER_CONI_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL

	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG
	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_CONI = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0

		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  


CLOSE CUR_RIC
DEALLOCATE CUR_RIC


--TRATTAMENTO LSRSER_ST
DECLARE CUR_RIC CURSOR FOR 
SELECT LSRSER_ST_KEY_ID_RICEV
FROM LSRSER_ST A
WHERE LSRSER_ST_DATA_DECOR = 
	(SELECT MAX(LSRSER_ST_DATA_DECOR) FROM LSRSER_ST B
	WHERE ((LSRSER_ST_DATA_DECOR <= @OGGI
	AND LSRSER_ST_KEY_DATA_INS =  @IERI)
	OR LSRSER_ST_DATA_DECOR =  @OGGI)
AND B.LSRSER_ST_KEY_ID_RICEV = A.LSRSER_ST_KEY_ID_RICEV
AND LSRSER_ST_FLAG_VALIDITA = 'Y'
AND LSRSER_ST_FT_VOS = '00000000')
AND LSRSER_ST_FLAG_VALIDITA = 'Y'
AND LSRSER_ST_FT_VOS = '00000000'
and LSRSER_ST_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)

OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL

	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG
	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_ST = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0

		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y')

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  


CLOSE CUR_RIC
DEALLOCATE CUR_RIC


--TRATTAMENTO LSRSER_GEV
DECLARE CUR_RIC CURSOR FOR 
SELECT LSRSER_GEV_KEY_ID_RICEV
FROM LSRSER_GEV A
WHERE LSRSER_GEV_DATA_DECOR = 
	(SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV B
	WHERE ((LSRSER_GEV_DATA_DECOR <= @OGGI
	AND LSRSER_GEV_KEY_DATA_INS =  @IERI)
	OR LSRSER_GEV_DATA_DECOR =  @OGGI)
AND B.LSRSER_GEV_KEY_ID_RICEV = A.LSRSER_GEV_KEY_ID_RICEV
AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
AND LSRSER_GEV_FT_VOS = '00000000')
AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
AND LSRSER_GEV_FT_VOS = '00000000'
and LSRSER_GEV_KEY_ID_RICEV  not in (select distinct(key_id_ricev) from ttb_v)


OPEN CUR_RIC
FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
WHILE @@FETCH_STATUS = 0 
BEGIN
	SELECT @RICEVITORIAB = NULL

	SELECT @RICEVITORIAB = LSRFLAG_KEY_ID_RICEV
	FROM LSRFLAG
	WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

	IF @RICEVITORIAB IS NOT NULL
	BEGIN
		UPDATE LSRFLAG
		SET LSRFLAG_GEV = 'Y'
		WHERE LSRFLAG_KEY_ID_RICEV = @RICEVITORIA

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN UPDATE LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END
	ELSE
	BEGIN
		INSERT INTO LSRFLAG
		VALUES (@RICEVITORIA,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y',NULL,NULL)

		IF @@ERROR <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE IN INSERT LSRFLAG'
			RAISERROR (@MSGERR, 16, 1)
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, @MSGERR, 0
			EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA IN MODO ANOMALO', 0

			CLOSE CUR_RIC
			DEALLOCATE CUR_RIC

			RETURN
		END

	END

	FETCH NEXT FROM CUR_RIC INTO @RICEVITORIA
END  


CLOSE CUR_RIC
DEALLOCATE CUR_RIC



EXEC MSDB..UT_AA004 9999, @NOMEJOB, 'S.P. CREA_LSRFLAG TERMINATA CORRETTAMENTE', 0
GO
