/****** Object:  StoredProcedure [dbo].[GEV_VARIAZIONE_CONTRATTI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[GEV_VARIAZIONE_CONTRATTI] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATADOC		CHAR(8),
@DATAINVIODOC	CHAR(8),
@NUMDOC		VARCHAR(25),
@COGNOME		VARCHAR(24),
@NOME		VARCHAR(20),
@ASSOCIAZIONE	CHAR(1),

@COMRES		CHAR(24),
@PROVRES		CHAR(2),
@CAPRES		CHAR(5),
@INDRES		CHAR(40),

@COMSPE		CHAR(24),
@PROVSPE		CHAR(2),
@CAPSPE		CHAR(5),
@INDSPE		CHAR(40),
@INOMESPE		CHAR(44),

@NUMTEL		CHAR(12),
@COMFIS		CHAR(24),
@PROVFIS		CHAR(2),
@CAPFIS		CHAR(5),
@INDFIS		CHAR(40),
@CODFIS		CHAR(16),
@PRTIVA		CHAR(11),
@NUMPACCHI		VARCHAR(10),

@NUMKITUNO		VARCHAR(10),
@NUMKITDUE		VARCHAR(10),
@DATAORAACQORD	VARCHAR(16),

@CODMERCEOLOGICO	CHAR(2),
@EMAIL		VARCHAR(100),

@FLAGNUOVOCON	CHAR(1),
@DATANUOVOCON	CHAR(8),

@FLGANAG		CHAR(1),
@FKINSTIT		VARCHAR(16),
@FKINSDOC		VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)


AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSDOC	CHAR(8),
@FKORAINSDOC	CHAR(8),
@FKDATAINSGEV	CHAR(8),
@FKORAINSGEV	CHAR(8),

@DATAINSORD	CHAR(8),
@ORAINSORD		CHAR(8),

@FLGANAGOLD	CHAR(1),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20)


SELECT @RICEAPPO = NULL
SELECT @FKDATAINSTIT = NULL
SELECT @FKORAINSTIT = NULL
SELECT @FKDATAINSGEV = NULL
SELECT @FKORAINSGEV = NULL

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
BEGIN
	SELECT @FKDATAINSGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSGEV = SUBSTRING(@FKINSTIT, 9, 8)
END
ELSE
BEGIN

	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)
END


SELECT @FKDATAINSDOC = SUBSTRING(@FKINSDOC, 1, 8)
SELECT @FKORAINSDOC = SUBSTRING(@FKINSDOC, 9, 8)

SELECT @DATAINSORD = SUBSTRING(@DATAORAACQORD, 1, 8)
SELECT @ORAINSORD = SUBSTRING(@DATAORAACQORD, 9, 8)

--------------------------------------------------------------------------------------------------------------------------------
-- CONTROLLO SE I DATI IN INPUT NON SIANO GIA' PRESENTI IN TABELLA
--------------------------------------------------------------------------------------------------------------------------------

SELECT @RICEAPPO = NULL
/*

SELECT @RICEAPPO = LSRCON_GEV_KEY_ID_RICEV
FROM LSRCON_GEV
WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
AND LSRCON_GEV_DATA_DOCUMENTO = @DATADOC
AND LSRCON_GEV_DATA_INVIO_DOC = @DATAINVIODOC
AND LSRCON_GEV_NUM_PROT_DOC = @NUMDOC
AND LSRCON_GEV_ASSOCIAZIONE = @ASSOCIAZIONE
AND LSRCON_GEV_NOME = @NOME
AND LSRCON_GEV_COGNOME = @COGNOME

AND lsrcon_GeV_comune_residenza = @COMRES		
AND lsrcon_GeV_provincia_residenza = @PROVRES	
AND lsrcon_GeV_cap_residenza = @CAPRES	
AND lsrcon_GeV_indirizzo_residenza = @INDRES	
AND lsrcon_GeV_telefono = @NUMTEL	
AND lsrcon_GeV_comune = @COMFIS	
AND lsrcon_GeV_provincia = @PROVFIS	
AND lsrcon_GeV_cap = @CAPFIS		
AND lsrcon_GeV_indirizzo = @INDFIS		
AND lsrcon_GeV_cod_fisc = @CODFIS		
AND lsrcon_GeV_partita_iva = @PRTIVA		
and lsrcon_gev_numero_pacchi = @NUMPACCHI

AND LSRCON_GEV_NOTE = @NOTE
AND LSRCON_GEV_FLAG_ANAG = @FLGANAG
AND LSRCON_GEV_KEY_DATA_INS = @FKDATAINSDOC
AND LSRCON_GEV_KEY_ORA_INS = @FKORAINSDOC



IF @RICEAPPO IS NOT NULL
BEGIN
	SELECT @MSGERR = '9 - I DATI INSERITI SONO GIA PRESENTI IN TABELLA'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

*/
--------------------------------------------------------------------------------------------------------------------------------
-- EFFETTUO I CONTROLLI SU FLAGANAG
--------------------------------------------------------------------------------------------------------------------------------

SELECT @FLGANAGOLD = NULL

SELECT @FLGANAGOLD = LSRCON_GEV_FLAG_ANAG
FROM LSRCON_GEV
WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
AND LSRCON_GEV_KEY_DATA_INS = @FKDATAINSDOC
AND LSRCON_GEV_KEY_ORA_INS = @FKORAINSDOC

IF @FLGANAGOLD = '0' AND @FLGANAG <> '0'
BEGIN

	SELECT @RICEAPPO = NULL

	SELECT @COGNOMEOLD = NULL
	SELECT @NOMEOLD = NULL
	
	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		SELECT @RICEAPPO = LSRCON_GEV_KEY_ID_RICEV 
		FROM LSRCON_GEV
		WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRCON_GEV_FK_DATA_INS_TIT_GEV = @FKDATAINSGEV
		AND LSRCON_GEV_FK_ORA_INS_TIT_GEV = @FKORAINSGEV
	ELSE
		SELECT @RICEAPPO = LSRCON_GEV_KEY_ID_RICEV 
		FROM LSRCON_GEV
		WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRCON_GEV_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRCON_GEV_FK_ORA_INS_TIT = @FKORAINSTIT


	IF @RICEAPPO IS NOT NULL
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO ASSOCIATO AL TITOLARE INDICATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END


IF @FLGANAGOLD = '0' AND @FLGANAG =  '0'
BEGIN
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSGEV = NULL
	SELECT @FKORAINSGEV = NULL

end

BEGIN TRANSACTION



UPDATE LSRCON_GEV SET
LSRCON_GEV_DATA_DOCUMENTO = @DATADOC,
LSRCON_GEV_DATA_INVIO_DOC = @DATAINVIODOC,
LSRCON_GEV_NUM_PROT_DOC = @NUMDOC,
LSRCON_GEV_ASSOCIAZIONE = @ASSOCIAZIONE,
LSRCON_GEV_NOME = @NOME,
LSRCON_GEV_COGNOME = @COGNOME,

lsrcon_GeV_comune_residenza = @COMRES,		
lsrcon_GeV_provincia_residenza = @PROVRES,	
lsrcon_GeV_cap_residenza = @CAPRES,	
lsrcon_GeV_indirizzo_residenza = @INDRES,	

lsrcon_GeV_comune_spedizione = @COMSPE,
 lsrcon_GeV_provincia_spedizione = @PROVSPE,
lsrcon_GeV_cap_spedizione = @CAPSPE,
lsrcon_GeV_indirizzo_spedizione = @INDSPE,
lsrcon_GeV_referente_spedizione = @INOMESPE,

lsrcon_GeV_telefono = @NUMTEL,	
lsrcon_GeV_comune = @COMFIS,
lsrcon_GeV_provincia = @PROVFIS,	
lsrcon_GeV_cap = @CAPFIS,		
lsrcon_GeV_indirizzo = @INDFIS,		
lsrcon_GeV_cod_fisc = @CODFIS,		
lsrcon_GeV_partita_iva = @PRTIVA,		
lsrcon_gev_numero_pacchi = @NUMPACCHI,
LSRCON_GEV_NOTE = @NOTE,
lsrcon_gev_cod_merce = @CODMERCEOLOGICO,
LSRCON_GEV_FLAG_ANAG = @FLGANAG,
LSRCON_GEV_EMAIL = @EMAIL,

LSRCON_GEV_FLAG_NUOVO_CON = @FLAGNUOVOCON,
LSRCON_GEV_DATA_NUOVO_CON = @DATANUOVOCON,

lsrcon_GeV_fk_data_ins_tit = @FKDATAINSTIT,
lsrcon_GeV_fk_ora_ins_tit = @FKORAINSTIT,
lsrcon_GeV_fk_data_ins_tit_gev = @FKDATAINSGEV,
lsrcon_GeV_fk_ora_ins_tit_gev = @FKORAINSGEV
WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
AND LSRCON_GEV_KEY_DATA_INS = @FKDATAINSDOC 
AND LSRCON_GEV_KEY_ORA_INS = @FKORAINSDOC

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN VARIAZIONE DOCUMENTO - RICEVITORIA: ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

ELSE
BEGIN	
/*
	UPDATE LSRORD_GEV
	SET LSRORD_GEV_NUMERO_PACCHI = @NUMKITUNO,
		LSRORD_GEV_FLAG_ANAG = @FLGANAG,
		lsrORD_GeV_fk_data_ins_tit = @FKDATAINSTIT,
		lsrORD_GeV_fk_ora_ins_tit = @FKORAINSTIT,
		lsrORD_GeV_fk_data_ins_tit_gev = @FKDATAINSGEV,
		lsrORD_GeV_fk_ora_ins_tit_gev = @FKORAINSGEV
	WHERE LSRORD_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRORD_GEV_KEY_ID_GIO = '1'
		AND LSRORD_GEV_KEY_DATA_INS = @DATAINSORD 
		AND LSRORD_GEV_KEY_ORA_INS = @ORAINSORD 

	UPDATE LSRORD_GEV
	SET LSRORD_GEV_NUMERO_PACCHI = @NUMKITDUE,
		LSRORD_GEV_FLAG_ANAG = @FLGANAG,
		lsrORD_GeV_fk_data_ins_tit = @FKDATAINSTIT,
		lsrORD_GeV_fk_ora_ins_tit = @FKORAINSTIT,
		lsrORD_GeV_fk_data_ins_tit_gev = @FKDATAINSGEV,
		lsrORD_GeV_fk_ora_ins_tit_gev = @FKORAINSGEV
	WHERE LSRORD_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRORD_GEV_KEY_ID_GIO = '2'
		AND LSRORD_GEV_KEY_DATA_INS = @DATAINSORD 
		AND LSRORD_GEV_KEY_ORA_INS = @ORAINSORD 

*/
	COMMIT TRANSACTION
END
GO
