/****** Object:  StoredProcedure [dbo].[IC_AUTORIZZA_SOSTITUZIONE]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE      PROCEDURE [dbo].[IC_AUTORIZZA_SOSTITUZIONE]  
 
      @LTMS             CHAR(6),
      @LTMDS                  CHAR(6),
      @DATAI                  CHAR(8),
      @DATAF                  CHAR(8),
      @FIRMA                  CHAR(17),
      @CAUSALE                CHAR(2),
      @UFFICIO                CHAR(5),
      @FLGINS                 CHAR(1),
      @OLDLTMS                CHAR(6),
      @OLDLTMDS               CHAR(6),
      @OLDDATAI               CHAR(8),
      @RC                     VARCHAR(100)  OUTPUT
 
AS
 
DECLARE
 
@RUOTAS           CHAR(2),
@RUOTADS          CHAR(2),
@RICEVS           CHAR(6),
@RICEVDS          CHAR(6),
@CHK_DATAI        CHAR(8),
@CHK_DATAF        CHAR(8),
@STATO            CHAR(1),
@CHK_ANNUL        CHAR(1),
@DATAINS          CHAR(8),
@ORAINS           CHAR(8),
@ENTE             CHAR(2),
@PROV             CHAR(2),
@IC               CHAR(2),
@PROG             CHAR(1),
@MILLENNIO        CHAR(1),
@TIPOAGG          CHAR(1)

--PRINT 'INIZIO'

IF    ISNUMERIC(@DATAI) = 0 OR ISDATE(@DATAI) = 0
BEGIN
      SELECT @RC = 'FORMATO DATA INIZIO FERIE IN INPUT ERRATO'
      RETURN
END
 
IF    ISNUMERIC(@DATAF) = 0 OR ISDATE(@DATAF) = 0
BEGIN
      SELECT @RC = 'FORMATO DATA FINE FERIE IN INPUT ERRATO'
      RETURN
END
 
IF @DATAF < @DATAI 
BEGIN
      SELECT @RC = 'DATA FINE < DATA INIZIO, CONTROLLARE DATE IN INPUT'
      RETURN
END

SELECT @DATAINS = CONVERT(CHAR(8),GETDATE(),112)
 
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2)+
                  SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2)+
                  SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2)+
                  SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)
 
 
SELECT @ENTE = SUBSTRING(@UFFICIO,1,2)  -- ES.: DG, IC
SELECT @PROV = SUBSTRING(@UFFICIO,3,2)
SELECT @PROG = SUBSTRING(@UFFICIO,5,1)
 
 
SELECT @RICEVDS = NULL
SELECT @RICEVS = NULL
 
--VERIFICO L'ESISTENZA DELLA RICEVITORIA DA SOSTITUIRE E A QUALE ISPETTORATO APPARTIENE
SELECT DISTINCT @RICEVDS = LSRRIC_KEY_ID_RICEV, @IC = LSRRIC_SIGLA_IC
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @LTMDS
AND LSRRIC_FLAG_VALIDITA = 'Y'
AND LSRRIC_DATA_VALIDITA = 
(SELECT MAX(LSRRIC_DATA_VALIDITA) 
FROM LSRRIC 
WHERE LSRRIC_KEY_ID_RICEV = @LTMDS 
AND LSRRIC_FLAG_VALIDITA = 'Y'
AND LSRRIC_DATA_VALIDITA <= @DATAINS)
 
IF @RICEVDS IS NULL OR @RICEVDS = ''
BEGIN
      SELECT @RC = 'RICEVITORIA DA SOSTITUIRE - ' + @RICEVDS + ' - INESISTENTE'
      RETURN
END
 
IF @ENTE = 'IC'
BEGIN
      IF @IC <> @PROV
      BEGIN
            SELECT @RC = 'ISPETTORATO DI ' + @PROV + ' NON COMPETENTE PER LA RICEVITORIA - ' + @RICEVDS 
            RETURN
      END
END
 
--PRINT ' ctrl 1 '

--VERIFICO L'ESISTENZA DELLA RICEVITORIA DA SOSTITUTIVA E A QUALE ISPETTORATO APPARTIENE
SELECT DISTINCT @RICEVS = LSRRIC_KEY_ID_RICEV, @IC = LSRRIC_SIGLA_IC
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @LTMS
AND LSRRIC_FLAG_VALIDITA = 'Y'
AND LSRRIC_DATA_VALIDITA = 
(SELECT MAX(LSRRIC_DATA_VALIDITA) 
FROM LSRRIC 
WHERE LSRRIC_KEY_ID_RICEV = @LTMS 
AND LSRRIC_FLAG_VALIDITA = 'Y'
AND LSRRIC_DATA_VALIDITA <= @DATAINS)
 
IF @RICEVS IS NULL OR @RICEVS = ''
BEGIN
      SELECT @RC = 'RICEVITORIA SOSTITUTIVA - ' + @RICEVS + ' - INESISTENTE'
      RETURN
END

 
IF @ENTE = 'IC'
BEGIN
      IF @IC <> @PROV
      BEGIN
            SELECT @RC = 'ISPETTORATO DI ' + @PROV + ' NON COMPETENTE PER LA RICEVITORIA - ' + @RICEVS 
            RETURN
      END
END

--PRINT ' ctrl 2 '
 
--SELECT @RUOTADS = NULL
--SELECT @RUOTAS = NULL
 
--SELECT @RUOTADS = SUBSTRING(@RICEVDS,1,2)
--SELECT @RUOTAS = SUBSTRING(@RICEVS,1,2)
 
--IF @RUOTADS <> @RUOTAS
--BEGIN
      --SELECT @RC = 'LE DUE RICEVITORIE NON APPARTENGONO ALLA STESSA RUOTA'
      --RETURN
--END
 
 
--VERIFICO LO STATO DELLA RICEVITORIA SOSTITUTIVA ALLA DATA DI INIZIO DEL PERIODO DI CHIUSURA
SELECT @STATO = LSRSER_LOTTO_TIPO_PROVV
FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @LTMS
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(
      SELECT MAX(LSRSER_LOTTO_DATA_DECOR)
      FROM LSRSER_LOTTO
      WHERE LSRSER_LOTTO_KEY_ID_RICEV = @LTMS
      AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
      AND LSRSER_LOTTO_DATA_DECOR <= @DATAI
)
 
IF @STATO <> 'A'
BEGIN
      SELECT @RC = 'RICEVITORIA SOSTITUTIVA - ' + @RICEVS + ' - NON ATTIVA NEL PERIODO INDICATO'
      RETURN
END

--PRINT ' ctrl 3 '
 
--VERIFICO SE IL NUOVO PERIODO SI TROVA A CAVALLO DI UN PERIODO GIA' INSERITO
 
SELECT @RICEVS = NULL
SELECT @RICEVDS = NULL
SELECT @CHK_DATAI = NULL
SELECT @CHK_DATAF = NULL
SELECT @CHK_ANNUL = NULL
SELECT @MILLENNIO = NULL
 
SELECT @RICEVS = LSRCHI_KEY_ID_RICEV, 
      @RICEVDS = LSRCHI_KEY_ID_RICEV_FERIE, 
      @CHK_DATAI = LSRCHI_KEY_DATA_INIZIO, 
      @CHK_DATAF = LSRCHI_DATA_FINE,
      @MILLENNIO = LSRCHI_MILLENNIO,
      @CHK_ANNUL = SUBSTRING(@CHK_DATAF,1,1)
FROM LSRCHI 
WHERE (LSRCHI_KEY_DATA_INIZIO BETWEEN @DATAI AND @DATAF OR LSRCHI_DATA_FINE  BETWEEN @DATAI AND @DATAF)
AND LSRCHI_KEY_ID_RICEV = @LTMS
AND LSRCHI_KEY_ID_RICEV_FERIE = @LTMDS
 
--PRINT '----------------------------- a cavallo' 
--PRINT '-' + isnull(@RICEVS ,'')
--PRINT '-' + isnull(@RICEVDS ,'')
--PRINT '-' + isnull(@CHK_DATAI ,'')
--PRINT '-' + isnull(@CHK_DATAF ,'')
--PRINT '-' + isnull(@CHK_ANNUL ,'')

IF @RICEVS IS NOT NULL OR @RICEVS <> ''
BEGIN
      IF @CHK_ANNUL <> '0'
      BEGIN
            SELECT @RC = 'PERIODO DI CHIUSURA INCOMPATIBILE CON UNO GIA PRESENTE'
            RETURN
      END
END
 
--PRINT ' ctrl 4 '

--VERIFICO SE ESISTE UN RECORD CON LA STESSA DATA INIZIO PERIODO PER LE RICEVITORIE INTERESSATE
 
SELECT @RICEVS = NULL
SELECT @RICEVDS = NULL
SELECT @CHK_DATAI = NULL
SELECT @CHK_DATAF = NULL
 
SELECT @RICEVS = LSRCHI_KEY_ID_RICEV, 
      @RICEVDS = LSRCHI_KEY_ID_RICEV_FERIE, 
      @CHK_DATAI = LSRCHI_KEY_DATA_INIZIO, 
      @CHK_DATAF = LSRCHI_DATA_FINE
FROM  LSRCHI
WHERE LSRCHI_KEY_ID_RICEV = @LTMS
AND   LSRCHI_KEY_ID_RICEV_FERIE = @LTMDS
AND   LSRCHI_KEY_DATA_INIZIO = @DATAI

--PRINT '----------------------------- stessa data inizio' 
--PRINT '-' + isnull(@RICEVS ,'')
--PRINT '-' + isnull(@RICEVDS ,'')
--PRINT '-' + isnull(@CHK_DATAI ,'')
--PRINT '-' + isnull(@CHK_DATAF ,'')
--PRINT '-' + isnull(@CHK_ANNUL ,'')

IF @RICEVS IS NOT NULL OR @RICEVS <> ''
BEGIN
      SELECT @CHK_ANNUL = SUBSTRING(@CHK_DATAF,1,1)
 
      IF @CHK_ANNUL <> '0'
      BEGIN
            SELECT @RC = 'PERIODO DI CHIUSURA GIA PRESENTE'
            RETURN
      END
      ELSE
      BEGIN
            IF @FLGINS <> 'Y'
            BEGIN
                  SELECT @RC = ''
                  RETURN
            END
      END
END
----------------------------------------
-- MOD 30/07/2007
----------------------------------------
-- NEL CASO NON VIENE TROVATO UN RECORD 
-- DEVO RIPULIRE IL CHK_ANNUL SE '0' 
-- (ALTRIMENTI TENTEREBBE L'AGGIORNAMENTO)
ELSE
BEGIN
      SELECT @CHK_ANNUL = NULL
END
-----------------------------------------
 
--PRINT ' ctrl 5 '

--PRINT '-' + isnull(@RICEVS ,'')
--PRINT '-' + isnull(@RICEVDS ,'')
--PRINT '-' + isnull(@CHK_DATAI ,'')
--PRINT '-' + isnull(@CHK_DATAF ,'')
--PRINT @FLGINS


IF @FLGINS = 'Y'
BEGIN
 
--SE IL RECORD GIA' INSERITO E' UNA REVOCA AGGIORNO IL RECORD
      IF @CHK_ANNUL = '0'  
      BEGIN
            SELECT @TIPOAGG = 'U'
      END
      ELSE
      BEGIN
            SELECT @TIPOAGG = 'I'
      END
 
      BEGIN TRANSACTION
 
      SELECT @MILLENNIO = SUBSTRING(@DATAF,1,1)
 
      INSERT INTO LSRCHI_FT_VOS VALUES
      (@LTMS, @LTMDS, @DATAI, @DATAF, 
      @DATAINS, @FIRMA, @CAUSALE,
      @ENTE, @PROV, @PROG, 
      @ORAINS, @TIPOAGG,  @MILLENNIO, 
      @OLDLTMS, @OLDLTMDS, @OLDDATAI, '00000000')
 
      IF @@ERROR <> 0
      BEGIN
            ROLLBACK TRANSACTION
            SELECT @RC = 'ERRORE IN INSERIMENTO DATI - AUTORIZZAZIONE NON ACQUISITA'
            RAISERROR (@RC, 16, 1)
            RETURN
      END
      ELSE
      BEGIN
            IF @TIPOAGG = 'I'
            BEGIN
 		--PRINT 'INSERISCO'
			
                  INSERT INTO LSRCHI VALUES
                  (@LTMS, @LTMDS, @DATAI, @DATAF, 
                  @DATAINS, @FIRMA, @CAUSALE,
                  @ENTE, @PROV, @PROG, 
                  @ORAINS, @MILLENNIO)
 
                  IF @@ERROR <> 0
                  BEGIN
                        ROLLBACK TRANSACTION
                        SELECT @RC = 'ERRORE IN INSERIMENTO DATI - AUTORIZZAZIONE NON ACQUISITA'
                        RAISERROR (@RC, 16, 1)
                        RETURN
                  END
                  ELSE
                  BEGIN
                        COMMIT TRANSACTION
                        SELECT @RC = 'AUTORIZZAZIONE ACQUISITA'
                        RETURN
                  END
            END
            ELSE
            BEGIN
 		--PRINT 'AGGIORNO'

                  UPDATE LSRCHI SET
                  LSRCHI_DATA_FINE = @DATAF,
                  LSRCHI_FIRMA = @FIRMA,
                  LSRCHI_DATA_INS = @DATAINS,
                  LSRCHI_ORA_INS = @ORAINS,
                  LSRCHI_MILLENNIO = @MILLENNIO
                  WHERE
                  LSRCHI_KEY_ID_RICEV = @LTMS AND
                  LSRCHI_KEY_ID_RICEV_FERIE = @LTMDS AND
                  LSRCHI_KEY_DATA_INIZIO = @DATAI
 
                  IF @@ERROR <> 0
                  BEGIN
                        ROLLBACK TRANSACTION
                        SELECT @RC = 'ERRORE IN INSERIMENTO DATI - AUTORIZZAZIONE NON ACQUISITA'
                        RAISERROR (@RC, 16, 1)
                        RETURN
                  END
                  ELSE
                  BEGIN
                        COMMIT TRANSACTION
                        SELECT @RC = 'AUTORIZZAZIONE ACQUISITA'
                        RETURN
                  END
            END
      END
END
 
RETURN
GO
