/****** Object:  StoredProcedure [dbo].[IC_AGGIORNA_SOSTITUZIONE]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[IC_AGGIORNA_SOSTITUZIONE]  
 
 @LTMS   CHAR(6),
 @LTMDS   CHAR(6),
 @DATAI   CHAR(8),
 @DATAF   CHAR(8),
 @FIRMA   CHAR(17),
 @UFFICIO   CHAR(5),
 @OLDLTMS   CHAR(6),
 @OLDLTMDS   CHAR(6),
 @OLDDATAI   CHAR(8),
 @OLDDATAF   CHAR(8),
 @CAUSALE   CHAR(2),
 @TIPOOPE   CHAR(1),
 @RC     VARCHAR(100)  OUTPUT
 
AS
 
DECLARE
 
@RUOTADS  CHAR(2),
@RUOTAS  CHAR(2),
@DATAINS  CHAR(8),
@ORAINS  CHAR(8),
@ENTE  CHAR(2),
@PROV  CHAR(2),
@PROG  CHAR(1),
@NEWDATAF  CHAR(8),
@MILLENNIO  CHAR(1),
@TIPOAGG  CHAR(1),
@RICEVS  CHAR(6),
@RICEVDS  CHAR(6),
@CHK_DATAI  CHAR(8),
@CHK_DATAF  CHAR(8),
@STATO  CHAR(1),
@PREVREV  INT,
@IC   VARCHAR(3)
 

IF    ISNUMERIC(@DATAI) = 0 OR ISDATE(@DATAI) = 0
BEGIN
      SELECT @RC = 'FORMATO DATA INIZIO FERIE IN INPUT ERRATO'
      RETURN
END
 
IF    ISNUMERIC(@DATAF) = 0 OR ISDATE(@DATAF) = 0
BEGIN
      SELECT @RC = 'FORMATO DATA FINE FERIE IN INPUT ERRATO'
      RETURN
END
 
IF @DATAF < @DATAI 
BEGIN
      SELECT @RC = 'DATA FINE < DATA INIZIO, CONTROLLARE DATE IN INPUT'
      RETURN
END

SELECT @DATAINS = CONVERT(CHAR(8),GETDATE(),112)
 
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2)+
   SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2)+
   SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2)+
   SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)
 
SELECT @ENTE = SUBSTRING(@UFFICIO,1,2)
SELECT @PROV = SUBSTRING(@UFFICIO,3,2)
SELECT @PROG = SUBSTRING(@UFFICIO,5,1)
 
SELECT @RUOTADS = NULL
SELECT @RUOTAS = NULL
 
--VERIFICO L'ESISTENZA DELLA RICEVITORIA DA SOSTITUIRE E A QUALE ISPETTORATO APPARTIENE
SELECT DISTINCT @RICEVDS = LSRRIC_KEY_ID_RICEV --, @IC = LSRRIC_SIGLA_IC
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @LTMDS
 
IF @RICEVDS IS NULL OR @RICEVDS = ''
BEGIN
 SELECT @RC = 'RICEVITORIA DA SOSTITUIRE - ' + @RICEVDS + ' - INESISTENTE'
 RAISERROR (@RC, 16, 1)
 RETURN
END
 
--VERIFICO L'ESISTENZA DELLA RICEVITORIA DA SOSTITUTIVA E A QUALE ISPETTORATO APPARTIENE
SELECT DISTINCT @IC = LSRRIC_SIGLA_IC
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @LTMDS
AND LSRRIC_SIGLA_IC = @PROV
 
IF @ENTE = 'IC'
BEGIN
 IF @IC <> @PROV
 BEGIN
  SELECT @RC = 'ISPETTORATO DI ' + @PROV + ' NON COMPETENTE PER LA RICEVITORIA - ' + @RICEVDS 
  RAISERROR (@RC, 16, 1)
  RETURN
 END
END
 
SELECT @IC = NULL
 
--VERIFICO L'ESISTENZA DELLA RICEVITORIA DA SOSTITUTIVA E A QUALE ISPETTORATO APPARTIENE
SELECT DISTINCT @RICEVS = LSRRIC_KEY_ID_RICEV --, @IC = LSRRIC_SIGLA_IC
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @LTMS
 
IF @RICEVS IS NULL OR @RICEVS = ''
BEGIN
 SELECT @RC = 'RICEVITORIA SOSTITUTIVA - ' + @RICEVS + ' - INESISTENTE'
 RAISERROR (@RC, 16, 1)
 RETURN
END
 
--VERIFICO L'ESISTENZA DELLA RICEVITORIA DA SOSTITUTIVA E A QUALE ISPETTORATO APPARTIENE
SELECT DISTINCT @IC = LSRRIC_SIGLA_IC
FROM LSRRIC
WHERE LSRRIC_KEY_ID_RICEV = @LTMS
AND LSRRIC_SIGLA_IC = @PROV
 
IF @ENTE = 'IC'
BEGIN
 IF @IC <> @PROV
 BEGIN
  SELECT @RC = 'ISPETTORATO DI ' + @PROV + ' NON COMPETENTE PER LA RICEVITORIA - ' + @RICEVS 
  RAISERROR (@RC, 16, 1)
  RETURN
 END
END
 
SELECT @RUOTADS = SUBSTRING(@RICEVDS,1,2)
SELECT @RUOTAS = SUBSTRING(@RICEVS,1,2)
 
IF @RUOTADS <> @RUOTAS
BEGIN
 SELECT @RC = 'LE DUE RICEVITORIE NON APPARTENGONO ALLA STESSA RUOTA'
 RAISERROR (@RC, 16, 1)
 RETURN
END
 

SELECT @MILLENNIO = SUBSTRING(@DATAF,1,1)
SELECT @PREVREV = 0
 
--VERIFICO LO STATO DELLA RICEVITORIA SOSTITUTIVA ALLA DATA DI INIZIO DEL PERIODO DI CHIUSURA
SELECT @STATO = LSRSER_LOTTO_TIPO_PROVV
FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @LTMS
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(
 SELECT MAX(LSRSER_LOTTO_DATA_DECOR)
 FROM LSRSER_LOTTO
 WHERE LSRSER_LOTTO_KEY_ID_RICEV = @LTMS
 AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
 AND LSRSER_LOTTO_DATA_DECOR <= @DATAI
)
 
IF @STATO <> 'A'
BEGIN
 SELECT @RC = 'RICEVITORIA SOSTITUTIVA - ' + @RICEVS + ' - NON ATTIVA NEL PERIODO INDICATO'
 RAISERROR (@RC, 16, 1)
 RETURN
END
 
--VERIFICO SE ESISTE UN RECORD CON LA STESSA DATA INIZIO PERIODO PER LE RICEVITORIE INTERESSATE
SELECT @CHK_DATAF = NULL
SELECT @RICEVS = NULL
 
SELECT @RICEVS = LSRCHI_KEY_ID_RICEV, 
 @RICEVDS = LSRCHI_KEY_ID_RICEV_FERIE, 
 @CHK_DATAI = LSRCHI_KEY_DATA_INIZIO, 
 @CHK_DATAF = LSRCHI_DATA_FINE
FROM LSRCHI
WHERE LSRCHI_KEY_ID_RICEV = @LTMS
AND LSRCHI_KEY_ID_RICEV_FERIE = @LTMDS
AND LSRCHI_KEY_DATA_INIZIO = @DATAI
 
/*
--INIZIO MODIFICA BY F.GIACOVAZZI 2004/07/23 PER IMPEDIRE AGGIORNAMENTI IN CASO DI REFRESH DELLA PAGINA
IF @CHK_DATAF = @DATAF
BEGIN
 SELECT @RC = 'ATTENZIONE - DATI GIA PRESENTI - AGGIORNAMENTO NON EFFETTUATO'
-- RAISERROR (@RC, 16, 1)
 RETURN
END
--FINE MODIFICA BY F.GIACOVAZZI 2004/07/23
*/
IF @RICEVS IS NOT NULL OR @RICEVS <> '' --ESISTE UN RECORD
BEGIN
 IF @TIPOOPE = 'R' --STO EFFETTUANDO UNA REVOCA
 BEGIN
  SELECT @TIPOAGG = 'U'
  SELECT @NEWDATAF = '0' + SUBSTRING(@DATAF,2,7)
 END
 ELSE --STO MODIFICANDO IL PERIODO DI CHIUSURA
 BEGIN
  SELECT @TIPOAGG = 'U'
  SELECT @NEWDATAF = @DATAF
 
  IF @CHK_DATAI <> @DATAI --LA VECCHIA DATA INIZIO E' DIVERSA DALLA NUOVA DATA INIZIO
  BEGIN
   SELECT @PREVREV = 1
  END
 END
END
ELSE --NON ESISTE UN RECORD
BEGIN
 SELECT @TIPOAGG = 'I'
 SELECT @NEWDATAF = @DATAF
END
 
BEGIN TRANSACTION
 
IF @PREVREV = 1
BEGIN
 SELECT @TIPOAGG = 'D'
END
 

INSERT INTO LSRCHI_FT_VOS VALUES
(@LTMS, @LTMDS, @DATAI, @NEWDATAF, 
@DATAINS, @FIRMA, @CAUSALE,
@ENTE, @PROV, @PROG, 
@ORAINS, @TIPOAGG, @MILLENNIO, @OLDLTMS, 
@OLDLTMDS, @OLDDATAI, '00000000')
 

IF @@ERROR <> 0
BEGIN
 ROLLBACK TRANSACTION
 SELECT @RC = 'ERRORE IN INSERIMENTO DATI - AGGIORNAMENTO NON EFFETTUATO'
 RAISERROR (@RC, 16, 1)
 RETURN
END
ELSE
BEGIN
 IF @TIPOOPE = 'R'  --CASO REVOCA AUTORIZZAZIONE
 BEGIN
  UPDATE LSRCHI SET
  LSRCHI_DATA_FINE = @NEWDATAF,
  LSRCHI_DATA_INS = @DATAINS,
  LSRCHI_ORA_INS = @ORAINS,
  LSRCHI_FIRMA = @FIRMA,
  LSRCHI_UFF_ENTE = @ENTE,
  LSRCHI_UFF_SIGLA_PROV = @PROV,
  LSRCHI_MILLENNIO = @MILLENNIO
  WHERE LSRCHI_KEY_ID_RICEV = @LTMS 
  AND LSRCHI_KEY_ID_RICEV_FERIE = @LTMDS
  AND LSRCHI_KEY_DATA_INIZIO = @DATAI
  AND LSRCHI_DATA_FINE = @OLDDATAF
 
  IF @@ERROR <> 0
  BEGIN
   ROLLBACK TRANSACTION
   SELECT @RC = 'ERRORE IN INSERIMENTO DATI - AGGIORNAMENTO NON EFFETTUATO'
   RAISERROR (@RC, 16, 1)
   RETURN
  END
  ELSE
  BEGIN
   COMMIT TRANSACTION
   SELECT @RC ='AGGIORNAMENTO EFFETTUATO CORRETTAMENTE'
   RETURN
  END
 END
 ELSE  --CASO MODIFICA AUTORIZZAZIONE
 BEGIN
  UPDATE LSRCHI SET
  LSRCHI_KEY_DATA_INIZIO = @DATAI,
  LSRCHI_DATA_FINE = @NEWDATAF,
  LSRCHI_DATA_INS = @DATAINS,
  LSRCHI_ORA_INS = @ORAINS,
  LSRCHI_FIRMA = @FIRMA,
  LSRCHI_UFF_ENTE = @ENTE,
  LSRCHI_UFF_SIGLA_PROV = @PROV,
  LSRCHI_MILLENNIO = @MILLENNIO 
  WHERE LSRCHI_KEY_ID_RICEV = @LTMS 
  AND LSRCHI_KEY_ID_RICEV_FERIE = @LTMDS
  AND LSRCHI_KEY_DATA_INIZIO = @OLDDATAI
 
  IF @@ERROR <> 0
  BEGIN
   ROLLBACK TRANSACTION
   SELECT @RC = 'ERRORE IN INSERIMENTO DATI - AGGIORNAMENTO NON EFFETTUATO'
   RAISERROR (@RC, 16, 1)
   RETURN
  END
  ELSE
  BEGIN
   COMMIT TRANSACTION
   SELECT @RC ='AGGIORNAMENTO EFFETTUATO CORRETTAMENTE'
   RETURN
 
  END
 END
END
 
RETURN
GO
