/****** Object:  StoredProcedure [dbo].[GEV_VARIAZIONE_QUESTIONARI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_VARIAZIONE_QUESTIONARI] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATADOC	CHAR(8),
@DATAINVIODOC	CHAR(8),
@NUMDOC		VARCHAR(25),
@COGNOME	VARCHAR(24),
@NOME		VARCHAR(20),
@ASSOCIAZIONE	CHAR(1),

@TIPOLOGIA	CHAR(2),
@ANNOINIZIO	CHAR(4),
@ORARIO		CHAR(30),
@GIORNORIPOSO	CHAR(1),
@NUMVETRINE	CHAR(1),
@SUPERFICIE	CHAR(1),
@INSEGNAESTERNA	CHAR(1),
@SPAZIOCLIENTE	CHAR(1),
@SPAZIOESPOS	CHAR(1),
@ESPOSITORI	CHAR(1),
@SUPERENALOTTO	CHAR(1),
@TOTOCALCIO	CHAR(1),
@TOTIP		CHAR(1),
@TRIS		CHAR(1),
@F101		CHAR(1),
@GEV		CHAR(1),
@INCASSOGEV	CHAR(10),
@PC		CHAR(1),
@STAMPANTE	CHAR(1),
@INTERNET	CHAR(1),
@UBICAZIONE	CHAR(1),
@VICINOA	CHAR(1),
@TELPRINC	CHAR(12),
@TELALTER	CHAR(12),
@FAX		CHAR(12),
@EMAIL		CHAR(50),

@FLGANAG	CHAR(1),
@FKINSTIT	VARCHAR(16),
@FKINSDOC	VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)


AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSDOC	CHAR(8),
@FKORAINSDOC	CHAR(8),
@FKDATAINSGEV	CHAR(8),
@FKORAINSGEV	CHAR(8),
@FLGANAGOLD	CHAR(1),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20)


SELECT @RICEAPPO = NULL
SELECT @FKDATAINSTIT = NULL
SELECT @FKORAINSTIT = NULL
SELECT @FKDATAINSGEV = NULL
SELECT @FKORAINSGEV = NULL

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
BEGIN
	SELECT @FKDATAINSGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSGEV = SUBSTRING(@FKINSTIT, 9, 8)
END
ELSE
BEGIN
	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)
END

SELECT @FKDATAINSDOC = SUBSTRING(@FKINSDOC, 1, 8)
SELECT @FKORAINSDOC = SUBSTRING(@FKINSDOC, 9, 8)

--------------------------------------------------------------------------------------------------------------------------------
-- CONTROLLO SE I DATI IN INPUT NON SIANO GIA' PRESENTI IN TABELLA
--------------------------------------------------------------------------------------------------------------------------------

SELECT @RICEAPPO = NULL

SELECT @RICEAPPO = LSRQST_GEV_KEY_ID_RICEV
FROM LSRQST_GEV
WHERE LSRQST_GEV_KEY_ID_RICEV = @CODSGI
AND LSRQST_GEV_DATA_DOCUMENTO = @DATADOC
AND LSRQST_GEV_DATA_INVIO_DOC = @DATAINVIODOC
AND LSRQST_GEV_NUM_PROT_DOC = @NUMDOC
AND LSRQST_GEV_ASSOCIAZIONE = @ASSOCIAZIONE
AND LSRQST_GEV_NOME = @NOME
AND LSRQST_GEV_COGNOME = @COGNOME

AND lsrqst_GeV_tipo_esercizio = @TIPOLOGIA
AND lsrqst_GeV_anno_inizio = @ANNOINIZIO
AND lsrqst_GeV_orario = @ORARIO
AND lsrqst_GeV_giorno_riposo = @GIORNORIPOSO
AND lsrqst_GeV_num_vetrine = @NUMVETRINE
AND lsrqst_GeV_superficie = @SUPERFICIE
AND lsrqst_GeV_insegna_esterna = @INSEGNAESTERNA
AND lsrqst_GeV_spazio_cliente = @SPAZIOCLIENTE
AND lsrqst_GeV_spazio_espositivo = @SPAZIOESPOS
AND lsrqst_GeV_spazio_espositori = @ESPOSITORI
AND lsrqst_GeV_presenza_superenalotto = @SUPERENALOTTO
AND lsrqst_GeV_presenza_totocalcio = @TOTOCALCIO
AND lsrqst_GeV_presenza_totip = @TOTIP
AND lsrqst_GeV_presenza_tris = @TRIS
AND lsrqst_GeV_presenza_f101 = @F101
AND lsrqst_GeV_presenza_gev = @GEV
AND lsrqst_GeV_incasso_gev = @INCASSOGEV
AND lsrqst_GeV_pc = @PC
AND lsrqst_GeV_stampante = @STAMPANTE
AND lsrqst_GeV_internet = @INTERNET
AND lsrqst_GeV_ubicazione = @UBICAZIONE
AND lsrqst_GeV_vicino_a = @VICINOA
AND lsrqst_GeV_tel_prinicipale = @TELPRINC
AND lsrqst_GeV_tel_alternativo = @TELALTER
AND lsrqst_GeV_fax = @FAX
AND lsrqst_GeV_e_mail = @EMAIL

AND LSRQST_GEV_NOTE = @NOTE
AND LSRQST_GEV_FLAG_ANAG = @FLGANAG
AND LSRQST_GEV_KEY_DATA_INS = @FKDATAINSDOC
AND LSRQST_GEV_KEY_ORA_INS = @FKORAINSDOC

IF @RICEAPPO IS NOT NULL
BEGIN
	SELECT @MSGERR = '9 - I DATI INSERITI SONO GIA PRESENTI IN TABELLA'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

--------------------------------------------------------------------------------------------------------------------------------
-- EFFETTUO I CONTROLLI SU FLAGANAG
--------------------------------------------------------------------------------------------------------------------------------

SELECT @FLGANAGOLD = NULL

SELECT @FLGANAGOLD = LSRQST_GEV_FLAG_ANAG
FROM LSRQST_GEV
WHERE LSRQST_GEV_KEY_ID_RICEV = @CODSGI
AND LSRQST_GEV_KEY_DATA_INS = @FKDATAINSDOC
AND LSRQST_GEV_KEY_ORA_INS = @FKORAINSDOC

IF @FLGANAGOLD = '0' AND @FLGANAG <> '0'
BEGIN

	SELECT @RICEAPPO = NULL

	SELECT @COGNOMEOLD = NULL
	SELECT @NOMEOLD = NULL
	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		SELECT @RICEAPPO = LSRQST_GEV_KEY_ID_RICEV 
		FROM LSRQST_GEV
		WHERE LSRQST_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRQST_GEV_FK_DATA_INS_TIT_GEV = @FKDATAINSGEV
		AND LSRQST_GEV_FK_ORA_INS_TIT_GEV = @FKORAINSGEV
	ELSE
		SELECT @RICEAPPO = LSRQST_GEV_KEY_ID_RICEV 
		FROM LSRQST_GEV
		WHERE LSRQST_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRQST_GEV_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRQST_GEV_FK_ORA_INS_TIT = @FKORAINSTIT

	IF @RICEAPPO IS NOT NULL
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN QUESTIONARIO ASSOCIATO AL TITOLARE INDICATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END


BEGIN TRANSACTION
 
SELECT @MSGERR = '0 - VARIAZIONE EFFETTUATA CORRETTAMENTE'
RAISERROR (@MSGERR, 16, 1)

UPDATE LSRQST_GEV SET
LSRQST_GEV_DATA_DOCUMENTO = @DATADOC,
LSRQST_GEV_DATA_INVIO_DOC = @DATAINVIODOC,
LSRQST_GEV_NUM_PROT_DOC = @NUMDOC,
LSRQST_GEV_ASSOCIAZIONE = @ASSOCIAZIONE,
LSRQST_GEV_NOME = @NOME,
LSRQST_GEV_COGNOME = @COGNOME,

lsrqst_GeV_tipo_esercizio = @TIPOLOGIA,
lsrqst_GeV_anno_inizio = @ANNOINIZIO,
lsrqst_GeV_orario = @ORARIO,
lsrqst_GeV_giorno_riposo = @GIORNORIPOSO,
lsrqst_GeV_num_vetrine = @NUMVETRINE,
lsrqst_GeV_superficie = @SUPERFICIE,
lsrqst_GeV_insegna_esterna = @INSEGNAESTERNA,
lsrqst_GeV_spazio_cliente = @SPAZIOCLIENTE,
lsrqst_GeV_spazio_espositivo = @SPAZIOESPOS,
lsrqst_GeV_spazio_espositori = @ESPOSITORI,
lsrqst_GeV_presenza_superenalotto = @SUPERENALOTTO,
lsrqst_GeV_presenza_totocalcio = @TOTOCALCIO,
lsrqst_GeV_presenza_totip = @TOTIP,
lsrqst_GeV_presenza_tris = @TRIS,
lsrqst_GeV_presenza_f101 = @F101,
lsrqst_GeV_presenza_gev = @GEV,
lsrqst_GeV_incasso_gev = @INCASSOGEV,
lsrqst_GeV_pc = @PC,
lsrqst_GeV_stampante = @STAMPANTE,
lsrqst_GeV_internet = @INTERNET,
lsrqst_GeV_ubicazione = @UBICAZIONE,
lsrqst_GeV_vicino_a = @VICINOA,
lsrqst_GeV_tel_prinicipale = @TELPRINC,
lsrqst_GeV_tel_alternativo = @TELALTER,
lsrqst_GeV_fax = @FAX,
lsrqst_GeV_e_mail = @EMAIL,

LSRQST_GEV_NOTE = @NOTE,
LSRQST_GEV_FLAG_ANAG = @FLGANAG,
LSRQST_GeV_fk_data_ins_tit = @FKDATAINSTIT,
LSRQST_GeV_fk_ora_ins_tit = @FKORAINSTIT,
LSRQST_GeV_fk_data_ins_tit_gev = @FKDATAINSGEV,
LSRQST_GeV_fk_ora_ins_tit_gev = @FKORAINSGEV
WHERE LSRQST_GEV_KEY_ID_RICEV = @CODSGI
AND LSRQST_GEV_KEY_DATA_INS = @FKDATAINSDOC 
AND LSRQST_GEV_KEY_ORA_INS = @FKORAINSDOC

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN VARIAZIONE DOCUMENTO - RICEVITORIA: ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
GO
