/****** Object:  StoredProcedure [dbo].[GEV_VARIAZIONE_ORDINE]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[GEV_VARIAZIONE_ORDINE] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@COGNOME	VARCHAR(24),
@NOME		VARCHAR(20),
@IDGIOCO	CHAR(4),
@NUMPACCHI	CHAR(3),

@FLGANAG	CHAR(1),
@FKINSTIT	VARCHAR(16),
@DATAINSDOC	VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)


AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@PKDATAINSDOC	CHAR(8),
@PKORAINSDOC	CHAR(8),
@FKDATAINSGEV	CHAR(8),
@FKORAINSGEV	CHAR(8),

@DATAINSORD	CHAR(8),
@ORAINSORD		CHAR(8),

@FLGANAGOLD	CHAR(1),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20)


SELECT @RICEAPPO = NULL
SELECT @FKDATAINSTIT = NULL
SELECT @FKORAINSTIT = NULL
SELECT @FKDATAINSGEV = NULL
SELECT @FKORAINSGEV = NULL

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
BEGIN
	SELECT @FKDATAINSGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSGEV = SUBSTRING(@FKINSTIT, 9, 8)
END
ELSE
BEGIN

	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)
END




--------------------------------------------------------------------------------------------------------------------------------
-- EFFETTUO I CONTROLLI SU FLAGANAG
--------------------------------------------------------------------------------------------------------------------------------

SELECT @FLGANAGOLD = NULL
SELECT @PKDATAINSDOC = SUBSTRING(@DATAINSDOC, 1, 8)
SELECT @PKORAINSDOC = SUBSTRING(@DATAINSDOC, 9, 8)

SELECT @FLGANAGOLD = LSRORD_GEV_FLAG_ANAG
FROM LSRORD_GEV
WHERE LSRORD_GEV_KEY_ID_RICEV = @CODSGI
AND LSRORD_GEV_KEY_DATA_INS = @PKDATAINSDOC
AND LSRORD_GEV_KEY_ORA_INS = @PKORAINSDOC

IF @FLGANAGOLD = '0' AND @FLGANAG <> '0'
BEGIN

	SELECT @RICEAPPO = NULL

	SELECT @COGNOMEOLD = NULL
	SELECT @NOMEOLD = NULL
	
	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		SELECT @RICEAPPO = LSRORD_GEV_KEY_ID_RICEV 
		FROM LSRORD_GEV
		WHERE LSRORD_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRORD_GEV_FK_DATA_INS_TIT_GEV = @FKDATAINSGEV
		AND LSRORD_GEV_FK_ORA_INS_TIT_GEV = @FKORAINSGEV
	ELSE
		SELECT @RICEAPPO = LSRORD_GEV_KEY_ID_RICEV 
		FROM LSRORD_GEV
		WHERE LSRORD_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRORD_GEV_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRORD_GEV_FK_ORA_INS_TIT = @FKORAINSTIT


	IF @RICEAPPO IS NOT NULL
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO ASSOCIATO AL TITOLARE INDICATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END


BEGIN TRANSACTION
UPDATE LSRORD_GEV
SET LSRORD_GEV_NUMERO_PACCHI = @NUMPACCHI,
	LSRORD_GEV_FLAG_ANAG = @FLGANAG,
	lsrORD_GeV_fk_data_ins_tit = @FKDATAINSTIT,
	lsrORD_GeV_fk_ora_ins_tit = @FKORAINSTIT,
	lsrORD_GeV_fk_data_ins_tit_gev = @FKDATAINSGEV,
	lsrORD_GeV_fk_ora_ins_tit_gev = @FKORAINSGEV
WHERE LSRORD_GEV_KEY_ID_RICEV = @CODSGI
	AND LSRORD_GEV_KEY_ID_GIO = @IDGIOCO
	AND LSRORD_GEV_KEY_DATA_INS = @PKDATAINSDOC
	AND LSRORD_GEV_KEY_ORA_INS = @PKORAINSDOC





COMMIT TRANSACTION
GO
