/****** Object:  StoredProcedure [dbo].[GEV_VARIAZIONE_NUOVI_CONTRATTI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[GEV_VARIAZIONE_NUOVI_CONTRATTI] 

@CODSGI		VARCHAR(7),
@CODLTM		VARCHAR(7),
@FLAGNUOVOCON	CHAR(1),
@DATANUOVOCON	CHAR(8),
@FIRMA		VARCHAR(17),
@MSGERR VARCHAR(200) OUTPUT
AS 

declare 
@DATAOGGI 	char(8),
@ORAOGGI 	char(8),
@DATAAPPO	CHAR(8),
@FLAGAPPO	CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)

SELECT @DATAAPPO = ''
SELECT @FLAGAPPO = ''
SELECT @DATAAPPO = LSRCON_GEV_DATA_NUOVO_CON ,
 	@FLAGAPPO = LSRCON_GEV_FLAG_NUOVO_CON
FROM LSRCON_GEV 
WHERE LSRCON_GEV_COD_LOTTO = @CODLTM
if @DATAAPPO is NULL 
begin
	select @DATAAPPO = ''
end
if @FLAGAPPO is NULL 
begin
	select @FLAGAPPO = ''
end

if ltrim(rtrim(@DATAAPPO)) <> '' 
begin 
	SELECT @MSGERR = 'DATA NUOVO CONTRATTO VALORIZZATA PER LA RICEVITORIA: ' + @CODLTM
end 
ELSE
BEGIN	
	IF (@FLAGAPPO <> '' AND @FLAGAPPO <> '0')
	BEGIN
		SELECT @MSGERR = 'DATA NUOVO CONTRATTO VALORIZZATA PER LA RICEVITORIA: ' + @CODLTM
	end 
	else
	begin
		UPDATE LSRCON_GEV SET
		LSRCON_GEV_KEY_DATA_INS = @DATAOGGI,
		LSRCON_GEV_KEY_ORA_INS = @ORAOGGI,
		LSRCON_GEV_FLAG_NUOVO_CON = @FLAGNUOVOCON,
		LSRCON_GEV_DATA_NUOVO_CON = @DATANUOVOCON
		WHERE LSRCON_GEV_COD_LOTTO = @CODLTM
		AND LSRCON_GEV_FLAG_ANAG = '1'
		if @@rowcount = 0
		begin 
			SELECT @MSGERR = 'CONTRATTO NON PRESENTE PER LA RICEVITORIA: ' + @CODLTM
		end 
	end
END
GO
