/****** Object:  StoredProcedure [dbo].[GEV_VARIAZIONE_FIDEJUSSIONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_VARIAZIONE_FIDEJUSSIONI] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATADOC		CHAR(8),
@DATAINVIODOC	CHAR(8),
@NUMDOC		VARCHAR(25),
@COGNOME		VARCHAR(24),
@NOME		VARCHAR(20),
@TOTDOV		VARCHAR(9),
@TOTPAG		VARCHAR(9),
@ASSICURAZIONE	CHAR(2),
@ANNORIF		CHAR(4),
@DATAINIZIO		CHAR(8),
@DATAFINE		CHAR(8),
@FLGANAG		CHAR(1),
@FKINSTIT		VARCHAR(16),
@FKINSDOC		VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)

AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSDOC	CHAR(8),
@FKORAINSDOC	CHAR(8),
@FKDATAINSGEV	CHAR(8),
@FKORAINSGEV	CHAR(8),
@FLGANAGOLD	CHAR(1),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20)


SELECT @RICEAPPO = NULL
SELECT @FKDATAINSTIT = NULL
SELECT @FKORAINSTIT = NULL
SELECT @FKDATAINSGEV = NULL
SELECT @FKORAINSGEV = NULL

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
BEGIN
	SELECT @FKDATAINSGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSGEV = SUBSTRING(@FKINSTIT, 9, 8)
END
ELSE
BEGIN
	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)
END


SELECT @FKDATAINSDOC = SUBSTRING(@FKINSDOC, 1, 8)
SELECT @FKORAINSDOC = SUBSTRING(@FKINSDOC, 9, 8)

IF LTRIM(RTRIM(@TOTDOV)) = '' OR @TOTDOV IS NULL
BEGIN
	SELECT @TOTDOV = '0'
END

IF LTRIM(RTRIM(@TOTPAG)) = '' OR @TOTPAG IS NULL
BEGIN
	SELECT @TOTPAG = '0'
END

SELECT @TOTDOV = CONVERT(DEC(18,2), @TOTDOV)
SELECT @TOTPAG = CONVERT(DEC(18,2), @TOTPAG)


--------------------------------------------------------------------------------------------------------------------------------
-- CONTROLLO SE I DATI IN INPUT NON SIANO GIA' PRESENTI IN TABELLA
--------------------------------------------------------------------------------------------------------------------------------

SELECT @RICEAPPO = NULL

SELECT @RICEAPPO = LSRFID_GEV_KEY_ID_RICEV
FROM LSRFID_GEV
WHERE LSRFID_GEV_KEY_ID_RICEV = @CODSGI
AND LSRFID_GEV_DATA_DOCUMENTO = @DATADOC
AND LSRFID_GEV_DATA_INVIO_DOC = @DATAINVIODOC
AND LSRFID_GEV_NUM_PROT_DOC = @NUMDOC
AND LSRFID_GEV_ID_SOC = @ASSICURAZIONE
AND LSRFID_GEV_NOME = @NOME
AND LSRFID_GEV_COGNOME = @COGNOME
AND LSRFID_GEV_IMPORTO_DOVUTO = @TOTDOV
AND LSRFID_GEV_IMPORTO_PAGATO = @TOTPAG
AND LSRFID_GEV_ANNO_RIF = @ANNORIF
AND LSRFID_GEV_DATA_INIZIO = @DATAINIZIO
AND LSRFID_GEV_DATA_FINE = @DATAFINE
AND LSRFID_GEV_NOTE = @NOTE
AND LSRFID_GEV_FLAG_ANAG = @FLGANAG
AND LSRFID_GEV_KEY_DATA_INS = @FKDATAINSDOC
AND LSRFID_GEV_KEY_ORA_INS = @FKORAINSDOC

IF @@ROWCOUNT > 0 
BEGIN
	SELECT @MSGERR = '9 - I DATI INSERITI SONO GIA PRESENTI IN TABELLA'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

--------------------------------------------------------------------------------------------------------------------------------
-- EFFETTUO I CONTROLLI SU FLAGANAG
--------------------------------------------------------------------------------------------------------------------------------

SELECT @FLGANAGOLD = NULL

SELECT @FLGANAGOLD = LSRFID_GEV_FLAG_ANAG
FROM LSRFID_GEV
WHERE LSRFID_GEV_KEY_ID_RICEV = @CODSGI
AND LSRFID_GEV_KEY_DATA_INS = @FKDATAINSDOC
AND LSRFID_GEV_KEY_ORA_INS = @FKORAINSDOC
AND LSRFID_GEV_ANNO_RIF = @ANNORIF

IF @FLGANAGOLD = '0' AND @FLGANAG <> '0'
BEGIN

	SELECT @RICEAPPO = NULL

	SELECT @COGNOMEOLD = NULL
	SELECT @NOMEOLD = NULL
	
	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		SELECT @RICEAPPO = LSRFID_GEV_KEY_ID_RICEV 
		FROM LSRFID_GEV
		WHERE LSRFID_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRFID_GEV_FK_DATA_INS_TIT_GEV = @FKDATAINSGEV
		AND LSRFID_GEV_FK_ORA_INS_TIT_GEV = @FKORAINSGEV
		AND LSRFID_GEV_ANNO_RIF = @ANNORIF
	ELSE
		SELECT @RICEAPPO = LSRFID_GEV_KEY_ID_RICEV 
		FROM LSRFID_GEV
		WHERE LSRFID_GEV_KEY_ID_RICEV = @CODSGI
		AND LSRFID_GEV_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRFID_GEV_FK_ORA_INS_TIT = @FKORAINSTIT
		AND LSRFID_GEV_ANNO_RIF = @ANNORIF


	IF @RICEAPPO IS NOT NULL
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO ASSOCIATO AL TITOLARE INDICATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END


BEGIN TRANSACTION

SELECT @MSGERR = '0 - VARIAZIONE EFFETTUATA CORRETTAMENTE'
RAISERROR (@MSGERR, 16, 1)

UPDATE LSRFID_GEV SET
LSRFID_GEV_DATA_DOCUMENTO = @DATADOC,
--LSRFID_GEV_DATA_INVIO_DOC = @DATAINVIODOC,
--LSRFID_GEV_NUM_PROT_DOC = @NUMDOC,
LSRFID_GEV_ID_SOC = @ASSICURAZIONE,
LSRFID_GEV_COGNOME = @COGNOME,
LSRFID_GEV_NOME = @NOME,
LSRFID_GEV_IMPORTO_DOVUTO = @TOTDOV,
LSRFID_GEV_IMPORTO_PAGATO = @TOTPAG,
LSRFID_GEV_ANNO_RIF = @ANNORIF,
LSRFID_GEV_DATA_INIZIO = @DATAINIZIO,
LSRFID_GEV_DATA_FINE = @DATAFINE,
LSRFID_GEV_NOTE = @NOTE,
LSRFID_GEV_FLAG_ANAG = @FLGANAG,
LSRFID_GeV_fk_data_ins_tit = @FKDATAINSTIT,
LSRFID_GeV_fk_ora_ins_tit = @FKORAINSTIT,
LSRFID_GeV_fk_data_ins_tit_gev = @FKDATAINSGEV,
LSRFID_GeV_fk_ora_ins_tit_gev = @FKORAINSGEV
WHERE LSRFID_GEV_KEY_ID_RICEV = @CODSGI
AND LSRFID_GEV_KEY_DATA_INS = @FKDATAINSDOC 
AND LSRFID_GEV_KEY_ORA_INS = @FKORAINSDOC

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN VARIAZIONE DOCUMENTO - RICEVITORIA: ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
GO
