/****** Object:  StoredProcedure [dbo].[INSERT_LSRPRO_F_CONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE      PROCEDURE [dbo].[INSERT_LSRPRO_F_CONI]
 
	@RICEVITORIA 	CHAR(6),
	@TIPOPROVV		CHAR(1),
	@DATAPROVV		CHAR(8),
	@NUMPROVV		CHAR(14),
	@CAUSALE		CHAR(40),
	@FIRMA		CHAR(17),
	@EMANATO		CHAR(25),
	@DATADECOR		CHAR(8),
	@FLAGDIS		CHAR(1),
	@NUMERR 		VARCHAR(4) OUTPUT,
	@MSGERR 		VARCHAR(200) OUTPUT

AS

DECLARE
@OGGI			CHAR(8),
@DOMANI		CHAR(8),
@DATADIS		CHAR(8),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATAINSLET		CHAR(8),
@ORAINSLET		CHAR(8),
@DATAAPPO		CHAR(8),
@APPORICEV		CHAR(6),
@FK_DATA_INS_TIT	CHAR(8),
@FK_ORA_INS_TIT	CHAR(8),
@FKPRO		CHAR(16),
@DATALET		CHAR(8),
@DATA_INS_LET	CHAR(8),
@STATOOGGI_CONI		CHAR(1),
@STATOOGGI_TRIS		CHAR(1),
@STATOOGGI_GEV		CHAR(1),
@STATOOGGI_ST		CHAR(1),
@STATOOGGI_GP		CHAR(1),
@TIPOPV		CHAR(1)

SELECT @OGGI = CONVERT(CHAR(8),GETDATE(),112)
SELECT @DOMANI = CONVERT(CHAR(8),GETDATE() + 1,112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)  + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2) 
SELECT @DATAAPPO = NULL

/*
-- STEP DA ESEGUIRE
1) VERIFICA CHE NON ESISTONO ALTRI PROVVEDIMENTI CON STESSA DATA E NUMERO PROVVEDIMENTO
2) VERIFICA CHE LA DATA DECORRENZA DEVE ESSERE SUPERIORE ALLA DECORRENZA DEL TITOLARE ATTUALE
3) VERIFICA CHE NON ESISTONO ALTRI PROVVEDIMENTI DELLO STESSO TIPO PER IL TITOLARE ATTUALE
4) VERIFICA CHE NON ESISTONO ALTRI PROVVEDIMENTI CON STESSA DATA VALIDITA'
5) VERIFICA CHE SE LA DECORRENZA è NEL FUTURO NON VI SIANO ALTRI PROVVEDIMENTI CON DATA DECORRENZA NEL FUTURO
6) INSERIMENTO RECORD SU LSRPRO
7) AGGIORNAMENTO FLAG ANAGRAFICA CONTRATTI
8) SE @FLAGDIS=S --> DISATTIVAZIONE DEL SERVIZIO A PARTIRE DALLA DATA DECORRENZA DEL PROVVEDIMENTO 
9) DISATTIVAZIONE DEL SERVIZIO G&V A PARTIRE DALLA DATA DECORRENZA DEL PROVVEDIMENTO 
9) DISATTIVAZIONE DEL SERVIZIO ST A PARTIRE DALLA DATA DECORRENZA DEL PROVVEDIMENTO 
*/



--*************************************************************************
--           STEP 1
--*************************************************************************
SELECT @APPORICEV = NULL
SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
FROM LSRPRO_CONI 
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_CONI_FLAG_VALIDITA = 'Y'
AND LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
AND lsrpro_coni_data_provv = @NUMPROVV
AND lsrpro_coni_prog_provv = @DATAPROVV

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO CON STESSA DATA  E NUMERO'
	RETURN 
END


--*************************************************************************
--           STEP 2
--*************************************************************************
SELECT @DATAAPPO = NULL
SELECT @DATAAPPO = lsrtit_coni_data_validita,
	@FK_DATA_INS_TIT = LSRTIT_CONI_KEY_DATA_INS,
	@FK_ORA_INS_TIT = LSRTIT_CONI_KEY_ORA_INS
FROM LSRTIT_CONI
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
AND (lsrtit_coni_data_validita + lsrtit_coni_ora_validita) =
	(select max(lsrtit_coni_data_validita + lsrtit_coni_ora_validita)
	from lsrtit_coni
	where lsrtit_coni_key_id_ricev = @RICEVITORIA
	and  lsrtit_coni_data_validita <= @OGGI
	and  lsrtit_coni_flag_validita = 'Y')
AND LSRTIT_CONI_FLAG_VALIDITA = 'Y'

IF (@DATAAPPO <>'' OR @DATAAPPO IS NOT NULL)
BEGIN
	IF @DATAAPPO >= @DATADECOR
	BEGIN
                           SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - LA DATA DECORRENZA DEVE ESSERE SUPERIORE A ' + @DATAAPPO
                           RETURN 
	END
END


--*************************************************************************
--           STEP 3
--*************************************************************************
SELECT @APPORICEV = NULL
SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
FROM LSRPRO_CONI 
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_CONI_FLAG_VALIDITA = 'Y'
AND LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
AND LSRPRO_CONI_FK_DATA_INS_TIT = @FK_DATA_INS_TIT
AND LSRPRO_CONI_FK_ORA_INS_TIT = @FK_ORA_INS_TIT

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO DELLO STESSO TIPO PER IL TITOLARE ATTUALE'
	RETURN 
END


--*************************************************************************
--           STEP 4
--*************************************************************************
SELECT @APPORICEV = NULL
SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
FROM LSRPRO_CONI
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_CONI_FLAG_VALIDITA = 'Y'
AND LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
AND LSRPRO_CONI_DECOR_DAL = @DATADECOR

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO CON STESSA DATA DECORRENZA'
	RETURN 
END




--*************************************************************************
--           STEP 5
--*************************************************************************

IF (@DATADECOR > @OGGI)
BEGIN
	SELECT @APPORICEV = NULL
	SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
	FROM LSRPRO_CONI
	WHERE lsrpro_CONI_key_id_ricev = @RICEVITORIA
	 	and LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
	 	and lsrpro_CONI_flag_validita='Y' 
		and lsrpro_CONI_decor_dal >@OGGI
	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO CON DATA DECORRENZA NEL FUTURO'
		RETURN 
	END
END




BEGIN TRANSACTION
--*************************************************************************
--           STEP 6
--*************************************************************************
INSERT INTO LSRPRO_CONI VALUES (
	@RICEVITORIA,
	@OGGI,
	@ORAINS,
	@TIPOPROVV,
	@DATAPROVV,
	@NUMPROVV,
	@DATADECOR,
	'',
	@CAUSALE,
	@FIRMA,
	@EMANATO,
	@FK_DATA_INS_TIT,
	@FK_ORA_INS_TIT,
	'Y',
	'00000000'
	)

IF @@ERROR <> 0 
BEGIN
	 
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRPRO'
	ROLLBACK TRANSACTION
	RETURN 0
                  
END

--*************************************************************************
--           STEP 7
--*************************************************************************

UPDATE LSRTIT_CONI
SET LSRTIT_CONI_FLAG_ANAG = LSRTIT_CONI_FLAG_ANAG + 1
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRTIT_CONI_FLAG_ANAG <> '0'

UPDATE LSRCON_CONI
SET LSRCON_CONI_FLAG_ANAG = LSRCON_CONI_FLAG_ANAG + 1
WHERE LSRCON_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRCON_CONI_FLAG_ANAG <> '0'

UPDATE LSRFID_CONI
SET LSRFID_CONI_FLAG_ANAG = LSRFID_CONI_FLAG_ANAG + 1
WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRFID_CONI_FLAG_ANAG <> '0'

UPDATE LSRNUO_CONI
SET LSRNUO_CONI_FLAG_ANAG = LSRNUO_CONI_FLAG_ANAG + 1
WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRNUO_CONI_FLAG_ANAG <> '0'

UPDATE LSRQST_CONI
SET LSRQST_CONI_FLAG_ANAG = LSRQST_CONI_FLAG_ANAG + 1
WHERE LSRQST_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRQST_CONI_FLAG_ANAG <> '0'

UPDATE LSRRAD_CONI
SET LSRRAD_CONI_FLAG_ANAG = LSRRAD_CONI_FLAG_ANAG + 1
WHERE LSRRAD_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRAD_CONI_FLAG_ANAG <> '0'

UPDATE LSRRIN_CONI
SET LSRRIN_CONI_FLAG_ANAG = LSRRIN_CONI_FLAG_ANAG + 1
WHERE LSRRIN_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRIN_CONI_FLAG_ANAG <> '0'

UPDATE LSRTLP_ST
SET LSRTLP_ST_FLAG_ANAG = LSRTLP_ST_FLAG_ANAG + 1
WHERE LSRTLP_ST_KEY_ID_RICEV = @RICEVITORIA
	AND LSRTLP_ST_FLAG_ANAG <> '0'

UPDATE LSRRAD_ST
SET LSRRAD_ST_FLAG_ANAG = LSRRAD_ST_FLAG_ANAG + 1
WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRAD_ST_FLAG_ANAG <> '0'

----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI SPORTIVI -----------------------------------
----------------------------------------------------------------------------------------------------------------------

UPDATE lsrcon_GS
SET lsrcon_GS_FLAG_ANAG = lsrcon_GS_FLAG_ANAG + 1
WHERE lsrcon_GS_KEY_ID_RICEV = @RICEVITORIA
	AND lsrcon_GS_FLAG_ANAG <> '0'

UPDATE lsrnuo_GS
SET lsrnuo_GS_FLAG_ANAG = lsrnuo_GS_FLAG_ANAG + 1
WHERE lsrnuo_GS_KEY_ID_RICEV = @RICEVITORIA
	AND lsrnuo_GS_FLAG_ANAG <> '0'

UPDATE lsrrad_GS
SET lsrrad_GS_FLAG_ANAG = lsrrad_GS_FLAG_ANAG + 1
WHERE lsrrad_GS_KEY_ID_RICEV = @RICEVITORIA
	AND lsrrad_GS_FLAG_ANAG <> '0'

UPDATE lsrtlp_GS
SET lsrtlp_GS_FLAG_ANAG = lsrtlp_GS_FLAG_ANAG + 1
WHERE lsrtlp_GS_KEY_ID_RICEV = @RICEVITORIA
	AND lsrtlp_GS_FLAG_ANAG <> '0'

----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI PUBBLICI -----------------------------------
----------------------------------------------------------------------------------------------------------------------

UPDATE lsrcon_GP
SET lsrcon_GP_FLAG_ANAG = lsrcon_GP_FLAG_ANAG + 1
WHERE lsrcon_GP_KEY_ID_RICEV = @RICEVITORIA
	AND lsrcon_GP_FLAG_ANAG <> '0'


UPDATE LSRFID_GP
SET LSRFID_GP_FLAG_ANAG = LSRFID_GP_FLAG_ANAG + 1
WHERE LSRFID_GP_KEY_ID_RICEV = @RICEVITORIA
	AND LSRFID_GP_FLAG_ANAG <> '0'


IF ISNUMERIC(LTRIM(RTRIM(@RICEVITORIA) )) = 1
BEGIN
	UPDATE LSRCON_GEV 
	SET LSRCON_GEV_FLAG_ANAG = LSRCON_GEV_FLAG_ANAG + 1
	WHERE LSRCON_GEV_COD_LOTTO = @RICEVITORIA
		AND LSRCON_GEV_FLAG_ANAG <> '0'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_GEV'
		RETURN
	END

	-- LSRQST_GEV
	UPDATE LSRQST_GEV 
	SET LSRQST_GEV_FLAG_ANAG = LSRQST_GEV_FLAG_ANAG + 1
	WHERE LSRQST_GEV_COD_LOTTO = @RICEVITORIA
		AND LSRQST_GEV_FLAG_ANAG <> '0'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRQST_GEV'
		RETURN
	END

	-- LSRFID_GEV
	UPDATE LSRFID_GEV  
	SET LSRFID_GEV_FLAG_ANAG = LSRFID_GEV_FLAG_ANAG + 1
	WHERE LSRFID_GEV_COD_LOTTO = @RICEVITORIA
	AND  LSRFID_GEV_FLAG_ANAG <> '0'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_GEV'
		RETURN
	END

	-- LSRRAD_GEV
	UPDATE LSRRAD_GEV 
	SET LSRRAD_FLAG_ANAG = LSRRAD_FLAG_ANAG + 1
	WHERE LSRRAD_COD_LOTTO = @RICEVITORIA
	AND LSRRAD_FLAG_ANAG <> '0'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
		RETURN
	END

	-- LSRORD_GEV
	UPDATE LSRORD_GEV 
	SET LSRORD_GEV_FLAG_ANAG = LSRORD_GEV_FLAG_ANAG + 1
	WHERE LSRORD_GEV_COD_LOTTO = @RICEVITORIA
	AND LSRORD_GEV_FLAG_ANAG <> '0'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
		RETURN
	END

	-- LSRCON_ITVM
	UPDATE LSRCON_ITVM 
	SET LSRCON_ITVM_FLAG_ANAG = LSRCON_ITVM_FLAG_ANAG + 1
	WHERE LSRCON_ITVM_COD_LOTTO = @RICEVITORIA
	AND LSRCON_ITVM_FLAG_ANAG <> '0'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_ITVM'
		RETURN
	END


END


--*************************************************************************
--           STEP 8
--*************************************************************************

IF (@FLAGDIS = 'S')
BEGIN

	SELECT @DATADIS = @DATADECOR
	
	-- SE LA DATA DI DECORRENZA è NEL PASSATO, DISATTIVO COMUNQUE DA DOMANI
	
	IF (@DATADECOR <= @OGGI)
	BEGIN
		SELECT @DATADIS = @DOMANI	
		SELECT @DATA_INS_LET =  @OGGI
	END
	ELSE
	BEGIN
		SELECT @DATA_INS_LET =  convert (char(8), dateadd(day, -1, @DATADIS),112)
	END

	-------------------------------------------------------------------------------------------------------------------------------
	------------------------------------------- DISATTIVAZIONE CONI -------------------------------------------
	-------------------------------------------------------------------------------------------------------------------------------	
	SELECT @STATOOGGI_CONI = NULL
	SELECT @STATOOGGI_CONI = LSRSER_CONI_STATO 
	FROM LSRSER_CONI
	WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
		AND LSRSER_CONI_DATA_DECOR =
			(SELECT MAX(LSRSER_CONI_DATA_DECOR) 
			FROM LSRSER_CONI
			WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIA
				AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
				AND LSRSER_CONI_DATA_DECOR <= @OGGI)
	
	print @STATOOGGI_CONI
	IF @STATOOGGI_CONI = '1' OR @STATOOGGI_CONI = '2'
	BEGIN
	
		IF @STATOOGGI_CONI = '2' 
		BEGIN
			SELECT @DATALET = '19000101'
		END 
		ELSE
		BEGIN
			SELECT @DATALET = '00000000'
		END
		SELECT @FKPRO = @OGGI + @ORAINS
		INSERT INTO LSRLET_CONI
		VALUES(@RICEVITORIA,@DATA_INS_LET,@ORAINS,'D',@DATADIS,'LSRPRO',@FKPRO,@DATALET,'SERVIZIO DISABILITATO PER CESSAZIONE TITOLARE',@FIRMA,'V')
		
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE IN INSERT/UPDATE SU LSRLET'
			ROLLBACK TRANSACTION
			RETURN
		END
			
		INSERT INTO LSRSER_CONI VALUES (@RICEVITORIA,@OGGI,@ORAINS, '2',@DATADIS,@TIPOPROVV,@DATAPROVV,@NUMPROVV,@FIRMA,NULL,'00000000','Y')
		
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE INSERIMENTO VARIAZIONE STATO'
			ROLLBACK TRANSACTION
			RETURN
		END
		
	END
	
	-- METTO AD N IL FLAG VALIDITA' DEI RECORD PRESENTI SU LSRSER_CONI CON DATA VALIDITA' MAGGIORE DI QUELLA DEL RECORD INSERITO
	UPDATE LSRSER_CONI
	SET LSRSER_CONI_FLAG_VALIDITA = 'N' 
	WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_CONI_DATA_DECOR >  @DATADIS
	AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
	AND (LSRSER_CONI_TIPO_PROVV not in ('I', 'S', 'R')or 
	 LSRSER_CONI_TIPO_PROVV IS NULL)
	
	-------------------------------------------------------------------------------------------------------------------------------
	------------------------------------------- DISATTIVAZIONE ST ----------------------------------------------
	-------------------------------------------------------------------------------------------------------------------------------
	--UN CAMBIO INTESTAZIONE CONI COMPORTA IN AUTOMATICO UNA DISATTIVAZIONE DEL SERVIZIO 
	--ST SE ATTIVO
	-- SE LA DATA DI DECORRENZA è NEL PASSATO, DISATTIVO COMUNQUE DA DOMANI
	
	IF (@DATADECOR <= @OGGI)
	BEGIN
		SELECT @DATADIS = @DOMANI	
		SELECT @DATA_INS_LET =  @OGGI
	END
	ELSE
	BEGIN
		SELECT @DATA_INS_LET =  convert (char(8), dateadd(day, -1, @DATADIS),112)
	END
	
	SELECT @STATOOGGI_ST = NULL
	SELECT @STATOOGGI_ST = LSRSER_ST_STATO 
	FROM LSRSER_ST
	WHERE LSRSER_ST_KEY_ID_RICEV = @RICEVITORIA
		AND LSRSER_ST_FLAG_VALIDITA = 'Y'
		AND LSRSER_ST_DATA_DECOR =
			(SELECT MAX(LSRSER_ST_DATA_DECOR) 
			FROM LSRSER_ST
			WHERE LSRSER_ST_KEY_ID_RICEV = @RICEVITORIA
				AND LSRSER_ST_FLAG_VALIDITA = 'Y'
				AND LSRSER_ST_DATA_DECOR <= @OGGI)
	
	print @STATOOGGI_ST
	IF @STATOOGGI_ST = '1' OR @STATOOGGI_ST = '2'
	BEGIN
	
		IF @STATOOGGI_ST = '2' 
		BEGIN
			SELECT @DATALET = '19000101'
		END 
		ELSE
		BEGIN
			SELECT @DATALET = '00000000'
		END
		SELECT @FKPRO = @OGGI + @ORAINS
		INSERT INTO LSRLET_ST
		VALUES(@RICEVITORIA,@DATA_INS_LET,@ORAINS,'D',@DATADIS,'LSRPRO',@FKPRO,@DATALET,'SERVIZIO DISABILITATO PER CESSAZIONE TITOLARE',@FIRMA,'V')
	
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE IN INSERT/UPDATE SU LSRLET'
			ROLLBACK TRANSACTION
			RETURN
		END
			
		INSERT INTO LSRSER_ST VALUES 
			(@RICEVITORIA,
			@OGGI,
			@ORAINS, 
			'2',
			'D',
			@DATADIS,  
			@TIPOPROVV,
			@DATAPROVV,
			@NUMPROVV, 
			@FIRMA,
			'SERVIZIO DISABILITATO PER CESSAZIONE TITOLARE',
			'00000000',
			'Y')
	
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE INSERIMENTO VARIAZIONE STATO'
			ROLLBACK TRANSACTION
			RETURN
		END
		
	END
	
	-------------------------------------------------------------------------------------------------------------------------------
	------------------------------------------- DISATTIVAZIONE TRIS -------------------------------------------
	-------------------------------------------------------------------------------------------------------------------------------	
	SELECT @STATOOGGI_TRIS = NULL
	SELECT @STATOOGGI_TRIS = LSRSER_TRIS_STATO 
	FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
		AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
		AND LSRSER_TRIS_DATA_DECOR =
			(SELECT MAX(LSRSER_TRIS_DATA_DECOR) 
			FROM LSRSER_TRIS
			WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
				AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
				AND LSRSER_TRIS_DATA_DECOR <= @OGGI)
	
	print @STATOOGGI_TRIS
	IF @STATOOGGI_TRIS = '1' OR @STATOOGGI_TRIS = '2'
	BEGIN
	
		IF @STATOOGGI_TRIS = '2' 
		BEGIN
			SELECT @DATALET = '19000101'
		END 
		ELSE
		BEGIN
			SELECT @DATALET = '00000000'
		END
		SELECT @FKPRO = @OGGI + @ORAINS
		INSERT INTO LSRLET_GS
		VALUES(@RICEVITORIA,@DATA_INS_LET,@ORAINS,'08', 'D',@DATADIS,'LSRPRO',@FKPRO,@DATALET,'SERVIZIO DISABILITATO PER CESSAZIONE TITOLARE',@FIRMA,'V')
		
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE IN INSERT/UPDATE SU LSRLET'
			ROLLBACK TRANSACTION
			RETURN
		END
			
		INSERT INTO LSRSER_TRIS VALUES (@RICEVITORIA,@OGGI,@ORAINS, '2',@DATADIS,@TIPOPROVV,@DATAPROVV,@NUMPROVV, '', @FIRMA,'Servizio disabilitato per cambio intestazione', '00000000','Y')
		
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE INSERIMENTO VARIAZIONE STATO'
			ROLLBACK TRANSACTION
			RETURN
		END
		
	END
	
	-- METTO AD N IL FLAG VALIDITA' DEI RECORD PRESENTI SU LSRSER_TRIS CON DATA VALIDITA' MAGGIORE DI QUELLA DEL RECORD INSERITO
	UPDATE LSRSER_TRIS
	SET LSRSER_TRIS_FLAG_VALIDITA = 'N' 
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_TRIS_DATA_DECOR >  @DATADIS
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
	AND (LSRSER_TRIS_TIPO_PROVV not in ('I', 'S', 'R')or 
	 LSRSER_TRIS_TIPO_PROVV IS NULL)


	-------------------------------------------------------------------------------------------------------------------------------
	------------------------------------------- DISATTIVAZIONE GP -------------------------------------------
	-------------------------------------------------------------------------------------------------------------------------------	
	SELECT @STATOOGGI_GP = NULL
	SELECT @STATOOGGI_GP = LSRSER_GP_STATO,
		 @TIPOPV = lsrser_gp_tipo_pv
	FROM LSRSER_GP
	WHERE LSRSER_GP_KEY_ID_RICEV = @RICEVITORIA
		AND LSRSER_GP_FLAG_VALIDITA = 'Y'
		AND LSRSER_GP_DATA_DECOR =
			(SELECT MAX(LSRSER_GP_DATA_DECOR) 
			FROM LSRSER_GP
			WHERE LSRSER_GP_KEY_ID_RICEV = @RICEVITORIA
				AND LSRSER_GP_FLAG_VALIDITA = 'Y'
				AND LSRSER_GP_DATA_DECOR <= @OGGI)
	
	print @STATOOGGI_GP
	IF @STATOOGGI_GP = '1' OR @STATOOGGI_GP = '2'
	BEGIN
	
		IF @STATOOGGI_GP = '2' 
		BEGIN
			SELECT @DATALET = '19000101'
		END 
		ELSE
		BEGIN
			SELECT @DATALET = '00000000'
		END
		SELECT @FKPRO = @OGGI + @ORAINS
		INSERT INTO LSRLET_GS
		VALUES(@RICEVITORIA,@DATA_INS_LET,@ORAINS,'02', 'D',@DATADIS,'LSRPRO',@FKPRO,@DATALET,'SERVIZIO DISABILITATO PER CESSAZIONE TITOLARE',@FIRMA,'V')
		
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE IN INSERT/UPDATE SU LSRLET'
			ROLLBACK TRANSACTION
			RETURN
		END
			
		INSERT INTO LSRSER_GP VALUES (@RICEVITORIA,@OGGI,@ORAINS, '2','D',@DATADIS,@TIPOPROVV,@DATAPROVV,@NUMPROVV, @TIPOPV, @FIRMA,'Servizio disabilitato per cambio intestazione', '00000000','Y')
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE INSERIMENTO VARIAZIONE STATO'
			ROLLBACK TRANSACTION
			RETURN
		END
		
	END
	
	-- METTO AD N IL FLAG VALIDITA' DEI RECORD PRESENTI SU LSRSER_TRIS CON DATA VALIDITA' MAGGIORE DI QUELLA DEL RECORD INSERITO
	UPDATE LSRSER_GP
	SET LSRSER_GP_FLAG_VALIDITA = 'N' 
	WHERE LSRSER_GP_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_GP_DATA_DECOR >  @DATADIS
	AND LSRSER_GP_FLAG_VALIDITA = 'Y'
	AND (LSRSER_GP_TIPO_PROVV not in ('I', 'S', 'R')or 
	 LSRSER_GP_TIPO_PROVV IS NULL)


END	

--*************************************************************************
--           STEP 9
--*************************************************************************

--UN CAMBIO INTESTAZIONE CONI COMPORTA IN AUTOMATICO UNA DISATTIVAZIONE DEL SERVIZIO 
--GRATTA E VINCI SE ATTIVO
IF ISNUMERIC(LTRIM(RTRIM(@RICEVITORIA) )) = 1
BEGIN
	-- SE LA DATA DI DECORRENZA è NEL PASSATO, DISATTIVO COMUNQUE DA DOMANI
	
	IF (@DATADECOR <= @OGGI)
	BEGIN
		SELECT @DATADIS = @DOMANI	
		SELECT @DATA_INS_LET =  @OGGI
	END
	ELSE
	BEGIN
		SELECT @DATA_INS_LET =  convert (char(8), dateadd(day, -1, @DATADIS),112)
	END
	
	SELECT @STATOOGGI_GEV = NULL
	SELECT @STATOOGGI_GEV = LSRSER_GEV_STATO 
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
		AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
		AND LSRSER_GEV_DATA_DECOR =
			(SELECT MAX(LSRSER_GEV_DATA_DECOR) 
			FROM LSRSER_GEV
			WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
				AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
				AND LSRSER_GEV_DATA_DECOR <= @OGGI)
	
	print @STATOOGGI_GEV
	IF @STATOOGGI_GEV = '1' OR @STATOOGGI_GEV = '2'
	BEGIN
	
		IF @STATOOGGI_GEV = '2' 
		BEGIN
			SELECT @DATALET = '19000101'
		END 
		ELSE
		BEGIN
			SELECT @DATALET = '00000000'
		END
		SELECT @FKPRO = @OGGI + @ORAINS
		INSERT INTO LSRLET
		VALUES(@RICEVITORIA,@DATA_INS_LET,@ORAINS,'09','D',@DATADIS,'LSRPRO',@FKPRO,@DATALET,'SERVIZIO DISABILITATO PER CESSAZIONE TITOLARE',@FIRMA,'V')
	
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE IN INSERT/UPDATE SU LSRLET'
			ROLLBACK TRANSACTION
			RETURN
		END
			
		INSERT INTO LSRSER_GEV VALUES (@RICEVITORIA,@OGGI,@ORAINS, '2',@DATADIS, 'D', @TIPOPROVV,@DATAPROVV,@NUMPROVV, '', @FIRMA,NULL,'00000000','Y')
		
		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSGERR = '9999 - ' + @RICEVITORIA +' ERRORE INSERIMENTO VARIAZIONE STATO'
			ROLLBACK TRANSACTION
			RETURN
		END
		
	END
END


SELECT @NUMERR = '0000'
SELECT @MSGERR = @NUMERR
COMMIT TRANSACTION

RETURN
GO
