/****** Object:  StoredProcedure [dbo].[INSERT_LSRPRO_E_CONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE     PROCEDURE [dbo].[INSERT_LSRPRO_E_CONI]
 
	@RICEVITORIA 	CHAR(6),
	@CODCONI	CHAR(6),
	@TIPORIV	CHAR(1),
	@TIPOPROVV	CHAR(1),
	@DATAPROVV	CHAR(8),
	@NUMPROVV	CHAR(14),
	@CAUSALE	CHAR(40),
	@FIRMA		CHAR(17),
	@EMANATO	CHAR(25),
	@DATADECOR	CHAR(8),


	@COGNOME	CHAR(24),
	@NOME		CHAR(20),
	@DENOMINAZIONE		CHAR(50),
	@DATANASC	CHAR(8),
	@LUOGONASC	CHAR(24),
	@PROVNASC	CHAR(2),
	@CODFISC	CHAR(16),
	@SESSO		CHAR(1),
	@INDIRIZZO	CHAR(40),
	@CAP		CHAR(5),
	@COMUNE		CHAR(24),
	@PROVINCIA	CHAR(2),
	@PARTITAIVA	CHAR(11),
	@TELCASA	CHAR(12),
	@TELCELL	CHAR(12),

	@NUMERR 	VARCHAR(4) OUTPUT,

	@MSGERR 	VARCHAR(200) OUTPUT

AS

DECLARE
@OGGI			CHAR(8),
@DOMANI			CHAR(8),
@DATADIS		CHAR(8),
@DATAINS		CHAR(8),
@ORAINS			CHAR(8),
@DATAINSLET		CHAR(8),
@ORAINSLET		CHAR(8),
@DATAAPPO		CHAR(8),
@APPORICEV		CHAR(6),
@FK_DATA_INS_TIT	CHAR(8),
@FK_ORA_INS_TIT		CHAR(8),
@FKPRO			CHAR(16),
@DATALET		CHAR(8),
@DATA_INS_LET		CHAR(8),
@STATOOGGI		CHAR(1)

SELECT @OGGI = CONVERT(CHAR(8),GETDATE(),112)
SELECT @DOMANI = CONVERT(CHAR(8),GETDATE() + 1,112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)  + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2) 
SELECT @DATAAPPO = NULL

/*
-- STEP DA ESEGUIRE
1) VERIFICA CHE NON ESISTONO ALTRI PROVVEDIMENTI CON STESSA DATA E NUMERO PROVVEDIMENTO
2) VERIFICA CHE LA DATA DECORRENZA DEVE ESSERE SUPERIORE ALLA DECORRENZA DEL TITOLARE ATTUALE
3) VERIFICA CHE NON ESISTONO ALTRI PROVVEDIMENTI CON STESSA DATA VALIDITA'
4) VERIFICA CHE LA DATA DECORRENZA NON SIA NEL FUTURO
5) INSERIMENTO RECORD SU LSRTIT_CONI
6) INSERIMENTO RECORD SU LSRPRO_CONI
7) AGGIORNO LE FK AI CONTRATTI
*/



--*************************************************************************
--           STEP 1
--*************************************************************************
SELECT @APPORICEV = NULL
SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
FROM LSRPRO_CONI 
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_CONI_FLAG_VALIDITA = 'Y'
AND LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
AND lsrpro_coni_data_provv = @NUMPROVV
AND lsrpro_coni_prog_provv = @DATAPROVV

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO CON STESSA DATA  E NUMERO'
	RETURN 
END

--*************************************************************************
--           STEP 2
--*************************************************************************
SELECT @DATAAPPO = NULL
SELECT @DATAAPPO = lsrtit_coni_data_validita,
	@FK_DATA_INS_TIT = LSRTIT_CONI_KEY_DATA_INS,
	@FK_ORA_INS_TIT = LSRTIT_CONI_KEY_ORA_INS
FROM LSRTIT_CONI
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
AND (lsrtit_coni_data_validita + lsrtit_coni_ora_validita) =
	(select max(lsrtit_coni_data_validita + lsrtit_coni_ora_validita)
	from lsrtit_coni
	where lsrtit_coni_key_id_ricev = @RICEVITORIA
	and  lsrtit_coni_data_validita <= @OGGI
	and  lsrtit_coni_flag_validita = 'Y')
AND LSRTIT_CONI_FLAG_VALIDITA = 'Y'

IF (@DATAAPPO <>'' OR @DATAAPPO IS NOT NULL)
BEGIN
	IF @DATAAPPO >= @DATADECOR
	BEGIN
                           SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - LA DATA DECORRENZA DEVE ESSERE SUPERIORE A ' + @DATAAPPO 
                           RETURN 
	END
END

--*************************************************************************
--           STEP 3
--*************************************************************************
SELECT @APPORICEV = NULL
SELECT @APPORICEV = LSRPRO_CONI_KEY_ID_RICEV 
FROM LSRPRO_CONI
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_CONI_FLAG_VALIDITA = 'Y'
AND LSRPRO_CONI_TIPO_PROVV = @TIPOPROVV
AND LSRPRO_CONI_DECOR_DAL = @DATADECOR

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ESISTE GIà UN PROVVEDIMENTO CON STESSA DATA DECORRENZA'
	RETURN 
END


--*************************************************************************
--           STEP 4
--*************************************************************************

IF (@DATADECOR > @OGGI)
BEGIN
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - LA DATA DECORRENZA NON DEVE ESSERE NEL FUTURO'
	RETURN 
END


BEGIN TRANSACTION

--*************************************************************************
--           STEP 5
--*************************************************************************


INSERT INTO lsrtit_coni VALUES(
	@RICEVITORIA,
	@OGGI,
	@ORAINS,
	@TIPORIV,
	@CODCONI,
	@COGNOME,
	@NOME, 
	@DENOMINAZIONE, 
	@DATANASC,
	@LUOGONASC,
	@PROVNASC,
	@CODFISC,
	@SESSO,
	@INDIRIZZO,
	@CAP,
	@COMUNE,
	@PROVINCIA,
	@PARTITAIVA,
	@TELCASA,
	@TELCELL,
	@FIRMA,
	@DATAPROVV, 
	@NUMPROVV, 
	@TIPOPROVV, 
	@DATADECOR , 
	'00000000', 
	'Y', 
	'1', 
	'00000000')

IF @@ERROR <> 0 
BEGIN
	 
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE ACQUISIZIONE TITOLARE'
	ROLLBACK TRANSACTION
	RETURN 0
                  
END


--*************************************************************************
--           STEP 6
--*************************************************************************
INSERT INTO LSRPRO_CONI VALUES (
	@RICEVITORIA,
	@OGGI,
	@ORAINS,
	@TIPOPROVV,
	@DATAPROVV,
	@NUMPROVV,
	@DATADECOR,
	'',
	@CAUSALE,
	@FIRMA,
	@EMANATO,
	@OGGI,
	@ORAINS,
	'Y',
	'00000000'
	)

IF @@ERROR <> 0 
BEGIN
	 
	SELECT @NUMERR = '9999'
	SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE ACQUISIZIONE PROVVEDIMENTO'
	ROLLBACK TRANSACTION
	RETURN 0
                  
END

--*************************************************************************
--           STEP 7
--*************************************************************************

UPDATE LSRPRO_CONI
SET LSRPRO_CONI_FK_DATA_INS_TIT = @OGGI,
	LSRPRO_CONI_FK_ORA_INS_TIT = @ORAINS
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRPRO_CONI_FK_DATA_INS_TIT = @FK_DATA_INS_TIT
	AND LSRPRO_CONI_FK_ORA_INS_TIT = @FK_ORA_INS_TIT 

UPDATE LSRCON_CONI
SET LSRCON_CONI_FK_DATA_INS_TIT = @OGGI,
	LSRCON_CONI_FK_ORA_INS_TIT = @ORAINS
WHERE LSRCON_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRCON_CONI_FLAG_ANAG = '1'

UPDATE LSRFID_CONI
SET LSRFID_CONI_FK_DATA_INS_TIT = @OGGI,
	LSRFID_CONI_FK_ORA_INS_TIT = @ORAINS
WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRFID_CONI_FLAG_ANAG = '1'

UPDATE LSRNUO_CONI
SET LSRNUO_CONI_FK_DATA_INS_TIT = @OGGI,
	LSRNUO_CONI_FK_ORA_INS_TIT = @ORAINS
WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRNUO_CONI_FLAG_ANAG = '1'

UPDATE LSRQST_CONI
SET LSRQST_CONI_FK_DATA_INS_TIT = @OGGI,
	LSRQST_CONI_FK_ORA_INS_TIT = @ORAINS
WHERE LSRQST_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRQST_CONI_FLAG_ANAG = '1'

UPDATE LSRRAD_CONI
SET LSRRAD_CONI_FK_DATA_INS_TIT = @OGGI,
	LSRRAD_CONI_FK_ORA_INS_TIT = @ORAINS
WHERE LSRRAD_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRAD_CONI_FLAG_ANAG = '1'

UPDATE LSRRIN_CONI
SET LSRRIN_CONI_FK_DATA_INS_TIT = @OGGI,
	LSRRIN_CONI_FK_ORA_INS_TIT = @ORAINS
WHERE LSRRIN_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRIN_CONI_FLAG_ANAG = '1'


UPDATE LSRTLP_ST
SET LSRTLP_ST_FK_DATA_INS_TIT = @OGGI,
	LSRTLP_ST_FK_ORA_INS_TIT = @ORAINS
WHERE LSRTLP_ST_KEY_ID_RICEV = @RICEVITORIA
	AND LSRTLP_ST_FLAG_ANAG = '1'


UPDATE LSRRAD_ST
SET LSRRAD_ST_FK_DATA_INS_TIT = @OGGI,
	LSRRAD_ST_FK_ORA_INS_TIT = @ORAINS
WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRAD_ST_FLAG_ANAG = '1'


----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI SPORTIVI -----------------------------------
----------------------------------------------------------------------------------------------------------------------

UPDATE lsrcon_GS
SET lsrcon_GS_FK_DATA_INS_TIT = @OGGI,
	lsrcon_GS_FK_ORA_INS_TIT = @ORAINS
WHERE lsrcon_GS_KEY_ID_RICEV = @RICEVITORIA
	AND lsrcon_GS_FLAG_ANAG  = '1'

UPDATE lsrnuo_GS
SET lsrnuo_GS_FK_DATA_INS_TIT = @OGGI,
	lsrnuo_GS_FK_ORA_INS_TIT = @ORAINS
WHERE lsrnuo_GS_KEY_ID_RICEV = @RICEVITORIA
	AND lsrnuo_GS_FLAG_ANAG  = '1'

UPDATE lsrrad_GS
SET lsrrad_GS_FK_DATA_INS_TIT = @OGGI,
	lsrrad_GS_FK_ORA_INS_TIT = @ORAINS
WHERE lsrrad_GS_KEY_ID_RICEV = @RICEVITORIA
	AND lsrrad_GS_FLAG_ANAG  = '1'

UPDATE lsrtlp_GS
SET lsrtlp_GS_FK_DATA_INS_TIT = @OGGI,
	lsrtlp_GS_FK_ORA_INS_TIT = @ORAINS
WHERE lsrtlp_GS_KEY_ID_RICEV = @RICEVITORIA
	AND lsrtlp_GS_FLAG_ANAG  = '1'

----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI PUBBLICI -----------------------------------
----------------------------------------------------------------------------------------------------------------------

UPDATE lsrcon_GP
SET lsrcon_GP_FK_DATA_INS_TIT = @OGGI,
	lsrcon_GP_FK_ORA_INS_TIT = @ORAINS
WHERE lsrcon_GP_KEY_ID_RICEV = @RICEVITORIA
	AND lsrcon_GP_FLAG_ANAG  = '1'


UPDATE LSRFID_GP
SET LSRFID_GP_FK_DATA_INS_TIT = @OGGI,
	LSRFID_GP_FK_ORA_INS_TIT = @ORAINS
WHERE LSRFID_GP_KEY_ID_RICEV = @RICEVITORIA
	AND LSRFID_GP_FLAG_ANAG  = '1'




IF ISNUMERIC(LTRIM(RTRIM(@RICEVITORIA) )) = 1
BEGIN
	UPDATE LSRCON_GEV 
	SET LSRCON_GEV_FK_DATA_INS_TIT_GEV = @OGGI,
		LSRCON_GEV_FK_ORA_INS_TIT_GEV =@ORAINS
	WHERE LSRCON_GEV_COD_LOTTO = @RICEVITORIA
		AND LSRCON_GEV_FLAG_ANAG = '1'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_GEV'
		RETURN
	END

	-- LSRQST_GEV
	UPDATE LSRQST_GEV 
	SET LSRQST_GEV_FK_DATA_INS_TIT_GEV = @OGGI,
		LSRQST_GEV_FK_ORA_INS_TIT_GEV = @ORAINS
	WHERE LSRQST_GEV_COD_LOTTO = @RICEVITORIA
		AND LSRQST_GEV_FLAG_ANAG = '1'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRQST_GEV'
		RETURN
	END

	-- LSRFID_GEV
	UPDATE LSRFID_GEV 
	SET LSRFID_GEV_FK_DATA_INS_TIT_GEV = @OGGI,
		LSRFID_GEV_FK_ORA_INS_TIT_GEV = @ORAINS
	WHERE LSRFID_GEV_COD_LOTTO = @RICEVITORIA
	AND  LSRFID_GEV_FLAG_ANAG = '1'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_GEV'
		RETURN
	END

	-- LSRRAD_GEV
	UPDATE LSRRAD_GEV 
	SET LSRRAD_FK_DATA_INS_TIT_GEV = @OGGI,
		LSRRAD_FK_ORA_INS_TIT_GEV = @ORAINS
	WHERE LSRRAD_COD_LOTTO = @RICEVITORIA
	AND LSRRAD_FLAG_ANAG = '1'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
		RETURN
	END

	-- LSRORD_GEV
	UPDATE LSRORD_GEV 
	SET LSRORD_GEV_FK_DATA_INS_TIT_GEV = @OGGI,
		LSRORD_GEV_FK_ORA_INS_TIT_GEV = @ORAINS
	WHERE LSRORD_GEV_COD_LOTTO = @RICEVITORIA
	AND LSRORD_GEV_FLAG_ANAG = '1'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRORD_GEV'
		RETURN
	END

	-- LSRCON_ITVM
	UPDATE LSRCON_ITVM 
	SET LSRCON_ITVM_FK_DATA_INS_TIT_GEV = @OGGI,
		LSRCON_ITVM_FK_ORA_INS_TIT_GEV = @ORAINS
	WHERE LSRCON_ITVM_COD_LOTTO = @RICEVITORIA
	AND LSRCON_ITVM_FLAG_ANAG = '1'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_ITVM'
		RETURN
	END

END

SELECT @NUMERR = '0000'
SELECT @MSGERR = @NUMERR + ' - ELABORAZIONE TERMINATA CORRETTAMENTE'
COMMIT TRANSACTION

RETURN
GO
