/****** Object:  StoredProcedure [dbo].[GEV_ASSOCIAZIONE_TITOLARE]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GEV_ASSOCIAZIONE_TITOLARE]

@CODLTM 		VARCHAR(7),
@COGNOME		VARCHAR(24),
@NOME		VARCHAR(20),
@ASSOCIAZIONE	CHAR(1)	OUTPUT

AS

SELECT @ASSOCIAZIONE = NULL

SELECT @ASSOCIAZIONE =  LSRRAD_COD_ASSOCIAZIONE
FROM LSRRAD
WHERE LSRRAD_KEY_ID_RICEV = @CODLTM
AND LSRRAD_COGNOME = @COGNOME
AND LSRRAD_NOME = @NOME
AND LSRRAD_FONTE = 'A'
AND LSRRAD_TIPO_SERVIZIO = '09'

IF @ASSOCIAZIONE IS NULL
BEGIN
	SELECT @ASSOCIAZIONE = LSRCON_GEV_ASSOCIAZIONE
	FROM LSRCON_GEV
	WHERE LSRCON_GEV_COD_LOTTO = @CODLTM
	AND LSRCON_GEV_COGNOME = @COGNOME
	AND LSRCON_GEV_NOME = @NOME
END
GO
