/****** Object:  StoredProcedure [dbo].[CREA_RAD_ATTIVAZIONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CREA_RAD_ATTIVAZIONI]  

	@QUERYSQL 			VARCHAR(2500),
	@OPERAZIONE 		CHAR(1), 
	@CODSER 			CHAR(2), 
	@CON	 			CHAR(15), 
	@CAS	 			CHAR(15), 
	@FID	 			CHAR(15), 
	@APS	 			CHAR(15), 
	@RAD	 			CHAR(15), 
	@FLAGLOTTO 			CHAR(1), 

	@NOMESERVER 		CHAR(20), 
	@FIRMA	 		CHAR(17), 
	@RC		 		CHAR(70)  OUTPUT


AS


DECLARE

@RICEV		CHAR(6),
@RICERIN		CHAR(6),
@DATARINRIN		char(8),
@RICEAPPO		CHAR(7),
@RICESER		CHAR(6),
@RICEFID		CHAR(6),
@RICEAPS		CHAR(6),
@STATOLOT		CHAR(1),
@STATODIA		CHAR(1),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@NOMEFILE		CHAR(100),
@FLAGADESIONE	CHAR(1), 
@NOMEJOB		CHAR(6),
@NUMREC		INT,
@PATHID		INT

SELECT @NOMEJOB = 'NO_LOG'

SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @CON = RTRIM(@CON)
SELECT @CAS = RTRIM(@CAS)
SELECT @FID = RTRIM(@FID)
SELECT @APS = RTRIM(@APS)
SELECT @RAD = RTRIM(@RAD)

SELECT @PATHID = 80
SELECT @NUMREC = 0

IF @CODSER = '02'
BEGIN
	SELECT @NOMEFILE = 'F101_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END

IF @CODSER = '05'
BEGIN
	SELECT @NOMEFILE = 'BOLLO_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END

IF @CODSER = '08'
BEGIN
	SELECT @NOMEFILE = 'TRIS_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END

--CANCELLO IL FILE DI OUTPUT
EXEC MSDB..UT_AA009 80, @NOMEFILE, 9999, @NOMEJOB

SELECT @QUERYSQL = 'DECLARE CUR_CON CURSOR FOR ' + RTRIM(@QUERYSQL)  + ' ORDER BY 1'
EXECUTE (@QUERYSQL) 
OPEN CUR_CON FETCH NEXT FROM CUR_CON INTO @RICEV WHILE @@FETCH_STATUS = 0 

BEGIN
	SELECT @RICESER = NULL

	--Inizializzo la variabile che mi indica nel caso del bollo se devo effettuare contestualmente l'adesione
	SELECT @FLAGADESIONE = '0'


	--VERIFICO LO STATO DEL SERVIZIO
	IF @CODSER = '02'
	BEGIN
		SELECT @RICESER = LSRSER_F101_KEY_ID_RICEV 
		FROM LSRSER_F101
		WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
		AND LSRSER_F101_FLAG_VALIDITA = 'Y'
		GROUP BY LSRSER_F101_KEY_ID_RICEV
		HAVING SUM (CONVERT(INT,LSRSER_F101_STATO)) = 0
	END
	ELSE IF @CODSER = '05'
	BEGIN
		SELECT @RICESER = LSRSER_BOLLO_KEY_ID_RICEV 
		FROM LSRSER_BOLLO
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
		GROUP BY LSRSER_BOLLO_KEY_ID_RICEV
		HAVING SUM (CONVERT(INT,LSRSER_BOLLO_STATO)) = 0

		-- Anche se la ricevitoria non ha effettuato l'adesione, deve comunque comparire nella lista delle attivabili
		-- Modifica del 22/10/2001 -  MEV Anaconda
		IF @RICESER = '' OR @RICESER IS NULL OR @RICESER = ' '
		BEGIN
			-- Verifica che la ricevitoria non abbia fatto l'adesione
			SELECT @RICESER = ''

			SELECT @RICESER = LSRSER_BOLLO_KEY_ID_RICEV 
			FROM LSRSER_BOLLO
			WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
			AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
			GROUP BY LSRSER_BOLLO_KEY_ID_RICEV

			IF @RICESER = '' OR @RICESER IS NULL OR @RICESER = ' '
			BEGIN
				-- Varaibile che indica che deve  essere effettuata contestualmente anche l'adesione
				SELECT @FLAGADESIONE = '1'
			END
			ELSE
			BEGIN
				SELECT @RICESER = NULL
			END

		END
	END
	ELSE IF @CODSER = '08'
	BEGIN
		SELECT @RICESER = LSRSER_TRIS_KEY_ID_RICEV 
		FROM LSRSER_TRIS
		WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
		AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
		GROUP BY LSRSER_TRIS_KEY_ID_RICEV
		HAVING SUM (CONVERT(INT,LSRSER_TRIS_STATO)) = 0
	END

	IF @RICESER <> '' OR @RICESER IS NOT NULL OR @RICESER <> ' '
	BEGIN
		SELECT @RICERIN = NULL
		SELECT @DATARINRIN = NULL

		--VERIFICO SE CI SONO RINUNCE AL SERVIZIO
		SELECT @RICERIN = LSRRIN_KEY_ID_RICEV ,
			@DATARINRIN = LSRRIN_DATA_RINUNCIA_RINUNCIA
		FROM LSRRIN
		WHERE LSRRIN_KEY_ID_RICEV = @RICEV
		AND LSRRIN_CODICE_SERVIZIO = @CODSER
		AND LSRRIN_FLAG_ANAG = '1'

--		IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' '
		IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' ' OR (@DATARINRIN <>''  AND @DATARINRIN <>'00000000' AND @DATARINRIN IS NOT NULL)
		BEGIN
			SELECT @STATOLOT = NULL

			--CONTROLLO LO STATO DEL LOTTO
			SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
			WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
			--AND LSRSER_LOTTO_FT_VOS <> '00000000'
			AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
			AND LSRSER_LOTTO_DATA_DECOR =
			(
				SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
				FROM LSRSER_LOTTO
				WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
				--AND LSRSER_LOTTO_FT_VOS <> '00000000'
				AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
				AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE(),112)
			)

			IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
			--IF @STATOLOT = 'A' --OR  @STATOLOT = '' OR @STATOLOT = ' '    
--			IF @STATOLOT <> 'S' AND @STATOLOT <> 'M' AND @STATOLOT <> 'R'
			BEGIN

/*
				SELECT @STATODIA = NULL
				--CONTROLLO LO STATO DELLA RICEVITORIA SU DIAMANTE_NUOVE
				SELECT @STATODIA = FLAG_ATTIVA FROM DIAMANTE_NUOVE
					WHERE DIAMANTE_KEY_ID_RICEV = @RICEV

					IF @STATODIA <> 'N' OR @STATODIA IS NULL
					BEGIN
						SELECT @NUMREC = @NUMREC + 1
						IF @CODSER = '05'
						BEGIN
							SELECT @RICEAPPO = NULL
							SELECT @RICEAPPO = @RICEV+'S'
							IF @NUMREC = 1
							BEGIN
								EXECUTE MASTER..SCRIVIFILE @NOMEFILE,@RICEAPPO,1
							END
							ELSE

							BEGIN
								EXECUTE MASTER..SCRIVIFILE @NOMEFILE,@RICEAPPO,0
							END
						END
						ELSE
						BEGIN
							IF @NUMREC = 1
							BEGIN
								EXECUTE MASTER..SCRIVIFILE @NOMEFILE,@RICEV,1
							END
							ELSE
							BEGIN
								EXECUTE MASTER..SCRIVIFILE @NOMEFILE,@RICEV,0
							END
						END

						EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA

					END
			END
			ELSE
			BEGIN
				IF @STATOLOT = 'A' 
				BEGIN
*/

				IF @CODSER = '05'
				BEGIN
					SELECT @RICEAPPO = NULL

					SELECT @RICEAPPO = @RICEV+'S'

					SELECT @NUMREC = @NUMREC + 1
					EXECUTE MSDB..UT_AA010 9999, @PATHID, @NOMEFILE,@RICEAPPO,  @NOMEJOB
				END
				ELSE
				BEGIN
					SELECT @NUMREC = @NUMREC + 1
					EXECUTE MSDB..UT_AA010 9999, @PATHID, @NOMEFILE,@RICEV,  @NOMEJOB
				END

				EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA

				 IF @CODSER = '05' AND  @FLAGADESIONE = '1'
				BEGIN
					-- Se deve  essere effettuata contestualmente anche l'adesione, occorre inserire un record su lsrlet per l'adesione
					EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,'I',@FIRMA						
				END
			END

		END
	END

FETCH NEXT FROM CUR_CON INTO @RICEV

END

SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)
--SELECT @RC =  @NOMEFILE

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
