/****** Object:  StoredProcedure [dbo].[CREA_RAD_ADESIONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CREA_RAD_ADESIONI] 

			@QUERYSQL 			VARCHAR(2500),
			@OPERAZIONE 		CHAR(1), 
			@CODSER 			CHAR(2), 
			@CON	 			CHAR(15), 
			@CAS	 			CHAR(15), 
			@FID	 			CHAR(15), 
			@APS	 			CHAR(15), 
			@RAD	 			CHAR(15), 
			@NOMESERVER 		CHAR(20), 
			@FIRMA	 		CHAR(17), 
			@RC		 		VARCHAR(100)  OUTPUT


AS


DECLARE

@RICEV		CHAR(6),
@RICERIN		CHAR(6),
@RICEAPPO		CHAR(14),
@RICESER		CHAR(6),
@RICEFID		CHAR(6),
@RICEAPS		CHAR(6),
@DATAADE		CHAR(8),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@NOMEFILE		VARCHAR(100),
@NOMEJOB		VARCHAR(25),
@PATHID		INT,
@NUMREC		INT

SELECT @NOMEJOB = 'NO_LOG'

SELECT @DATAADE = CONVERT(CHAR,GETDATE() + 1,112)

SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @CON = RTRIM(@CON)
SELECT @CAS = RTRIM(@CAS)
SELECT @FID = RTRIM(@FID)
SELECT @APS = RTRIM(@APS)
SELECT @RAD = RTRIM(@RAD)

--@PATHID = S_INTRANET/APP/RICE_STORICO
SELECT @PATHID = 80

IF @CODSER = '01'
BEGIN
	SELECT @NOMEFILE ='LOTTO_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END
IF @CODSER = '02'
BEGIN
	SELECT @NOMEFILE ='F101_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END
IF @CODSER = '05'
BEGIN
	SELECT @NOMEFILE ='BOLLO_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END
IF @CODSER = '08'
BEGIN
	SELECT @NOMEFILE ='TRIS_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END

SELECT @NUMREC = 0

--CANCELLO FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB

SELECT @QUERYSQL = 'DECLARE CUR_CON CURSOR FOR ' + RTRIM(@QUERYSQL)  +  ' ORDER BY 1'
EXECUTE (@QUERYSQL) 
OPEN CUR_CON 

FETCH NEXT FROM CUR_CON 
INTO @RICEV 

WHILE @@FETCH_STATUS = 0 

BEGIN

	SELECT @RICESER = NULL

	IF @CODSER = '02'
	BEGIN
		SELECT @RICESER = LSRSER_F101_KEY_ID_RICEV 
		FROM LSRSER_F101
		WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
		AND LSRSER_F101_FLAG_VALIDITA = 'Y'
	END

	IF @CODSER = '05'
	BEGIN
		SELECT @RICESER = LSRSER_BOLLO_KEY_ID_RICEV 
		FROM LSRSER_BOLLO
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
	END

	IF @CODSER = '08'
	BEGIN
		SELECT @RICESER = LSRSER_TRIS_KEY_ID_RICEV 
		FROM LSRSER_TRIS
		WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
		AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
	END


	IF @RICESER = '' OR @RICESER IS NULL OR @RICESER = ' '
	BEGIN
		SELECT @RICERIN = NULL
		--VERIFICO SE CI SONO RINUNCE AL SERVIZIO
		SELECT @RICERIN = LSRRIN_KEY_ID_RICEV FROM LSRRIN
			WHERE LSRRIN_KEY_ID_RICEV = @RICEV
			AND LSRRIN_CODICE_SERVIZIO = @CODSER
			AND LSRRIN_FLAG_ANAG = '1'

		IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' '
		BEGIN
			SELECT @RICEAPPO = NULL			
			SELECT @RICEAPPO = @RICEV + @DATAADE

			SELECT @NUMREC = @NUMREC + 1

			--SCRIVO IL FILE RAD
			EXEC MSDB..UT_AA010 9999,  @PATHID, @NOMEFILE, @RICEAPPO, @NOMEJOB
		END

		EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA

	END

FETCH NEXT FROM CUR_CON INTO @RICEV

END

SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)
--SELECT @RC =  @NOMEFILE

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
