/****** Object:  StoredProcedure [dbo].[INSERT_SER_LOTTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[INSERT_SER_LOTTO] 

	@RICEVITORIA 	CHAR(6),
	@DATAINS		CHAR(8),
	@ORAINS		CHAR(8),
	@DATADECOR		CHAR(8),
	@DATAPROVV		CHAR(8),
	@TIPOPROVV		CHAR(1),
	@NUMPROVV		CHAR(14),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(150),
	@OGGI			CHAR(8),
	@OPZIONE		CHAR(1),
	@OLDPROVV		CHAR(1),
	@OLDDATAPROVV	CHAR(8),
	@OLDPROGPROVV	CHAR(14),
	@OPZDIS		CHAR(5),
	@NUMERR 		VARCHAR(4) OUTPUT,
	@MSGERR 		VARCHAR(50) OUTPUT
AS

DECLARE @ASSOCIAZIONE	CHAR(1)

BEGIN TRANSACTION

SELECT @ASSOCIAZIONE=LSRSER_LOTTO_ASSOCIAZIONE
FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIA
AND LSRSER_LOTTO_DATA_DECOR =
(
	SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
	FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_DATA_DECOR <= @OGGI
	AND LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIA
)

IF @OPZDIS = 'TUTTI'
BEGIN
	IF @TIPOPROVV = 'R' OR @TIPOPROVV ='S' OR @TIPOPROVV = 'M'
	BEGIN
		SELECT @NOTE = 'IL PROVVEDIMENTO DISABILITA TUTTI I SERVIZI LOTTOMATICA - LIS' --F101,TRIS,BOLLO,GEV
	
		EXEC DISABILITA_SER_LOTTOMATICA @RICEVITORIA,@DATAINS,@ORAINS,@DATADECOR,@DATAPROVV,@TIPOPROVV,@NUMPROVV,@FIRMA,@OGGI,@NUMERR OUTPUT,@MSGERR OUTPUT
	
		IF @NUMERR <> '0000'
		BEGIN
			SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' - ERRORE IN ESECUZIONE DISABILITA_SER_LOTTOMATICA'
			ROLLBACK TRANSACTION
			RETURN
		END
	
		-- MODIFICA DEL 29/03/2002: AGGIUNTA CHIAMATA ALLA STORED PROCEDURE DISABILITA_SER_LIS (CDS)
		EXEC DISABILITA_SER_LIS @RICEVITORIA,@DATAINS,@ORAINS,@DATADECOR,@DATAPROVV,@TIPOPROVV,@NUMPROVV,@FIRMA,@OGGI,@NUMERR OUTPUT,@MSGERR OUTPUT
		IF @NUMERR <> '0000'
		BEGIN
			SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' - ERRORE IN ESECUZIONE DISABILITA_SER_LIS'
			ROLLBACK TRANSACTION
			RETURN
		END
	END
END

IF @OPZIONE <> 'F'
BEGIN

--	BEGIN TRANSACTION

	INSERT INTO LSRSER_LOTTO VALUES
	(@RICEVITORIA,@DATAINS,@ORAINS,@DATADECOR,
	@TIPOPROVV,@DATAPROVV,@NUMPROVV,
	@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_LOTTO'
		ROLLBACK TRANSACTION
		RETURN
	END
/*	ELSE
	BEGIN
		SELECT @NUMERR = '0000'
		SELECT @MSGERR = @NUMERR
		COMMIT TRANSACTION
	END
*/
END

ELSE

BEGIN
--	BEGIN TRANSACTION

	UPDATE LSRSER_LOTTO SET 
	LSRSER_LOTTO_FLAG_VALIDITA = 'N',
	LSRSER_LOTTO_KEY_DATA_INS = @DATAINS,
	LSRSER_LOTTO_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_LOTTO_TIPO_PROVV = @OLDPROVV
	AND LSRSER_LOTTO_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_LOTTO_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_LOTTO'
		ROLLBACK TRANSACTION
		RETURN
	END


--INIZIO MODIFICA 26-08-2002 F.GIACOVAZZI

	UPDATE LSRRIC SET 
	LSRRIC_FLAG_VALIDITA = 'N',
	LSRRIC_KEY_DATA_INS = @DATAINS,
	LSRRIC_KEY_ORA_INS = @ORAINS
	WHERE LSRRIC_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRIC_TIPO_PROVV = @OLDPROVV
	AND LSRRIC_DATA_PROVV = @OLDDATAPROVV
	AND LSRRIC_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRRIC'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRTIT SET 
	LSRTIT_FLAG_VALIDITA = 'N',
	LSRTIT_KEY_DATA_INS = @DATAINS,
	LSRTIT_KEY_ORA_INS = @ORAINS
	WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
	AND LSRTIT_TIPO_PROVV = @OLDPROVV
	AND LSRTIT_DATA_PROVV = @OLDDATAPROVV
	AND LSRTIT_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRTIT'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRSER_F101 SET 
	LSRSER_F101_FLAG_VALIDITA = 'N',
	LSRSER_F101_KEY_DATA_INS = @DATAINS,
	LSRSER_F101_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_F101_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_F101_TIPO_PROVV = @OLDPROVV
	AND LSRSER_F101_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_F101_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_F101'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRSER_BOLLO SET 
	LSRSER_BOLLO_FLAG_VALIDITA = 'N',
	LSRSER_BOLLO_KEY_DATA_INS = @DATAINS,
	LSRSER_BOLLO_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_BOLLO_TIPO_PROVV = @OLDPROVV
	AND LSRSER_BOLLO_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_BOLLO_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_BOLLO'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRSER_TRIS SET 
	LSRSER_TRIS_FLAG_VALIDITA = 'N',
	LSRSER_TRIS_KEY_DATA_INS = @DATAINS,
	LSRSER_TRIS_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_TRIS_TIPO_PROVV = @OLDPROVV
	AND LSRSER_TRIS_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_TRIS_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_TRIS'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRSER_CITT SET 
	LSRSER_CITT_FLAG_VALIDITA = 'N',
	LSRSER_CITT_KEY_DATA_INS = @DATAINS,
	LSRSER_CITT_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_CITT_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_CITT_TIPO_PROVV = @OLDPROVV
	AND LSRSER_CITT_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_CITT_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_CITT'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRSER_PAG SET 
	LSRSER_PAG_FLAG_VALIDITA = 'N',
	LSRSER_PAG_KEY_DATA_INS = @DATAINS,
	LSRSER_PAG_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_PAG_TIPO_PROVV = @OLDPROVV
	AND LSRSER_PAG_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_PAG_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_PAG'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRSER_BIG SET 
	LSRSER_BIG_FLAG_VALIDITA = 'N',
	LSRSER_BIG_KEY_DATA_INS = @DATAINS,
	LSRSER_BIG_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_BIG_TIPO_PROVV = @OLDPROVV
	AND LSRSER_BIG_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_BIG_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_BIG'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRSER_TEL SET 
	LSRSER_TEL_FLAG_VALIDITA = 'N',
	LSRSER_TEL_KEY_DATA_INS = @DATAINS,
	LSRSER_TEL_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_TEL_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_TEL_TIPO_PROVV = @OLDPROVV
	AND LSRSER_TEL_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_TEL_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_TEL'
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE LSRSER_ATTI SET 
	LSRSER_ATTI_FLAG_VALIDITA = 'N',
	LSRSER_ATTI_KEY_DATA_INS = @DATAINS,
	LSRSER_ATTI_KEY_ORA_INS = @ORAINS
	WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_ATTI_TIPO_PROVV = @OLDPROVV
	AND LSRSER_ATTI_DATA_PROVV = @OLDDATAPROVV
	AND LSRSER_ATTI_PROG_PROVV = @OLDPROGPROVV

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_ATTI'
		ROLLBACK TRANSACTION
		RETURN
	END


--FINE MODIFICA 26-08-2002 F.GIACOVAZZI

	INSERT INTO LSRSER_LOTTO VALUES
	(@RICEVITORIA,@DATAINS,@ORAINS,@DATADECOR,
	@TIPOPROVV,@DATAPROVV,@NUMPROVV,
	@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ' + CONVERT(CHAR(20),@@ERROR) + ' ERRORE IN INSERIMENTO LSRSER_LOTTO'
		ROLLBACK TRANSACTION
		RETURN
	END



END

SELECT @NUMERR = '0000'
SELECT @MSGERR = @NUMERR
COMMIT TRANSACTION

RETURN
GO
