/****** Object:  StoredProcedure [dbo].[CREA_RAD_DISATTIVAZIONI_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CREA_RAD_DISATTIVAZIONI_LIS] 

	@QUERYSQL 			VARCHAR(2500),
	@OPERAZIONE 		CHAR(1), 
	@CATEGORIA			CHAR(2),
	@SERVIZIO			CHAR(2),
	@ATTIVITA			CHAR(2),
	@CON	 			CHAR(15), 
	@CAS	 			CHAR(15),
	@AUT	 			CHAR(15), 
	@FID	 			CHAR(15), 
	@RAD	 			CHAR(15), 
	@NOMESERVER 		CHAR(20), 
	@FIRMA	 		CHAR(17), 
	@RC		 		CHAR(70)  OUTPUT


AS


DECLARE

@NOMESERVIZIO	VARCHAR(6),
@RICEV		CHAR(6),
@RICERIN		CHAR(6),
@RICEAPPO		CHAR(6),
@RICESER		CHAR(6),
@RICEFID		CHAR(6),
@STATOOGGI		CHAR(1),
@STATODOM		CHAR(1),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@NOMEFILE		VARCHAR(100),
@NOMEJOB		CHAR(6),
@NUMREC		INT,
@PATHID		INT

SELECT @NOMEJOB = 'NO_LOG'

SELECT @NOMESERVIZIO = RTRIM(@CATEGORIA+@SERVIZIO + @ATTIVITA)

SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @CON = RTRIM(@CON)
SELECT @CAS = RTRIM(@CAS)
SELECT @AUT = RTRIM(@AUT)
SELECT @FID = RTRIM(@FID)
SELECT @RAD = RTRIM(@RAD)

SELECT @PATHID = 80
SELECT @NUMREC = 0

SELECT @NOMEFILE ='LIS_'+ @NOMESERVIZIO+'_'+@OPERAZIONE+'_'+@DATAINS+'.txt'

--CANCELLO FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB

SELECT @QUERYSQL = 'DECLARE CUR_CON CURSOR FOR ' + RTRIM(@QUERYSQL) + ' ORDER BY 1'
EXECUTE (@QUERYSQL) 
OPEN CUR_CON 
FETCH NEXT FROM CUR_CON INTO @RICEV 
WHILE @@FETCH_STATUS = 0 

BEGIN

	SELECT @STATODOM = NULL
	SELECT @STATOOGGI = NULL
	SELECT @RICESER = NULL

	--***********SERVIZI TELEFONICI***********
 	IF @CATEGORIA = '01'
	BEGIN
		--VERIFICO LO STATO DEL SERVIZIO
		SELECT @STATODOM = LSRSER_TEL_STATO
		FROM LSRSER_TEL
		WHERE LSRSER_TEL_KEY_ID_RICEV = @RICEV
		AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA      
		AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
		AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
		AND LSRSER_TEL_FLAG_VALIDITA = 'Y'
		AND LSRSER_TEL_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)

	
		IF @STATODOM = '' OR @STATODOM IS NULL
		BEGIN
			SELECT @STATOOGGI = LSRSER_TEL_STATO
			FROM LSRSER_TEL
			WHERE LSRSER_TEL_KEY_ID_RICEV = @RICEV
			AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA      
			AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_TEL_DATA_DECOR =
			(
				SELECT MAX(LSRSER_TEL_DATA_DECOR) FROM LSRSER_TEL 
				WHERE LSRSER_TEL_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_TEL_KEY_ID_RICEV = @RICEV
				AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_TEL_FLAG_VALIDITA = 'Y'
			)
			AND LSRSER_TEL_FLAG_VALIDITA = 'Y'

			IF @STATOOGGI = '1'
			BEGIN
				SELECT @NUMREC = @NUMREC + 1

				EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

				EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
			END
		END
	END


	--***********SERVIZI AL CITTADINO***********
 	IF @CATEGORIA = '02'
	BEGIN
		--VERIFICO LO STATO DEL SERVIZIO
		SELECT @STATODOM = LSRSER_CITT_STATO
		FROM LSRSER_CITT
		WHERE LSRSER_CITT_KEY_ID_RICEV = @RICEV
		AND LSRSER_CITT_KEY_CATEGORIA = @CATEGORIA      
		AND LSRSER_CITT_KEY_SERVIZIO = @SERVIZIO
		AND LSRSER_CITT_KEY_ATTIVITA = @ATTIVITA
		AND LSRSER_CITT_FLAG_VALIDITA = 'Y'
		AND LSRSER_CITT_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)

	
		IF @STATODOM = '' OR @STATODOM IS NULL
		BEGIN
			SELECT @STATOOGGI = LSRSER_CITT_STATO
			FROM LSRSER_CITT
			WHERE LSRSER_CITT_KEY_ID_RICEV = @RICEV
			AND LSRSER_CITT_KEY_CATEGORIA = @CATEGORIA      
			AND LSRSER_CITT_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_CITT_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_CITT_DATA_DECOR =
			(
				SELECT MAX(LSRSER_CITT_DATA_DECOR) FROM LSRSER_CITT
				WHERE LSRSER_CITT_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_CITT_KEY_ID_RICEV = @RICEV
				AND LSRSER_CITT_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_CITT_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_CITT_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_CITT_FLAG_VALIDITA = 'Y'
			)
			AND LSRSER_CITT_FLAG_VALIDITA = 'Y'

			IF @STATOOGGI = '1'
			BEGIN
				SELECT @NUMREC = @NUMREC + 1

				EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

				EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
			END
		END
	END


	--***********PAGAMENTO UTENZE***********
	ELSE IF @CATEGORIA = '03'
	BEGIN

		--VERIFICO LO STATO DEL SERVIZIO
		SELECT @STATODOM = LSRSER_PAG_STATO
		FROM LSRSER_PAG
		WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEV
		AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA      
		AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
		AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
		AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
		AND LSRSER_PAG_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	
		IF @STATODOM = '' OR @STATODOM IS NULL
		BEGIN
			SELECT @STATOOGGI = LSRSER_PAG_STATO
			FROM LSRSER_PAG
			WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEV
			AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA      
			AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_PAG_DATA_DECOR =
			(
				SELECT MAX(LSRSER_PAG_DATA_DECOR) FROM LSRSER_PAG
				WHERE LSRSER_PAG_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_PAG_KEY_ID_RICEV = @RICEV
				AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
			)
			AND LSRSER_PAG_FLAG_VALIDITA = 'Y'

			IF @STATOOGGI = '1'
			BEGIN
				SELECT @NUMREC = @NUMREC + 1
				EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

				EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
			END
		END
	END

	--***********BIGLIETTERIA***********
	ELSE IF @CATEGORIA = '04'
	BEGIN

		--VERIFICO LO STATO DEL SERVIZIO
		SELECT @STATODOM = LSRSER_BIG_STATO
		FROM LSRSER_BIG
		WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEV
		AND LSRSER_BIG_KEY_CATEGORIA = @CATEGORIA      
		AND LSRSER_BIG_KEY_SERVIZIO = @SERVIZIO
		AND LSRSER_BIG_KEY_ATTIVITA = @ATTIVITA
		AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
		AND LSRSER_BIG_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)

	
		IF @STATODOM = '' OR @STATODOM IS NULL
		BEGIN
			SELECT @STATOOGGI = LSRSER_BIG_STATO
			FROM LSRSER_BIG
			WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEV
			AND LSRSER_BIG_KEY_CATEGORIA = @CATEGORIA      
			AND LSRSER_BIG_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_BIG_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_BIG_DATA_DECOR =
			(
				SELECT MAX(LSRSER_BIG_DATA_DECOR) FROM LSRSER_BIG
				WHERE LSRSER_BIG_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_BIG_KEY_ID_RICEV = @RICEV
				AND LSRSER_BIG_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_BIG_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_BIG_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
			)

			AND LSRSER_BIG_FLAG_VALIDITA = 'Y'		

			IF @STATOOGGI = '1'
			BEGIN
				SELECT @NUMREC = @NUMREC + 1

				EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

				EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
			END
		END

	END


	--***********ATTI GIUDIZIARI***********
	ELSE IF @CATEGORIA = '05'
	BEGIN

		--VERIFICO LO STATO DEL SERVIZIO
		SELECT @STATODOM = LSRSER_ATTI_STATO
		FROM LSRSER_ATTI
		WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEV
		AND LSRSER_ATTI_KEY_CATEGORIA = @CATEGORIA      
		AND LSRSER_ATTI_KEY_SERVIZIO = @SERVIZIO
		AND LSRSER_ATTI_KEY_ATTIVITA = @ATTIVITA
		AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'
		AND LSRSER_ATTI_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)

	
		IF @STATODOM = '' OR @STATODOM IS NULL
		BEGIN
			SELECT @STATOOGGI = LSRSER_ATTI_STATO
			FROM LSRSER_ATTI
			WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEV
			AND LSRSER_ATTI_KEY_CATEGORIA = @CATEGORIA      
			AND LSRSER_ATTI_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_ATTI_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_ATTI_DATA_DECOR =
			(
				SELECT MAX(LSRSER_ATTI_DATA_DECOR) FROM LSRSER_ATTI
				WHERE LSRSER_ATTI_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_ATTI_KEY_ID_RICEV = @RICEV
				AND LSRSER_ATTI_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_ATTI_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_ATTI_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'
			)
			AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'		

			IF @STATOOGGI = '1'
			BEGIN
				SELECT @NUMREC = @NUMREC + 1

				EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

				EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
			END
		END

	END


FETCH NEXT FROM CUR_CON INTO @RICEV

END

SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)
--SELECT @RC =  @NOMEFILE

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
