/****** Object:  StoredProcedure [dbo].[CREA_RAD_RIATTIVAZIONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CREA_RAD_RIATTIVAZIONI]  
			@QUERYSQL 			VARCHAR(2500),
			@OPERAZIONE 		CHAR(1), 
			@CODSER 			CHAR(2), 
			@CON	 			CHAR(15), 
			@CAS	 			CHAR(15), 
			@FID	 			CHAR(15), 
			@APS	 			CHAR(15), 
			@RAD	 			CHAR(15), 
			@FLAGLOTTO 			CHAR(1), 
			@NOMESERVER 		CHAR(20), 
			@FIRMA	 		CHAR(17), 
			@RC		 		CHAR(70)  OUTPUT


AS


DECLARE

@RICEV		CHAR(6),
@RICERIN		CHAR(6),
@RICEAPPO		CHAR(7),
@RICESER		CHAR(6),
@RICEFID		CHAR(6),
@RICEAPS		CHAR(6),
@STATOOGGI		CHAR(1),
@STATODOM		CHAR(1),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@DATARINRIN		CHAR(8),
@NOMEFILE		CHAR(100),
@NOMEJOB		CHAR(6),
@STATOLOT		CHAR(1),
@NUMREC		INT,
@PATHID		INT

SELECT @NOMEJOB = 'NO_LOG'

SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @CON = RTRIM(@CON)
SELECT @CAS = RTRIM(@CAS)
SELECT @FID = RTRIM(@FID)
SELECT @APS = RTRIM(@APS)
SELECT @RAD = RTRIM(@RAD)

SELECT @PATHID = 80
SELECT @NUMREC = 0

IF @CODSER = '02'
BEGIN
	SELECT @NOMEFILE ='F101_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END

IF @CODSER = '05'
BEGIN
	SELECT @NOMEFILE ='BOLLO_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END

IF @CODSER = '08'
BEGIN
	SELECT @NOMEFILE ='TRIS_'+@OPERAZIONE+'_'+@DATAINS+'.txt'
END

--CANCELLO IL FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB


SELECT @QUERYSQL = 'DECLARE CUR_CON CURSOR FOR ' + RTRIM(@QUERYSQL) + ' ORDER BY 1' 
EXECUTE (@QUERYSQL) 
OPEN CUR_CON 
FETCH NEXT FROM CUR_CON INTO @RICEV 
WHILE @@FETCH_STATUS = 0 

BEGIN
	SELECT @RICERIN = NULL
	SELECT @DATARINRIN = NULL

	--VERIFICO SE CI SONO RINUNCE AL SERVIZIO E SE E' IMPOSTATA LA
	--DATA DELLA RINUNCIA DELLA RINUNCIA

	SELECT @RICERIN = LSRRIN_KEY_ID_RICEV, 
		@DATARINRIN = LSRRIN_DATA_RINUNCIA_RINUNCIA
	FROM LSRRIN
	WHERE LSRRIN_KEY_ID_RICEV = @RICEV
		AND LSRRIN_CODICE_SERVIZIO = @CODSER
		AND LSRRIN_FLAG_ANAG = '1'

	IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' ' OR (@DATARINRIN <>''  AND @DATARINRIN <>'00000000' AND @DATARINRIN IS NOT NULL)
	BEGIN

		SELECT @STATODOM = NULL
		SELECT @STATOOGGI = NULL
		SELECT @RICESER = NULL

		--VERIFICO LO STATO DEL SERVIZIO
		IF @CODSER = '02'
		BEGIN
			SELECT @STATODOM = LSRSER_F101_STATO
			FROM LSRSER_F101
			WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
			AND LSRSER_F101_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
			AND LSRSER_F101_FLAG_VALIDITA = 'Y'


			IF @STATODOM = '' OR @STATODOM IS NULL
			BEGIN
				SELECT @STATOOGGI = LSRSER_F101_STATO
				FROM LSRSER_F101
				WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
				AND LSRSER_F101_DATA_DECOR =
				(
					SELECT MAX(LSRSER_F101_DATA_DECOR) FROM LSRSER_F101 
					WHERE LSRSER_F101_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
					AND LSRSER_F101_FLAG_VALIDITA = 'Y'
					AND LSRSER_F101_KEY_ID_RICEV = @RICEV
				)
				AND LSRSER_F101_FLAG_VALIDITA = 'Y'
			
				IF @STATOOGGI = '2'
				BEGIN
					SELECT @STATOLOT = NULL
					--CONTROLLO LO STATO DEL LOTTO A DOMANI
					SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					--AND LSRSER_LOTTO_FT_VOS <> '00000000'
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR =
					(
						SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
						--AND LSRSER_LOTTO_FT_VOS <> '00000000'
						AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
					)

					IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
					--IF @STATOLOT = 'A'
--					IF @STATOLOT <> 'S' AND @STATOLOT <> 'M' AND @STATOLOT <> 'R'
					BEGIN
						SELECT @NUMREC = @NUMREC + 1

						EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

						EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
					END
				END
			END
		END
		ELSE IF @CODSER = '05'
		BEGIN
			SELECT @STATODOM = LSRSER_BOLLO_STATO
			FROM LSRSER_BOLLO
			WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
			AND LSRSER_BOLLO_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
			AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'

			IF @STATODOM = '' OR @STATODOM IS NULL
			BEGIN
				SELECT @STATOOGGI = LSRSER_BOLLO_STATO
				FROM LSRSER_BOLLO
				WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
				AND LSRSER_BOLLO_DATA_DECOR =
				(
					SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO
					WHERE LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
					AND LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
					AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
				)
				AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
			
				IF @STATOOGGI = '2'
				BEGIN

					SELECT @STATOLOT = NULL
					--CONTROLLO LO STATO DEL LOTTO A DOMANI
					SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					--AND LSRSER_LOTTO_FT_VOS <> '00000000'
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR =
					(
						SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
						--AND LSRSER_LOTTO_FT_VOS <> '00000000'
						AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
					)

					IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
--					IF @STATOLOT = 'A'
--					IF @STATOLOT <> 'S' AND @STATOLOT <> 'M' AND @STATOLOT <> 'R'
					BEGIN
						SELECT @RICEAPPO = NULL
						SELECT @RICEAPPO = @RICEV + 'N'

						SELECT @NUMREC = @NUMREC + 1

						EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEAPPO, @NOMEJOB
	
						EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
					END
				END
			END
		END
		ELSE IF @CODSER = '08'
		BEGIN
			SELECT @STATODOM = LSRSER_TRIS_STATO
			FROM LSRSER_TRIS
			WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
			AND LSRSER_TRIS_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
			AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'

			IF @STATODOM = '' OR @STATODOM IS NULL
			BEGIN
				SELECT @STATOOGGI = LSRSER_TRIS_STATO
				FROM LSRSER_TRIS
				WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
				AND LSRSER_TRIS_DATA_DECOR =
				(
					SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS
					WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
					AND LSRSER_TRIS_KEY_ID_RICEV = @RICEV
					AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
				)
				AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
			
				IF @STATOOGGI = '2' OR @STATOOGGI = '3'
				BEGIN
					SELECT @STATOLOT = NULL
					--CONTROLLO LO STATO DEL LOTTO A DOMANI
					SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					--AND LSRSER_LOTTO_FT_VOS <> '00000000'
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR =
					(
						SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
						--AND LSRSER_LOTTO_FT_VOS <> '00000000'
						AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
					)

					IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
--					IF @STATOLOT = 'A'
--					IF @STATOLOT <> 'S' AND @STATOLOT <> 'M' AND @STATOLOT <> 'R'
					BEGIN
						SELECT @NUMREC = @NUMREC + 1

						EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

						EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
	
					END
				END
			END
		END
	END -- END CONTROLLO CHE NON ESISTE RINUNCIA O SE ESISTE E' VALORIZZATA LA RINUNCIA DELLA RINUNCIA

FETCH NEXT FROM CUR_CON INTO @RICEV

END

SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)
--SELECT @RC =  @NOMEFILE

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
