/****** Object:  StoredProcedure [dbo].[ANA_DISATTIVA_LTM_TEMP]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_DISATTIVA_LTM_TEMP]  

@CODLTM 		CHAR(6),
@FIRMA		VARCHAR(17),
@NOTE		VARCHAR(255),
@MSGOUTB 		VARCHAR(255) OUTPUT,
@MSGOUTF 		VARCHAR(255) OUTPUT,
@MSGOUTT 		VARCHAR(255) OUTPUT


AS

DECLARE 	

@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@MSGFROM		VARCHAR(255),
@MSGERR		VARCHAR(255)


SELECT @DATAINS = CONVERT(CHAR(8),GETDATE(),112)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

SELECT @MSGFROM = NULL
SELECT @MSGERR = NULL

BEGIN TRANSACTION

EXEC ANA_DISATTIVA_BOLLO_TEMP

@CODLTM,
@DATAINS,
@ORAINS,
@FIRMA,
@NOTE,
@MSGFROM OUTPUT

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' - ' + @MSGFROM
	SELECT @MSGOUTB = @MSGERR
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	SELECT @MSGOUTB = @MSGFROM
END


SELECT @MSGFROM = NULL
SELECT @MSGERR = NULL


EXEC ANA_DISATTIVA_F101_TEMP

@CODLTM,
@DATAINS,
@ORAINS,
@FIRMA,
@NOTE,
@MSGFROM OUTPUT

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' - ' + @MSGFROM
	SELECT @MSGOUTF = @MSGERR
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	SELECT @MSGOUTF = @MSGFROM
END


SELECT @MSGFROM = NULL
SELECT @MSGERR = NULL

EXEC ANA_DISATTIVA_TRIS_TEMP

@CODLTM,
@DATAINS,
@ORAINS,
@FIRMA,
@NOTE,
@MSGFROM OUTPUT

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' - ' + @MSGFROM
	SELECT @MSGOUTT = @MSGERR
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	SELECT @MSGOUTT = @MSGFROM
END



COMMIT TRANSACTION
GO
