/****** Object:  StoredProcedure [dbo].[CREA_RAD_RIATTIVAZIONI_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[CREA_RAD_RIATTIVAZIONI_LIS]  
			@QUERYSQL 			VARCHAR(2500),
			@OPERAZIONE 		CHAR(1), 
			@CATEGORIA			CHAR(2),
			@SERVIZIO			CHAR(2),
			@ATTIVITA			CHAR(2),
			@CON	 			CHAR(15), 
			@CAS	 			CHAR(15), 
			@AUT	 			CHAR(15), 
			@FID	 			CHAR(15), 
			@RAD	 			CHAR(15), 
			@FLAGLOTTO 			CHAR(1),

			@NOMESERVER 		CHAR(20), 
			@FIRMA	 		CHAR(17), 
			@RC		 		CHAR(70)  OUTPUT
 
AS


DECLARE

@NOMESERVIZIO	VARCHAR(6),
@RICEV		CHAR(6),
@DENOM 		CHAR(50),
@RICERIN		CHAR(6),
@RICEAPPO		CHAR(7),
@RICESER		CHAR(6),
@RICEFID		CHAR(6),
@RICEAPS		CHAR(6),
@STATOOGGI		CHAR(1),
@STATODOM		CHAR(1),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@DATARINRIN		CHAR(8),
@PARTITAIVA		CHAR(11),
@NOMEFILE		CHAR(100),
@NOMEJOB		CHAR(6),
@STATOLOT		CHAR(1),
@ABI			CHAR(5),
@CAB			CHAR(5),
@NUMREC		INT,
@PATHID		INT


SELECT @NOMEJOB = 'NO_LOG'

SELECT @NOMESERVIZIO = RTRIM(@CATEGORIA+@SERVIZIO + @ATTIVITA)

SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @CON = RTRIM(@CON)
SELECT @CAS = RTRIM(@CAS)
SELECT @AUT= RTRIM(@AUT)
SELECT @FID = RTRIM(@FID)
SELECT @RAD = RTRIM(@RAD)

SELECT @PATHID = 80
SELECT @NUMREC = 0

SELECT @NOMEFILE ='LIS_'+ @NOMESERVIZIO+'_'+@OPERAZIONE+'_'+@DATAINS+'.txt'

--CANCELLO FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB

IF @CATEGORIA = '01'
BEGIN
	SELECT @QUERYSQL = 'SELECT DISTINCT(RICEV) FROM (' + RTRIM(@QUERYSQL)  + ' ) Q WHERE RICEV  IN 
					(SELECT DISTINCT(LSRSER_TEL_KEY_ID_RICEV) FROM LSRSER_TEL A
					WHERE LSRSER_TEL_KEY_CATEGORIA = ' + '"' + @CATEGORIA  + '"' +
						' AND LSRSER_TEL_KEY_SERVIZIO = ' + '"' +  @SERVIZIO + '"'+
						' AND LSRSER_TEL_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
						' AND LSRSER_TEL_FLAG_VALIDITA = "Y"
						AND LSRSER_TEL_STATO = "2" 
						AND LSRSER_TEL_DATA_DECOR = (
							SELECT MAX(LSRSER_TEL_DATA_DECOR) 
							FROM LSRSER_TEL
							WHERE LSRSER_TEL_DATA_DECOR <=  ' + '"' + @DATAINS  + '"' +
							'AND LSRSER_TEL_KEY_CATEGORIA =  ' + '"' + @CATEGORIA  + '"' +
							'AND LSRSER_TEL_KEY_SERVIZIO =  ' + '"' +  @SERVIZIO + '"'+
							'AND LSRSER_TEL_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
							'AND LSRSER_TEL_FLAG_VALIDITA = "Y"
							AND LSRSER_TEL_KEY_ID_RICEV = A.LSRSER_TEL_KEY_ID_RICEV
						)
					)'

END
IF @CATEGORIA = '02'
BEGIN
	SELECT @QUERYSQL = 'SELECT DISTINCT(RICEV) FROM (' + RTRIM(@QUERYSQL)  + ' ) Q WHERE RICEV  IN 
					(SELECT DISTINCT(LSRSER_CITT_KEY_ID_RICEV) FROM LSRSER_CITT A
					WHERE LSRSER_CITT_KEY_CATEGORIA = ' + '"' + @CATEGORIA  + '"' +
						' AND LSRSER_CITT_KEY_SERVIZIO = ' + '"' +  @SERVIZIO + '"'+
						' AND LSRSER_CITT_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
						' AND LSRSER_CITT_FLAG_VALIDITA = "Y"
						AND LSRSER_CITT_STATO = "2" 
						AND LSRSER_CITT_DATA_DECOR = (
							SELECT MAX(LSRSER_CITT_DATA_DECOR) 
							FROM LSRSER_CITT
							WHERE LSRSER_CITT_DATA_DECOR <=  ' + '"' + @DATAINS  + '"' +
							'AND LSRSER_CITT_KEY_CATEGORIA =  ' + '"' + @CATEGORIA  + '"' +
							'AND LSRSER_CITT_KEY_SERVIZIO =  ' + '"' +  @SERVIZIO + '"'+
							'AND LSRSER_CITT_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
							'AND LSRSER_CITT_FLAG_VALIDITA = "Y"
							AND LSRSER_CITT_KEY_ID_RICEV = A.LSRSER_CITT_KEY_ID_RICEV
						)
					)'

END
IF @CATEGORIA = '03'
BEGIN
	SELECT @QUERYSQL = 'SELECT DISTINCT(RICEV) FROM (' + RTRIM(@QUERYSQL)  + ' ) Q WHERE RICEV IN 
					(SELECT DISTINCT(LSRSER_PAG_KEY_ID_RICEV) FROM LSRSER_PAG A
					WHERE LSRSER_PAG_KEY_CATEGORIA = ' + '"' + @CATEGORIA  + '"' +
						' AND LSRSER_PAG_KEY_SERVIZIO = ' + '"' +  @SERVIZIO + '"'+
						' AND LSRSER_PAG_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
						' AND LSRSER_PAG_FLAG_VALIDITA = "Y"
						AND LSRSER_PAG_STATO = "2" 
						AND LSRSER_PAG_DATA_DECOR = (
							SELECT MAX(LSRSER_PAG_DATA_DECOR) 
							FROM LSRSER_PAG
							WHERE LSRSER_PAG_DATA_DECOR <=  ' + '"' + @DATAINS  + '"' +
							'AND LSRSER_PAG_KEY_CATEGORIA =  ' + '"' + @CATEGORIA  + '"' +
							'AND LSRSER_PAG_KEY_SERVIZIO =  ' + '"' +  @SERVIZIO + '"'+
							'AND LSRSER_PAG_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
							'AND LSRSER_PAG_FLAG_VALIDITA = "Y"
							AND LSRSER_PAG_KEY_ID_RICEV = A.LSRSER_PAG_KEY_ID_RICEV
						)
					)'

END
IF @CATEGORIA = '04'
BEGIN
	SELECT @QUERYSQL = 'SELECT DISTINCT(RICEV) FROM (' + RTRIM(@QUERYSQL)  + ' ) Q WHERE RICEV IN 	
					(SELECT DISTINCT(LSRSER_BIG_KEY_ID_RICEV) FROM LSRSER_BIG A
					WHERE LSRSER_BIG_KEY_CATEGORIA = ' + '"' + @CATEGORIA  + '"' +
						' AND LSRSER_BIG_KEY_SERVIZIO = ' + '"' +  @SERVIZIO + '"'+
						' AND LSRSER_BIG_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
						' AND LSRSER_BIG_FLAG_VALIDITA = "Y"
						AND LSRSER_BIG_STATO = "2" 
						AND LSRSER_BIG_DATA_DECOR = (
							SELECT MAX(LSRSER_BIG_DATA_DECOR) 
							FROM LSRSER_BIG
							WHERE LSRSER_BIG_DATA_DECOR <=  ' + '"' + @DATAINS  + '"' +
							'AND LSRSER_BIG_KEY_CATEGORIA =  ' + '"' + @CATEGORIA  + '"' +
							'AND LSRSER_BIG_KEY_SERVIZIO =  ' + '"' +  @SERVIZIO + '"'+
							'AND LSRSER_BIG_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
							'AND LSRSER_BIG_FLAG_VALIDITA = "Y"
							AND LSRSER_BIG_KEY_ID_RICEV = A.LSRSER_BIG_KEY_ID_RICEV
						)
					)'
END
IF @CATEGORIA = '05'
BEGIN
	SELECT @QUERYSQL = 'SELECT DISTINCT(RICEV) FROM (' + RTRIM(@QUERYSQL)  + ' ) Q WHERE RICEV IN 
					(SELECT DISTINCT(LSRSER_ATTI_KEY_ID_RICEV) FROM LSRSER_ATTI A
					WHERE LSRSER_ATTI_KEY_CATEGORIA = ' + '"' + @CATEGORIA  + '"' +
						' AND LSRSER_ATTI_KEY_SERVIZIO = ' + '"' +  @SERVIZIO + '"'+
						' AND LSRSER_ATTI_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
						' AND LSRSER_ATTI_FLAG_VALIDITA = "Y"
						AND LSRSER_ATTI_STATO = "2" 
						AND LSRSER_ATTI_DATA_DECOR = (
							SELECT MAX(LSRSER_ATTI_DATA_DECOR) 
							FROM LSRSER_ATTI
							WHERE LSRSER_ATTI_DATA_DECOR <=  ' + '"' + @DATAINS  + '"' +
							'AND LSRSER_ATTI_KEY_CATEGORIA =  ' + '"' + @CATEGORIA  + '"' +
							'AND LSRSER_ATTI_KEY_SERVIZIO =  ' + '"' +  @SERVIZIO + '"'+
							'AND LSRSER_ATTI_KEY_ATTIVITA = ' + '"'+ @ATTIVITA + '"'+
							'AND LSRSER_ATTI_FLAG_VALIDITA = "Y"
							AND LSRSER_ATTI_KEY_ID_RICEV = A.LSRSER_ATTI_KEY_ID_RICEV
						)
					)'
END


SELECT @QUERYSQL = 'DECLARE CUR_CON CURSOR FOR ' + RTRIM(@QUERYSQL) + ' ORDER BY 1' 
EXECUTE (@QUERYSQL) 
OPEN CUR_CON 
FETCH NEXT FROM CUR_CON INTO @RICEV 
WHILE @@FETCH_STATUS = 0 

BEGIN
	SELECT @RICERIN = NULL
	SELECT @DATARINRIN = NULL

	SELECT @PARTITAIVA = ''
	SELECT @DENOM = ''
	--******************************************************--
	--MODIFICA DEL 16/07/2002: 
	--LA DENOMINAZIONE E' LA CONCATENAZIONE COGNOME TIT + NOME TIT

	--MODIFICA DEL 30/01/2003: ANNULLATA LA PRECEDENTE MODIFICA	
	-- PRENDO LA DENOMINAZIONE CORRENTE DA LSRRIC
	SELECT @DENOM = LSRRIC_DECOD_RICEV 
	FROM LSRRIC
	WHERE LSRRIC_KEY_ID_RICEV = @RICEV
		AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
			(SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) FROM LSRRIC 
			WHERE LSRRIC_KEY_ID_RICEV = @RICEV
				AND  LSRRIC_DATA_VALIDITA <= @DATAINS
				AND  LSRRIC_FLAG_VALIDITA = 'Y')
		AND LSRRIC_FLAG_VALIDITA = 'Y '
			
	/*SELECT @DENOM = RTRIM(LSRTIT_COGNOME) + ' ' + RTRIM(LSRTIT_NOME)
	FROM LSRTIT
	WHERE LSRTIT_KEY_ID_RICEV = @RICEV
		AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
			(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) FROM LSRTIT 
			WHERE LSRTIT_KEY_ID_RICEV = @RICEV
			AND  LSRTIT_DATA_VALIDITA <= @DATAINS
			AND  LSRTIT_FLAG_VALIDITA = 'Y')
		AND LSRTIT_FLAG_VALIDITA = 'Y'*/			
	--FINE MODIFICA DEL 16/07/2002
	--******************************************************--



	--CONTROLLO L'ESISTENZA DELLA PARTITA IVA
	SELECT @PARTITAIVA = LSRCON_LIS_PARTITA_IVA 
	FROM LSRCON_LIS
	WHERE LSRCON_LIS_KEY_ID_RICEV = @RICEV
	AND LSRCON_LIS_FLAG_ANAG = '1'

	IF @PARTITAIVA <> ''	
	--IF @PARTITAIVA = ''	
	BEGIN
		--VERIFICO SE CI SONO RINUNCE AL SERVIZIO E SE E' IMPOSTATA LA
		--DATA DELLA RINUNCIA DELLA RINUNCIA
		SELECT @RICERIN = LSRRIN_LIS_KEY_ID_RICEV ,
			@DATARINRIN = LSRRIN_LIS_DATA_RINUNCIA_RINUNCIA
		FROM LSRRIN_LIS
		WHERE LSRRIN_LIS_KEY_ID_RICEV = @RICEV
		AND LSRRIN_LIS_KEY_CATEGORIA = @CATEGORIA      
		AND LSRRIN_LIS_KEY_SERVIZIO = @SERVIZIO
		AND LSRRIN_LIS_KEY_ATTIVITA = @ATTIVITA
		AND LSRRIN_LIS_FLAG_ANAG = '1'

		IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' ' OR (@DATARINRIN <>''  AND @DATARINRIN <>'00000000' AND @DATARINRIN IS NOT NULL)
		BEGIN

			SELECT @STATODOM = NULL
			SELECT @STATOOGGI = NULL
			SELECT @RICESER = NULL

			--***********SERVIZI TELEFONICI***********
		 	IF @CATEGORIA = '01'
			BEGIN
				--VERIFICO LO STATO DEL SERVIZIO
				SELECT @STATODOM = LSRSER_TEL_STATO
				FROM LSRSER_TEL
				WHERE LSRSER_TEL_KEY_ID_RICEV = @RICEV
				AND LSRSER_TEL_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_TEL_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_TEL_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_TEL_FLAG_VALIDITA = 'Y'
				AND LSRSER_TEL_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	
				IF @STATODOM = '' OR @STATODOM IS NULL
				BEGIN
					SELECT @STATOLOT = NULL
					--CONTROLLO LO STATO DEL LOTTO A DOMANI
					SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR =
					(
						SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
						AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
					)

					--Modifica del 16/09/02: aggiunto controllo stato lotto
					IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
--					IF @STATOLOT = 'A'
					BEGIN
						--CONTROLLO ESISTENZA DELEGA RID
						SELECT @ABI = ''
						SELECT @CAB = ''
						SELECT @ABI = ABI,
							@CAB = CAB
						FROM LWK04A_ARCHIVIO_ATTUALE
						WHERE COD_LOTTOMATICA = @RICEV
							AND DENOMINAZIONE = @DENOM
							AND ABI <> '99999'
						IF (@ABI <> ''  AND @CAB <> '')
						BEGIN
							SELECT @NUMREC = @NUMREC + 1

							EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

							EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
						END
					END
				END
			END

			--***********SERVIZI AL CITTADINO***********
		 	IF @CATEGORIA = '02'
			BEGIN
				--VERIFICO LO STATO DEL SERVIZIO
				SELECT @STATODOM = LSRSER_CITT_STATO
				FROM LSRSER_CITT
				WHERE LSRSER_CITT_KEY_ID_RICEV = @RICEV
				AND LSRSER_CITT_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_CITT_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_CITT_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_CITT_FLAG_VALIDITA = 'Y'
				AND LSRSER_CITT_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	
				IF @STATODOM = '' OR @STATODOM IS NULL
				BEGIN
					SELECT @STATOLOT = NULL
					--CONTROLLO LO STATO DEL LOTTO A DOMANI
					SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR =
					(
						SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
						AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
					)

					--Modifica del 16/09/02: aggiunto controllo stato lotto
					IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
--					IF @STATOLOT = 'A'
					BEGIN

						--CONTROLLO ESISTENZA DELEGA RID
						SELECT @ABI = ''
						SELECT @CAB = ''
						SELECT @ABI = ABI,
							@CAB = CAB
						FROM LWK04A_ARCHIVIO_ATTUALE
						WHERE COD_LOTTOMATICA = @RICEV
							AND DENOMINAZIONE = @DENOM
							AND ABI <> '99999'
						IF (@ABI <> ''  AND @CAB <> '')
						BEGIN
							SELECT @NUMREC = @NUMREC + 1

							EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB
								
							EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
						END
					END
				END
			END	

			--***********PAGAMENTO UTENZE***********
			ELSE IF @CATEGORIA = '03'
			BEGIN
				--VERIFICO LO STATO DEL SERVIZIO
				SELECT @STATODOM = LSRSER_PAG_STATO
				FROM LSRSER_PAG
				WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEV
				AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
				AND LSRSER_PAG_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)

	
				IF @STATODOM = '' OR @STATODOM IS NULL
				BEGIN
					SELECT @STATOLOT = NULL
					--CONTROLLO LO STATO DEL LOTTO A DOMANI
					SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR =
					(
						SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
						AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
					)
		
					--Modifica del 16/09/02: aggiunto controllo stato lotto
					IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
--					IF @STATOLOT = 'A'
					BEGIN
						--CONTROLLO ESISTENZA DELEGA RID
						SELECT @ABI = ''
						SELECT @CAB = ''
						SELECT @ABI = ABI,
							@CAB = CAB
						FROM LWK04A_ARCHIVIO_ATTUALE
						WHERE COD_LOTTOMATICA = @RICEV
							AND DENOMINAZIONE = @DENOM
							AND ABI <> '99999'
						IF (@ABI <> ''  AND @CAB <> '')
						BEGIN
							SELECT @NUMREC = @NUMREC + 1

							EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

							EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
						END
					END
				END
	
			END

			--***********BIGLIETTERIA***********
			ELSE IF @CATEGORIA = '04'
			BEGIN	
				--VERIFICO LO STATO DEL SERVIZIO
				SELECT @STATODOM = LSRSER_BIG_STATO
				FROM LSRSER_BIG
				WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEV
				AND LSRSER_BIG_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_BIG_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_BIG_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_BIG_FLAG_VALIDITA = 'Y'
				AND LSRSER_BIG_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	
				IF @STATODOM = '' OR @STATODOM IS NULL
				BEGIN

					SELECT @STATOLOT = NULL
					--CONTROLLO LO STATO DEL LOTTO A DOMANI
					SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR =
					(
						SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
						AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
					)

					--Modifica del 16/09/02: aggiunto controllo stato lotto
					IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
--					IF @STATOLOT = 'A'
					BEGIN
						--CONTROLLO ESISTENZA DELEGA RID
						SELECT @ABI = ''
						SELECT @CAB = ''
						SELECT @ABI = ABI,
							@CAB = CAB
						FROM LWK04A_ARCHIVIO_ATTUALE
						WHERE COD_LOTTOMATICA = @RICEV
							AND DENOMINAZIONE = @DENOM
							AND ABI <> '99999'
						IF (@ABI <> ''  AND @CAB <> '')
						BEGIN
							SELECT @NUMREC = @NUMREC + 1

							EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB	

							EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
						END
					END
				END

			END

			--***********ATTI GIUDIZIARI***********
			ELSE IF @CATEGORIA = '05'
			BEGIN	
				--VERIFICO LO STATO DEL SERVIZIO
				SELECT @STATODOM = LSRSER_ATTI_STATO
				FROM LSRSER_ATTI
				WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEV
				AND LSRSER_ATTI_KEY_CATEGORIA = @CATEGORIA      
				AND LSRSER_ATTI_KEY_SERVIZIO = @SERVIZIO
				AND LSRSER_ATTI_KEY_ATTIVITA = @ATTIVITA
				AND LSRSER_ATTI_FLAG_VALIDITA = 'Y'
				AND LSRSER_ATTI_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	
				IF @STATODOM = '' OR @STATODOM IS NULL
				BEGIN
					SELECT @STATOLOT = NULL
					--CONTROLLO LO STATO DEL LOTTO A DOMANI
					SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR =
					(
						SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
						AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
					)

					--Modifica del 16/09/02: aggiunto controllo stato lotto
					IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
--					IF @STATOLOT = 'A'
					BEGIN
						--CONTROLLO ESISTENZA DELEGA RID
						SELECT @ABI = ''
						SELECT @CAB = ''
						SELECT @ABI = ABI,
							@CAB = CAB
						FROM LWK04A_ARCHIVIO_ATTUALE
						WHERE COD_LOTTOMATICA = @RICEV
							AND DENOMINAZIONE = @DENOM
							AND ABI <> '99999'
						IF (@ABI <> ''  AND @CAB <> '')
						BEGIN
							SELECT @NUMREC = @NUMREC + 1

							EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB
	
							EXECUTE SCRIVI_LSRLET_LIS @RICEV, @CATEGORIA, @SERVIZIO , @ATTIVITA, @CON, @CAS, @AUT, @FID, @RAD,@DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
						END
					END
				END

			END


		END -- END CONTROLLO CHE NON ESISTE RINUNCIA O SE ESISTE E' VALORIZZATA LA RINUNCIA DELLA RINUNCIA
	END -- END CONTROLLO ESISTENZA PARTITA IVA
	FETCH NEXT FROM CUR_CON INTO @RICEV

END

SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)
--SELECT @RC =  @NOMEFILE

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
