/****** Object:  StoredProcedure [dbo].[AGGIORNA_FT_VOS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[AGGIORNA_FT_VOS] 

 AS

DECLARE  	

@OGGI			CHAR(8),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@STRINGA		VARCHAR(100),
@FILELOG		VARCHAR(80),
@NOMEJOB		VARCHAR(25)


SELECT @NOMEJOB = 'AAEG012005UC'

SELECT @OGGI = CONVERT(CHAR, GETDATE(), 112)

BEGIN TRANSACTION

UPDATE LSRRIC
SET LSRRIC_FT_VOS = @OGGI
WHERE 
LSRRIC_FLAG_VALIDITA = 'Y' AND
LSRRIC_FT_VOS = '00000000' AND
LSRRIC_DATA_VALIDITA <= CONVERT(CHAR, GETDATE(), 112) AND
LSRRIC_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRRIC'
	EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
	RAISERROR (@STRINGA, 16, 1)
	RETURN
END


/*
TRATTAMENTO LSRTIT
*/

UPDATE LSRTIT
SET LSRTIT_FT_VOS = @OGGI
WHERE 
LSRTIT_FLAG_VALIDITA = 'Y' AND
LSRTIT_FT_VOS = '00000000' AND
LSRTIT_DATA_VALIDITA <= CONVERT(CHAR, GETDATE(), 112) AND
LSRTIT_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRTIT'
	EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
	RAISERROR (@STRINGA, 16, 1)
	RETURN
END


/*
TRATTAMENTO LSRPRO
*/

UPDATE LSRPRO
SET LSRPRO_FT_VOS = @OGGI
WHERE
LSRPRO_FLAG_VALIDITA = 'Y' AND
LSRPRO_FT_VOS = '00000000' AND
LSRPRO_DECOR_DAL <= CONVERT(CHAR, GETDATE(), 112) AND
LSRPRO_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRPRO'
	EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
	RAISERROR (@STRINGA, 16, 1)
	RETURN
END


/*
TRATTAMENTO LSRSER_LOTTO
*/

	UPDATE LSRSER_LOTTO
	SET LSRSER_LOTTO_FT_VOS = @OGGI
	WHERE
	LSRSER_LOTTO_FLAG_VALIDITA = 'Y' AND
	LSRSER_LOTTO_FT_VOS = '00000000' AND
	LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
	LSRSER_LOTTO_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRSER_LOTTO'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
		RAISERROR (@STRINGA, 16, 1)
		RETURN
	END


/*
TRATTAMENTO LSRSER_F101
*/

	UPDATE LSRSER_F101
	SET LSRSER_F101_FT_VOS = @OGGI
	WHERE
	LSRSER_F101_FLAG_VALIDITA = 'Y' AND
	LSRSER_F101_FT_VOS = '00000000' AND
	LSRSER_F101_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
	LSRSER_F101_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRSER_F101'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
		RAISERROR (@STRINGA, 16, 1)
		RETURN
	END


/*
TRATTAMENTO LSRSER_BOLLO
*/

	UPDATE LSRSER_BOLLO
	SET LSRSER_BOLLO_FT_VOS = @OGGI
	WHERE
	LSRSER_BOLLO_FLAG_VALIDITA = 'Y' AND
	LSRSER_BOLLO_FT_VOS = '00000000' AND
	LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
	LSRSER_BOLLO_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRSER_BOLLO'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
		RAISERROR (@STRINGA, 16, 1)
		RETURN
	END

/*
TRATTAMENTO LSRSER_TRIS
*/

	UPDATE LSRSER_TRIS
	SET LSRSER_TRIS_FT_VOS = @OGGI
	WHERE
	LSRSER_TRIS_FLAG_VALIDITA = 'Y' AND
	LSRSER_TRIS_FT_VOS = '00000000' AND
	LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
	LSRSER_TRIS_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRSER_TRIS'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
		RAISERROR (@STRINGA, 16, 1)
		RETURN
	END

/*
MODIFICA DEL 23/07/2003: GESTIONE CONI (CDS)
TRATTAMENTO LSRSER_CONI
*/

	UPDATE LSRSER_CONI
	SET LSRSER_CONI_FT_VOS = @OGGI
	WHERE
	LSRSER_CONI_FLAG_VALIDITA = 'Y' AND
	LSRSER_CONI_FT_VOS = '00000000' AND
	LSRSER_CONI_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
	LSRSER_CONI_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRSER_CONI'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
		RAISERROR (@STRINGA, 16, 1)
		RETURN
	END

/*
MODIFICA DEL 22/02/2005: GESTIONE ST (CDS)
TRATTAMENTO LSRSER_ST
*/

	UPDATE LSRSER_ST
	SET LSRSER_ST_FT_VOS = @OGGI
	WHERE
	LSRSER_ST_FLAG_VALIDITA = 'Y' AND
	LSRSER_ST_FT_VOS = '00000000' AND
	LSRSER_ST_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
	LSRSER_ST_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRSER_ST'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
		RAISERROR (@STRINGA, 16, 1)
		RETURN
	END


/*
MODIFICA DEL 27/04/2004: GESTIONE GEV (CDS)
TRATTAMENTO LSRSER_GEV
*/

	UPDATE LSRSER_GEV
	SET LSRSER_GEV_FT_VOS = @OGGI
	WHERE
	LSRSER_GEV_FLAG_VALIDITA = 'Y' AND
	LSRSER_GEV_FT_VOS = '00000000' AND
	LSRSER_GEV_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
	LSRSER_GEV_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRSER_GEV'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
		RAISERROR (@STRINGA, 16, 1)
		RETURN
	END

/*
MODIFICA DEL 04/06/2007: GESTIONE GP (CDS)
TRATTAMENTO LSRSER_GP
*/

	UPDATE LSRSER_GP
	SET LSRSER_GP_FT_VOS = @OGGI
	WHERE
	LSRSER_GP_FLAG_VALIDITA = 'Y' AND
	LSRSER_GP_FT_VOS = '00000000' AND
	LSRSER_GP_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) AND
	LSRSER_GP_KEY_DATA_INS  < CONVERT(CHAR, GETDATE(), 112)

	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @STRINGA='ERRORE IN AGGIORNAMENTO LSRSER_GP'
		EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
		RAISERROR (@STRINGA, 16, 1)
		RETURN
	END

COMMIT TRANSACTION

SELECT @STRINGA='SP AGGIORNA_FT_VOS TERMINATA CORRETTAMENTE'

EXEC  MSDB..UT_AA004 9999, @NOMEJOB, @STRINGA, 0
GO
