/****** Object:  StoredProcedure [dbo].[Annulla_Provvedimento_Anagrafica_CONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE     PROCEDURE [dbo].[Annulla_Provvedimento_Anagrafica_CONI] 

	@RICEVITORIA		CHAR(6),
	@DATAOLD		CHAR(8),
	@ORAOLD		CHAR(8),
	@TIPOPROVV		CHAR(1),
	@DATAPROVV		CHAR(8),
	@PROGPROVV		CHAR(12),
	@NOTE		VARCHAR(150),
	@FIRMA		VARCHAR(17),
	@MSGERR		VARCHAR(100) OUTPUT  

AS

DECLARE	@DATAINS 		CHAR(8),
                 	@ORAINS   		CHAR(8),
		@DATAINSTIT   	CHAR(8),
		@ORAINSTIT   		CHAR(8),
		@NEWDATAINSTIT   	CHAR(8),
		@NEWORAINSTIT   	CHAR(8)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR, GETDATE(), 121),1,4)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),6,2)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),9,2)

SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)

BEGIN TRANSACTION


-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
DELETE FROM LSRLET_CONI
WHERE LSRLET_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRLET_CONI_NOME_TAB_DOCUMENTO = 'LSRPRO'
AND LSRLET_CONI_FK_TAB_DOCUMENTO = @DATAOLD + @ORAOLD


-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
DELETE FROM LSRLET_ST
WHERE LSRLET_ST_KEY_ID_RICEV = @RICEVITORIA
AND LSRLET_ST_NOME_TAB_DOCUMENTO = 'LSRPRO'
AND LSRLET_ST_FK_TAB_DOCUMENTO = @DATAOLD + @ORAOLD

-- AGGIORNO LA TABELLA DEI PROVVEDIMENTI
UPDATE LSRPRO_CONI SET 
LSRPRO_CONI_FLAG_VALIDITA = 'A',
LSRPRO_CONI_KEY_DATA_INS = @DATAINS,
LSRPRO_CONI_KEY_ORA_INS = @ORAINS,
lsrpro_coni_causale = 'Annullato da ' + @FIRMA
WHERE LSRPRO_CONI_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_CONI_KEY_DATA_INS = @DATAOLD
AND LSRPRO_CONI_KEY_ORA_INS = @ORAOLD

-- AGGIORNO LA TABELLA DEI TITOLARI
UPDATE LSRTIT_CONI SET 
LSRTIT_CONI_FLAG_VALIDITA = 'A',
LSRTIT_CONI_KEY_DATA_INS = @DATAINS,
LSRTIT_CONI_KEY_ORA_INS = @ORAINS
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
AND lsrtit_coni_data_provv = @DATAPROVV
AND lsrtit_coni_prog_provv = @PROGPROVV
AND lsrtit_coni_tipo_provv = @TIPOPROVV

-- AGGIORNO LA TABELLA LSRSER_CONI
UPDATE LSRSER_CONI SET
LSRSER_CONI_FLAG_VALIDITA = 'A', 
LSRSER_CONI_KEY_DATA_INS = @DATAINS,
LSRSER_CONI_KEY_ORA_INS = @ORAINS,
LSRSER_CONI_NOTE = @NOTE,
LSRSER_CONI_FIRMA = @FIRMA
WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIA
AND lsrSER_coni_data_provv = @DATAPROVV
AND lsrSER_coni_prog_provv = @PROGPROVV
AND lsrSER_coni_tipo_provv = @TIPOPROVV


-- AGGIORNO LA TABELLA LSRSER_GEV
UPDATE LSRSER_GEV SET
LSRSER_GEV_FLAG_VALIDITA = 'A', 
LSRSER_GEV_KEY_DATA_INS = @DATAINS,
LSRSER_GEV_KEY_ORA_INS = @ORAINS,
LSRSER_GEV_NOTE = @NOTE,
LSRSER_GEV_FIRMA = @FIRMA
WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
AND lsrSER_GEV_data_provv = @DATAPROVV
AND lsrSER_GEV_prog_provv = @PROGPROVV
AND lsrSER_GEV_tipo_provv = @TIPOPROVV

-- AGGIORNO LA TABELLA LSRSER_ST
UPDATE LSRSER_ST SET
LSRSER_ST_FLAG_VALIDITA = 'A', 
LSRSER_ST_KEY_DATA_INS = @DATAINS,
LSRSER_ST_KEY_ORA_INS = @ORAINS,
LSRSER_ST_NOTE = @NOTE,
LSRSER_ST_FIRMA = @FIRMA
WHERE LSRSER_ST_KEY_ID_RICEV = @RICEVITORIA
AND lsrSER_ST_data_provv = @DATAPROVV
AND lsrSER_ST_prog_provv = @PROGPROVV
AND lsrSER_ST_tipo_provv = @TIPOPROVV

-- AGGIORNO LA TABELLA LSRSER_TRIS
UPDATE LSRSER_TRIS SET
LSRSER_TRIS_FLAG_VALIDITA = 'A', 
LSRSER_TRIS_KEY_DATA_INS = @DATAINS,
LSRSER_TRIS_KEY_ORA_INS = @ORAINS,
LSRSER_TRIS_NOTE = @NOTE,
LSRSER_TRIS_FIRMA = @FIRMA
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
AND lsrSER_TRIS_data_provv = @DATAPROVV
AND lsrSER_TRIS_prog_provv = @PROGPROVV
AND lsrSER_TRIS_tipo_provv = @TIPOPROVV

-- SE IL PROVVEDIMENTO è DI TIPO F DEVO AGGIORNARE I FLAG ANAG DELLA CONTRATTUALISTICA
IF (@TIPOPROVV='F') 
BEGIN
	UPDATE LSRTIT_CONI
	SET LSRTIT_CONI_FLAG_ANAG = LSRTIT_CONI_FLAG_ANAG - 1
	WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRTIT_CONI_FLAG_ANAG <> '0'
	
	UPDATE LSRCON_CONI
	SET LSRCON_CONI_FLAG_ANAG = LSRCON_CONI_FLAG_ANAG - 1
	WHERE LSRCON_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRCON_CONI_FLAG_ANAG <> '0'
	
	UPDATE LSRFID_CONI
	SET LSRFID_CONI_FLAG_ANAG = LSRFID_CONI_FLAG_ANAG - 1
	WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRFID_CONI_FLAG_ANAG <> '0'
	
	UPDATE LSRNUO_CONI
	SET LSRNUO_CONI_FLAG_ANAG = LSRNUO_CONI_FLAG_ANAG - 1
	WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRNUO_CONI_FLAG_ANAG <> '0'
	
	UPDATE LSRQST_CONI
	SET LSRQST_CONI_FLAG_ANAG = LSRQST_CONI_FLAG_ANAG - 1
	WHERE LSRQST_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRQST_CONI_FLAG_ANAG <> '0'
	
	UPDATE LSRRAD_CONI
	SET LSRRAD_CONI_FLAG_ANAG = LSRRAD_CONI_FLAG_ANAG - 1
	WHERE LSRRAD_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRAD_CONI_FLAG_ANAG <> '0'
	
	UPDATE LSRRIN_CONI
	SET LSRRIN_CONI_FLAG_ANAG = LSRRIN_CONI_FLAG_ANAG - 1
	WHERE LSRRIN_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRIN_CONI_FLAG_ANAG <> '0'

	UPDATE LSRTLP_ST
	SET LSRTLP_ST_FLAG_ANAG = LSRTLP_ST_FLAG_ANAG - 1
	WHERE LSRTLP_ST_KEY_ID_RICEV = @RICEVITORIA
		AND LSRTLP_ST_FLAG_ANAG <> '0'

	UPDATE LSRRAD_ST
	SET LSRRAD_ST_FLAG_ANAG = LSRRAD_ST_FLAG_ANAG - 1
	WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRAD_ST_FLAG_ANAG <> '0'

----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI SPORTIVI -----------------------------------
----------------------------------------------------------------------------------------------------------------------
	UPDATE lsrcon_GS
	SET lsrcon_GS_FLAG_ANAG = lsrcon_GS_FLAG_ANAG - 1
	WHERE lsrcon_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrcon_GS_FLAG_ANAG <> '0'
	UPDATE lsrnuo_GS
	SET lsrnuo_GS_FLAG_ANAG = lsrnuo_GS_FLAG_ANAG - 1
	WHERE lsrnuo_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrnuo_GS_FLAG_ANAG <> '0'
	UPDATE lsrrad_GS
	SET lsrrad_GS_FLAG_ANAG = lsrrad_GS_FLAG_ANAG - 1
	WHERE lsrrad_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrrad_GS_FLAG_ANAG <> '0'
	UPDATE lsrtlp_GS
	SET lsrtlp_GS_FLAG_ANAG = lsrtlp_GS_FLAG_ANAG - 1
	WHERE lsrtlp_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrtlp_GS_FLAG_ANAG <> '0'

----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI PUBBLICI -----------------------------------
----------------------------------------------------------------------------------------------------------------------

	UPDATE lsrcon_GP
	SET lsrcon_GP_FLAG_ANAG = lsrcon_GP_FLAG_ANAG - 1
	WHERE lsrcon_GP_KEY_ID_RICEV = @RICEVITORIA
		AND lsrcon_GP_FLAG_ANAG <> '0'
	
	
	UPDATE LSRFID_GP
	SET LSRFID_GP_FLAG_ANAG = LSRFID_GP_FLAG_ANAG - 1
	WHERE LSRFID_GP_KEY_ID_RICEV = @RICEVITORIA
		AND LSRFID_GP_FLAG_ANAG <> '0'



	IF ISNUMERIC(LTRIM(RTRIM(@RICEVITORIA) )) = 1
	BEGIN
		UPDATE LSRCON_GEV 
		SET LSRCON_GEV_FLAG_ANAG = LSRCON_GEV_FLAG_ANAG - 1
		WHERE LSRCON_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRCON_GEV_FLAG_ANAG <> '0'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_GEV'
			RETURN
		END
	
		-- LSRQST_GEV
		UPDATE LSRQST_GEV 
		SET LSRQST_GEV_FLAG_ANAG = LSRQST_GEV_FLAG_ANAG - 1
		WHERE LSRQST_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRQST_GEV_FLAG_ANAG <> '0'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRQST_GEV'
			RETURN
		END
	
		-- LSRFID_GEV
		UPDATE LSRFID_GEV  
		SET LSRFID_GEV_FLAG_ANAG = LSRFID_GEV_FLAG_ANAG - 1
		WHERE LSRFID_GEV_COD_LOTTO = @RICEVITORIA
		AND  LSRFID_GEV_FLAG_ANAG <> '0'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_GEV'
			RETURN
		END
	
		-- LSRRAD_GEV
		UPDATE LSRRAD_GEV 
		SET LSRRAD_FLAG_ANAG = LSRRAD_FLAG_ANAG - 1
		WHERE LSRRAD_COD_LOTTO = @RICEVITORIA
		AND LSRRAD_FLAG_ANAG <> '0'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
			RETURN
		END

		-- LSRORD_GEV
		UPDATE LSRORD_GEV 
		SET LSRORD_GEV_FLAG_ANAG = LSRORD_GEV_FLAG_ANAG - 1
		WHERE LSRORD_GEV_COD_LOTTO = @RICEVITORIA
		AND LSRORD_GEV_FLAG_ANAG <> '0'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
			RETURN
		END
	
		-- LSRCON_ITVM
		UPDATE LSRCON_ITVM_GEV 
		SET LSRCON_ITVM_FLAG_ANAG = LSRCON_ITVM_FLAG_ANAG - 1
		WHERE LSRCON_ITVM_COD_LOTTO = @RICEVITORIA
		AND LSRCON_ITVM_FLAG_ANAG <> '0'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_ITVM'
			RETURN
		END

	END


END
IF (@TIPOPROVV = 'I') 
BEGIN
	--PRENDO LA CHIAVE ESTERNA DEL TITOLARE ANNULLATO  
	SELECT @DATAINSTIT = LSRTIT_CONI_KEY_DATA_INS,
		@ORAINSTIT = LSRTIT_CONI_KEY_ORA_INS
	FROM LSRTIT_CONI 
	WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRTIT_CONI_DATA_PROVV =  @DATAPROVV
	AND LSRTIT_CONI_PROG_PROVV =  @PROGPROVV
	AND LSRTIT_CONI_TIPO_PROVV =  @TIPOPROVV
	
	UPDATE LSRCON_CONI
	SET LSRCON_CONI_FLAG_ANAG = '0',
		LSRCON_CONI_FK_DATA_INS_TIT = NULL,
		LSRCON_CONI_FK_ORA_INS_TIT = NULL
	WHERE LSRCON_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRCON_CONI_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRCON_CONI_FK_ORA_INS_TIT = @ORAINSTIT

	UPDATE LSRFID_CONI
	SET LSRFID_CONI_FLAG_ANAG  = '0',
		LSRFID_CONI_FK_DATA_INS_TIT = NULL,
		LSRFID_CONI_FK_ORA_INS_TIT = NULL
	WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRFID_CONI_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRFID_CONI_FK_ORA_INS_TIT = @ORAINSTIT
	
	UPDATE LSRNUO_CONI
	SET LSRNUO_CONI_FLAG_ANAG = '0',
		LSRNUO_CONI_FK_DATA_INS_TIT = NULL,
		LSRNUO_CONI_FK_ORA_INS_TIT = NULL
	WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRNUO_CONI_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRNUO_CONI_FK_ORA_INS_TIT = @ORAINSTIT
	
	UPDATE LSRQST_CONI
	SET LSRQST_CONI_FLAG_ANAG = '0',
		LSRQST_CONI_FK_DATA_INS_TIT = NULL,
		LSRQST_CONI_FK_ORA_INS_TIT = NULL
	WHERE LSRQST_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRQST_CONI_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRQST_CONI_FK_ORA_INS_TIT = @ORAINSTIT
	
	UPDATE LSRRAD_CONI
	SET LSRRAD_CONI_FLAG_ANAG = '0',
		LSRRAD_CONI_FK_DATA_INS_TIT = NULL,
		LSRRAD_CONI_FK_ORA_INS_TIT = NULL
	WHERE LSRRAD_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRAD_CONI_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRRAD_CONI_FK_ORA_INS_TIT = @ORAINSTIT
	
	UPDATE LSRRIN_CONI
	SET LSRRIN_CONI_FLAG_ANAG = '0',
		LSRRIN_CONI_FK_DATA_INS_TIT = NULL,
		LSRRIN_CONI_FK_ORA_INS_TIT = NULL
	WHERE LSRRIN_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRIN_CONI_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRRIN_CONI_FK_ORA_INS_TIT = @ORAINSTIT

	UPDATE LSRTLP_ST
	SET LSRTLP_ST_FLAG_ANAG = '0',
		LSRTLP_ST_FK_DATA_INS_TIT = NULL,
		LSRTLP_ST_FK_ORA_INS_TIT = NULL
	WHERE LSRTLP_ST_KEY_ID_RICEV = @RICEVITORIA
		AND LSRTLP_ST_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRTLP_ST_FK_ORA_INS_TIT = @ORAINSTIT

	UPDATE LSRRAD_ST
	SET LSRRAD_ST_FLAG_ANAG = '0',
		LSRRAD_ST_FK_DATA_INS_TIT = NULL,
		LSRRAD_ST_FK_ORA_INS_TIT = NULL
	WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRAD_ST_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRRAD_ST_FK_ORA_INS_TIT = @ORAINSTIT

----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI SPORTIVI -----------------------------------
----------------------------------------------------------------------------------------------------------------------
	UPDATE lsrcon_GS
	SET lsrcon_GS_FLAG_ANAG = '0',
		lsrcon_GS_fk_data_ins_tit = NULL,
		lsrcon_GS_FK_ORA_INS_TIT = NULL
	WHERE lsrcon_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrcon_GS_FK_DATA_INS_TIT = @DATAINSTIT
		AND lsrcon_GS_FK_ORA_INS_TIT = @ORAINSTIT


	UPDATE lsrnuo_GS
	SET lsrnuo_GS_FLAG_ANAG ='0',
		lsrnuo_GS_FK_DATA_INS_TIT = NULL,
		lsrnuo_GS_FK_ORA_INS_TIT = NULL
	WHERE lsrnuo_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrnuo_GS_FK_DATA_INS_TIT = @DATAINSTIT
		AND lsrnuo_GS_FK_ORA_INS_TIT = @ORAINSTIT

	UPDATE lsrrad_GS
	SET lsrrad_GS_FLAG_ANAG ='0',
		lsrrad_GS_FK_DATA_INS_TIT = NULL,
		lsrrad_GS_FK_ORA_INS_TIT = NULL
	WHERE lsrrad_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrrad_GS_FK_DATA_INS_TIT = @DATAINSTIT
		AND lsrrad_GS_FK_ORA_INS_TIT = @ORAINSTIT

	UPDATE lsrtlp_GS
	SET lsrtlp_GS_FLAG_ANAG = '0',
		lsrtlp_GS_FK_DATA_INS_TIT = NULL,
		lsrtlp_GS_FK_ORA_INS_TIT = NULL
	WHERE lsrtlp_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrtlp_GS_FK_DATA_INS_TIT = @DATAINSTIT
		AND lsrtlp_GS_FK_ORA_INS_TIT = @ORAINSTIT


----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI PUBBLICI -----------------------------------
----------------------------------------------------------------------------------------------------------------------

	UPDATE lsrcon_GP
	SET lsrcon_GP_FLAG_ANAG = '0',
		lsrcon_GP_FK_DATA_INS_TIT = NULL,
		lsrcon_GP_FK_ORA_INS_TIT = NULL
	WHERE lsrcon_GP_KEY_ID_RICEV = @RICEVITORIA
		AND lsrcon_GP_FK_DATA_INS_TIT = @DATAINSTIT
		AND lsrcon_GP_FK_ORA_INS_TIT = @ORAINSTIT
	
	
	UPDATE LSRFID_GP
	SET LSRFID_GP_FLAG_ANAG =  '0',
		LSRFID_GP_FK_DATA_INS_TIT = NULL,
		LSRFID_GP_FK_ORA_INS_TIT = NULL
	WHERE LSRFID_GP_KEY_ID_RICEV = @RICEVITORIA
		AND LSRFID_GP_FK_DATA_INS_TIT = @DATAINSTIT
		AND LSRFID_GP_FK_ORA_INS_TIT = @ORAINSTIT




	IF ISNUMERIC(LTRIM(RTRIM(@RICEVITORIA) )) = 1
	BEGIN
		UPDATE LSRCON_GEV 
		SET LSRCON_GEV_FLAG_ANAG = '0',
			LSRCON_GEV_FK_DATA_INS_TIT_GEV = NULL,
			LSRCON_GEV_FK_ORA_INS_TIT_GEV = NULL
		WHERE LSRCON_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRCON_GEV_FK_DATA_INS_TIT_GEV = @DATAINSTIT
			AND LSRCON_GEV_FK_ORA_INS_TIT_GEV = @ORAINSTIT
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_GEV'
			RETURN
		END
	
		-- LSRQST_GEV
		UPDATE LSRQST_GEV 
		SET LSRQST_GEV_FLAG_ANAG = '0',
			LSRQST_GEV_FK_DATA_INS_TIT_GEV = NULL,
			LSRQST_GEV_FK_ORA_INS_TIT_GEV = NULL
		WHERE LSRQST_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRQST_GEV_FK_DATA_INS_TIT_GEV = @DATAINSTIT
			AND LSRQST_GEV_FK_ORA_INS_TIT_GEV = @ORAINSTIT
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRQST_GEV'
			RETURN
		END
	
		-- LSRFID_GEV
		UPDATE LSRFID_GEV 
		SET LSRFID_GEV_FLAG_ANAG = '0',
			LSRFID_GEV_FK_DATA_INS_TIT_GEV = NULL,
			LSRFID_GEV_FK_ORA_INS_TIT_GEV = NULL
		WHERE LSRFID_GEV_COD_LOTTO = @RICEVITORIA
			AND  LSRFID_GEV_FK_DATA_INS_TIT_GEV = @DATAINSTIT
			AND LSRFID_GEV_FK_ORA_INS_TIT_GEV = @ORAINSTIT
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_GEV'
			RETURN
		END
	
		-- LSRRAD_GEV
		UPDATE LSRRAD_GEV 
		SET  LSRRAD_FLAG_ANAG = '1',
			LSRRAD_FK_DATA_INS_TIT_GEV = NULL,
			LSRRAD_FK_ORA_INS_TIT_GEV = NULL
		WHERE LSRRAD_COD_LOTTO = @RICEVITORIA
			AND LSRRAD_FK_DATA_INS_TIT_GEV = @DATAINSTIT
			AND LSRRAD_FK_ORA_INS_TIT_GEV = @ORAINSTIT
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
			RETURN
		END

		-- LSRORD_GEV
		UPDATE LSRORD_GEV 
		SET  LSRORD_GEV_FLAG_ANAG = '1',
			LSRORD_GEV_FK_DATA_INS_TIT_GEV = NULL,
			LSRORD_GEV_FK_ORA_INS_TIT_GEV = NULL
		WHERE LSRORD_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRORD_GEV_FK_DATA_INS_TIT_GEV = @DATAINSTIT
			AND LSRORD_GEV_FK_ORA_INS_TIT_GEV = @ORAINSTIT
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRORD_GEV'
			RETURN
		END

		-- LSRCON_ITVM
		UPDATE LSRCON_ITVM 
		SET  LSRCON_ITVM_FLAG_ANAG = '1',
			LSRCON_ITVM_FK_DATA_INS_TIT_GEV = NULL,
			LSRCON_ITVM_FK_ORA_INS_TIT_GEV = NULL
		WHERE LSRCON_ITVM_COD_LOTTO = @RICEVITORIA
			AND LSRCON_ITVM_FK_DATA_INS_TIT_GEV = @DATAINSTIT
			AND LSRCON_ITVM_FK_ORA_INS_TIT_GEV = @ORAINSTIT
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_ITVM'
			RETURN
		END

	END


END

IF (@TIPOPROVV = 'E')
BEGIN

	--PRENDO LA CHIAVE ESTERNA DELL'ULTIMO TITOLARE VALIDO PRIMA DI QUELLO ANNULLATO
	SELECT @NEWDATAINSTIT = LSRTIT_CONI_KEY_DATA_INS,
		@NEWORAINSTIT = LSRTIT_CONI_KEY_ORA_INS
	FROM LSRTIT_CONI 
	WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND (LSRTIT_CONI_DATA_VALIDITA + LSRTIT_CONI_ORA_VALIDITA) = 
		(SELECT MAX(LSRTIT_CONI_DATA_VALIDITA + LSRTIT_CONI_ORA_VALIDITA) 
		FROM LSRTIT_CONI 
		WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND  LSRTIT_CONI_DATA_VALIDITA <= @DATAINS
		AND LSRTIT_CONI_FLAG_VALIDITA = 'Y')
	AND LSRTIT_CONI_FLAG_VALIDITA = 'Y'

	UPDATE LSRCON_CONI
	SET LSRCON_CONI_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRCON_CONI_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRCON_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRCON_CONI_FLAG_ANAG = '1'

	UPDATE LSRFID_CONI
	SET LSRFID_CONI_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRFID_CONI_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRFID_CONI_FLAG_ANAG = '1'
	
	UPDATE LSRNUO_CONI
	SET LSRNUO_CONI_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRNUO_CONI_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRNUO_CONI_FLAG_ANAG = '1'
	
	UPDATE LSRQST_CONI
	SET LSRQST_CONI_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRQST_CONI_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRQST_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRQST_CONI_FLAG_ANAG = '1'
	
	UPDATE LSRRAD_CONI
	SET LSRRAD_CONI_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRRAD_CONI_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRRAD_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRAD_CONI_FLAG_ANAG = '1'
	
	UPDATE LSRRIN_CONI
	SET LSRRIN_CONI_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRRIN_CONI_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRRIN_CONI_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRIN_CONI_FLAG_ANAG = '1'

	UPDATE LSRTLP_ST
	SET LSRTLP_ST_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRTLP_ST_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRTLP_ST_KEY_ID_RICEV = @RICEVITORIA
		AND LSRTLP_ST_FLAG_ANAG = '1'

	UPDATE LSRRAD_ST
	SET LSRRAD_ST_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRRAD_ST_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEVITORIA
		AND LSRRAD_ST_FLAG_ANAG = '1'

----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI SPORTIVI -----------------------------------
----------------------------------------------------------------------------------------------------------------------
	UPDATE lsrcon_GS
	SET lsrcon_GS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		lsrcon_GS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE lsrcon_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrcon_GS_FLAG_ANAG = '1'


	UPDATE lsrnuo_GS
	SET lsrnuo_GS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		lsrnuo_GS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE lsrnuo_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrnuo_GS_FLAG_ANAG = '1'

	UPDATE lsrrad_GS
	SET lsrrad_GS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		lsrrad_GS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE lsrrad_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrrad_GS_FLAG_ANAG = '1'

	UPDATE lsrtlp_GS
	SET lsrtlp_GS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		lsrtlp_GS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE lsrtlp_GS_KEY_ID_RICEV = @RICEVITORIA
		AND lsrtlp_GS_FLAG_ANAG = '1'


----------------------------------------------------------------------------------------------------------------------
---------------------------- CONTRATTI  GIOCHI PUBBLICI -----------------------------------
----------------------------------------------------------------------------------------------------------------------

	UPDATE lsrcon_GP
	SET lsrcon_GP_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		lsrcon_GP_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE lsrcon_GP_KEY_ID_RICEV = @RICEVITORIA
		AND lsrcon_GP_FLAG_ANAG = '1'	
	
	UPDATE LSRFID_GP
	SET LSRFID_GP_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRFID_GP_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRFID_GP_KEY_ID_RICEV = @RICEVITORIA
		AND LSRFID_GP_FLAG_ANAG = '1'


	IF ISNUMERIC(LTRIM(RTRIM(@RICEVITORIA) )) = 1
	BEGIN
		UPDATE LSRCON_GEV 
		SET LSRCON_GEV_FK_DATA_INS_TIT_GEV = @NEWDATAINSTIT,
			LSRCON_GEV_FK_ORA_INS_TIT_GEV =@NEWORAINSTIT
		WHERE LSRCON_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRCON_GEV_FLAG_ANAG = '1'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_GEV'
			RETURN
		END
	
		-- LSRQST_GEV
		UPDATE LSRQST_GEV 
		SET LSRQST_GEV_FK_DATA_INS_TIT_GEV = @NEWDATAINSTIT,
			LSRQST_GEV_FK_ORA_INS_TIT_GEV = @NEWORAINSTIT
		WHERE LSRQST_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRQST_GEV_FLAG_ANAG = '1'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRQST_GEV'
			RETURN
		END
	
		-- LSRFID_GEV
		UPDATE LSRFID_GEV 
		SET LSRFID_GEV_FK_DATA_INS_TIT_GEV = @NEWDATAINSTIT,
			LSRFID_GEV_FK_ORA_INS_TIT_GEV = @NEWORAINSTIT
		WHERE LSRFID_GEV_COD_LOTTO = @RICEVITORIA
		AND  LSRFID_GEV_FLAG_ANAG = '1'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_GEV'
			RETURN
		END
	
		-- LSRRAD_GEV
		UPDATE LSRRAD_GEV 
		SET LSRRAD_FK_DATA_INS_TIT_GEV = @NEWDATAINSTIT,
			LSRRAD_FK_ORA_INS_TIT_GEV = @NEWORAINSTIT
		WHERE LSRRAD_COD_LOTTO = @RICEVITORIA
		AND LSRRAD_FLAG_ANAG = '1'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
			RETURN
		END

		-- LSRORD_GEV
		UPDATE LSRORD_GEV 
		SET LSRORD_GEV_FK_DATA_INS_TIT_GEV = @NEWDATAINSTIT,
			LSRORD_GEV_FK_ORA_INS_TIT_GEV = @NEWORAINSTIT
		WHERE LSRORD_GEV_COD_LOTTO = @RICEVITORIA
		AND LSRORD_GEV_FLAG_ANAG = '1'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRORD_GEV'
			RETURN
		END

		-- LSRCON_ITVM
		UPDATE LSRCON_ITVM 
		SET LSRCON_ITVM_FK_DATA_INS_TIT_GEV = @NEWDATAINSTIT,
			LSRCON_ITVM_FK_ORA_INS_TIT_GEV = @NEWORAINSTIT
		WHERE LSRCON_ITVM_COD_LOTTO = @RICEVITORIA
		AND LSRCON_ITVM_FLAG_ANAG = '1'
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_ITVM'
			RETURN
		END

	END


END

IF @@ERROR <> 0
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = '9999 - OPERAZIONE FALLITA - ERRORE IN AGGIORNAMENTO'
	RETURN
END

COMMIT TRANSACTION

SELECT @MSGERR = '0000 - OPERAZIONE TERMINATA CORRETTAMENTE'

RETURN
GO
