/****** Object:  StoredProcedure [dbo].[ANNULLA_PROVVEDIMENTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE    PROCEDURE [dbo].[ANNULLA_PROVVEDIMENTO]  

	@SERVIZIO		VARCHAR(10),
	@RICEVITORIA		CHAR(6),
	@DATAPROVV		CHAR(8),
	@PROGPROVV		VARCHAR(14),
	@TIPOREC		CHAR(1),
	@NEWFLAG		CHAR(1),
	@FIRMA		VARCHAR(17),
	@MSGERR		VARCHAR(100) OUTPUT  

AS

DECLARE	

@DATAINS 			CHAR(8),
@ORAINS   			CHAR(8),
@DATADECORR		CHAR(8),
@DATAINSPROVV		CHAR(8),
@ORAINSPROVV		CHAR(8),
@DATADECORPROVV		CHAR(8),
@DATAINSTIT			CHAR(8),
@ORAINSTIT			CHAR(8),
@NEWDATAINSTIT		CHAR(8),
@NEWORAINSTIT		CHAR(8),
@RICEVITORIA_APP 		CHAR(6),
@DECODRICEV		CHAR(50),
@NOTE   			VARCHAR(100)
		

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR, GETDATE(), 121),1,4)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),6,2)+ 
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),9,2)

SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
	SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)

BEGIN TRANSACTION

-- PRENDO LA DATA E ORA INSERIMENTO DEL PROVVEDIMENTO PRIMA CHE VENGA MODIFICATA
-- MI SERVE PERCHE' LA TROVO COME CHIAVE NELLA TABELLA LSRLET PER I RECORD DA CANCELLARE
SELECT @DATAINSPROVV = LSRPRO_DATA_INS,
	@ORAINSPROVV = LSRPRO_ORA_INS,
	@DATADECORPROVV = LSRPRO_DECOR_DAL
FROM LSRPRO	
WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
AND LSRPRO_KEY_DATA_PROVV = @DATAPROVV
AND LSRPRO_KEY_PROG_PROVV = @PROGPROVV
AND LSRPRO_KEY_TIPO_REC = @TIPOREC

--PRENDO L'ULTIMA DENOMINAZIONE VALIDA PRIMA DEL PROVVEDIMENTO ANNULLATO
SELECT @DECODRICEV = lsrric_decod_ricev
FROM LSRRIC A
WHERE LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA = 
	(SELECT MAX(LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) FROM LSRRIC B
	 WHERE LSRRIC_DATA_VALIDITA <= @DATAINS 
	AND B.LSRRIC_KEY_ID_RICEV = A.LSRRIC_KEY_ID_RICEV
	AND LSRRIC_FLAG_VALIDITA = 'Y'
	AND LSRRIC_DATA_VALIDITA < @DATADECORPROVV
	) 
AND LSRRIC_FLAG_VALIDITA = 'Y'
AND LSRRIC_KEY_ID_RICEV = @RICEVITORIA

IF @SERVIZIO = '01'
SELECT @NOTE = 'ANNULLAMENTO EFFETTUATO DA ' + @FIRMA + ' - VEDI PROVVEDIMENTO LOTTO ASSOCIATO'

BEGIN
	IF @TIPOREC = 'R' OR @TIPOREC = 'S' OR @TIPOREC = 'M'
	--INIZIO MODIFICA 25/06/2002 F-GIACOVAZZI
	 OR @TIPOREC = 'A'
	--FINE MODIFICA 25/06/2002 F-GIACOVAZZI
	BEGIN
		--SELEZIONO LA DATA DECORRENZA E LA DATA E ORA INSERIMENTO DEL PROVVEDIMENTO ANNULLATO
		SELECT @DATADECORR = LSRPRO_DECOR_DAL
		FROM LSRPRO	
		WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
		AND LSRPRO_KEY_DATA_PROVV = @DATAPROVV
		AND LSRPRO_KEY_PROG_PROVV = @PROGPROVV
		AND LSRPRO_KEY_TIPO_REC = @TIPOREC

		-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
		DELETE FROM LSRLET
		WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
		AND LSRLET_NOME_TAB_DOCUMENTO = 'LSRPRO'
		AND LSRLET_FK_TAB_DOCUMENTO = @DATAINSPROVV + @ORAINSPROVV

		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
			RETURN
		END

		-- CANCELLO I RECORD DELLA TABELLA LSRLET_LIS LEGATI AL PROVVEDIMENTO
		DELETE FROM LSRLET_LIS
		WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEVITORIA
		AND LSRLET_LIS_NOME_TAB_DOCUMENTO = 'LSRPRO'
		AND LSRLET_LIS_FK_TAB_DOCUMENTO = @DATAINSPROVV + @ORAINSPROVV

		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET_LIS'
			RETURN
		END
	END

	UPDATE LSRPRO SET 
	LSRPRO_FLAG_VALIDITA = @NEWFLAG,
	LSRPRO_DATA_INS = @DATAINS,
	LSRPRO_ORA_INS = @ORAINS
	WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRPRO_KEY_DATA_PROVV = @DATAPROVV
	AND LSRPRO_KEY_PROG_PROVV = @PROGPROVV
	AND LSRPRO_KEY_TIPO_REC = @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRPRO'
		RETURN
	END


	UPDATE LSRRIC SET 
	LSRRIC_FLAG_VALIDITA = @NEWFLAG,
	LSRRIC_KEY_DATA_INS = @DATAINS,
	LSRRIC_KEY_ORA_INS = @ORAINS
	WHERE LSRRIC_KEY_ID_RICEV =  @RICEVITORIA
	AND LSRRIC_DATA_PROVV =  @DATAPROVV
	AND LSRRIC_PROG_PROVV =  @PROGPROVV
	AND LSRRIC_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRIC'
		RETURN
	END

	--***********************************************************************************************************************************************************
	--***********************************************************************************************************************************************************
	-- MODIFICA DEL 09/01/2004: QUANDO ANNULLO DEVO MODIFICARE LA DENOMINAZIONE AI RECORD DI LSRRIC 
	-- DI TIPO T CON DECORRENZA > DI QUELLA DEL PROVVEDIMENTO ANNULLATO
	UPDATE LSRRIC SET 
	LSRRIC_DECOD_RICEV = @DECODRICEV
	WHERE LSRRIC_KEY_ID_RICEV =  @RICEVITORIA
		AND LSRRIC_DATA_VALIDITA >= @DATADECORPROVV
		AND LSRRIC_TIPO_PROVV = 'T'
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRIC'
		RETURN
	END
	--***********************************************************************************************************************************************************
	--***********************************************************************************************************************************************************

	UPDATE LSRTIT SET 
	LSRTIT_FLAG_VALIDITA = @NEWFLAG,
	LSRTIT_KEY_DATA_INS = @DATAINS,
	LSRTIT_KEY_ORA_INS = @ORAINS
	WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
	AND LSRTIT_DATA_PROVV =  @DATAPROVV
	AND LSRTIT_PROG_PROVV =  @PROGPROVV
	AND LSRTIT_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRTIT'
		RETURN
	END


	UPDATE LSRSER_LOTTO SET
	LSRSER_LOTTO_FLAG_VALIDITA = @NEWFLAG,	LSRSER_LOTTO_KEY_DATA_INS = @DATAINS,
	LSRSER_LOTTO_KEY_ORA_INS = @ORAINS,
	LSRSER_LOTTO_NOTE = @NOTE
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_LOTTO_DATA_PROVV =  @DATAPROVV
	AND LSRSER_LOTTO_PROG_PROVV =  @PROGPROVV
	AND LSRSER_LOTTO_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_LOTTO'
		RETURN
	END

	UPDATE LSRSER_F101 SET
	LSRSER_F101_FLAG_VALIDITA = @NEWFLAG,
	LSRSER_F101_KEY_DATA_INS = @DATAINS,
	LSRSER_F101_KEY_ORA_INS = @ORAINS,
	LSRSER_F101_NOTE = @NOTE
	WHERE LSRSER_F101_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_F101_DATA_PROVV =  @DATAPROVV
	AND LSRSER_F101_PROG_PROVV =  @PROGPROVV
	AND LSRSER_F101_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_F101'
		RETURN
	END

	UPDATE LSRSER_BOLLO SET
	LSRSER_BOLLO_FLAG_VALIDITA = @NEWFLAG,
	LSRSER_BOLLO_KEY_DATA_INS = @DATAINS,
	LSRSER_BOLLO_KEY_ORA_INS = @ORAINS,
	LSRSER_BOLLO_NOTE = @NOTE
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_BOLLO_DATA_PROVV =  @DATAPROVV
	AND LSRSER_BOLLO_PROG_PROVV =  @PROGPROVV
	AND LSRSER_BOLLO_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_BOLLO'
		RETURN
	END

/*	UPDATE LSRSER_TRIS SET
	LSRSER_TRIS_FLAG_VALIDITA = @NEWFLAG,
	LSRSER_TRIS_KEY_DATA_INS = @DATAINS,
	LSRSER_TRIS_KEY_ORA_INS = @ORAINS,
	LSRSER_TRIS_NOTE = @NOTE
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_TRIS_DATA_PROVV =  @DATAPROVV
	AND LSRSER_TRIS_PROG_PROVV =  @PROGPROVV
	AND LSRSER_TRIS_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_TRIS'
		RETURN
	END
*/
	UPDATE LSRSER_CONI SET
	LSRSER_CONI_FLAG_VALIDITA = @NEWFLAG,	LSRSER_CONI_KEY_DATA_INS = @DATAINS,
	LSRSER_CONI_KEY_ORA_INS = @ORAINS,
	LSRSER_CONI_NOTE = @NOTE
	WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_CONI_DATA_PROVV =  @DATAPROVV
	AND LSRSER_CONI_PROG_PROVV =  @PROGPROVV
	AND LSRSER_CONI_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_CONI'
		RETURN
	END

	UPDATE LSRSER_GEV SET
	LSRSER_GEV_FLAG_VALIDITA = @NEWFLAG,	LSRSER_GEV_KEY_DATA_INS = @DATAINS,
	LSRSER_GEV_KEY_ORA_INS = @ORAINS,
	LSRSER_GEV_NOTE = @NOTE
	WHERE LSRSER_GEV_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_GEV_DATA_PROVV =  @DATAPROVV
	AND LSRSER_GEV_PROG_PROVV =  @PROGPROVV
	AND LSRSER_GEV_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_GEV'
		RETURN
	END

	--**********************************
	--          SERVIZI LIS
	--**********************************
	UPDATE LSRSER_TEL SET
	LSRSER_TEL_FLAG_VALIDITA = @NEWFLAG,
	LSRSER_TEL_KEY_DATA_INS = @DATAINS,
	LSRSER_TEL_KEY_ORA_INS = @ORAINS,
	LSRSER_TEL_NOTE = @NOTE
	WHERE LSRSER_TEL_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_TEL_DATA_PROVV =  @DATAPROVV
	AND LSRSER_TEL_PROG_PROVV =  @PROGPROVV
	AND LSRSER_TEL_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_TEL'
		RETURN
	END

	UPDATE LSRSER_CITT SET
	LSRSER_CITT_FLAG_VALIDITA = @NEWFLAG,
	LSRSER_CITT_KEY_DATA_INS = @DATAINS,
	LSRSER_CITT_KEY_ORA_INS = @ORAINS,
	LSRSER_CITT_NOTE = @NOTE
	WHERE LSRSER_CITT_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_CITT_DATA_PROVV =  @DATAPROVV
	AND LSRSER_CITT_PROG_PROVV =  @PROGPROVV
	AND LSRSER_CITT_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_CITT'
		RETURN
	END

	UPDATE LSRSER_PAG SET
	LSRSER_PAG_FLAG_VALIDITA = @NEWFLAG,
	LSRSER_PAG_KEY_DATA_INS = @DATAINS,
	LSRSER_PAG_KEY_ORA_INS = @ORAINS,
	LSRSER_PAG_NOTE = @NOTE
	WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_PAG_DATA_PROVV =  @DATAPROVV
	AND LSRSER_PAG_PROG_PROVV =  @PROGPROVV
	AND LSRSER_PAG_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_PAG'
		RETURN
	END

	UPDATE LSRSER_BIG SET
	LSRSER_BIG_FLAG_VALIDITA = @NEWFLAG,
	LSRSER_BIG_KEY_DATA_INS = @DATAINS,
	LSRSER_BIG_KEY_ORA_INS = @ORAINS,
	LSRSER_BIG_NOTE = @NOTE
	WHERE LSRSER_BIG_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_BIG_DATA_PROVV =  @DATAPROVV
	AND LSRSER_BIG_PROG_PROVV =  @PROGPROVV
	AND LSRSER_BIG_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_BIG'
		RETURN
	END

	UPDATE LSRSER_ATTI SET
	LSRSER_ATTI_FLAG_VALIDITA = @NEWFLAG,
	LSRSER_ATTI_KEY_DATA_INS = @DATAINS,
	LSRSER_ATTI_KEY_ORA_INS = @ORAINS,
	LSRSER_ATTI_NOTE = @NOTE
	WHERE LSRSER_ATTI_KEY_ID_RICEV = @RICEVITORIA
	AND LSRSER_ATTI_DATA_PROVV =  @DATAPROVV
	AND LSRSER_ATTI_PROG_PROVV =  @PROGPROVV
	AND LSRSER_ATTI_TIPO_PROVV =  @TIPOREC

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRSER_ATTI'
		RETURN
	END
END


--***************************************************************************************************************************
-- SE IL PROVVEDIMENTO ANNULLATO è DI TIPO I, OCCORRE RIMETTERE A POSTO IL FLAG ANAGRAFICA SULLA CONTRATTUALISTICA,
-- E OCCORRE ELIMINARE I RECORD DALLA TABELLA LSRLET LEGATI A TALE PROVVEDIMENTO
IF @TIPOREC = 'I'
BEGIN
	--SELEZIONO LA DATA DECORRENZA E LA DATA E ORA INSERIMENTO DEL PROVVEDIMENTO ANNULLATO
	SELECT @DATADECORR = LSRPRO_DECOR_DAL
	FROM LSRPRO	
	WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRPRO_KEY_DATA_PROVV = @DATAPROVV
	AND LSRPRO_KEY_PROG_PROVV = @PROGPROVV
	AND LSRPRO_KEY_TIPO_REC = @TIPOREC

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET
	WHERE LSRLET_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_NOME_TAB_DOCUMENTO = 'LSRPRO'
	AND LSRLET_FK_TAB_DOCUMENTO = @DATAINSPROVV + @ORAINSPROVV
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET'
		RETURN
	END

	-- CANCELLO I RECORD DELLA TABELLA LSRLET LEGATI AL PROVVEDIMENTO
	DELETE FROM LSRLET_LIS
	WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRLET_LIS_NOME_TAB_DOCUMENTO = 'LSRPRO'
	AND LSRLET_LIS_FK_TAB_DOCUMENTO = @DATAINSPROVV + @ORAINSPROVV
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN DELETE LSRLET_LIS'
		RETURN
	END

--************************************************************************************************************
-- CONTROLLO COMMENTATO DA CDS IL 05/02/2004 PERCHè RITENUTO SBAGLIATO

	--VERIFICO CHE LA DATA DECORRENZA SIA NEL PASSATO E CHE NON CI SIANO ALTRI PROVVEDIMENTI CON
	--DATA DECORRENZA MAGGIORE
--	IF (@DATADECORR <= @DATAINS)  
--	BEGIN
--		select @RICEVITORIA_APP = null
--		SELECT  @RICEVITORIA_APP = LSRPRO_KEY_ID_RICEV 
--		FROM LSRPRO
--		WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
--		AND LSRPRO_DECOR_DAL > @DATADECORR
--		AND LSRPRO_DECOR_DAL <= @DATAINS
--		AND LSRPRO_FLAG_VALIDITA ='Y'

--		IF (@RICEVITORIA_APP = '') OR (@RICEVITORIA_APP IS NULL)
--		BEGIN
			--*****************************************************************
			--PRENDO LA CHIAVE ESTERNA DEL TITOLARE ANNULLATO  
			SELECT @DATAINSTIT = LSRTIT_KEY_DATA_INS,
				@ORAINSTIT = LSRTIT_KEY_ORA_INS			FROM LSRTIT 
			WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
			AND LSRTIT_DATA_PROVV =  @DATAPROVV
			AND LSRTIT_PROG_PROVV =  @PROGPROVV
			AND LSRTIT_TIPO_PROVV =  @TIPOREC
			
			-- ANNULLO TUTTI I CONTRATTI CHE HANNO QUESTA CHIAVE ESTERNA, METTENDO IL FLAG_ANAG A 0 
			-- E METTENDO A ''  FK_DATA_INS_TIT E FK_ORA_INS_TIT

			--LSRAPS_F101
			UPDATE LSRAPS_F101 
			SET LSRAPS_F101_FK_DATA_INS_TIT = '',
				LSRAPS_F101_FK_ORA_INS_TIT ='',
				LSRAPS_F101_FLAG_ANAG = '0' 
			WHERE LSRAPS_F101_KEY_ID_RICEV = @RICEVITORIA
			AND LSRAPS_F101_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRAPS_F101_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAPS_F101'
				RETURN
			END

			-- LSRAPS_TRIS
			UPDATE LSRAPS_TRIS 
			SET LSRAPS_TRIS_FK_DATA_INS_TIT = '',
				LSRAPS_TRIS_FK_ORA_INS_TIT ='',
				LSRAPS_TRIS_FLAG_ANAG = '0' 
			WHERE LSRAPS_TRIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRAPS_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRAPS_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAPS_TRIS'
				RETURN
			END

			-- LSRCON_BOLLO
			UPDATE LSRCON_BOLLO 
			SET LSRCON_BOLLO_FK_DATA_INS_TIT = '',
				LSRCON_BOLLO_FK_ORA_INS_TIT ='',
				LSRCON_BOLLO_FLAG_ANAG = '0' 
			WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEVITORIA
			AND LSRCON_BOLLO_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_BOLLO_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_BOLLO'
				RETURN
			END

			-- LSRCON_F101
			UPDATE LSRCON_F101 
			SET LSRCON_F101_FK_DATA_INS_TIT = '',
				LSRCON_F101_FK_ORA_INS_TIT ='',
				LSRCON_F101_FLAG_ANAG = '0' 
			WHERE LSRCON_F101_KEY_ID_RICEV = @RICEVITORIA
			AND LSRCON_F101_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_F101_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_F101'
				RETURN
			END

			-- LSRCON_TRIS
			UPDATE LSRCON_TRIS 
			SET LSRCON_TRIS_FK_DATA_INS_TIT = '',
				LSRCON_TRIS_FK_ORA_INS_TIT ='',
				LSRCON_TRIS_FLAG_ANAG = '0' 
			WHERE LSRCON_TRIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRCON_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_TRIS'
				RETURN
			END

			-- LSRFID_F101
			UPDATE LSRFID_F101 
			SET LSRFID_F101_FK_DATA_INS_TIT = '',
				LSRFID_F101_FK_ORA_INS_TIT ='',
				LSRFID_F101_FLAG_ANAG = '0' 
			WHERE LSRFID_F101_KEY_ID_RICEV = @RICEVITORIA
			AND LSRFID_F101_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRFID_F101_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_F101'
				RETURN
			END

			-- LSRFID_TRIS
			UPDATE LSRFID_TRIS 
			SET LSRFID_TRIS_FK_DATA_INS_TIT = '',
				LSRFID_TRIS_FK_ORA_INS_TIT ='',
				LSRFID_TRIS_FLAG_ANAG = '0' 
			WHERE LSRFID_TRIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRFID_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRFID_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_TRIS'
				RETURN
			END

			-- LSRRAD
			UPDATE LSRRAD 
			SET LSRRAD_FK_DATA_INS_TIT = '',
				LSRRAD_FK_ORA_INS_TIT ='',
				LSRRAD_FLAG_ANAG = '0' 
			WHERE LSRRAD_KEY_ID_RICEV = @RICEVITORIA
			AND LSRRAD_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRAD_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD'
				RETURN
			END

			-- LSRRIN
			UPDATE LSRRIN 
			SET LSRRIN_FK_DATA_INS_TIT = '',
				LSRRIN_FK_ORA_INS_TIT ='',
				LSRRIN_FLAG_ANAG = '0' 
			WHERE LSRRIN_KEY_ID_RICEV = @RICEVITORIA
			AND LSRRIN_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRIN_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRIN'
				RETURN
			END



			--*****************************************************************
			--  GRATTA E VINCI

			-- LSRCON_GEV
			UPDATE LSRCON_GEV 
			SET LSRCON_GEV_FK_DATA_INS_TIT = null,
				LSRCON_GEV_FK_ORA_INS_TIT =null,
				LSRCON_GEV_FLAG_ANAG = '0' 
			WHERE LSRCON_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRCON_GEV_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_GEV_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_GEV'
				RETURN
			END

			-- LSRQST_GEV
			UPDATE LSRQST_GEV 
			SET LSRQST_GEV_FK_DATA_INS_TIT = null,
				LSRQST_GEV_FK_ORA_INS_TIT = null,
				LSRQST_GEV_FLAG_ANAG = '0' 
			WHERE LSRQST_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRQST_GEV_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRQST_GEV_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRQST_GEV'
				RETURN
			END

			-- LSRFID_GEV
			UPDATE LSRFID_GEV 
			SET LSRFID_GEV_FK_DATA_INS_TIT = null,
				LSRFID_GEV_FK_ORA_INS_TIT =null,
				LSRFID_GEV_FLAG_ANAG = '0' 
			WHERE LSRFID_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRFID_GEV_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRFID_GEV_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_GEV'
				RETURN
			END

			-- LSRRAD_GEV
			UPDATE LSRRAD_GEV 
			SET LSRRAD_FK_DATA_INS_TIT = null,
				LSRRAD_FK_ORA_INS_TIT = null,
				LSRRAD_FLAG_ANAG = '0' 
			WHERE LSRRAD_COD_LOTTO = @RICEVITORIA
			AND LSRRAD_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRAD_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
				RETURN
			END

			-- LSRORD_GEV
			UPDATE LSRORD_GEV 
			SET LSRORD_GEV_FK_DATA_INS_TIT = null,
				LSRORD_GEV_FK_ORA_INS_TIT = null,
				LSRORD_GEV_FLAG_ANAG = '0' 
			WHERE LSRORD_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRORD_GEV_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRORD_GEV_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
				RETURN
			END

			-- LSRCON_ITVM
			UPDATE LSRCON_ITVM 
			SET LSRCON_ITVM_FK_DATA_INS_TIT = null,
				LSRCON_ITVM_FK_ORA_INS_TIT = null,
				LSRCON_ITVM_FLAG_ANAG = '0' 
			WHERE LSRCON_ITVM_COD_LOTTO = @RICEVITORIA
			AND LSRCON_ITVM_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_ITVM_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_ITVM'
				RETURN
			END

			--*****************************************************************
			--  SERVIZI LIS

			-- LSRADE_LIS
			UPDATE LSRADE_LIS 
			SET LSRADE_LIS_FK_DATA_INS_TIT = '',
				LSRADE_LIS_FK_ORA_INS_TIT ='',
				LSRADE_LIS_FLAG_ANAG = '0' 
			WHERE LSRADE_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRADE_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRADE_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRADE_LIS'
				RETURN
			END

			-- LSRAUT_LIS
			UPDATE LSRAUT_LIS 
			SET LSRAUT_LIS_FK_DATA_INS_TIT = '',
				LSRAUT_LIS_FK_ORA_INS_TIT ='',
				LSRAUT_LIS_FLAG_ANAG = '0' 
			WHERE LSRAUT_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRAUT_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRAUT_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAUT_LIS'
				RETURN
			END

			-- LSRCON_LIS
			UPDATE LSRCON_LIS 
			SET LSRCON_LIS_FK_DATA_INS_TIT = '',
				LSRCON_LIS_FK_ORA_INS_TIT ='',
				LSRCON_LIS_FLAG_ANAG = '0' 
			WHERE LSRCON_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRCON_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_LIS'
				RETURN
			END

			-- LSRFID_LIS
			UPDATE LSRFID_LIS 
			SET LSRFID_LIS_FK_DATA_INS_TIT = '',				LSRFID_LIS_FK_ORA_INS_TIT ='',
				LSRFID_LIS_FLAG_ANAG = '0' 
			WHERE LSRFID_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRFID_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRFID_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_LIS'
				RETURN
			END

			-- LSRRAD_LIS
			UPDATE LSRRAD_LIS 
			SET LSRRAD_LIS_FK_DATA_INS_TIT = '',
				LSRRAD_LIS_FK_ORA_INS_TIT ='',
				LSRRAD_LIS_FLAG_ANAG = '0' 
			WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRRAD_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRAD_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_LIS'
				RETURN
			END

			-- LSRRIN_LIS
			UPDATE LSRRIN_LIS 
			SET LSRRIN_LIS_FK_DATA_INS_TIT = '',
				LSRRIN_LIS_FK_ORA_INS_TIT ='',
				LSRRIN_LIS_FLAG_ANAG = '0' 
			WHERE LSRRIN_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRRIN_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRIN_LIS_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRIN_LIS'
				RETURN
			END

		

			--*****************************************************************
			--*****************************************************************
			--PRENDO LA CHIAVE ESTERNA DELL'ULTIMO TITOLARE VALIDO PRIMA DI QUELLO ANNULLATO
			SELECT @DATAINSTIT = LSRTIT_KEY_DATA_INS,
				@ORAINSTIT = LSRTIT_KEY_ORA_INS
			FROM LSRTIT 
			WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
			AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
				(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) 
				FROM LSRTIT 
				WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
				AND  LSRTIT_DATA_VALIDITA <= @DATAINS
				AND LSRTIT_FLAG_VALIDITA = 'Y')
			AND LSRTIT_FLAG_VALIDITA = 'Y'
			
			--METTO A 1 IL FLAG DEI CONTRATTI ASSOCIATI A QUESTO TITOLARE

			-- LSRAPS_F101
			UPDATE LSRAPS_F101 
			SET LSRAPS_F101_FLAG_ANAG = '1' 
			WHERE LSRAPS_F101_KEY_ID_RICEV = @RICEVITORIA
			AND LSRAPS_F101_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRAPS_F101_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAPS_F101'
				RETURN
			END

			-- LSRAPS_TRIS
			UPDATE LSRAPS_TRIS 
			SET LSRAPS_TRIS_FLAG_ANAG = '1' 
			WHERE LSRAPS_TRIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRAPS_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRAPS_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAPS_TRIS'
				RETURN
			END

			-- LSRCON_BOLLO
			UPDATE LSRCON_BOLLO 
			SET LSRCON_BOLLO_FLAG_ANAG = '1' 
			WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEVITORIA
			AND LSRCON_BOLLO_FK_DATA_INS_TIT = @DATAINSTIT			AND LSRCON_BOLLO_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_BOLLO'
				RETURN
			END

			-- LSRCON_F101
			UPDATE LSRCON_F101 
			SET LSRCON_F101_FLAG_ANAG = '1' 
			WHERE LSRCON_F101_KEY_ID_RICEV = @RICEVITORIA
			AND LSRCON_F101_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_F101_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN

				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_F101'
				RETURN
			END

			-- LSRCON_TRIS
			UPDATE LSRCON_TRIS 
			SET LSRCON_TRIS_FLAG_ANAG = '1' 
			WHERE LSRCON_TRIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRCON_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_TRIS'
				RETURN
			END

			-- LSRFID_F101
			UPDATE LSRFID_F101 
			SET LSRFID_F101_FLAG_ANAG = '1' 
			WHERE LSRFID_F101_KEY_ID_RICEV = @RICEVITORIA
			AND LSRFID_F101_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRFID_F101_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_F101'
				RETURN
			END

			-- LSRFID_TRIS
			UPDATE LSRFID_TRIS 
			SET LSRFID_TRIS_FLAG_ANAG = '1' 
			WHERE LSRFID_TRIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRFID_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRFID_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_TRIS'
				RETURN
			END

			-- LSRRAD
			UPDATE LSRRAD 
			SET LSRRAD_FLAG_ANAG = '1' 
			WHERE LSRRAD_KEY_ID_RICEV = @RICEVITORIA
			AND LSRRAD_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRAD_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD'
				RETURN
			END

			-- LSRRIN
			UPDATE LSRRIN 
			SET LSRRIN_FLAG_ANAG = '1' 
			WHERE LSRRIN_KEY_ID_RICEV = @RICEVITORIA
			AND LSRRIN_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRIN_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRIN'
				RETURN
			END

			--*****************************************************************
			--  GRATTA E VINCI
			--*****************************************************************
			-- LSRCON_GEV
			UPDATE LSRCON_GEV 
			SET LSRCON_GEV_FLAG_ANAG = '1' 
			WHERE LSRCON_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRCON_GEV_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_GEV_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_GEV'
				RETURN
			END

			-- LSRQST_GEV
			UPDATE LSRQST_GEV 
			SET LSRQST_GEV_FLAG_ANAG = '1' 
			WHERE LSRQST_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRQST_GEV_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRQST_GEV_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRQST_GEV'
				RETURN
			END

			-- LSRFID_GEV
			UPDATE LSRFID_GEV 
			SET LSRFID_GEV_FLAG_ANAG = '1' 
			WHERE LSRFID_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRFID_GEV_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRFID_GEV_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_GEV'
				RETURN
			END

			-- LSRRAD_GEV
			UPDATE LSRRAD_GEV 
			SET LSRRAD_FLAG_ANAG = '1' 
			WHERE LSRRAD_COD_LOTTO = @RICEVITORIA
			AND LSRRAD_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRAD_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
				RETURN
			END

			-- LSRORD_GEV
			UPDATE LSRORD_GEV
			SET LSRORD_GEV_FLAG_ANAG = '1' 
			WHERE LSRORD_GEV_COD_LOTTO = @RICEVITORIA
			AND LSRORD_GEV_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRORD_GEV_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRORD_GEV'
				RETURN
			END

			-- LSRCON_ITVM
			UPDATE LSRCON_ITVM 
			SET LSRCON_ITVM_FLAG_ANAG = '1' 
			WHERE LSRCON_ITVM_COD_LOTTO = @RICEVITORIA
			AND LSRCON_ITVM_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_ITVM_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_ITVM'
				RETURN
			END


			--*****************************************************************
			--  SERVIZI LIS

			-- LSRADE_LIS
			UPDATE LSRADE_LIS 
			SET LSRADE_LIS_FLAG_ANAG = '1' 
			WHERE LSRADE_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRADE_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRADE_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRADE_LIS'
				RETURN
			END

			-- LSRAUT_LIS
			UPDATE LSRAUT_LIS 
			SET LSRAUT_LIS_FLAG_ANAG = '1' 
			WHERE LSRAUT_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRAUT_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRAUT_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAUT_LIS'
				RETURN
			END

			-- LSRCON_LIS
			UPDATE LSRCON_LIS 
			SET LSRCON_LIS_FLAG_ANAG = '1' 
			WHERE LSRCON_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRCON_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRCON_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_LIS'
				RETURN
			END

			-- LSRFID_LIS
			UPDATE LSRFID_LIS 
			SET LSRFID_LIS_FLAG_ANAG = '1' 
			WHERE LSRFID_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRFID_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRFID_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_LIS'
				RETURN
			END

			-- LSRRAD_LIS
			UPDATE LSRRAD_LIS 
			SET LSRRAD_LIS_FLAG_ANAG = '1' 
			WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRRAD_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRAD_LIS_FK_ORA_INS_TIT = @ORAINSTIT

			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_LIS'
				RETURN
			END

			-- LSRRIN_LIS
			UPDATE LSRRIN_LIS 
			SET LSRRIN_LIS_FLAG_ANAG = '1' 
			WHERE LSRRIN_LIS_KEY_ID_RICEV = @RICEVITORIA
			AND LSRRIN_LIS_FK_DATA_INS_TIT = @DATAINSTIT
			AND LSRRIN_LIS_FK_ORA_INS_TIT = @ORAINSTIT
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION
				SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRIN_LIS'
				RETURN
			END


--		END		

--	END

END


--***************************************************************************************************************************
-- SE IL PROVVEDIMENTO ANNULLATO è DI TIPO E, OCCORRE RIMETTERE A POSTO IL FLAG ANAGRAFICA SULLA CONTRATTUALISTICA
IF @TIPOREC = 'E'
BEGIN

	--PRENDO LA CHIAVE ESTERNA DEL TITOLARE ANNULLATO  
	SELECT @DATAINSTIT = LSRTIT_KEY_DATA_INS,
		@ORAINSTIT = LSRTIT_KEY_ORA_INS
	FROM LSRTIT 
	WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
	AND LSRTIT_DATA_PROVV =  @DATAPROVV
	AND LSRTIT_PROG_PROVV =  @PROGPROVV
	AND LSRTIT_TIPO_PROVV =  @TIPOREC

	--PRENDO LA CHIAVE ESTERNA DELL'ULTIMO TITOLARE VALIDO PRIMA DI QUELLO ANNULLATO
	SELECT @NEWDATAINSTIT = LSRTIT_KEY_DATA_INS,
		@NEWORAINSTIT = LSRTIT_KEY_ORA_INS
	FROM LSRTIT 
	WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
	AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
		(SELECT MAX(LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) 
		FROM LSRTIT 
		WHERE LSRTIT_KEY_ID_RICEV = @RICEVITORIA
		AND  LSRTIT_DATA_VALIDITA <= @DATAINS
		AND LSRTIT_FLAG_VALIDITA = 'Y')
	AND LSRTIT_FLAG_VALIDITA = 'Y'
	
	--AGGIORNO LA CHIAVE ESTERNA DEI CONTRATTI PER ASSOCIARE I CONTRATTI ALL'UTLIMO TITOLARE VALIDO

	-- LSRAPS_F101
	UPDATE LSRAPS_F101 
	SET  LSRAPS_F101_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRAPS_F101_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRAPS_F101_KEY_ID_RICEV = @RICEVITORIA
	AND LSRAPS_F101_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRAPS_F101_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAPS_F101'
		RETURN
	END

	-- LSRAPS_TRIS
	UPDATE LSRAPS_TRIS 
	SET  LSRAPS_TRIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		 LSRAPS_TRIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRAPS_TRIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRAPS_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRAPS_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAPS_TRIS'
		RETURN
	END

	-- LSRCON_BOLLO
	UPDATE LSRCON_BOLLO 
	SET LSRCON_BOLLO_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		 LSRCON_BOLLO_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRCON_BOLLO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRCON_BOLLO_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRCON_BOLLO_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_BOLLO'
		RETURN
	END

	-- LSRCON_F101
	UPDATE LSRCON_F101 
	SET LSRCON_F101_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRCON_F101_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRCON_F101_KEY_ID_RICEV = @RICEVITORIA
	AND LSRCON_F101_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRCON_F101_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_F101'
		RETURN
	END

	-- LSRCON_TRIS
	UPDATE LSRCON_TRIS 
	SET  LSRCON_TRIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		 LSRCON_TRIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRCON_TRIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRCON_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRCON_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_TRIS'
		RETURN
	END

	-- LSRFID_F101
	UPDATE LSRFID_F101 
	SET LSRFID_F101_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		 LSRFID_F101_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRFID_F101_KEY_ID_RICEV = @RICEVITORIA
	AND LSRFID_F101_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRFID_F101_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_F101'
		RETURN
	END

	-- LSRFID_TRIS
	UPDATE LSRFID_TRIS 
	SET LSRFID_TRIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		 LSRFID_TRIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRFID_TRIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRFID_TRIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRFID_TRIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_TRIS'
		RETURN
	END

	-- LSRRAD
	UPDATE LSRRAD 
	SET LSRRAD_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		 LSRRAD_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRRAD_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRAD_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRRAD_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD'
		RETURN
	END

	-- LSRRIN
	UPDATE LSRRIN 
	SET LSRRIN_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRRIN_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRRIN_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRIN_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRRIN_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRIN'
		RETURN
	END


	--*****************************************************************
	--  GRATTA E VINCI
	--*****************************************************************
	-- LSRCON_GEV
	UPDATE LSRCON_GEV 
	SET  LSRCON_GEV_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRCON_GEV_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRCON_GEV_COD_LOTTO = @RICEVITORIA
	AND LSRCON_GEV_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRCON_GEV_FK_ORA_INS_TIT = @ORAINSTIT
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_GEV'
		RETURN
	END

	-- LSRQST_GEV
	UPDATE LSRQST_GEV 
	SET LSRQST_GEV_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRQST_GEV_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRQST_GEV_COD_LOTTO = @RICEVITORIA
	AND LSRQST_GEV_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRQST_GEV_FK_ORA_INS_TIT = @ORAINSTIT
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRQST_GEV'
		RETURN
	END

	-- LSRFID_GEV
	UPDATE LSRFID_GEV 
	SET LSRFID_GEV_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRFID_GEV_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRFID_GEV_COD_LOTTO = @RICEVITORIA
	AND LSRFID_GEV_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRFID_GEV_FK_ORA_INS_TIT = @ORAINSTIT
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_GEV'
		RETURN
	END

	-- LSRRAD_GEV
	UPDATE LSRRAD_GEV 
	SET LSRRAD_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRRAD_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRRAD_COD_LOTTO = @RICEVITORIA
	AND LSRRAD_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRRAD_FK_ORA_INS_TIT = @ORAINSTIT
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_GEV'
		RETURN
	END


	-- LSRCON_ITVM
	UPDATE LSRCON_ITVM 
	SET LSRCON_ITVM_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRCON_ITVM_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRCON_ITVM_COD_LOTTO = @RICEVITORIA
	AND LSRCON_ITVM_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRCON_ITVM_FK_ORA_INS_TIT = @ORAINSTIT
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_ITVM'
		RETURN
	END


	--*****************************************************************
	--  SERVIZI LIS

	-- LSRADE_LIS
	UPDATE LSRADE_LIS 
	SET LSRADE_LIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRADE_LIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRADE_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRADE_LIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRADE_LIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRADE_LIS'
		RETURN
	END

	-- LSRAUT_LIS
	UPDATE LSRAUT_LIS 
	SET  LSRAUT_LIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRAUT_LIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRAUT_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRAUT_LIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRAUT_LIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRAUT_LIS'
		RETURN
	END

	-- LSRCON_LIS
	UPDATE LSRCON_LIS 
	SET  LSRCON_LIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRCON_LIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRCON_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRCON_LIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRCON_LIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRCON_LIS'
		RETURN
	END

	-- LSRFID_LIS
	UPDATE LSRFID_LIS 
	SET  LSRFID_LIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRFID_LIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRFID_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRFID_LIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRFID_LIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRFID_LIS'
		RETURN
	END

	-- LSRRAD_LIS
	UPDATE LSRRAD_LIS 
	SET LSRRAD_LIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRRAD_LIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRRAD_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRAD_LIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRRAD_LIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRAD_LIS'
		RETURN
	END

	-- LSRRIN_LIS
	UPDATE LSRRIN_LIS 
	SET  LSRRIN_LIS_FK_DATA_INS_TIT = @NEWDATAINSTIT,
		LSRRIN_LIS_FK_ORA_INS_TIT = @NEWORAINSTIT
	WHERE LSRRIN_LIS_KEY_ID_RICEV = @RICEVITORIA
	AND LSRRIN_LIS_FK_DATA_INS_TIT = @DATAINSTIT
	AND LSRRIN_LIS_FK_ORA_INS_TIT = @ORAINSTIT

	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'NOK - ERRORE IN UPDATE LSRRIN_LIS'
		RETURN
	END


END


SELECT @MSGERR = 'OK - ANNULLAMENTO EFFETTUATO CORRETTAMENTE'
COMMIT

RETURN
GO
