/****** Object:  StoredProcedure [dbo].[GEV_SCRIVI_LSRLET]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[GEV_SCRIVI_LSRLET] 
 
@CODLTM			CHAR(6),
@CON	 			VARCHAR(3), 
@FID	 			VARCHAR(3), 
@RID	 			VARCHAR(3), 
@QUE	 			VARCHAR(3), 
@RAD	 			VARCHAR(3), 
@DATAINS			CHAR(8),
@ORAINS			CHAR(8),
@TIPOMOV			CHAR(1),
@FIRMA	 		VARCHAR(17)


AS

DECLARE		

@IDDOC		CHAR(16),
@RICERIN		CHAR(6),
@CODSER		CHAR(2)

SELECT @CODSER = '09'

IF @CON <> '0'
BEGIN
	SELECT @IDDOC = NULL
	
	SELECT @IDDOC =  LSRCON_GEV_KEY_DATA_INS +  LSRCON_GEV_KEY_ORA_INS 
	FROM LSRCON_GEV 
	WHERE LSRCON_GEV_COD_LOTTO = @CODLTM
	AND LSRCON_GEV_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINS, @ORAINS, @CODSER, @TIPOMOV, '00000000', 'LSRCON_GEV', @IDDOC, '00000000', '', @FIRMA, '')
	END
END


IF @FID <> '0'
BEGIN
		SELECT @IDDOC = NULL
		SELECT @IDDOC =  LSRFID_GEV_KEY_DATA_INS +  LSRFID_GEV_KEY_ORA_INS 
		FROM LSRFID_GEV WHERE LSRFID_GEV_COD_LOTTO = @CODLTM
		AND LSRFID_GEV_ANNO_RIF = CONVERT(CHAR(4), GETDATE(), 112)
		AND LSRFID_GEV_FLAG_ANAG = '1'

		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET VALUES
			(@CODLTM, @DATAINS, @ORAINS, @CODSER, @TIPOMOV, '00000000', 'LSRFID_GEV', @IDDOC, '00000000', '', @FIRMA, '')
		END

END

IF @QUE <> '0'
BEGIN
	SELECT @IDDOC = NULL
	SELECT @IDDOC =  LSRQST_GEV_KEY_DATA_INS +  LSRQST_GEV_KEY_ORA_INS 
	FROM LSRQST_GEV 
	WHERE LSRQST_GEV_KEY_ID_RICEV = @CODLTM
	AND LSRQST_GEV_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINS, @ORAINS, @CODSER, @TIPOMOV, '00000000', 'LSRQST_GEV', @IDDOC, '00000000', '', @FIRMA, '')
	END
END



IF @RAD <> '0'
BEGIN

	SELECT @IDDOC = NULL
	DECLARE CUR_RAD_1 CURSOR FOR 
	
	SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS 
	FROM LSRRAD_GEV D
	WHERE  LSRRAD_FLAG_ANAG = '1'
		AND LSRRAD_TIPO_MOVIMENTAZIONE =  @TIPOMOV 
		AND LSRRAD_COD_LOTTO = @CODLTM
		AND LSRRAD_DATA_INVIO_DOC <= CONVERT(CHAR, GETDATE(), 112)
		AND LSRRAD_DATA_DECOR >= 
			(SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV  
			WHERE LSRSER_GEV_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
			AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	 		AND LSRSER_GEV_KEY_ID_RICEV = D.LSRRAD_COD_LOTTO )

		AND LSRRAD_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)


	OPEN CUR_RAD_1
	FETCH NEXT FROM CUR_RAD_1 INTO @IDDOC
	WHILE @@FETCH_STATUS = 0
	BEGIN

		
			INSERT INTO LSRLET VALUES
			(@CODLTM, @DATAINS, @ORAINS, @CODSER, @TIPOMOV, '00000000', 'LSRRAD_GEV', @IDDOC, '00000000', '', @FIRMA, '')
		
		SELECT @IDDOC = NULL
	
		FETCH NEXT FROM CUR_RAD_1 INTO @IDDOC
	END

	CLOSE CUR_RAD_1
	DEALLOCATE CUR_RAD_1
END

/*
IF @RID <> '0'
BEGIN
	SELECT @IDDOC = NULL
	SELECT @IDDOC =  LCR01A_KEY_ID_RICEV +  LCR01A_TIPO_GIOCO + LCR01A_KEY_DATA_FINE_VAL
	FROM LCR01A
	WHERE LCR01A_KEY_ID_RICEV = @CODLTM
	AND LCR01A_KEY_DATA_FINE_VAL = '99999999'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN

		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINS, @ORAINS, @CODSER, @TIPOMOV, '00000000', 'LCR01A', @IDDOC, '00000000', '', @FIRMA, '')
	END
END
*/

/*
IF @RAD <> '0'
BEGIN
	IF @TIPOMOV = 'D'
	BEGIN
		-- MODIFICA DEL 30/07/2001:
		-- AGGIUNTA LA CONDIZIONE CHE LA DATA DI INVIO DEL DOCUMENTO RAD
		-- SIA >= DELLA DATA DECORRENZA DELLO STATO ATTUALE DEL SERVIZIO
		IF @CODSER = '02'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			OR
			(LSRRAD_FONTE = 'Q' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' )
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '7'))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'D' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_F101_DATA_DECOR)
				FROM LSRSER_F101
				WHERE LSRSER_F101_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_F101_FLAG_VALIDITA = 'Y' 
				AND LSRSER_F101_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD
			DEALLOCATE CUR_RAD
		END -- END IF CODSER=02

		IF @CODSER = '05'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			OR
			(LSRRAD_FONTE = 'Q' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' )
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '7'))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'D' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
				FROM LSRSER_BOLLO
				WHERE LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y' 
				AND LSRSER_BOLLO_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD
			DEALLOCATE CUR_RAD

		END -- END IF CODSER=05

		IF @CODSER = '08'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			OR
			(LSRRAD_FONTE = 'Q' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D')
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' )
			OR
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'D' AND LSRRAD_CAUSALE_LOTTOMATICA = '7'))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'D' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_TRIS_DATA_DECOR)
				FROM LSRSER_TRIS 
				WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
				AND LSRSER_TRIS_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD
			DEALLOCATE CUR_RAD

		END -- END IF CODSER=08
	END
	IF @TIPOMOV = 'S'
	BEGIN
		DECLARE CUR_RAD CURSOR FOR 
		SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
		LSRRAD_KEY_ID_RICEV = @RICEV
		AND
		((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S')
		OR
		(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
		OR
		(LSRRAD_FONTE = 'Q' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S')
		OR
		(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S' )
		OR
		(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'S' AND LSRRAD_CAUSALE_LOTTOMATICA = '7'))
		AND LSRRAD_TIPO_SERVIZIO = @CODSER
		AND LSRRAD_FLAG_ANAG = '1'
		AND LSRRAD_DATA_INVIO_DOC > 
			(SELECT  VAR = CASE 
				WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 			FROM LSRRAD 
			WHERE LSRRAD_FLAG_ANAG = '1' 
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_KEY_ID_RICEV = @RICEV
			AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'S' )
		AND LSRRAD_DATA_INVIO_DOC >=
			(SELECT MAX(LSRSER_TRIS_DATA_DECOR)
			FROM LSRSER_TRIS 
			WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
			AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
			AND LSRSER_TRIS_KEY_ID_RICEV = @RICEV)

		--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
		AND lsrrad_data_decor <= (convert(char(8) ,getdate() + 1,112))

		OPEN CUR_RAD
		FETCH NEXT FROM CUR_RAD INTO @IDDOC
		WHILE @@FETCH_STATUS = 0
		BEGIN
			INSERT INTO LSRLET VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
		
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
		END

		CLOSE CUR_RAD
		DEALLOCATE CUR_RAD

	END

	IF @TIPOMOV = 'R'
	BEGIN

		-- MODIFICA DEL 30/07/2001:
		-- AGGIUNTA LA CONDIZIONE CHE LA DATA DI INVIO DEL DOCUMENTO RAD
		-- SIA >= DELLA DATA DECORRENZA DELLO STATO ATTUALE DEL SERVIZIO

		IF @CODSER = '02' 
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			(
			(LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R')
			OR
			--MODIFICA DEL 15/06/2001 : TOLTA LA CAUSALE LOTTOMATICA
			--(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' )
			--MODIFICA DEL 06/02/2002 : TOLTA LA FONTE ASSOCIAZIONE
			--OR
			--(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' )
			)
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'R' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_F101_DATA_DECOR)
				FROM LSRSER_F101
				WHERE LSRSER_F101_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_F101_FLAG_VALIDITA = 'Y' 
				AND LSRSER_F101_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD

			DEALLOCATE CUR_RAD
		END -- END IF CODSER=02

		IF @CODSER = '05' 
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R')
			OR
			--MODIFICA DEL 15/06/2001 : TOLTA LA CAUSALE LOTTOMATICA
			--(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' )
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' ))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'R' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_BOLLO_DATA_DECOR)
				FROM LSRSER_BOLLO
				WHERE LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y' 
				AND LSRSER_BOLLO_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD

			DEALLOCATE CUR_RAD
		END -- END IF CODSER=05

		IF @CODSER = '08' 
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R')
			OR
			--MODIFICA DEL 15/06/2001 : TOLTA LA CAUSALE LOTTOMATICA
			--(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' AND LSRRAD_CAUSALE_LOTTOMATICA = '3')
			(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' )
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R' ))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'R' )
			AND LSRRAD_DATA_INVIO_DOC >=
				(SELECT MAX(LSRSER_TRIS_DATA_DECOR)
				FROM LSRSER_TRIS
				WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
				AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
				AND LSRSER_TRIS_KEY_ID_RICEV = @RICEV)

			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD

			DEALLOCATE CUR_RAD
		END -- END IF CODSER=02

	END

	IF @TIPOMOV = 'A'
	BEGIN
		-- MODIFICA DEL 30/07/2001:
		-- AGGIUNTA LA CONDIZIONE CHE LA DATA DI INVIO DEL DOCUMENTO RAD
		-- SIA >= DELLA DATA DECORRENZA DELLO STATO ATTUALE DEL SERVIZIO
		-- WARNING: CONTROLLO RIMOSSO IL 01/08/2001
		IF @CODSER = '05'
		BEGIN
			DECLARE CUR_RAD CURSOR FOR 
			SELECT LSRRAD_KEY_DATA_INS + LSRRAD_KEY_ORA_INS FROM LSRRAD WHERE
			LSRRAD_KEY_ID_RICEV = @RICEV
			AND
			((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'A')
			OR
			(LSRRAD_FONTE = 'A' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'A' ))
			AND LSRRAD_TIPO_SERVIZIO = @CODSER
			AND LSRRAD_FLAG_ANAG = '1'
			AND LSRRAD_DATA_INVIO_DOC > 
				(SELECT  VAR = CASE 
					WHEN(MAX(LSRRAD_DATA_INVIO_DOC)) IS NULL THEN '00000000'  ELSE (MAX(LSRRAD_DATA_INVIO_DOC)) END
 				FROM LSRRAD 
				WHERE LSRRAD_FLAG_ANAG = '1' 
				AND LSRRAD_TIPO_SERVIZIO = @CODSER
				AND LSRRAD_KEY_ID_RICEV = @RICEV
				AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'A' )
	
			--Modifica del 03/09/2002: aggiunto controllo sulla data decorrenza del docuemnto RAD
			AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))

			OPEN CUR_RAD
			FETCH NEXT FROM CUR_RAD INTO @IDDOC
			WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD',@IDDOC,'00000000','',@FIRMA,'')
			
				FETCH NEXT FROM CUR_RAD INTO @IDDOC
			END

			CLOSE CUR_RAD

			DEALLOCATE CUR_RAD

		END
	END

END
*/
--IF @TIPOMOV = 'D'
--MODIFICA DEL 05/01/2001: ANCHE PER LE SOSPENSIONI TRIS SONO TENUTE IN CONSIDERAZIONE LE RINUNCE
IF @TIPOMOV = 'D' OR @TIPOMOV = 'S'
BEGIN
	--SE ESISTE LA RINUNCIA, LA SUA DATA DEVE ESSERE MINORE O UGUALE ALLA DATA DI DOMANI
	SELECT @IDDOC = NULL
	SELECT @IDDOC = LSRRIN_GEV_KEY_DATA_INS + LSRRIN_GEV_KEY_ORA_INS
	 FROM LSRRIN_GEV
	WHERE LSRRIN_GEV_COD_LOTTO = @CODLTM
		AND LSRRIN_GEV_FLAG_ANAG = '1'
		AND LSRRIN_GEV_DATA_RIN <= CONVERT(CHAR,GETDATE() + 1 ,112)
		AND (LSRRIN_GEV_DATA_RIN_RIN IS NULL OR LSRRIN_GEV_DATA_RIN_RIN ='00000000' OR LSRRIN_GEV_DATA_RIN_RIN = '')
	
	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINS, @ORAINS, @CODSER, @TIPOMOV, '00000000', 'LSRRIN_GEV', @IDDOC, '00000000', '', @FIRMA, '')
	END
END
GO
