/****** Object:  StoredProcedure [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_LTM]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_LTM] 

@CODLTM 		VARCHAR(7),
@DATAORAINS	CHAR(16),
@TIPOPROVV		CHAR(1),
@DATAPROVV		CHAR(8),
@NUMPROVV		VARCHAR(14),
@DATADECOR		CHAR(8),
@NEWFLAG		CHAR(1),
@FIRMA		VARCHAR(17),
@NOTE		VARCHAR(255)


AS

DECLARE 

@MSGERR	VARCHAR(255),
@DATAINS	CHAR(8),
@ORAINS	CHAR(8)


SELECT @DATAINS = NULL
SELECT @ORAINS = NULL

SELECT @DATAINS = CONVERT(CHAR, GETDATE(), 112)

SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
			SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
			SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
			SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)


BEGIN TRANSACTION


---F101
EXEC ANA_ANNULLA_MOVIMENTAZIONE_F101 
@CODLTM, @DATAORAINS, @TIPOPROVV, @DATAPROVV, @NUMPROVV, @DATADECOR, @DATAINS, @ORAINS, @NEWFLAG, 'Y', NULL, @FIRMA, @NOTE

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_F101 - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

---TRIS
EXEC ANA_ANNULLA_MOVIMENTAZIONE_TRIS
@CODLTM, @DATAORAINS, @TIPOPROVV, @DATAPROVV, @NUMPROVV, @DATADECOR, @DATAINS, @ORAINS, @NEWFLAG, 'Y', NULL, @FIRMA, @NOTE

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_TRIS - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


---BOLLO
EXEC ANA_ANNULLA_MOVIMENTAZIONE_BOLLO
@CODLTM, @DATAORAINS, @TIPOPROVV, @DATAPROVV, @NUMPROVV, @DATADECOR, @DATAINS, @ORAINS, @NEWFLAG, 'Y', NULL, @FIRMA, @NOTE


IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_BOLLO - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


COMMIT TRANSACTION
GO
