/****** Object:  StoredProcedure [dbo].[ANA_TROVA_CONTRATTI_NON_ABBINATI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE    PROCEDURE [dbo].[ANA_TROVA_CONTRATTI_NON_ABBINATI]

@DATAINIZIORICERCA	CHAR(8),
@DATAFINERICERCA	CHAR(8),
@CODSERVIZIO	CHAR(2),
@NOMEDOC		VARCHAR(20)

AS

DECLARE	


@SQL			VARCHAR(6000),
@MSG			VARCHAR(255)

--******************************* GEV ******************************* 
IF @CODSERVIZIO = '02'
BEGIN
	IF @NOMEDOC = 'CON'  
	BEGIN

		SELECT 'CON' AS TIPO_DOCUMENTO, 
		 LSRCON_F101_KEY_ID_RICEV AS RICEV,
		  LSRCON_F101_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_F101_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_F101_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_F101_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_F101 
		 WHERE LSRCON_F101_TIPO_DOC = 'C' 
		 AND LSRCON_F101_KEY_DATA_INS >=  @DATAINIZIORICERCA 
		 AND LSRCON_F101_KEY_DATA_INS <= @DATAFINERICERCA 
		  AND LSRCON_F101_FLAG_ANAG = '0' ORDER BY 2
	END
	IF @NOMEDOC = 'CAS'  
	BEGIN
		SELECT 'CAS' AS TIPO_DOCUMENTO, 
		 LSRCON_F101_KEY_ID_RICEV AS RICEV,
		  LSRCON_F101_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_F101_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_F101_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_F101_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_F101 
		 WHERE LSRCON_F101_TIPO_DOC = 'A' 
		 AND LSRCON_F101_KEY_DATA_INS >=  @DATAINIZIORICERCA 
		 AND LSRCON_F101_KEY_DATA_INS <=  @DATAFINERICERCA 
		  AND LSRCON_F101_FLAG_ANAG = '0' ORDER BY 2
	END

	IF @NOMEDOC = 'FID'  
	BEGIN
		SELECT 'FID' AS TIPO_DOCUMENTO, 
		 LSRFID_F101_KEY_ID_RICEV AS RICEV,
		  LSRFID_F101_KEY_DATA_INS AS DATA_INS, 
		  LSRFID_F101_KEY_ORA_INS AS ORA_INS, 
		 LSRFID_F101_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRFID_F101_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA,
		 LSRFID_F101_ANNO_RIF AS ANNO_RIF
		 FROM LSRFID_F101 
		 WHERE  LSRFID_F101_FLAG_ANAG = '0'
		 AND LSRFID_F101_KEY_DATA_INS >=  @DATAINIZIORICERCA 
		 AND LSRFID_F101_KEY_DATA_INS <=  @DATAFINERICERCA
		   ORDER BY 2	
	END

	IF @NOMEDOC = 'APS'  
	BEGIN
		SELECT 'APS' AS TIPO_DOCUMENTO, 
		 LSRAPS_F101_KEY_ID_RICEV AS RICEV,
		  LSRAPS_F101_KEY_DATA_INS AS DATA_INS, 
		 LSRAPS_F101_KEY_ORA_INS AS ORA_INS, 
		 LSRAPS_F101_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRAPS_F101_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 LSRAPS_F101_ANNO_RIF AS ANNO_RIF 
		  FROM LSRAPS_F101 
		 WHERE LSRAPS_F101_FLAG_ANAG = '0' 
		 AND LSRAPS_F101_KEY_DATA_INS >= @DATAINIZIORICERCA 
		 AND LSRAPS_F101_KEY_DATA_INS <=  @DATAFINERICERCA 
		  ORDER BY 2	
	END

	IF @NOMEDOC = 'RAD'  
	BEGIN
		SELECT 'RAD' AS TIPO_DOCUMENTO,  
		 LSRRAD_KEY_ID_RICEV AS RICEV,
		  LSRRAD_KEY_DATA_INS AS DATA_INS, 
		  LSRRAD_KEY_ORA_INS AS ORA_INS, 
		 LSRRAD_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRAD_NOME AS NOME_CONTRAENTE, 
		 LSRRAD_FONTE AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRAD 
		 WHERE LSRRAD_TIPO_SERVIZIO = '02' 
		  AND LSRRAD_FLAG_ANAG = '0' 
		 AND LSRRAD_KEY_DATA_INS >=  @DATAINIZIORICERCA
		 AND LSRRAD_KEY_DATA_INS <= @DATAFINERICERCA 
		   ORDER BY 2	
	END

	IF @NOMEDOC = 'RIN'  
	BEGIN
		SELECT 'RIN' AS TIPO_DOCUMENTO, 
		 LSRRIN_KEY_ID_RICEV AS RICEV,
		  LSRRIN_KEY_DATA_INS AS DATA_INS, 
		 LSRRIN_KEY_ORA_INS AS ORA_INS, 
		 LSRRIN_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRIN_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRIN 
		 WHERE LSRRIN_CODICE_SERVIZIO = '02' 
		  AND LSRRIN_FLAG_ANAG = '0' 
		 AND LSRRIN_KEY_DATA_INS >= @DATAINIZIORICERCA 
		 AND LSRRIN_KEY_DATA_INS <= @DATAFINERICERCA 
		   ORDER BY 2	
	END

	--*************************************************************
	-- SE IL NOME DEL DOCUMENTO NON E' SPECIFICATO FACCIO VEDERE TUTTI I DOCUMENTI
	IF @NOMEDOC = ''
	BEGIN

		SELECT 'CON' AS TIPO_DOCUMENTO, 
		 LSRCON_F101_KEY_ID_RICEV AS RICEV,
		 LSRCON_F101_KEY_DATA_INS AS DATA_INS, 
		 LSRCON_F101_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_F101_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_F101_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_F101 
		 WHERE LSRCON_F101_TIPO_DOC = 'C' 
		 AND LSRCON_F101_KEY_DATA_INS >= @DATAINIZIORICERCA 
		 AND LSRCON_F101_KEY_DATA_INS <= @DATAFINERICERCA 
		  AND LSRCON_F101_FLAG_ANAG = '0' 
		  UNION    
		 SELECT 'CAS' AS TIPO_DOCUMENTO,  
		 LSRCON_F101_KEY_ID_RICEV AS RICEV, 
		   LSRCON_F101_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_F101_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_F101_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_F101_NOME AS NOME_CONTRAENTE,
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_F101 
		 WHERE LSRCON_F101_TIPO_DOC = 'A'
		 AND LSRCON_F101_KEY_DATA_INS >=  @DATAINIZIORICERCA 
		 AND LSRCON_F101_KEY_DATA_INS <= @DATAFINERICERCA 
		  AND LSRCON_F101_FLAG_ANAG = '0' 
		  UNION  
		 SELECT 'FID' AS TIPO_DOCUMENTO, 
		 LSRFID_F101_KEY_ID_RICEV AS RICEV,
		  LSRFID_F101_KEY_DATA_INS AS DATA_INS, 
		  LSRFID_F101_KEY_ORA_INS AS ORA_INS, 
		 LSRFID_F101_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRFID_F101_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 LSRFID_F101_ANNO_RIF AS ANNO_RIF 
		 FROM LSRFID_F101 
		 WHERE  LSRFID_F101_FLAG_ANAG = '0'
		 AND LSRFID_F101_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRFID_F101_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION    
		 SELECT 'APS' AS TIPO_DOCUMENTO, 
		 LSRAPS_F101_KEY_ID_RICEV AS RICEV,
		  LSRAPS_F101_KEY_DATA_INS AS DATA_INS, 
		  LSRAPS_F101_KEY_ORA_INS AS ORA_INS, 
		 LSRAPS_F101_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRAPS_F101_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 LSRAPS_F101_ANNO_RIF AS ANNO_RIF 
		  FROM LSRAPS_F101 
		 WHERE LSRAPS_F101_FLAG_ANAG = '0' 
		 AND LSRAPS_F101_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRAPS_F101_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION    
		 SELECT 'RAD' AS TIPO_DOCUMENTO, 
		 LSRRAD_KEY_ID_RICEV AS RICEV,
		  LSRRAD_KEY_DATA_INS AS DATA_INS, 
		  LSRRAD_KEY_ORA_INS AS ORA_INS, 
		 LSRRAD_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRAD_NOME AS NOME_CONTRAENTE, 
		 LSRRAD_FONTE AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRAD 
		 WHERE LSRRAD_TIPO_SERVIZIO = '02' 
		  AND LSRRAD_FLAG_ANAG = '0' 
		 AND LSRRAD_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRAD_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION  
		 SELECT 'RIN' AS TIPO_DOCUMENTO, 
		 LSRRIN_KEY_ID_RICEV AS RICEV,
		  LSRRIN_KEY_DATA_INS AS DATA_INS, 
		  LSRRIN_KEY_ORA_INS AS ORA_INS, 
		 LSRRIN_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRIN_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRIN 
		 WHERE LSRRIN_CODICE_SERVIZIO = '02' 
		  AND LSRRIN_FLAG_ANAG = '0' 
		 AND LSRRIN_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRIN_KEY_DATA_INS <= @DATAFINERICERCA
		 ORDER BY 1, 2 
	END  
END

--******************************* BOLLO *******************************
IF @CODSERVIZIO = '05'
BEGIN
	IF @NOMEDOC = 'CON'  
	BEGIN

		SELECT 'CON' AS TIPO_DOCUMENTO, LSRCON_BOLLO_KEY_ID_RICEV AS RICEV,
		LSRCON_BOLLO_KEY_DATA_INS AS DATA_INS, 
		LSRCON_BOLLO_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_BOLLO_COGNOME AS COGNOME_CONTRAENTE, 
		LSRCON_BOLLO_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		FROM LSRCON_BOLLO 
		WHERE LSRCON_BOLLO_TIPO_DOC = 'C' 
		AND LSRCON_BOLLO_KEY_DATA_INS >= @DATAINIZIORICERCA + '' 
	         AND LSRCON_BOLLO_KEY_DATA_INS <= @DATAFINERICERCA + '' 


		 AND LSRCON_BOLLO_FLAG_ANAG = '0' ORDER BY 2


	END
	IF @NOMEDOC = 'ADE'  
	BEGIN
		SELECT 'ADE' AS TIPO_DOCUMENTO, LSRCON_BOLLO_KEY_ID_RICEV AS RICEV,
		  LSRCON_BOLLO_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_BOLLO_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_BOLLO_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_BOLLO_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_BOLLO 
		 WHERE LSRCON_BOLLO_TIPO_DOC = 'A' 
		 AND LSRCON_BOLLO_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRCON_BOLLO_KEY_DATA_INS <= @DATAFINERICERCA
		  AND LSRCON_BOLLO_FLAG_ANAG = '0' ORDER BY 2
	END

	IF @NOMEDOC = 'RAD'  
	BEGIN
		SELECT 'RAD' AS TIPO_DOCUMENTO, LSRRAD_KEY_ID_RICEV AS RICEV,
		  LSRRAD_KEY_DATA_INS AS DATA_INS, 
		  LSRRAD_KEY_ORA_INS AS ORA_INS, 
		 LSRRAD_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRAD_NOME AS NOME_CONTRAENTE, 
		 LSRRAD_FONTE AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRAD 
		 WHERE LSRRAD_TIPO_SERVIZIO = '05' 
		  AND LSRRAD_FLAG_ANAG = '0' 
		 AND LSRRAD_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRAD_KEY_DATA_INS <= @DATAFINERICERCA
		   ORDER BY 2
	END

	IF @NOMEDOC = 'RIN'  
	BEGIN
		SELECT 'RIN' AS TIPO_DOCUMENTO, LSRRIN_KEY_ID_RICEV AS RICEV,
		  LSRRIN_KEY_DATA_INS AS DATA_INS, 
		  LSRRIN_KEY_ORA_INS AS ORA_INS, 
		 LSRRIN_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRIN_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRIN 
		 WHERE LSRRIN_CODICE_SERVIZIO = '05' 
		  AND LSRRIN_FLAG_ANAG = '0' 
		 AND LSRRIN_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRIN_KEY_DATA_INS <= @DATAFINERICERCA
		  ORDER BY 2
	END

	--*************************************************************
	-- SE IL NOME DEL DOCUMENTO NON E' SPECIFICATO FACCIO VEDERE TUTTI I DOCUMENTI
	IF @NOMEDOC = ''
	BEGIN

		SELECT 'CON' AS TIPO_DOCUMENTO, LSRCON_BOLLO_KEY_ID_RICEV AS RICEV,
		  LSRCON_BOLLO_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_BOLLO_KEY_ORA_INS AS ORA_INS,
		 LSRCON_BOLLO_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_BOLLO_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_BOLLO 
		 WHERE LSRCON_BOLLO_TIPO_DOC = 'C' 
		 AND LSRCON_BOLLO_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRCON_BOLLO_KEY_DATA_INS <= @DATAFINERICERCA
		  AND LSRCON_BOLLO_FLAG_ANAG = '0' 
		  UNION  
		 SELECT 'ADE' AS TIPO_DOCUMENTO, LSRCON_BOLLO_KEY_ID_RICEV AS RICEV,
		  LSRCON_BOLLO_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_BOLLO_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_BOLLO_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_BOLLO_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_BOLLO 
		 WHERE LSRCON_BOLLO_TIPO_DOC = 'A' 
		 AND LSRCON_BOLLO_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRCON_BOLLO_KEY_DATA_INS <= @DATAFINERICERCA
		  AND LSRCON_BOLLO_FLAG_ANAG = '0' 
		  UNION  
		 SELECT 'RAD' AS TIPO_DOCUMENTO, LSRRAD_KEY_ID_RICEV AS RICEV,
		  LSRRAD_KEY_DATA_INS AS DATA_INS, 
		  LSRRAD_KEY_ORA_INS AS ORA_INS, 
		 LSRRAD_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRAD_NOME AS NOME_CONTRAENTE, 
		 LSRRAD_FONTE AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRAD 
		 WHERE LSRRAD_TIPO_SERVIZIO = '05' 
		  AND LSRRAD_FLAG_ANAG = '0' 
		 AND LSRRAD_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRAD_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION    
		 SELECT 'RIN' AS TIPO_DOCUMENTO, LSRRIN_KEY_ID_RICEV AS RICEV,
		  LSRRIN_KEY_DATA_INS AS DATA_INS, 
		  LSRRIN_KEY_ORA_INS AS ORA_INS, 
		 LSRRIN_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRIN_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRIN 
		 WHERE LSRRIN_CODICE_SERVIZIO = '05' 
		  AND LSRRIN_FLAG_ANAG = '0' 
		 AND LSRRIN_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRIN_KEY_DATA_INS <= @DATAFINERICERCA
		  ORDER BY 1, 2

	END
END

--******************************* TRIS *******************************
IF @CODSERVIZIO = '08'
BEGIN
	IF @NOMEDOC = 'CON'  
	BEGIN

		SELECT 'CON' AS TIPO_DOCUMENTO,  LSRCON_TRIS_KEY_ID_RICEV AS RICEV,
		  LSRCON_TRIS_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_TRIS_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_TRIS_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_TRIS_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_TRIS 
		 WHERE LSRCON_TRIS_FLAG_ANAG = '0' 
		 AND LSRCON_TRIS_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRCON_TRIS_KEY_DATA_INS <= @DATAFINERICERCA
		  ORDER BY 2
	END


	IF @NOMEDOC = 'FID'  
	BEGIN
		SELECT  'FID' AS TIPO_DOCUMENTO, LSRFID_TRIS_KEY_ID_RICEV AS RICEV,
		  LSRFID_TRIS_KEY_DATA_INS AS DATA_INS, 
		  LSRFID_TRIS_KEY_ORA_INS AS ORA_INS, 
		 LSRFID_TRIS_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRFID_TRIS_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 LSRFID_TRIS_ANNO_RIF AS ANNO_RIF 
		 FROM LSRFID_TRIS 
		 WHERE LSRFID_TRIS_FLAG_ANAG = '0' 
		 AND LSRFID_TRIS_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRFID_TRIS_KEY_DATA_INS <= @DATAFINERICERCA
		  ORDER BY 2
	END

	IF @NOMEDOC = 'APS'  
	BEGIN
		SELECT 'APS' AS TIPO_DOCUMENTO, LSRAPS_TRIS_KEY_ID_RICEV AS RICEV,
		  LSRAPS_TRIS_KEY_DATA_INS AS DATA_INS, 
		 LSRAPS_TRIS_KEY_ORA_INS AS ORA_INS, 
		 LSRAPS_TRIS_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRAPS_TRIS_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		  FROM LSRAPS_TRIS 
		 WHERE LSRAPS_TRIS_FLAG_ANAG = '0' 
		 AND LSRAPS_TRIS_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRAPS_TRIS_KEY_DATA_INS <= @DATAFINERICERCA
		  ORDER BY 2
	END

	IF @NOMEDOC = 'RAD'  
	BEGIN
		SELECT 'RAD' AS TIPO_DOCUMENTO, LSRRAD_KEY_ID_RICEV AS RICEV,
		  LSRRAD_KEY_DATA_INS AS DATA_INS, 
		  LSRRAD_KEY_ORA_INS AS ORA_INS, 
		 LSRRAD_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRAD_NOME AS NOME_CONTRAENTE, 
		 LSRRAD_FONTE AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRAD 
		 WHERE LSRRAD_TIPO_SERVIZIO = '08' 
		  AND LSRRAD_FLAG_ANAG = '0' 
		 AND LSRRAD_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRAD_KEY_DATA_INS <= @DATAFINERICERCA
		  ORDER BY 2	
	END

	IF @NOMEDOC = 'RIN'  
	BEGIN
		SELECT 'RIN' AS TIPO_DOCUMENTO, LSRRIN_KEY_ID_RICEV AS RICEV,
		  LSRRIN_KEY_DATA_INS AS DATA_INS, 
		  LSRRIN_KEY_ORA_INS AS ORA_INS,
		 LSRRIN_COGNOME AS COGNOME_CONTRAENTE,
		 LSRRIN_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA,
		 '' AS ANNO_RIF 
		 FROM LSRRIN 
		 WHERE LSRRIN_CODICE_SERVIZIO = '08' 
		  AND LSRRIN_FLAG_ANAG = '0' 
		 AND LSRRIN_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRIN_KEY_DATA_INS <= @DATAFINERICERCA
		 ORDER BY 2
	END

	--*************************************************************
	-- SE IL NOME DEL DOCUMENTO NON E' SPECIFICATO FACCIO VEDERE TUTTI I DOCUMENTI
	IF @NOMEDOC = ''
	BEGIN
		SELECT 'CON' AS TIPO_DOCUMENTO,  LSRCON_TRIS_KEY_ID_RICEV AS RICEV,
		  LSRCON_TRIS_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_TRIS_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_TRIS_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_TRIS_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_TRIS 
		 WHERE LSRCON_TRIS_FLAG_ANAG = '0'
		 AND LSRCON_TRIS_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRCON_TRIS_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION   
		 SELECT  'FID' AS TIPO_DOCUMENTO, LSRFID_TRIS_KEY_ID_RICEV AS RICEV,
		  LSRFID_TRIS_KEY_DATA_INS AS DATA_INS, 
		  LSRFID_TRIS_KEY_ORA_INS AS ORA_INS, 
		 LSRFID_TRIS_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRFID_TRIS_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 LSRFID_TRIS_ANNO_RIF AS ANNO_RIF 
		 FROM LSRFID_TRIS 
		 WHERE LSRFID_TRIS_FLAG_ANAG = '0' 
		 AND LSRFID_TRIS_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRFID_TRIS_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION   
		 SELECT 'APS' AS TIPO_DOCUMENTO, LSRAPS_TRIS_KEY_ID_RICEV AS RICEV,
		  LSRAPS_TRIS_KEY_DATA_INS AS DATA_INS, 
		  LSRAPS_TRIS_KEY_ORA_INS AS ORA_INS, 
		 LSRAPS_TRIS_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRAPS_TRIS_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		  FROM LSRAPS_TRIS 
		 WHERE LSRAPS_TRIS_FLAG_ANAG = '0' 
		 AND LSRAPS_TRIS_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRAPS_TRIS_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION    
		 SELECT 'RAD' AS TIPO_DOCUMENTO, LSRRAD_KEY_ID_RICEV AS RICEV,
		  LSRRAD_KEY_DATA_INS AS DATA_INS, 
		  LSRRAD_KEY_ORA_INS AS ORA_INS, 
		 LSRRAD_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRAD_NOME AS NOME_CONTRAENTE, 
		 LSRRAD_FONTE AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRAD 
		 WHERE LSRRAD_TIPO_SERVIZIO = '08' 
		  AND LSRRAD_FLAG_ANAG = '0' 
		 AND LSRRAD_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRAD_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION  
		 SELECT 'RIN' AS TIPO_DOCUMENTO, LSRRIN_KEY_ID_RICEV AS RICEV,
		  LSRRIN_KEY_DATA_INS AS DATA_INS, 
		  LSRRIN_KEY_ORA_INS AS ORA_INS, 
		 LSRRIN_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRRIN_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRRIN 
		 WHERE LSRRIN_CODICE_SERVIZIO = '08' 
		  AND LSRRIN_FLAG_ANAG = '0' 
		 AND LSRRIN_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRRIN_KEY_DATA_INS <= @DATAFINERICERCA
		   ORDER BY 1, 2	

	END
END

--******************************* GRATTA & VINCI ******************************* 
IF @CODSERVIZIO = '09'
BEGIN


	IF @NOMEDOC = 'CON'  
	BEGIN

		SELECT 'CON' AS TIPO_DOCUMENTO, 
		 lsrcon_GeV_cod_lotto AS RICEV,
		  LSRCON_GEV_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_GEV_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_GEV_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_GEV_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_GEV 
		 WHERE LSRCON_GEV_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRCON_GEV_KEY_DATA_INS <= @DATAFINERICERCA
		  AND LSRCON_GEV_FLAG_ANAG = '0' ORDER BY 2
	END

	IF @NOMEDOC = 'FID'  
	BEGIN
		SELECT 'FID' AS TIPO_DOCUMENTO, 
		 lsrfid_GeV_cod_lotto AS RICEV,
		  LSRFID_GEV_KEY_DATA_INS AS DATA_INS, 
		  LSRFID_GEV_KEY_ORA_INS AS ORA_INS, 
		 LSRFID_GEV_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRFID_GEV_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 LSRFID_GEV_ANNO_RIF AS ANNO_RIF 
		 FROM LSRFID_GEV 
		 WHERE  LSRFID_GEV_FLAG_ANAG = '0'
		 AND LSRFID_GEV_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRFID_GEV_KEY_DATA_INS <= @DATAFINERICERCA
		   ORDER BY 2
	END

	IF @NOMEDOC = 'QUE'  
	BEGIN
		SELECT 'QST' AS TIPO_DOCUMENTO, 
		 lsrqst_GeV_cod_lotto AS RICEV,
		  LSRQST_GEV_KEY_DATA_INS AS DATA_INS, 
		  LSRQST_GEV_KEY_ORA_INS AS ORA_INS, 
		 LSRQST_GEV_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRQST_GEV_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRQST_GEV 
		 WHERE  LSRQST_GEV_FLAG_ANAG = '0'
		 AND LSRQST_GEV_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRQST_GEV_KEY_DATA_INS <= @DATAFINERICERCA
		  ORDER BY 2
	END


	--*************************************************************
	-- SE IL NOME DEL DOCUMENTO NON E' SPECIFICATO FACCIO VEDERE TUTTI I DOCUMENTI
	IF @NOMEDOC = ''
	BEGIN

		SELECT 'CON' AS TIPO_DOCUMENTO, 
		 lsrcon_GeV_cod_lotto AS RICEV,
		  LSRCON_GEV_KEY_DATA_INS AS DATA_INS, 
		  LSRCON_GEV_KEY_ORA_INS AS ORA_INS, 
		 LSRCON_GEV_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRCON_GEV_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		 FROM LSRCON_GEV 
		 WHERE LSRCON_GEV_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRCON_GEV_KEY_DATA_INS <= @DATAFINERICERCA
		  AND LSRCON_GEV_FLAG_ANAG = '0' 
		  UNION  
		 SELECT 'FID' AS TIPO_DOCUMENTO, 
		 lsrfid_GeV_cod_lotto AS RICEV,
		  LSRFID_GEV_KEY_DATA_INS AS DATA_INS, 
		  LSRFID_GEV_KEY_ORA_INS AS ORA_INS, 
		 LSRFID_GEV_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRFID_GEV_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 LSRFID_GEV_ANNO_RIF AS ANNO_RIF 
		 FROM LSRFID_GEV 
		 WHERE  LSRFID_GEV_FLAG_ANAG = '0'
		 AND LSRFID_GEV_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRFID_GEV_KEY_DATA_INS <= @DATAFINERICERCA
		  UNION    
		 SELECT 'QST' AS TIPO_DOCUMENTO, 
		 lsrqst_GeV_cod_lotto AS RICEV,
		  LSRQST_GEV_KEY_DATA_INS AS DATA_INS, 
		  LSRQST_GEV_KEY_ORA_INS AS ORA_INS, 
		 LSRQST_GEV_COGNOME AS COGNOME_CONTRAENTE, 
		 LSRQST_GEV_NOME AS NOME_CONTRAENTE, 
		 '' AS PROVENIENZA, 
		 '' AS ANNO_RIF 
		  FROM LSRQST_GEV 
		 WHERE LSRQST_GEV_FLAG_ANAG = '0' 
		 AND LSRQST_GEV_KEY_DATA_INS >= @DATAINIZIORICERCA
		 AND LSRQST_GEV_KEY_DATA_INS <= @DATAFINERICERCA
		 ORDER BY 1, 2 
	END  
END
GO
