/****** Object:  StoredProcedure [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_LOTTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_LOTTO] 

@CODLTM 		VARCHAR(7),
@TIPOPROVV		CHAR(1),
@DATAPROVV		CHAR(8),
@NUMPROVV		VARCHAR(14),
@DATADECOR		VARCHAR(8),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@NEWFLAG		CHAR(1),
@FIRMA		VARCHAR(17),
@NOTE		VARCHAR(255)

AS

DECLARE

@CHKLTM		VARCHAR(7),
@MSGERR		VARCHAR(255)


SELECT @CHKLTM = NULL

SELECT @CHKLTM = LSRSER_LOTTO_KEY_ID_RICEV
FROM LSRSER_LOTTO
WHERE
LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM AND
LSRSER_LOTTO_FLAG_VALIDITA = 'Y' AND
LSRSER_LOTTO_TIPO_PROVV = @TIPOPROVV AND
LSRSER_LOTTO_PROG_PROVV = @NUMPROVV AND
LSRSER_LOTTO_DATA_PROVV = @DATAPROVV

IF @CHKLTM IS NULL
BEGIN
	SELECT @MSGERR = 'NESSUNA MOVIMENTAZIONE LOTTO ESISTENTE PER I PARAMETRI INDICATI'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

SELECT @MSGERR = NULL

BEGIN TRANSACTION

UPDATE LSRSER_LOTTO SET 
LSRSER_LOTTO_FLAG_VALIDITA = @NEWFLAG, 
LSRSER_LOTTO_NOTE = @NOTE,
LSRSER_LOTTO_FIRMA = @FIRMA
WHERE 
LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM AND
LSRSER_LOTTO_FLAG_VALIDITA = 'Y' AND
LSRSER_LOTTO_TIPO_PROVV = @TIPOPROVV AND
LSRSER_LOTTO_PROG_PROVV = @NUMPROVV AND
LSRSER_LOTTO_DATA_PROVV = @DATAPROVV

	
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN AGGIORNAMENTO LSRSER_LOTTO - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

SELECT @MSGERR = NULL

UPDATE LSRRIC SET 
LSRRIC_FLAG_VALIDITA = @NEWFLAG,
LSRRIC_KEY_DATA_INS = @DATAINS,
LSRRIC_KEY_ORA_INS = @ORAINS
WHERE LSRRIC_KEY_ID_RICEV = @CODLTM
AND LSRRIC_TIPO_PROVV = @TIPOPROVV
AND LSRRIC_DATA_PROVV = @DATAPROVV
AND LSRRIC_PROG_PROVV = @NUMPROVV

	
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN AGGIORNAMENTO LSRRIC - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

SELECT @MSGERR = NULL

UPDATE LSRTIT SET 
LSRTIT_FLAG_VALIDITA = @NEWFLAG,
LSRTIT_KEY_DATA_INS = @DATAINS,
LSRTIT_KEY_ORA_INS = @ORAINS
WHERE LSRTIT_KEY_ID_RICEV = @CODLTM
AND LSRTIT_TIPO_PROVV = @TIPOPROVV
AND LSRTIT_DATA_PROVV = @DATAPROVV
AND LSRTIT_PROG_PROVV = @NUMPROVV

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN AGGIORNAMENTO LSRTIT - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

COMMIT TRANSACTION
GO
