/****** Object:  StoredProcedure [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_ANNULLA_MOVIMENTAZIONE_LIS] 

@CODLTM 		VARCHAR(7),
@DATAORAINS	CHAR(16),
@TIPOPROVV		CHAR(1),
@DATAPROVV		CHAR(8),
@NUMPROVV		VARCHAR(14),
@DATADECOR		CHAR(8),
@NEWFLAG		CHAR(1),
@FIRMA		VARCHAR(17),
@NOTE		VARCHAR(255)


AS

DECLARE 

@MSGERR	VARCHAR(255),
@DATAINS	CHAR(8),
@ORAINS	CHAR(8)


SELECT @DATAINS = NULL
SELECT @ORAINS = NULL

SELECT @DATAINS = CONVERT(CHAR, GETDATE(), 112)

SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
			SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
			SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
			SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)


BEGIN TRANSACTION


---SERVIZI AL CITTADINO
EXEC ANA_ANNULLA_MOVIMENTAZIONE_COMUNI
@CODLTM, @DATAORAINS, @TIPOPROVV, @DATAPROVV, @NUMPROVV, @DATADECOR, @DATAINS, @ORAINS, @NEWFLAG, 'Y', NULL, NULL, NULL, NULL, @FIRMA, @NOTE

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_COMUNI - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

---CANONI
EXEC ANA_ANNULLA_MOVIMENTAZIONE_CANONE
@CODLTM, @DATAORAINS, @TIPOPROVV, @DATAPROVV, @NUMPROVV, @DATADECOR, @DATAINS, @ORAINS, @NEWFLAG, 'Y', NULL, NULL, NULL, NULL, @FIRMA, @NOTE

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_CANONE - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


---RICARICHE TELEFONICHE
EXEC ANA_ANNULLA_MOVIMENTAZIONE_RICARICHE
@CODLTM, @DATAORAINS, @TIPOPROVV, @DATAPROVV, @NUMPROVV, @DATADECOR, @DATAINS, @ORAINS, @NEWFLAG, 'Y', NULL, NULL, NULL, NULL, @FIRMA, @NOTE


IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_RICARICHE - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

---CONTRIBUTO UNIFICATO
EXEC ANA_ANNULLA_MOVIMENTAZIONE_CONTRIBUTO
@CODLTM, @DATAORAINS, @TIPOPROVV, @DATAPROVV, @NUMPROVV, @DATADECOR, @DATAINS, @ORAINS, @NEWFLAG, 'Y', NULL, NULL, NULL, NULL, @FIRMA, @NOTE


IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_CONTRIBUTO - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

---BIGLIETTERIA
EXEC ANA_ANNULLA_MOVIMENTAZIONE_BIGLIETTERIA
@CODLTM, @DATAORAINS, @TIPOPROVV, @DATAPROVV, @NUMPROVV, @DATADECOR, @DATAINS, @ORAINS, @NEWFLAG, 'Y', NULL, NULL, NULL, NULL, @FIRMA, @NOTE


IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_BIGLIETTERIA - RICEVITORIA ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

COMMIT TRANSACTION
GO
