/****** Object:  StoredProcedure [dbo].[GEV_ESISTE_RICEVITORIA]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_ESISTE_RICEVITORIA] 

@CODLTM		VARCHAR(7) OUTPUT,
@CODAMM		VARCHAR(7) OUTPUT,
@CODSGI		VARCHAR(7) OUTPUT

AS 

DECLARE

@ASSOCIAZIONE	CHAR(1),
@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(100),
@RICEAPPO		VARCHAR(7)

SELECT @RICEAPPO = NULL

IF (LTRIM(RTRIM(@CODLTM)) = '' OR @CODLTM IS NULL) 
	AND (LTRIM(RTRIM(@CODAMM)) = '' OR @CODAMM IS NULL) 
	AND (LTRIM(RTRIM(@CODSGI)) = '' OR @CODSGI IS NULL) 
BEGIN
	SELECT @MSGERR = 'CODICI RICEVITORIA MANCANTI'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

IF LTRIM(RTRIM(@CODLTM)) <> '' AND LTRIM(RTRIM(@CODLTM)) IS NOT NULL
BEGIN
	SELECT @RICEAPPO = NULL

	SELECT @RICEAPPO = LSRRIC_KEY_ID_RICEV, @CODAMM = LSRRIC_COD_AMM
	FROM LSRRIC 
	WHERE LSRRIC_KEY_ID_RICEV = @CODLTM

	IF @RICEAPPO IS NULL
	BEGIN
		SELECT @MSGERR = 'CODICE LOTTOMATICA INESISTENTE - ' + @CODLTM
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE
	BEGIN
		SELECT @CODLTM = @RICEAPPO
	END

	EXEC @RESULT = GEV_CODIFICA_LTM_SGI @CODLTM, @CODSGI OUTPUT
	IF @RESULT <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE NELLA DECODIFICA DEL CODICE LOTTOMATICA - '  + @CODLTM
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

--IF @RICEAPPO IS NULL AND (LTRIM(RTRIM(@CODAMM)) <> '' AND @CODSGI IS NOT NULL)
IF @RICEAPPO IS NULL AND (LTRIM(RTRIM(@CODAMM)) <> '' )           -- - CHIARA       AND @CODSGI IS NOT NULL)
BEGIN
	SELECT @CODLTM = LSRRIC_KEY_ID_RICEV, @RICEAPPO = LSRRIC_COD_AMM
	FROM LSRRIC 
	WHERE LSRRIC_COD_AMM = @CODAMM

	IF @RICEAPPO IS NULL
	BEGIN
		SELECT @MSGERR = 'CODICE AMMINISTRATIVO INESISTENTE - ' + @CODAMM
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE
	BEGIN
		SELECT @CODAMM = @RICEAPPO
	END

	EXEC @RESULT = GEV_CODIFICA_LTM_SGI @CODLTM, @CODSGI OUTPUT
	IF @RESULT <> 0
	BEGIN
		SELECT @MSGERR = 'ERRORE NELLA DECODIFICA DEL CODICE LOTTOMATICA - '  + @CODLTM
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END


IF @RICEAPPO IS NULL AND (LTRIM(RTRIM(@CODSGI)) = '' OR @CODSGI IS NULL)
BEGIN
	SELECT @MSGERR = 'CODICI RICEVITORIA MANCANTI O ERRATI'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

IF @RICEAPPO IS NULL AND (LTRIM(RTRIM(@CODSGI)) <> '' AND @CODSGI IS NOT NULL)
BEGIN
	IF ISNUMERIC(@CODSGI) = 1
	BEGIN
		EXEC @RESULT = GEV_CODIFICA_SGI_LTM @CODSGI, @CODLTM OUTPUT
		IF @RESULT <> 0
		BEGIN
			SELECT @MSGERR = 'ERRORE NELLA DECODIFICA DEL CODICE SGI - '  + @CODSGI
			RAISERROR (@MSGERR, 16, 1)
			RETURN
		END
		ELSE
		BEGIN
		
			SELECT @CODAMM = NULL
			SELECT @CODAMM = LSRRIC_COD_AMM , @CODLTM = LSRRIC_KEY_ID_RICEV
			FROM LSRRIC
			WHERE LSRRIC_KEY_ID_RICEV = @CODLTM

			IF @CODAMM IS NULL
			BEGIN
				SELECT @MSGERR = 'RICEVITORIA INESISTENTE'
				RAISERROR (@MSGERR, 16, 1)
				RETURN
			END

		END
	END
	ELSE
	BEGIN
		SELECT @MSGERR = 'CODICE SGI NON CORRETTO - '  + @CODSGI
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END
GO
