/****** Object:  StoredProcedure [dbo].[ANA_REP_STAT_TITATT]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ANA_REP_STAT_TITATT] 
@NOMEQUERY         	CHAR(30)
AS 
BEGIN
	IF @NOMEQUERY = 'TITATT_GENERALE'
	BEGIN

		--* CONTRATTI TITOLARE ATTUALE ***********************
		--- GENERALE
		SELECT count(*) FROM lsrcon_gev
		WHERE  lsrcon_gev_FLAG_ANAG = '1' 
	END 
	ELSE
	IF @NOMEQUERY = 'TITATT_LOTTISTI'
	BEGIN

		-- LOTTISTI
		SELECT COUNT(*) FROM lsrcon_gev
		WHERE  LSRCON_GEV_KEY_ID_RICEV LIKE '3%'
		AND lsrcon_gev_FLAG_ANAG = '1' 

	END 
	ELSE
	IF @NOMEQUERY = 'TITATT_TOTORICEVITORI'
	BEGIN

		--- TOTORICEVITORI
		SELECT COUNT(*) FROM lsrcon_gev
		WHERE LSRCON_GEV_KEY_ID_RICEV LIKE '1%'
		AND lsrcon_gev_FLAG_ANAG = '1' 

	END 
	ELSE
	IF @NOMEQUERY = 'TITATT_POSGIALLO'
	BEGIN

		--- POS GIALLO
		SELECT COUNT(*) FROM lsrcon_gev
		WHERE LSRCON_GEV_KEY_ID_RICEV LIKE '9%'
		AND lsrcon_gev_FLAG_ANAG = '1' 

	END 
	ELSE
	IF @NOMEQUERY = 'TITATT_POSMARRONE'
	BEGIN

		--- POS MARRONE
		SELECT COUNT(*) FROm lsrcon_gev
		WHERE  LSRCON_GEV_KEY_ID_RICEV LIKE '4%'
		AND lsrcon_gev_FLAG_ANAG = '1' 

	END 
	ELSE
	IF @NOMEQUERY = 'TITATT_LOTTEL'
	BEGIN

		--- LOTTERIE TELEMATICHE
		SELECT COUNT(*) FROM lsrcon_gev
		WHERE lsrcon_gev_COD_LOTTO  LIKE 'LI%'
		AND lsrcon_gev_FLAG_ANAG = '1'

	END 
END
GO
