/****** Object:  StoredProcedure [dbo].[Report_ricevitorie_e_documenti_inviati]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE	PROCEDURE [dbo].[Report_ricevitorie_e_documenti_inviati] 
	--@DATA		 	CHAR(8),
	@SERVIZIO		CHAR(2),
	@CODRICEV		CHAR(6),
	@SIGLAPROV		CHAR(2),
	@COMUNE			CHAR(20),
	@REGIONE		CHAR(2),
	@RUOTA			CHAR(2),
	@STATOSERVIZIO		CHAR(2),
	@FLAG_BRIEF		CHAR(1),
	@XML 			CHAR(1),
	@ESITO 			INT OUT

AS
DECLARE  @TIPOSTATO CHAR(1)

SELECT @ESITO = 0

--IF (@DATA IS NULL) OR (RTRIM(LTRIM(@DATA)) = '')
--BEGIN
	--SELECT @ESITO = 9
	--RAISERROR ('MANCA LA DATA',16,1)
	--RETURN @ESITO
--	SELECT @DATA = convert(char(8),getdate(),112)
--END

IF (@SERVIZIO IS NULL) OR (RTRIM(LTRIM(@SERVIZIO)) = '')
BEGIN
    SELECT @ESITO = 9
    RAISERROR ('MANCA IL NOME DEL SERVIZIO',16,1)
    RETURN @ESITO
END

IF (@SIGLAPROV IS NULL) OR (RTRIM(LTRIM(@SIGLAPROV)) = '')
BEGIN
    SELECT @SIGLAPROV = NULL
END
-- SE LA SIGLA DELLA PROVINCIA NON E' NULLA, 
-- METTO A NULL LA SIGLA DELLA REGIONE
ELSE
BEGIN
	SELECT @REGIONE = NULL
END

IF (@REGIONE IS NULL) OR (RTRIM(LTRIM(@REGIONE)) = '')
BEGIN
    SELECT @REGIONE = NULL
END

IF (@comune IS NULL) OR (RTRIM(LTRIM(@comune)) = '')
BEGIN
    SELECT @comune = NULL
END

IF (@ruota IS NULL) OR (RTRIM(LTRIM(@ruota)) = '')
BEGIN
    SELECT @ruota = NULL
END



/*
IF (@SERVIZIO) = '01' 
BEGIN
	EXEC [Anaconda].[dbo].[Report_ricevitorie_e_documenti_inviati_LOTTO] @DATA, @SERVIZIO, @CODRICEV, @SIGLAPROV, @COMUNE, @REGIONE, @RUOTA, @STATOSERVIZIO, @FLAG_BRIEF, @XML, @ESITO OUTPUT
END
ELSE 
*/

IF (@SERVIZIO) = '02' 
BEGIN
	EXEC [Anaconda].[dbo].[Report_ricevitorie_e_documenti_inviati_F101] 
--@DATA, 
@SERVIZIO, @CODRICEV, @SIGLAPROV, @COMUNE, @REGIONE, @RUOTA, @STATOSERVIZIO, @FLAG_BRIEF, @XML, @ESITO OUTPUT
END
ELSE IF (@SERVIZIO) = '05' 
BEGIN
	EXEC [Anaconda].[dbo].[Report_ricevitorie_e_documenti_inviati_BOLLO] 
--@DATA, 
@SERVIZIO, @CODRICEV, @SIGLAPROV, @COMUNE, @REGIONE, @RUOTA, @STATOSERVIZIO, @FLAG_BRIEF, @XML, @ESITO OUTPUT
END
ELSE IF (@SERVIZIO) = '08' 
BEGIN
	EXEC [Anaconda].[dbo].[Report_ricevitorie_e_documenti_inviati_TRIS] 
--@DATA, 
@SERVIZIO, @CODRICEV, @SIGLAPROV, @COMUNE, @REGIONE, @RUOTA, @STATOSERVIZIO, @FLAG_BRIEF, @XML, @ESITO OUTPUT
END
ELSE
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('SERVIZIO ERRATO O NON PREVISTO',16,1)
	RETURN @ESITO
END

SET QUOTED_IDENTIFIER OFF
GO
