/****** Object:  StoredProcedure [dbo].[VARIAZIONE_RAD_ST]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[VARIAZIONE_RAD_ST]  

	@RICEV 			CHAR(6),
	@TIPOMOVIMENTAZIONE	CHAR(1),
	@FONTE			CHAR(1),  
	@FIRMADOC 			CHAR(17),
	@NOMEFILE			VARCHAR(255),
	@DATAINVIODOC		CHAR(8),
	@DATADOC			CHAR(8),
	@NUMPROTDOC		CHAR(25),
	@STATODOC			CHAR(1),
	@CAUSALE			CHAR(2),
	@ASSOCIAZIONE		CHAR(1),
	@COGNOME			CHAR(24),
	@NOME			CHAR(20),
	@NOTE			CHAR(100),
	@FLAGANAG			CHAR(1),
	@FKDATAINSTIT		CHAR(8),
	@FKORAINSTIT		CHAR(8),

	@KEYDATAINSDOC	CHAR(8),
	@KEYORAINSDOC	CHAR(8),
	@ABBINATO 		CHAR(1),

	@FIRMA			CHAR(17),
	@MSGERR 			VARCHAR(100) OUTPUT

 AS

DECLARE 	

@APPORICEV		CHAR(6),
@DATAOGGI   		CHAR(8),
@ORAOGGI  		CHAR(8),
@COGNOMETIT	CHAR(24),
@NOMETIT		CHAR(20),
@FLAGANAGTIT	CHAR(1),
@DATAINSTIT		CHAR(8),
@ORAINSTIT		CHAR(8),
@TIPOPREC 		CHAR(1),
@TIPOPROVV		CHAR(1),
@TITTROVATO   	CHAR(1),
@FLAGOK 		CHAR(1),
@CHKRICEV		CHAR(6)

SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)

--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL ABBINATO = '0' E FLAGANAG è <>0 VERIFICO CHE NON SIA GIà PRESENTE UN RAD PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 2) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT

SELECT @CHKRICEV = NULL

SELECT @CHKRICEV = LSRTIT_CONI_KEY_ID_RICEV FROM LSRTIT_CONI
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE'
	RETURN
END


--*************************************************************************
--           CONTROLLO 1
--*************************************************************************
/*
IF (@ABBINATO = '0' AND @FLAGANAG <> '0')
BEGIN

	SELECT @APPORICEV = LSRRAD_ST_KEY_ID_RICEV 
	FROM LSRRAD_ST
	WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEV
		AND LSRRAD_ST_fk_data_ins_tit  =@FKDATAINSTIT
		AND LSRRAD_ST_fk_ORa_ins_tit = @FKORAINSTIT

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +'PER LA RICEVITORIA ESISTE UN RAD ABBINATO - RAD NON ACQUISITO'
		RETURN
	END
END
*/
--*************************************************************************
--           CONTROLLO 2
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_CONI_COGNOME , @NOME = LSRTIT_CONI_NOME
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 


--*************************************************************************
--           CONTROLLO 3
--*************************************************************************

IF @FLAGANAG <> '0' 
BEGIN
	SELECT  @FLAGANAG = LSRTIT_CONI_FLAG_ANAG
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 

IF @FLAGANAG = '0' 
BEGIN
	SELECT @FKDATAINSTIT = NULL	
	SELECT @FKORAINSTIT = NULL	
END


--*************************************************************************
--           IL RECORD VIENE INSERITO SU LSRRAD_ST
--*************************************************************************
UPDATE LSRRAD_ST 
SET	
	LSRRAD_ST_key_data_ins = @DATAOGGI,                 
	LSRRAD_ST_key_ora_ins = @ORAOGGI,                  
	LSRRAD_ST_tipo_movimentazione = @TIPOMOVIMENTAZIONE,
	LSRRAD_ST_fonte = @FONTE,  
	LSRRAD_ST_firma_doc = @FIRMADOC,	
	LSRRAD_ST_data_decor = @DATADOC,	
	LSRRAD_ST_data_doc = @DATADOC,	
	LSRRAD_ST_data_invio_doc = @DATAINVIODOC,	
	LSRRAD_ST_num_prot_doc = @NUMPROTDOC,	
	LSRRAD_ST_cod_associazione = @ASSOCIAZIONE,	
	LSRRAD_ST_causale_lottomatica = @CAUSALE, 
	LSRRAD_ST_stato = @STATODOC,	
	LSRRAD_ST_cognome = @COGNOME,	
	LSRRAD_ST_nome = @NOME	,	
	LSRRAD_ST_note = @NOTE,	
	LSRRAD_ST_flag_anag = @FLAGANAG,	
	LSRRAD_ST_fk_data_ins_tit = @FKDATAINSTIT,	
	LSRRAD_ST_fk_ora_ins_tit = @FKORAINSTIT,	
	LSRRAD_ST_firma = @FIRMA	
WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEV
	AND LSRRAD_ST_KEY_DATA_INS = @KEYDATAINSDOC
	AND LSRRAD_ST_KEY_ORA_INS = @KEYORAINSDOC
 
IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO RAD - RAD NON ACQUISITO'
	RETURN
END
ELSE
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +'RAD VARIATO  CORRETTAMENTE'
	RETURN
END
GO
