/****** Object:  StoredProcedure [dbo].[Report_attivabili_TRIS_con_fidejussione]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE        PROCEDURE [dbo].[Report_attivabili_TRIS_con_fidejussione] 
	@FLAGLOTTO 	CHAR(1),
	@FILE		CHAR(255)  OUTPUT

AS

DECLARE

@RICEV		CHAR(6),
@RICERIN	CHAR(6),
@RICEAPPO	CHAR(7),
@RICESER	CHAR(6),
@RICEFID	CHAR(6),
@RICEAPS	CHAR(6),
@STATOOGGI	CHAR(1),
@STATODOM	CHAR(1),
@ORAINS		CHAR(8),
@DATAINS	CHAR(8),
@DATARINRIN	CHAR(8),
@NOMEFILE	CHAR(100),
@NOMEJOB	CHAR(6),
@STATOLOT	CHAR(1),
@FLAGCANONE	CHAR(1),
@NUMERR 	varchar(4),
@MSGERR 	varchar(50),
@PATHID		INT



SELECT @PATHID = 80
SELECT @DATAINS = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @NOMEFILE ='ATTIVABILI_TRIS_'+@DATAINS+'.txt'
SELECT @NOMEJOB = 'NO_LOG'
SELECT @FILE = 'NESSUN RECORD SCRITTO'

--CANCELLO IL FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB

DECLARE CUR_CON CURSOR FOR
SELECT DISTINCT (LSRFID_TRIS_KEY_ID_RICEV) 
FROM LSRFID_TRIS 
WHERE LSRFID_TRIS_ANNO_RIF = CONVERT(CHAR(4),GETDATE(),112) 
AND LSRFID_TRIS_FLAG_ANAG = '1'
AND  LSRFID_TRIS_KEY_ID_RICEV IN  (
	SELECT DISTINCT (LSRCON_TRIS_KEY_ID_RICEV) 
	FROM LSRCON_TRIS 
	WHERE LSRCON_TRIS_FLAG_ANAG = '1'
	)

OPEN CUR_CON 
FETCH NEXT FROM CUR_CON INTO @RICEV 
WHILE @@FETCH_STATUS = 0 
BEGIN

	SELECT @RICESER = NULL

	SELECT @RICESER = LSRSER_TRIS_KEY_ID_RICEV 
	FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
	GROUP BY LSRSER_TRIS_KEY_ID_RICEV
	HAVING SUM (CONVERT(INT,LSRSER_TRIS_STATO)) = 0

	IF @RICESER <> '' OR @RICESER IS NOT NULL OR @RICESER <> ' '
	BEGIN
		SELECT @RICERIN = NULL

		--VERIFICO SE CI SONO RINUNCE AL SERVIZIO
		SELECT @RICERIN = LSRRIN_KEY_ID_RICEV FROM LSRRIN
		WHERE LSRRIN_KEY_ID_RICEV = @RICEV
		AND LSRRIN_CODICE_SERVIZIO = '08'
		AND LSRRIN_FLAG_ANAG = '1'

		IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' '
		BEGIN
			SELECT @STATOLOT = NULL

			--CONTROLLO LO STATO DEL LOTTO
			SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
			WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
			AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
			AND LSRSER_LOTTO_DATA_DECOR =
			(
				SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
				FROM LSRSER_LOTTO
				WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
				AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
				AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE(),112)
			)

			IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
			BEGIN
				EXECUTE MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV,  @NOMEJOB
				SELECT @FILE = @NOMEFILE
			END

		END
	END
	FETCH NEXT FROM CUR_CON		
	INTO @RICEV


END

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
