/****** Object:  StoredProcedure [dbo].[Report_riattivabili_F101_con_fidejussione]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE      PROCEDURE [dbo].[Report_riattivabili_F101_con_fidejussione] 
	@FLAGLOTTO 	CHAR(1),
	@FILE		CHAR(255)  OUTPUT

AS

DECLARE

@RICEV		CHAR(6),
@RICERIN	CHAR(6),
@RICEAPPO	CHAR(7),
@RICESER	CHAR(6),
@RICEFID	CHAR(6),
@RICEAPS	CHAR(6),
@STATOOGGI	CHAR(1),
@STATODOM	CHAR(1),
@ORAINS		CHAR(8),
@DATAINS	CHAR(8),
@DATARINRIN	CHAR(8),
@NOMEFILE	CHAR(100),
@NOMEJOB	CHAR(6),
@STATOLOT	CHAR(1),
@FLAGCANONE	CHAR(1),
@NUMERR 	varchar(4),
@MSGERR 	varchar(50),
@PATHID		INT



SELECT @PATHID = 80
SELECT @DATAINS = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @NOMEFILE ='RIATTIVABILI_F101_'+@DATAINS+'.txt'
SELECT @NOMEJOB = 'NO_LOG'
SELECT @FILE = 'NESSUN RECORD SCRITTO'

--CANCELLO IL FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB

DECLARE CUR_CON CURSOR FOR
SELECT DISTINCT (LSRFID_F101_KEY_ID_RICEV) 
FROM LSRFID_F101 
WHERE LSRFID_F101_ANNO_RIF = CONVERT(CHAR(4),GETDATE(),112) 
AND LSRFID_F101_FLAG_ANAG = '1'
AND  LSRFID_F101_KEY_ID_RICEV IN  (
	SELECT DISTINCT (LSRCON_F101_KEY_ID_RICEV) 
	FROM LSRCON_F101 
	WHERE LSRCON_F101_TIPO_DOC = 'C' 
		AND LSRCON_F101_FLAG_ANAG = '1'
	)

OPEN CUR_CON 
FETCH NEXT FROM CUR_CON INTO @RICEV 
WHILE @@FETCH_STATUS = 0 
BEGIN

	SELECT @RICERIN = NULL
	SELECT @DATARINRIN = NULL

	--VERIFICO SE CI SONO RINUNCE AL SERVIZIO E SE E' IMPOSTATA LA
	--DATA DELLA RINUNCIA DELLA RINUNCIA

	SELECT @RICERIN = LSRRIN_KEY_ID_RICEV, 
		@DATARINRIN = LSRRIN_DATA_RINUNCIA_RINUNCIA
	FROM LSRRIN
	WHERE LSRRIN_KEY_ID_RICEV = @RICEV
		AND LSRRIN_CODICE_SERVIZIO = '02'
		AND LSRRIN_FLAG_ANAG = '1'


	IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' ' OR (@DATARINRIN <>''  AND @DATARINRIN <>'00000000' AND @DATARINRIN IS NOT NULL)
	BEGIN

		SELECT @STATODOM = NULL
		SELECT @STATOOGGI = NULL
		SELECT @RICESER = NULL

		SELECT @STATODOM = LSRSER_F101_STATO
		FROM LSRSER_F101
		WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
		AND LSRSER_F101_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
		AND LSRSER_F101_FLAG_VALIDITA = 'Y'

		IF @STATODOM = '' OR @STATODOM IS NULL
		BEGIN
			SELECT @STATOOGGI = LSRSER_F101_STATO
			FROM LSRSER_F101
			WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
			AND LSRSER_F101_DATA_DECOR =
				(SELECT MAX(LSRSER_F101_DATA_DECOR) FROM LSRSER_F101
				WHERE LSRSER_F101_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
					AND LSRSER_F101_KEY_ID_RICEV = @RICEV
					AND LSRSER_F101_FLAG_VALIDITA = 'Y'
				)
				AND LSRSER_F101_FLAG_VALIDITA = 'Y'
			
			IF @STATOOGGI = '2'
			BEGIN
				SELECT @STATOLOT = NULL
				--CONTROLLO LO STATO DEL LOTTO A DOMANI
				SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
				WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
				--AND LSRSER_LOTTO_FT_VOS <> '00000000'
				AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
				AND LSRSER_LOTTO_DATA_DECOR =
				(
					SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
					FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					--AND LSRSER_LOTTO_FT_VOS <> '00000000'
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
				)

				IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
				BEGIN
					EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB
					SELECT @FILE = @NOMEFILE
				END
			END
		END
	
	END
	FETCH NEXT FROM CUR_CON		
	INTO @RICEV

END

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
