/****** Object:  StoredProcedure [dbo].[Report_riattivabili_bollo_canone]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE           PROCEDURE [dbo].[Report_riattivabili_bollo_canone] 
	@CANONE		CHAR(1) = '1',
	@FLAGLOTTO 	CHAR(1) = '1',
	@FILE		VARCHAR(255) OUTPUT

AS

DECLARE

@RICEV		CHAR(6),
@RICERIN	CHAR(6),
@RICEAPPO	CHAR(7),
@RICESER	CHAR(6),
@RICEFID	CHAR(6),
@RICEAPS	CHAR(6),
@STATOOGGI	CHAR(1),
@STATODOM	CHAR(1),
@ORAINS		CHAR(8),
@DATAINS	CHAR(8),
@DATARINRIN	CHAR(8),
@NOMEFILE	VARCHAR(255),
@NOMEJOB	CHAR(6),
@STATOLOT	CHAR(1),
@FLAGCANONE	CHAR(1),
@NUMERR 	VARCHAR(4),
@MSGERR 	VARCHAR(50),
@PATHID		INT


SELECT @PATHID = 80
--A SECONDA DEL VALORE DEL CAMPO IN INPUT CREO IL NOME DEL
--FILE DI 
SELECT @DATAINS = CONVERT (VARCHAR(10), GETDATE(),112)
IF @CANONE = '1' 
BEGIN 
	SELECT @CANONE = 'S'
END
ELSE
BEGIN 
	SELECT @CANONE = 'N'
END

IF @CANONE = 'N'
BEGIN
	SELECT @NOMEFILE ='BOLLO_CANONE_NO_'+@DATAINS+'.txt'
END
ELSE
BEGIN
	SELECT @NOMEFILE ='BOLLO_CANONE_SI_'+@DATAINS+'.txt'
END
SELECT @FILE = 'NESSUN RECORD SCRITTO'

SELECT @NOMEJOB = 'NO_LOG'

--CANCELLO IL FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB


DECLARE CUR_CON CURSOR FOR
SELECT DISTINCT(LSRRAD_KEY_ID_RICEV) 
FROM LSRRAD A 
WHERE ((LSRRAD_FONTE = 'R' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R') 
	OR 
	(LSRRAD_FONTE = 'L' AND LSRRAD_TIPO_MOVIMENTAZIONE = 'R')) 
	AND LSRRAD_TIPO_SERVIZIO = '05' 
	AND LSRRAD_FLAG_ANAG = '1'   
	AND LSRRAD_DATA_INVIO_DOC > 
		(SELECT VAR = CASE WHEN(MAX(lsrrad_data_invio_doc)) IS NULL THEN '00000000' 
		ELSE (MAX(lsrrad_data_invio_doc)) END 
		FROM LSRRAD B 
		 WHERE LSRRAD_FLAG_ANAG = '1' 
			AND LSRRAD_TIPO_SERVIZIO = '05' 
			AND LSRRAD_FLAG_ANAG = '1' 
			AND A.LSRRAD_KEY_ID_RICEV = B.LSRRAD_KEY_ID_RICEV 
			AND LSRRAD_TIPO_MOVIMENTAZIONE <> 'R' )
	AND LSRRAD_DATA_INVIO_DOC >= 
		(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO D 
		WHERE LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y' 
		AND D.LSRSER_BOLLO_KEY_ID_RICEV = A.LSRRAD_KEY_ID_RICEV ) 			
		AND lsrrad_data_decor <= (convert(char(8),getdate() + 1,112))
OPEN CUR_CON 
FETCH NEXT FROM CUR_CON INTO @RICEV 
WHILE @@FETCH_STATUS = 0 
BEGIN

	SELECT @RICERIN = NULL
	SELECT @DATARINRIN = NULL

	--VERIFICO SE CI SONO RINUNCE AL SERVIZIO E SE E' IMPOSTATA LA
	--DATA DELLA RINUNCIA DELLA RINUNCIA

	SELECT @RICERIN = LSRRIN_KEY_ID_RICEV, 
		@DATARINRIN = LSRRIN_DATA_RINUNCIA_RINUNCIA
	FROM LSRRIN
	WHERE LSRRIN_KEY_ID_RICEV = @RICEV
		AND LSRRIN_CODICE_SERVIZIO = '05'
		AND LSRRIN_FLAG_ANAG = '1'


	IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' ' 
        OR (@DATARINRIN <>''  AND @DATARINRIN <>'00000000' AND @DATARINRIN IS NOT NULL)
	BEGIN


		SELECT @STATODOM = NULL
		SELECT @STATOOGGI = NULL
		SELECT @RICESER = NULL

		SELECT @STATODOM = LSRSER_BOLLO_STATO
		FROM LSRSER_BOLLO
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRSER_BOLLO_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'

		IF @STATODOM = '' OR @STATODOM IS NULL
		BEGIN


			SELECT @STATOOGGI = LSRSER_BOLLO_STATO
			FROM LSRSER_BOLLO
			WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
			AND LSRSER_BOLLO_DATA_DECOR =
				(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO
				WHERE LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
					AND LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
					AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
				)
				AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
			

			IF @STATOOGGI = '2'
			BEGIN


				SELECT @STATOLOT = NULL
				--CONTROLLO LO STATO DEL LOTTO A DOMANI
				SELECT @STATOLOT = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
				WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
				--AND LSRSER_LOTTO_FT_VOS <> '00000000'
				AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
				AND LSRSER_LOTTO_DATA_DECOR =
				(
					SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
					FROM LSRSER_LOTTO
					WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
					--AND LSRSER_LOTTO_FT_VOS <> '00000000'
					AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() +1,112)
				)

				IF (@FLAGLOTTO = '1' AND @STATOLOT = 'A') OR (@FLAGLOTTO = '0' AND LTRIM(RTRIM(@STATOLOT)) = '') 
				BEGIN

					SELECT @RICEAPPO = NULL
					SELECT @RICEAPPO = @RICEV + 'N'
					SELECT @FLAGCANONE = ''
					EXECUTE Calcola_Addebito_Canone_Bollo  @RICEV, @FLAGCANONE output, @NUMERR OUTPUT , @MSGERR OUTPUT 
					IF @NUMERR <> '0000'
					BEGIN
		                        	SELECT @FLAGCANONE = ''
					END
					IF (@CANONE = 'N' AND @FLAGCANONE = 'N') OR (@CANONE = 'Y' AND @FLAGCANONE = 'Y')
					BEGIN
						SELECT @RICEAPPO = @RICEV + @FLAGCANONE
						SELECT @FILE = @NOMEFILE
						EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEAPPO, @NOMEJOB
					END
				END
			END
		END
	
	END
	FETCH NEXT FROM CUR_CON		
	INTO @RICEV

END

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
