/****** Object:  StoredProcedure [dbo].[Report_Movimentazioni_per_periodo_di_tempo_LOTTO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
/****** Object:  Stored Procedure dbo.Report_Movimentazioni_per_periodo_di_tempo_LOTTO    Script Date: 16/10/2003 10.27.10 ******/





CREATE	PROCEDURE [dbo].[Report_Movimentazioni_per_periodo_di_tempo_LOTTO] 
	@DATAINIZIOPERIODO 	CHAR(8),
	@DATAFINEPERIODO 	CHAR(8),
	@TIPOMOVIMENTAZIONE	CHAR(1),
	@SERVIZIO		CHAR(2),
	@SIGLAREG		CHAR(2),
	@SIGLAPROV		CHAR(2),
	@XML 			CHAR(1),
	@ESITO 			INT OUT

AS
DECLARE  @TIPOSTATO CHAR(1)

SELECT @ESITO = 0

IF (@SERVIZIO IS NULL) OR (RTRIM(LTRIM(@SERVIZIO)) = '')
BEGIN
    SELECT @ESITO = 9
    RAISERROR ('MANCA IL NOME DEL SERVIZIO',16,1)
    RETURN @ESITO
END


if (@SIGLAPROV is null) or (rtrim(ltrim(@SIGLAPROV)) = '')
begin
    select @SIGLAPROV = null
end
-- SE LA SIGLA DELLA PROVINCIA NON E' NULLA, 
-- METTO A NULL LA SIGLA DELLA REGIONE
ELSE
BEGIN
	SELECT @SIGLAREG = NULL
END

if (@SIGLAREG is null) or (rtrim(ltrim(@SIGLAREG)) = '')
begin
    select @SIGLAREG = null
end

IF (@DATAINIZIOPERIODO IS NULL) OR (RTRIM(LTRIM(@DATAINIZIOPERIODO)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA LA DATA DI INIZIO PERIODO',16,1)
	RETURN @ESITO
END

IF (@DATAFINEPERIODO IS NULL) OR (RTRIM(LTRIM(@DATAFINEPERIODO)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA LA DATA DI FINE PERIODO',16,1)
	RETURN @ESITO
END

IF (@TIPOMOVIMENTAZIONE IS NULL) OR (RTRIM(LTRIM(@TIPOMOVIMENTAZIONE)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA IL TIPO DELLA MOVIMENTAZIONE',16,1)
	RETURN @ESITO
END
ELSE
BEGIN
	SELECT @TIPOSTATO =@TIPOMOVIMENTAZIONE
END

------PRINT ' - TIPOSTATO --> ' + @TIPOSTATO

--*******************************************
--IL RISULTATO DEVE ESSERE PRODOTTO IN FORMATO XML
--*******************************************
IF (@XML = '1')
BEGIN 
--*******************************************
-- CONTROLLO SIGLAPROV NOT NULL
--*******************************************
	IF @SIGLAPROV IS NOT NULL
	BEGIN
		--***********************
		--    	LOTTO
		--***********************
		IF (@SERVIZIO = '01')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
					
				FOR XML RAW
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_LOTTO C, LSRTIT A, LSRRIC B
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_TIPO_PROVV='I'
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
					
				FOR XML RAW
			END		
			ELSE
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRSER_LOTTO_TIPO_PROVV = @TIPOSTATO
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
					
				FOR XML RAW
			END
		END
	END
-- ***********************************************
-- CONTROLLO SIGLAREG NOT NULL
-- ***********************************************
	ELSE IF (@SIGLAREG IS NOT NULL)
	BEGIN
		--***********************
		--    	LOTTO
		--***********************
		IF (@SERVIZIO = '01')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM  LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
				FOR XML RAW
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_TIPO_PROVV='I'
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
				FOR XML RAW
			END		
			ELSE
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRSER_LOTTO_TIPO_PROVV = @TIPOSTATO
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
				FOR XML RAW
			END
		END
	END
-- ***********************************************
-- SIGLAREG & SIGLAPROV NULL
-- ***********************************************
	ELSE
	BEGIN
		--***********************
		--    	LOTTO
		--***********************
		IF (@SERVIZIO = '01')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN

				select 					
					lsrser_LOTTO_key_id_ricev as [cod_lottomatica], 
					lsrric_cod_amm as [cod_amm],
					lsrser_LOTTO_key_data_ins as [data_acquisizione], 
					rtrim(ltrim(lsrric_indirizzo)) as [indirizzo],
					lsrric_cap as [cap],
					rtrim(ltrim(lsrric_comune_ricev)) as [comune],
					lsrric_prov_ricev as [provincia],
					lsrric_sigla_reg as [regione],
					rtrim(ltrim(lsrtit_cognome)) as [cognome],
					rtrim(ltrim(lsrtit_nome)) as [nome],
					LSRSER_LOTTO_TIPO_PROVV as [stato_LOTTO],
					lsrser_LOTTO_data_decor as [data_decorrenza],
					lsrser_lotto_tipo_provv as [provv_lotto]

				from lsrtit a, lsrric b, lsrser_lotto c
				where lsrser_LOTTO_key_data_ins between @datainizioperiodo and @datafineperiodo
					and lsrser_LOTTO_flag_validita= 'y'
					and lsrtit_key_id_ricev=lsrser_LOTTO_key_id_ricev
					and  lsrser_lotto_flag_validita = 'y'
					and (lsrtit_data_validita + lsrtit_ora_validita) = 
						(select max((lsrtit_data_validita + lsrtit_ora_validita)) 
						from lsrtit 
						where lsrtit_key_id_ricev = a.lsrtit_key_id_ricev 
							and  lsrtit_data_validita <= lsrser_LOTTO_key_data_ins
							and  lsrtit_flag_validita = 'y')
					and lsrtit_key_id_ricev=lsrric_key_id_ricev
					and (lsrric_data_validita + lsrric_ora_validita) = 
						(select max((lsrric_data_validita + lsrric_ora_validita)) 
						from lsrric 
						where lsrric_key_id_ricev = b.lsrric_key_id_ricev 
							and  lsrric_data_validita <= lsrser_LOTTO_key_data_ins
							and  lsrric_flag_validita = 'y')
				and  lsrtit_flag_validita = 'y'
				and  lsrric_flag_validita = 'y'
					
				for xml raw

			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_TIPO_PROVV='I'
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
					
				FOR XML RAW
			END		
			ELSE
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRSER_LOTTO_TIPO_PROVV = @TIPOSTATO
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
					
				FOR XML RAW
			END
		END
	END
END
--*******************************************
--IL RISULTATO NON DEVE ESSERE PRODOTTO IN FORMATO XML
--*******************************************
ELSE
BEGIN 
--*******************************************
-- CONTROLLO SIGLAPROV NOT NULL
--*******************************************
	IF @SIGLAPROV IS NOT NULL
	BEGIN
		--***********************
		--    	LOTTO
		--***********************
		IF (@SERVIZIO = '01')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_TIPO_PROVV='I'
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
			END		
			ELSE
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRSER_LOTTO_TIPO_PROVV = @TIPOSTATO
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
			END
		END
	END
-- ***********************************************
-- CONTROLLO SIGLAREG NOT NULL
-- ***********************************************
	ELSE IF (@SIGLAREG IS NOT NULL)
	BEGIN
		--***********************
		--    	LOTTO
		--***********************
		IF (@SERVIZIO = '01')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM, 					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_TIPO_PROVV='I'
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
			END		
			ELSE
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRSER_LOTTO_TIPO_PROVV = @TIPOSTATO
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
			END
		END
	END
-- ***********************************************
-- SIGLAREG & SIGLAPROV NULL
-- ***********************************************
	ELSE
	BEGIN
		--***********************
		--    	LOTTO
		--***********************
		IF (@SERVIZIO = '01')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_TIPO_PROVV='I'
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
			END		
			ELSE
			BEGIN
				SELECT LSRSER_LOTTO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_LOTTO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_LOTTO_TIPO_PROVV AS STATO,
					LSRSER_LOTTO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_LOTTO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_LOTTO_FLAG_VALIDITA= 'Y'
					AND LSRSER_LOTTO_TIPO_PROVV = @TIPOSTATO
					AND LSRTIT_KEY_ID_RICEV=LSRSER_LOTTO_KEY_ID_RICEV
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_LOTTO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
			END
		END
	END
END

RETURN @ESITO

SET QUOTED_IDENTIFIER OFF
GO
