/****** Object:  StoredProcedure [dbo].[Report_Movimentazioni_per_periodo_di_tempo_BOLLO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
/****** Object:  Stored Procedure dbo.Report_Movimentazioni_per_periodo_di_tempo_BOLLO    Script Date: 16/10/2003 10.27.08 ******/





CREATE	PROCEDURE [dbo].[Report_Movimentazioni_per_periodo_di_tempo_BOLLO] 
	@DATAINIZIOPERIODO 	CHAR(8),
	@DATAFINEPERIODO 	CHAR(8),
	@TIPOMOVIMENTAZIONE	CHAR(1),
	@SERVIZIO		CHAR(2),
	@SIGLAREG		CHAR(2),
	@SIGLAPROV		CHAR(2),
	@XML 			CHAR(1),
	@ESITO 			INT OUT

AS
DECLARE  @TIPOSTATO CHAR(1)

SELECT @ESITO = 0

IF (@SERVIZIO IS NULL) OR (RTRIM(LTRIM(@SERVIZIO)) = '')
BEGIN
    SELECT @ESITO = 9
    RAISERROR ('MANCA IL NOME DEL SERVIZIO',16,1)
    RETURN @ESITO
END


if (@SIGLAPROV is null) or (rtrim(ltrim(@SIGLAPROV)) = '')
begin
    select @SIGLAPROV = null
end
-- SE LA SIGLA DELLA PROVINCIA NON E' NULLA, 
-- METTO A NULL LA SIGLA DELLA REGIONE
ELSE
BEGIN
	SELECT @SIGLAREG = NULL
END

if (@SIGLAREG is null) or (rtrim(ltrim(@SIGLAREG)) = '')
begin
    select @SIGLAREG = null
end

IF (@DATAINIZIOPERIODO IS NULL) OR (RTRIM(LTRIM(@DATAINIZIOPERIODO)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA LA DATA DI INIZIO PERIODO',16,1)
	RETURN @ESITO
END

IF (@DATAFINEPERIODO IS NULL) OR (RTRIM(LTRIM(@DATAFINEPERIODO)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA LA DATA DI FINE PERIODO',16,1)
	RETURN @ESITO
END

IF (@TIPOMOVIMENTAZIONE IS NULL) OR (RTRIM(LTRIM(@TIPOMOVIMENTAZIONE)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA IL TIPO DELLA MOVIMENTAZIONE',16,1)
	RETURN @ESITO
END
ELSE
BEGIN
	SELECT @TIPOSTATO =
		CASE @TIPOMOVIMENTAZIONE 
		WHEN 'A' THEN '1'
		WHEN 'D' THEN '2'
		WHEN 'R' THEN '1'
		WHEN 'S' THEN '2'
		ELSE 0
	END		
END

----PRINT ' - TIPOSTATO --> ' + @TIPOSTATO

--*******************************************
--IL RISULTATO DEVE ESSERE PRODOTTO IN FORMATO XML
--*******************************************
IF (@XML = '1')
BEGIN 
--*******************************************
-- CONTROLLO SIGLAPROV NOT NULL
--*******************************************
	IF @SIGLAPROV IS NOT NULL
	BEGIN
		--***********************
		--    	BOLLO
		--***********************
		IF (@SERVIZIO = '05')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
					
				FOR XML RAW
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_TIPO_PROVV='I'
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
					
				FOR XML RAW
			END		
			ELSE
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_STATO = @TIPOSTATO
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
					
				FOR XML RAW
			END
		END
	END
-- ***********************************************
-- CONTROLLO SIGLAREG NOT NULL
-- ***********************************************
	ELSE IF (@SIGLAREG IS NOT NULL)
	BEGIN
		--***********************
		--    	BOLLO
		--***********************
		IF (@SERVIZIO = '05')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
				FOR XML RAW
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_TIPO_PROVV='I'
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) =  						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
				FOR XML RAW
			END		
			ELSE
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_STATO = @TIPOSTATO
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
				FOR XML RAW
			END
		END
	END
-- ***********************************************
-- SIGLAREG & SIGLAPROV NULL
-- ***********************************************
	ELSE
	BEGIN
		--***********************
		--    	BOLLO
		--***********************
		IF (@SERVIZIO = '05')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN

/*
				select 	1 as tag, 
					null as parent, 
					null as [parametri!1],
					null as [datirichiesti!2!data_inizio_periodo],
					null as [datirichiesti!2!data_fine_periodo],
					null as [datirichiesti!2!servizio],
					null as [datioutput!3], 
					null as [report_bollo!4!cod_lottomatica], 
					null as [report_bollo!4!cod_amm],
					null as [report_bollo!4!data_acquisizione], 
					null as [report_bollo!4!indirizzo],
					null as [report_bollo!4!cap],
					null as [report_bollo!4!comune],
					null as [report_bollo!4!provincia],
					null as [report_bollo!4!regione],
					null as [report_bollo!4!cognome],
					null as [report_bollo!4!nome],
					null as [report_bollo!4!stato_bollo],
					null as [report_bollo!4!data_decorrenza],
					null as [report_bollo!4!provv_lotto]

				union all

				select 	2 as tag,
					1 as parent,
					null as [parametri!1],
					@datainizioperiodo as [datirichiesti!2!data_inizio_periodo],
					@datafineperiodo as [datirichiesti!2!data_fine_periodo],
					@servizio as [datirichiesti!2!servizio],
					null as [datioutput!3], 
					null as [report_bollo!4!cod_lottomatica], 
					null as [report_bollo!4!cod_amm],
					null as [report_bollo!4!data_acquisizione], 
					null as [report_bollo!4!indirizzo],
					null as [report_bollo!4!cap],
					null as [report_bollo!4!comune],
					null as [report_bollo!4!provincia],
					null as [report_bollo!4!regione],
					null as [report_bollo!4!cognome],
					null as [report_bollo!4!nome],
					null as [report_bollo!4!stato_bollo],
					null as [report_bollo!4!data_decorrenza],
					null as [report_bollo!4!provv_lotto]

				union all

				select 	3 as tag,
					null as parent,
					null as [parametri!1],
					null as [datirichiesti!2!data_inizio_periodo],
					null as [datirichiesti!2!data_fine_periodo],
					null as [datirichiesti!2!servizio],
					null as [datioutput!3], 
					null as [report_bollo!4!cod_lottomatica], 
					null as [report_bollo!4!cod_amm],
					null as [report_bollo!4!data_acquisizione], 
					null as [report_bollo!4!indirizzo],
					null as [report_bollo!4!cap],
					null as [report_bollo!4!comune],
					null as [report_bollo!4!provincia],
					null as [report_bollo!4!regione],
					null as [report_bollo!4!cognome],
					null as [report_bollo!4!nome],
					null as [report_bollo!4!stato_bollo],
					null as [report_bollo!4!data_decorrenza],
					null as [report_bollo!4!provv_lotto]

				union all

				select 	4 as tag,
					3 as parent,
					null as [parametri!1],
					null as [datirichiesti!2!data_inizio_periodo],
					null as [datirichiesti!2!data_fine_periodo],
					null as [datirichiesti!2!servizio],
					null as [datioutput!3], 
					lsrser_bollo_key_id_ricev as [report_bollo!4!cod_lottomatica], 
					lsrric_cod_amm as [report_bollo!4!cod_amm],
					lsrser_bollo_key_data_ins as [report_bollo!4!data_acquisizione], 
					rtrim(ltrim(lsrric_indirizzo)) as [report_bollo!4!indirizzo],
					lsrric_cap as [report_bollo!4!cap],
					rtrim(ltrim(lsrric_comune_ricev)) as [report_bollo!4!comune],
					lsrric_prov_ricev as [report_bollo!4!provincia],
					lsrric_sigla_reg as [report_bollo!4!regione],
					rtrim(ltrim(lsrtit_cognome)) as [report_bollo!4!cognome],
					rtrim(ltrim(lsrtit_nome)) as [report_bollo!4!nome],
					lsrser_bollo_stato as [report_bollo!4!stato_bollo],
					lsrser_bollo_data_decor as [report_bollo!4!data_decorrenza],
					lsrser_lotto_tipo_provv as [report_bollo!4!provv_lotto]

				for xml explicit
*/
				select 					
					lsrser_bollo_key_id_ricev as [cod_lottomatica], 
					lsrric_cod_amm as [cod_amm],
					lsrser_bollo_key_data_ins as [data_acquisizione], 
					rtrim(ltrim(lsrric_indirizzo)) as [indirizzo],
					lsrric_cap as [cap],
					rtrim(ltrim(lsrric_comune_ricev)) as [comune],
					lsrric_prov_ricev as [provincia],
					lsrric_sigla_reg as [regione],
					rtrim(ltrim(lsrtit_cognome)) as [cognome],
					rtrim(ltrim(lsrtit_nome)) as [nome],
					lsrser_bollo_stato as [stato_bollo],
					lsrser_bollo_data_decor as [data_decorrenza],
					lsrser_lotto_tipo_provv as [provv_lotto]

				from lsrser_bollo, lsrtit a, lsrric b, lsrser_lotto c
				where lsrser_bollo_key_data_ins between @datainizioperiodo and @datafineperiodo
					and lsrser_bollo_flag_validita= 'y'
					and lsrser_bollo_key_id_ricev = lsrser_lotto_key_id_ricev
					and lsrtit_key_id_ricev=lsrser_bollo_key_id_ricev
					and lsrser_lotto_data_decor =
						(select max(lsrser_lotto_data_decor) 
						from lsrser_lotto 
						where lsrser_lotto_key_id_ricev = c.lsrser_lotto_key_id_ricev 
							and  lsrser_lotto_data_decor <= lsrser_bollo_key_data_ins
							and  lsrser_lotto_flag_validita = 'y'
						)
					and  lsrser_lotto_flag_validita = 'y'
					and (lsrtit_data_validita + lsrtit_ora_validita) = 
						(select max((lsrtit_data_validita + lsrtit_ora_validita)) 
						from lsrtit 
						where lsrtit_key_id_ricev = a.lsrtit_key_id_ricev 
							and  lsrtit_data_validita <= lsrser_bollo_key_data_ins
							and  lsrtit_flag_validita = 'y')
					and lsrtit_key_id_ricev=lsrric_key_id_ricev
					and (lsrric_data_validita + lsrric_ora_validita) = 
						(select max((lsrric_data_validita + lsrric_ora_validita)) 
						from lsrric 
						where lsrric_key_id_ricev = b.lsrric_key_id_ricev 
							and  lsrric_data_validita <= lsrser_bollo_key_data_ins
							and  lsrric_flag_validita = 'y')
				and  lsrtit_flag_validita = 'y'
				and  lsrric_flag_validita = 'y'
					
				for xml raw

			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_TIPO_PROVV='I'
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO  						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
					
				FOR XML RAW
			END		
			ELSE
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_STATO = @TIPOSTATO
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
					
				FOR XML RAW
			END
		END
	END
END
--*******************************************
--IL RISULTATO NON DEVE ESSERE PRODOTTO IN FORMATO XML
--*******************************************
ELSE
BEGIN 
--*******************************************
-- CONTROLLO SIGLAPROV NOT NULL
--*******************************************
	IF @SIGLAPROV IS NOT NULL
	BEGIN
		--***********************
		--    	BOLLO
		--***********************
		IF (@SERVIZIO = '05')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_TIPO_PROVV='I'
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
			END		
			ELSE
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_STATO = @TIPOSTATO
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_PROV_RICEV = @SIGLAPROV
			END
		END
	END
-- ***********************************************
-- CONTROLLO SIGLAREG NOT NULL
-- ***********************************************
	ELSE IF (@SIGLAREG IS NOT NULL)
	BEGIN
		--***********************
		--    	BOLLO
		--***********************
		IF (@SERVIZIO = '05')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM, 					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_TIPO_PROVV='I'
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
			END		
			ELSE
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_STATO = @TIPOSTATO
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
				AND LSRRIC_SIGLA_REG = @SIGLAREG					
			END
		END
	END
-- ***********************************************
-- SIGLAREG & SIGLAPROV NULL
-- ***********************************************
	ELSE
	BEGIN
		--***********************
		--    	BOLLO
		--***********************
		IF (@SERVIZIO = '05')
		BEGIN
			IF @TIPOMOVIMENTAZIONE = '*'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
			END
			ELSE IF @TIPOMOVIMENTAZIONE = 'I'
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_TIPO_PROVV='I'
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
			END		
			ELSE
			BEGIN
				SELECT LSRSER_BOLLO_KEY_ID_RICEV AS CODLTM, 
					LSRSER_BOLLO_KEY_DATA_INS AS DATAACQ, 
					LSRRIC_COD_AMM AS CODAMM,
					LSRRIC_INDIRIZZO AS INDIRIZZO,
					LSRRIC_CAP AS CAP,
					LSRRIC_COMUNE_RICEV AS COMUNE,
					LSRRIC_PROV_RICEV AS PROVINCIA,
					LSRRIC_SIGLA_REG AS REGIONE,
					LSRTIT_COGNOME AS COGNOME,
					LSRTIT_NOME AS NOME,
					LSRSER_BOLLO_STATO AS STATO,
					LSRSER_BOLLO_DATA_DECOR AS DATADECORR,
					LSRSER_LOTTO_TIPO_PROVV AS TIPOPROVVLOTTO
					
				FROM LSRSER_BOLLO, LSRTIT A, LSRRIC B, LSRSER_LOTTO C
				WHERE LSRSER_BOLLO_KEY_DATA_INS BETWEEN @DATAINIZIOPERIODO AND @DATAFINEPERIODO
					AND LSRSER_BOLLO_FLAG_VALIDITA= 'Y'
					AND LSRSER_BOLLO_STATO = @TIPOSTATO
					AND LSRSER_BOLLO_KEY_ID_RICEV = LSRSER_LOTTO_KEY_ID_RICEV
					AND LSRTIT_KEY_ID_RICEV=LSRSER_BOLLO_KEY_ID_RICEV
					AND LSRSER_LOTTO_DATA_DECOR =
						(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
						FROM LSRSER_LOTTO 
						WHERE LSRSER_LOTTO_KEY_ID_RICEV = C.LSRSER_LOTTO_KEY_ID_RICEV 
							AND  LSRSER_LOTTO_DATA_DECOR <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
						)
					AND  LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
					AND (LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA) = 
						(SELECT MAX((LSRTIT_DATA_VALIDITA + LSRTIT_ORA_VALIDITA)) 
						FROM LSRTIT 
						WHERE LSRTIT_KEY_ID_RICEV = A.LSRTIT_KEY_ID_RICEV 
							AND  LSRTIT_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRTIT_FLAG_VALIDITA = 'Y')
					AND LSRTIT_KEY_ID_RICEV=LSRRIC_KEY_ID_RICEV
					AND (LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA) = 
						(SELECT MAX((LSRRIC_DATA_VALIDITA + LSRRIC_ORA_VALIDITA)) 
						FROM LSRRIC 
						WHERE LSRRIC_KEY_ID_RICEV = B.LSRRIC_KEY_ID_RICEV 
							AND  LSRRIC_DATA_VALIDITA <= LSRSER_BOLLO_KEY_DATA_INS
							AND  LSRRIC_FLAG_VALIDITA = 'Y')
				AND  LSRTIT_FLAG_VALIDITA = 'Y'
				AND  LSRRIC_FLAG_VALIDITA = 'Y'
			END
		END
	END
END

RETURN @ESITO

SET QUOTED_IDENTIFIER OFF
GO
