/****** Object:  StoredProcedure [dbo].[RIATTIVAZIONE_TRIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[RIATTIVAZIONE_TRIS] 

	@RICEV 		CHAR(6),
	@DATARIATTIV	CHAR(8),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(50),
	@MSGERR 		VARCHAR(100) OUTPUT

AS

DECLARE 	

@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATAORAINS	CHAR(16),
@CHKRICEV		CHAR(6),
@STATOLOTTO	CHAR(1),
@STATOTRIS		CHAR(1),
@TIPOPROVV		CHAR(1),
@PROVVFUT		CHAR(8),
@DESCSTATO		CHAR(80)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

/*
' ESEGUO I CONTROLLI NEL CASO DI ATTIVAZIONE AL SERVIZIO TRIS:
' 1) - ESISTE LA RICEVITORIA IN LSRSER_TRIS
' 2) - LO STATO DEL SERVIZIO LOTTO SIA ATTIVO ALLA DATA DI ATTIVAZIONE
' 3) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 4) - IL SERVIZIO SIA IN UNO STATO COMPATIBILE CON LA RIATTIVAZIONE
*/


/*
CONTROLLO 1
*/
SELECT @CHKRICEV = LSRSER_TRIS_KEY_ID_RICEV FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE SU LSRSER_TRIS'
	RETURN
END

/*
CONTROLLO 2
*/

SELECT @STATOLOTTO = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(
	SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
	AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
	AND LSRSER_LOTTO_DATA_DECOR <= @DATARIATTIV
)

IF @STATOLOTTO = 'S' OR @STATOLOTTO = 'M' OR @STATOLOTTO = 'R'

BEGIN
	SELECT @MSGERR = '7777 - ' + @RICEV +' SERVIZIO LOTTO SOSPESO/REVOCATO'
	RETURN
END

/*
CONTROLLO 3
*/
SELECT @PROVVFUT = LSRSER_TRIS_DATA_DECOR,@STATOTRIS=LSRSER_TRIS_STATO
FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
AND LSRSER_TRIS_DATA_DECOR = @DATARIATTIV

IF @PROVVFUT IS NOT NULL

BEGIN
	IF @STATOTRIS = '0'
	BEGIN
		SELECT @DESCSTATO = 'SERVIZIO NON ATTIVO ALLA DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOTRIS = '1'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI TIPO ATTIVAZIONE/ RIATTIVAZIONE GIA PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOTRIS = '2'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI TIPO DISATTIVAZIONE GIA PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOTRIS = '3'
	BEGIN
		SELECT @DESCSTATO = 'PROVVEDIMENTO DI TIPO SOSPENSIONE GIA PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END

	SELECT @MSGERR = '6666 - ' + @RICEV + ' ' + @DESCSTATO
	RETURN
END


/*
CONTROLLO 4
*/
SELECT @STATOTRIS = LSRSER_TRIS_STATO FROM LSRSER_TRIS
WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
AND LSRSER_TRIS_DATA_DECOR =
(
	SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
	AND LSRSER_TRIS_DATA_DECOR <= @DATARIATTIV
)

IF @STATOTRIS = '1'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO TRIS GIA ATTIVATO'
	RETURN
END

IF @STATOTRIS = '0'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV + ' ' + ' SERVIZIO TRIS ANCORA NON ATTIVATO'
	RETURN
END


--INIZIO MODIFICA IN DATA 02-05-2001

BEGIN TRANSACTION

SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
FROM LSRLET
WHERE LSRLET_KEY_ID_RICEV = @RICEV
AND LSRLET_COD_SERVIZIO = '08'
AND LSRLET_TIPO_MOVIMENTAZIONE = 'R'
AND LSRLET_KEY_DATA_INS = @DATAINS
AND LSRLET_DECOR_DAL = '00000000'

IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
BEGIN
---MODIFICA DEL 24-07-2001 (SANTA GRISTINA)
	IF LTRIM(RTRIM(@NOTE)) = ''
	BEGIN
		UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATARIATTIV
		WHERE LSRLET_KEY_ID_RICEV = @RICEV
		AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
		AND LSRLET_COD_SERVIZIO = '08'
		AND LSRLET_TIPO_MOVIMENTAZIONE = 'R'
	END
	ELSE
	BEGIN
		UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATARIATTIV,
		LSRLET_NOTE = @NOTE
		WHERE LSRLET_KEY_ID_RICEV = @RICEV
		AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
		AND LSRLET_COD_SERVIZIO = '08'
		AND LSRLET_TIPO_MOVIMENTAZIONE = 'R'
	END
END
ELSE
BEGIN
	INSERT INTO LSRLET VALUES
	(@RICEV,@DATAINS,@ORAINS,'08','R',@DATARIATTIV,'','','00000000',@NOTE,@FIRMA,'V')
END

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET'
	ROLLBACK TRANSACTION
	RETURN
END


--FINE MODIFICA IN DATA 02-05-2001


INSERT INTO LSRSER_TRIS VALUES 
(@RICEV,@DATAINS,@ORAINS,'1',@DATARIATTIV,NULL,NULL,NULL,NULL,@FIRMA,NULL,'00000000','Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV + ' ' + ' ERRORE IN INSERT SU LSRSER_TRIS'
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	SELECT @MSGERR = '0000 -' + @RICEV + ' OPERAZIONE TERMINATA CORRETTAMENTE'
	COMMIT TRANSACTION
	RETURN
END
GO
