/****** Object:  StoredProcedure [dbo].[SCRIVI_LSRLET_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[SCRIVI_LSRLET_GS]  
			@RICEV			CHAR(6),
			@CODSER			CHAR(2),
			@CON	 			CHAR(15),
			@QST				CHAR(15),
			@NUO	 			CHAR(15), 			
			@FID	 			CHAR(15), 
			@TLP	 			CHAR(15), 
		
			@RAD	 			CHAR(15), 
			@RID	 			CHAR(15), 
			@ANNOINIZIOCAMPIONATO	CHAR(4),
			@TIPOPV			CHAR(1),
			@DATAINS			CHAR(8),
			@ORAINS			CHAR(8),
			@TIPOMOV			CHAR(1),
			@FIRMA	 		CHAR(17)


AS
DECLARE		@IDDOC			CHAR(16),
		@RICERIN			CHAR(6),
		@DATAAPPO	CHAR(8),
		@DATA1	CHAR(8),
		@RADFONTE		CHAR(1),
		@RADCAUSALELTM		CHAR(1)


IF @CON <> '0'
BEGIN
	IF @CODSER = '02'
	BEGIN
		SELECT @IDDOC = NULL
	
		SELECT @IDDOC =  LSRCON_GP_KEY_DATA_INS +  LSRCON_GP_KEY_ORA_INS 
		FROM LSRCON_GP 
		WHERE LSRCON_GP_KEY_ID_RICEV = @RICEV
			AND LSRCON_GP_FLAG_ANAG = '1'
			AND LSRCON_GP_TIPO_PV = @TIPOPV
	
		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET_GS VALUES
				(@RICEV,@DATAINS,@ORAINS, @CODSER, @TIPOMOV,'00000000','LSRCON_GP',@IDDOC,'00000000','',@FIRMA,'')
		END

	END
	ELSE
	BEGIN

		SELECT @IDDOC = NULL
	
		SELECT @IDDOC =  LSRCON_GS_KEY_DATA_INS +  LSRCON_GS_KEY_ORA_INS 
		FROM LSRCON_GS 
		WHERE LSRCON_GS_KEY_ID_RICEV = @RICEV
			AND LSRCON_GS_FLAG_ANAG = '1'
			AND LSRCON_GS_CODICE_SERVIZIO = @CODSER
	
		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET_GS VALUES
				(@RICEV,@DATAINS,@ORAINS, @CODSER, @TIPOMOV,'00000000','LSRCON_GS',@IDDOC,'00000000','',@FIRMA,'')
		END
	END
END

IF @TLP <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRTLP_GS_KEY_DATA_INS +  LSRTLP_GS_KEY_ORA_INS 
	FROM LSRTLP_GS 
	WHERE LSRTLP_GS_KEY_ID_RICEV = @RICEV
		AND LSRTLP_GS_FLAG_ANAG = '1'
		AND LSRTLP_GS_CODICE_SERVIZIO = @CODSER
	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_GS VALUES
			(@RICEV, @DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRTLP_GS',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @NUO <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRNUO_GS_KEY_DATA_INS +  LSRNUO_GS_KEY_ORA_INS 
	FROM LSRNUO_GS
	WHERE LSRNUO_GS_KEY_ID_RICEV = @RICEV
		AND LSRNUO_GS_CODICE_SERVIZIO = @CODSER
		AND LSRNUO_GS_FLAG_ANAG = '1'
		AND LSRNUO_GS_data_accettazione <> '00000000'
		AND LSRNUO_GS_data_accettazione is not null
		AND lsrnuo_gs_data_accettazione <> '' 
		AND (lsrnuo_gs_data_revoca = '00000000' 
		OR lsrnuo_gs_data_revoca is null 
		OR lsrnuo_gs_data_revoca = '') 


	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_GS VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRNUO_GS',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @FID <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRFID_CONI_KEY_DATA_INS +  LSRFID_CONI_KEY_ORA_INS 
	FROM LSRFID_CONI 
	WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEV
		AND LSRFID_CONI_FLAG_ANAG = '1'
		AND LSRFID_CONI_ANNO_RIF = @ANNOINIZIOCAMPIONATO


	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_GS VALUES
			(@RICEV,@DATAINS,@ORAINS, @CODSER, @TIPOMOV,'00000000','LSRFID_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END

END


IF @QST <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRQST_CONI_KEY_DATA_INS +  LSRQST_CONI_KEY_ORA_INS 
	FROM LSRQST_CONI 
	WHERE LSRQST_CONI_KEY_ID_RICEV = @RICEV
		AND LSRQST_CONI_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_GS VALUES
			(@RICEV,@DATAINS,@ORAINS,@CODSER, @TIPOMOV,'00000000','LSRQST_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @RAD <> '0'
BEGIN

	SELECT @IDDOC = NULL

	-- GIOCHI PUBBLICI
	IF @CODSER = '02'
	BEGIN
		-- CONTROLLO SULLA DATA DI INVIO DEL DOCUMENTO RAD
		SELECT @IDDOC =  LSRRAD_GS_KEY_DATA_INS +  LSRRAD_GS_KEY_ORA_INS 
		FROM LSRRAD_GS 
		WHERE LSRRAD_GS_KEY_ID_RICEV = @RICEV
			AND LSRRAD_GS_CODICE_SERVIZIO = @CODSER
			AND LSRRAD_GS_TIPO_MOVIMENTAZIONE = @TIPOMOV
			AND LSRRAD_GS_FLAG_ANAG = '1'
			AND LSRRAD_GS_DATA_INVIO_DOC >= 
				(SELECT MAX(LSRSER_GP_DATA_DECOR) FROM LSRSER_GP
				WHERE LSRSER_GP_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
				AND LSRSER_GP_FLAG_VALIDITA = 'Y' 
				AND LSRSER_GP_KEY_ID_RICEV = LSRRAD_GS_KEY_ID_RICEV ) 
		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
			INSERT INTO LSRLET_GS VALUES
				(@RICEV, @DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD_GS',@IDDOC,'00000000','',@FIRMA,'')
		END

	END

	ELSE
	BEGIN
		IF @TIPOMOV='R'
		BEGIN
			--******************************************--	
			-- PALETTI: LA CAUSALE DI RIATTIVAZIONE E'  --	
			-- QUELLA UGUALE E CONTRARIA ALLA PRIMA	    --
			-- CAUSALE DI DISATTIVAZIONE                --
			--******************************************--	
			
			--PRENDO LA DATA DI PRIMA DISATTIVAZIONE
			SELECT @DATA1 = MAX(LSRSER_TRIS_DATA_DECOR) 
			FROM LSRSER_TRIS B
			WHERE LSRSER_TRIS_FT_VOS <> '00000000' 
				AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
				AND LSRSER_TRIS_STATO = '1' 
				AND LSRSER_TRIS_KEY_ID_RICEV =  @RICEV
			GROUP BY LSRSER_TRIS_KEY_ID_RICEV, LSRSER_TRIS_STATO 
		
			SELECT @DATAAPPO = MIN(LSRSER_TRIS_DATA_DECOR) 
			FROM LSRSER_TRIS A 
			WHERE A.LSRSER_TRIS_FT_VOS <> '00000000' 
				AND A.LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
				AND A.LSRSER_TRIS_STATO = '2' 
				AND A.LSRSER_TRIS_DATA_DECOR >=  @DATA1
				AND A.LSRSER_TRIS_KEY_ID_RICEV = @RICEV 
	
	/*
			SELECT @DATAAPPO = 
				(SELECT MIN(LSRSER_TRIS_DATA_DECOR) DATA 
				FROM LSRSER_TRIS A 
				WHERE A.LSRSER_TRIS_FT_VOS <> '00000000' 
					AND A.LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
					AND A.LSRSER_TRIS_STATO = '2' 
					AND A.LSRSER_TRIS_DATA_DECOR >=  MAX(B.LSRSER_TRIS_DATA_DECOR) 
					AND A.LSRSER_TRIS_KEY_ID_RICEV = @RICEV ) 
			FROM LSRSER_TRIS B 
			WHERE LSRSER_TRIS_FT_VOS <> '00000000' 
				AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
				AND LSRSER_TRIS_STATO = '1' 
				AND LSRSER_TRIS_KEY_ID_RICEV =  @RICEV
			GROUP BY LSRSER_TRIS_KEY_ID_RICEV, LSRSER_TRIS_STATO 
	*/
	
	
			-- PRENDO IL DOC RAD CHE HA GENERATO LA DISATTIVAZIONE
			SELECT @RADFONTE = LSRRAD_GS_fonte, 
				@RADCAUSALELTM = LSRRAD_GS_causale_lottomatica
			FROM LSRRAD_GS  
			WHERE LSRRAD_GS_KEY_ID_RICEV  =  @RICEV
				AND LSRRAD_GS_CODICE_SERVIZIO = @CODSER
				AND LSRRAD_GS_KEY_DATA_INS + LSRRAD_GS_KEY_ORA_INS = (
					SELECT  LSRLET_GS_FK_TAB_DOCUMENTO 
					FROM LSRLET_GS 
					WHERE LSRLET_GS_KEY_ID_RICEV  = @RICEV
						AND LSRLET_GS_KEY_CODICE_SERVIZIO = @CODSER
						AND LSRLET_GS_TIPO_MOVIMENTAZIONE = 'D' 
						AND LSRLET_GS_DECOR_DAL = @DATAAPPO
						AND LSRLET_GS_NOME_TAB_DOCUMENTO = 'LSRRAD_GS'
						AND LSRLET_GS_DECOR_DAL <> '00000000'
				)
	
			-- PRENDO IL DOC RAD DI RIATTIVAZIONE CON CAUSALE UGUALE E 
			-- CONTRARIA A QUELLO CHE HA GENERATO LA DISATTIVAZIONE
			IF @RADFONTE = 'M' OR @RADFONTE = 'A' 
			BEGIN			
				SELECT @IDDOC =  LSRRAD_GS_KEY_DATA_INS +  LSRRAD_GS_KEY_ORA_INS				
				FROM LSRRAD_GS 
				WHERE LSRRAD_GS_KEY_ID_RICEV  = @RICEV
					AND LSRRAD_GS_CODICE_SERVIZIO = @CODSER
					AND LSRRAD_GS_fonte = @RADFONTE
					AND LSRRAD_GS_data_decor >= @DATAAPPO
					and LSRRAD_GS_tipo_movimentazione = 'R' 
				
				
			END
			
			IF @RADFONTE = 'L' 
			BEGIN
				SELECT  @IDDOC =  LSRRAD_GS_KEY_DATA_INS +  LSRRAD_GS_KEY_ORA_INS
				FROM LSRRAD_GS 
				WHERE LSRRAD_GS_KEY_ID_RICEV  = @RICEV
					AND LSRRAD_GS_CODICE_SERVIZIO = @CODSER
					AND LSRRAD_GS_fonte = @RADFONTE
					AND LSRRAD_GS_data_decor >= @DATAAPPO
					and LSRRAD_GS_tipo_movimentazione = 'R' 
					AND LSRRAD_GS_causale_lottomatica = @RADCAUSALELTM
				
			
			END
	
			-- SE LA PRIMA DISATTIVAZIONE NON E' STATA GENERATA DA
			-- NESSUN DOCUMENTO RAD, ALLORA PRENDO COME CAUSALE 
			-- QUELLA DI UN DOC DI RIATTIVAZIONE
	
			IF LTRIM(RTRIM(@IDDOC)) = '' OR @IDDOC IS NULL
			BEGIN
	
				-- CONTROLLO SULLA DATA DI INVIO DEL DOCUMENTO RAD
				SELECT @IDDOC =  LSRRAD_GS_KEY_DATA_INS +  LSRRAD_GS_KEY_ORA_INS 
				FROM LSRRAD_GS 
				WHERE LSRRAD_GS_KEY_ID_RICEV = @RICEV
					AND LSRRAD_GS_CODICE_SERVIZIO = @CODSER
					AND LSRRAD_GS_TIPO_MOVIMENTAZIONE = @TIPOMOV
					AND LSRRAD_GS_FLAG_ANAG = '1'
					AND LSRRAD_GS_DATA_INVIO_DOC >= 
						(SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS  
						WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
						AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
						AND LSRSER_TRIS_KEY_ID_RICEV = LSRRAD_GS_KEY_ID_RICEV ) 
	
			end
		END
	
		ELSE
		BEGIN
			-- CONTROLLO SULLA DATA DI INVIO DEL DOCUMENTO RAD
			SELECT @IDDOC =  LSRRAD_GS_KEY_DATA_INS +  LSRRAD_GS_KEY_ORA_INS 
			FROM LSRRAD_GS 
			WHERE LSRRAD_GS_KEY_ID_RICEV = @RICEV
				AND LSRRAD_GS_CODICE_SERVIZIO = @CODSER
				AND LSRRAD_GS_TIPO_MOVIMENTAZIONE = @TIPOMOV
				AND LSRRAD_GS_FLAG_ANAG = '1'
				AND LSRRAD_GS_DATA_INVIO_DOC >= 
					(SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS  
					WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
					AND LSRSER_TRIS_FLAG_VALIDITA = 'Y' 
					AND LSRSER_TRIS_KEY_ID_RICEV = LSRRAD_GS_KEY_ID_RICEV ) 
		END
		IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
		BEGIN
	print @IDDOC
	print @TIPOMOV
	print @CODSER
			INSERT INTO LSRLET_GS VALUES
				(@RICEV, @DATAINS,@ORAINS,@CODSER,@TIPOMOV,'00000000','LSRRAD_GS',@IDDOC,'00000000','',@FIRMA,'')
		END
	END
END
GO
