/****** Object:  StoredProcedure [dbo].[SCRIVI_LSRLET_CONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[SCRIVI_LSRLET_CONI]  
			@RICEV			CHAR(6),
			@CON	 			CHAR(15), 
			@QST	 			CHAR(15), 
			@NUO	 			CHAR(15), 
			@FID	 			CHAR(15), 
			@RAD	 			CHAR(15), 
			@RID	 			CHAR(15), 
			@ANNOINIZIOCAMPIONATO	CHAR(4),
			@DATAINS			CHAR(8),
			@ORAINS			CHAR(8),
			@TIPOMOV			CHAR(1),
			@FIRMA	 		CHAR(17)


AS

DECLARE		@IDDOC			CHAR(16),
			@RICERIN			CHAR(6),
			@NOMESERVIZIO		VARCHAR(6)


IF @CON <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRCON_CONI_KEY_DATA_INS +  LSRCON_CONI_KEY_ORA_INS 
	FROM LSRCON_CONI 
	WHERE LSRCON_CONI_KEY_ID_RICEV = @RICEV
		AND LSRCON_CONI_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_CONI VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRCON_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @QST <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRQST_CONI_KEY_DATA_INS +  LSRQST_CONI_KEY_ORA_INS 
	FROM LSRQST_CONI 
	WHERE LSRQST_CONI_KEY_ID_RICEV = @RICEV
		AND LSRQST_CONI_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_CONI VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRQST_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @NUO <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRNUO_CONI_KEY_DATA_INS +  LSRNUO_CONI_KEY_ORA_INS 
	FROM LSRNUO_CONI 
	WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEV
		AND LSRNUO_CONI_FLAG_ANAG = '1'
		AND lsrnuo_coni_data_accettazione <> '00000000'
		AND lsrnuo_coni_data_accettazione is not null

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_CONI VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRNUO_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @FID <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRFID_CONI_KEY_DATA_INS +  LSRFID_CONI_KEY_ORA_INS 
	FROM LSRFID_CONI 
	WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEV
		AND LSRFID_CONI_FLAG_ANAG = '1'
		AND LSRFID_CONI_ANNO_RIF = @ANNOINIZIOCAMPIONATO


	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_CONI VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRFID_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END

END

IF @RAD <> '0'
BEGIN

	SELECT @IDDOC = NULL

	-- CONTROLLO SULLA DATA DI INVIO DEL DOCUMENTO RAD
	SELECT @IDDOC =  LSRRAD_CONI_KEY_DATA_INS +  LSRRAD_CONI_KEY_ORA_INS 
	FROM LSRRAD_CONI 
	WHERE LSRRAD_CONI_KEY_ID_RICEV = @RICEV
		AND LSRRAD_CONI_TIPO_MOVIMENTAZIONE = @TIPOMOV
		AND LSRRAD_CONI_FLAG_ANAG = '1'
		AND LSRRAD_CONI_DATA_INVIO_DOC >= 
			(SELECT MAX(LSRSER_CONI_DATA_DECOR) FROM LSRSER_CONI  
			WHERE LSRSER_CONI_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
			AND LSRSER_CONI_FLAG_VALIDITA = 'Y' 
			AND LSRSER_CONI_KEY_ID_RICEV = LSRRAD_CONI_KEY_ID_RICEV ) 

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_CONI VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRRAD_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END
END


--IF @TIPOMOV = 'D'
IF @TIPOMOV = 'D'
BEGIN
	--Se esiste la rinuncia, la sua data deve essere minore o uguale alla data di domani
	SELECT @IDDOC = NULL
	SELECT @IDDOC = LSRRIN_CONI_KEY_DATA_INS + LSRRIN_CONI_KEY_ORA_INS
	 FROM LSRRIN_CONI
	WHERE LSRRIN_CONI_KEY_ID_RICEV = @RICEV
		AND LSRRIN_CONI_FLAG_ANAG = '1'
		AND LSRRIN_CONI_CODICE_SERVIZIO = '11'
		AND LSRRIN_CONI_DATA_RINUNCIA <= CONVERT(CHAR,GETDATE() + 1 ,112)
		AND (LSRRIN_CONI_data_rinuncia_rinuncia is NULL OR LSRRIN_CONI_data_rinuncia_rinuncia ='00000000' or LSRRIN_CONI_data_rinuncia_rinuncia = '')
	
	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_CONI VALUES
		(@RICEV, @DATAINS, @ORAINS, @TIPOMOV,'00000000','LSRRIN_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END
END
GO
