/****** Object:  StoredProcedure [dbo].[VARIAZIONE_FIDEJUSSIONE_UNICA_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE    PROCEDURE [dbo].[VARIAZIONE_FIDEJUSSIONE_UNICA_LIS]


	@RICEV 		CHAR(6),
	@NOMEFILE	VARCHAR(255),
	@DATAINVIODOC	CHAR(8),
	@DATADOC	CHAR(8),
	@NUMPROTDOC	CHAR(25),
	@STATODOC	CHAR(1),
	@ASSOCIAZIONE	CHAR(2),
	@IMPORTO	CHAR(20),
	@ANNORIF	CHAR(4),
	@COGNOME	CHAR(24),
	@NOME		CHAR(20),
	@NOTE		CHAR(50),
	@FLAGANAG	CHAR(1),
	@FKDATAINSTIT	CHAR(8),
	@FKORAINSTIT	CHAR(8),

	@KEYDATAINSDOC	CHAR(8),
	@KEYORAINSDOC	CHAR(8),
	@ABBINATO 	CHAR(1),
	
	@FIRMA		CHAR(17),
	@MSGERR 	VARCHAR(100) OUTPUT
 AS


DECLARE 	

@CATEGORIA		CHAR(2),
@SERVIZIO   		CHAR(2),
@ATTIVITA  		CHAR(2),
@FLAGOK 		CHAR(1)

/* VARIO LA FIDEJUSSIONE PER LE BIGLIETTERIE */
SELECT @CATEGORIA = '04'
SELECT @SERVIZIO = '01'
SELECT @ATTIVITA = '  '
EXEC  VARIAZIONE_FIDEJUSSIONE_LIS @RICEV,
				@CATEGORIA,
				@SERVIZIO,
				@ATTIVITA,
				@NOMEFILE,
				@DATAINVIODOC,
				@DATADOC,
				@NUMPROTDOC,
				@STATODOC,
				@ASSOCIAZIONE,
				@IMPORTO,
				@ANNORIF,
				@COGNOME,
				@NOME,
				@NOTE,
				@FLAGANAG,
				@FKDATAINSTIT,
				@FKORAINSTIT,
				@KEYDATAINSDOC,
				@KEYORAINSDOC,
				@ABBINATO,
				@FIRMA,
				@MSGERR OUTPUT

      print @MSGERR       

IF @MSGERR like '9999%'
BEGIN
        RETURN
END

ELSE
BEGIN

	/* VARIO LA FIDEJUSSIONE PER LE MULTE */
	SELECT @CATEGORIA = '02'
	SELECT @SERVIZIO = '03'
	SELECT @ATTIVITA = '  '
	EXEC  VARIAZIONE_FIDEJUSSIONE_LIS @RICEV,
					@CATEGORIA,
					@SERVIZIO,
					@ATTIVITA,
					@NOMEFILE,
					@DATAINVIODOC,
					@DATADOC,
					@NUMPROTDOC,
					@STATODOC,
					@ASSOCIAZIONE,
					@IMPORTO,
					@ANNORIF,
					@COGNOME,
					@NOME,
					@NOTE,
					@FLAGANAG,
					@FKDATAINSTIT,
					@FKORAINSTIT,
					@KEYDATAINSDOC,
					@KEYORAINSDOC,
					@ABBINATO,
					@FIRMA,
					@MSGERR OUTPUT
	


	IF @MSGERR like '9999%'
	BEGIN
	        RETURN
	END
	
	ELSE
	BEGIN
	
		/* VARIO LA FIDEJUSSIONE PER LE RICARICHE */
		SELECT @CATEGORIA = '01'
		SELECT @SERVIZIO = '02'
		SELECT @ATTIVITA = '  '
		EXEC  VARIAZIONE_FIDEJUSSIONE_LIS @RICEV,
						@CATEGORIA,
						@SERVIZIO,
						@ATTIVITA,
						@NOMEFILE,
						@DATAINVIODOC,
						@DATADOC,
						@NUMPROTDOC,
						@STATODOC,
						@ASSOCIAZIONE,
						@IMPORTO,
						@ANNORIF,
						@COGNOME,
						@NOME,
						@NOTE,
						@FLAGANAG,
						@FKDATAINSTIT,
						@FKORAINSTIT,
						@KEYDATAINSDOC,
						@KEYORAINSDOC,
						@ABBINATO,
						@FIRMA,
						@MSGERR OUTPUT
		
	
	END
END
GO
