/****** Object:  StoredProcedure [dbo].[VARIAZIONE_FIDEJUSSIONE_CONI]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[VARIAZIONE_FIDEJUSSIONE_CONI]


	@RICEV 		CHAR(6),
	@NOMEFILE	VARCHAR(255),
	@DATAINVIODOC	CHAR(8),
	@DATADOC	CHAR(8),
	@NUMPROTDOC	CHAR(25),
	@ASSOCIAZIONE	CHAR(2),
	@IMPORTO	CHAR(20),
	@ANNORIF	CHAR(4),
	@COGNOME	CHAR(24),
	@NOME		CHAR(20),
	@NOTE		CHAR(100),
	@FLAGANAG	CHAR(1),
	@FKDATAINSTIT	CHAR(8),
	@FKORAINSTIT	CHAR(8),

	@KEYDATAINSDOC	CHAR(8),
	@KEYORAINSDOC	CHAR(8),
	@ABBINATO 		CHAR(1),

	@FIRMA		CHAR(17),	
	@MSGERR 	VARCHAR(100) OUTPUT
 AS

DECLARE 	

@APPORICEV		CHAR(6),
@CHKRICEV		CHAR(6),
@DATAOGGI   		CHAR(8),
@ORAOGGI  		CHAR(8),
@COGNOMETIT		CHAR(24),
@NOMETIT		CHAR(20),
@FLAGANAGTIT		CHAR(1),
@DATAINSTIT		CHAR(8),
@ORAINSTIT		CHAR(8),
@TIPOPREC 		CHAR(1),
@TIPOPROVV		CHAR(1),
@TITTROVATO 		CHAR(1),
@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)

IF (@ANNORIF = '' OR @ANNORIF IS NULL)
BEGIN
	SELECT @ANNORIF = SUBSTRING(CONVERT (VARCHAR(10), GETDATE(),112),1,4)
END  



--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL ABBINATO = '0' E FLAGANAG è <>0 VERIFICO CHE NON SIA GIà PRESENTE UNA FIDEJUSSIONE PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 2) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT


SELECT @CHKRICEV = NULL

SELECT @CHKRICEV = LSRTIT_CONI_KEY_ID_RICEV FROM LSRTIT_CONI
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE'
	RETURN
END



--*************************************************************************
--           CONTROLLO 1
--*************************************************************************


IF (@ABBINATO = '0' AND @FLAGANAG <> '0')
BEGIN

	SELECT @APPORICEV = LSRFID_CONI_KEY_ID_RICEV 
	FROM LSRFID_CONI
	WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEV
		AND LSRFID_CONI_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRFID_CONI_FK_ORA_INS_TIT = @FKORAINSTIT
		AND lsrfid_coni_anno_rif = @ANNORIF


	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +'PER LA RICEVITORIA ESISTE UNA FID. PER IL TIT. E ANNO RIF. INDICATI - FIDEJUSSIONE NON ACQUISITA'
		RETURN
	END
END



--*************************************************************************
--           CONTROLLO 2
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_CONI_COGNOME , @NOME = LSRTIT_CONI_NOME
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 


--*************************************************************************
--           CONTROLLO 3
--*************************************************************************

IF @FLAGANAG <> '0' 
BEGIN
	SELECT  @FLAGANAG = LSRTIT_CONI_FLAG_ANAG
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 


IF @FLAGANAG = '0' 
BEGIN
	SELECT @FKDATAINSTIT = NULL	
	SELECT @FKORAINSTIT = NULL	
END

--*************************************************************************
--           IL RECORD VIENE AGGIORNATO SU LSRFID_CONI
--*************************************************************************
UPDATE LSRFID_CONI 
SET 		
	--lsrfid_coni_key_data_ins = @DATAOGGI,
	--lsrfid_coni_key_ora_ins = @ORAOGGI,
	lsrfid_coni_data_doc = @DATADOC,		
	lsrfid_coni_data_invio_doc = @DATAINVIODOC,	
	lsrfid_coni_num_prot_doc = @NUMPROTDOC,	
	lsrfid_coni_id_soc = @ASSOCIAZIONE,	
	lsrfid_coni_cognome = @COGNOME,	
	lsrfid_coni_nome = @NOME	,	
	lsrfid_coni_importo = @IMPORTO,
	lsrfid_coni_anno_rif = @ANNORIF,
	lsrfid_coni_note = @NOTE	,	
	lsrfid_coni_flag_anag = @FLAGANAG,	
	lsrfid_coni_fk_data_ins_tit = @FKDATAINSTIT,	
	lsrfid_coni_fk_ora_ins_tit = @FKORAINSTIT,	
	lsrfid_coni_firma = @FIRMA	
WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEV
	AND LSRFID_CONI_KEY_DATA_INS = @KEYDATAINSDOC
	AND LSRFID_CONI_KEY_ORA_INS = @KEYORAINSDOC


IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO FIDEJUSSIONE - FIDEJUSSIONE NON ACQUISITA'
	RETURN
END
ELSE
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' FIDEJUSSIONE VARIATA CORRETTAMENTE'
	RETURN
END
GO
