/****** Object:  StoredProcedure [dbo].[RIATTIVAZIONE_PAG_LIS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[RIATTIVAZIONE_PAG_LIS]  
	@RICEV 		CHAR(6),
	@CATEGORIA		CHAR(2),
	@SERVIZIO		CHAR(2),
	@ATTIVITA		CHAR(2),
	@DATAATTIV		CHAR(8),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(50),
	@MSGERR 		VARCHAR(100) OUTPUT
AS



DECLARE 	@DATAINS		CHAR(8),
		@ORAINS		CHAR(8),
		@DATAORAINS	CHAR(16),
		@DATAMAX		CHAR(8),
		@CHKRICEV		CHAR(6),
		@STATOLOTTO	CHAR(1),
		@STATOA		CHAR(1),
		@STATOFUTURO	CHAR(1),
		@TIPOPROVV		CHAR(1),
		@PROVVFUT		CHAR(8),
		@ASSOCIAZIONE	CHAR(1),
		@DESCSTATO		CHAR(80)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)
/*
' ESEGUO I CONTROLLI NEL CASO DI ATTIVAZIONE AD UN SERVIZIO PAGAMENTO UTENZE
' 1) - ESISTE LA RICEVITORIA IN LSRSER_PAG
' 2) - LO STATO DEL SERVIZIO LOTTO SIA ATTIVO ALLA DATA DI ATTIVAZIONE
' 3) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 4) - IL SERVIZIO SIA IN UNO STATO COMPATIBILE CON LA RIATTIVAZIONE
*/

/*
CONTROLLO 1
*/
SELECT @CHKRICEV = LSRSER_PAG_KEY_ID_RICEV
FROM LSRSER_PAG
WHERE  LSRSER_PAG_KEY_ID_RICEV = @RICEV
	AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_PAG_FLAG_VALIDITA = 'Y'

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE SUGLI ARCHIVI'
	RETURN
END

/*
CONTROLLO 2
*/
SELECT @STATOLOTTO = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR <= @DATAATTIV)

IF @STATOLOTTO = 'S' OR @STATOLOTTO = 'M' OR @STATOLOTTO = 'R'

BEGIN
	SELECT @MSGERR = '7777 - ' + @RICEV +' SERVIZIO LOTTO SOSPESO/REVOCATO'
	RETURN
END

/*
CONTROLLO 3
*/

SELECT @PROVVFUT = LSRSER_PAG_DATA_DECOR, @STATOFUTURO = LSRSER_PAG_STATO
FROM LSRSER_PAG
WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEV
	AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
	AND LSRSER_PAG_DATA_DECOR = @DATAATTIV


IF @PROVVFUT IS NOT NULL

BEGIN
	IF @STATOFUTURO = '1'
	BEGIN
		SELECT @DESCSTATO = 'PROVV. DI ATTIVAZIONE/ RIATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOFUTURO = '2'
	BEGIN
		SELECT @DESCSTATO = 'PROVV. DI DISATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	SELECT @MSGERR = '6666 - ' + @RICEV + '  ' + @DESCSTATO
	RETURN
END

/*
CONTROLLO 4
*/
SELECT @STATOA = LSRSER_PAG_STATO 
FROM LSRSER_PAG
WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEV
	AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA
	AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
	AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
	AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
	AND LSRSER_PAG_DATA_DECOR =
		(SELECT MAX(LSRSER_PAG_DATA_DECOR) 
		FROM LSRSER_PAG
		WHERE LSRSER_PAG_KEY_ID_RICEV = @RICEV
			AND LSRSER_PAG_KEY_CATEGORIA = @CATEGORIA
			AND LSRSER_PAG_KEY_SERVIZIO = @SERVIZIO
			AND LSRSER_PAG_KEY_ATTIVITA = @ATTIVITA
			AND LSRSER_PAG_FLAG_VALIDITA = 'Y'
			AND LSRSER_PAG_DATA_DECOR <= @DATAATTIV)

IF @STATOA = '1'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO GIA ATTIVATO'
	RETURN
END


BEGIN TRANSACTION

SELECT @DATAORAINS = MAX(LSRLET_LIS_KEY_DATA_INS+LSRLET_LIS_KEY_ORA_INS)
				FROM LSRLET_LIS
				WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEV
				AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA
				AND LSRLET_LIS_KEY_SERVIZIO =  @SERVIZIO
				AND LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA
				AND LSRLET_LIS_TIPO_MOVIMENTAZIONE = 'R'
				AND LSRLET_LIS_KEY_DATA_INS = @DATAINS
				AND LSRLET_LIS_DECOR_DAL = '00000000'

IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET_LIS 
	SET LSRLET_LIS_DECOR_DAL = @DATAATTIV,
		LSRLET_LIS_NOTE = @NOTE
	WHERE LSRLET_LIS_KEY_ID_RICEV = @RICEV
	AND LSRLET_LIS_KEY_DATA_INS+LSRLET_LIS_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_LIS_KEY_CATEGORIA = @CATEGORIA
	AND LSRLET_LIS_KEY_SERVIZIO =  @SERVIZIO
	AND LSRLET_LIS_KEY_ATTIVITA = @ATTIVITA
	AND LSRLET_LIS_TIPO_MOVIMENTAZIONE = 'R'

END
ELSE
BEGIN
	INSERT INTO LSRLET_LIS
	 VALUES(@RICEV,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA, 'R',@DATAATTIV,'','','00000000',@NOTE,@FIRMA,'V')
END

	
IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET'
	ROLLBACK TRANSACTION
	RETURN
END


INSERT INTO LSRSER_PAG VALUES (@RICEV,@DATAINS,@ORAINS,@CATEGORIA, @SERVIZIO, @ATTIVITA, '1',@DATAATTIV,NULL,NULL,NULL,NULL,@FIRMA,NULL,'00000000','Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO VARIAZIONE STATO'
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN

	SELECT @MSGERR = '0000 - ' + @RICEV +' OPERAZIONE TERMINATA CORRETTAMENTE'


	COMMIT TRANSACTION
	RETURN
END
GO
