/****** Object:  StoredProcedure [dbo].[ATTIVAZIONE_F101]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ATTIVAZIONE_F101]  

	@RICEV 		CHAR(6),
	@DATAATTIV		CHAR(8),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(50),
	@MSGERR 		VARCHAR(100) OUTPUT
AS

DECLARE 	

@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATAORAINS	CHAR(16),
@DATAMAX		CHAR(8),
@CHKRICEV		CHAR(6),
@STATOLOTTO	CHAR(1),
@STATOF101A		CHAR(1),
@STATOF101F		CHAR(1),
@TIPOPROVV		CHAR(1),
@PROVVFUT		CHAR(8),
@ASSOCIAZIONE	CHAR(1),
@DESCSTATO		CHAR(80)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

/*
' ESEGUO I CONTROLLI NEL CASO DI ATTIVAZIONE AL SERVIZIO F101:
' 1) - ESISTE LA RICEVITORIA IN LSRSER_F101
' 2) - LO STATO DEL SERVIZIO LOTTO SIA ATTIVO OPPURE ABBIA ALMENO LA CONCESSIONE ALLA DATA DI ATTIVAZIONE
' 3) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 4) - IL SERVIZIO NON SIA GIà ATTIVO	
*/


/*
CONTROLLO 1
*/
SELECT @CHKRICEV = LSRSER_F101_KEY_ID_RICEV FROM LSRSER_F101
WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE SU LSRSER_F101'
	RETURN
END

/*
CONTROLLO 2
*/

SELECT @STATOLOTTO = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR <= @DATAATTIV)

IF @STATOLOTTO = 'S' OR @STATOLOTTO = 'M' OR @STATOLOTTO = 'R'

BEGIN
	SELECT @MSGERR = '7777 - ' + @RICEV +' SERVIZIO LOTTO SOSPESO/REVOCATO'
	RETURN
END

/*
CONTROLLO 3
*/

SELECT @PROVVFUT = LSRSER_F101_DATA_DECOR,@STATOF101F = LSRSER_F101_STATO
FROM LSRSER_F101
WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
AND LSRSER_F101_FLAG_VALIDITA = 'Y'
AND LSRSER_F101_DATA_DECOR = @DATAATTIV


IF @PROVVFUT IS NOT NULL

BEGIN
	IF @STATOF101F = '1'
	BEGIN
		SELECT @DESCSTATO = 'PROVV. DI ATTIVAZIONE/ RIATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOF101F = '2'
	BEGIN
		SELECT @DESCSTATO = 'PROVV. DI DISATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	SELECT @MSGERR = '6666 - ' + @RICEV + '  ' + @DESCSTATO
	RETURN
END

/*
CONTROLLO 4
*/
SELECT @STATOF101A = LSRSER_F101_STATO 
FROM LSRSER_F101
WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
AND LSRSER_F101_FLAG_VALIDITA = 'Y'
AND LSRSER_F101_DATA_DECOR =
	(SELECT MAX(LSRSER_F101_DATA_DECOR) 
	FROM LSRSER_F101
	WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
	AND LSRSER_F101_FLAG_VALIDITA = 'Y'
	AND LSRSER_F101_DATA_DECOR <= @DATAATTIV)

IF @STATOF101A = '1'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO F101 GIA ATTIVATO'
	RETURN
END

IF @STATOF101A = '2'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO F101 DISATTIVO'
	RETURN
END


/*
IF @STATOF101F = 0
BEGIN
	UPDATE LSRSER_F101 SET LSRSER_F101_FLAG_VALIDITA = 'N'
	WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
	AND LSRSER_F101_FLAG_VALIDITA = 'Y'
	AND LSRSER_F101_DATA_DECOR >= @DATAATTIV
END
*/

--INIZIO MODIFICA IN DATA 02-05-2001

BEGIN TRANSACTION

SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
				FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @RICEV
				AND LSRLET_COD_SERVIZIO = '02'
				AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'
				AND LSRLET_KEY_DATA_INS = @DATAINS
				AND LSRLET_DECOR_DAL = '00000000'

IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATAATTIV
	WHERE LSRLET_KEY_ID_RICEV = @RICEV
	AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_COD_SERVIZIO = '02'
	AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'

END
ELSE
BEGIN
	INSERT INTO LSRLET VALUES(@RICEV,@DATAINS,@ORAINS,'02','A',@DATAATTIV,'','','00000000',@NOTE,@FIRMA,'V')
END

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET'
	ROLLBACK TRANSACTION
	RETURN
END

--FINE MODIFICA IN DATA 02-05-2001

INSERT INTO LSRSER_F101 VALUES (@RICEV,@DATAINS,@ORAINS,'1',@DATAATTIV,NULL,NULL,NULL,NULL,@FIRMA,NULL,'00000000','Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT SU LSRSER_F101'
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	SELECT @MSGERR = '0000 - ' + @RICEV +' OPERAZIONE TERMINATA CORRETTAMENTE'
	COMMIT TRANSACTION
	RETURN
END
GO
