/****** Object:  StoredProcedure [dbo].[ATTIVAZIONE_BOLLO]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ATTIVAZIONE_BOLLO]  
	@RICEV 		CHAR(6),
	@DATAATTIV		CHAR(8),
	@FIRMA			CHAR(17),
	@NOTE			CHAR(50),
	@CANONE		CHAR(1),
	@MSGERR 		VARCHAR(100) OUTPUT
AS

DECLARE 	

@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@ORAINS2		CHAR(8),
@DATAORAINS	CHAR(16),
@DATAMAX		CHAR(8),
@CHKRICEV		CHAR(6),
@STATOLOTTO	CHAR(1),
@STATOBOLLOA	CHAR(1),
@STATOBOLLOF	CHAR(1),
@TIPOPROVV		CHAR(1),
@PROVVFUT		CHAR(8),
@ASSOCIAZIONE	CHAR(1),
@DESCSTATO		CHAR(80)

SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)

SELECT @ORAINS2 = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
		SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2) + 1

/*
' ESEGUO I CONTROLLI NEL CASO DI ATTIVAZIONE AL SERVIZIO BOLLO:
' 1) - ESISTE LA RICEVITORIA IN LSRSER_BOLLO -ELIMINATO PERCHE' VIENE EFFETTUATA CONTESTUALMENTE ANCHE L'ADESIONE
' 2) - NON ESISTANO PROVVEDIMENTI NEL FUTURO (DOMANI)
' 3) - IL SERVIZIO NON SIA GIà ATTIVO	
' 4) - LO STATO DEL SERVIZIO BOLLO SIA UGUALE A 0 
        OPPURE
        LA RICEVITORIA NON è PRESENTE SU LSRSER_BOLLO (IN QUESTO CASO VIENE EFFETTUATA CONTESTUALMENTE ANCHE L'ADESIONE)
*/


/*
CONTROLLO 1 ELIMINATO!!!!!!
*/
--SELECT @CHKRICEV = LSRSER_BOLLO_KEY_ID_RICEV FROM LSRSER_BOLLO
--WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV

--IF @CHKRICEV IS NULL

--BEGIN
--	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE SU LSRSER_BOLLO'
--	RETURN
--END

/*
CONTROLLO 2
*/

SELECT @STATOLOTTO = LSRSER_LOTTO_TIPO_PROVV FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(SELECT MAX(LSRSER_LOTTO_DATA_DECOR) FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @RICEV
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR <= @DATAATTIV)


IF @STATOLOTTO = 'S' OR @STATOLOTTO = 'M' OR @STATOLOTTO = 'R'

BEGIN
	SELECT @MSGERR = '7777 - ' + @RICEV +' SERVIZIO LOTTO SOSPESO/REVOCATO'
	RETURN
END


/*
CONTROLLO 3
*/

SELECT @PROVVFUT = LSRSER_BOLLO_DATA_DECOR,@STATOBOLLOF = LSRSER_BOLLO_STATO
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_DATA_DECOR = @DATAATTIV


IF @PROVVFUT IS NOT NULL

BEGIN
	IF @STATOBOLLOF = '0'
	BEGIN
		SELECT @DESCSTATO = 'ERRORE: ADESIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	IF @STATOBOLLOF = '1'
	BEGIN
		SELECT @DESCSTATO = 'ERRORE: PROVVEDIMENTO DI ATTIVAZIONE/ RIATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	ELSE IF @STATOBOLLOF = '2'
	BEGIN
		SELECT @DESCSTATO = 'ERRORE: PROVVEDIMENTO DI DISATTIVAZIONE PRESENTE IN DATA ' + SUBSTRING(@PROVVFUT,7,2) +'-'+SUBSTRING(@PROVVFUT,5,2) +'-'+SUBSTRING(@PROVVFUT,1,4) 
	END
	SELECT @MSGERR = '6666 - ' + @RICEV + '  ' + @DESCSTATO
	RETURN
END

/*
CONTROLLO 4
*/
SELECT @STATOBOLLOA = LSRSER_BOLLO_STATO ,
	@ASSOCIAZIONE=LSRSER_BOLLO_ASSOCIAZIONE
FROM LSRSER_BOLLO
WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
AND LSRSER_BOLLO_DATA_DECOR =
	(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) 
	FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
	AND LSRSER_BOLLO_DATA_DECOR <= @DATAATTIV)

IF @STATOBOLLOA = '1'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO BOLLO GIA ATTIVATO'
	RETURN
END

IF @STATOBOLLOA ='2'

BEGIN
	SELECT @MSGERR = '5555 - ' + @RICEV +' SERVIZIO BOLLO DISATTIVO'
	RETURN
END


--INIZIO MODIFICA IN DATA 02-05-2001

BEGIN TRANSACTION

SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
				FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @RICEV
				AND LSRLET_COD_SERVIZIO = '05'
				AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'
				AND LSRLET_KEY_DATA_INS = @DATAINS
				AND LSRLET_DECOR_DAL = '00000000'

IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATAATTIV
	WHERE LSRLET_KEY_ID_RICEV = @RICEV
	AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_COD_SERVIZIO = '05'
	AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'

END
ELSE
BEGIN
	INSERT INTO LSRLET VALUES(@RICEV,@DATAINS,@ORAINS,'05','A',@DATAATTIV,'','','00000000',@NOTE,@FIRMA,'V')
END

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET'
	ROLLBACK TRANSACTION
	RETURN
END

--FINE MODIFICA IN DATA 02-05-2001

-- LA RICEVITORIA NON è PRESENTE SU LSRSER_BOLLO, QUINDI OCCORRE EFFETTUARE ANCHE L'ADESIONE
--COME DATA ADESIONE SI UTILIZZA LA DATA OGGI (@DATAINS)
IF @STATOBOLLOA IS NULL
BEGIN
	SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
				FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @RICEV
				AND LSRLET_COD_SERVIZIO = '05'
				AND LSRLET_TIPO_MOVIMENTAZIONE = 'I'
				AND LSRLET_KEY_DATA_INS = @DATAINS
				AND LSRLET_DECOR_DAL = '00000000'

	IF @DATAORAINS <> '' OR @DATAORAINS IS NOT NULL
	BEGIN
		UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATAINS
		WHERE LSRLET_KEY_ID_RICEV = @RICEV
		AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
		AND LSRLET_COD_SERVIZIO = '05'
		AND LSRLET_TIPO_MOVIMENTAZIONE = 'I'
	
	END
	ELSE
	BEGIN
		INSERT INTO LSRLET VALUES(@RICEV,@DATAINS,@ORAINS,'05','I',@DATAINS,'','','00000000',@NOTE,@FIRMA,'V')
	END

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT/UPDATE SU LSRLET'
		ROLLBACK TRANSACTION
		RETURN
	END

	INSERT INTO LSRSER_BOLLO VALUES (@RICEV,@DATAINS,@ORAINS2,'0',@DATAINS,@CANONE,NULL,NULL,NULL,@ASSOCIAZIONE,@FIRMA,'','00000000','Y')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT SU LSRSER_BOLLO'
		ROLLBACK TRANSACTION
		RETURN
	END
END


INSERT INTO LSRSER_BOLLO VALUES (@RICEV,@DATAINS,@ORAINS,'1',@DATAATTIV,@CANONE,NULL,NULL,NULL,@ASSOCIAZIONE,@FIRMA,'','00000000','Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE IN INSERT SU LSRSER_BOLLO'
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	SELECT @MSGERR = '0000 - ' + @RICEV +' OPERAZIONE TERMINATA CORRETTAMENTE'
	COMMIT TRANSACTION
	RETURN
END
GO
