/****** Object:  StoredProcedure [dbo].[ACQUISIZIONE_RAD_GS]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[ACQUISIZIONE_RAD_GS]  

	@RICEV 			CHAR(6),
	@TIPOMOVIMENTAZIONE	CHAR(1),
	@FONTE			CHAR(1),  
	@CODICESERVIZIO CHAR(2),
	@FIRMADOC 			CHAR(17),
	@NOMEFILE			VARCHAR(255),
	@DATAINVIODOC		CHAR(8),
	@DATADOC			CHAR(8),
	@NUMPROTDOC		CHAR(25),
	@STATODOC			CHAR(1),
	@CAUSALE			CHAR(2),
	@ASSOCIAZIONE		CHAR(1),
	@COGNOME			CHAR(24),
	@NOME			CHAR(20),
	@NOTE			CHAR(100),
	@FLAGANAG			CHAR(1),
	@FKDATAINSTIT		CHAR(8),
	@FKORAINSTIT		CHAR(8),
	@FIRMA			CHAR(17),
	@MSGERR 			VARCHAR(100) OUTPUT

 AS

DECLARE 	

@APPORICEV		CHAR(6),
@DATAOGGI   		CHAR(8),
@ORAOGGI  		CHAR(8),
@COGNOMETIT	CHAR(24),
@NOMETIT		CHAR(20),
@FLAGANAGTIT	CHAR(1),
@DATAINSTIT		CHAR(8),
@ORAINSTIT		CHAR(8),
@TIPOPREC 		CHAR(1),
@TIPOPROVV		CHAR(1),
@TITTROVATO   	CHAR(1),
@FLAGOK 		CHAR(1),
@CHKRICEV		CHAR(6)

SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)

--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL NOME FILE è VALORIZZATO, CONTROLLO SE IL NOME/COGNOME DEL TITOLARE PRESENTE SUL FILE è QUELLO DI UN TITOLARE VALIDO
-- 2) CONTROLLO CHE LA RICEVITORIA NON ABBIA GIà UN RAD CON LA STESSA DATA E NUM PROTOCOLLO
-- 3) SE IL FLAGANAG è A 0 VERIFICO CHE NON SIA GIà PRESENTE UN RAD PER LA RICEVITORIA CON FLAG A 0
-- 4) SE IL FLAGANAG è A 1 VERIFICO CHE NON SIA GIà PRESENTE UN RAD PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 5) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT_CONI

SELECT @CHKRICEV = NULL

SELECT @CHKRICEV = LSRTIT_CONI_KEY_ID_RICEV FROM LSRTIT_CONI
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE'
	RETURN
END


--*************************************************************************
--           CONTROLLO 1
--*************************************************************************
/*IF @NOMEFILE <> '' 
BEGIN

	DECLARE CUR_R1 SCROLL CURSOR FOR
	SELECT LSRTIT_CONI_COGNOME, LSRTIT_CONI_NOME, LSRTIT_CONI_KEY_DATA_INS, LSRTIT_CONI_KEY_ORA_INS, LSRTIT_CONI_FLAG_ANAG
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV AND
	  	LSRTIT_CONI_DATA_VALIDITA < @DATAOGGI AND
		  LSRTIT_CONI_FLAG_VALIDITA = 'Y' 
	ORDER BY LSRTIT_CONI_DATA_VALIDITA DESC  
	SELECT @TIPOPREC = ''
	SELECT @FLAGOK = 'N'
	SELECT @TITTROVATO = 'N'

	SELECT @FLAGANAG ='0'
	SELECT @FKDATAINSTIT = '00000000'	
	SELECT @FKORAINSTIT = '00000000'	

	OPEN CUR_R1
	FETCH NEXT FROM CUR_R1
	INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @FLAGANAGTIT
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @TITTROVATO = 'N'
		BEGIN
			IF (@COGNOME = @COGNOMETIT AND @NOME = @NOMETIT)
			BEGIN
				SELECT @FLAGANAG = @FLAGANAGTIT
				SELECT @FKDATAINSTIT	= @DATAINSTIT
				SELECT @FKORAINSTIT = @ORAINSTIT
				SELECT @COGNOME = @COGNOMETIT
				SELECT @NOME = @NOMETIT
				SELECT @TITTROVATO = 'Y'
			END
		END --END IF @TITTROVATO = 'N'
		FETCH NEXT FROM CUR_R1
		INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @FLAGANAGTIT
	END

	CLOSE CUR_R1
	DEALLOCATE CUR_R1

END
*/

IF @NOMEFILE <> '' 
BEGIN

	DECLARE CUR_R1 SCROLL CURSOR FOR
	SELECT LSRTIT_CONI_COGNOME, LSRTIT_CONI_NOME, LSRTIT_CONI_KEY_DATA_INS, LSRTIT_CONI_KEY_ORA_INS, LSRTIT_CONI_FLAG_ANAG, LSRTIT_CONI_TIPO_PROVV
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV AND
	  	LSRTIT_CONI_DATA_VALIDITA < @DATAOGGI AND
		  LSRTIT_CONI_FLAG_VALIDITA = 'Y' 
	ORDER BY LSRTIT_CONI_DATA_VALIDITA DESC  
	SELECT @TIPOPREC = ''
	SELECT @FLAGOK = 'N'
	SELECT @TITTROVATO = 'N'

	SELECT @FLAGANAG ='0'
	SELECT @FKDATAINSTIT = '00000000'	
	SELECT @FKORAINSTIT = '00000000'	

	OPEN CUR_R1
	FETCH NEXT FROM CUR_R1
	INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @FLAGANAGTIT, @TIPOPROVV
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @TITTROVATO = 'N'
		BEGIN
			  --******************************************************************
			  --INIZIO CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			 --******************************************************************
			IF @TIPOPREC = ''
			BEGIN
				SELECT @TIPOPREC = @TIPOPROVV
				SELECT @FLAGOK ='Y'
			END
			ELSE
			BEGIN
				IF @TIPOPREC = 'E' AND @FLAGOK ='Y'
				BEGIN
					SELECT @TIPOPREC = @TIPOPROVV
					SELECT @FLAGOK = 'N'
				END
				ELSE
				BEGIN
					IF ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND (@TIPOPROVV ='I' OR @TIPOPROVV ='C')) OR ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND @TIPOPROVV ='E')
					BEGIN
						SELECT @TIPOPREC = @TIPOPROVV
						SELECT @FLAGOK = 'Y'
					END
					ELSE
	    				BEGIN
	     					SELECT @TIPOPREC = @TIPOPROVV
	     					SELECT @FLAGOK = 'N'
	    				END
	   			END
	  		END
			--******************************************************************
			--FINE CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			--******************************************************************
			-- SE HO TROVATO UN TITOLARE VALIDO INIZIALIZZO TUTTE LE VARIABILI RELATIVE A QUESTO TITOLARE
			IF @FLAGOK = 'Y'
			BEGIN
				IF (@COGNOME = @COGNOMETIT AND @NOME = @NOMETIT)
				BEGIN
					SELECT @FLAGANAG = @FLAGANAGTIT
					SELECT @FKDATAINSTIT	= @DATAINSTIT
					SELECT @FKORAINSTIT = @ORAINSTIT
					SELECT @COGNOME = @COGNOMETIT
					SELECT @NOME = @NOMETIT
					SELECT @TITTROVATO = 'Y'
				END
			END
		END --END IF @TITTROVATO = 'N'
		FETCH NEXT FROM CUR_R1
		INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @FLAGANAGTIT, @TIPOPROVV
	END

	CLOSE CUR_R1
	DEALLOCATE CUR_R1

END


--*************************************************************************
--           CONTROLLO 2
--*************************************************************************
SELECT @APPORICEV = NULL

SELECT @APPORICEV = LSRRAD_GS_KEY_ID_RICEV 
FROM LSRRAD_GS
WHERE LSRRAD_GS_KEY_ID_RICEV = @RICEV
	AND LSRRAD_GS_FONTE = @FONTE	
	AND LSRRAD_GS_DATA_DOC = @DATADOC
	AND LSRRAD_GS_NUM_PROT_DOC = @NUMPROTDOC
	AND LSRRAD_GS_COD_ASSOCIAZIONE = @ASSOCIAZIONE
	AND LSRRAD_GS_CODICE_SERVIZIO = @CODICESERVIZIO

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RICEVITORIA ESISTE UN RAD CON STESSA DATA E PROT.- RAD NON ACQUISITO'
	RETURN
END

--*************************************************************************
--           CONTROLLO 3
--*************************************************************************
IF (@FLAGANAG = '0')
BEGIN
	SELECT @FKDATAINSTIT = NULL	
	SELECT @FKORAINSTIT = NULL	

	SELECT @APPORICEV = LSRRAD_GS_KEY_ID_RICEV 
	FROM LSRRAD_GS
	WHERE LSRRAD_GS_KEY_ID_RICEV = @RICEV
		AND LSRRAD_GS_FLAG_ANAG = '0'
		AND LSRRAD_GS_CODICE_SERVIZIO = @CODICESERVIZIO

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +'PER LA RICEVITORIA ESISTE UN RAD NON ABBINATO - RAD NON ACQUISITO'
		RETURN
	END
END

--*************************************************************************
--           CONTROLLO 4
--*************************************************************************
/*
IF (@FLAGANAG <> '0')
BEGIN

	SELECT @APPORICEV = LSRRAD_GS_KEY_ID_RICEV 
	FROM LSRRAD_GS
	WHERE LSRRAD_GS_KEY_ID_RICEV = @RICEV
		AND LSRRAD_GS_fk_data_ins_tit  =@FKDATAINSTIT
		AND LSRRAD_GS_fk_ORa_ins_tit = @FKORAINSTIT

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +'PER LA RICEVITORIA ESISTE UN RAD ABBINATO - RAD NON ACQUISITO'
		RETURN
	END
END
*/
--*************************************************************************
--           CONTROLLO 5
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_CONI_COGNOME , @NOME = LSRTIT_CONI_NOME
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 


--*************************************************************************
--           CONTROLLO 6
--*************************************************************************

IF @FLAGANAG <> '0' 
BEGIN
	SELECT  @FLAGANAG = LSRTIT_CONI_FLAG_ANAG
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 

--*************************************************************************
--           IL RECORD VIENE INSERITO SU LSRRAD_GS
--*************************************************************************
INSERT INTO LSRRAD_GS VALUES (
	@RICEV, 		
	@DATAOGGI,                 
	@ORAOGGI,  
	@CODICESERVIZIO,                
	@TIPOMOVIMENTAZIONE,
	@FONTE,  
	@FIRMADOC,	
	@NOMEFILE,		
	@DATADOC,	
	@DATADOC,	
	@DATAINVIODOC,	
	@NUMPROTDOC,	
	@ASSOCIAZIONE,	
	@CAUSALE, 
	@STATODOC,	
	@COGNOME,	
	@NOME	,	
	@NOTE,	
	@FLAGANAG,	
	@FKDATAINSTIT,	
	@FKORAINSTIT,	
	@FIRMA	)
IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO RAD - RAD NON ACQUISITO'
	RETURN
END
ELSE
BEGIN
	IF @FLAGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' RAD ACQUISITO MA NON ABBINATO'
	END
	ELSE	
	BEGIN	
		SELECT @MSGERR = '9999 - ' + @RICEV +'RAD  ACQUISITO CORRETTAMENTE'
	END
	RETURN
END
GO
