/****** Object:  StoredProcedure [dbo].[ACQUISIZIONE_NULLA_OSTA_CONI]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE      PROCEDURE [dbo].[ACQUISIZIONE_NULLA_OSTA_CONI]
	@RICEV 			CHAR(6),
	@NOMEFILE			VARCHAR(255),
	@DATA_DOC			CHAR(8),
	@DATA_INVIO_DOC		CHAR(8),
	@NUMPROTDOC		CHAR(25),
	@COGNOME			CHAR(24),
	@NOME			CHAR(20),
	@DATAACCETTAZIONE	CHAR(8),
	@DATAREVOCA		CHAR(8),

	@NUM_CONC_SCOMMESSE	CHAR(10),
	@DATA_CONC_SCOMMESSE	CHAR(8),
	@NUM_AUTORIZZAZIONE	CHAR(10),
	@RIL_AUTORIZZAZIONE	CHAR(20),
	@NUM_CONCESSIONE		CHAR(6),
	@STATODOC			CHAR(1),
	@NOTE			CHAR(100),
	@FLAGANAG			CHAR(1),
	@FKDATAINSTIT		CHAR(8),
	@FKORAINSTIT		CHAR(8),
	@FIRMA			CHAR(17),
	@MSGERR			VARCHAR(100) OUTPUT
 AS



DECLARE 	@APPORICEV		CHAR(6),
		@CHKRICEV		CHAR(6),
		@APPODATA		CHAR(8),
		@DATAOGGI   		CHAR(8),
		@ORAOGGI  		CHAR(8),
		@COGNOMETIT	CHAR(24),
		@NOMETIT		CHAR(20),
		@FLAGANAGTIT	CHAR(1),
		@DATAINSTIT		CHAR(8),
		@ORAINSTIT		CHAR(8),
		@TIPOPREC 		CHAR(1),
		@TIPOPROVV		CHAR(1),
		@TITTROVATO	CHAR(1),
		@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)


--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL NOME FILE è VALORIZZATO, CONTROLLO SE IL NOME/COGNOME DEL TITOLARE PRESENTE SUL FILE è QUELLO DI UN TITOLARE VALIDO
-- 2) SE IL FLAGANAG è A 1 VERIFICO CHE NON SIA GIà PRESENTE UN NULLA OSTA PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 3) SE IL FLAGANAG è A 0 VERIFICO CHE NON SIA GIà PRESENTE UN  NULLA OSTA PER LA RICEVITORIA CON FLAG A 0
-- 4) CONTROLLO CHE LA RICEVITORIA NON ABBIA GIà UN NULLA OSTA CON STESSA DATA
-- 5) CONTROLLO CHE LA DATA DEL NULLA OSTA SIA MAGGIORE DELLA MAX DATA DEI NULLA OSTA PRESENTI PER LA RICEVITORIA
-- 6) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT_CONI
-- 7) INSERISCO IL RECORD SU LSRNUO_CONI


SELECT @CHKRICEV = NULL

SELECT @CHKRICEV = LSRTIT_CONI_KEY_ID_RICEV FROM LSRTIT_CONI
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE'
	RETURN
END

IF LTRIM(RTRIM(@DATAACCETTAZIONE)) = ''
BEGIN
	SELECT @DATAACCETTAZIONE = NULL  
END 



--*************************************************************************
--           STEP 1
--*************************************************************************

IF @NOMEFILE <> '' 
BEGIN

	DECLARE CUR_R1 SCROLL CURSOR FOR
	SELECT LSRTIT_CONI_COGNOME, LSRTIT_CONI_NOME, LSRTIT_CONI_KEY_DATA_INS, LSRTIT_CONI_KEY_ORA_INS, LSRTIT_CONI_FLAG_ANAG, LSRTIT_CONI_TIPO_PROVV
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV AND
	  	LSRTIT_CONI_DATA_VALIDITA < @DATAOGGI AND
		  LSRTIT_CONI_FLAG_VALIDITA = 'Y' 
	ORDER BY LSRTIT_CONI_DATA_VALIDITA DESC  
	SELECT @TIPOPREC = ''
	SELECT @FLAGOK = 'N'
	SELECT @TITTROVATO = 'N'

	SELECT @FLAGANAG ='0'
	SELECT @FKDATAINSTIT = '00000000'	
	SELECT @FKORAINSTIT = '00000000'	

	OPEN CUR_R1
	FETCH NEXT FROM CUR_R1
	INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @FLAGANAGTIT, @TIPOPROVV
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @TITTROVATO = 'N'
		BEGIN
			  --******************************************************************
			  --INIZIO CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			 --******************************************************************
			IF @TIPOPREC = ''
			BEGIN
				SELECT @TIPOPREC = @TIPOPROVV
				SELECT @FLAGOK ='Y'
			END
			ELSE
			BEGIN
				IF @TIPOPREC = 'E' AND @FLAGOK ='Y'
				BEGIN
					SELECT @TIPOPREC = @TIPOPROVV
					SELECT @FLAGOK = 'N'
				END
				ELSE
				BEGIN
					IF ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND (@TIPOPROVV ='I' OR @TIPOPROVV ='C')) OR ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND @TIPOPROVV ='E')
					BEGIN
						SELECT @TIPOPREC = @TIPOPROVV
						SELECT @FLAGOK = 'Y'
					END
					ELSE
	    				BEGIN
	     					SELECT @TIPOPREC = @TIPOPROVV
	     					SELECT @FLAGOK = 'N'
	    				END
	   			END
	  		END
			--******************************************************************
			--FINE CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			--******************************************************************
			-- SE HO TROVATO UN TITOLARE VALIDO INIZIALIZZO TUTTE LE VARIABILI RELATIVE A QUESTO TITOLARE
			IF @FLAGOK = 'Y'
			BEGIN
				IF (@COGNOME = @COGNOMETIT AND @NOME = @NOMETIT)
				BEGIN
					SELECT @FLAGANAG = @FLAGANAGTIT
					SELECT @FKDATAINSTIT	= @DATAINSTIT
					SELECT @FKORAINSTIT = @ORAINSTIT
					SELECT @COGNOME = @COGNOMETIT
					SELECT @NOME = @NOMETIT
					SELECT @TITTROVATO = 'Y'
				END
			END
		END --END IF @TITTROVATO = 'N'
		FETCH NEXT FROM CUR_R1
		INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @FLAGANAGTIT, @TIPOPROVV
	END

	CLOSE CUR_R1
	DEALLOCATE CUR_R1

END



--*************************************************************************
--           STEP 2
--*************************************************************************

SELECT @APPORICEV = NULL

IF (@FLAGANAG <> '0')
BEGIN
	SELECT @APPORICEV = LSRNUO_CONI_KEY_ID_RICEV 
	FROM LSRNUO_CONI
	WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEV
		AND LSRNUO_CONI_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRNUO_CONI_FK_ORA_INS_TIT = @FKORAINSTIT
	
	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RIC. ESISTE UN NULLA OSTA CON STESSO TITOLARE - NULLA OSTA NON ACQUISITO'
		RETURN
	END
END

--*************************************************************************
--           STEP 3
--*************************************************************************
SELECT @APPORICEV = NULL

IF (@FLAGANAG = '0')
BEGIN
	SELECT @FKDATAINSTIT = NULL	
	SELECT @FKORAINSTIT = NULL	

	SELECT @APPORICEV = LSRNUO_CONI_KEY_ID_RICEV 
	FROM LSRNUO_CONI
	WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEV
		AND LSRNUO_CONI_FLAG_ANAG = '0'

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +'PER LA RICEVITORIA ESISTE UN NULLA OSTA NON ABBINATO - NULLA OSTA NON ACQUISITO'
		RETURN
	END
END


--*************************************************************************
--           STEP 4
--*************************************************************************

SELECT @APPORICEV = NULL

SELECT @APPORICEV = LSRNUO_CONI_KEY_ID_RICEV 
FROM LSRNUO_CONI
WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEV
	AND LSRNUO_CONI_DATA_NULLA_OSTA = @DATA_DOC
	AND LSRNUO_CONI_NUM_PROT = @NUMPROTDOC

IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RIC. ESISTE UN NULLA OSTA CON STESSA DATA E PROT - NULLA OSTA NON ACQUISITO'
	RETURN
END


--*************************************************************************
--           STEP 5
--*************************************************************************

SELECT @APPODATA = NULL

SELECT @APPODATA = MAX(LSRNUO_CONI_DATA_NULLA_OSTA )
FROM LSRNUO_CONI
WHERE LSRNUO_CONI_KEY_ID_RICEV = @RICEV
	AND LSRNUO_CONI_COGNOME = @COGNOME
	AND LSRNUO_CONI_NOME = @NOME

IF (@APPODATA <>'' OR @APPODATA IS NOT NULL)
BEGIN

	IF @APPODATA >= @DATA_DOC
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RIC. ESISTE UN NULLA OSTA DATA MAGGIORE - NULLA OSTA NON ACQUISITO'
		RETURN
	END
END


 
--*************************************************************************
--          STEP 6
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_CONI_COGNOME , @NOME = LSRTIT_CONI_NOME
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 


--*************************************************************************
--           CONTROLLO 7
--*************************************************************************

IF @FLAGANAG <> '0' 
BEGIN
	SELECT  @FLAGANAG = LSRTIT_CONI_FLAG_ANAG
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 

--*************************************************************************
--           STEP 8
--*************************************************************************

INSERT INTO lsrnuo_coni VALUES(
	@RICEV, 
	@DATAOGGI, 
	@ORAOGGI, 
	@NOMEFILE, 
	@DATA_DOC, 
	@DATA_INVIO_DOC, 
	@NUMPROTDOC, 
	@DATAACCETTAZIONE,
	@DATAREVOCA,
	@STATODOC, 
	@COGNOME, 
	@NOME, 
	@NUM_CONC_SCOMMESSE, 
	@DATA_CONC_SCOMMESSE, 
	@NUM_AUTORIZZAZIONE, 
	@RIL_AUTORIZZAZIONE, 
	@NUM_CONCESSIONE, 
	@NOTE, 
	@FLAGANAG, 
	@FKDATAINSTIT, 
	@FKORAINSTIT, 
	@FIRMA)

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO NULLA OSTA - DOC. NON ACQUISITO'
	RETURN
END
ELSE
BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' NULLA OSTA ACQUISITO CORRETTAMENTE'
END
GO
