/****** Object:  StoredProcedure [dbo].[ACQUISIZIONE_FIDEJUSSIONE_UNICA_LIS]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE    PROCEDURE [dbo].[ACQUISIZIONE_FIDEJUSSIONE_UNICA_LIS]


	@RICEV 		CHAR(6),
	@NOMEFILE	VARCHAR(255),
	@DATAINVIODOC	CHAR(8),
	@DATADOC	CHAR(8),
	@NUMPROTDOC	CHAR(25),
	@STATODOC	CHAR(1),
	@ASSOCIAZIONE	CHAR(2),
	@IMPORTO	CHAR(20),
	@ANNORIF	CHAR(4),
	@COGNOME	CHAR(24),
	@NOME		CHAR(20),
	@NOTE		CHAR(50),
	@FLAGANAG	CHAR(1),
	@FKDATAINSTIT	CHAR(8),
	@FKORAINSTIT	CHAR(8),
	@FIRMA		CHAR(17),
	
	@MSGERR 		VARCHAR(100) OUTPUT
 AS


DECLARE 	
@DATAOGGI	CHAR(8),
@ORAOGGI	CHAR(8),
@CATEGORIA		CHAR(2),
@SERVIZIO   		CHAR(2),
@ATTIVITA  		CHAR(2),
@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)


/* ACQUISISCO LA FIDEJUSSIONE PER LE BIGLIETTERIE */
SELECT @CATEGORIA = '04'
SELECT @SERVIZIO = '01'
SELECT @ATTIVITA = '  '
EXEC  ACQUISIZIONE_FIDEJUSSIONE_LIS @RICEV, 
					@DATAOGGI,
					@ORAOGGI,
					@CATEGORIA, 
					@SERVIZIO, 
					@ATTIVITA, 
					@NOMEFILE, 
					@DATAINVIODOC, 
					@DATADOC, 
					@NUMPROTDOC, 
					@STATODOC, 
					@ASSOCIAZIONE, 
					@IMPORTO, 
					@ANNORIF, 
					@COGNOME, 
					@NOME, 
					@NOTE, 
					@FLAGANAG, 
					@FKDATAINSTIT, 
					@FKORAINSTIT, 
					@FIRMA, 
					@MSGERR OUTPUT 
             

IF @MSGERR like '9999%'
BEGIN
        RETURN
END

ELSE
BEGIN

	/* ACQUISISCO LA FIDEJUSSIONE PER LE MULTE */
	SELECT @CATEGORIA = '02'
	SELECT @SERVIZIO = '03'
	SELECT @ATTIVITA = '  '
	EXEC  ACQUISIZIONE_FIDEJUSSIONE_LIS @RICEV, 
						@DATAOGGI,
						@ORAOGGI,
						@CATEGORIA, 
						@SERVIZIO, 
						@ATTIVITA, 
						@NOMEFILE, 
						@DATAINVIODOC, 
						@DATADOC, 
						@NUMPROTDOC, 
						@STATODOC, 
						@ASSOCIAZIONE, 
						@IMPORTO, 
						@ANNORIF, 
						@COGNOME, 
						@NOME, 
						@NOTE, 
						@FLAGANAG, 
						@FKDATAINSTIT, 
						@FKORAINSTIT, 
						@FIRMA, 
						@MSGERR OUTPUT 


	IF @MSGERR like '9999%'
	BEGIN
	        RETURN
	END
	
	ELSE
	BEGIN
	
		/* ACQUISISCO LA FIDEJUSSIONE PER LE RICARICHE */
		SELECT @CATEGORIA = '01'
		SELECT @SERVIZIO = '02'
		SELECT @ATTIVITA = '  '
		EXEC  ACQUISIZIONE_FIDEJUSSIONE_LIS @RICEV, 
							@DATAOGGI,
							@ORAOGGI,
							@CATEGORIA, 
							@SERVIZIO, 
							@ATTIVITA, 
							@NOMEFILE, 
							@DATAINVIODOC, 
							@DATADOC, 
							@NUMPROTDOC, 
							@STATODOC, 
							@ASSOCIAZIONE, 
							@IMPORTO, 
							@ANNORIF, 
							@COGNOME, 
							@NOME, 
							@NOTE, 
							@FLAGANAG, 
							@FKDATAINSTIT, 
							@FKORAINSTIT, 
							@FIRMA, 
							@MSGERR OUTPUT 
	
	END
END
GO
