/****** Object:  StoredProcedure [dbo].[ACQUISIZIONE_FIDEJUSSIONE_GP]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ACQUISIZIONE_FIDEJUSSIONE_GP]


	@RICEV 		CHAR(6),
	@Codice_Servizio CHAR(2),
	@NOMEFILE	VARCHAR(255),
	@DATAINVIODOC	CHAR(8),
	@DATADOC	CHAR(8),
	@NUMPROTDOC	CHAR(25),
	@ASSOCIAZIONE	CHAR(2),
	@IMPORTO	CHAR(20),
	@ANNORIF	CHAR(4),
	@DATAINIZIO		CHAR(8),
	@DATAFINE		CHAR(8),
	@COGNOME	CHAR(24),
	@NOME		CHAR(20),
	@NOTE		CHAR(100),
	@FLAGANAG	CHAR(1),
	@FKDATAINSTIT	CHAR(8),
	@FKORAINSTIT	CHAR(8),
	@FIRMA		CHAR(17),
	
	@MSGERR 	VARCHAR(100) OUTPUT
 AS


DECLARE 	

@APPORICEV		CHAR(6),
@CHKRICEV		CHAR(6),
@DATAOGGI   		CHAR(8),
@ORAOGGI  		CHAR(8),
@COGNOMETIT		CHAR(24),
@NOMETIT		CHAR(20),
@FLAGANAGTIT		CHAR(1),
@DATAINSTIT		CHAR(8),
@ORAINSTIT		CHAR(8),
@TIPOPREC 		CHAR(1),
@TIPOPROVV		CHAR(1),
@TITTROVATO 		CHAR(1),
@FLAGOK 		CHAR(1)


SELECT @DATAOGGI = CONVERT (VARCHAR(10), GETDATE(),112)
SELECT @ORAOGGI =
	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),12,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),15,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),18,2)+
 	SUBSTRING(CONVERT (VARCHAR(22), GETDATE(),121),21,2)

IF (@ANNORIF = '' OR @ANNORIF IS NULL)
BEGIN
	SELECT @ANNORIF = SUBSTRING(CONVERT (VARCHAR(10), GETDATE(),112),1,4)
END  



--EFFETTUO I SEGUENTI CONTROLLI:
-- 1) SE IL NOME FILE è VALORIZZATO, CONTROLLO SE IL NOME/COGNOME DEL TITOLARE PRESENTE SUL FILE è QUELLO DI UN TITOLARE VALIDO
-- 2) CONTROLLO CHE LA RICEVITORIA NON ABBIA GIà UN RAD CON LA STESSA DATA E NUM PROTOCOLLO
-- 3) SE IL FLAGANAG è A 0 VERIFICO CHE NON SIA GIà PRESENTE UN RAD PER LA RICEVITORIA CON FLAG A 0
-- 4) SE IL FLAGANAG è A 1 VERIFICO CHE NON SIA GIà PRESENTE UN RAD PER IL RICEVITORE E LA RICEVITORIA IN QUESTIONE
-- 5) SE IL NOME/COGNOME NON è VALORIZZATO, MA è VALORIZZATO LA FK DEL TIT, PRENDO I VALORI DA LSRTIT_CONI_CONI

SELECT @CHKRICEV = NULL

SELECT @CHKRICEV = LSRTIT_CONI_KEY_ID_RICEV FROM LSRTIT_CONI
WHERE LSRTIT_CONI_KEY_ID_RICEV = @RICEV

IF @CHKRICEV IS NULL

BEGIN
	SELECT @MSGERR = '8888 - ' + @RICEV +' RICEVITORIA INESISTENTE'
	RETURN
END


--*************************************************************************
--           CONTROLLO 1
--*************************************************************************
IF @NOMEFILE <> '' 
BEGIN

	DECLARE CUR_R1 SCROLL CURSOR FOR
	SELECT LSRTIT_CONI_COGNOME, LSRTIT_CONI_NOME, LSRTIT_CONI_KEY_DATA_INS, LSRTIT_CONI_KEY_ORA_INS, LSRTIT_CONI_FLAG_ANAG, LSRTIT_CONI_TIPO_PROVV
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV AND
	  	LSRTIT_CONI_DATA_VALIDITA < @DATAOGGI AND
		  LSRTIT_CONI_FLAG_VALIDITA = 'Y' 
	ORDER BY LSRTIT_CONI_DATA_VALIDITA DESC  
	SELECT @TIPOPREC = ''
	SELECT @FLAGOK = 'N'
	SELECT @TITTROVATO = 'N'

	SELECT @FLAGANAG ='0'
	SELECT @FKDATAINSTIT = '00000000'	
	SELECT @FKORAINSTIT = '00000000'	

	OPEN CUR_R1
	FETCH NEXT FROM CUR_R1
	INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @FLAGANAGTIT, @TIPOPROVV
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @TITTROVATO = 'N'
		BEGIN
			  --******************************************************************
			  --INIZIO CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			 --******************************************************************
			IF @TIPOPREC = ''
			BEGIN
				SELECT @TIPOPREC = @TIPOPROVV
				SELECT @FLAGOK ='Y'
			END
			ELSE
			BEGIN
				IF @TIPOPREC = 'E' AND @FLAGOK ='Y'
				BEGIN
					SELECT @TIPOPREC = @TIPOPROVV
					SELECT @FLAGOK = 'N'
				END
				ELSE
				BEGIN
					IF ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND (@TIPOPROVV ='I' OR @TIPOPROVV ='C')) OR ((@TIPOPREC = 'I' OR @TIPOPREC = 'C') AND @TIPOPROVV ='E')
					BEGIN
						SELECT @TIPOPREC = @TIPOPROVV
						SELECT @FLAGOK = 'Y'
					END
					ELSE
	    				BEGIN
	     					SELECT @TIPOPREC = @TIPOPROVV
	     					SELECT @FLAGOK = 'N'
	    				END
	   			END
	  		END
			--******************************************************************
			--FINE CONTROLLO SE IL RECORD RAPPRESENTA UN TITOLARE VALIDO
			--******************************************************************
			-- SE HO TROVATO UN TITOLARE VALIDO INIZIALIZZO TUTTE LE VARIABILI RELATIVE A QUESTO TITOLARE
			IF @FLAGOK = 'Y'
			BEGIN
				IF (@COGNOME = @COGNOMETIT AND @NOME = @NOMETIT)
				BEGIN
					SELECT @FLAGANAG = @FLAGANAGTIT
					SELECT @FKDATAINSTIT	= @DATAINSTIT
					SELECT @FKORAINSTIT = @ORAINSTIT
					SELECT @COGNOME = @COGNOMETIT
					SELECT @NOME = @NOMETIT
					SELECT @TITTROVATO = 'Y'
				END
			END
		END --END IF @TITTROVATO = 'N'
		FETCH NEXT FROM CUR_R1
		INTO @COGNOMETIT, @NOMETIT, @DATAINSTIT, @ORAINSTIT, @FLAGANAGTIT, @TIPOPROVV
	END

	CLOSE CUR_R1
	DEALLOCATE CUR_R1

END


--*************************************************************************
--           CONTROLLO 2
--*************************************************************************

SELECT @APPORICEV =  NULL
SELECT @APPORICEV = lsrfid_gp_KEY_ID_RICEV 
FROM lsrfid_gp
WHERE lsrfid_gp_KEY_ID_RICEV = @RICEV
	AND lsrfid_gp_DATA_DOC = @DATADOC
	AND lsrfid_gp_NUM_PROT_DOC = @NUMPROTDOC
	AND lsrfid_gp_ID_SOC = @ASSOCIAZIONE
	AND lsrfid_gp_CODICE_SERVIZIO=@CODICE_SERVIZIO
IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RICEVITORIA ESISTE UNA FID. CON STESSA DATA E PROT.- FIDEJUSSIONE NON ACQUISITA'
	RETURN
END

--*************************************************************************
--           CONTROLLO 3
--*************************************************************************
IF (@FLAGANAG = '0')
BEGIN
	SELECT @FKDATAINSTIT = NULL	
	SELECT @FKORAINSTIT = NULL	

	SELECT @APPORICEV = lsrfid_gp_KEY_ID_RICEV 
	FROM lsrfid_gp
	WHERE lsrfid_gp_KEY_ID_RICEV = @RICEV
		AND lsrfid_gp_FLAG_ANAG = '0'
		AND lsrfid_gp_CODICE_SERVIZIO=@CODICE_SERVIZIO

	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +'PER LA RICEVITORIA ESISTE UNA FID. NON ABBINATA - FIDEJUSSIONE NON ACQUISITA'
		RETURN
	END
END


--*************************************************************************
--           CONTROLLO 4
--*************************************************************************
IF (@FLAGANAG <> '0')
BEGIN
	SELECT @APPORICEV = lsrfid_gp_KEY_ID_RICEV 
	FROM lsrfid_gp
	WHERE lsrfid_gp_KEY_ID_RICEV = @RICEV
		AND lsrfid_gp_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND lsrfid_gp_FK_ORA_INS_TIT = @FKORAINSTIT
		AND lsrfid_gp_ANNO_RIF = @ANNORIF
		AND lsrfid_gp_CODICE_SERVIZIO=@CODICE_SERVIZIO


	IF (@APPORICEV <>'' OR @APPORICEV IS NOT NULL)
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' PER LA RIC. ESISTE UNA FID. PER IL TIT. E ANNO RIF. INDICATI - FID. NON ACQUISITA'
		RETURN
	END
END


--*************************************************************************
--           CONTROLLO 5
--*************************************************************************

IF @FLAGANAG <> '0' AND (@COGNOME = '' OR @COGNOME IS NULL)
BEGIN
	SELECT  @COGNOME = LSRTIT_CONI_COGNOME , @NOME = LSRTIT_CONI_NOME
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 

--*************************************************************************
--           CONTROLLO 6
--*************************************************************************

IF @FLAGANAG <> '0' 
BEGIN
	SELECT  @FLAGANAG = LSRTIT_CONI_FLAG_ANAG
	FROM LSRTIT_CONI
	WHERE LSRTIT_CONI_KEY_ID_RICEV=@RICEV 
		AND LSRTIT_CONI_KEY_DATA_INS = @FKDATAINSTIT
		AND LSRTIT_CONI_KEY_ORA_INS = @FKORAINSTIT

END 



--*************************************************************************
--           IL RECORD VIENE INSERITO SU lsrfid_gp
--*************************************************************************
INSERT INTO lsrfid_gp VALUES (
	@RICEV, 		
	@DATAOGGI,
	@ORAOGGI,
	@CODICE_SERVIZIO,
	@NOMEFILE,			
	@DATADOC,		
	@DATAINVIODOC,	
	@NUMPROTDOC,	
	@ASSOCIAZIONE,	
	@COGNOME,	
	@NOME	,	
	@IMPORTO,
	@ANNORIF,
	@DATAINIZIO,
	@DATAFINE,
	@NOTE	,	
	@FLAGANAG,	
	@FKDATAINSTIT,	
	@FKORAINSTIT,	
	@FIRMA	)


IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = '9999 - ' + @RICEV +' ERRORE INSERIMENTO FIDEJUSSIONE - FIDEJUSSIONE NON ACQUISITA'
	RETURN
END
ELSE
BEGIN
	IF @FLAGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9999 - ' + @RICEV +' FIDEJUSSIONE ACQUISITA MA NON ABBINATA'
	END
	ELSE	
	BEGIN	
		SELECT @MSGERR = '9999 - ' + @RICEV +' FIDEJUSSIONE ACQUISITA CORRETTAMENTE'
	END
	RETURN
END
GO
