/****** Object:  StoredProcedure [dbo].[ATTIVAZIONI_PACCHETTO]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ATTIVAZIONI_PACCHETTO]  
			@RICEV			CHAR(6),
			@CODSER 			CHAR(2), 
			@CON	 			CHAR(15), 
			@CAS	 			CHAR(15), 
			@FID	 			CHAR(15), 
			@APS	 			CHAR(15), 
			@RAD	 			CHAR(15), 
			@CANONE			CHAR(1),
			@NOTE			CHAR(50),
			@RC		 		CHAR(70)  OUTPUT


AS


DECLARE

@STATOOGGI		CHAR(1),
@STATODOM		CHAR(1),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@DATAORAINS	CHAR(16),
@DATARIATTIV	CHAR(8),
@OPERAZIONE 	CHAR(1),
@ASSOCIAZIONE 	CHAR(1)


SELECT @DATARIATTIV = CONVERT(CHAR,GETDATE() + 1,112)
SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)

SELECT @RICEV = UPPER(@RICEV)


SELECT @CON = RTRIM(@CON)
SELECT @CAS = RTRIM(@CAS)
SELECT @FID = RTRIM(@FID)
SELECT @APS = RTRIM(@APS)
SELECT @RAD = RTRIM(@RAD)
SELECT @OPERAZIONE = 'A'


SELECT @STATODOM = NULL
SELECT @STATOOGGI = NULL

--VERIFICO LO STATO DEL SERVIZIO
IF @CODSER = '02'
BEGIN
	SELECT @STATODOM = LSRSER_F101_STATO
	FROM LSRSER_F101
	WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
	AND LSRSER_F101_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	AND LSRSER_F101_FLAG_VALIDITA = 'Y'


	IF @STATODOM = '' OR @STATODOM IS NULL
	BEGIN

		BEGIN TRANSACTION

		SELECT @STATOOGGI = LSRSER_F101_STATO
		FROM LSRSER_F101
		WHERE LSRSER_F101_KEY_ID_RICEV = @RICEV
		AND LSRSER_F101_DATA_DECOR =
			(SELECT MAX(LSRSER_F101_DATA_DECOR) FROM LSRSER_F101 
			WHERE LSRSER_F101_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
			AND LSRSER_F101_FLAG_VALIDITA = 'Y'
			AND LSRSER_F101_KEY_ID_RICEV = @RICEV)
		AND LSRSER_F101_FLAG_VALIDITA = 'Y'
			
		IF @STATOOGGI = '0'
		BEGIN
			EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,'ANATEAM'

			IF @@ERROR <> 0
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV +' ERRORE IN ESECUZIONE SCRIVI_LSRLET'
				ROLLBACK TRANSACTION
				RETURN @RC				
			END

			SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
			FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @RICEV
			AND LSRLET_COD_SERVIZIO = '02'
			AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'
			AND LSRLET_KEY_DATA_INS = @DATAINS
			AND LSRLET_DECOR_DAL = '00000000'

			UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATARIATTIV,
			LSRLET_NOTE = @NOTE
			WHERE LSRLET_KEY_ID_RICEV = @RICEV
			AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
			AND LSRLET_COD_SERVIZIO = '02'
			AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'


			IF @@ERROR <> 0 
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV +' ERRORE IN UPDATE LSRLET'
				ROLLBACK TRANSACTION
				RETURN @RC
			END

			INSERT INTO LSRSER_F101 VALUES 
			(@RICEV,@DATAINS,@ORAINS,'1',@DATARIATTIV,null,null,null,@ASSOCIAZIONE,'ANATEAM',@NOTE,'00000000','Y')

			IF @@ERROR <> 0 
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV + ' ' + ' ERRORE IN INSERT SU LSRSER_F101'
				ROLLBACK TRANSACTION
				RETURN @RC
			END
			ELSE
			BEGIN
				SELECT @RC = '0000 - ' + @RICEV +' OPERAZIONE TERMINATA CORRETTAMENTE'
				COMMIT TRANSACTION
				RETURN @RC
			END
		END
		ELSE
		BEGIN
			SELECT @RC = 'RICEVITORIA GIA" ATTIVATA'
			ROLLBACK TRANSACTION
			RETURN @RC
		END
	END
END
ELSE IF @CODSER = '05'
BEGIN
	IF @CANONE = 'S'
	BEGIN
		SELECT @CANONE = 'Y'
	END

	SELECT @STATODOM = LSRSER_BOLLO_STATO
	FROM LSRSER_BOLLO
	WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
	AND LSRSER_BOLLO_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'

	IF @STATODOM = '' OR @STATODOM IS NULL
	BEGIN

		BEGIN TRANSACTION

		SELECT @STATOOGGI = LSRSER_BOLLO_STATO, @ASSOCIAZIONE = LSRSER_BOLLO_ASSOCIAZIONE
		FROM LSRSER_BOLLO
		WHERE LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
		AND LSRSER_BOLLO_DATA_DECOR =
			(SELECT MAX(LSRSER_BOLLO_DATA_DECOR) FROM LSRSER_BOLLO
			WHERE LSRSER_BOLLO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
			AND LSRSER_BOLLO_KEY_ID_RICEV = @RICEV
			AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y')
		AND LSRSER_BOLLO_FLAG_VALIDITA = 'Y'
			
		IF @STATOOGGI = '0'
		BEGIN
			EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,'ANATEAM'

			IF @@ERROR <> 0
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV +' ERRORE IN ESECUZIONE SCRIVI_LSRLET'
				ROLLBACK TRANSACTION
				RETURN @RC				
			END

			SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
			FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @RICEV
			AND LSRLET_COD_SERVIZIO = '05'
			AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'
			AND LSRLET_KEY_DATA_INS = @DATAINS
			AND LSRLET_DECOR_DAL = '00000000'

			UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATARIATTIV,
			LSRLET_NOTE = @NOTE
			WHERE LSRLET_KEY_ID_RICEV = @RICEV
			AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
			AND LSRLET_COD_SERVIZIO = '05'
			AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'


			IF @@ERROR <> 0 
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV +' ERRORE IN UPDATE LSRLET'
				ROLLBACK TRANSACTION
				RETURN @RC
			END

			INSERT INTO LSRSER_BOLLO VALUES 
			(@RICEV,@DATAINS,@ORAINS,'1',@DATARIATTIV,@CANONE,null,null,null,@ASSOCIAZIONE,'ANATEAM',@NOTE,'00000000','Y')

			IF @@ERROR <> 0 
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV + ' ' + ' ERRORE IN INSERT SU LSRSER_BOLLO'
				ROLLBACK TRANSACTION
				RETURN @RC
			END
			ELSE
			BEGIN
				SELECT @RC = '0000 - ' + @RICEV +' OPERAZIONE TERMINATA CORRETTAMENTE'
				COMMIT TRANSACTION
				RETURN @RC
			END
		END
		ELSE
		BEGIN
			SELECT @RC = 'RICEVITORIA GIA" ATTIVATA'
			ROLLBACK TRANSACTION
			RETURN @RC
		END
	END
END
ELSE IF @CODSER = '08'
BEGIN
	SELECT @STATODOM = LSRSER_TRIS_STATO
	FROM LSRSER_TRIS
	WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
	AND LSRSER_TRIS_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'

	IF @STATODOM = '' OR @STATODOM IS NULL
	BEGIN

		BEGIN TRANSACTION

		SELECT @STATOOGGI = LSRSER_TRIS_STATO,
		@ASSOCIAZIONE = LSRSER_TRIS_ASSOCIAZIONE
		FROM LSRSER_TRIS
		WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
		AND LSRSER_TRIS_DATA_DECOR =
			(SELECT MAX(LSRSER_TRIS_DATA_DECOR) FROM LSRSER_TRIS
			WHERE LSRSER_TRIS_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
			AND LSRSER_TRIS_KEY_ID_RICEV = @RICEV
			AND LSRSER_TRIS_FLAG_VALIDITA = 'Y')
		AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
			
		IF @STATOOGGI = '0'
		BEGIN
			EXECUTE SCRIVI_LSRLET @RICEV, @CODSER,@CON,@CAS,@FID,@APS,@RAD,@DATAINS,@ORAINS,@OPERAZIONE,'ANATEAM'

			IF @@ERROR <> 0
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV +' ERRORE IN ESECUZIONE SCRIVI_LSRLET'
				ROLLBACK TRANSACTION
				RETURN @RC				
			END

			SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS)
			FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @RICEV
			AND LSRLET_COD_SERVIZIO = '08'
			AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'
			AND LSRLET_KEY_DATA_INS = @DATAINS
			AND LSRLET_DECOR_DAL = '00000000'

			UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATARIATTIV,
			LSRLET_NOTE = @NOTE
			WHERE LSRLET_KEY_ID_RICEV = @RICEV
			AND LSRLET_KEY_DATA_INS+LSRLET_KEY_ORA_INS = @DATAORAINS
			AND LSRLET_COD_SERVIZIO = '08'
			AND LSRLET_TIPO_MOVIMENTAZIONE = 'A'


			IF @@ERROR <> 0 
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV +' ERRORE IN UPDATE LSRLET'
				ROLLBACK TRANSACTION
				RETURN @RC
			END

			INSERT INTO LSRSER_TRIS VALUES 
			(@RICEV,@DATAINS,@ORAINS,'1',@DATARIATTIV,null,null,null,@ASSOCIAZIONE,'ANATEAM',@NOTE,'00000000','Y')

			IF @@ERROR <> 0 
			BEGIN
				SELECT @RC = '9999 - ' + @RICEV + ' ' + ' ERRORE IN INSERT SU LSRSER_TRIS'
				ROLLBACK TRANSACTION
				RETURN @RC
			END
			ELSE
			BEGIN
				SELECT @RC = '0000 - ' + @RICEV +' OPERAZIONE TERMINATA CORRETTAMENTE'
				COMMIT TRANSACTION
				RETURN @RC
			END
		END
		ELSE
		BEGIN
			SELECT @RC = 'RICEVITORIA GIA" ATTIVATA'
			ROLLBACK TRANSACTION
			RETURN @RC
		END
	END
END
GO
