/****** Object:  StoredProcedure [dbo].[ANA_REP_STAT_CONNOABB]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ANA_REP_STAT_CONNOABB] 
@NOMEQUERY         	CHAR(30)
AS 
BEGIN
--* CONTRATTI NON ABBINATI *******************
	IF @NOMEQUERY = 'CONNOABB_GENERALE'
	BEGIN
		--- GENERALE
		select count(*) from lsrcon_gev
		WHERE lsrcon_gev_FLAG_ANAG = '0'
	END 
	ELSE
	IF @NOMEQUERY = 'CONNOABB_LOTTISTI'
	BEGIN
		-- LOTTISTI  
		select COUNT(*) from lsrcon_gev
		WHERE LSRCON_GEV_KEY_ID_RICEV LIKE '3%'
		AND lsrcon_gev_FLAG_ANAG = '0'

	END 
	ELSE
	IF @NOMEQUERY = 'CONNOABB_TOTORICEVITORI'
	BEGIN
		--- TOTORICEVITORI
		select COUNT(*) from lsrcon_gev
		WHERE LSRCON_GEV_KEY_ID_RICEV LIKE '1%'
		AND lsrcon_gev_FLAG_ANAG = '0'
	END 
	ELSE
	IF @NOMEQUERY = 'CONNOABB_POSGIALLO'
	BEGIN
		--- POS GIALLO
		select COUNT(*) from lsrcon_gev
		WHERE LSRCON_GEV_KEY_ID_RICEV LIKE '9%'
                      AND lsrcon_gev_FLAG_ANAG = '0'

	END 
	ELSE
	IF @NOMEQUERY = 'CONNOABB_POSMARRONE'
	BEGIN
		--- POS MARRONE
		select COUNT(*) from lsrcon_gev
		WHERE  LSRCON_GEV_KEY_ID_RICEV LIKE '4%'
		AND lsrcon_gev_FLAG_ANAG = '0'

	END 
	ELSE
	IF @NOMEQUERY = 'CONNOABB_LOTTEL'
	BEGIN

		--- LOTTERIE TELEMATICHE
		select COUNT(*) from lsrcon_gev
		WHERE lsrcon_gev_COD_LOTTO  LIKE 'LI%'
		AND lsrcon_gev_FLAG_ANAG = '0'

	END 
END
GO
