/****** Object:  StoredProcedure [dbo].[ANA_REP_SITUAZCONPOSGIALLO]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE            PROCEDURE [dbo].[ANA_REP_SITUAZCONPOSGIALLO]  
AS 
BEGIN

SELECT 
LSRCON_GEV_COD_LOTTO,
LSRCON_GEV_COGNOME,
LSRCON_GEV_NOME,
LSRCON_GEV_PROVINCIA,
TFIDEUSSIONE.SOCASSICURATRICE,
TDELEGARID.RICEV,
LSRCON_GEV_NOTE


FROM LSRCON_GEV 
	LEFT OUTER JOIN 
	(SELECT LSRSOC_DESCRIZIONE AS SOCASSICURATRICE, LSRFID_GEV_key_id_ricev 
         FROM LSRFID_GEV, LSRSOC
         WHERE LSRFID_GEV_FLAG_ANAG = '1'
         AND LSRFID_GEV_ID_SOC = LSRSOC_KEY_ID_SOC
         AND lsrfid_gev_anno_rif = Year(CONVERT(CHAR, GETDATE(), 112)) ) as TFIDEUSSIONE
         ON (LSRCON_GEV.LSRCON_GEV_key_id_ricev = TFIDEUSSIONE.LSRFID_GEV_key_id_ricev) 
	LEFT OUTER JOIN 
	(SELECT DISTINCT LCR01A_DATA_INIZIO_VAL AS RICEV,lcr01a_key_id_ricev  FROM  Riscossioni.dbo.LCR01A
         WHERE LCR01A_DATA_INIZIO_VAL <= CONVERT(CHAR, GETDATE(), 112)
         AND LCR01A_TIPO_GIOCO='09'
         AND LCR01A_KEY_DATA_FINE_VAL = '99999999') as TDELEGARID
         ON (LSRCON_GEV.LSRCON_GEV_cod_lotto = TDELEGARID.lcr01a_key_id_ricev) 
WHERE LSRCON_GEV_FLAG_ANAG = '1'
AND (LSRCON_GEV_COD_LOTTO BETWEEN 'A00001' AND  'A99999' OR LSRCON_GEV_COD_LOTTO LIKE 'B0%' OR LSRCON_GEV_COD_LOTTO LIKE 'B2%' )
AND LSRCON_GEV_COD_LOTTO NOT IN (
	SELECT lsrser_GeV_key_id_ricev
	FROM LSRSER_GEV A
	WHERE LSRSER_GEV_DATA_DECOR =
	(
		SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV
		WHERE LSRSER_GEV_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
		AND lsrser_GeV_key_id_ricev = A.lsrser_GeV_key_id_ricev
		AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	)
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_STATO = '1'
)
AND ((LSRCON_GEV_NOTE NOT LIKE '%RINUNC%' )
AND LSRCON_GEV_NOTE NOT LIKE '%REVOC%LTM%2%')
AND NOT (TFIDEUSSIONE.SOCASSICURATRICE is not null AND TDELEGARID.RICEV  is not null)
ORDER BY 1


END
GO
