/****** Object:  StoredProcedure [dbo].[SCRIVI_LSRLET_ST]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[SCRIVI_LSRLET_ST]  
			@RICEV			CHAR(6),
			@CON	 			CHAR(15), 
			@TLP	 			CHAR(15), 
			@NUO	 			CHAR(15), 
			@FID	 			CHAR(15), 
			@RAD	 			CHAR(15), 
			@RID	 			CHAR(15), 
			@ANNOINIZIOCAMPIONATO	CHAR(4),
			@DATAINS			CHAR(8),
			@ORAINS			CHAR(8),
			@TIPOMOV			CHAR(1),
			@FIRMA	 		CHAR(17)


AS

DECLARE		@IDDOC			CHAR(16),
		@RICERIN			CHAR(6),
		@DATAAPPO	CHAR(8),
		@DATA1	CHAR(8),
		@RADFONTE		CHAR(1),
		@RADCAUSALELTM		CHAR(1)


IF @CON <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRCON_ST_KEY_DATA_INS +  LSRCON_ST_KEY_ORA_INS 
	FROM LSRCON_ST 
	WHERE LSRCON_ST_KEY_ID_RICEV = @RICEV
		AND LSRCON_ST_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_ST VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRCON_ST',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @TLP <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRTLP_ST_KEY_DATA_INS +  LSRTLP_ST_KEY_ORA_INS 
	FROM LSRTLP_ST 
	WHERE LSRTLP_ST_KEY_ID_RICEV = @RICEV
		AND LSRTLP_ST_FLAG_ANAG = '1'

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_ST VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRTLP_ST',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @NUO <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRNUO_ST_KEY_DATA_INS +  LSRNUO_ST_KEY_ORA_INS 
	FROM LSRNUO_ST 
	WHERE LSRNUO_ST_KEY_ID_RICEV = @RICEV
		AND LSRNUO_ST_FLAG_ANAG = '1'
		AND LSRNUO_ST_data_accettazione <> '00000000'
		AND LSRNUO_ST_data_accettazione is not null

	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_ST VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRNUO_ST',@IDDOC,'00000000','',@FIRMA,'')
	END
END

IF @FID <> '0'
BEGIN
	SELECT @IDDOC = NULL

	SELECT @IDDOC =  LSRFID_CONI_KEY_DATA_INS +  LSRFID_CONI_KEY_ORA_INS 
	FROM LSRFID_CONI
	WHERE LSRFID_CONI_KEY_ID_RICEV = @RICEV
		AND LSRFID_CONI_FLAG_ANAG = '1'
		AND LSRFID_CONI_ANNO_RIF = @ANNOINIZIOCAMPIONATO


	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_ST VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRFID_CONI',@IDDOC,'00000000','',@FIRMA,'')
	END

END

IF @RAD <> '0'
BEGIN

	SELECT @IDDOC = NULL


	IF @TIPOMOV='R'
	BEGIN
		--******************************************--	
		-- PALETTI: LA CAUSALE DI RIATTIVAZIONE E'  --	
		-- QUELLA UGUALE E CONTRARIA ALLA PRIMA	    --
		-- CAUSALE DI DISATTIVAZIONE                --
		--******************************************--	
		
		--PRENDO LA DATA DI PRIMA DISATTIVAZIONE
		SELECT @DATA1 = MAX(LSRSER_ST_DATA_DECOR) 
		FROM LSRSER_ST B
		WHERE LSRSER_ST_FT_VOS <> '00000000' 
			AND LSRSER_ST_FLAG_VALIDITA = 'Y' 
			AND LSRSER_ST_STATO = '1' 
			AND LSRSER_ST_KEY_ID_RICEV =  @RICEV
		GROUP BY LSRSER_ST_KEY_ID_RICEV, LSRSER_ST_STATO 
	
		SELECT @DATAAPPO = MIN(LSRSER_ST_DATA_DECOR) 
		FROM LSRSER_ST A 
		WHERE A.LSRSER_ST_FT_VOS <> '00000000' 
			AND A.LSRSER_ST_FLAG_VALIDITA = 'Y' 
			AND A.LSRSER_ST_STATO = '2' 
			AND A.LSRSER_ST_DATA_DECOR >=  @DATA1
			AND A.LSRSER_ST_KEY_ID_RICEV = @RICEV 

/*
		SELECT @DATAAPPO = 
			(SELECT MIN(LSRSER_ST_DATA_DECOR) DATA 
			FROM LSRSER_ST A 
			WHERE A.LSRSER_ST_FT_VOS <> '00000000' 
				AND A.LSRSER_ST_FLAG_VALIDITA = 'Y' 
				AND A.LSRSER_ST_STATO = '2' 
				AND A.LSRSER_ST_DATA_DECOR >=  MAX(B.LSRSER_ST_DATA_DECOR) 
				AND A.LSRSER_ST_KEY_ID_RICEV = @RICEV ) 
		FROM LSRSER_ST B 
		WHERE LSRSER_ST_FT_VOS <> '00000000' 
			AND LSRSER_ST_FLAG_VALIDITA = 'Y' 
			AND LSRSER_ST_STATO = '1' 
			AND LSRSER_ST_KEY_ID_RICEV =  @RICEV
		GROUP BY LSRSER_ST_KEY_ID_RICEV, LSRSER_ST_STATO 
*/


		-- PRENDO IL DOC RAD CHE HA GENERATO LA DISATTIVAZIONE
		SELECT @RADFONTE = lsrrad_st_fonte, 
			@RADCAUSALELTM = lsrrad_st_causale_lottomatica
		FROM LSRRAD_ST  
		WHERE LSRRAD_ST_KEY_ID_RICEV  =  @RICEV
			AND LSRRAD_ST_KEY_DATA_INS + LSRRAD_ST_KEY_ORA_INS = (
				SELECT  LSRLET_ST_FK_TAB_DOCUMENTO 
				FROM LSRLET_ST 
				WHERE LSRLET_ST_KEY_ID_RICEV  = @RICEV
					AND LSRLET_ST_TIPO_MOVIMENTAZIONE = 'D' 
					AND LSRLET_ST_DECOR_DAL = @DATAAPPO
					AND LSRLET_ST_NOME_TAB_DOCUMENTO = 'LSRRAD_ST'
					AND LSRLET_ST_DECOR_DAL <> '00000000'
			)

		-- PRENDO IL DOC RAD DI RIATTIVAZIONE CON CAUSALE UGUALE E 
		-- CONTRARIA A QUELLO CHE HA GENERATO LA DISATTIVAZIONE
		IF @RADFONTE = 'M' OR @RADFONTE = 'A' 
		BEGIN			
			SELECT @IDDOC =  LSRRAD_ST_KEY_DATA_INS +  LSRRAD_ST_KEY_ORA_INS				
			FROM LSRRAD_ST 
			WHERE LSRRAD_ST_KEY_ID_RICEV  = @RICEV
				AND lsrrad_ST_fonte = @RADFONTE
				AND lsrrad_ST_data_decor >= @DATAAPPO
				and lsrrad_ST_tipo_movimentazione = 'R' 
			
			
		END
		
		IF @RADFONTE = 'L' 
		BEGIN
			SELECT  @IDDOC =  LSRRAD_ST_KEY_DATA_INS +  LSRRAD_ST_KEY_ORA_INS
			FROM LSRRAD_ST 
			WHERE LSRRAD_ST_KEY_ID_RICEV  = @RICEV
				AND lsrrad_ST_fonte = @RADFONTE
				AND lsrrad_ST_data_decor >= @DATAAPPO
				and lsrrad_ST_tipo_movimentazione = 'R' 
				AND lsrrad_ST_causale_lottomatica = @RADCAUSALELTM
			
		
		END

		-- SE LA PRIMA DISATTIVAZIONE NON E' STATA GENERATA DA
		-- NESSUN DOCUMENTO RAD, ALLORA PRENDO COME CAUSALE 
		-- QUELLA DI UN DOC DI RIATTIVAZIONE

		IF LTRIM(RTRIM(@IDDOC)) = '' OR @IDDOC IS NULL
		BEGIN

			-- CONTROLLO SULLA DATA DI INVIO DEL DOCUMENTO RAD
			SELECT @IDDOC =  LSRRAD_ST_KEY_DATA_INS +  LSRRAD_ST_KEY_ORA_INS 
			FROM LSRRAD_ST 
			WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEV
				AND LSRRAD_ST_TIPO_MOVIMENTAZIONE = @TIPOMOV
				AND LSRRAD_ST_FLAG_ANAG = '1'
				AND LSRRAD_ST_DATA_INVIO_DOC >= 
					(SELECT MAX(LSRSER_ST_DATA_DECOR) FROM LSRSER_ST  
					WHERE LSRSER_ST_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
					AND LSRSER_ST_FLAG_VALIDITA = 'Y' 
					AND LSRSER_ST_KEY_ID_RICEV = LSRRAD_ST_KEY_ID_RICEV ) 

		end
	END

	ELSE
	BEGIN
		-- CONTROLLO SULLA DATA DI INVIO DEL DOCUMENTO RAD
		SELECT @IDDOC =  LSRRAD_ST_KEY_DATA_INS +  LSRRAD_ST_KEY_ORA_INS 
		FROM LSRRAD_ST 
		WHERE LSRRAD_ST_KEY_ID_RICEV = @RICEV
			AND LSRRAD_ST_TIPO_MOVIMENTAZIONE = @TIPOMOV
			AND LSRRAD_ST_FLAG_ANAG = '1'
			AND LSRRAD_ST_DATA_INVIO_DOC >= 
				(SELECT MAX(LSRSER_ST_DATA_DECOR) FROM LSRSER_ST  
				WHERE LSRSER_ST_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
				AND LSRSER_ST_FLAG_VALIDITA = 'Y' 
				AND LSRSER_ST_KEY_ID_RICEV = LSRRAD_ST_KEY_ID_RICEV ) 
	END
	IF LTRIM(RTRIM(@IDDOC)) <> '' OR @IDDOC IS NOT NULL
	BEGIN
		INSERT INTO LSRLET_ST VALUES
			(@RICEV,@DATAINS,@ORAINS,@TIPOMOV,'00000000','LSRRAD_ST',@IDDOC,'00000000','',@FIRMA,'')
	END
END
GO
