/****** Object:  StoredProcedure [dbo].[ANA_MOVIMENTA_LTM_DA_LOTTO]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_MOVIMENTA_LTM_DA_LOTTO] 


@RICEVITORIA 	CHAR(6),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATADECOR		CHAR(8),
@DATAPROVV		CHAR(8),
@TIPOPROVV		CHAR(1),
@NUMPROVV		CHAR(8),
@FIRMA		CHAR(17),
@NOTE		VARCHAR(255)


AS


DECLARE 

@MSGERR	VARCHAR(255)


BEGIN TRANSACTION


---F101
PRINT 'ANA_MOVIMENTA_F101_DA_LOTTO'
EXEC ANA_MOVIMENTA_F101_DA_LOTTO
	@RICEVITORIA,
	@DATAINS,
	@ORAINS,
	@DATADECOR,
	@DATAPROVV,
	@TIPOPROVV,
	@NUMPROVV,
	@FIRMA,
	@NOTE

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_MOVIMENTA_F101_DA_LOTTO - RICEVITORIA ' + @RICEVITORIA
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

---TRIS
PRINT 'ANA_MOVIMENTA_TRIS_DA_LOTTO'
EXEC ANA_MOVIMENTA_TRIS_DA_LOTTO
	@RICEVITORIA,
	@DATAINS,
	@ORAINS,
	@DATADECOR,
	@DATAPROVV,
	@TIPOPROVV,
	@NUMPROVV,
	@FIRMA,
	@NOTE

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_MOVIMENTA_TRIS_DA_LOTTO - RICEVITORIA ' + @RICEVITORIA
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


---BOLLO
PRINT 'ANA_MOVIMENTA_BOLLO_DA_LOTTO'
EXEC ANA_MOVIMENTA_BOLLO_DA_LOTTO
	@RICEVITORIA,
	@DATAINS,
	@ORAINS,
	@DATADECOR,
	@DATAPROVV,
	@TIPOPROVV,
	@NUMPROVV,
	@FIRMA,
	@NOTE

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_MOVIMENTA_BOLLO_DA_LOTTO - RICEVITORIA ' + @RICEVITORIA
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


COMMIT TRANSACTION
GO
