/****** Object:  StoredProcedure [dbo].[ANA_MOVIMENTA_LTM]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_MOVIMENTA_LTM]  

@RICEV		CHAR(6),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATADECOR		CHAR(8),
@DATAPROVV		CHAR(8),
@TIPOPROVV		CHAR(1),
@NUMPROVV		VARCHAR(14),
@FIRMA		CHAR(17),
@DALOTTO		CHAR(1),
@CHKLOTTO		CHAR(1)


AS

DECLARE

@MSG		VARCHAR(255)



IF @ORAINS IS NULL OR LTRIM(RTRIM(@ORAINS)) = ''
BEGIN

	SELECT @DATAINS = CONVERT(CHAR, GETDATE(), 112)
	
	SELECT @ORAINS =  SUBSTRING(CONVERT(CHAR, GETDATE(), 121),12,2)+
				SUBSTRING(CONVERT(CHAR, GETDATE(), 121),15,2)+
				SUBSTRING(CONVERT(CHAR, GETDATE(), 121),18,2)+
				SUBSTRING(CONVERT(CHAR, GETDATE(), 121),21,2)
END


BEGIN TRANSACTION

--F101
EXEC ANA_MOVIMENTA_F101
	@RICEV,
	@DATAINS,
	@ORAINS,
	@DATADECOR,
	@DATAPROVV,
	@TIPOPROVV,
	@NUMPROVV,
	@FIRMA,
	@DALOTTO,
	@CHKLOTTO

IF @@ERROR <> 0
BEGIN
	SELECT @MSG = 'ERRORE NELLA S.P. ANA_MOVIMENTA_F101 - RICEVITORIA ' + @RICEV
	RAISERROR (@MSG, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

--BOLLO
EXEC ANA_MOVIMENTA_BOLLO
	@RICEV,
	@DATAINS,
	@ORAINS,
	@DATADECOR,
	@DATAPROVV,
	@TIPOPROVV,
	@NUMPROVV,
	@FIRMA,
	@DALOTTO,
	@CHKLOTTO

IF @@ERROR <> 0
BEGIN
	SELECT @MSG = 'ERRORE NELLA S.P. ANA_MOVIMENTA_BOLLO - RICEVITORIA ' + @RICEV
	RAISERROR (@MSG, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
GO
