/****** Object:  StoredProcedure [dbo].[Report_Movimentazioni_per_periodo_di_tempo]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE	PROCEDURE [dbo].[Report_Movimentazioni_per_periodo_di_tempo] 
	@DATAINIZIOPERIODO 	CHAR(8),
	@DATAFINEPERIODO 	CHAR(8),
	@TIPOMOVIMENTAZIONE	CHAR(1),
	@SERVIZIO		CHAR(2),
	@SIGLAREG		CHAR(2),
	@SIGLAPROV		CHAR(2),
	@XML 			CHAR(1),
	@ESITO 			INT OUT

AS
DECLARE  @TIPOSTATO CHAR(1)

SELECT @ESITO = 0

IF (@SERVIZIO IS NULL) OR (RTRIM(LTRIM(@SERVIZIO)) = '')
BEGIN
    SELECT @ESITO = 9
    RAISERROR ('MANCA IL NOME DEL SERVIZIO',16,1)
    RETURN @ESITO
END

IF (@SIGLAPROV IS NULL) OR (RTRIM(LTRIM(@SIGLAPROV)) = '')
BEGIN
    SELECT @SIGLAPROV = NULL
END
-- SE LA SIGLA DELLA PROVINCIA NON E' NULLA, 
-- METTO A NULL LA SIGLA DELLA REGIONE
ELSE
BEGIN
	SELECT @SIGLAREG = NULL
END

IF (@SIGLAREG IS NULL) OR (RTRIM(LTRIM(@SIGLAREG)) = '')
BEGIN
    SELECT @SIGLAREG = NULL
END

IF (@DATAINIZIOPERIODO IS NULL) OR (RTRIM(LTRIM(@DATAINIZIOPERIODO)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA LA DATA DI INIZIO PERIODO',16,1)
	RETURN @ESITO
END


IF (@DATAFINEPERIODO IS NULL) OR (RTRIM(LTRIM(@DATAFINEPERIODO)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA LA DATA DI FINE PERIODO',16,1)
	RETURN @ESITO
END

IF (@TIPOMOVIMENTAZIONE IS NULL) OR (RTRIM(LTRIM(@TIPOMOVIMENTAZIONE)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA IL TIPO DELLA MOVIMENTAZIONE',16,1)
	RETURN @ESITO
END



IF (@SERVIZIO) = '01' 
BEGIN
	EXEC [Anaconda].[dbo].[Report_Movimentazioni_per_periodo_di_tempo_LOTTO] @DATAINIZIOPERIODO, @DATAFINEPERIODO, @TIPOMOVIMENTAZIONE, @SERVIZIO, @SIGLAREG, @SIGLAPROV, @XML, @ESITO OUTPUT 
END
ELSE IF (@SERVIZIO) = '02' 
BEGIN
	EXEC [Anaconda].[dbo].[Report_Movimentazioni_per_periodo_di_tempo_F101] @DATAINIZIOPERIODO, @DATAFINEPERIODO, @TIPOMOVIMENTAZIONE, @SERVIZIO, @SIGLAREG, @SIGLAPROV, @XML, @ESITO OUTPUT 
END
ELSE IF (@SERVIZIO) = '05' 
BEGIN
	EXEC [Anaconda].[dbo].[Report_Movimentazioni_per_periodo_di_tempo_BOLLO] @DATAINIZIOPERIODO, @DATAFINEPERIODO, @TIPOMOVIMENTAZIONE, @SERVIZIO, @SIGLAREG, @SIGLAPROV, @XML, @ESITO OUTPUT 
END
ELSE IF (@SERVIZIO) = '08' 
BEGIN
	EXEC [Anaconda].[dbo].[Report_Movimentazioni_per_periodo_di_tempo_TRIS] @DATAINIZIOPERIODO, @DATAFINEPERIODO, @TIPOMOVIMENTAZIONE, @SERVIZIO, @SIGLAREG, @SIGLAPROV, @XML, @ESITO OUTPUT 
END
ELSE
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('SERVIZIO ERRATO',16,1)
	RETURN @ESITO
END

SET QUOTED_IDENTIFIER OFF
GO
