/****** Object:  StoredProcedure [dbo].[Report_movimentazioni_CONI_ST]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE	PROCEDURE [dbo].[Report_movimentazioni_CONI_ST] 
	@DATAINIZIOPERIODO 	CHAR(8),
	@SERVIZIO		CHAR(2),
	@XML 			CHAR(1),
	@ESITO 			INT OUT

AS
DECLARE  @TIPOSTATO CHAR(1)

SELECT @ESITO = 0

IF (@SERVIZIO IS NULL) OR (RTRIM(LTRIM(@SERVIZIO)) = '')
BEGIN
    SELECT @ESITO = 9
    RAISERROR ('MANCA IL NOME DEL SERVIZIO',16,1)
    RETURN @ESITO
END

IF (@DATAINIZIOPERIODO IS NULL) OR (RTRIM(LTRIM(@DATAINIZIOPERIODO)) = '')
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('MANCA LA DATA DI INIZIO PERIODO',16,1)
	RETURN @ESITO
END




IF (@SERVIZIO) = '11' 
BEGIN
	EXEC [Anaconda].[dbo].[RepMovimentazioniCONI] @DATAINIZIOPERIODO, @XML, @ESITO OUTPUT 
END
ELSE IF (@SERVIZIO) = '12' 
BEGIN

	EXEC [Anaconda].[dbo].[RepMovimentazioniST] @DATAINIZIOPERIODO, @XML, @ESITO OUTPUT 
END
ELSE
BEGIN
	SELECT @ESITO = 9
	RAISERROR ('SERVIZIO ERRATO',16,1)
	RETURN @ESITO
END

SET QUOTED_IDENTIFIER OFF
GO
