/****** Object:  StoredProcedure [dbo].[GEV_ATTIVAZIONE]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_ATTIVAZIONE]  

@CODLTM 		CHAR(6),
@CODSGI 		CHAR(7),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATADAL		CHAR(8),
@FIRMA		CHAR(17),
@NOMEFILE		VARCHAR(255),
@NOTE		CHAR(50)

AS

DECLARE 	


@DATAORAINS	CHAR(16),
@CHKRICEV		CHAR(6),
@CODSER		CHAR(2),
@TIPOMOV		CHAR(1),
@STATOINS		CHAR(1),
@STATOLOTTO	VARCHAR(50),
@STATOGEVA		VARCHAR(50),
@STATOGEVF		VARCHAR(50),
@TIPOPROVV		CHAR(1),
@RESULT		INT,
@CODAMM		CHAR(6),
@DATASTATO		CHAR(10),
@DATARIN1		CHAR(8),
@DATARIN2		CHAR(8),
@ABI 			char(5),
@CAB 			char(5),
@BANCA 		varchar(50),

@MSGERR		VARCHAR(100)

SELECT @TIPOMOV = 'A'
SELECT @CODSER = '09'
SELECT @STATOINS = '1'

IF LTRIM(RTRIM(@DATAINS)) = '' OR @DATAINS IS NULL
BEGIN
	SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

	SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)
END

/*
' ESEGUO I CONTROLLI NEL CASO DI ATTIVAZIONE AL SERVIZIO GEV:
' 1) - ESISTE LA RICEVITORIA IN LSRRIC
' 2) - ESISTE LA RICEVITORIA IN LSRSER_GEV
' 3) - LO STATO DEL GEV SIA COMPATIBILE CON L'OPERAZIONE
' 4) - LO STATO DEL LOTTO SIA ATTIVO OPPURE ABBIA ALMENO LA CONCESSIONE ALLA DATA DI ATTIVAZIONE (OPZIONALE)
' 5) - ESISTE LA DELEGA RID
*/


/*
' 1) - ESISTE LA RICEVITORIA IN LSRRIC
*/

EXEC @RESULT = GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

IF @RESULT <> 0
BEGIN
	SELECT @MSGERR = 'RICEVITORIA INESISTENTE'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

/*
' 2) - ESISTE LA RICEVITORIA IN LSRSER_GEV


SELECT @STATOGEVF = NULL

SELECT @STATOGEVF = LSRSER_GEV_STATO
FROM LSRSER_GEV
WHERE LSRSER_GEV_COD_LOTTO = @CODLTM
AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
AND LSRSER_GEV_DATA_DECOR =
(
	SELECT MAX(LSRSER_GEV_DATA_DECOR)
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_COD_LOTTO = @CODLTM
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_DATA_DECOR <= @DATADAL
)

IF @STATOGEVF IS NOT NULL
BEGIN
	SELECT @MSGERR = 'STATO DEL GIOCO INCOMPATIBILE ALLA DATA DI ATTIVAZIONE '
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END
*/

/*
' 3) - LO STATO DEL GEV SIA COMPATIBILE CON L'OPERAZIONE
*/
SELECT @STATOGEVF = NULL
SELECT @DATASTATO = NULL

SELECT @DATASTATO = CONVERT(CHAR(10), CONVERT(DATETIME, LSRSER_GEV_DATA_DECOR), 121),
@STATOGEVF = 
	CASE LSRSER_GEV_STATO
	WHEN '1' THEN 'GEV ATTIVO DAL ' + @DATASTATO
	WHEN '2' THEN 'GEV DISATTIVO DAL ' + @DATASTATO
END
FROM LSRSER_GEV
WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM
AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
AND LSRSER_GEV_DATA_DECOR =
(
	SELECT MAX(LSRSER_GEV_DATA_DECOR)
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_DATA_DECOR <= @DATADAL
)

IF @STATOGEVF IS NOT NULL
BEGIN
	SELECT @MSGERR = @STATOGEVF
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

/*
' 4) - LO STATO DEL LOTTO SIA ATTIVO OPPURE ABBIA ALMENO LA CONCESSIONE ALLA DATA DI ATTIVAZIONE (OPZIONALE)
*/
SELECT @STATOLOTTO = NULL
SELECT @DATASTATO = NULL

SELECT @DATASTATO = CONVERT(CHAR(10), CONVERT(DATETIME, LSRSER_LOTTO_DATA_DECOR), 121),
@STATOLOTTO = 
	CASE LSRSER_LOTTO_TIPO_PROVV 
--	WHEN 'A' THEN 'ATTIVO DAL ' + @DATASTATO
	WHEN 'R' THEN 'LOTTO REVOCATO DAL ' + @DATASTATO
	WHEN 'S' THEN 'LOTTO SOSPESO DAL ' + @DATASTATO
	WHEN 'M' THEN 'RICEVITORIA SMANTELLATA DAL ' + @DATASTATO
END
FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
AND LSRSER_LOTTO_TIPO_PROVV IN ('A', 'R', 'S', 'M', '')
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(
	SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
	FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
	AND LSRSER_LOTTO_TIPO_PROVV IN ('A', 'R', 'S', 'M', '')
	AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
	AND LSRSER_LOTTO_DATA_DECOR <= @DATADAL
)

IF @STATOLOTTO IS NOT NULL
BEGIN
	SELECT @MSGERR = @STATOLOTTO
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END


-- 5) -ESISTE LA DELEGA RID

/*
EXEC GEV_ESISTE_RID @CODLTM, @DATADAL, @CODSER, @ABI OUTPUT, @CAB OUTPUT, @BANCA OUTPUT

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'RID INESISTENTE PER LA RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

*/

BEGIN TRANSACTION

SELECT @DATAORAINS = NULL

SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS + LSRLET_KEY_ORA_INS)
FROM LSRLET	
WHERE LSRLET_KEY_ID_RICEV = @CODLTM
AND LSRLET_COD_SERVIZIO = @CODSER
AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV
AND LSRLET_KEY_DATA_INS = @DATAINS
AND LSRLET_DECOR_DAL = '00000000'

IF @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATADAL
	WHERE LSRLET_KEY_ID_RICEV = @CODLTM
	AND LSRLET_KEY_DATA_INS + LSRLET_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_COD_SERVIZIO = @CODSER
	AND LSRLET_TIPO_MOVIMENTAZIONE = @TIPOMOV


	IF @@ERROR <> 0 
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'ERRORE IN UPDATE LSRLET'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END
ELSE
BEGIN
	INSERT INTO LSRLET VALUES
	(@CODLTM, @DATAINS, @ORAINS, @CODSER, @TIPOMOV, @DATADAL, '', '', '00000000', @NOTE, @FIRMA, 'V')

	IF @@ERROR <> 0 
	BEGIN
		ROLLBACK TRANSACTION
		SELECT @MSGERR = 'ERRORE IN INSERT LSRLET'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END

SELECT @MSGERR = NULL

INSERT INTO LSRSER_GEV VALUES 
	(@CODLTM, 
	@DATAINS, 
	@ORAINS,
	@STATOINS, 
	@DATADAL, 
	@TIPOMOV, 
	NULL, 
	NULL, 
	NULL, 
	'',
	@FIRMA, 
	@NOTE, 
	'00000000',  
	'Y')

IF @@ERROR <> 0 
BEGIN
	ROLLBACK TRANSACTION
	SELECT @MSGERR = 'ERRORE IN INSERT LSRSER_GEV'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

COMMIT TRANSACTION
GO
