/****** Object:  StoredProcedure [dbo].[GEV_CREA_RAD_old]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE      PROCEDURE [dbo].[GEV_CREA_RAD_old] 
 
@TIPOOPE CHAR(1),
@CON  VARCHAR(3),
@QUE  VARCHAR(3),
@RID  VARCHAR(3),
@RAD  VARCHAR(3),
@FID  VARCHAR(3),
@ANDOR VARCHAR(3),
@FIRMA VARCHAR(17),
@PATHTOT VARCHAR(100) OUTPUT,
@NUM  VARCHAR(5) OUTPUT
 
AS
 
DECLARE 
 
@CODLTM  VARCHAR(6),
@PATHID  INT,
@NOMEFILE  VARCHAR(20),
@PATHDESC  VARCHAR(70),
@SQL   VARCHAR(2500),
@MSGERR  VARCHAR(70),
@CONTADOC  INT,
@NUMDOC  INT,
@STATOGEV  CHAR(1),
@FLGOK  INT,
@FLGANAG  VARCHAR(6),
@DATARID  CHAR(8),
@DATARIN1  CHAR(8),
@DATARIN2  CHAR(8),
@CODSER  CHAR(2),
@DATAINS  CHAR(8),
@ORAINS  CHAR(8)
 
 
SELECT @DATAINS = CONVERT(CHAR(8), GETDATE(),112)
 
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
  SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
  SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
  SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)
 
SELECT @CODSER = '09'
SELECT @CONTADOC = 0
SELECT @FLGANAG = '''1'' '
SELECT @DATARID = '99999999'
 
IF @TIPOOPE NOT IN ('A', 'R', 'D')
BEGIN
 SELECT @MSGERR = 'TIPO OPERAZIONE NON PREVISTA'
 RAISERROR (@MSGERR, 16, 1)
 RETURN
END
 
/*
SELECT @PATHDESC = PATH 
FROM GESTIONE.DBO.TAB_PATHS 
WHERE PATHID = 80
AND SERVER = @@SERVERNAME
*/
 
SELECT @PATHID = 80
SELECT @NOMEFILE = 'GEV_' + @TIPOOPE + '_' + CONVERT(VARCHAR, GETDATE(),112) + '.txt'
SELECT @PATHTOT = @NOMEFILE
 
-- CANCELLO IL FILE RAD
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, 'NO_LOG'
 
/*
IF @TIPOOPE = 'A'
BEGIN
 IF @ANDOR <> 'AND'
 BEGIN
  SELECT @MSGERR = 'CRITERIO DI SELEZIONE NON AMMESSO PER ATTIVARE IL SERVIZIO'
  RAISERROR (@MSGERR, 16, 1)
  RETURN
 END
END
 
IF @TIPOOPE = 'D'
BEGIN
 IF @ANDOR <> 'AND'
 BEGIN
  SELECT @MSGERR = 'CRITERIO DI SELEZIONE NON AMMESSO PER DISATTIVARE IL SERVIZIO'
  RAISERROR (@MSGERR, 16, 1)
  RETURN
 END
 
 IF LTRIM(RTRIM(@RAD)) = '' OR @RAD IS NULL OR @RAD = '0'
 BEGIN
  SELECT @MSGERR = 'NECESSARIO DOCUMENTO RAD PER DISATTIVARE IL SERVIZIO'
  RAISERROR (@MSGERR, 16, 1)
  RETURN
 END
END
 
IF @TIPOOPE = 'R'
BEGIN
 IF @ANDOR NOT IN ('OR', 'AND')
 BEGIN
  SELECT @MSGERR = 'CRITERIO DI SELEZIONE AND/OR NON INDCATO'
  RAISERROR (@MSGERR, 16, 1)
  RETURN
 END
 
 IF LTRIM(RTRIM(@RAD)) = '' OR @RAD IS NULL OR @RAD = '0'
 BEGIN
  SELECT @MSGERR = 'NECESSARIO DOCUMENTO RAD PER RIATTIVARE IL SERVIZIO'
  RAISERROR (@MSGERR, 16, 1)
  RETURN
 END
END
*/
 
IF @CON = 'CON'
BEGIN
 SELECT @CONTADOC = @CONTADOC + 1
END
 
IF @FID = 'FID'
BEGIN
 SELECT @CONTADOC = @CONTADOC + 1
END
 
IF @RID = 'RID'
BEGIN
 SELECT @CONTADOC = @CONTADOC + 1
END
 
IF @RAD = 'RAD'
BEGIN
 SELECT @CONTADOC = @CONTADOC + 1
END
 
IF @QUE = 'QUE'
BEGIN
 SELECT @CONTADOC = @CONTADOC + 1
END
 
SELECT @NUMDOC = @CONTADOC
 
 
IF @TIPOOPE IN ('A', 'D')
BEGIN
 SELECT @ANDOR = 'AND'
END
ELSE
BEGIN
 IF @ANDOR NOT IN ('AND', 'OR') AND @CONTADOC > 1
 BEGIN
  SELECT @MSGERR = 'CRITERIO AND/OR NON INDICATO'
  RAISERROR (@MSGERR, 16, 1)
  RETURN
 END
END
 
SELECT @SQL = ''
 
 
IF @CON = 'CON' 
BEGIN
 SELECT @SQL = @SQL +
 'SELECT DISTINCT LSRCON_GEV_COD_LOTTO AS RICEV FROM LSRCON_GEV
 WHERE LSRCON_GEV_FLAG_ANAG = ' + @FLGANAG
 
 SELECT @CONTADOC = @CONTADOC - 1
 
 IF @CONTADOC > 0
 BEGIN
  IF @ANDOR = 'AND'
  BEGIN
   SELECT @SQL = @SQL +
   ' AND LSRCON_GEV_COD_LOTTO IN
   ('
  END
  ELSE
  BEGIN
   SELECT @SQL = @SQL + ' UNION '
  END
 END
END
 
IF @RID = 'RID' 
BEGIN
 SELECT @SQL = @SQL +
 '
 SELECT DISTINCT LCR01A_KEY_ID_RICEV AS RICEV FROM Riscossioni.dbo.LCR01A
 WHERE LCR01A_DATA_INIZIO_VAL <= CONVERT(CHAR, GETDATE(), 112)
 AND LCR01A_TIPO_GIOCO=''09''
 AND LCR01A_KEY_DATA_FINE_VAL = ''99999999'' '
 
 SELECT @CONTADOC = @CONTADOC - 1
 
 IF (@NUMDOC = 2 AND @CON = 'CON') AND @ANDOR = 'AND'
 BEGIN
  SELECT @SQL = @SQL + ')'
 END
 
 IF @CONTADOC > 0
 BEGIN
  IF @ANDOR = 'AND'
  BEGIN
   SELECT @SQL = @SQL +
   ' AND LCR01A_KEY_ID_RICEV IN
   ('
  END
  ELSE
 
  BEGIN
   SELECT @SQL = @SQL + ' UNION '
  END
 END
END
 
IF @FID = 'FID' 
BEGIN
 SELECT @SQL = @SQL +
 
 'SELECT DISTINCT LSRFID_GEV_COD_LOTTO AS RICEV FROM LSRFID_GEV
 WHERE LSRFID_GEV_ANNO_RIF = CONVERT(CHAR(4),GETDATE(),112) 
 AND LSRFID_GEV_FLAG_ANAG = ' + @FLGANAG + ' '
 
 SELECT @CONTADOC = @CONTADOC - 1
 
 IF @NUMDOC = 3 AND (@CON = 'CON' AND @RID = 'RID') AND @ANDOR = 'AND'
 BEGIN
  SELECT @SQL = @SQL + '))'
 END
 
 IF @NUMDOC = 2 AND (@CON = 'CON' OR @RID = 'RID') AND @ANDOR = 'AND'
 BEGIN
  SELECT @SQL = @SQL + ')'
 END
 
 IF @CONTADOC > 0
 BEGIN
  IF @ANDOR = 'AND'
  BEGIN
   SELECT @SQL = @SQL +
   ' AND LSRFID_GEV_COD_LOTTO IN
   ('
  END
  ELSE
  BEGIN
 
   SELECT @SQL = @SQL + ' UNION '
  END
 END
END
 
IF @QUE = 'QUE' 
BEGIN
 SELECT @SQL = @SQL +
 'SELECT DISTINCT LSRQST_GEV_COD_LOTTO AS RICEV FROM LSRQST_GEV
 WHERE LSRQST_GEV_FLAG_ANAG = ''1'' '
 
 SELECT @CONTADOC = @CONTADOC - 1
 
 IF @NUMDOC = 4 AND (@CON = 'CON' AND @RID = 'RID' AND @FID = 'FID') AND @ANDOR = 'AND'
 BEGIN
  SELECT @SQL = @SQL + ') ) )'
 END
 
 IF @NUMDOC = 3 AND 
 ((@CON = 'CON' AND @RID = 'RID') OR (@CON = 'CON' AND @FID = 'FID') OR (@FID = 'FID' AND @RID = 'RID'))
  AND @ANDOR = 'AND'
 BEGIN
  SELECT @SQL = @SQL + '))'
 END
 
 IF @NUMDOC = 2 AND 
 (@CON = 'CON' OR @RID = 'RID' OR @FID = 'FID') AND @ANDOR = 'AND'
 BEGIN
  SELECT @SQL = @SQL + ')'
 END
 
 IF @CONTADOC > 0
 BEGIN
  IF @ANDOR = 'AND'
  BEGIN
   SELECT @SQL = @SQL +
   ' AND LSRQST_GEV_COD_LOTTO IN
   ('
  END
  ELSE
  BEGIN
   SELECT @SQL = @SQL + ' UNION '
  END
 END
END
 
IF @RAD = 'RAD' 
BEGIN
 
/*
PRIMA LA SELECT ERA QUESTA
 
 SELECT @SQL = @SQL +
 'SELECT DISTINCT LSRRAD_COD_LOTTO AS RICEV FROM LSRRAD_GEV
 WHERE LSRRAD_FLAG_ANAG = ''1''
 AND LSRRAD_TIPO_MOVIMENTAZIONE = ' + '''' + @TIPOOPE + ''' ' +
 'AND LSRRAD_DATA_INVIO_DOC <= CONVERT(CHAR, GETDATE(), 112)
 AND LSRRAD_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112) '
 
*/
 
/* IL 14/12/2004 E' STATA MODIFICATA CON QUESTA */
 
 SELECT @SQL = @SQL +
 'SELECT DISTINCT LSRRAD_COD_LOTTO AS RICEV FROM LSRRAD_GEV D
 WHERE LSRRAD_FLAG_ANAG = ''1''
  AND LSRRAD_TIPO_MOVIMENTAZIONE = ' + '''' + @TIPOOPE + ''' ' +
  'AND LSRRAD_DATA_INVIO_DOC <= CONVERT(CHAR, GETDATE(), 112)
  AND LSRRAD_DATA_DECOR >= 
   (SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV  
   WHERE LSRSER_GEV_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112) 
    AND LSRSER_GEV_FLAG_VALIDITA = ''Y''
     AND LSRSER_GEV_KEY_ID_RICEV = D.LSRRAD_COD_LOTTO )
  AND LSRRAD_DATA_DECOR <= CONVERT(CHAR, GETDATE(), 112)'
 
 
 
 
 
 SELECT @CONTADOC = @CONTADOC - 1
 
 IF @NUMDOC > 1 AND @ANDOR = 'AND'
 BEGIN
  SELECT @SQL = @SQL + REPLICATE(')', @NUMDOC - 1)
 END
 
END
 
SELECT @SQL = 'SELECT DISTINCT(RICEV) FROM (' + @SQL + ') A '
  
 
IF @TIPOOPE = 'A'
BEGIN
 SELECT @SQL = @SQL + '  WHERE A.RICEV NOT IN 
     (
      SELECT DISTINCT(lsrser_GeV_key_id_ricev) 
      FROM LSRSER_GEV 
      WHERE LSRSER_GEV_FLAG_VALIDITA = ''Y''
     ) 
     AND A.RICEV IN 
     (
      SELECT DISTINCT(LSRSER_LOTTO_KEY_ID_RICEV) 
      FROM LSRSER_LOTTO B
      WHERE LSRSER_LOTTO_TIPO_PROVV IN (''A'',''R'', ''S'', ''M'', '''')
      AND LSRSER_LOTTO_FLAG_VALIDITA = ''Y''
      AND LSRSER_LOTTO_DATA_DECOR =
      (
       SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
       FROM LSRSER_LOTTO
       WHERE LSRSER_LOTTO_KEY_ID_RICEV = B.LSRSER_LOTTO_KEY_ID_RICEV
       AND LSRSER_LOTTO_TIPO_PROVV IN  (''A'',''R'', ''S'', ''M'', '''')
       AND LSRSER_LOTTO_FLAG_VALIDITA = ''Y''
       AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
      )
      AND (LSRSER_LOTTO_TIPO_PROVV = ''A'' OR LSRSER_LOTTO_TIPO_PROVV = '''' )
     )
 
 
     '
END
IF @TIPOOPE = 'D'
BEGIN
 SELECT @SQL = @SQL + ' WHERE A.RICEV  IN
  (
  SELECT lsrser_GeV_key_id_ricev
  FROM LSRSER_GEV A
  WHERE LSRSER_GEV_DATA_DECOR =
  (
   SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV
   WHERE LSRSER_GEV_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
   AND lsrser_GeV_key_id_ricev = A.lsrser_GeV_key_id_ricev
   AND LSRSER_GEV_FLAG_VALIDITA = ''Y''
  )
  AND LSRSER_GEV_FLAG_VALIDITA = ''Y''
  AND LSRSER_GEV_STATO = ''1''
  )
'
 
END
IF @TIPOOPE = 'R'
BEGIN
 SELECT @SQL = @SQL + '  WHERE A.RICEV  IN
  (
   SELECT lsrser_GeV_key_id_ricev
   FROM LSRSER_GEV A
   WHERE LSRSER_GEV_DATA_DECOR =
   (
    SELECT MAX(LSRSER_GEV_DATA_DECOR) FROM LSRSER_GEV
    WHERE LSRSER_GEV_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
    AND lsrser_GeV_key_id_ricev = A.lsrser_GeV_key_id_ricev
    AND LSRSER_GEV_FLAG_VALIDITA = ''Y''
   )
   AND LSRSER_GEV_FLAG_VALIDITA = ''Y''
   AND LSRSER_GEV_STATO = ''2''
  )
  AND A.RICEV IN 
  (
   SELECT DISTINCT(LSRSER_LOTTO_KEY_ID_RICEV) 
   FROM LSRSER_LOTTO B
   WHERE LSRSER_LOTTO_TIPO_PROVV IN (''A'',''R'', ''S'', ''M'', '''')
   AND LSRSER_LOTTO_FLAG_VALIDITA = ''Y''
   AND LSRSER_LOTTO_DATA_DECOR =
   (
    SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
    FROM LSRSER_LOTTO
    WHERE LSRSER_LOTTO_KEY_ID_RICEV = B.LSRSER_LOTTO_KEY_ID_RICEV
    AND LSRSER_LOTTO_TIPO_PROVV IN  (''A'',''R'', ''S'', ''M'', '''')
    AND LSRSER_LOTTO_FLAG_VALIDITA = ''Y''
    AND LSRSER_LOTTO_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
   )
   AND (LSRSER_LOTTO_TIPO_PROVV = ''A'' OR LSRSER_LOTTO_TIPO_PROVV = '''' )
  )
 
'
END
 
 
SELECT @NUM = '0'
SELECT @NUM = CONVERT(INT, @NUM)
 
SELECT @CODLTM = NULL
SELECT @STATOGEV = NULL
SELECT @DATARIN1 = NULL
SELECT @DATARIN2 = NULL
 
PRINT @SQL
 
declare @erroreexec varchar(255)
 
 
SELECT @SQL = 'DECLARE CUR_RAD CURSOR FOR ' + RTRIM(@SQL)  + ' ORDER BY 1'
 
EXECUTE (@SQL) 
 
select @erroreexec = cast(@@error as varchar)
if @erroreexec <> 0 
begin
 RAISERROR (@erroreexec, 16, 1)
 RETURN
end
 
OPEN CUR_RAD 
 
FETCH NEXT FROM CUR_RAD INTO @CODLTM 
WHILE @@FETCH_STATUS = 0 
BEGIN
 SELECT @NUM = @NUM + 1
 
 EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @CODLTM, @NOMEFILE
 
 EXECUTE GEV_SCRIVI_LSRLET
 @CODLTM,
 @CON, 
 @FID, 
 @RID, 
 @QUE, 
 @RAD, 
 @DATAINS,
 @ORAINS,
 @TIPOOPE,
 @FIRMA
 
 FETCH NEXT FROM CUR_RAD INTO @CODLTM 
END
 
CLOSE CUR_RAD
DEALLOCATE CUR_RAD
 
SELECT @NUM = CONVERT(VARCHAR(5), @NUM)
GO
