/****** Object:  StoredProcedure [dbo].[GEV_DISATTIVAZIONE]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_DISATTIVAZIONE]  

@CODLTM 		CHAR(7),
@CODSGI 		CHAR(6),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATADISATT		CHAR(8),
@FIRMA		CHAR(17),
@NOMEFILE		VARCHAR(255),
@NOTE		CHAR(50)

AS

DECLARE 	


@DATAORAINS	CHAR(16),
@CHKRICEV		CHAR(6),
@STATOGEVA		CHAR(1),
@STATOGEVF		CHAR(1),
@TIPOPROVV		CHAR(1),
@DATADECOR		CHAR(8),
@RESULT		INT,
@CODAMM		CHAR(6),
@STATOLOTTO	CHAR(1),
@MSGERR		VARCHAR(100)

IF LTRIM(RTRIM(@DATAINS)) = '' OR @DATAINS IS NULL
BEGIN
	SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

	SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)
END

/*
' ESEGUO I CONTROLLI NEL CASO DI DISATTIVAZIONE AL SERVIZIO GEV:
' 1) - ESISTE LA RICEVITORIA IN LSRRIC
' 2) - ESISTE LA RICEVITORIA IN LSRSER_GEV
' 3) - NON ESISTANO DISATTIVAZIONI NEL FUTURO (DOMANI)
' 4) - IL SERVIZIO NON SIA GIA' DISATTIVO	
*/


/*
CONTROLLO 1
' 1) - ESISTE LA RICEVITORIA IN LSRRIC
*/

EXEC @RESULT = GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

IF @RESULT <> 0
BEGIN
	SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' INESISTENTE'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

/*
==CONTROLLO 2==
' 2) - ESISTE LA RICEVITORIA IN LSRSER_GEV
*/


SELECT @CHKRICEV = NULL

SELECT DISTINCT @CHKRICEV = LSRSER_GEV_KEY_ID_RICEV 
FROM LSRSER_GEV
WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM

-- SE LA RICEVITORIA NON ESISTE SU LSRSER_GEV NON POSSO DISATTIVARE
IF @CHKRICEV IS NULL 
BEGIN
	SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' INESISTENTE SU TABELLA LSRSER_GEV'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END


-- SE LA RICEVITORIA ESISTE SU LSRSER_GEV CONTROLLO LO STATO ATTUALE E FUTURO DEL GEV
IF @CHKRICEV IS NOT NULL
BEGIN
	
	--CONTROLLO LO STATO ATTUALE DEL GEV
	SELECT @STATOGEVA = NULL
	SELECT @DATADECOR = NULL

	SELECT @DATADECOR = LSRSER_GEV_DATA_DECOR, @STATOGEVA = LSRSER_GEV_STATO
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_DATA_DECOR = 
	(
		SELECT MAX(LSRSER_GEV_DATA_DECOR)
		FROM LSRSER_GEV
		WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM
		AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
		AND LSRSER_GEV_DATA_DECOR < @DATADISATT
	)

	-- SE LO STATO ATTUALE E' GIA' DISATTIVO NON POSSO DISATTIVARE
	IF @STATOGEVA = '2'
	BEGIN
		SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' - GEV DISATTIVO DALLA DATA ' + @DATADECOR
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

	-- SE LO STATO ATTUALE E' NULL NON POSSO DISATTIVARE
	IF @STATOGEVA IS NULL
	BEGIN
		SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' - STATO GEV INESISTENTE ALLA DATA ODIERNA'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

	--CONTROLLO LO STATO FUTURO DEL GEV ALLA DATA DI DISATTIVAZIONE
	SELECT @STATOGEVF = NULL
	SELECT @DATADECOR = NULL

	SELECT @DATADECOR = LSRSER_GEV_DATA_DECOR, @STATOGEVF = LSRSER_GEV_STATO
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_DATA_DECOR = @DATADISATT

	-- SE LO STATO FUTURO E' GIA' DISATTIVO NON POSSO DISATTIVARE
	IF @STATOGEVF = '2'
	BEGIN
		SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' - GEV GIA DISATTIVO DALLA DATA ' + @DATADECOR
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END

BEGIN TRANSACTION

SELECT @DATAORAINS = NULL

SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS + LSRLET_KEY_ORA_INS)
FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @CODLTM
AND LSRLET_COD_SERVIZIO = '09'
AND LSRLET_TIPO_MOVIMENTAZIONE = 'D'
AND LSRLET_KEY_DATA_INS = @DATAINS
AND LSRLET_DECOR_DAL = '00000000'

IF @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATADISATT
	WHERE LSRLET_KEY_ID_RICEV = @CODLTM
	AND LSRLET_KEY_DATA_INS + LSRLET_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_COD_SERVIZIO = '09'
	AND LSRLET_TIPO_MOVIMENTAZIONE = 'D'
END
ELSE
BEGIN
	INSERT INTO LSRLET VALUES
	(@CODLTM, @DATAINS, @ORAINS, '09', 'D', @DATADISATT, '', '', '00000000', @NOTE, @FIRMA, 'V')
END

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = @CODLTM + ' / ' + @CODSGI + ' ERRORE IN INSERT/UPDATE SU LSRLET'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

INSERT INTO LSRSER_GEV VALUES 
		(@CODLTM, 
		@DATAINS, 
		@ORAINS, 
		 '2', 
		 @DATADISATT, 
		'D', 
		NULL, 
		NULL, 
		NULL, 
		'',
		@FIRMA, 
		@NOTE, 
		'00000000', 
		'Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = @CODLTM + ' / ' + @CODSGI + ' ERRORE IN INSERT SU LSRSER_GEV'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

COMMIT TRANSACTION
GO
