/****** Object:  StoredProcedure [dbo].[GEV_RIATTIVAZIONE]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[GEV_RIATTIVAZIONE]  

@CODLTM 		CHAR(6),
@CODSGI 		CHAR(7),
--@CHKLOTTO		CHAR(1),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATARIATTIV	CHAR(8),
@FIRMA		CHAR(17),
@NOMEFILE		VARCHAR(255),
@NOTE		CHAR(50)

AS

DECLARE 	


@DATAORAINS	CHAR(16),
@CHKLOTTO		CHAR(1),
@CHKRICEV		CHAR(6),
@STATOLOTTO	VARCHAR(50),
@STATOGEVA		CHAR(1),
@STATOGEVF		CHAR(1),
@TIPOPROVV		CHAR(1),
@DATADECOR		CHAR(8),
@DATASTATO		CHAR(8),	
@RESULT		INT,
@CODAMM		CHAR(6),
@ABI			CHAR(5),
@CAB			CHAR(5),
@BANCA		VARCHAR(35),
@CODSER		CHAR(2),
@MSGERR		VARCHAR(100)


IF LTRIM(RTRIM(@DATAINS)) = '' OR @DATAINS IS NULL
BEGIN
	SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2)

	SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)+
			SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2)
END


/*
' ESEGUO I CONTROLLI NEL CASO DI RIATTIVAZIONE AL SERVIZIO GEV:
' 1) - ESISTE LA RICEVITORIA IN LSRRIC
' 2) - ESISTE LA RICEVITORIA IN LSRSER_GEV
' 3) -  IL SERVIZIO NON SIA GIA' ATTIVO
' 4) - LO STATO GEV NEL FUTURO (DOMANI) SIA COMPATIBILE CON LA RIATTIVAZIONE
' 5) - LO STATO DEL SERVIZIO LOTTO SIA ATTIVO OPPURE ABBIA ALMENO LA CONCESSIONE ALLA DATA DI RIATTIVAZIONE (OPZIONALE)
' 6) - ESISTE IL RID PER LA RICEVITORIA
*/


/*
CONTROLLO 1
' 1) - ESISTE LA RICEVITORIA IN LSRRIC
*/

EXEC @RESULT = GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

IF @RESULT <> 0
BEGIN
	SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' INESISTENTE'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

/*
==CONTROLLO 2==
' 2) - ESISTE LA RICEVITORIA IN LSRSER_GEV
*/

SELECT @CHKRICEV = NULL

SELECT DISTINCT @CHKRICEV = LSRSER_GEV_KEY_ID_RICEV FROM LSRSER_GEV
WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM

-- SE LA RICEVITORIA NON ESISTE SU LSRSER_GEV NON POSSO RIATTIVARE
IF @CHKRICEV IS NULL 
BEGIN
	SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' INESISTENTE SU TABELLA LSRSER_GEV'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

-- SE LA RICEVITORIA ESISTE SU LSRSER_GEV CONTROLLO LO STATO ATTUALE E FUTURO DEL GEV
IF @CHKRICEV IS NOT NULL
BEGIN
	
	--CONTROLLO LO STATO ATTUALE DEL GEV
	SELECT @STATOGEVA = NULL
	SELECT @DATADECOR = NULL

	SELECT @DATADECOR = LSRSER_GEV_DATA_DECOR, @STATOGEVA = LSRSER_GEV_STATO
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_DATA_DECOR = 
	(
		SELECT MAX(LSRSER_GEV_DATA_DECOR)
		FROM LSRSER_GEV
		WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM
		AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
		AND LSRSER_GEV_DATA_DECOR < @DATARIATTIV
	)

	-- SE LO STATO ATTUALE E' GIA' ATTIVO NON POSSO RIATTIVARE
	IF @STATOGEVA = '1'
	BEGIN
		SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' - GEV ATTIVO DALLA DATA ' + @DATADECOR
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

	-- SE LO STATO ATTUALE E' NULL NON POSSO RIATTIVARE
	IF @STATOGEVA IS NULL
	BEGIN
		SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' - GEV NON PRESENTE ALLA DATA ODIERNA'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

	--CONTROLLO LO STATO FUTURO DEL GEV ALLA DATA DI RIATTIVAZIONE
	SELECT @STATOGEVF = NULL
	SELECT @DATADECOR = NULL

	SELECT @DATADECOR = LSRSER_GEV_DATA_DECOR, @STATOGEVF = LSRSER_GEV_STATO
	FROM LSRSER_GEV
	WHERE LSRSER_GEV_KEY_ID_RICEV = @CODLTM
	AND LSRSER_GEV_FLAG_VALIDITA = 'Y'
	AND LSRSER_GEV_DATA_DECOR = @DATARIATTIV

	-- SE LO STATO FUTURO E' GIA' ATTIVO NON POSSO RIATTIVARE
	IF @STATOGEVF = '1'
	BEGIN
		SELECT @MSGERR = 'RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI + ' - GEV ATTIVO DALLA DATA ' + @DATADECOR
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END
/*
SELECT @STATOLOTTO = NULL

SELECT @STATOLOTTO = LSRSER_LOTTO_TIPO_PROVV 
FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR <=
(
	SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
	FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
	AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
	AND LSRSER_LOTTO_DATA_DECOR <= @DATARIATTIV
)

IF @CHKLOTTO = 'Y' -- OPZIONE STATO LOTTO CHE INDICA SE DEVO CONTROLLARNE LO STATO ALLA DATA DI RIATTIVAZIONE GEV
BEGIN
	IF @STATOLOTTO = 'S' OR @STATOLOTTO = 'M' OR @STATOLOTTO = 'R' 

-- INIZIO MODIFICA 31/10/2002 BY F.GIACOVAZZI
--	OR LTRIM(RTRIM(@STATOLOTTO)) = '' OR @STATOLOTTO IS NULL
-- FINE MODIFICA 31/10/2002
	BEGIN
		SELECT @MSGERR = @CODLTM + ' / ' + @CODSGI + ' - SERVIZIO LOTTO SOSPESO/REVOCATO O SMANTELLATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END
*/

SELECT @STATOLOTTO = NULL
SELECT @DATASTATO = NULL

SELECT @DATASTATO = CONVERT(CHAR(10), CONVERT(DATETIME, LSRSER_LOTTO_DATA_DECOR), 121),
@STATOLOTTO = 
	CASE LSRSER_LOTTO_TIPO_PROVV 
--	WHEN 'A' THEN 'ATTIVO DAL ' + @DATASTATO
	WHEN 'R' THEN 'LOTTO REVOCATO DAL ' + @DATASTATO
	WHEN 'S' THEN 'LOTTO SOSPESO DAL ' + @DATASTATO
	WHEN 'M' THEN 'RICEVITORIA SMANTELLATA DAL ' + @DATASTATO
END
FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
AND LSRSER_LOTTO_TIPO_PROVV IN ('A', 'R', 'S', 'M', '')
AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
AND LSRSER_LOTTO_DATA_DECOR =
(
	SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
	FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
	AND LSRSER_LOTTO_TIPO_PROVV IN ('A', 'R', 'S', 'M', '')
	AND LSRSER_LOTTO_FLAG_VALIDITA = 'Y'
	AND LSRSER_LOTTO_DATA_DECOR <= @DATARIATTIV
)

/*
--CDS: Modifica del 28/04/2008
 	 eliminato controllo stato del lotto
IF @STATOLOTTO IS NOT NULL
BEGIN
	SELECT @MSGERR = @STATOLOTTO
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

*/


/*
SELECT @ABI = NULL
SELECT @CAB = NULL
SELECT @BANCA = NULL
SELECT @CODSER = '09'


EXEC GEV_ESISTE_RID @CODLTM, @DATARIATTIV, @CODSER, @ABI OUTPUT, @CAB OUTPUT, @BANCA OUTPUT

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'RID INESISTENTE PER LA RICEVITORIA ' + @CODLTM + ' / ' + @CODSGI
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END
*/

BEGIN TRANSACTION

SELECT @DATAORAINS = NULL

SELECT @DATAORAINS = MAX(LSRLET_KEY_DATA_INS + LSRLET_KEY_ORA_INS)
FROM LSRLET	WHERE LSRLET_KEY_ID_RICEV = @CODLTM
AND LSRLET_COD_SERVIZIO = '09'
AND LSRLET_TIPO_MOVIMENTAZIONE = 'R'
AND LSRLET_KEY_DATA_INS = @DATAINS
AND LSRLET_DECOR_DAL = '00000000'

IF @DATAORAINS IS NOT NULL
BEGIN
	UPDATE LSRLET SET LSRLET_DECOR_DAL = @DATARIATTIV
	WHERE LSRLET_KEY_ID_RICEV = @CODLTM
	AND LSRLET_KEY_DATA_INS + LSRLET_KEY_ORA_INS = @DATAORAINS
	AND LSRLET_COD_SERVIZIO = '09'
	AND LSRLET_TIPO_MOVIMENTAZIONE = 'R'
END
ELSE
BEGIN
	INSERT INTO LSRLET VALUES
	(@CODLTM, @DATAINS, @ORAINS, '09', 'R', @DATARIATTIV, '', '', '00000000', @NOTE, @FIRMA, 'V')
END

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = @CODLTM + ' / ' + @CODSGI + ' ERRORE IN INSERT/UPDATE SU LSRLET'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


INSERT INTO LSRSER_GEV VALUES 
		(@CODLTM, 
		@DATAINS, 
		@ORAINS, 
		'1', 
		 @DATARIATTIV, 
		'R', 
		NULL, 
		NULL, 
		NULL, 
		'',
		@FIRMA, 
		@NOTE, 
		'00000000', 
		'Y')

IF @@ERROR <> 0 
BEGIN
	SELECT @MSGERR = @CODLTM + ' / ' + @CODSGI + ' ERRORE IN INSERT SU LSRSER_GEV'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

COMMIT TRANSACTION
GO
