/****** Object:  StoredProcedure [dbo].[CREA_RAD_RIATTIVAZIONI_GS]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[CREA_RAD_RIATTIVAZIONI_GS]  

	@QUERYSQL 			VARCHAR(2500),
	@OPERAZIONE 		CHAR(1), 
	@CODSER 		CHAR(2),
	@CON	 			CHAR(15), 
	@QST	 			CHAR(15), 
	@NUO	 			CHAR(15), 
	@FID	 			CHAR(15), 
	@TLP				CHAR(15), 
	@RAD	 			CHAR(15), 
	@RID	 			CHAR(15), 
	@ANNOINIZIOCAMPIONATO	CHAR(4),
	@NOMESERVER 		CHAR(20), 
	@FIRMA	 		CHAR(17), 
	@RC		 		CHAR(2500)  OUTPUT



AS

DECLARE

@RICEV		CHAR(6),
@DENOM		CHAR(50),
@RICERIN		CHAR(6),
@RICEAPPO		CHAR(7),
@RICESER		CHAR(6),
@RICEFID		CHAR(6),
@STATOLOT		CHAR(1),
@STATODIA		CHAR(1),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@PARTITAIVA		CHAR(11),
@NOMEFILE		VARCHAR(100),
@DATARINRIN		CHAR(8),
@STATOOGGI		CHAR(1),
@STATODOM		CHAR(1),
@FLAGADESIONE	CHAR(1), 
@ABI			CHAR(5),
@CAB			CHAR(5),
@NUMREC		INT,
@PATHID		INT,
@NOMEJOB		CHAR(6)


SELECT @NOMEJOB = 'NO_LOG'


SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @CON = RTRIM(@CON)
SELECT @QST = RTRIM(@QST)
SELECT @FID = RTRIM(@FID)
SELECT @NUO = RTRIM(@NUO)
SELECT @TLP = RTRIM(@TLP)
SELECT @RAD = RTRIM(@RAD)
SELECT @RID = RTRIM(@RID)

select @PATHID = 80
SELECT @NUMREC = 0

SELECT @NOMEFILE ='GS_'+@OPERAZIONE+'_'+@DATAINS+'.txt'

--CANCELLO IL FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB

SELECT @QUERYSQL = 'SELECT DISTINCT(RICEV) FROM (' + RTRIM(@QUERYSQL)  + ' ) Q WHERE RICEV  IN 
				(SELECT DISTINCT(LSRSER_TRIS_KEY_ID_RICEV) FROM LSRSER_TRIS A
				WHERE LSRSER_TRIS_FLAG_VALIDITA = ''Y''
					AND (LSRSER_TRIS_STATO = ''2'' OR LSRSER_TRIS_STATO = ''3'')
					AND LSRSER_TRIS_DATA_DECOR = (
						SELECT MAX(LSRSER_TRIS_DATA_DECOR) 
						FROM LSRSER_TRIS
						WHERE LSRSER_TRIS_DATA_DECOR <=  ' + '''' + @DATAINS  + '''' +
						'AND LSRSER_TRIS_FLAG_VALIDITA = ''Y''
						AND LSRSER_TRIS_KEY_ID_RICEV = A.LSRSER_TRIS_KEY_ID_RICEV
					)
				)'

SELECT @QUERYSQL = 'DECLARE CUR_CON CURSOR FOR ' + RTRIM(@QUERYSQL)  + ' ORDER BY 1'
print @QUERYSQL
EXECUTE (@QUERYSQL) 
OPEN CUR_CON FETCH NEXT FROM CUR_CON INTO @RICEV WHILE @@FETCH_STATUS = 0 

BEGIN

	SELECT @RICERIN = NULL
	SELECT @DATARINRIN = NULL

	--VERIFICO SE CI SONO RINUNCE AL SERVIZIO E SE E' IMPOSTATA LA
	--DATA DELLA RINUNCIA DELLA RINUNCIA
	SELECT @RICERIN = LSRRIN_CONI_KEY_ID_RICEV ,
		@DATARINRIN = LSRRIN_CONI_DATA_RINUNCIA_RINUNCIA
	FROM LSRRIN_CONI
	WHERE LSRRIN_CONI_KEY_ID_RICEV = @RICEV
	AND LSRRIN_CONI_FLAG_ANAG = '1'
	AND LSRRIN_CONI_CODICE_SERVIZIO = '08'

	IF @RICERIN = '' OR @RICERIN IS NULL OR @RICERIN = ' ' OR (@DATARINRIN <>''  AND @DATARINRIN <>'00000000' AND @DATARINRIN IS NOT NULL)
	BEGIN
		SELECT @STATODOM = NULL
		SELECT @STATOOGGI = NULL
		SELECT @RICESER = NULL

		--VERIFICO LO STATO DEL SERVIZIO
		SELECT @STATODOM = LSRSER_TRIS_STATO
		FROM LSRSER_TRIS
		WHERE LSRSER_TRIS_KEY_ID_RICEV = @RICEV
			AND LSRSER_TRIS_FLAG_VALIDITA = 'Y'
			AND LSRSER_TRIS_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)
	
		IF @STATODOM = '' OR @STATODOM IS NULL
		BEGIN
			SELECT @NUMREC = @NUMREC + 1
			EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

			EXECUTE SCRIVI_LSRLET_GS @RICEV, @CODSER,  @CON, @QST, @NUO, @FID, @TLP, @RAD, @RID, @ANNOINIZIOCAMPIONATO, '', @DATAINS, @ORAINS, @OPERAZIONE, @FIRMA

		END
	END

	FETCH NEXT FROM CUR_CON INTO @RICEV

END


SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)



--SELECT @RC =  @NOMEFILE

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
