/****** Object:  StoredProcedure [dbo].[CREA_RAD_RIATTIVAZIONI_ST]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[CREA_RAD_RIATTIVAZIONI_ST]  
	@QUERYSQL 			VARCHAR(2500),
	@OPERAZIONE 		CHAR(1), 
	@CON	 			CHAR(15), 
	@TLP	 			CHAR(15),
	@NUO	 			CHAR(15), 
	@FID	 			CHAR(15), 
	@RAD	 			CHAR(15), 
	@RID	 			CHAR(15), 
	@ANNOINIZIOCAMPIONATO 	CHAR(4),
	@NOMESERVER 		CHAR(20), 
	@FIRMA	 		CHAR(17), 
	@RC		 		CHAR(70)  OUTPUT
 
AS


DECLARE


@RICEV			CHAR(6),
@DENOM 			CHAR(50),
@RICERIN		CHAR(6),
@RICEAPPO		CHAR(7),
@RICESER		CHAR(6),
@RICEFID		CHAR(6),
@RICEAPS		CHAR(6),
@PALRICEV		CHAR(8),
@STATOCONI		CHAR(1),
@STATOOGGI		CHAR(1),
@STATODOM		CHAR(1),
@ORAINS			CHAR(8),
@DATAINS		CHAR(8),
@DATARINRIN		CHAR(8),
@DATA1			CHAR(8),
@DATA2			CHAR(8),
@RADFONTE		CHAR(1),
@RADCAUSALELTM		CHAR(1),
@FLAGPALETTO		CHAR(1),
@PARTITAIVA		CHAR(11),
@NOMEFILE		CHAR(100),
@NOMEJOB		CHAR(6),
@STATOLOT		CHAR(1),
@ABI			CHAR(5),
@CAB			CHAR(5),
@NUMREC			INT,
@PATHID			INT


SELECT @NOMEJOB = 'NO_LOG'


SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @CON = RTRIM(@CON)
SELECT @TLP = RTRIM(@TLP)
SELECT @NUO = RTRIM(@NUO)
SELECT @FID = RTRIM(@FID)
SELECT @RAD = RTRIM(@RAD)
SELECT @RID = RTRIM(@RID)

SELECT @PATHID = 80
SELECT @NUMREC = 0

SELECT @NOMEFILE ='ST_'+@OPERAZIONE+'_'+@DATAINS+'.txt'

--CANCELLO FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB

	SELECT @QUERYSQL = 'SELECT DISTINCT(RICEV) FROM (' + RTRIM(@QUERYSQL)  + ' ) Q WHERE RICEV  IN 
					(SELECT DISTINCT(LSRSER_ST_KEY_ID_RICEV) FROM LSRSER_ST A
					WHERE LSRSER_ST_FLAG_VALIDITA = "Y"
						AND LSRSER_ST_STATO = "2" 
						AND LSRSER_ST_DATA_DECOR = (
							SELECT MAX(LSRSER_ST_DATA_DECOR) 
							FROM LSRSER_ST
							WHERE LSRSER_ST_DATA_DECOR <=  ' + '"' + @DATAINS  + '"' +
							'AND LSRSER_ST_FLAG_VALIDITA = "Y"
							AND LSRSER_ST_KEY_ID_RICEV = A.LSRSER_ST_KEY_ID_RICEV
						)
					)'

SELECT @QUERYSQL = 'DECLARE CUR_CON CURSOR FOR ' + RTRIM(@QUERYSQL) + ' ORDER BY 1' 
EXECUTE (@QUERYSQL) 
--PRINT @QUERYSQL
OPEN CUR_CON 
FETCH NEXT FROM CUR_CON INTO @RICEV 
WHILE @@FETCH_STATUS = 0 

BEGIN
	SELECT @STATODOM = NULL
	SELECT @STATOOGGI = NULL
	SELECT @RICESER = NULL

	--VERIFICO LO STATO DEL SERVIZIO
	SELECT @STATODOM = LSRSER_ST_STATO
	FROM LSRSER_ST
	WHERE LSRSER_ST_KEY_ID_RICEV = @RICEV
		AND LSRSER_ST_FLAG_VALIDITA = 'Y'
		AND LSRSER_ST_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)

	IF @STATODOM = '' OR @STATODOM IS NULL
	BEGIN

		/*
		CONTROLLO - STATO CONI ATTIVO
		*/
		SELECT @STATOCONI = ''
		SELECT @STATOCONI = LSRSER_CONI_STATO 
		FROM LSRSER_CONI
		WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEV
			AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
			AND LSRSER_CONI_DATA_DECOR =
			(
				SELECT MAX(LSRSER_CONI_DATA_DECOR) 
				FROM LSRSER_CONI
				WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEV
				AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
				AND LSRSER_CONI_DATA_DECOR <= @DATAINS
			)
		
		IF @STATOCONI =  '1' 
		BEGIN

			SELECT @FLAGPALETTO = '1'
			--*******************************************************--
			--           INIZIO GESTIONE PALETTI
			--*******************************************************--
		
			IF @RAD <> '0'
			BEGIN
	
				SELECT @DATA1 = MAX(LSRSER_ST_DATA_DECOR) 
				FROM LSRSER_ST B
				WHERE LSRSER_ST_FT_VOS <> '00000000' 
					AND LSRSER_ST_FLAG_VALIDITA = 'Y' 
					AND LSRSER_ST_STATO = '1' 
					AND LSRSER_ST_KEY_ID_RICEV =  @RICEV
				GROUP BY LSRSER_ST_KEY_ID_RICEV, LSRSER_ST_STATO 
			
				SELECT @DATA2 = MIN(LSRSER_ST_DATA_DECOR) 
				FROM LSRSER_ST A 
				WHERE A.LSRSER_ST_FT_VOS <> '00000000' 
					AND A.LSRSER_ST_FLAG_VALIDITA = 'Y' 
					AND A.LSRSER_ST_STATO = '2' 
					AND A.LSRSER_ST_DATA_DECOR >=  @DATA1
					AND A.LSRSER_ST_KEY_ID_RICEV = @RICEV 
	PRINT @DATA2
			 	DECLARE CUR_PAL SCROLL CURSOR FOR
		
				SELECT lsrrad_st_fonte, lsrrad_st_causale_lottomatica 
				FROM LSRRAD_ST  
				WHERE LSRRAD_ST_KEY_ID_RICEV  =  @RICEV
					AND LSRRAD_ST_KEY_DATA_INS + LSRRAD_ST_KEY_ORA_INS = (
						SELECT  LSRLET_ST_FK_TAB_DOCUMENTO 
						FROM LSRLET_ST 
						WHERE LSRLET_ST_KEY_ID_RICEV  = @RICEV
							AND LSRLET_ST_TIPO_MOVIMENTAZIONE = 'D' 
							AND LSRLET_ST_DECOR_DAL = @DATA2
							AND LSRLET_ST_NOME_TAB_DOCUMENTO = 'LSRRAD_ST'
							AND LSRLET_ST_DECOR_DAL <> '00000000'
					)
			
				UNION
		
				SELECT lsrrad_st_fonte, lsrrad_st_causale_lottomatica 
				FROM LSRRAD_ST 
				WHERE LSRRAD_ST_KEY_ID_RICEV  = @RICEV
					AND LSRRAD_ST_TIPO_MOVIMENTAZIONE = 'D' 
					AND LSRRAD_ST_DATA_INVIO_DOC > @DATA2
		
		
				--VERIFICO CHE ESISTONO I CONTRO-PALETTI
				OPEN CUR_PAL
				FETCH NEXT FROM CUR_PAL INTO @RADFONTE, @RADCAUSALELTM 
				WHILE @@FETCH_STATUS = 0 AND @FLAGPALETTO = '1' 
				BEGIN
					
	PRINT @RADFONTE
	PRINT @RADCAUSALELTM
					-- VERIFICO SE ESISTE IL CONTRO-PALETTO
					IF (@RADFONTE = 'M' OR @RADFONTE = 'A' )
					BEGIN			
						SELECT @PALRICEV = '' 
						SELECT @PALRICEV = LSRRAD_ST_KEY_ID_RICEV
						FROM LSRRAD_ST 
						WHERE LSRRAD_ST_KEY_ID_RICEV  = @RICEV
							AND lsrrad_ST_fonte = @RADFONTE
							AND lsrrad_ST_data_decor >= @DATA2
							and lsrrad_ST_tipo_movimentazione = 'R' 
						IF @PALRICEV = '' OR @PALRICEV IS NULL
							SELECT @FLAGPALETTO = '0'
						
					END
					-- VERIFICO SE ESISTE IL CONTRO-PALETTO
					IF @RADFONTE = 'L' 
					BEGIN
						SELECT @PALRICEV = '' 
						SELECT @PALRICEV = LSRRAD_ST_KEY_ID_RICEV
						FROM LSRRAD_ST 
						WHERE LSRRAD_ST_KEY_ID_RICEV  = @RICEV
							AND lsrrad_ST_fonte = @RADFONTE
							AND lsrrad_ST_data_decor >= @DATA2
							and lsrrad_ST_tipo_movimentazione = 'R' 
							AND lsrrad_ST_causale_lottomatica = @RADCAUSALELTM
						IF @PALRICEV = '' OR @PALRICEV IS NULL
							SELECT @FLAGPALETTO = '0'
					
					END
	
					FETCH NEXT FROM CUR_PAL INTO @RADFONTE, @RADCAUSALELTM 
			
				END
				CLOSE CUR_PAL
				DEALLOCATE CUR_PAL
		
				-- VERIFICO SE ESISTE IL SUPER-PALETTO
				IF @FLAGPALETTO = '0'
				BEGIN
					SELECT @PALRICEV = '' 
					SELECT @PALRICEV = LSRRAD_ST_KEY_ID_RICEV
					FROM LSRRAD_ST 
					WHERE LSRRAD_ST_KEY_ID_RICEV  = @RICEV
						AND lsrrad_ST_fonte = @RADFONTE
						AND lsrrad_ST_data_decor >= @DATA2
						and lsrrad_ST_tipo_movimentazione = 'R' 
						AND lsrrad_ST_causale_lottomatica = '4'
					IF @PALRICEV <> ''
						SELECT @FLAGPALETTO = '1'
				END
		
			END
		
		
			--*******************************************************--
			--           FINE GESTIONE PALETTI
			--*******************************************************--
			IF (@FLAGPALETTO = '1')
			BEGIN
				SELECT @NUMREC = @NUMREC + 1
				EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB
	
				EXECUTE SCRIVI_LSRLET_ST @RICEV,  @CON, @TLP, @NUO, @FID, @RAD, @RID, @ANNOINIZIOCAMPIONATO, @DATAINS, @ORAINS, @OPERAZIONE, @FIRMA
			END
		END
	END

	FETCH NEXT FROM CUR_CON INTO @RICEV

END

SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)
--SELECT @RC =  @NOMEFILE

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
