/****** Object:  StoredProcedure [dbo].[CREA_RAD_DISATTIVAZIONI_CONI]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[CREA_RAD_DISATTIVAZIONI_CONI] 

	@QUERYSQL 			VARCHAR(2500),
	@OPERAZIONE 		CHAR(1), 
	@CON	 			CHAR(15), 
	@QST	 			CHAR(15),
	@NUO	 			CHAR(15), 
	@FID	 			CHAR(15), 
	@RAD	 			CHAR(15), 
	@RID	 			CHAR(15), 
	@ANNOINIZIOCAMPIONATO	CHAR(4),
	@NOMESERVER 		CHAR(20), 
	@FIRMA	 		CHAR(17), 
	@RC		 		CHAR(70)  OUTPUT


AS


DECLARE


@RICEV		CHAR(6),
@RICERIN		CHAR(6),
@RICEAPPO		CHAR(6),
@RICESER		CHAR(6),
@RICEFID		CHAR(6),
@STATOOGGI		CHAR(1),
@STATODOM		CHAR(1),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@NOMEFILE		VARCHAR(100),
@NOMEJOB		CHAR(6),
@NUMREC		INT,
@PATHID		INT

SELECT @NOMEJOB = 'NO_LOG'

SELECT @DATAINS = CONVERT(CHAR,GETDATE(),112)
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(),121),12,2) + 
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),15,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),18,2) +
		SUBSTRING(CONVERT(CHAR,GETDATE(),121),21,2)


SELECT @CON = RTRIM(@CON)
SELECT @QST = RTRIM(@QST)
SELECT @NUO = RTRIM(@NUO)
SELECT @FID = RTRIM(@FID)
SELECT @RAD = RTRIM(@RAD)
SELECT @RID = RTRIM(@RID)

SELECT @PATHID = 80
SELECT @NUMREC = 0

SELECT @NOMEFILE ='CONI_' + @OPERAZIONE+'_'+ @DATAINS + '.txt'

--CANCELLO FILE DI OUTPUT
EXEC MSDB..UT_AA009 @PATHID, @NOMEFILE, 9999, @NOMEJOB

SELECT @QUERYSQL = 'DECLARE CUR_CON CURSOR FOR ' + RTRIM(@QUERYSQL) + ' ORDER BY 1'
EXECUTE (@QUERYSQL) 
OPEN CUR_CON 
FETCH NEXT FROM CUR_CON INTO @RICEV 
WHILE @@FETCH_STATUS = 0 

BEGIN

	SELECT @STATODOM = NULL
	SELECT @STATOOGGI = NULL
	SELECT @RICESER = NULL

	--VERIFICO LO STATO DEL SERVIZIO
	SELECT @STATODOM = LSRSER_CONI_STATO
	FROM LSRSER_CONI
	WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEV
	AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
	AND LSRSER_CONI_DATA_DECOR = CONVERT(CHAR,GETDATE() + 1,112)


	IF @STATODOM = '' OR @STATODOM IS NULL
	BEGIN
		SELECT @STATOOGGI = LSRSER_CONI_STATO
		FROM LSRSER_CONI
		WHERE LSRSER_CONI_KEY_ID_RICEV = @RICEV
		AND LSRSER_CONI_DATA_DECOR =
		(
			SELECT MAX(LSRSER_CONI_DATA_DECOR) FROM LSRSER_CONI 
			WHERE LSRSER_CONI_DATA_DECOR <= CONVERT(CHAR,GETDATE() ,112)
			AND LSRSER_CONI_KEY_ID_RICEV = @RICEV
			AND LSRSER_CONI_FLAG_VALIDITA = 'Y'
		)
		AND LSRSER_CONI_FLAG_VALIDITA = 'Y'

		IF @STATOOGGI = '1'
		BEGIN
			SELECT @NUMREC = @NUMREC + 1

			EXEC MSDB..UT_AA010 9999, @PATHID, @NOMEFILE, @RICEV, @NOMEJOB

			EXECUTE SCRIVI_LSRLET_CONI @RICEV, @CON, @QST, @NUO, @FID, @RAD, @RID, @ANNOINIZIOCAMPIONATO, @DATAINS,@ORAINS,@OPERAZIONE,@FIRMA
		END
	END



FETCH NEXT FROM CUR_CON INTO @RICEV

END

SELECT @RC = @DATAINS+CONVERT(CHAR,@NUMREC)
--SELECT @RC =  @NOMEFILE

CLOSE CUR_CON
DEALLOCATE CUR_CON
GO
