/****** Object:  StoredProcedure [dbo].[GEV_ACQUISIZIONE_RINUNCE]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GEV_ACQUISIZIONE_RINUNCE] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@TIPOACQ		CHAR(1),
@DATADOC		CHAR(8),
@DATAINVIODOC	CHAR(8),
@PROTDOC		VARCHAR(25),
@COGNOME		VARCHAR(24),
@NOME		VARCHAR(20),
@DATARIN1		CHAR(8),
@DATARIN2		CHAR(8),
@ASSOCIAZIONE	VARCHAR(2),
@FLGANAG		CHAR(1),
@FKINSTIT		CHAR(16),		
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)



AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@DATAAPPO		CHAR(8),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSTITGEV	CHAR(8),
@FKORAINSTITGEV	CHAR(8),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20),
@FLGANAGOLD	CHAR(1)


SELECT @RICEAPPO = NULL
SELECT @FKDATAINSTITGEV = '00000000'
SELECT @FKORAINSTITGEV = '00000000'

SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 8, 8)

IF @DATARIN1 IS NULL OR LTRIM(RTRIM(@DATARIN1)) = ''
BEGIN
	SELECT @DATARIN1 = '00000000'
END

IF @DATARIN2 IS NULL OR LTRIM(RTRIM(@DATARIN2)) = ''
BEGIN
	SELECT @DATARIN2 = '00000000'
END

IF @DATARIN1 = '00000000'
BEGIN
	SELECT @MSGERR = '9 - DATA RINUNCIA MANCANTE'
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

SELECT @MSGERR = NULL

EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

SELECT @MSGERR = NULL

EXEC GEV_DECOD_RICEV @CODLTM, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

SELECT @COGNOMEOLD = NULL
SELECT @NOMEOLD = NULL

SELECT @COGNOMEOLD = LSRRIN_GEV_COGNOME, @NOMEOLD = LSRRIN_GEV_NOME
FROM LSRRIN_GEV
WHERE LSRRIN_GEV_COD_LOTTO = @CODLTM
AND LSRRIN_GEV_COGNOME = @COGNOME
AND LSRRIN_GEV_NOME = @NOME
AND LSRRIN_GEV_DATA_RIN_RIN = '00000000'
AND LSRRIN_GEV_DATA_RIN <> '00000000'

IF @COGNOMEOLD IS NOT NULL
BEGIN
	SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO INTESTATO A ' + @COGNOME + ' ' + @NOME
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- IMPOSTO IL TIPO DI ASSOCIAZIONE TRA DOCUMENTO E CONTRAENTE (SOLO PER ACQUISIZIONE DA FILE)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF @TIPOACQ = 'F'
BEGIN

	SELECT @MSGERR = NULL
	SELECT @FLGANAG = NULL
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	
	EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTIT OUTPUT, @FKORAINSTIT OUTPUT

	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

SELECT @RICEAPPO = NULL
SELECT @FLGANAGOLD = NULL
SELECT @MSGERR = NULL

SELECT @FLGANAGOLD = LSRRIN_GEV_FLAG_ANAG
FROM LSRRIN_GEV
WHERE LSRRIN_GEV_KEY_ID_RICEV = @CODSGI
AND LSRRIN_GEV_FLAG_ANAG = @FLGANAG

IF @FLGANAGOLD IS NOT NULL
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO NON ASSOCIATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '2' 
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END	
ELSE
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO NON ASSOCIATO AD ALCUN TITOLARE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '2' 
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
	END

END

BEGIN TRANSACTION

INSERT INTO LSRRIN_GEV VALUES
(@CODSGI, @DATAINS, @ORAINS, @CODLTM, @CODAMM, @TIPOACQ, @DATADOC, @DATAINVIODOC, @PROTDOC, @ASSOCIAZIONE,
 @COGNOME, @NOME, @DATARIN1, @DATARIN2, @NOTE, @FLGANAG, @FKDATAINSTIT, @FKORAINSTIT, 
 @FKDATAINSTITGEV, @FKORAINSTITGEV, @FIRMA)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	COMMIT TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
GO
