/****** Object:  StoredProcedure [dbo].[GEV_ACQUISIZIONE_RAD]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  PROCEDURE [dbo].[GEV_ACQUISIZIONE_RAD] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@TIPOACQ	CHAR(1),
@TIPOMOV		CHAR(1),
@DATADECOR		CHAR(8),
@DATADOC		CHAR(8),
@DATAINVIODOC	CHAR(8),
@PROTDOC		VARCHAR(25),
@ASSOCIAZIONE	CHAR(1),
@FONTE		CHAR(3),
@CAUSALE		VARCHAR(50),
@COGNOME		VARCHAR(24),
@NOME		VARCHAR(20),
@FLGANAG	CHAR(1),
@FKINSTIT	VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)


AS 

DECLARE

@STATO		CHAR(1),
@DECORSTATO	CHAR(8),
@DATACOND		CHAR(8),
@RESULT		INT,
@MSGERR		VARCHAR(100),
@RICEAPPO		VARCHAR(7),
@FKDATAINSTIT		CHAR(8),
@FKORAINSTIT		CHAR(8),
@FKDATAINSTITGEV	CHAR(8),
@FKORAINSTITGEV	CHAR(8),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20),
@TIPOMOVAPPO		CHAR(1),
@FLGANAGOLD	CHAR(1)


SELECT @RICEAPPO = ''
SELECT @FKDATAINSTITGEV = null
SELECT @FKORAINSTITGEV = null
SELECT @FKDATAINSTIT = null
SELECT @FKORAINSTIT = null

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN
	SELECT @FKDATAINSTITGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTITGEV = SUBSTRING(@FKINSTIT, 9, 8)

END
ELSE
BEGIN
	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)

END


SELECT @MSGERR = NULL

-------------------------------------------------------------
-- CONTROLLO SE GIA' ESISTE UN DOCUMENTO RAD PER QUEL CONTRAENTE
-------------------------------------------------------------

SELECT @RICEAPPO = ''
SELECT @MSGERR = NULL

SELECT @COGNOMEOLD = ''
SELECT @NOMEOLD = NULL


/* CONTROLLO ELIMINATO IL 13/12/2004

SELECT @COGNOMEOLD = LSRRAD_COGNOME, @NOMEOLD = LSRRAD_NOME
FROM LSRRAD_GEV
WHERE LSRRAD_KEY_ID_RICEV = @CODSGI
AND LSRRAD_COGNOME = @COGNOME
AND LSRRAD_NOME = @NOME
 

IF @@ROWCOUNT > 0
BEGIN
	SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO INTESTATO A: ' + @COGNOME + ' ' + @NOME
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

*/
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- IMPOSTO IL TIPO DI ASSOCIAZIONE TRA DOCUMENTO E CONTRAENTE (SOLO PER ACQUISIZIONE DA FILE)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF @TIPOACQ = 'F'
BEGIN
	SELECT @MSGERR = NULL
	SELECT @FLGANAG = NULL
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSTITGEV = null
	SELECT @FKORAINSTITGEV = null

	EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT
	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END



	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO_CONI @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTITGEV OUTPUT, @FKORAINSTITGEV OUTPUT
	ELSE	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTIT OUTPUT, @FKORAINSTIT OUTPUT

	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

SELECT @RICEAPPO = NULL
SELECT @FLGANAGOLD = NULL
SELECT @MSGERR = NULL

SELECT @FLGANAGOLD = LSRRAD_FLAG_ANAG
FROM LSRRAD_GEV
WHERE LSRRAD_KEY_ID_RICEV = @CODSGI
AND LSRRAD_FLAG_ANAG = @FLGANAG

IF @FLGANAGOLD IS NOT NULL
BEGIN
	
	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO NON ASSOCIATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	/*
	ELSE IF @FLGANAG = '1'
	BEGIN

		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '2' 
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'

		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	*/

END	
ELSE
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @FKDATAINSTIT = NULL
		SELECT @FKORAINSTIT = NULL
		SELECT @FKDATAINSTITGEV = null
		SELECT @FKORAINSTITGEV = null
		SELECT @MSGERR = '0 - DOCUMENTO NON ASSOCIATO AD ALCUN TITOLARE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG >= '2' 
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
	END

END

BEGIN TRANSACTION


INSERT INTO LSRRAD_GEV VALUES (
	@CODSGI, 
	@DATAINS, 
	@ORAINS, 
	@CODLTM, 
	@CODAMM, 
	@TIPOACQ,
	@TIPOMOV, 
	@DATADECOR, 
	@DATADOC, 
	@DATAINVIODOC, 
	'00000000', 
	@PROTDOC, 
	@ASSOCIAZIONE, 
	@FONTE, 
	@CAUSALE, 
	@COGNOME, 
	@NOME, 
	@NOTE, 		
	@FLGANAG, 
	@FKDATAINSTIT, 
	@FKORAINSTIT, 
	@FKDATAINSTITGEV, 
	@FKORAINSTITGEV, 
	@FIRMA
	)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ACQUISIZIONE DOCUMENTO - RICEVITORIA: ' + @CODLTM
	RAISERROR (@MSGERR, 16, 1)
	COMMIT TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
GO
