/****** Object:  StoredProcedure [dbo].[GEV_ACQUISIZIONE_QUESTIONARI]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[GEV_ACQUISIZIONE_QUESTIONARI] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS	CHAR(8),
@ORAINS		CHAR(8),
@TIPOACQ	CHAR(1),
@DATADOC	CHAR(8),
@DATAINVIODOC	CHAR(8),
@PROTDOC	VARCHAR(25),
@COGNOME	VARCHAR(24),
@NOME		VARCHAR(20),
@ASSOCIAZIONE	CHAR(1),

@TIPOLOGIA	CHAR(2),
@ANNOINIZIO	CHAR(4),
@ORARIO		CHAR(30),
@GIORNORIPOSO	CHAR(1),
@NUMVETRINE	CHAR(1),
@SUPERFICIE	CHAR(1),
@INSEGNAESTERNA	CHAR(1),
@SPAZIOCLIENTE	CHAR(1),
@SPAZIOESPOS	CHAR(1),
@ESPOSITORI	CHAR(1),
@SUPERENALOTTO	CHAR(1),
@TOTOCALCIO	CHAR(1),
@TOTIP		CHAR(1),
@TRIS		CHAR(1),
@F101		CHAR(1),
@GEV		CHAR(1),
@INCASSOGEV	CHAR(10),
@PC		CHAR(1),
@STAMPANTE	CHAR(1),
@INTERNET	CHAR(1),
@UBICAZIONE	CHAR(1),
@VICINOA	CHAR(1),
@TELPRINC	CHAR(12),
@TELALTER	CHAR(12),
@FAX		CHAR(12),
@EMAIL		CHAR(50),

@FLGANAG	CHAR(1),
@FKINSTIT	VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)

AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@DATAAPPO		CHAR(8),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSTITGEV	CHAR(8),
@FKORAINSTITGEV	CHAR(8),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20),
@FLGANAGOLD	CHAR(1)


SELECT @RICEAPPO = ''
SELECT @FKDATAINSTITGEV = null
SELECT @FKORAINSTITGEV = null
SELECT @FKDATAINSTIT = null
SELECT @FKORAINSTIT = null

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN
	SELECT @FKDATAINSTITGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTITGEV = SUBSTRING(@FKINSTIT, 9, 8)

END
ELSE
BEGIN
	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)

END


SELECT @MSGERR = NULL

/* 	COMMENTO AGGIUNTO DA CDS: I CODICI SONO GIà TUTTI VALORIZZATI, QUINDI
	LE CHIAMATE SONO INUTILI

EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

SELECT @MSGERR = NULL

EXEC GEV_DECOD_RICEV @CODLTM, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END
*/
-------------------------------------------------------------
-- CONTROLLO SE GIA' ESISTE UN QUESTIONARIO PER QUEL CONTRAENTE
-------------------------------------------------------------

SELECT @RICEAPPO = ''
SELECT @MSGERR = NULL

SELECT @COGNOMEOLD = ''
SELECT @NOMEOLD = NULL

SELECT @COGNOMEOLD = LSRQST_GEV_COGNOME, @NOMEOLD = LSRQST_GEV_NOME
FROM LSRQST_GEV
WHERE LSRQST_GEV_KEY_ID_RICEV = @CODSGI
AND LSRQST_GEV_COGNOME = @COGNOME
AND LSRQST_GEV_NOME = @NOME


IF @@ROWCOUNT > 0
BEGIN
	SELECT @MSGERR = '9 - ESISTE GIA UN QUESTIONARIO INTESTATO A: ' + @COGNOME + ' ' + @NOME
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- IMPOSTO IL TIPO DI ASSOCIAZIONE TRA DOCUMENTO E CONTRAENTE (SOLO PER ACQUISIZIONE DA FILE)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF @TIPOACQ = 'F'
BEGIN

	SELECT @MSGERR = NULL
	SELECT @FLGANAG = NULL
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSTITGEV = null
	SELECT @FKORAINSTITGEV = null

	EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT
	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END


	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO_CONI @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTITGEV OUTPUT, @FKORAINSTITGEV OUTPUT
	ELSE	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTIT OUTPUT, @FKORAINSTIT OUTPUT


	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

SELECT @RICEAPPO = NULL
SELECT @FLGANAGOLD = NULL
SELECT @MSGERR = NULL

SELECT @FLGANAGOLD = LSRQST_GEV_FLAG_ANAG
FROM LSRQST_GEV
WHERE LSRQST_GEV_KEY_ID_RICEV = @CODSGI
AND LSRQST_GEV_FLAG_ANAG = @FLGANAG

IF @FLGANAGOLD IS NOT NULL
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO NON ASSOCIATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '2' 
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END	
ELSE
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @FKDATAINSTIT = NULL
		SELECT @FKORAINSTIT = NULL
		SELECT @FKDATAINSTITGEV = null
		SELECT @FKORAINSTITGEV = null

		SELECT @MSGERR = '0 - DOCUMENTO NON ASSOCIATO AD ALCUN TITOLARE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG >= '2' 
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
	END

END

BEGIN TRANSACTION

INSERT INTO LSRQST_GEV VALUES
(@CODSGI, 
@DATAINS, 
@ORAINS, 
@CODLTM, 
@CODAMM, 
@TIPOACQ, 
@DATADOC, 
@DATAINVIODOC, 
@PROTDOC, 
@ASSOCIAZIONE, 
@COGNOME, 
@NOME, 

@TIPOLOGIA,
@ANNOINIZIO,
@ORARIO,
@GIORNORIPOSO,
@NUMVETRINE,
@SUPERFICIE,
@INSEGNAESTERNA,
@SPAZIOCLIENTE,
@SPAZIOESPOS,
@ESPOSITORI,
@SUPERENALOTTO,
@TOTOCALCIO,
@TOTIP,
@TRIS,
@F101,
@GEV,
@INCASSOGEV,
@PC,
@STAMPANTE,
@INTERNET,
@UBICAZIONE,
@VICINOA,
@TELPRINC,
@TELALTER,
@FAX,
@EMAIL,
@NOTE, 

NULL,
NULL,

@FLGANAG, 
@FKDATAINSTIT, 
@FKORAINSTIT, 
@FKDATAINSTITGEV, 
@FKORAINSTITGEV, 
@FIRMA)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
GO
