/****** Object:  StoredProcedure [dbo].[GEV_ACQUISIZIONE_ORDINE]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[GEV_ACQUISIZIONE_ORDINE] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS	CHAR(8),
@ORAINS		CHAR(8),
@TIPOACQ	CHAR(1),
@COGNOME	VARCHAR(24),
@NOME		VARCHAR(20),
@IDGIOCO	CHAR(4),
@NUMPACCHI	CHAR(3),
@FLGANAG	CHAR(1),
@FKINSTIT	VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)

AS 

DECLARE

@RETE			CHAR(1),
@RESULT			INT,
@MSGERR			VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@DATAAPPO		CHAR(8),
@FKDATAINSTIT		CHAR(8),
@FKORAINSTIT		CHAR(8),
@FKDATAINSTITGEV	CHAR(8),
@FKORAINSTITGEV		CHAR(8),
@COGNOMEOLD		VARCHAR(24),
@NOMEOLD		VARCHAR(20),
@FLGANAGOLD		CHAR(1)


SELECT @RICEAPPO = ''
SELECT @FKDATAINSTITGEV = null
SELECT @FKORAINSTITGEV = null
SELECT @FKDATAINSTIT = null
SELECT @FKORAINSTIT = null

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN
	SELECT @FKDATAINSTITGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTITGEV = SUBSTRING(@FKINSTIT, 9, 8)

END
ELSE
BEGIN
	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)

END


SELECT @MSGERR = NULL


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- IMPOSTO IL TIPO DI ASSOCIAZIONE TRA DOCUMENTO E CONTRAENTE (SOLO PER ACQUISIZIONE DA FILE)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF @TIPOACQ = 'F'
BEGIN
	SELECT @MSGERR = NULL
	SELECT @FLGANAG = NULL
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSTITGEV = null
	SELECT @FKORAINSTITGEV = null

	EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT
	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END



	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO_CONI @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTITGEV OUTPUT, @FKORAINSTITGEV OUTPUT
	ELSE	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTIT OUTPUT, @FKORAINSTIT OUTPUT

	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

IF @FLGANAG = '0'
BEGIN
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSTITGEV = null
	SELECT @FKORAINSTITGEV = null
	SELECT @MSGERR = '0 - DOCUMENTO NON ASSOCIATO AD ALCUN TITOLARE'
	RAISERROR (@MSGERR, 16, 1)
END
ELSE IF @FLGANAG = '1'
BEGIN
	SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
	RAISERROR (@MSGERR, 16, 1)
END
ELSE IF @FLGANAG >= '2' 
BEGIN
	SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
	RAISERROR (@MSGERR, 16, 1)
END


BEGIN TRANSACTION

INSERT INTO LSRORD_GEV VALUES(
			@CODSGI, 
			@DATAINS, 
			@ORAINS, 
			@CODLTM, 
			@TIPOACQ, 
			@COGNOME, 
			@NOME, 
			@IDGIOCO,
			@NUMPACCHI,
			@NOTE, 
			@FLGANAG, 
			@FKDATAINSTIT, 
			@FKORAINSTIT, 
			@FKDATAINSTITGEV, 
			@FKORAINSTITGEV, 
			@FIRMA
			)


IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
GO
