/****** Object:  StoredProcedure [dbo].[INSERTPROVVSTATO]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[INSERTPROVVSTATO]

	@RICEVITORIA 	CHAR(6),
	@DATADECOR		CHAR(8),
	@DATAPROVV		CHAR(8),
	@TIPOPROVV		CHAR(1),
	@NUMPROVV		CHAR(14),
	@CAUSALE		CHAR(40),
	@EMANATO		CHAR(25),
	@FIRMA		CHAR(17),
	@NOTE		CHAR(150),
	@FLAGVAL		CHAR(1),
	@SERVIZIO		CHAR(2),
	@IDTAB		CHAR(10),
	@OPZIONE		CHAR(1),
	@OLDPROVV		CHAR(1),
	@OLDDATAPROVV	CHAR(8),
	@OLDPROGPROVV	CHAR(14),
	@OPZDIS		CHAR(5),
	@NUMERR 		VARCHAR(4) OUTPUT,
	@MSGERR 		VARCHAR(50) OUTPUT
AS

DECLARE 

@OGGI			CHAR(8),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@DATAINSLET		CHAR(8),
@ORAINSLET		CHAR(8),
@DATAAPPO		CHAR(8)

SELECT @OGGI = CONVERT(CHAR(8),GETDATE(),112)
SELECT @DATAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),1,4) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),6,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),9,2) 
SELECT @ORAINS = SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),12,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),15,2) + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),18,2)  + SUBSTRING(CONVERT(CHAR(25),GETDATE(),121),21,2) 
SELECT @DATAAPPO = NULL

BEGIN TRANSACTION

IF @SERVIZIO = '01' --- NUOVO PROVVEDIMENTO LOTTO
BEGIN
--	BEGIN TRANSACTION


	SELECT @DATAAPPO = LSRPRO_DECOR_DAL 
	FROM LSRPRO 
	WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
	AND LSRPRO_FLAG_VALIDITA = 'Y'
	AND LSRPRO_KEY_TIPO_REC IN ('A', 'R', 'S', 'M')
	AND LSRPRO_DECOR_DAL =
	(
		SELECT MAX(LSRPRO_DECOR_DAL)
		FROM LSRPRO 
		WHERE LSRPRO_KEY_ID_RICEV = @RICEVITORIA
		AND LSRPRO_FLAG_VALIDITA = 'Y'
		AND LSRPRO_KEY_TIPO_REC IN ('A', 'R', 'S', 'M')
		AND LSRPRO_DECOR_DAL <= CONVERT(CHAR, GETDATE(), 112)
	)

	IF @DATAAPPO IS NOT NULL
	BEGIN
		IF @DATAAPPO >= @DATADECOR
		BEGIN
	                           SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' - DATA DECORRENZA PROVVEDIMENTO INFERIORE ALLA DATA DECORRENZA DELLO STATO ATTUALE'
            			ROLLBACK TRANSACTION
	                           RETURN 
		END
	END

 	EXEC  INSERT_LSRPRO @RICEVITORIA,@DATAINS,@ORAINS,
				@TIPOPROVV,@DATAPROVV,
				@NUMPROVV,@CAUSALE,@FIRMA,
				@EMANATO,@DATADECOR,@OGGI,@IDTAB,
				@OPZIONE,@OLDPROVV,@OLDDATAPROVV,
				@OLDPROGPROVV,@NUMERR OUTPUT,@MSGERR OUTPUT
             

	IF @NUMERR <> '0000'
	BEGIN
                           SELECT @NUMERR = '9999'
		SELECT @MSGERR = @NUMERR + ' - ERRORE PROCEDURA INSERT_LSRPRO'
            		ROLLBACK TRANSACTION
                           RETURN 
	END
	ELSE
	BEGIN
	 	EXEC  INSERT_SER_LOTTO @RICEVITORIA,@DATAINS,@ORAINS,
					@DATADECOR,@DATAPROVV,@TIPOPROVV,
					@NUMPROVV,@FIRMA,@NOTE,@OGGI,
					@OPZIONE,@OLDPROVV,@OLDDATAPROVV,
					@OLDPROGPROVV, @OPZDIS,
					@NUMERR OUTPUT,@MSGERR OUTPUT
		IF @NUMERR <> '0000'
		BEGIN
			SELECT @NUMERR = '9999'
			SELECT @MSGERR = @NUMERR + ' - ERRORE PROCEDURA INSERT_SER_LOTTO'
			ROLLBACK TRANSACTION
			RETURN 
		END
		ELSE
		BEGIN
			--INIZIO MODIFICA 06/09/2001 - F-GIACOVAZZI
			--SE VIENE INSERITO UN PROVVEDIMENTO CON DATA DECORRENZA FUTURA
			--OCCORRE IMPOSTARE LA DATA INSERIMENTO LETTERA UGUALE A DATA DECORRENZA MENO 1 GIORNO

			IF @DATADECOR > CONVERT(CHAR,GETDATE(),112)
			BEGIN
				SELECT @DATAINSLET = CONVERT(CHAR,CONVERT(DATETIME,@DATADECOR)-1,112)
				SELECT @ORAINSLET = '00000000'

				INSERT INTO LSRLET VALUES
				(@RICEVITORIA,@DATAINSLET,@ORAINSLET,'01',@TIPOPROVV,@DATADECOR,'LSRPRO',
				@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')
			END
			ELSE
			BEGIN
				INSERT INTO LSRLET VALUES
				(@RICEVITORIA,@DATAINS,@ORAINS,'01',@TIPOPROVV,@DATADECOR,'LSRPRO',
				@DATAINS+@ORAINS,'00000000','',@FIRMA,'V')
			END
			--FINE MODIFICA 06/09/2001 - F-GIACOVAZZI

			IF @@ERROR <> 0
			BEGIN
				SELECT @NUMERR = '9999'
				SELECT @MSGERR = @NUMERR + ' - ERRORE PROCEDURA INSERT_SER_LOTTO'
				ROLLBACK TRANSACTION
				RETURN 
			END
		END
	END


	COMMIT TRANSACTION
	SELECT @NUMERR = '0000'
	SELECT @MSGERR = @NUMERR + ' - '  + ' ELABORAZIONE TERMINATA CORRETTAMENTE'

END
GO
