/****** Object:  StoredProcedure [dbo].[GEV_VARIAZIONE_CONTRATTI_ITVM]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[GEV_VARIAZIONE_CONTRATTI_ITVM] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS	CHAR(8),
@ORAINS		CHAR(8),
@TIPOACQ	CHAR(1),
@DATADOC	CHAR(8),
@DATALET	CHAR(8),
@DATACES	CHAR(8),
@PROTDOC	VARCHAR(25),
@COGNOME	CHAR(24),
@NOME		CHAR(20),
@NMATR		CHAR(2),
@FLGANAG	CHAR(1),
@FKINSTIT	VARCHAR(16),
@FKINSDOC	varCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17),
@MATRICOLA1	CHAR(30),
@MATRICOLA2	CHAR(30),
@MATRICOLA3	CHAR(30),
@MATRICOLA4	CHAR(30),
@MATRICOLA5	CHAR(30),
@MATRICOLA6	CHAR(30),
@MATRICOLA7	CHAR(30),
@MATRICOLA8	CHAR(30),
@MATRICOLA9	CHAR(30),
@MATRICOLA10	CHAR(30)
AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@DATAAPPO		CHAR(8),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSGEV	CHAR(8),
@FKORAINSGEV	CHAR(8),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20),
@FLGANAGOLD	CHAR(1),
@NMATRICOLE     int,
@MATRICOLA_ins  char(10),
@FKDATAINSDOC char(8),
@FKORAINSDOC char(8)


SELECT @RICEAPPO = ''


SELECT @FKDATAINSTIT = null
SELECT @FKORAINSTIT = null
select @NMATRICOLE = 1

SELECT @RICEAPPO = NULL
SELECT @FKDATAINSTIT = NULL
SELECT @FKORAINSTIT = NULL


IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
BEGIN
	SELECT @FKDATAINSGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSGEV = SUBSTRING(@FKINSTIT, 9, 8)
END
ELSE
BEGIN

	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)
END
SELECT @FKDATAINSDOC = SUBSTRING(@FKINSDOC, 1, 8)
SELECT @FKORAINSDOC = SUBSTRING(@FKINSDOC, 9, 8)


SELECT @MSGERR = NULL

SELECT @RICEAPPO = ''
SELECT @MSGERR = NULL

SELECT @COGNOMEOLD = ''
SELECT @NOMEOLD = NULL







SELECT @FLGANAGOLD = NULL

SELECT @FLGANAGOLD = LSRCON_ITVM_FLAG_ANAG
FROM LSRCON_ITVM
WHERE LSRCON_ITVM_KEY_ID_RICEV = @CODSGI
AND LSRCON_ITVM_KEY_DATA_INS = @FKDATAINSDOC
AND LSRCON_ITVM_KEY_ORA_INS = @FKORAINSDOC

IF @FLGANAGOLD = '0' AND @FLGANAG <> '0'
BEGIN

	SELECT @RICEAPPO = NULL

	SELECT @COGNOMEOLD = NULL
	SELECT @NOMEOLD = NULL
	
	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		SELECT @RICEAPPO = LSRCON_ITVM_KEY_ID_RICEV 
		FROM LSRCON_ITVM
		WHERE LSRCON_ITVM_KEY_ID_RICEV = @CODSGI
		AND LSRCON_ITVM_FK_DATA_INS_TIT_GEV = @FKDATAINSGEV
		AND LSRCON_ITVM_FK_ORA_INS_TIT_GEV = @FKORAINSGEV
	ELSE
		SELECT @RICEAPPO = LSRCON_ITVM_KEY_ID_RICEV 
		FROM LSRCON_ITVM
		WHERE LSRCON_ITVM_KEY_ID_RICEV = @CODSGI
		AND LSRCON_ITVM_FK_DATA_INS_TIT = @FKDATAINSTIT
		AND LSRCON_ITVM_FK_ORA_INS_TIT = @FKORAINSTIT


	IF @RICEAPPO IS NOT NULL
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO ASSOCIATO AL TITOLARE INDICATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END


IF @FLGANAGOLD = '0' AND @FLGANAG =  '0'
BEGIN
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSGEV = NULL
	SELECT @FKORAINSGEV = NULL

end

--print @FLGANAG
--print @FKDATAINSTIT
--print @FKORAINSTIT
--print @FKDATAINSTITGEV
--print @FKDATAINSTITgev

BEGIN TRANSACTION

	update LSRCON_ITVM 
	set LSRCON_ITVM_DATA_LETTERA=@DATALET,
	LSRCON_ITVM_NUM_MACCH=@NMATR,
	LSRCON_ITVM_NOTE=@NOTE,
	LSRCON_ITVM_FK_DATA_INS_TIT=@FKDATAINSTIT,
	LSRCON_ITVM_FK_ORA_INS_TIT=@FKORAINSTIT,
	LSRCON_ITVM_FK_DATA_INS_TIT_GEV=@FKDATAINSGEV,
	LSRCON_ITVM_FK_ORA_INS_TIT_GEV=@FKORAINSGEV,
	LSRCON_ITVM_DATA_CESSAZIONE=@DATACES,
	LSRCON_ITVM_NUM_PROT_DOC=@PROTDOC
	WHERE LSRCON_ITVM_KEY_ID_RICEV = @CODSGI
	AND LSRCON_ITVM_KEY_DATA_INS = @FKDATAINSDOC 
	AND LSRCON_ITVM_KEY_ORA_INS = @FKORAINSDOC

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
drop table ##matricole
CREATE TABLE ##matricole ( id INT, matricola char(30) ) 
insert into ##matricole  values ('1', @matricola1)
insert into ##matricole values ('2', @matricola2)
insert into ##matricole values ('3', @matricola3)
insert into ##matricole values ('4', @matricola4)
insert into ##matricole values ('5', @matricola5)
insert into ##matricole values ('6', @matricola6)
insert into ##matricole values ('7', @matricola7)
insert into ##matricole values ('8', @matricola8)
insert into ##matricole values ('9', @matricola9)
insert into ##matricole values ('10', @matricola10)

delete from lsrcon_itvm_matr
where lsrcon_itvm_matr_key_id_ricev=@codsgi
and Lsrcon_itvm_matr_key_data_ins= @FKDATAINSDOC 
and Lsrcon_itvm_matr_key_ORA_ins= @FKoraINSDOC 


while @nmatricole <= @nmatr
begin




select @MATRICOLA_INS=matricola  from ##matricole where id=@nmatricole
if @@rowcount>0 and @MATRICOLA_INS<>''
begin
insert into lsrcon_itvm_matr values (
@CODSGI, 
@FKDATAINSDOC, 
@FKorainsDOC,
@CODLTM,
@NMATRICOLE,
@MATRICOLA_INS,
@FIRMA
)
select @NMATRICOLE=@NMATRICOLE+1
end
else
begin
select @nmatricole=@nmatr +1
end
end
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
if exists (select * from dbo.sysobjects where id =
object_id(N'[dbo].[##matricole]') and OBJECTPROPERTY(id, N'IsUserTable')
= 1)
BEGIN
drop table ##matricole
END
GO
