/****** Object:  StoredProcedure [dbo].[GEV_ACQUISIZIONE_FIDEJUSSIONI]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   PROCEDURE [dbo].[GEV_ACQUISIZIONE_FIDEJUSSIONI] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@COGNOME		VARCHAR(24),
@NOME		VARCHAR(20),
@TIPOACQ		CHAR(1),
@DATADOC		CHAR(8),
@DATAINVIODOC	CHAR(8),
@PROTDOC		VARCHAR(25),
@IMPORTODOV	VARCHAR(9),
@IMPORTOPAG	VARCHAR(9),
@SOCASS		CHAR(2),
@ANNORIF		CHAR(4),
@DATAINIZIO		CHAR(8),
@DATAFINE		CHAR(8),
@FLGANAG		CHAR(1),
@FKINSTIT		VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)

AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@DATAAPPO		CHAR(8),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSTITGEV	CHAR(8),
@FKORAINSTITGEV	CHAR(8),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20),
@FLGANAGOLD	CHAR(1)

SELECT @RICEAPPO = NULL
SELECT @FKDATAINSTITGEV = null
SELECT @FKORAINSTITGEV = null
SELECT @FKDATAINSTIT = null
SELECT @FKORAINSTIT = null




IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN
	SELECT @FKDATAINSTITGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTITGEV = SUBSTRING(@FKINSTIT, 9, 8)

END
ELSE
BEGIN
	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)

END

IF LTRIM(RTRIM(@IMPORTODOV)) = '' OR @IMPORTODOV IS NULL
BEGIN
	SELECT @IMPORTODOV = '0'
END

IF LTRIM(RTRIM(@IMPORTOPAG)) = '' OR @IMPORTOPAG IS NULL
BEGIN
	SELECT @IMPORTOPAG = '0'
END

SELECT @IMPORTODOV = CONVERT(DEC(18,2), @IMPORTODOV)
SELECT @IMPORTOPAG = CONVERT(DEC(18,2), @IMPORTOPAG)
/* 	COMMENTO AGGIUNTO DA CDS: I CODICI SONO GIà TUTTI VALORIZZATI, QUINDI
	LE CHIAMATE SONO INUTILI

EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF LTRIM(RTRIM(@MSGERR)) <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

EXEC GEV_DECOD_RICEV @CODLTM, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF LTRIM(RTRIM(@MSGERR)) <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

*/
SELECT @COGNOMEOLD = NULL
SELECT @NOMEOLD = NULL

--FA 06/08/08
-- Controllo inserito per il problema acquisizione fidejussini con lo stesso titolare
-- ma denominazione diverse
IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN

	SELECT @COGNOMEOLD = LSRFID_GEV_COGNOME, @NOMEOLD = LSRFID_GEV_NOME
	FROM LSRFID_GEV
	WHERE LSRFID_GEV_KEY_ID_RICEV = @CODSGI
	AND LSRFID_GEV_COGNOME = @COGNOME
	AND LSRFID_GEV_NOME = @NOME
	AND LSRFID_GEV_ANNO_RIF = @ANNORIF
	AND lsrfid_GeV_fk_data_ins_tit_gev=@FKDATAINSTITGEV
	AND lsrfid_GeV_fk_ora_ins_tit_gev=@FKORAINSTITGEV
	

END
ELSE
BEGIN

	SELECT @COGNOMEOLD = LSRFID_GEV_COGNOME, @NOMEOLD = LSRFID_GEV_NOME
	FROM LSRFID_GEV
	WHERE LSRFID_GEV_KEY_ID_RICEV = @CODSGI
	AND LSRFID_GEV_COGNOME = @COGNOME
	AND LSRFID_GEV_NOME = @NOME
	AND LSRFID_GEV_ANNO_RIF = @ANNORIF
	AND lsrfid_GeV_fk_data_ins_tit=@FKDATAINSTIT
	AND lsrfid_GeV_fk_ora_ins_tit=@FKORAINSTIT
	

END


IF @COGNOMEOLD IS NOT NULL
BEGIN
	SELECT @MSGERR = 'ESISTE GIA UN DOCUMENTO PER LA RICEVITORIA ' + @CODLTM + ' - CONTRAENTE: ' + @COGNOME + ' ' + @NOME
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- IMPOSTO IL TIPO DI ASSOCIAZIONE TRA DOCUMENTO E CONTRAENTE (SOLO PER ACQUISIZIONE DA FILE)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF @TIPOACQ = 'F'
BEGIN

	SELECT @MSGERR = NULL
	SELECT @FLGANAG = NULL
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSTITGEV = null
	SELECT @FKORAINSTITGEV = null

	EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT
	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO_CONI @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTITGEV OUTPUT, @FKORAINSTITGEV OUTPUT
	ELSE	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTIT OUTPUT, @FKORAINSTIT OUTPUT

	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

SELECT @RICEAPPO = NULL
SELECT @FLGANAGOLD = NULL
SELECT @MSGERR = NULL

SELECT @FLGANAGOLD = LSRFID_GEV_FLAG_ANAG
FROM LSRFID_GEV
WHERE LSRFID_GEV_KEY_ID_RICEV = @CODSGI
AND LSRFID_GEV_FLAG_ANAG = @FLGANAG
AND LSRFID_GEV_ANNO_RIF = @ANNORIF


IF @FLGANAGOLD IS NOT NULL
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO NON ASSOCIATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG >= '2' 
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END	
ELSE
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @FKDATAINSTIT = NULL
		SELECT @FKORAINSTIT = NULL
		SELECT @FKDATAINSTITGEV = null
		SELECT @FKORAINSTITGEV = null
		SELECT @MSGERR = '0 - DOCUMENTO NON ASSOCIATO AD ALCUN TITOLARE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG >= '2' 
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
	END

END

BEGIN TRANSACTION

INSERT INTO LSRFID_GEV VALUES
(@CODSGI, @DATAINS, @ORAINS, @CODLTM, @TIPOACQ, @DATADOC, @DATAINVIODOC, @PROTDOC, @SOCASS,
 @COGNOME, @NOME, @IMPORTODOV, @IMPORTOPAG, @ANNORIF, @DATAINIZIO, @DATAFINE, @NOTE, @FLGANAG, @FKDATAINSTIT, @FKORAINSTIT, 
 @FKDATAINSTITGEV, @FKORAINSTITGEV, @FIRMA)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	COMMIT TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION

END
GO
