/****** Object:  StoredProcedure [dbo].[GEV_ACQUISIZIONE_CONTRATTI_ITVM]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE          PROCEDURE [dbo].[GEV_ACQUISIZIONE_CONTRATTI_ITVM] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS	CHAR(8),
@ORAINS		CHAR(8),
@TIPOACQ	CHAR(1),
@DATADOC	CHAR(8),
@DATALET	CHAR(8),
@DATAINVIODOC	CHAR(8),
@PROTDOC	VARCHAR(25),
@COGNOME	CHAR(24),
@NOME		CHAR(20),
@NMATR		CHAR(2),
@FLGANAG	CHAR(1),
@DATACES	CHAR(8),
@FKINSTIT	VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17),
@MATRICOLA1	CHAR(30),
@MATRICOLA2	CHAR(30),
@MATRICOLA3	CHAR(30),
@MATRICOLA4	CHAR(30),
@MATRICOLA5	CHAR(30),
@MATRICOLA6	CHAR(30),
@MATRICOLA7	CHAR(30),
@MATRICOLA8	CHAR(30),
@MATRICOLA9	CHAR(30),
@MATRICOLA10	CHAR(30)
AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@DATAAPPO		CHAR(8),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSTITGEV	CHAR(8),
@FKORAINSTITGEV	CHAR(8),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20),
@FLGANAGOLD	CHAR(1),
@NMATRICOLE     int,
@MATRICOLA_ins  char(30)

SELECT @RICEAPPO = ''
SELECT @FKDATAINSTITGEV = null
SELECT @FKORAINSTITGEV = null
SELECT @FKDATAINSTIT = null
SELECT @FKORAINSTIT = null
select @NMATRICOLE = 1

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN
	SELECT @FKDATAINSTITGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTITGEV = SUBSTRING(@FKINSTIT, 9, 8)

END
ELSE
BEGIN
	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)

END


SELECT @MSGERR = NULL

/* 	COMMENTO AGGIUNTO DA CDS: I CODICI SONO GIà TUTTI VALORIZZATI, QUINDI
	LE CHIAMATE SONO INUTILI

EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

SELECT @MSGERR = NULL

EXEC GEV_DECOD_RICEV @CODLTM, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END
*/
-------------------------------------------------------------
-- CONTROLLO SE GIA' ESISTE UN QUESTIONARIO PER QUEL CONTRAENTE
-------------------------------------------------------------

SELECT @RICEAPPO = ''
SELECT @MSGERR = NULL

SELECT @COGNOMEOLD = ''
SELECT @NOMEOLD = NULL



IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN
	SELECT @COGNOMEOLD = LSRCON_ITVM_COGNOME, @NOMEOLD = LSRCON_ITVM_NOME
	FROM LSRCON_ITVM
	WHERE LSRCON_ITVM_KEY_ID_RICEV = @CODSGI
		AND lsrcon_ITVM_fk_data_ins_tit_gev = @FKDATAINSTITGEV
		AND lsrcon_ITVM_fk_ora_ins_tit_GEV = @FKORAINSTITGEV

	IF @@ROWCOUNT > 0
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO INTESTATO A: ' + @COGNOME + ' ' + @NOME
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END
ELSE
BEGIN
	SELECT @COGNOMEOLD = LSRCON_ITVM_COGNOME, @NOMEOLD = LSRCON_ITVM_NOME
	FROM LSRCON_ITVM
	WHERE LSRCON_ITVM_KEY_ID_RICEV = @CODSGI
		AND lsrcon_ITVM_fk_data_ins_tit = @FKDATAINSTIT
		AND lsrcon_ITVM_fk_ora_ins_tit = @FKORAINSTIT

	IF @@ROWCOUNT > 0
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO INTESTATO A: ' + @COGNOME + ' ' + @NOME
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END



--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- IMPOSTO IL TIPO DI ASSOCIAZIONE TRA DOCUMENTO E CONTRAENTE (SOLO PER ACQUISIZIONE DA FILE)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF @TIPOACQ = 'F'
BEGIN
	SELECT @MSGERR = NULL
	SELECT @FLGANAG = NULL
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSTITGEV = null
	SELECT @FKORAINSTITGEV = null

	EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT
	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO_CONI @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTITGEV OUTPUT, @FKORAINSTITGEV OUTPUT
	
	ELSE	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTIT OUTPUT, @FKORAINSTIT OUTPUT

	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

SELECT @RICEAPPO = NULL
SELECT @FLGANAGOLD = NULL
SELECT @MSGERR = NULL

SELECT @FLGANAGOLD = LSRCON_ITVM_FLAG_ANAG
FROM LSRCON_ITVM
WHERE LSRCON_ITVM_KEY_ID_RICEV = @CODSGI
AND LSRCON_ITVM_FLAG_ANAG = @FLGANAG

IF @FLGANAGOLD IS NOT NULL
BEGIN

	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO NON ASSOCIATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '1'
	BEGIN		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '2' 
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END	
ELSE
BEGIN


	IF @FLGANAG = '0'
	BEGIN

		SELECT @FKDATAINSTIT = NULL
		SELECT @FKORAINSTIT = NULL
		SELECT @FKDATAINSTITGEV = null
		SELECT @FKORAINSTITGEV = null
		SELECT @MSGERR = '0 - DOCUMENTO NON ASSOCIATO AD ALCUN TITOLARE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG >= '2' 
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
	END

END

--print @FLGANAG
--print @FKDATAINSTIT
--print @FKORAINSTIT
--print @FKDATAINSTITGEV
--print @FKDATAINSTITgev

BEGIN TRANSACTION

INSERT INTO LSRCON_ITVM VALUES
(@CODSGI, 
@DATAINS, 
@ORAINS, 
@CODLTM, 
@CODAMM, 
@TIPOACQ, 
@DATADOC, 
@DATAINVIODOC, 
@PROTDOC,
@cognome,
@nome,
@DATALET, 
@NMATR,
@DATACES,
@NOTE, 
@FLGANAG, 
@FKDATAINSTIT, 
@FKORAINSTIT, 
@FKDATAINSTITGEV, 
@FKORAINSTITGEV, 
@FIRMA)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
drop table ##matricole
CREATE TABLE ##matricole ( id INT, matricola char(30) ) 
insert into ##matricole  values ('1', @matricola1)
insert into ##matricole values ('2', @matricola2)
insert into ##matricole values ('3', @matricola3)
insert into ##matricole values ('4', @matricola4)
insert into ##matricole values ('5', @matricola5)
insert into ##matricole values ('6', @matricola6)
insert into ##matricole values ('7', @matricola7)
insert into ##matricole values ('8', @matricola8)
insert into ##matricole values ('9', @matricola9)
insert into ##matricole values ('10', @matricola10)

while @nmatricole <= @nmatr
begin

select @MATRICOLA_INS=matricola  from ##matricole where id=@nmatricole
if @@rowcount>0 and @MATRICOLA_INS<>''
begin
insert into lsrcon_itvm_matr values (
@CODSGI, 
@DATAINS, 
@ORAINS,
@CODLTM,
@NMATRICOLE,
@MATRICOLA_INS,
@FIRMA
)
select @NMATRICOLE=@NMATRICOLE+1
end
else
begin
select @nmatricole=@nmatr +1
end
end
IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
if exists (select * from dbo.sysobjects where id =
object_id(N'[dbo].[##matricole]') and OBJECTPROPERTY(id, N'IsUserTable')
= 1)
BEGIN
drop table ##matricole
END
GO
