/****** Object:  StoredProcedure [dbo].[GEV_ACQUISIZIONE_CONTRATTI]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE      PROCEDURE [dbo].[GEV_ACQUISIZIONE_CONTRATTI] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS	CHAR(8),
@ORAINS		CHAR(8),
@TIPOACQ	CHAR(1),
@DATADOC	CHAR(8),
@DATAINVIODOC	CHAR(8),
@PROTDOC	VARCHAR(25),
@COGNOME	VARCHAR(24),
@NOME		VARCHAR(20),
@ASSOCIAZIONE	CHAR(1),

@COMRES		CHAR(24),
@PROVRES	CHAR(2),
@CAPRES		CHAR(5),
@INDRES		CHAR(40),

@COMSPE		CHAR(24),
@PROVSPE		CHAR(2),
@CAPSPE		CHAR(5),
@INDSPE		CHAR(40),
@NOMESPE		CHAR(44),

@NUMTEL		CHAR(12),
@COMFIS		CHAR(24),
@PROVFIS	CHAR(2),
@CAPFIS		CHAR(5),
@INDFIS		CHAR(40),
@CODFIS		CHAR(16),
@PRTIVA		CHAR(11),
@NUMPACCHI		VARCHAR(10),
@NUMKITUNO		VARCHAR(10),
@NUMKITDUE		VARCHAR(10),

@CODMERCEOLOGICO	CHAR(2),
@EMAIL		VARCHAR(100),

@FLAGNUOVOCON	CHAR(1),
@DATANUOVOCON	CHAR(8),

@FLGANAG	CHAR(1),
@FKINSTIT	VARCHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)

AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@DATAAPPO		CHAR(8),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSTITGEV	CHAR(8),
@FKORAINSTITGEV	CHAR(8),
@COGNOMEOLD	VARCHAR(24),
@NOMEOLD		VARCHAR(20),
@FLGANAGOLD	CHAR(1)


SELECT @RICEAPPO = ''
SELECT @FKDATAINSTITGEV = null
SELECT @FKORAINSTITGEV = null
SELECT @FKDATAINSTIT = null
SELECT @FKORAINSTIT = null

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN
	SELECT @FKDATAINSTITGEV = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTITGEV = SUBSTRING(@FKINSTIT, 9, 8)

END
ELSE
BEGIN
	SELECT @FKDATAINSTIT = SUBSTRING(@FKINSTIT, 1, 8)
	SELECT @FKORAINSTIT = SUBSTRING(@FKINSTIT, 9, 8)

END


SELECT @MSGERR = NULL

/* 	COMMENTO AGGIUNTO DA CDS: I CODICI SONO GIà TUTTI VALORIZZATI, QUINDI
	LE CHIAMATE SONO INUTILI

EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

SELECT @MSGERR = NULL

EXEC GEV_DECOD_RICEV @CODLTM, @CODSGI OUTPUT

SET @MSGERR = @@ERROR

IF @MSGERR <> 0
BEGIN
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END
*/
-------------------------------------------------------------
-- CONTROLLO SE GIA' ESISTE UN QUESTIONARIO PER QUEL CONTRAENTE
-------------------------------------------------------------

SELECT @RICEAPPO = ''
SELECT @MSGERR = NULL

SELECT @COGNOMEOLD = ''
SELECT @NOMEOLD = NULL

--- MODIFICA DEL 13/09/2006 ------
-- COMMENTATO CODICE SOTTO E SOSTITUITO
/*
SELECT @COGNOMEOLD = LSRCON_GEV_COGNOME, @NOMEOLD = LSRCON_GEV_NOME
FROM LSRCON_GEV
WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
AND LSRCON_GEV_COGNOME = @COGNOME
AND LSRCON_GEV_NOME = @NOME
 

IF @@ROWCOUNT > 0
BEGIN
	SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO INTESTATO A: ' + @COGNOME + ' ' + @NOME
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

*/

IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1
BEGIN
	SELECT @COGNOMEOLD = LSRCON_GEV_COGNOME, @NOMEOLD = LSRCON_GEV_NOME
	FROM LSRCON_GEV
	WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
		AND lsrcon_GeV_fk_data_ins_tit_gev = @FKDATAINSTITGEV
		AND lsrcon_GeV_fk_ora_ins_tit_GEV = @FKORAINSTITGEV

	IF @@ROWCOUNT > 0
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO INTESTATO A: ' + @COGNOME + ' ' + @NOME
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END
ELSE
BEGIN
	SELECT @COGNOMEOLD = LSRCON_GEV_COGNOME, @NOMEOLD = LSRCON_GEV_NOME
	FROM LSRCON_GEV
	WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
		AND lsrcon_GeV_fk_data_ins_tit = @FKDATAINSTIT
		AND lsrcon_GeV_fk_ora_ins_tit = @FKORAINSTIT

	IF @@ROWCOUNT > 0
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN CONTRATTO INTESTATO A: ' + @COGNOME + ' ' + @NOME
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END

END



--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- IMPOSTO IL TIPO DI ASSOCIAZIONE TRA DOCUMENTO E CONTRAENTE (SOLO PER ACQUISIZIONE DA FILE)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF @TIPOACQ = 'F'
BEGIN
	SELECT @MSGERR = NULL
	SELECT @FLGANAG = NULL
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	SELECT @FKDATAINSTITGEV = null
	SELECT @FKORAINSTITGEV = null

	EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT
	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END



	IF ISNUMERIC(LTRIM(RTRIM(@CODLTM) )) = 1	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO_CONI @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTITGEV OUTPUT, @FKORAINSTITGEV OUTPUT
	ELSE	
		EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTIT OUTPUT, @FKORAINSTIT OUTPUT

	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

SELECT @RICEAPPO = NULL
SELECT @FLGANAGOLD = NULL
SELECT @MSGERR = NULL

SELECT @FLGANAGOLD = LSRCON_GEV_FLAG_ANAG
FROM LSRCON_GEV
WHERE LSRCON_GEV_KEY_ID_RICEV = @CODSGI
AND LSRCON_GEV_FLAG_ANAG = @FLGANAG

IF @FLGANAGOLD IS NOT NULL
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO NON ASSOCIATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '1'
	BEGIN

		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '2' 
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'

		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END	
ELSE
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @FKDATAINSTIT = NULL
		SELECT @FKORAINSTIT = NULL
		SELECT @FKDATAINSTITGEV = null
		SELECT @FKORAINSTITGEV = null
		SELECT @MSGERR = '0 - DOCUMENTO NON ASSOCIATO AD ALCUN TITOLARE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG >= '2' 
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
	END

END

BEGIN TRANSACTION
/*
INSERT INTO LSRORD_GEV VALUES(
			@CODSGI, 
			@DATAINS, 
			@ORAINS, 
			@CODLTM, 
			@TIPOACQ, 
			@COGNOME, 
			@NOME, 
			'1',
			@NUMKITUNO,
			@NOTE, 
			@FLGANAG, 
			@FKDATAINSTIT, 
			@FKORAINSTIT, 
			@FKDATAINSTITGEV, 
			@FKORAINSTITGEV, 
			@FIRMA
			)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

INSERT INTO LSRORD_GEV VALUES(
			@CODSGI, 
			@DATAINS, 
			@ORAINS, 
			@CODLTM, 
			@TIPOACQ, 
			@COGNOME, 
			@NOME, 
			'2',
			@NUMKITDUE,
			@NOTE, 
			@FLGANAG, 
			@FKDATAINSTIT, 
			@FKORAINSTIT, 
			@FKDATAINSTITGEV, 
			@FKORAINSTITGEV, 
			@FIRMA
			)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END

*/

INSERT INTO LSRCON_GEV VALUES
(@CODSGI, 
@DATAINS, 
@ORAINS, 
@CODLTM, 
@CODAMM, 
@TIPOACQ, 
@DATADOC, 
@DATAINVIODOC, 
@PROTDOC, 
@ASSOCIAZIONE, 
@COGNOME, 
@NOME, 

@COMRES,
@PROVRES,
@CAPRES,
@INDRES,

@COMSPE,
@PROVSPE,
@CAPSPE,
@INDSPE,
@NOMESPE,

@NUMTEL,
@CODFIS,
@PRTIVA,
@COMFIS,
@PROVFIS,
@CAPFIS,
@INDFIS,
@NUMPACCHI,

@NOTE, 
@CODMERCEOLOGICO,

@EMAIL,

@FLAGNUOVOCON,
@DATANUOVOCON,

@FLGANAG, 
@FKDATAINSTIT, 
@FKORAINSTIT, 
@FKDATAINSTITGEV, 
@FKORAINSTITGEV, 
@FIRMA)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = '9 - ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
GO
