/****** Object:  StoredProcedure [dbo].[GEV_ACQUISIZIONE_APS]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GEV_ACQUISIZIONE_APS] 

@CODLTM		VARCHAR(7),
@CODAMM		VARCHAR(7),
@CODSGI		VARCHAR(7),
@DATAINS		CHAR(8),
@ORAINS		CHAR(8),
@TIPOACQ		CHAR(1),
@DATADOC		CHAR(8),
@DATAINVIODOC	CHAR(8),
@PROTDOC		VARCHAR(25),
@COGNOME		VARCHAR(24),
@NOME		VARCHAR(20),
@MODULO		CHAR(1),
@ASSOCIAZIONE	CHAR(1),
@FLGANAG		CHAR(1),
@FKINSTIT		CHAR(16),
@NOTE		VARCHAR(100),
@FIRMA		VARCHAR(17)

AS 

DECLARE

@RETE		CHAR(1),
@RESULT		INT,
@MSGERR		VARCHAR(200),
@RICEAPPO		VARCHAR(7),
@FKDATAINSTIT	CHAR(8),
@FKORAINSTIT	CHAR(8),
@FKDATAINSTITGEV	CHAR(8),
@FKORAINSTITGEV	CHAR(8),
@FLGANAGOLD	CHAR(1)


SELECT @RICEAPPO = NULL
SELECT @FKDATAINSTITGEV = '00000000'
SELECT @FKORAINSTITGEV = '00000000'


EXEC GEV_ESISTE_RICEVITORIA @CODLTM OUTPUT, @CODAMM OUTPUT, @CODSGI OUTPUT

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = @@ERROR
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

EXEC GEV_DECOD_RICEV @CODLTM, @CODSGI OUTPUT

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = @@ERROR
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END


--------------------------------------------------------------------------------------------------------------------------------
-- CONTROLLO SE GIA' ESISTE UNA A.P.S. PER QUEL CONTRAENTE
--------------------------------------------------------------------------------------------------------------------------------

SELECT @RICEAPPO = NULL

SELECT @RICEAPPO = LSRAPS_GEV_COGNOME
FROM LSRAPS_GEV
WHERE LSRAPS_GEV_KEY_ID_RICEV = @CODSGI
AND LSRAPS_GEV_COGNOME = @COGNOME
AND LSRAPS_GEV_NOME = @NOME

IF @RICEAPPO IS NOT NULL
BEGIN
	SELECT @MSGERR = 'ESISTE GIA UN DOCUMENTO - CONTRAENTE: ' + @COGNOME + ' ' + @NOME
	RAISERROR (@MSGERR, 16, 1)
	RETURN
END

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- IMPOSTO IL TIPO DI ASSOCIAZIONE TRA DOCUMENTO E CONTRAENTE (SOLO PER ACQUISIZIONE DA FILE)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF @TIPOACQ = 'F'
BEGIN

	SELECT @MSGERR = NULL
	SELECT @FLGANAG = NULL
	SELECT @FKDATAINSTIT = NULL
	SELECT @FKORAINSTIT = NULL
	
	EXEC GEV_ASSOCIA_TITOLARE_DOCUMENTO @CODLTM, @COGNOME, @NOME, @FLGANAG OUTPUT, @FKDATAINSTIT OUTPUT, @FKORAINSTIT OUTPUT

	SET @MSGERR = @@ERROR
	
	IF @MSGERR <> 0
	BEGIN
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END

SELECT @RICEAPPO = NULL
SELECT @FLGANAGOLD = NULL
SELECT @MSGERR = NULL

SELECT @FLGANAGOLD = LSRAPS_GEV_FLAG_ANAG
FROM LSRAPS_GEV
WHERE LSRAPS_GEV_KEY_ID_RICEV = @CODSGI
AND LSRAPS_GEV_FLAG_ANAG = @FLGANAG

IF @FLGANAGOLD IS NOT NULL
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO NON ASSOCIATO'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
	ELSE IF @FLGANAG = '2' 
	BEGIN
		SELECT @MSGERR = '9 - ESISTE GIA UN DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
		RETURN
	END
END	
ELSE
BEGIN
	IF @FLGANAG = '0'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO NON ASSOCIATO AD ALCUN TITOLARE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '1'
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AL TITOLARE ATTUALE'
		RAISERROR (@MSGERR, 16, 1)
	END
	ELSE IF @FLGANAG = '2' 
	BEGIN
		SELECT @MSGERR = '0 - DOCUMENTO ASSOCIATO AD UN TITOLARE PRECEDENTE'
		RAISERROR (@MSGERR, 16, 1)
	END

END

BEGIN TRANSACTION

INSERT INTO LSRAPS_GEV VALUES
(@CODSGI, @DATAINS, @ORAINS, @CODLTM, @TIPOACQ, @DATADOC, @DATAINVIODOC, @PROTDOC, 
@MODULO, @ASSOCIAZIONE, @COGNOME, @NOME, @NOTE, @FLGANAG, @FKDATAINSTIT, @FKORAINSTIT, 
@FKDATAINSTITGEV, @FKORAINSTITGEV, @FIRMA)

IF @@ERROR <> 0
BEGIN
	SELECT @MSGERR = 'ERRORE IN ACQUISIZIONE DOCUMENTO'
	RAISERROR (@MSGERR, 16, 1)
	COMMIT TRANSACTION
	RETURN
END
ELSE
BEGIN
	COMMIT TRANSACTION
END
GO
