/****** Object:  StoredProcedure [dbo].[ANA_MOVIMENTA_LOTTO]    Script Date: 11/17/2025 15:18:32 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ANA_MOVIMENTA_LOTTO] 

	@CODLTM	 	CHAR(6),
	@DATADECOR		CHAR(8),
	@DATAPROVV		CHAR(8),
	@TIPOPROVV		CHAR(1),
	@NUMPROVV		VARCHAR(14),
	@CAUSALE		CHAR(40),
	@EMANATO		CHAR(25),
	@FIRMA		CHAR(17),
	@NOTE		VARCHAR(255),
	@NEWOLD		CHAR(3),
	@OPZDIS		CHAR(5),
	@FDATAPROVV	CHAR(8),
	@FTIPOPROVV		CHAR(1),
	@FNUMPROVV		VARCHAR(14),
	@FDATADECOR	CHAR(8)

AS

DECLARE

@CHKLTM		VARCHAR(7),
@CHKSTATO		CHAR(1),
@ORAINS		CHAR(8),
@DATAINS		CHAR(8),
@ASSOCIAZIONE	CHAR(1),
@FDATAINS		CHAR(8),
@FORAINS		CHAR(8),
@DATAINSLET		CHAR(8),
@ORAINSLET		CHAR(8),
@FDATAORAINS	CHAR(16),
@NEWFLAG		CHAR(1),
@CODSER		CHAR(2),
@TIPOMOV		CHAR(1),
@NUMERR		VARCHAR,
@MSGERR		VARCHAR,
@MSG			VARCHAR(255)


SELECT @CODSER = '01'

SELECT @DATAINS = CONVERT(CHAR, GETDATE(),112)

SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(), 121),12,2) +
	SUBSTRING(CONVERT(CHAR,GETDATE(), 121),15,2) +
	SUBSTRING(CONVERT(CHAR,GETDATE(), 121),18,2) +
	SUBSTRING(CONVERT(CHAR,GETDATE(), 121),21,2)


BEGIN TRANSACTION

EXEC ANA_MOVIMENTA_LSRPRO

	@CODLTM,
	@DATAINS,
	@ORAINS,
	@TIPOPROVV,
	@DATAPROVV,
	@NUMPROVV,
	@CAUSALE,
	@FIRMA,
	@EMANATO,
	@DATADECOR,
	@NEWOLD,
	@FDATAINS OUTPUT,
	@FORAINS OUTPUT,
	@FTIPOPROVV OUTPUT,
	@FDATAPROVV OUTPUT,
	@FNUMPROVV OUTPUT,
	@FDATADECOR OUTPUT

IF @@ERROR <> 0
BEGIN
	SELECT @MSG = 'ERRORE IN ESECUZIONE S.P. ANA_MOVIMENTA_LSRPRO - RICEVITORIA ' + @CODLTM
	RAISERROR(@MSG, 16, 1)
	ROLLBACK TRANSACTION
	RETURN
END


SELECT @FDATAORAINS = NULL
SELECT @FDATAORAINS = @FDATAINS + @FORAINS


SELECT @ASSOCIAZIONE= LSRSER_LOTTO_ASSOCIAZIONE
FROM LSRSER_LOTTO
WHERE LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
AND LSRSER_LOTTO_DATA_DECOR =
(
	SELECT MAX(LSRSER_LOTTO_DATA_DECOR) 
	FROM LSRSER_LOTTO
	WHERE LSRSER_LOTTO_DATA_DECOR <= @DATAINS
	AND LSRSER_LOTTO_KEY_ID_RICEV = @CODLTM
)

IF @NEWOLD = 'OLD'
BEGIN
	--INSERISCO IL NUOVO PROVVEDIMENTO E MANTENGO VALIDO QUELLO FUTURO
	
	INSERT INTO LSRSER_LOTTO VALUES
	(@CODLTM,@DATAINS,@ORAINS,@DATADECOR,
	@TIPOPROVV,@DATAPROVV,@NUMPROVV,
	@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','N')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSG = @@ERROR
		RAISERROR(@MSG, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END
END

IF @NEWOLD = 'NEW'
BEGIN
	--CANCELLO DA LSRLET IL RECORD RELATIVO ALLA MOVIMENTAZIONE FUTURA DEL LOTTO
	DELETE FROM LSRLET WHERE
	LSRLET_KEY_ID_RICEV = @CODLTM AND
	LSRLET_COD_SERVIZIO = @CODSER AND
	LSRLET_DECOR_DAL > @DATADECOR

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSG = 'ERRORE IN CANCELLAZIONE RECORD SU LSRLET'
		RAISERROR(@MSG, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END


	--INSERISCO IL NUOVO PROVVEDIMENTO E ANNULLO LOGICAMENTE QUELLO FUTURO

	SELECT @NOTE = 'ANNULLATO DAL PROVVEDIMENTO N° ' + LTRIM(RTRIM(@NUMPROVV)) + ' DEL ' + @DATAPROVV

	SELECT @NEWFLAG = NULL
	SELECT @NEWFLAG = 'N'


	EXEC ANA_ANNULLA_MOVIMENTAZIONE_LOTTO 
		@CODLTM, 
		@FTIPOPROVV, 
		@FDATAPROVV, 
		@FNUMPROVV, 
		@FDATADECOR,
		@DATAINS, 
		@ORAINS, 
		@NEWFLAG, 
		@FIRMA, 
		@NOTE

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSG = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_LOTTO - RICEVITORIA ' + @CODLTM
		RAISERROR(@MSG, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END

	EXEC ANA_ANNULLA_MOVIMENTAZIONE_LTM
		@CODLTM, 
		@FDATAORAINS,
		@FTIPOPROVV, 
		@FDATAPROVV, 
		@FNUMPROVV, 
		@FDATADECOR,
		@NEWFLAG,
		@FIRMA, 
		@NOTE

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSG = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_LTM - RICEVITORIA ' + @CODLTM
		RAISERROR(@MSG, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END

	EXEC ANA_ANNULLA_MOVIMENTAZIONE_LIS
		@CODLTM, 
		@FDATAORAINS,
		@FTIPOPROVV, 
		@FDATAPROVV, 
		@FNUMPROVV, 
		@FDATADECOR,
		@NEWFLAG,
		@FIRMA, 
		@NOTE

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSG = 'ERRORE IN ESECUZIONE S.P. ANA_ANNULLA_MOVIMENTAZIONE_LIS - RICEVITORIA ' + @CODLTM
		RAISERROR(@MSG, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END

	SELECT @NOTE = NULL

	INSERT INTO LSRSER_LOTTO VALUES
	(@CODLTM,@DATAINS,@ORAINS,@DATADECOR,
	@TIPOPROVV,@DATAPROVV,@NUMPROVV,
	@ASSOCIAZIONE,@FIRMA,@NOTE,'00000000','Y')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSG = 'ERRORE IN INSERIMENTO RECORD SU LSRSER_LOTTO - RICEVITORIA ' + @CODLTM
		RAISERROR(@MSG, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END

	--SCRIVO UN RECORD SU LSRLET RELATIVO AL GIOCO LOTTO
	IF @DATADECOR > CONVERT(CHAR,GETDATE(),112)
	BEGIN
		SELECT @DATAINSLET = CONVERT(CHAR,CONVERT(DATETIME,@DATADECOR)-1,112)
		SELECT @ORAINSLET = '00000000'

		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINSLET, @ORAINSLET, @CODSER, @TIPOPROVV, @DATADECOR, 'LSRPRO',
		@DATAINS+@ORAINS, '00000000', '', @FIRMA, 'V')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSG = 'ERRORE IN INSERIMENTO RECORD SU LSRLET - RICEVITORIA ' + @CODLTM
			RAISERROR(@MSG, 16, 1)
			ROLLBACK TRANSACTION
			RETURN
		END
	END
	ELSE
	BEGIN
		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINS, @ORAINS,  @CODSER, @TIPOPROVV, @DATADECOR, 'LSRPRO',
		@DATAINS+@ORAINS, '00000000', '', @FIRMA, 'V')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSG = 'ERRORE IN INSERIMENTO RECORD SU LSRLET - RICEVITORIA ' + @CODLTM
			RAISERROR(@MSG, 16, 1)
			ROLLBACK TRANSACTION
			RETURN
		END
	END


	IF @OPZDIS = 'TUTTI'
	BEGIN
		IF @TIPOPROVV = 'R' OR @TIPOPROVV ='S' OR @TIPOPROVV = 'M'
		BEGIN
			SELECT @NOTE = 'IL PROVVEDIMENTO DISABILITA TUTTI I SERVIZI LOTTOMATICA - LIS' --F101,TRIS,BOLLO,GEV

			SELECT @ORAINS = SUBSTRING(CONVERT(CHAR,GETDATE(), 121),12,2) +
					SUBSTRING(CONVERT(CHAR,GETDATE(), 121),15,2) +
					SUBSTRING(CONVERT(CHAR,GETDATE(), 121),18,2) +
					SUBSTRING(CONVERT(CHAR,GETDATE(), 121),21,2)

			
			EXEC ANA_MOVIMENTA_LTM_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@DATADECOR,
			@DATAPROVV,
			@TIPOPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

			IF @@ERROR <> 0
			BEGIN
				SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_MOVIMENTA_LTM_DA_LOTTO - RICEVITORIA ' + @CODLTM
				RAISERROR (@MSGERR, 16, 1)
				ROLLBACK TRANSACTION
				RETURN
			END


			EXEC ANA_MOVIMENTA_LIS_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@DATADECOR,
			@DATAPROVV,
			@TIPOPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

			IF @@ERROR <> 0
			BEGIN
				SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_MOVIMENTA_LIS_DA_LOTTO - RICEVITORIA ' + @CODLTM
				RAISERROR (@MSGERR, 16, 1)
				ROLLBACK TRANSACTION
				RETURN
			END

		END
	END
END
IF @NEWOLD IS NULL OR LTRIM(RTRIM(@NEWOLD)) = ''
BEGIN
	--INSERISCO IL NUOVO PROVVEDIMENTO
	INSERT INTO LSRSER_LOTTO VALUES
	(@CODLTM, @DATAINS, @ORAINS, @DATADECOR,
	@TIPOPROVV, @DATAPROVV, @NUMPROVV,
	@ASSOCIAZIONE, @FIRMA, @NOTE,'00000000','Y')

	IF @@ERROR <> 0 
	BEGIN
		SELECT @MSG = 'ERRORE IN INSERIMENTO RECORD SU LSRSER_LOTTO - RICEVITORIA ' + @CODLTM
		RAISERROR(@MSG, 16, 1)
		ROLLBACK TRANSACTION
		RETURN
	END

	--SCRIVO UN RECORD SU LSRLET RELATIVO AL GIOCO LOTTO
	IF @DATADECOR > CONVERT(CHAR,GETDATE(),112)
	BEGIN
		SELECT @DATAINSLET = CONVERT(CHAR,CONVERT(DATETIME,@DATADECOR)-1,112)
		SELECT @ORAINSLET = '00000000'

		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINSLET, @ORAINSLET, @CODSER, @TIPOPROVV, @DATADECOR, 'LSRPRO',
		@DATAINS+@ORAINS, '00000000', '', @FIRMA, 'V')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSG = 'ERRORE IN INSERIMENTO RECORD SU LSRLET - RICEVITORIA ' + @CODLTM
			RAISERROR(@MSG, 16, 1)
			ROLLBACK TRANSACTION
			RETURN
		END
	END
	ELSE
	BEGIN
		INSERT INTO LSRLET VALUES
		(@CODLTM, @DATAINS, @ORAINS,  @CODSER, @TIPOPROVV, @DATADECOR, 'LSRPRO',
		@DATAINS+@ORAINS, '00000000', '', @FIRMA, 'V')

		IF @@ERROR <> 0 
		BEGIN
			SELECT @MSG = 'ERRORE IN INSERIMENTO RECORD SU LSRLET - RICEVITORIA ' + @CODLTM
			RAISERROR(@MSG, 16, 1)
			ROLLBACK TRANSACTION
			RETURN
		END
	END


	IF @OPZDIS = 'TUTTI'
	BEGIN
		IF @TIPOPROVV = 'R' OR @TIPOPROVV ='S' OR @TIPOPROVV = 'M'
		BEGIN
			SELECT @NOTE = 'IL PROVVEDIMENTO DISABILITA TUTTI I SERVIZI LOTTOMATICA - LIS' --F101,TRIS,BOLLO,GEV

			EXEC ANA_MOVIMENTA_LTM_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@DATADECOR,
			@DATAPROVV,
			@TIPOPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

			IF @@ERROR <> 0
			BEGIN
				SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_MOVIMENTA_LTM_DA_LOTTO - RICEVITORIA ' + @CODLTM
				RAISERROR (@MSGERR, 16, 1)
				ROLLBACK TRANSACTION
				RETURN
			END

			EXEC ANA_MOVIMENTA_LIS_DA_LOTTO
			@CODLTM,
			@DATAINS,
			@ORAINS,
			@DATADECOR,
			@DATAPROVV,
			@TIPOPROVV,
			@NUMPROVV,
			@FIRMA,
			@NOTE

			IF @@ERROR <> 0
			BEGIN
				SELECT @MSGERR = 'ERRORE IN ESECUZIONE S.P. ANA_MOVIMENTA_LIS_DA_LOTTO - RICEVITORIA ' + @CODLTM
				RAISERROR (@MSGERR, 16, 1)
				ROLLBACK TRANSACTION
				RETURN
			END

	
		END
	END

END


COMMIT TRANSACTION

RETURN
GO
