/****** Object:  Database [Anaconda]    Script Date: 11/17/2025 15:18:25 ******/
CREATE DATABASE [Anaconda] ON  PRIMARY 
( NAME = N'AnacondaSystem', FILENAME = N'S:\MicrosoftSqlServer\MSSQL$A\Data\Anaconda.MDF' , SIZE = 69696KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
 FILEGROUP [DATA]  DEFAULT 
( NAME = N'AnacondaData1', FILENAME = N'S:\MicrosoftSqlServer\MSSQL$A\Data\Anaconda_1.NDF' , SIZE = 3840000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [INDEX] 
( NAME = N'AnacondaIndex1', FILENAME = N'S:\MicrosoftSqlServer\MSSQL$A\Data\Anaconda_2.NDF' , SIZE = 563200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'AnacondaLog', FILENAME = N'S:\MicrosoftSqlServer\MSSQL$A\TLogs\Anaconda_3.LDF' , SIZE = 1875456KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [Anaconda] SET COMPATIBILITY_LEVEL = 80
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Anaconda].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [Anaconda] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Anaconda] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Anaconda] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Anaconda] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Anaconda] SET ARITHABORT OFF
GO
ALTER DATABASE [Anaconda] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Anaconda] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Anaconda] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Anaconda] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Anaconda] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Anaconda] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Anaconda] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Anaconda] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Anaconda] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Anaconda] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Anaconda] SET  ENABLE_BROKER
GO
ALTER DATABASE [Anaconda] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Anaconda] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Anaconda] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Anaconda] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Anaconda] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Anaconda] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Anaconda] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Anaconda] SET  READ_WRITE
GO
ALTER DATABASE [Anaconda] SET RECOVERY FULL
GO
ALTER DATABASE [Anaconda] SET  MULTI_USER
GO
ALTER DATABASE [Anaconda] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Anaconda] SET DB_CHAINING OFF
GO
USE [Anaconda]
GO
