/****** Object:  Database [Attivazioni]    Script Date: 11/17/2025 15:21:50 ******/
CREATE DATABASE [Attivazioni] ON  PRIMARY 
( NAME = N'AttivazioniSystem', FILENAME = N'N:\MicrosoftSQLServer\Attivazioni.MDF' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5120KB ), 
 FILEGROUP [DATA]  DEFAULT 
( NAME = N'AttivazioniData1', FILENAME = N'N:\MicrosoftSQLServer\Attivazioni_1.NDF' , SIZE = 2048000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ), 
 FILEGROUP [INDEX] 
( NAME = N'AttivazioniIndex1', FILENAME = N'N:\MicrosoftSQLServer\Attivazioni_2.NDF' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'AttivazioniLog', FILENAME = N'N:\MicrosoftSQLServer\Attivazioni_3.LDF' , SIZE = 14137792KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [Attivazioni] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Attivazioni].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [Attivazioni] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Attivazioni] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Attivazioni] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Attivazioni] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Attivazioni] SET ARITHABORT OFF
GO
ALTER DATABASE [Attivazioni] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Attivazioni] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Attivazioni] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Attivazioni] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Attivazioni] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Attivazioni] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Attivazioni] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Attivazioni] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Attivazioni] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Attivazioni] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Attivazioni] SET  ENABLE_BROKER
GO
ALTER DATABASE [Attivazioni] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Attivazioni] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Attivazioni] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Attivazioni] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Attivazioni] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Attivazioni] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Attivazioni] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Attivazioni] SET  READ_WRITE
GO
ALTER DATABASE [Attivazioni] SET RECOVERY FULL
GO
ALTER DATABASE [Attivazioni] SET  MULTI_USER
GO
ALTER DATABASE [Attivazioni] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Attivazioni] SET DB_CHAINING OFF
GO
USE [Attivazioni]
GO
