/****** Object:  View [dbo].[VIEW_RMF_LOG]    Script Date: 11/17/2025 15:18:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VIEW_RMF_LOG]
AS
SELECT     TOP 100 PERCENT dbo.RMF_MODULE_PARAMETER_LOG.PARAMETER_VALUE, dbo.RMF_MODULE_MESSAGE_LOG.MODULE_LOG_NO, 
                      dbo.RMF_MODULE_MESSAGE_LOG.MODULE_EVENT_NO, dbo.RMF_MODULE_MESSAGE_LOG.MODULE_MESSAGE_NO, 
                      dbo.RMF_MODULE_MESSAGE_LOG.EXCEPTION_NO, dbo.RMF_MODULE_MESSAGE_TEXT_LOG.MODULE_MESSAGE_TEXT, 
                      dbo.RMF_EXCEPTIONS.EXCEPTION_NAME, dbo.RMF_EXCEPTIONS.EXCEPTION_TEXT
FROM         dbo.RMF_MODULE_PARAMETER_LOG INNER JOIN
                      dbo.RMF_EXCEPTIONS INNER JOIN
                      dbo.RMF_MODULE_MESSAGE_LOG INNER JOIN
                      dbo.RMF_MODULE_MESSAGE_TEXT_LOG ON 
                      dbo.RMF_MODULE_MESSAGE_LOG.MODULE_MESSAGE_NO = dbo.RMF_MODULE_MESSAGE_TEXT_LOG.MODULE_MESSAGE_NO AND 
                      dbo.RMF_MODULE_MESSAGE_LOG.MODULE_EVENT_NO = dbo.RMF_MODULE_MESSAGE_TEXT_LOG.MODULE_EVENT_NO AND 
                      dbo.RMF_MODULE_MESSAGE_LOG.MODULE_LOG_NO = dbo.RMF_MODULE_MESSAGE_TEXT_LOG.MODULE_LOG_NO ON 
                      dbo.RMF_EXCEPTIONS.EXCEPTION_NO = dbo.RMF_MODULE_MESSAGE_LOG.EXCEPTION_NO ON 
                      dbo.RMF_MODULE_PARAMETER_LOG.MODULE_LOG_NO = dbo.RMF_MODULE_MESSAGE_TEXT_LOG.MODULE_LOG_NO
ORDER BY dbo.RMF_MODULE_MESSAGE_LOG.MODULE_LOG_NO, dbo.RMF_MODULE_MESSAGE_LOG.MODULE_EVENT_NO, 
                      dbo.RMF_MODULE_MESSAGE_LOG.MODULE_MESSAGE_NO
GO
