/****** Object:  View [dbo].[QRY_LOTTO_AWP_NOEtichetta]    Script Date: 11/17/2025 15:16:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[QRY_LOTTO_AWP_NOEtichetta] AS 
SELECT DENOMINAZIONE_GESTORE, CODICE_GESTORE,
CODE_ID_AWP, CODE_ID_AWP_PROVV, MODELLO_AWP, SECONDO_STATO_AWP,
DENOMINAZIONE_ESERCIZIO, VESE_ESERCIZIO,TIPOLOGIA_LOCALE_ESERCIZIO,ULTIMA_MOVIMENTAZIONE_AWP
FROM LOTTOPARCOAWP
WHERE 
CODE_ID_AWP_PROVV  NOT IN (
SELECT DISTINCT IdentificativoProv
FROM 
RicambiGiacenza r INNER JOIN BizDedicati d ON r.fkluogo = d.IdDedicato
INNER JOIN LOTTOPARCOAWP la ON la.CODE_ID_AWP_PROVV = d.IdentificativoProv
WHERE TipoLuogo = 'A3'
AND not IdentificativoProv IS NULL  
) 
AND Denominazione_proprietario = 'BACK OFFICE COMMERCIALE'
AND TIPOLOGIA_AWP = 'AWP 2'
GO
