/****** Object:  View [dbo].[ApparecchiIncassi11]    Script Date: 11/17/2025 15:16:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ApparecchiIncassi11] AS SELECT 'NSL' AS Categoria, 'New Slot' AS Tipo, incassi.codicelocale AS IdLocale,2 AS TipoOggetto,'NSL' AS TipoOggettoDesc,incassi.CodiceOggetto,incassi.prop AS Proprieta,incassi.agente, incassi.Associato, dedicati.matricola,dedicati.nome as Modello, dedicati.identificativo,dedicati.nullaosta, 1 AS TM ,NULL AS idmove, incassi.idincasso,incassi.data, tipoincasso, incassi.incasso,incassonetto, ricevuta, contatore1, contatore2, contatore3, contatore4, bollettaincasso, trasferito, totaleentrate, totaleuscite, perc, tasse, aams, rete, idmagazzino, 0 AS Ordinamento, 0 AS OrdinamentoCategoria,societa.ragionesociale,tipomerce AS TipoScarto,locali.Nome as Locale, Locali.IdZona, ParZone.NomeZona, locali.CodEsercente AS CodiceEsercente, CASE WHEN appoincassi.IdConcessionario is null THEN dedicati.idconcessionario ELSE appoincassi.IdConcessionario END as idconcess
 FROM ((((incassi INNER JOIN dedicati  ON  dedicati.iddedicato=incassi.codiceoggetto)  INNER JOIN societa  ON societa.idsocieta=incassi.prop)  INNER JOIN locali ON locali.idlocale=incassi.codicelocale) LEFT JOIN ParZone ON Locali.IdZona = ParZone.IdZona) LEFT JOIN appoincassi ON appoincassi.idincasso = incassi.idincasso 
 Where incassi.partipologiamonopoli = 1 And incassi.TipoOggetto = 2 And dedicati.IsVLT = 0 
 UNION SELECT 'VLT' AS Categoria, 'Vlt' AS Tipo, incassi.codicelocale AS IdLocale,2 AS TipoOggetto,'VLT' AS TipoOggettoDesc,incassi.CodiceOggetto,incassi.prop AS Proprieta,incassi.agente, incassi.Associato, dedicati.matricola,dedicati.nome as Modello, dedicati.identificativo,dedicati.nullaosta, 1 AS TM ,NULL AS idmove, incassi.idincasso,incassi.data, tipoincasso, incassi.incasso,incassonetto, ricevuta, contatore1, contatore2, contatore3, contatore4, bollettaincasso, trasferito, totaleentrate, totaleuscite, perc, tasse, aams, rete, idmagazzino, 0 AS Ordinamento, 0 AS OrdinamentoCategoria,societa.ragionesociale,tipomerce AS TipoScarto,locali.Nome as Locale, Locali.IdZona, ParZone.NomeZona, locali.CodEsercente AS CodiceEsercente, CASE WHEN appoincassi.IdConcessionario is null THEN dedicati.idconcessionario ELSE appoincassi.IdConcessionario END as idconcess
 FROM ((((incassi INNER JOIN dedicati  ON  dedicati.iddedicato=incassi.codiceoggetto)  INNER JOIN societa  ON societa.idsocieta=incassi.prop)  INNER JOIN locali ON locali.idlocale=incassi.codicelocale) LEFT JOIN ParZone ON Locali.IdZona = ParZone.IdZona) LEFT JOIN appoincassi ON appoincassi.idincasso = incassi.idincasso 
 Where incassi.partipologiamonopoli = 1 And incassi.TipoOggetto = 2  And dedicati.IsVLT <> 0 
 UNION SELECT 'C7A' AS Categoria, 'Gioco' AS Tipo, incassi.codicelocale AS IdLocale,2 AS TipoOggetto,'GIO' AS TipoOggettoDesc,incassi.CodiceOggetto,incassi.prop AS Proprieta,incassi.agente, incassi.Associato, dedicati.matricola,dedicati.nome as Modello, dedicati.identificativo,dedicati.nullaosta, 2 AS TM, NULL AS idmove, incassi.idincasso, incassi.data, tipoincasso, incassi.incasso,incassonetto, ricevuta, contatore1, contatore2, contatore3, contatore4, bollettaincasso, trasferito, totaleentrate, totaleuscite, perc, tasse, aams, rete, idmagazzino, 0 AS Ordinamento, 1 AS OrdinamentoCategoria,societa.ragionesociale,tipomerce AS TipoScarto,locali.Nome as Locale, Locali.IdZona, ParZone.NomeZona, locali.CodEsercente AS CodiceEsercente, NULL as IdConcess
 FROM (((incassi INNER JOIN dedicati  ON  dedicati.iddedicato=incassi.codiceoggetto)  INNER JOIN societa  ON societa.idsocieta=incassi.prop)  INNER JOIN locali ON locali.idlocale=incassi.codicelocale) LEFT JOIN ParZone ON Locali.IdZona = ParZone.IdZona 
 WHERE incassi.partipologiamonopoli=2  AND incassi.tipooggetto=2
 UNION SELECT 'C7C' AS Categoria, 'Gioco' AS Tipo, incassi.codicelocale AS IdLocale,2 AS TipoOggetto,'GIO' AS TipoOggettoDesc,incassi.CodiceOggetto,incassi.prop AS Proprieta,incassi.agente, incassi.Associato, dedicati.matricola,dedicati.nome as Modello, dedicati.identificativo,dedicati.nullaosta, 4 AS TM, NULL AS idmove, incassi.idincasso, incassi.data, tipoincasso, incassi.incasso,incassonetto, ricevuta, contatore1, contatore2, contatore3, contatore4, bollettaincasso, trasferito, totaleentrate, totaleuscite, perc, tasse, aams, rete, idmagazzino, 0 AS Ordinamento, 2 AS OrdinamentoCategoria,societa.ragionesociale,tipomerce AS TipoScarto,locali.Nome as Locale   , Locali.IdZona, ParZone.NomeZona, locali.CodEsercente AS CodiceEsercente, NULL as IdConcess
 FROM (((incassi INNER JOIN dedicati  ON  dedicati.iddedicato=incassi.codiceoggetto)  INNER JOIN societa  ON societa.idsocieta=incassi.prop)  INNER JOIN locali ON locali.idlocale=incassi.codicelocale) LEFT JOIN ParZone ON Locali.IdZona = ParZone.IdZona
 Where incassi.partipologiamonopoli = 4 And incassi.TipoOggetto = 2
 UNION SELECT 'MEC' AS Categoria, 'Gioco' AS Tipo, incassi.codicelocale AS IdLocale,2 AS TipoOggetto,'GIO' AS TipoOggettoDesc,incassi.CodiceOggetto,incassi.prop AS Proprieta,incassi.agente, incassi.Associato, dedicati.matricola,dedicati.nome as Modello, dedicati.identificativo,dedicati.nullaosta, NULL AS TM, NULL AS idmove, incassi.idincasso, incassi.data, tipoincasso, incassi.incasso,incassonetto, ricevuta, contatore1, contatore2, contatore3, contatore4, bollettaincasso, trasferito, totaleentrate, totaleuscite, perc, tasse, aams, rete, idmagazzino, 0 AS Ordinamento, 3 AS OrdinamentoCategoria,societa.ragionesociale,tipomerce AS TipoScarto,locali.Nome as Locale, Locali.IdZona, ParZone.NomeZona, locali.CodEsercente AS CodiceEsercente, NULL as IdConcess
 FROM (((incassi INNER JOIN dedicati  ON  dedicati.iddedicato=incassi.codiceoggetto)  INNER JOIN societa  ON societa.idsocieta=incassi.prop)  INNER JOIN locali ON locali.idlocale=incassi.codicelocale) LEFT JOIN ParZone ON Locali.IdZona = ParZone.IdZona
 Where (incassi.partipologiamonopoli > 4 Or incassi.partipologiamonopoli Is Null) And incassi.TipoOggetto = 2
 UNION SELECT 'SCH' AS Categoria, 'Scheda' AS Tipo, incassi.codicelocale AS IdLocale,1 AS TipoOggetto,'SCH' AS TipoOggettoDesc, incassi.CodiceOggetto,incassi.prop AS Proprieta,incassi.agente, incassi.Associato, schede.matricola,schede.nome as Modello, '' AS identificativo,'' AS nullaosta, NULL AS TM, NULL AS idmove, incassi.idincasso, incassi.data, tipoincasso, incassi.incasso,incassonetto, ricevuta, contatore1, contatore2, contatore3, contatore4, bollettaincasso, trasferito, totaleentrate, totaleuscite, perc, tasse, aams, rete, idmagazzino, 3 AS Ordinamento, 0 AS OrdinamentoCategoria,societa.ragionesociale,tipomerce AS TipoScarto,locali.Nome as Locale, Locali.IdZona, ParZone.NomeZona, locali.CodEsercente AS CodiceEsercente, NULL as IdConcess
 FROM (((incassi INNER JOIN schede ON schede.idscheda=incassi.codiceoggetto) INNER JOIN societa ON societa.idsocieta=incassi.prop)  INNER JOIN locali ON locali.idlocale=incassi.codicelocale) LEFT JOIN ParZone ON Locali.IdZona = ParZone.IdZona
 Where incassi.TipoOggetto = 1
 UNION SELECT 'DIS' AS Categoria, 'Distributore' AS Tipo, incassi.codicelocale AS IdLocale,15 AS TipoOggetto,'DIS' AS TipoOggettoDesc, incassi.CodiceOggetto,incassi.prop AS Proprieta,incassi.agente, incassi.Associato, distribut.matricola,distribut.nome as Modello, '' AS identificativo,'' AS nullaosta, NULL AS TM, NULL AS idmove, incassi.idincasso, incassi.data, tipoincasso, incassi.incasso,incassonetto, ricevuta, contatore1, contatore2, contatore3, contatore4, bollettaincasso, trasferito, totaleentrate, totaleuscite, perc, tasse, aams, rete, idmagazzino, 4 AS Ordinamento, 0 AS OrdinamentoCategoria,societa.ragionesociale,tipomerce AS TipoScarto,locali.Nome as Locale, Locali.IdZona, ParZone.NomeZona, locali.CodEsercente AS CodiceEsercente, NULL as IdConcess
 FROM (((incassi INNER JOIN distribut ON distribut.iddistributore=incassi.codiceoggetto) INNER JOIN societa ON societa.idsocieta=incassi.prop) INNER JOIN locali ON locali.idlocale=incassi.codicelocale) LEFT JOIN ParZone ON Locali.IdZona = ParZone.IdZona
 Where incassi.TipoOggetto = 15
 UNION SELECT 'SCO' AS Categoria, 'Sconto' AS Tipo, incassi.codicelocale AS IdLocale,20 AS TipoOggetto,'SCO' AS TipoOggettoDesc, incassi.CodiceOggetto,incassi.prop AS Proprieta,incassi.agente, incassi.Associato, 'Sconto' as matricola,'Sconto' as Modello, 'Sconto' AS identificativo,'Sconto' AS nullaosta, partipologiamonopoli AS TM, NULL AS idmove, incassi.idincasso, incassi.data, tipoincasso, incassi.incasso,incassonetto, ricevuta, contatore1, contatore2, contatore3, contatore4, bollettaincasso, trasferito, totaleentrate, totaleuscite, perc, tasse, aams, rete, '' as idmagazzino, 4 AS Ordinamento, 0 AS OrdinamentoCategoria,societa.ragionesociale,tipomerce AS TipoScarto,locali.Nome as Locale, Locali.IdZona, ParZone.NomeZona, locali.CodEsercente AS CodiceEsercente, IdConcSconto as IdConcess
 FROM (((incassi INNER JOIN societa ON societa.idsocieta=incassi.prop) INNER JOIN Locali ON locali.idlocale=incassi.codicelocale) LEFT JOIN ParZone ON Locali.IdZona = ParZone.IdZona) LEFT JOIN AppoIncassi ON AppoIncassi.IdIncasso = Incassi.Idincasso
 WHERE incassi.tipooggetto=20
GO
