/****** Object:  Table [dbo].[KLA]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KLA](
	[RUOTA] [nvarchar](255) NULL,
	[HOST] [nvarchar](255) NULL,
	[PROV_RUO] [nvarchar](255) NULL,
	[MODULO] [nvarchar](255) NULL,
	[NUM_RICEV] [float] NULL,
	[PROV_RICEV] [nvarchar](255) NULL,
	[ID_AMMINISTRATIVO] [nvarchar](255) NULL,
	[ID_LOTTOMATICA] [nvarchar](255) NULL,
	[PROGR_TERMINALE] [nvarchar](255) NULL,
	[NTER] [nvarchar](255) NULL,
	[TITOLARE] [nvarchar](255) NULL,
	[COMUNE_RICEV] [nvarchar](255) NULL,
	[PROV] [nvarchar](255) NULL,
	[CAP] [nvarchar](255) NULL,
	[INDIRIZZO] [nvarchar](255) NULL,
	[STATO] [nvarchar](255) NULL,
	[TEL_RICEVITORIA] [nvarchar](255) NULL,
	[TEL_CASA] [nvarchar](255) NULL,
	[CODICE MAGAZZINO] [nvarchar](255) NULL,
	[MATRICOLA] [nvarchar](255) NULL,
	[FEP_IP] [nvarchar](255) NULL,
	[CODOR_IP] [nvarchar](255) NULL,
	[SDLC_IP] [nvarchar](255) NULL,
	[TD_IP] [nvarchar](255) NULL,
	[TIPO_T_IP] [nvarchar](255) NULL,
	[N_VERDE_IP] [nvarchar](255) NULL,
	[N_VERDE2_IP] [nvarchar](255) NULL,
	[N_VERDE_ISDN B] [nvarchar](255) NULL,
	[IP_TERM] [nvarchar](255) NULL,
	[IP_HOST] [nvarchar](255) NULL,
	[IP_FTP] [nvarchar](255) NULL,
	[FEP_SDLC] [nvarchar](255) NULL,
	[CODOR_SDLC] [nvarchar](255) NULL,
	[SDLC_SDLC] [nvarchar](255) NULL,
	[TD_SDLC] [nvarchar](255) NULL,
	[TIPO_T_SDLC] [nvarchar](255) NULL,
	[N_VERDE_SDLC] [nvarchar](255) NULL,
	[N_VERDE2_SDLC] [nvarchar](255) NULL,
	[NUAT] [nvarchar](255) NULL,
	[PORTA_T] [nvarchar](255) NULL,
	[TGU_T] [nvarchar](255) NULL,
	[NODO_T] [nvarchar](255) NULL,
	[TDH] [nvarchar](255) NULL,
	[NUAH] [nvarchar](255) NULL,
	[PORTA_H] [nvarchar](255) NULL,
	[TGU_H] [nvarchar](255) NULL,
	[NODO_H] [nvarchar](255) NULL,
	[TD] [nvarchar](255) NULL
) ON [DATA]
GO
