/****** Object:  Table [dbo].[DOMANDE]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DOMANDE](
	[ANZ_GG] [float] NULL,
	[ISPETT] [nvarchar](15) NULL,
	[PROV] [nvarchar](2) NULL,
	[RUOTA] [nvarchar](2) NULL,
	[ISTAT] [float] NULL,
	[COMUNE] [nvarchar](25) NOT NULL,
	[NUM_TABAC] [smallint] NOT NULL,
	[TITOLARE] [nvarchar](40) NULL,
	[INDIRIZZO] [nvarchar](40) NULL,
	[CLASSE] [nvarchar](2) NULL,
	[ISTA_COMU] [nvarchar](3) NULL,
	[ISTA_PROV] [nvarchar](3) NULL,
	[POSIZ] [float] NULL,
	[ISTA_REG] [nvarchar](2) NULL,
	[COGNOME] [nvarchar](20) NULL,
	[NOME] [nvarchar](20) NULL,
	[CAP] [nvarchar](5) NULL,
	[TEL_RIC] [nvarchar](12) NULL,
	[TEL_CASA] [nvarchar](12) NULL,
	[CF] [nvarchar](16) NULL,
	[FLAG_RIC] [smallint] NULL,
	[ELENCO] [smallint] NULL,
	[SIGLA_ISP] [nvarchar](2) NULL,
	[NUM_RICEV] [smallint] NULL,
	[PROGR_RIC] [nvarchar](4) NULL,
	[ASSOCIAZ] [smallint] NULL,
	[PIANO] [smallint] NULL,
	[TELECOM] [smallint] NULL,
	[ADESIONE] [nvarchar](2) NULL,
	[TWIN] [smallint] NULL,
	[FLAG_REV] [smallint] NULL,
	[DATA_REV] [datetime] NULL,
	[SPROVV] [smallint] NULL,
	[CONTRATTI] [smallint] NULL,
	[DATAREV] [float] NULL,
	[PERIODO] [nvarchar](20) NULL,
	[DATA_RIAP] [float] NULL,
	[FLAG_PROVV] [smallint] NULL,
	[DATA_COM] [float] NULL,
	[DATA_DED] [float] NULL,
	[DATA_STA] [float] NULL,
	[DATA_ADD] [float] NULL,
	[DATA_OFF_LINE] [float] NULL,
	[DATA_GIOC] [float] NULL,
	[DATA_PROV] [float] NULL,
	[FLAG_ATT] [smallint] NULL,
	[FLAG_GIOC] [smallint] NULL,
	[DATARV] [float] NULL,
	[MODULO] [nvarchar](1) NULL,
	[LINEA_DISP] [nvarchar](1) NULL,
	[AQ2] [nvarchar](50) NULL,
	[COS] [smallint] NULL,
	[COS_PROBLEM] [int] NULL,
	[COS_TIPO_TELEFONO] [int] NULL,
	[COS_CHIAMATA] [datetime] NULL,
	[COS_INVIO_TELECOM] [datetime] NULL,
	[ORDINE GENERALE TELECOM] [datetime] NULL,
	[SDLC] [int] NULL,
	[IP] [int] NULL,
	[MAEL] [datetime] NULL,
	[MAEL SENZA RILASCIO] [datetime] NULL,
	[M350] [smallint] NULL,
	[RILASCIO TELECOM] [datetime] NULL,
	[IP TEST] [int] NULL,
	[ID_LOTTO] [nvarchar](6) NULL,
	[ID_AMM] [nvarchar](6) NULL,
	[MAGAZZINO] [smallint] NULL,
 CONSTRAINT [PK_DOMANDE] PRIMARY KEY CLUSTERED 
(
	[COMUNE] ASC,
	[NUM_TABAC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
