/****** Object:  Table [dbo].[contratti]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[contratti](
	[td] [varchar](13) NOT NULL,
	[lotto_telecom] [varchar](5) NULL,
 CONSTRAINT [PK_contratti] PRIMARY KEY CLUSTERED 
(
	[td] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
