/****** Object:  Table [dbo].[FLAG_CEZ]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FLAG_CEZ](
	[flag_cez] [char](2) NOT NULL,
	[desc_flag_cez] [char](50) NOT NULL,
 CONSTRAINT [PK_FLAG_CEZ] PRIMARY KEY CLUSTERED 
(
	[flag_cez] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
