/****** Object:  Table [dbo].[FEP]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FEP](
	[DESC_SITO] [varchar](20) NOT NULL,
	[PROGR_SITO] [smallint] NOT NULL,
	[FEP] [char](4) NOT NULL,
	[COD_REG] [char](2) NULL,
	[SETT] [varchar](5) NULL,
	[RUOTA] [varchar](20) NULL,
	[PROV_RUO] [char](2) NULL,
	[MODRIF] [char](1) NOT NULL,
	[TIPO_M] [char](1) NOT NULL,
 CONSTRAINT [PK_FEP] PRIMARY KEY CLUSTERED 
(
	[FEP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
