/****** Object:  Table [dbo].[COLLEGAMENTI_TERMINALI]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COLLEGAMENTI_TERMINALI](
	[NTER] [char](7) NOT NULL,
	[CODOR] [char](5) NOT NULL,
	[SDLC] [char](2) NOT NULL,
	[NUM_RICEV] [smallint] NOT NULL,
	[PROV_RICEV] [char](2) NOT NULL,
	[STAT] [char](1) NULL,
	[TD] [varchar](13) NULL,
	[RET2] [varchar](2) NOT NULL,
	[TIPO_T] [varchar](4) NOT NULL,
	[NUAT] [varchar](15) NULL,
	[PORTA_T] [varchar](15) NULL,
	[TGU_T] [varchar](13) NULL,
	[NODO_T] [varchar](15) NULL,
	[N_VERDE] [smallint] NOT NULL,
	[ID_AMMINISTRATIVO] [char](6) NOT NULL,
	[ID_LOTTOMATICA] [char](6) NOT NULL,
	[PROGR_TERMINALE] [char](1) NOT NULL,
	[lotto] [char](5) NULL,
	[data_ordine] [datetime] NULL,
	[lotto_telecom] [varchar](5) NOT NULL,
	[DEFAULT_GATEWAY] [char](15) NULL,
	[SUBNET_MASK] [char](15) NULL,
	[IP_FTP] [char](15) NULL,
	[VISTA] [char](1) NULL,
	[TD_ADSL] [char](20) NULL,
	[MOD_ROUTER] [char](30) NULL,
	[INFO_NODO] [char](30) NULL,
	[IP_RETE] [char](15) NULL,
	[IP_BROADCAST] [char](15) NULL,
	[NOTE] [varchar](50) NULL,
 CONSTRAINT [PK_COLLEGAMENTI_TERMINALI] PRIMARY KEY NONCLUSTERED 
(
	[NTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
CREATE CLUSTERED INDEX [IX_COLLEGAMENTI_TERMINALI] ON [dbo].[COLLEGAMENTI_TERMINALI] 
(
	[NTER] ASC,
	[ID_LOTTOMATICA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
GO
CREATE NONCLUSTERED INDEX [IX_collegamenti_terminali_2] ON [dbo].[COLLEGAMENTI_TERMINALI] 
(
	[NTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_collegamenti_terminali_3] ON [dbo].[COLLEGAMENTI_TERMINALI] 
(
	[CODOR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_collegamenti_terminali_4] ON [dbo].[COLLEGAMENTI_TERMINALI] 
(
	[ID_LOTTOMATICA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
