/****** Object:  Table [dbo].[CODICI_TIPO_APPAR]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CODICI_TIPO_APPAR](
	[cod_tipo_appar] [char](2) NOT NULL,
	[desc_tipo_appar] [char](50) NOT NULL,
	[tipologia] [char](2) NULL,
 CONSTRAINT [PK_CODICI_TIPO_APPAR] PRIMARY KEY CLUSTERED 
(
	[cod_tipo_appar] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
