/****** Object:  Table [dbo].[CENSIMENTO_STAMPANTI]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CENSIMENTO_STAMPANTI](
	[COD_LOTTO] [char](6) NULL,
	[COD_AMM] [char](6) NULL,
	[POSTAZIONE] [char](2) NULL,
	[TIPO_STAMPANTE] [char](8) NULL,
	[MATRICOLA] [char](15) NULL,
	[DATA] [char](8) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
