/****** Object:  Table [dbo].[ATTIVITA_IN_PROBLEMATICHE]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATTIVITA_IN_PROBLEMATICHE](
	[Cod_attivita_A] [char](3) NOT NULL,
	[Cod_attivita_P] [char](3) NOT NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
