/****** Object:  Table [dbo].[ATTIVITA]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATTIVITA](
	[ID_ATTIVITA] [char](3) NOT NULL,
	[DESC_ATTIVITA] [varchar](50) NOT NULL,
	[FLAG_GESTIONE] [char](1) NULL,
 CONSTRAINT [PK_ATTIVITA] PRIMARY KEY CLUSTERED 
(
	[ID_ATTIVITA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
