/****** Object:  Table [dbo].[NOTE]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTE](
	[PROV] [nvarchar](2) NULL,
	[NUM_RICEV] [int] NULL,
	[RUOTA] [nvarchar](15) NULL,
	[PROGR_RIC] [nvarchar](4) NULL,
	[DATA_NOTA] [smalldatetime] NULL,
	[UTENTE] [nvarchar](50) NOT NULL,
	[NOTE] [ntext] NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_NOTE] PRIMARY KEY NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
) ON [DATA] TEXTIMAGE_ON [DATA]
GO
CREATE CLUSTERED INDEX [ix_note] ON [dbo].[NOTE] 
(
	[RUOTA] ASC,
	[PROGR_RIC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
GO
CREATE NONCLUSTERED INDEX [ix_note_2] ON [dbo].[NOTE] 
(
	[RUOTA] ASC,
	[PROGR_RIC] ASC,
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
