/****** Object:  Table [dbo].[RIEPILOGO_NUMERI_VERDI]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RIEPILOGO_NUMERI_VERDI](
	[NUMERO_VERDE] [varchar](50) NULL,
	[DESCRIZIONE] [varchar](50) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
