/****** Object:  Table [dbo].[PROGR_MANCATA_ATT]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROGR_MANCATA_ATT](
	[ID_COMPETENZA] [char](1) NOT NULL,
	[ID_RUOTA] [char](2) NOT NULL,
	[PROGRESSIVO] [smallint] NOT NULL,
 CONSTRAINT [PK_PROGR_MANCATA_ATT] PRIMARY KEY CLUSTERED 
(
	[ID_COMPETENZA] ASC,
	[ID_RUOTA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
