/****** Object:  Table [dbo].[PIANO_APPARECCHIATURA]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PIANO_APPARECCHIATURA](
	[ID_PIANO] [char](10) NOT NULL,
	[TIPO_APPAR] [char](1) NOT NULL,
	[DESC_APPAR] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PIANO_APPARECCHIATURA] PRIMARY KEY CLUSTERED 
(
	[ID_PIANO] ASC,
	[TIPO_APPAR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
