/****** Object:  Table [dbo].[PIANI_MENU]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PIANI_MENU](
	[ID_MENU] [int] NOT NULL,
	[MENU_DESCRIZIONE] [char](50) NOT NULL,
	[MENU_ASP] [char](50) NOT NULL,
 CONSTRAINT [PK_PIANI_MENU] PRIMARY KEY CLUSTERED 
(
	[ID_MENU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
