/****** Object:  Table [dbo].[TEMPORANEA]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TEMPORANEA](
	[ricevitoria] [varchar](6) NOT NULL,
	[id_piano] [char](10) NOT NULL,
 CONSTRAINT [PK_TEMPORANEA] PRIMARY KEY CLUSTERED 
(
	[ricevitoria] ASC,
	[id_piano] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
