/****** Object:  Table [dbo].[TELECOM_UP_MAX]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TELECOM_UP_MAX](
	[COD_LOTTO] [varchar](6) NOT NULL,
	[COD_AMM] [varchar](6) NOT NULL,
	[POSTAZIONE] [char](2) NOT NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
