/****** Object:  Table [dbo].[SITI_FEP]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SITI_FEP](
	[DESC_SITO] [varchar](20) NOT NULL,
	[PROGR_SITO] [smallint] NOT NULL,
	[LOCALITA] [varchar](50) NOT NULL,
	[PROV] [char](2) NOT NULL,
	[INDIRIZZO] [varchar](50) NULL,
	[RESPONSABILE] [varchar](50) NULL,
	[TELEFONO] [varchar](25) NULL,
	[NOTE] [varchar](50) NULL,
 CONSTRAINT [PK_SITI_FEP] PRIMARY KEY CLUSTERED 
(
	[DESC_SITO] ASC,
	[PROGR_SITO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
