/****** Object:  Table [dbo].[SETTORI]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SETTORI](
	[COMUNE] [char](50) NOT NULL,
	[PROVINCIA] [char](2) NOT NULL,
	[SETTORE] [varchar](3) NOT NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
