/****** Object:  Table [dbo].[USER_CEZ_1]    Script Date: 11/17/2025 15:21:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER_CEZ_1](
	[user_id] [char](10) NOT NULL,
	[pwd] [char](15) NOT NULL,
	[cez] [char](2) NULL,
	[livello] [char](1) NULL,
 CONSTRAINT [PK_USER_CEZ_1] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
