/****** Object:  Table [dbo].[CODICI_AVANZAMENTO]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CODICI_AVANZAMENTO](
	[COD_AVANZAMENTO] [char](5) NOT NULL,
	[DES_AVANZAMENTO] [varchar](50) NOT NULL,
	[flag_verbale] [char](1) NULL,
	[cod_interv] [char](1) NULL,
	[cod_attivita] [char](3) NOT NULL,
	[ordine] [smallint] NULL,
 CONSTRAINT [PK_CODICI_AVANZAMENTO] PRIMARY KEY CLUSTERED 
(
	[COD_AVANZAMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
