/****** Object:  Table [dbo].[CODICI_PROBLEMATICHE]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CODICI_PROBLEMATICHE](
	[Cod_problematica] [char](5) NOT NULL,
	[Desc_problematica] [varchar](50) NOT NULL,
	[Cod_attivita] [char](3) NOT NULL,
 CONSTRAINT [PK_CODICI_PROBLEMATICHE] PRIMARY KEY CLUSTERED 
(
	[Cod_problematica] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
