/****** Object:  Table [dbo].[PROFILO_PIANI]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROFILO_PIANI](
	[tipo_piano] [char](2) NOT NULL,
	[id_attivita] [char](3) NOT NULL,
	[cod_avanzamento] [char](5) NULL,
	[qta_app] [smallint] NOT NULL,
	[tipo_app] [char](2) NULL,
	[ordine] [smallint] NULL,
 CONSTRAINT [PK_PROFILO_PIANI] PRIMARY KEY NONCLUSTERED 
(
	[tipo_piano] ASC,
	[id_attivita] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
CREATE CLUSTERED INDEX [IX_PROFILO_PIANI] ON [dbo].[PROFILO_PIANI] 
(
	[tipo_piano] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
GO
