/****** Object:  Table [dbo].[SOGGETTI_DEL_PIANO]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SOGGETTI_DEL_PIANO](
	[ID_PIANO] [char](10) NOT NULL,
	[ID_SOGGETTO] [char](10) NOT NULL,
	[FLAG] [char](2) NULL,
	[COD_AMM] [char](10) NULL,
	[flag_cez] [char](2) NULL,
	[lavorato_cez] [char](5) NULL,
 CONSTRAINT [PK_SOGGETTI_DEL_PIANO] PRIMARY KEY CLUSTERED 
(
	[ID_SOGGETTO] ASC,
	[ID_PIANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
