/****** Object:  Table [dbo].[SOGGETTI_IN_GESTIONE]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SOGGETTI_IN_GESTIONE](
	[ID_SOGGETTO] [char](10) NOT NULL,
	[DATA_TRASF] [datetime] NOT NULL,
	[DATA_IN_GIOCO] [datetime] NOT NULL,
	[ID_PIANO] [char](10) NOT NULL,
 CONSTRAINT [PK_SOGGETTI_IN_GESTIONE] PRIMARY KEY NONCLUSTERED 
(
	[ID_SOGGETTO] ASC,
	[ID_PIANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
CREATE CLUSTERED INDEX [IX_SOGGETTI_IN_GESTIONE] ON [dbo].[SOGGETTI_IN_GESTIONE] 
(
	[ID_SOGGETTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
GO
