/****** Object:  Table [dbo].[STORICO_SOGGETTI_IN_GESTIONE]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[STORICO_SOGGETTI_IN_GESTIONE](
	[ID_SOGGETTO] [char](10) NOT NULL,
	[DATA_TRASF] [datetime] NOT NULL,
	[DATA_IN_GIOCO] [datetime] NOT NULL,
	[ID_PIANO] [char](10) NOT NULL,
 CONSTRAINT [PK_STORICO_SOGGETTI_IN_GESTIONE] PRIMARY KEY CLUSTERED 
(
	[ID_SOGGETTO] ASC,
	[ID_PIANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
) ON [INDEX]
GO
SET ANSI_PADDING OFF
GO
