/****** Object:  Table [dbo].[ATTIVITA_PIANIFICATE]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATTIVITA_PIANIFICATE](
	[ID_PIANO] [char](10) NOT NULL,
	[ID_SOGGETTO] [char](10) NOT NULL,
	[ID_ATTIVITA] [char](3) NOT NULL,
	[INIZIO] [datetime] NULL,
	[FINE] [datetime] NULL,
	[STATO] [char](1) NULL,
	[qta_app] [smallint] NULL,
 CONSTRAINT [PK_ATTIVITA_PIANIFICATE] PRIMARY KEY CLUSTERED 
(
	[ID_PIANO] ASC,
	[ID_SOGGETTO] ASC,
	[ID_ATTIVITA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
