/****** Object:  Table [dbo].[STATO_AVANZAMENTO_CEZ]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[STATO_AVANZAMENTO_CEZ](
	[ID_PIANO] [char](10) NOT NULL,
	[ID_SOGGETTO] [char](10) NOT NULL,
	[PROGR_OPERAZIONE] [int] NOT NULL,
	[ID_ATTIVITA] [char](3) NOT NULL,
	[COD_AVANZAMENTO] [char](5) NOT NULL,
	[INIZIO] [datetime] NULL,
	[FINE] [datetime] NULL,
	[ORA_INIZIO] [datetime] NULL,
	[ORA_FINE] [datetime] NULL,
	[NOTE] [varchar](255) NULL,
	[COD_APPAR] [char](10) NULL,
	[VERBALE_COLLAUDO] [char](1) NULL,
	[DATA_INT_VERB] [datetime] NULL,
	[VALIDATO] [char](1) NULL,
	[COD_MANCATO_INT] [smallint] NULL,
	[FLAG_INS] [char](1) NULL,
 CONSTRAINT [PK_STATO_AVANZAMENTO_CEZ_1] PRIMARY KEY NONCLUSTERED 
(
	[ID_PIANO] ASC,
	[ID_SOGGETTO] ASC,
	[PROGR_OPERAZIONE] ASC,
	[ID_ATTIVITA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
CREATE CLUSTERED INDEX [IX_STATO_AVANZAMENTO_CEZ] ON [dbo].[STATO_AVANZAMENTO_CEZ] 
(
	[ID_PIANO] ASC,
	[ID_SOGGETTO] ASC,
	[ID_ATTIVITA] ASC,
	[COD_AVANZAMENTO] ASC,
	[FINE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_STATO_AVANZAMENTO_CEZ_2] ON [dbo].[STATO_AVANZAMENTO_CEZ] 
(
	[ID_PIANO] ASC,
	[ID_SOGGETTO] ASC,
	[PROGR_OPERAZIONE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_STATO_AVANZAMENTO_CEZ_3] ON [dbo].[STATO_AVANZAMENTO_CEZ] 
(
	[ID_PIANO] ASC,
	[ID_SOGGETTO] ASC,
	[PROGR_OPERAZIONE] ASC,
	[ID_ATTIVITA] ASC,
	[FINE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_STATO_AVANZAMENTO_CEZ_4] ON [dbo].[STATO_AVANZAMENTO_CEZ] 
(
	[ID_SOGGETTO] ASC,
	[PROGR_OPERAZIONE] ASC,
	[ID_ATTIVITA] ASC,
	[FINE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_STATO_AVANZAMENTO_CEZ_5] ON [dbo].[STATO_AVANZAMENTO_CEZ] 
(
	[ID_PIANO] ASC,
	[ID_SOGGETTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_STATO_AVANZAMENTO_CEZ_6] ON [dbo].[STATO_AVANZAMENTO_CEZ] 
(
	[ID_SOGGETTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_STATO_AVANZAMENTO_CEZ_7] ON [dbo].[STATO_AVANZAMENTO_CEZ] 
(
	[ID_PIANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [INDEX]
GO
