/****** Object:  ForeignKey [FK_PIANI_CODICI_PIANI]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[PIANI]  WITH CHECK ADD  CONSTRAINT [FK_PIANI_CODICI_PIANI] FOREIGN KEY([tipo_piano])
REFERENCES [dbo].[CODICI_PIANI] ([codice_tipo_piano])
GO
ALTER TABLE [dbo].[PIANI] CHECK CONSTRAINT [FK_PIANI_CODICI_PIANI]
GO
