/****** Object:  ForeignKey [FK_CODICI_AVANZAMENTO_ATTIVITA]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[CODICI_AVANZAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_CODICI_AVANZAMENTO_ATTIVITA] FOREIGN KEY([cod_attivita])
REFERENCES [dbo].[ATTIVITA] ([ID_ATTIVITA])
GO
ALTER TABLE [dbo].[CODICI_AVANZAMENTO] CHECK CONSTRAINT [FK_CODICI_AVANZAMENTO_ATTIVITA]
GO
