/****** Object:  ForeignKey [FK_legenda_CODICI_AVANZAMENTO]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[LEGENDA]  WITH NOCHECK ADD  CONSTRAINT [FK_legenda_CODICI_AVANZAMENTO] FOREIGN KEY([cod_avanzamento])
REFERENCES [dbo].[CODICI_AVANZAMENTO] ([COD_AVANZAMENTO])
GO
ALTER TABLE [dbo].[LEGENDA] CHECK CONSTRAINT [FK_legenda_CODICI_AVANZAMENTO]
GO
