/****** Object:  ForeignKey [FK_PROFILO_PIANI_ATTIVITA]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[PROFILO_PIANI]  WITH CHECK ADD  CONSTRAINT [FK_PROFILO_PIANI_ATTIVITA] FOREIGN KEY([id_attivita])
REFERENCES [dbo].[ATTIVITA] ([ID_ATTIVITA])
GO
ALTER TABLE [dbo].[PROFILO_PIANI] CHECK CONSTRAINT [FK_PROFILO_PIANI_ATTIVITA]
GO
