/****** Object:  ForeignKey [FK_PROFILO_PIANI_CODICI_AVANZAMENTO]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[PROFILO_PIANI]  WITH CHECK ADD  CONSTRAINT [FK_PROFILO_PIANI_CODICI_AVANZAMENTO] FOREIGN KEY([cod_avanzamento])
REFERENCES [dbo].[CODICI_AVANZAMENTO] ([COD_AVANZAMENTO])
GO
ALTER TABLE [dbo].[PROFILO_PIANI] CHECK CONSTRAINT [FK_PROFILO_PIANI_CODICI_AVANZAMENTO]
GO
