/****** Object:  ForeignKey [FK_PROBLEMATICHE_STATO_AVANZAMENTO]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[PROBLEMATICHE]  WITH NOCHECK ADD  CONSTRAINT [FK_PROBLEMATICHE_STATO_AVANZAMENTO] FOREIGN KEY([id_piano], [id_soggetto], [progr_operazione])
REFERENCES [dbo].[STATO_AVANZAMENTO] ([ID_PIANO], [ID_SOGGETTO], [PROGR_OPERAZIONE])
GO
ALTER TABLE [dbo].[PROBLEMATICHE] CHECK CONSTRAINT [FK_PROBLEMATICHE_STATO_AVANZAMENTO]
GO
