/****** Object:  ForeignKey [FK_SOGGETTI_DEL_PIANO_PIANI]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[SOGGETTI_DEL_PIANO]  WITH CHECK ADD  CONSTRAINT [FK_SOGGETTI_DEL_PIANO_PIANI] FOREIGN KEY([ID_PIANO])
REFERENCES [dbo].[PIANI] ([ID_PIANO])
GO
ALTER TABLE [dbo].[SOGGETTI_DEL_PIANO] CHECK CONSTRAINT [FK_SOGGETTI_DEL_PIANO_PIANI]
GO
