/****** Object:  ForeignKey [FK_STORICO_SOGGETTI_IN_GESTIONE_SOGGETTI_DEL_PIANO]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[STORICO_SOGGETTI_IN_GESTIONE]  WITH CHECK ADD  CONSTRAINT [FK_STORICO_SOGGETTI_IN_GESTIONE_SOGGETTI_DEL_PIANO] FOREIGN KEY([ID_SOGGETTO], [ID_PIANO])
REFERENCES [dbo].[SOGGETTI_DEL_PIANO] ([ID_SOGGETTO], [ID_PIANO])
GO
ALTER TABLE [dbo].[STORICO_SOGGETTI_IN_GESTIONE] CHECK CONSTRAINT [FK_STORICO_SOGGETTI_IN_GESTIONE_SOGGETTI_DEL_PIANO]
GO
