/****** Object:  ForeignKey [FK_NOTE_CEZ_FLAG_CEZ]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[NOTE_CEZ]  WITH CHECK ADD  CONSTRAINT [FK_NOTE_CEZ_FLAG_CEZ] FOREIGN KEY([flag_cez])
REFERENCES [dbo].[FLAG_CEZ] ([flag_cez])
GO
ALTER TABLE [dbo].[NOTE_CEZ] CHECK CONSTRAINT [FK_NOTE_CEZ_FLAG_CEZ]
GO
