/****** Object:  ForeignKey [FK_NOTE_CEZ_SOGGETTI_DEL_PIANO]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[NOTE_CEZ]  WITH CHECK ADD  CONSTRAINT [FK_NOTE_CEZ_SOGGETTI_DEL_PIANO] FOREIGN KEY([id_piano], [id_soggetto])
REFERENCES [dbo].[SOGGETTI_DEL_PIANO] ([ID_SOGGETTO], [ID_PIANO])
GO
ALTER TABLE [dbo].[NOTE_CEZ] CHECK CONSTRAINT [FK_NOTE_CEZ_SOGGETTI_DEL_PIANO]
GO
