/****** Object:  ForeignKey [FK_ATTIVITA_PIANIFICATE_ATTIVITA]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[ATTIVITA_PIANIFICATE]  WITH CHECK ADD  CONSTRAINT [FK_ATTIVITA_PIANIFICATE_ATTIVITA] FOREIGN KEY([ID_ATTIVITA])
REFERENCES [dbo].[ATTIVITA] ([ID_ATTIVITA])
GO
ALTER TABLE [dbo].[ATTIVITA_PIANIFICATE] CHECK CONSTRAINT [FK_ATTIVITA_PIANIFICATE_ATTIVITA]
GO
