/****** Object:  ForeignKey [FK_ATTIVITA_PIANIFICATE_SOGGETTI_DEL_PIANO]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[ATTIVITA_PIANIFICATE]  WITH CHECK ADD  CONSTRAINT [FK_ATTIVITA_PIANIFICATE_SOGGETTI_DEL_PIANO] FOREIGN KEY([ID_SOGGETTO], [ID_PIANO])
REFERENCES [dbo].[SOGGETTI_DEL_PIANO] ([ID_SOGGETTO], [ID_PIANO])
GO
ALTER TABLE [dbo].[ATTIVITA_PIANIFICATE] CHECK CONSTRAINT [FK_ATTIVITA_PIANIFICATE_SOGGETTI_DEL_PIANO]
GO
