/****** Object:  ForeignKey [FK_STATO_AVANZAMENTO_CEZ_ATTIVITA_PIANIFICATE]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[STATO_AVANZAMENTO_CEZ]  WITH CHECK ADD  CONSTRAINT [FK_STATO_AVANZAMENTO_CEZ_ATTIVITA_PIANIFICATE] FOREIGN KEY([ID_PIANO], [ID_SOGGETTO], [ID_ATTIVITA])
REFERENCES [dbo].[ATTIVITA_PIANIFICATE] ([ID_PIANO], [ID_SOGGETTO], [ID_ATTIVITA])
GO
ALTER TABLE [dbo].[STATO_AVANZAMENTO_CEZ] CHECK CONSTRAINT [FK_STATO_AVANZAMENTO_CEZ_ATTIVITA_PIANIFICATE]
GO
