/****** Object:  ForeignKey [FK_STATO_AVANZAMENTO_CEZ_CODICI_AVANZAMENTO]    Script Date: 11/17/2025 15:21:53 ******/
ALTER TABLE [dbo].[STATO_AVANZAMENTO_CEZ]  WITH CHECK ADD  CONSTRAINT [FK_STATO_AVANZAMENTO_CEZ_CODICI_AVANZAMENTO] FOREIGN KEY([COD_AVANZAMENTO])
REFERENCES [dbo].[CODICI_AVANZAMENTO] ([COD_AVANZAMENTO])
GO
ALTER TABLE [dbo].[STATO_AVANZAMENTO_CEZ] CHECK CONSTRAINT [FK_STATO_AVANZAMENTO_CEZ_CODICI_AVANZAMENTO]
GO
