/****** Object:  View [dbo].[V_ANAGRAFICA]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_ANAGRAFICA]

AS

SELECT 
LSR01A_KEY_ID_RICEV ID_LOTTO, 
LSR01A_COD_AMM ID_AMM,
lsr01a_decod_ricev DENOMINAZIONE, 
lsr01a_indirizzo INDIRIZZO, 
lsr01a_comune_ricev COMUNE, 
lsr01a_prov_ricev PROVINCIA, 
lsr01a_cap CAP, 
lsr01a_cognome COGNOME, 
lsr01a_nome NOME, 
lsr01a_tel_ricevitoria TEL_RICEV, 
lsr01a_tel_casa TEL_CASA,

CASE LSR01A_PROV_RICEV 
WHEN 'AG' THEN 'AGRIGENTO'
WHEN 'AL' THEN 'ALESSANDRIA'
WHEN 'AN' THEN 'ANCONA'
WHEN 'AO' THEN 'AOSTA'
WHEN 'AP' THEN 'ASCOLI PICENO'
WHEN 'AQ' THEN 'L''AQUILA'
WHEN 'AR' THEN 'AREZZO'
WHEN 'AT' THEN 'ASTI'
WHEN 'AV' THEN 'AVELLINO'
WHEN 'BA' THEN 'BARI'
WHEN 'BG' THEN 'BERGAMO'
WHEN 'BI' THEN 'BIELLA'
WHEN 'BL' THEN 'BELLUNO'
WHEN 'BN' THEN 'BENEVENTO'
WHEN 'BO' THEN 'BOLOGNA'
WHEN 'BR' THEN 'BRINDISI'
WHEN 'BS' THEN 'BRESCIA'
WHEN 'BZ' THEN 'BOLZANO'
WHEN 'CA' THEN 'CAGLIARI'
WHEN 'CB' THEN 'CAMPOBASSO'
WHEN 'CE' THEN 'CASERTA'
WHEN 'CH' THEN 'CHIETI'
WHEN 'CL' THEN 'CALTANISSETTA'
WHEN 'CN' THEN 'CUNEO'
WHEN 'CO' THEN 'COMO'
WHEN 'CR' THEN 'CREMONA'
WHEN 'CS' THEN 'COSENZA'
WHEN 'CT' THEN 'CATANIA'
WHEN 'CZ' THEN 'CATANZARO'
WHEN 'EN' THEN 'ENNA'
WHEN 'FE' THEN 'FERRARA'
WHEN 'FG' THEN 'FOGGIA'
WHEN 'FI' THEN 'FIRENZE'
WHEN 'FO' THEN 'FORLì'
WHEN 'FR' THEN 'FROSINONE'
WHEN 'GE' THEN 'GENOVA'
WHEN 'GO' THEN 'GORIZIA'
WHEN 'GR' THEN 'GROSSETO'
WHEN 'IM' THEN 'IMPERIA'
WHEN 'IS' THEN 'ISERNIA'
WHEN 'KR' THEN 'CROTONE'
WHEN 'LC' THEN 'LECCO'
WHEN 'LE' THEN 'LECCE'
WHEN 'LI' THEN 'LIVORNO'
WHEN 'LO' THEN 'LODI'
WHEN 'LT' THEN 'LATINA'
WHEN 'LU' THEN 'LUCCA'
WHEN 'MC' THEN 'MACERATA'
WHEN 'ME' THEN 'MESSINA'
WHEN 'MI' THEN 'MILANO'
WHEN 'MN' THEN 'MANTOVA'
WHEN 'MO' THEN 'MODENA'
WHEN 'MS' THEN 'MASSA CARRARA'
WHEN 'MT' THEN 'MATERA'
WHEN 'NA' THEN 'NAPOLI'
WHEN 'NO' THEN 'NOVARA'
WHEN 'OR' THEN 'ORISTANO'
WHEN 'PA' THEN 'PALERMO'
WHEN 'PC' THEN 'PIACENZA'
WHEN 'PD' THEN 'PADOVA'
WHEN 'PE' THEN 'PESCARA'
WHEN 'PG' THEN 'PERUGIA'
WHEN 'PI' THEN 'PISA'
WHEN 'PN' THEN 'PORDENONE'
WHEN 'PO' THEN 'PRATO'
WHEN 'PR' THEN 'PARMA'
WHEN 'PS' THEN 
CASE
	WHEN LSR01A_CAP = '61100' THEN 'PESARO'
	WHEN LSR01A_CAP = '61029' THEN 'URBINO'
END
WHEN 'PT' THEN 'PISTOIA'
WHEN 'PU' THEN 
CASE
	WHEN LSR01A_CAP = '61100' THEN 'PESARO'
	WHEN LSR01A_CAP = '61029' THEN 'URBINO'
END
WHEN 'PV' THEN 'PAVIA'
WHEN 'PZ' THEN 'POTENZA'
WHEN 'RA' THEN 'RAVENNA'
WHEN 'RC' THEN 
CASE 
	WHEN ISNUMERIC(LSR01A_KEY_ID_RICEV) = 0 THEN 'REGGIO DI CALABRIA'
	ELSE 'REGGIO CALABRIA'
END
WHEN 'RE' THEN 
CASE 
	WHEN ISNUMERIC(LSR01A_KEY_ID_RICEV) = 0 THEN 'REGGIO NELL''EMILIA'
	ELSE 'REGGIO EMILIA'
END
WHEN 'RG' THEN 'RAGUSA'
WHEN 'RI' THEN 'RIETI'
WHEN 'RM' THEN 'ROMA'
WHEN 'RN' THEN 'RIMINI'
WHEN 'RO' THEN 'ROVIGO'
WHEN 'SA' THEN 'SALERNO'
WHEN 'SI' THEN 'SIENA'
WHEN 'SO' THEN 'SONDRIA'
WHEN 'SP' THEN 'LA SPEZIA'
WHEN 'SR' THEN 'SIRACUSA'
WHEN 'SS' THEN 'SASSARI'
WHEN 'SV' THEN 'SAVONA'
WHEN 'TA' THEN 'TARANTO'
WHEN 'TE' THEN 'TERAMO'
WHEN 'TN' THEN 'TRENTO'
WHEN 'TO' THEN 'TORINO'
WHEN 'TP' THEN 'TRAPANI'
WHEN 'TR' THEN 'TERNI'
WHEN 'TS' THEN 'TRIESTE'
WHEN 'TV' THEN 'TREVISO'
WHEN 'UD' THEN 'UDINE'
WHEN 'VA' THEN 'VARESE'
WHEN 'VB' THEN 'VERBANIA'
WHEN 'VC' THEN 'VERCELLI'
WHEN 'VE' THEN 'VENEZIA'
WHEN 'VI' THEN 'VICENZA'
WHEN 'VR' THEN 'VERONA'
WHEN 'VT' THEN 'VITERBO'
WHEN 'VV' THEN 'VIBO VALENTIA'
END DESC_PROVINCIA
FROM CONDIVISO.DBO.LSR01A
GO
