/****** Object:  View [dbo].[Giocate_e_annullate_lotto_da_DBDAF]    Script Date: 11/17/2025 15:21:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE VIEW [dbo].[Giocate_e_annullate_lotto_da_DBDAF]
AS
SELECT     COD_LOTTOMATICA, TERMINALE, NUM_EMESSE_LOTTO, NUM_ANNULLATE_LOTTO,DATA_CONT, TOT_INCASSATE_LOTTO,TOT_ANNULLATE_LOTTO
FROM         DBDaf.dbo.LCS02A_INCASSATO_LOTTO
GO
