/****** Object:  Table [dbo].[lsrgen_BACKUP]    Script Date: 11/17/2025 15:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[lsrgen_BACKUP](
	[LSRGEN_COD_LTM] [char](6) NOT NULL,
	[LSRGEN_COD_AMM] [char](6) NULL,
	[LSRGEN_DATA_DECOR] [char](8) NULL,
	[LSRGEN_DATA_DECOR_al] [char](8) NULL,
	[LSRGEN_COGNOME] [char](24) NULL,
	[LSRGEN_NOME] [char](20) NULL,
	[LSRGEN_TIPO_PROVV] [char](1) NULL,
	[LSRGEN_DATA_PROVV] [char](8) NULL,
	[LSRGEN_DATA_NASCITA] [char](8) NULL,
	[LSRGEN_COMUNE_NASCITA] [char](30) NULL,
	[LSRGEN_PROVINCIA_NASCITA] [char](2) NULL,
	[LSRGEN_CODICE_FISCALE] [char](17) NULL,
	[lsrgen_decod_ricev] [varchar](50) NULL,
	[LSRGEN_INDIRIZZO_RIC] [char](40) NULL,
	[LSRGEN_COMUNE_RIC] [char](24) NULL,
	[LSRGEN_CAP_RIC] [char](5) NULL,
	[LSRGEN_PROV_RIC] [char](2) NULL,
	[LSRGEN_ISPETT_RIC] [char](2) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
