/****** Object:  Table [dbo].[S2T_valori_default]    Script Date: 11/17/2025 15:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[S2T_valori_default](
	[campo] [varchar](30) NOT NULL,
	[valore_default] [varchar](1000) NOT NULL,
 CONSTRAINT [PK_S2T_valori_default] PRIMARY KEY CLUSTERED 
(
	[campo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
