/****** Object:  Table [dbo].[DIAMANTE_NUOVE]    Script Date: 11/17/2025 15:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DIAMANTE_NUOVE](
	[DIAMANTE_KEY_ID_RICEV] [char](6) NOT NULL,
	[BOLLO_FLAG] [char](10) NULL,
	[F101_FLAG] [char](10) NULL,
	[TRIS_FLAG] [char](10) NULL,
	[RICARICHE_FLAG] [char](10) NULL,
	[LOTTO_FLAG] [char](10) NULL,
	[BOLLO_EMESSE] [int] NULL,
	[LOTTO_EMESSE] [int] NULL,
	[RICARICHE_EMESSE] [int] NULL,
	[F101_EMESSE] [int] NULL,
	[TRIS_EMESSE] [int] NULL,
	[TRIS_CONTRATTO] [char](1) NULL,
	[TRIS_FIDEJUSSIONE] [char](1) NULL,
	[TRIS_PS] [char](1) NULL,
	[F101_CONTRATTO] [char](1) NULL,
	[F101_FIDEJUSSIONE] [char](1) NULL,
	[F101_CONTRATTO_ASSOCIAZIONE] [char](1) NULL,
	[F101_PS] [char](1) NULL,
	[BOLLO_CONTRATTO] [char](1) NULL,
	[BOLLO_ADESIONE] [char](1) NULL,
	[ESITO] [char](1) NULL,
	[DATA_ESITO] [char](8) NULL,
	[PIANO_ATTIVAZIONE] [char](5) NULL,
	[UTENTE_ESITO] [char](10) NULL,
	[FLAG_LOCK] [char](1) NULL,
	[NOTE] [char](255) NULL,
	[FLAG_ATTIVA] [char](1) NULL,
	[ID_TRIS_CONTRATTO] [char](16) NULL,
	[ID_TRIS_FIDEJUSSIONE] [char](16) NULL,
	[ID_TRIS_PS] [char](16) NULL,
	[ID_F101_CONTRATTO] [char](16) NULL,
	[ID_F101_FIDEJUSSIONE] [char](16) NULL,
	[ID_F101_CONTRATTO_ASSOCIAZIONE] [char](16) NULL,
	[ID_F101_PS] [char](16) NULL,
	[ID_BOLLO_CONTRATTO] [char](16) NULL,
	[ID_BOLLO_ADESIONE] [char](16) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
