/****** Object:  Table [dbo].[lfb06a_conc]    Script Date: 11/17/2025 15:18:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[lfb06a_conc](
	[lfb06a_conc_key_id] [char](2) NOT NULL,
	[lfb06a_conc_value] [char](5) NOT NULL,
 CONSTRAINT [PK_lfb06a_conc] PRIMARY KEY CLUSTERED 
(
	[lfb06a_conc_key_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
