/****** Object:  Table [dbo].[RMF_MODULE_PARAMETER_LOG]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RMF_MODULE_PARAMETER_LOG](
	[MODULE_LOG_NO] [int] NULL,
	[PHYSICAL_MODULE_NO] [int] NULL,
	[LOGICAL_MODULE_NO] [int] NULL,
	[PARAMETER_NO] [int] NULL,
	[PARAMETER_VALUE] [nvarchar](255) NULL,
	[PARAMETER_BINARY_VALUE] [nvarchar](255) NULL,
	[IS_NEGATED] [nvarchar](255) NULL,
	[FILE_DATA_CARICAMENTO] [varchar](50) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
