/****** Object:  Table [dbo].[RMF_MODULE_MESSAGE_TEXT_LOG]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RMF_MODULE_MESSAGE_TEXT_LOG](
	[MODULE_LOG_NO] [int] NULL,
	[MODULE_EVENT_NO] [int] NULL,
	[MODULE_MESSAGE_NO] [int] NULL,
	[MODULE_MESSAGE_TEXT_NO] [int] NULL,
	[PARAMETER_NO] [nvarchar](255) NULL,
	[OBJECT_ID] [nvarchar](255) NULL,
	[MODULE_MESSAGE_TEXT] [nvarchar](255) NULL,
	[FILE_DATA_CARICAMENTO] [varchar](50) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
