/****** Object:  Table [dbo].[RMF_MODULE_MESSAGE_LOG]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RMF_MODULE_MESSAGE_LOG](
	[MODULE_LOG_NO] [int] NULL,
	[MODULE_EVENT_NO] [int] NULL,
	[MODULE_MESSAGE_NO] [int] NULL,
	[EXCEPTION_NO] [int] NULL,
	[SEVERITY_CODE_TYPE] [int] NULL,
	[SEVERITY_CODE_NO] [int] NULL,
	[EXCEPTION_DATE] [nvarchar](255) NULL,
	[MODULE_NAME] [nvarchar](255) NULL,
	[ROUTINE_NAME] [nvarchar](255) NULL,
	[EXCEPTION_POSITION] [nvarchar](255) NULL,
	[FILE_DATA_CARICAMENTO] [nvarchar](255) NULL
) ON [DATA]
GO
