/****** Object:  Table [dbo].[APPO_FID]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[APPO_FID](
	[COD_LOTT] [char](6) NULL,
	[ID_SOC] [char](2) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
