/****** Object:  Table [dbo].[lsr3ann]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[lsr3ann](
	[RICEVITORIA] [char](6) NULL,
	[DATA_ANNULL] [char](8) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
