/****** Object:  Table [dbo].[TAB_RIF_FIDE]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TAB_RIF_FIDE](
	[Cod_Prodotto] [char](2) NOT NULL,
	[AnnoRif] [char](4) NOT NULL,
 CONSTRAINT [PK_TAB_RIF_FIDE] PRIMARY KEY CLUSTERED 
(
	[Cod_Prodotto] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
