/****** Object:  Table [dbo].[TMP_RMF]    Script Date: 11/17/2025 15:18:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TMP_RMF](
	[ID_NUM] [int] IDENTITY(0,1) NOT NULL,
	[TIPO] [varchar](1) NOT NULL,
	[RMF] [char](330) NULL
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
