/****** Object:  Table [dbo].[ParCentroDiCosto]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ParCentroDiCosto](
	[IdParCDC] [int] IDENTITY(1,1) NOT NULL,
	[TextCDC] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdParCDC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
