/****** Object:  Table [dbo].[LOTTO_STATSPARCO]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOTTO_STATSPARCO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REGIONE] [nvarchar](50) NULL,
	[MODELLO] [nvarchar](250) NULL,
	[INMEDIO] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
