/****** Object:  Table [dbo].[LOTTO_ODARDA_OLD]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOTTO_ODARDA_OLD](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdentificativoProv] [nvarchar](50) NULL,
	[ODA] [nvarchar](50) NULL,
	[RDA] [nvarchar](50) NULL,
	[DataMod] [smalldatetime] NULL,
 CONSTRAINT [PK_LOTTO_ODARDA] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
