/****** Object:  Table [dbo].[LOTTO_MODELLOMASTER]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOTTO_MODELLOMASTER](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MODELLOMASTER] [nvarchar](250) NULL,
	[MODELLO_AWP] [nvarchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
