/****** Object:  Table [dbo].[LOTTO_LOC]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOTTO_LOC](
	[IdLottoLOC] [int] IDENTITY(1,1) NOT NULL,
	[CODICE_ESERCENTE] [varchar](100) NULL,
	[CODICE_GESTORE] [varchar](100) NULL,
	[PARTITA_IVA_ESERCENTE] [varchar](100) NULL,
	[DENOMINAZIONE_ESERCIZIO] [varchar](100) NULL,
	[VESE_ESERCIZIO] [varchar](100) NULL,
	[TIPOLOGIA_LOCALE_ESERCIZIO] [varchar](100) NULL,
	[CERTIFICAZIONE_AAMS_ESERCIZIO] [varchar](20) NULL,
	[MAX_AWP_INSTALLABILI] [float] NULL,
	[DATA_CERTIFICAZIONE_ESERCIZIO] [smalldatetime] NULL,
	[INDIRIZZO_ESERCIZIO] [varchar](250) NULL,
	[CAP_ESERCIZIO] [varchar](10) NULL,
	[COMUNE_ESERCIZIO] [varchar](200) NULL,
	[PROVINCIA_ESERCIZIO] [varchar](10) NULL,
	[TELEFONO1_ESERCIZIO] [varchar](100) NULL,
	[TELEFONO2_ESERCIZIO] [varchar](100) NULL,
	[MQ] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdLottoLOC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
