/****** Object:  Table [dbo].[LOTTO_CONT_MONTH_202007]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOTTO_CONT_MONTH_202007](
	[IdLottoIMP] [int] IDENTITY(1,1) NOT NULL,
	[CODE_ID_AWP] [varchar](50) NULL,
	[DATA_CONTATORI_ULTIMA_TELEMATICA] [datetime] NULL,
	[CNTTOTIN_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[CNTTOTOT_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[VESE_ESERCIZIO] [varchar](100) NULL,
	[DATA_DEL_GIORNO] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdLottoIMP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
