/****** Object:  Table [dbo].[LOTTO_CONT_DAY_20200929]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOTTO_CONT_DAY_20200929](
	[IdLottoIMP] [int] IDENTITY(1,1) NOT NULL,
	[CODE_ID_AWP] [varchar](50) NULL,
	[VESE_ESERCIZIO] [varchar](100) NULL,
	[PRIMO_STATO_AWP] [varchar](200) NULL,
	[DATA_ATTIVAZIONE_AWP] [datetime] NULL,
	[SECONDO_STATO_AWP] [varchar](200) NULL,
	[INIZIO_BLOCCO_AWP] [datetime] NULL,
	[FINE_BLOCCO_AWP] [datetime] NULL,
	[STATO_MSG_724] [varchar](400) NULL,
	[DATA_INVIO_MSG_724] [datetime] NULL,
	[ULTIMA_PROC_AMM] [varchar](400) NULL,
	[DATA_RICHIESTA_PROC_AMM] [datetime] NULL,
	[DATA_EVENTO_PROC_AMM] [datetime] NULL,
	[STATO_LAVORAZIONE_PROC_AMM] [varchar](400) NULL,
	[ULTIMA_MOVIMENTAZIONE_AWP] [datetime] NULL,
	[CODICE_MOVIMENTAZIONE_AWP] [varchar](200) NULL,
	[DATA_CNT_ULTIMA_MOVIM] [datetime] NULL,
	[CNTTOTIN_ULTIMA_MOV] [float] NULL,
	[CNTTOTOT_ULTIMA_MOV] [float] NULL,
	[CNTCL_ULTIMA_MOV] [float] NULL,
	[CNTIN_ULTIMA_MOV] [float] NULL,
	[CNTOT_ULTIMA_MOV] [float] NULL,
	[CNTNP_ULTIMA_MOV] [float] NULL,
	[COD_CONTRATTO_GESTORE] [varchar](200) NULL,
	[CONTRATTO_GESTORE] [varchar](200) NULL,
	[SUBCONTRATTO_GESTORE] [varchar](200) NULL,
	[PARAMETRI_CONTR_GEST] [varchar](200) NULL,
	[COD_CONTRATTO_ESERCIZIO] [varchar](200) NULL,
	[CONTRATTO_ESERCIZIO] [varchar](200) NULL,
	[PARAMETRI_CONTR_ESE] [varchar](200) NULL,
	[MAC_ADDRESS_PDA] [varchar](200) NULL,
	[MODELLO_PDA] [varchar](200) NULL,
	[STATO_PDA] [varchar](200) NULL,
	[DATA_ULTIMO_COLLEGAMENTO] [datetime] NULL,
	[DATA_INVIO_ULTIMA_TELEMATICA] [datetime] NULL,
	[ESITO_AAMS_ULTIMA_TELEMATICA] [varchar](100) NULL,
	[COD_MOTIVO_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[ERRORE_AAMS_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[DATA_CONTATORI_ULTIMA_TELEMATICA] [datetime] NULL,
	[CNTTOTIN_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[CNTTOTOT_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[CNTCL_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[CNTIN_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[CNTOT_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[CNTNP_ULTIMA_TELEMATICA] [varchar](200) NULL,
	[DATA_INVIO_ULTIMO_SPONTANEO] [datetime] NULL,
	[CODICE_PDA_ULTIMO_SPONTANEO] [varchar](200) NULL,
	[DATA_CONTATORI_ULTIMO_SPONTANEO] [datetime] NULL,
	[ESITO_COMUNICAZIONE_113] [varchar](100) NULL,
	[CNTTOTIN_ULTIMO_SPONTANEO] [float] NULL,
	[CNTTOTOT_ULTIMO_SPONTANEO] [float] NULL,
	[CNTCL_ULTIMO_SPONTANEO] [float] NULL,
	[CNTIN_ULTIMO_SPONTANEO] [float] NULL,
	[CNTOT_ULTIMO_SPONTANEO] [float] NULL,
	[CNTNP_ULTIMO_SPONTANEO] [float] NULL,
	[DATA_ULTIMO_002] [datetime] NULL,
	[DATA_DEL_GIORNO] [datetime] NULL,
	[GIORNI_SOSP_ACCUMULATI] [int] NULL,
	[GIORNI_SOSP_RESIDUI] [int] NULL,
	[GIORNI_ESERCIZIO_NECESSARI] [int] NULL,
	[ORIGINE_DATO_DECADENZA] [varchar](100) NULL,
	[BLOCCO_PREU] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdLottoIMP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
