/****** Object:  Table [dbo].[LOTTO_CONFIG]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOTTO_CONFIG](
	[IdLottoConfig] [int] IDENTITY(1,1) NOT NULL,
	[CODICE_GESTORE] [int] NULL,
	[DENOMINAZIONE_GESTORE] [varchar](250) NULL,
	[BIZMACRO] [int] NULL,
	[bEscludiImport] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdLottoConfig] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
