/****** Object:  Table [dbo].[LOTTO_AWP]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOTTO_AWP](
	[IdLottoAWP] [int] IDENTITY(1,1) NOT NULL,
	[DENOMINAZIONE_GESTORE] [varchar](400) NULL,
	[CODICE_GESTORE] [int] NULL,
	[DENOMINAZIONE_PROPRIETARIO] [varchar](200) NULL,
	[CODE_ID_AWP] [varchar](50) NULL,
	[CODE_ID_AWP_DEF] [varchar](50) NULL,
	[CODE_ID_AWP_PROVV] [varchar](50) NULL,
	[TIPOLOGIA_AWP] [varchar](50) NULL,
	[MODELLO_AWP] [varchar](250) NULL,
	[CODICE_MODELLO_AWP] [varchar](250) NULL,
	[NULLA_OSTA_AWP] [varchar](400) NULL,
	[DATA_NULLA_OSTA_AWP] [smalldatetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdLottoAWP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
