/****** Object:  Table [dbo].[ELENCO_PROVINCE]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ELENCO_PROVINCE](
	[PROVINCIA] [varchar](255) NOT NULL,
	[SIGLA] [varchar](6) NULL,
	[REGIONE] [varchar](255) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
