/****** Object:  Table [dbo].[AloParemeters_User]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AloParemeters_User](
	[IdAloUser] [int] IDENTITY(1,1) NOT NULL,
	[FkParameters] [int] NULL,
	[FkUserPar] [int] NULL,
	[AloDataUser] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdAloUser] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
