/****** Object:  Table [dbo].[CAMBIA_MICROHARD_Storico]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CAMBIA_MICROHARD_Storico](
	[Pk] [int] IDENTITY(1,1) NOT NULL,
	[Fk] [int] NULL,
	[sn] [varchar](80) NULL,
	[vendor] [varchar](80) NULL,
	[giorno] [smalldatetime] NULL,
	[firstupdate] [smalldatetime] NULL,
	[lastupdate] [smalldatetime] NULL,
	[sData_Lettura] [varchar](80) NULL,
	[sBanconote_Entrate] [float] NULL,
	[sBanconote_Uscite] [float] NULL,
	[sMonete_Entrate] [float] NULL,
	[sMonete_Uscite] [float] NULL,
	[sTaglio_Valore01] [float] NULL,
	[sTaglio_Entrate01] [float] NULL,
	[sTaglio_Uscite01] [float] NULL,
	[sTaglio_Valore02] [float] NULL,
	[sTaglio_Entrate02] [float] NULL,
	[sTaglio_Uscite02] [float] NULL,
	[sTaglio_Valore03] [float] NULL,
	[sTaglio_Entrate03] [float] NULL,
	[sTaglio_Uscite03] [float] NULL,
	[sTaglio_Valore04] [float] NULL,
	[sTaglio_Entrate04] [float] NULL,
	[sTaglio_Uscite04] [float] NULL,
	[sTaglio_Valore05] [float] NULL,
	[sTaglio_Entrate05] [float] NULL,
	[sTaglio_Uscite05] [float] NULL,
	[sTaglio_Valore06] [float] NULL,
	[sTaglio_Entrate06] [float] NULL,
	[sTaglio_Uscite06] [float] NULL,
	[sTaglio_Valore07] [float] NULL,
	[sTaglio_Entrate07] [float] NULL,
	[sTaglio_Uscite07] [float] NULL,
	[sTaglio_Valore08] [float] NULL,
	[sTaglio_Entrate08] [float] NULL,
	[sTaglio_Uscite08] [float] NULL,
	[sTaglio_Valore09] [float] NULL,
	[sTaglio_Entrate09] [float] NULL,
	[sTaglio_Uscite09] [float] NULL,
	[sTaglio_Valore10] [float] NULL,
	[sTaglio_Entrate10] [float] NULL,
	[sTaglio_Uscite10] [float] NULL,
	[Data_Lettura] [varchar](80) NULL,
	[Banconote_Entrate] [float] NULL,
	[Banconote_Uscite] [float] NULL,
	[Monete_Entrate] [float] NULL,
	[Monete_Uscite] [float] NULL,
	[Taglio_Valore01] [float] NULL,
	[Taglio_Entrate01] [float] NULL,
	[Taglio_Uscite01] [float] NULL,
	[Taglio_Valore02] [float] NULL,
	[Taglio_Entrate02] [float] NULL,
	[Taglio_Uscite02] [float] NULL,
	[Taglio_Valore03] [float] NULL,
	[Taglio_Entrate03] [float] NULL,
	[Taglio_Uscite03] [float] NULL,
	[Taglio_Valore04] [float] NULL,
	[Taglio_Entrate04] [float] NULL,
	[Taglio_Uscite04] [float] NULL,
	[Taglio_Valore05] [float] NULL,
	[Taglio_Entrate05] [float] NULL,
	[Taglio_Uscite05] [float] NULL,
	[Taglio_Valore06] [float] NULL,
	[Taglio_Entrate06] [float] NULL,
	[Taglio_Uscite06] [float] NULL,
	[Taglio_Valore07] [float] NULL,
	[Taglio_Entrate07] [float] NULL,
	[Taglio_Uscite07] [float] NULL,
	[Taglio_Valore08] [float] NULL,
	[Taglio_Entrate08] [float] NULL,
	[Taglio_Uscite08] [float] NULL,
	[Taglio_Valore09] [float] NULL,
	[Taglio_Entrate09] [float] NULL,
	[Taglio_Uscite09] [float] NULL,
	[Taglio_Valore10] [float] NULL,
	[Taglio_Entrate10] [float] NULL,
	[Taglio_Uscite10] [float] NULL,
	[VersioneFw] [varchar](80) NULL,
	[ResetMovimenti] [varchar](80) NULL,
	[UltimaConfigurazione] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[Pk] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
