/****** Object:  Table [dbo].[QRY_Filter]    Script Date: 11/17/2025 15:15:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[QRY_Filter](
	[IdFilter] [int] IDENTITY(1,1) NOT NULL,
	[FkReport] [int] NULL,
	[Titolo] [varchar](50) NULL,
	[Tag] [varchar](250) NULL,
	[Tipo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdFilter] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DATA]
) ON [DATA]
GO
SET ANSI_PADDING OFF
GO
