name: Test Custom Action

on:
  push:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Usa la custom action
        uses: ./actions/hello-test
        with:
          name: "Abdolhadi"